### ISSUE TITLE
Parenthesis matching matches incorrectly in edit mode of vim mode

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/rstudio#4152] opened 2019-01-12 23:35 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1060
    OS Version      :  Debian Stretch (4.9.130-2)
    R Version       : 3.5.2

### Steps to reproduce the problem
1. In a code editor type foo(bar(baz))
2. In edit mode of vim mode, move the red box onto the last parenthesis in the text
3. Observe that the open parenthesis immediately after 'bar' is highlighted
### Describe the problem in detail
-
### Describe the behavior you expected
Parenthesis immediately after 'foo' should be highlighted.

**Comment by ronblum** [comment] 2019-01-14 16:30
@MilesMcBain Thank you for reporting the issue. Can you describe what happens if you add a space and move the cursor onto it? I'm trying to reproduce this issue on Windows and Mac as well, and what I see is that the parentheses match when moving the cursor one past the closing parens.

**Comment by kevinushey** [comment] 2019-01-14 19:02
FWIW I reported this upstream a while back: https://github.com/ajaxorg/ace/issues/2302

**Comment by MilesMcBain** [comment] 2019-01-14 20:04
Hi @ronblum I see the same thing re moving to a space following. Most of the time one would not have a whitespace following a bracket more likely end of line.

Thanks for letting me know @kevinushey.

**Comment by ronblum** [comment] 2019-01-15 14:03
@MilesMcBain Oh, yes, I agree. I just wanted to see if at least we're getting the same misbehavior all around.

**Comment by jmcphers** [comment] 2020-02-12 00:48
Nothing for us to do here besides wait for the upstream fix (looks like it's still pending as of today, 2020-02-11)

**Comment by HHalva** [comment] 2021-09-06 19:15
I still see this issue, any fix coming?

**Comment by ronblum** [comment] 2021-09-10 12:56
@HHalva This is dependent on an upstream fix, which is still unresolved: https://github.com/ajaxorg/ace/issues/2302

**Comment by ronblum** [comment] 2022-06-03 14:14
@dvg-p4 Thanks! I'll reopen the issue, since it closed automatically.

@jgutman Is this just a matter of updating our version of Ace?

**Comment by dvg-p4** [comment] 2022-07-28 14:52
Any update on this?

**Comment by ronblum** [comment] 2022-07-28 17:31
@kevinushey What do you think—it looks like the latest version of Ace would help?

**Comment by kevinushey** [comment] 2022-07-28 17:44
Yes, I think we could get this fix if we updated Ace (or, for a more lightweight fix, we could just pull the fix into our fork). @romainfrancois, do you think either of these approaches are worth approaching / would you have time to take a look?

**Comment by romainfrancois** [comment] 2022-08-24 14:38
That would be an opportunity to learn how to upgrade our ace.

**Comment by kevinushey** [comment] 2022-08-24 17:28
FWIW the (intended) approach for these upgrades is something like:

1. Create a new branch off of the Ace release (or commit) that we want to fork off,
2. Review and apply existing Ace patches from the previous branch one-by-one as necessary (since some patches may, in theory, already have fixes upstream)
3. Update RStudio to use the newly-updated branch.

**Comment by dvg-p4** [comment] 2024-03-18 17:45
Are there any plans to do this ACE update for RStudio? I'd offer to make a PR but it sounds like this probably needs some institutional knowledge and/or git permissions to pull off.

**Comment by kevinushey** [comment] 2024-03-18 18:17
> Are there any plans to do this ACE update for RStudio? I'd offer to make a PR but it sounds like this probably needs some institutional knowledge and/or git permissions to pull off.

We actually did pull in an Ace update for this release, but that didn't seem to fix the issue here (perhaps related to the myriad of patches we've already applied?). I've applied a small patch to Ace that should ensure this is now appropriately resolved now.

**Comment by ronblum** [comment] 2024-03-19 20:21
Verified in Posit Workbench 2024.04.0-daily+609.pro1 on Ubuntu 22.04 via Chrome on MacOS 14.4.

**Comment by ronblum** [comment] 2024-03-20 12:44
Verified in RStudio Desktop 2024.04.0-daily+624 on MacOS 14.4.

![Image](https://github.com/rstudio/rstudio/assets/31009952/b0263b1b-dd4a-446b-9bf9-15a20a2c67d6)

**Closed by ronblum** 2024-03-20 12:44 UTC
Labels: bug, ace
