### ISSUE TITLE
Changes to environment very slow when large `sf` object is loaded.

### ISSUE THREAD

**Issue by dblodgett-usgs** [rstudio/rstudio#12908] opened 2023-03-25 15:38 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version :  2023.03.0+386
    OS Version      :  Windows 10  21H2
    R Version       :  4.2.2

### Steps to reproduce the problem

```r
sessionInfo()
options(timeout = 60000)
u <- "https://prod-is-usgs-sb-prod-publish.s3.amazonaws.com/641f0b82d34e807d39b8a1c1/sample_very_large_sf.rds"
f <- tempfile(fileext = ".rds")
download.file(u, f, mode = "wb")

test <- readRDS(f)

x <- 1

# observe very slow response when removing x
rm(x)

# also notice that operations that mutate the environment are SLOW
test2 <- test[1:100, ]
rm(test2)

# operations that mutate existing data are not slow?
test$test <- sample(1:10, nrow(test), replace = TRUE)
```

```r
> sessionInfo()

R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.2   cli_3.6.0        tools_4.2.2      withr_2.5.0      fs_1.6.0        
 [6] glue_1.6.2       rstudioapi_0.14  reprex_2.0.2     lifecycle_1.0.3  rlang_1.0.6.9000
```

Also note an error emitted while typing out the `[1:100, ]` part of the below.
```
test2 <- test[1:100, ]

Error in order(typeScores, scores) : argument lengths differ
In addition: Warning message:
In completions$type == .rs.acCompletionTypes$DATAFRAME & !completions$context %in%  :
  longer object length is not a multiple of shorter object length
```

I also notice that after running the reprex, the RStudio download monitor process name remains in Task Manager and is the process that is thrashing when the environment changes... This is likely unrelated, but was an odd observation worth noting.

### Describe the problem in detail

I updated to the new rstudio and have found that, when I have large `sf` data.frames loaded - the one in the sample triggers the issue - rstudio thrashes the RStudio R Session process every time the environment is modified. Watching Task Manager, I see that process hammering a CPU for a couple seconds every time I execute code that touches the R environment. I've verified that the same does not occur in a R session run outside of RStudio. My suspicion is that this is related to #12895 but I've not attempted to use the viewer on these data.frames.

### Describe the behavior you expected

In prior versions of sf, performance has been satisfactory with data this large in the environment. I can confirm that downgrading to RStudio 2022.12.0 fixes the slowness. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by stibu81** [comment] 2023-03-28 10:46
I can confirm this problem with a different setup:

    RStudio Edition :  Server
    RStudio Version :  2023.03.0+386 "Cherry Blossom"
    OS Version      :  Ubuntu 20.04.6 LTS
    R Version       :  4.2.3

RStudio reacts very slowly already for much smaller `sf` objects than the one in the original post.

As long as this `sf` object is in memory, CPU-Usage is reported at around 100% permanently, even when I am doing nothing in RStudio. As soon as the `sf` object is removed, CPU-Usage drops to near 0%.

For `sf` objects that are not all that large, CPU-Usage is also raised to a more or less constant level below 100%. For example, if I only keep 100'000 rows from the example file with

    test <- readRDS(f)[1:100000, ]

CPU-Usage is constantly around 60%.

I have also checked that the same does not happen in an ordinary RSession. This really seems to be a problem with RStudio, not with R.

It is well possible that this is the same as #12895: since everything in RStudio is slow, also using the viewer is.

**Comment by stibu81** [comment] 2023-03-28 11:16
It seems that this is not a problem specific to `sf` objects but happens for all large lists. (Since the geometry column in an `sf` object is a list, this encompasses `sf` objects. Creating a large list like this,

    library(magrittr)
    l <- sample(letters, 1e8, replace = TRUE) %>%
      split(rep(1:1e7, each = 10))

keeps my CPU load at around 95% permanently.

**Comment by dblodgett-usgs** [comment] 2023-03-28 13:45
That was my suspicion. It seems that rstudio is indexing the contents of the environment or something along those lines? 

I am on a pretty beefy laptop (8 core i7 w/ 64GB of ram) and was unable to reproduce the issue with smaller list columns... so perhaps the near thrashing behavior is resource availability dependent?

**Comment by stibu81** [comment] 2023-03-29 11:42
Could this be the same as #12923?

**Comment by jwilliamrozelle** [comment] 2023-03-31 22:27
I also get the error 

`Error in order(typeScores, scores) : argument lengths differ
In addition: Warning message:
In completions$type == .rs.acCompletionTypes$DATAFRAME & !completions$context %in%  :
  longer object length is not a multiple of shorter object length`
  
While RStudio tries to make suggestions when typing. This is for a non sf, large dataframe.

**Comment by kevinushey** [comment] 2023-04-04 18:34
@jwilliamrozelle: can you please file a separate issue (preferably with a reproducible example)?

**Comment by mikebessuille** [comment] 2023-04-10 14:16
@kevinushey should this be in test now that the PR is merged?

**Comment by kevinushey** [comment] 2023-04-10 16:59
@mikebessuille yes it should; thanks for the reminder!

**Comment by ronblum** [comment] 2023-04-14 17:27
Verified in RStudio Desktop 2023.05.0-daily+217 in Windows 11: The actions are now much, much faster.

**Closed by ronblum** 2023-04-14 17:27 UTC
Labels: bug

**Comment by melindahiggins2000** [comment] 2023-06-30 15:14
I also confirm I am getting this error with RStudio - working with a `data.frame` 146 rows x 2707 columns.

Error message:

```
Error in order(typeScores, scores) : argument lengths differ
In addition: Warning message:
In completions$type == .rs.acCompletionTypes$DATAFRAME & !completions$context %in%  :
  longer object length is not a multiple of shorter object length
```

RStudio Version:

```
RStudio 2023.03.1+446 "Cherry Blossom" 
Release (6e31ffc3ef2a1f81d377eeccab71ddc11cfbd29e, 2023-05-09) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
RStudio/2023.03.1+446 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
```

SessionInfo:

```
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.4.0 dplyr_1.1.0  

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13  knitr_1.39       magrittr_2.0.3   tidyselect_1.2.0
 [5] munsell_0.5.0    colorspace_2.0-3 R6_2.5.1         rlang_1.0.6     
 [9] fastmap_1.1.0    fansi_1.0.4      tools_4.2.2      grid_4.2.2      
[13] gtable_0.3.0     xfun_0.39        utf8_1.2.3       cli_3.6.0       
[17] withr_2.5.0      htmltools_0.5.4  digest_0.6.29    yaml_2.3.5      
[21] tibble_3.2.0     lifecycle_1.0.3  vctrs_0.5.2      evaluate_0.15   
[25] glue_1.6.2       rmarkdown_2.22   compiler_4.2.2   pillar_1.8.1    
[29] generics_0.1.3   scales_1.2.1     pkgconfig_2.0.3 
```

**Comment by ronblum** [comment] 2023-06-30 15:41
@melindahiggins2000 The issue is fixed in t[he current release](https://posit.co/download/rstudio-desktop/), Mountain Hydrangea 2023.06.0+421.

**Comment by melindahiggins2000** [comment] 2023-07-02 09:57
@ronblum Thank you for the information on the updates in the Mountain Hydrangea 2023.06.0+421 release. I will get the new version installed. Thank you for getting these updates added to the RStudio IDE!!
