### ISSUE TITLE
Can't follow windows shortcut (.lnk) 

### ISSUE THREAD

**Issue by M3IT** [rstudio/rstudio#7327] opened 2020-07-12 02:38 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959 
    OS Version      : Win 10 v2004 (19041.329)
    R Version       :  4.0.2

### Steps to reproduce the problem
- Create a windows shortcut (.lnk file) in the default working directory. The shortcut points to a folder containing R projects.
- In RStudio, File | Open Project. R opens a file browser window in the default working directory.
- Double click on the shortcut
- Error appears
![image](https://user-images.githubusercontent.com/25129392/87237600-b78ff180-c43b-11ea-8191-0c5c551a33cc.png)

### Describe the problem in detail/the behaviour you expected
I use a number shortcuts in my default working directory and Documents folder to redirect apps opening/saving files to various locations.  In other windows apps, double-clicking on these links when opening files moves the file browser window directly to the folder in the shortcut.
RStudio is not recognising the shortcut as a link, but is instead trying to open the .lnk file as a project and failing.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2020-07-13 18:58
Reproduces with 1.3.1056, and also with 1.2.5033.

Works as expected with 1.1.463.

Closely-related bug, do File / Open File... instead of Open Project, double-click on shortcut, and it opens a File Explorer window with the shortcut destination instead of following it in-place.

**Comment by kevinushey** [comment] 2020-07-13 19:09
Might be caused by this:

https://github.com/rstudio/rstudio/blob/de0b176a6afd48792c74109032f13a15586fbdf8/src/cpp/desktop/DesktopGwtCallback.cpp#L263-L267

It looks like Qt also interprets this flag on Windows to mean "don't resolve shortcuts". Since we _do_ want that behavior on Windows, we probably need to scope that check to not-Windows.

**Comment by kevinushey** [comment] 2020-07-13 19:11
From https://code.woboq.org/qt5/qtbase/src/plugins/platforms/windows/qwindowsdialoghelpers.cpp.html#993:

```
    if (options & QFileDialogOptions::DontResolveSymlinks)
        flags |= FOS_NODEREFERENCELINKS;
```

so there's a pretty good chance this is indeed the cause.

**Comment by kevinushey** [comment] 2020-07-13 19:11
Marking as v1.4 just because the associated fix should be simple.

**Comment by gtritchie** [comment] 2020-07-13 19:20
#2476 prompted addition of this code back in 1.2

**Closed** 2020-07-17 21:10 UTC
Labels: backlog, bug, desktop, windows

**Comment by R-Hannibal** [comment] 2020-08-27 18:14
@M3IT, thanks again for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by M3IT** [comment] 2020-08-28 15:49
@R-Hannibal, it is resolved in the linked version.
