### ISSUE TITLE
File created when clicking on file location seen while using `devtools::test()`

### ISSUE THREAD

**Issue by billdenney** [rstudio/rstudio#11825] opened 2022-08-24 11:54 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Windows 11
    R Version       : 4.2.1

### Steps to reproduce the problem

1. Test a package (`devtools::test()`) that has at least two warnings or errors during testing (I'm not sure if at least two warnings/errors is required)
    1. It may be required that the test file is in a different directory than the current directory.  In my case, I was in the `c:/git/pknca/tests` directory while my test files are in `c:/git/pknca/tests/testthat`.
2. Click on a link to go to the warning/error location in the code (click location is shown with the down red arrow in the image below).
3. Edit and save the file with edits.
4. **Without rerunning the tests**, click on another location in the same file.

### Describe the problem in detail

5. After step 4 above, an empty file will be created in the current directory (shown in the image below as the up red arrow).  I cannot close that file without closing Rstudio.

![image](https://user-images.githubusercontent.com/10359931/186410345-1d4c1665-8e4b-4003-88b9-3c56ca4f6c5f.png)

### Describe the behavior you expected

Either of the following:

* Need: Do not create a new, uncloseable file.
* Preferred: Go to the location in the original file.  Since the file has changed, go to the best approximation of the location.  This approximation is likely just the originally specified location, and if that location does not exist (e.g. the line or column number does not exist because the file is smaller or there are fewer columns in the line), go as close as possible.
* Alternate: Indicate a warning that the file has changed and so the location cannot be used.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by billdenney** [comment] 2022-08-24 12:27
When I closed Rstudio and reopened it, I now get a blank Rstudio window: 
![image](https://user-images.githubusercontent.com/10359931/186417506-045642ef-d720-4dc2-b145-a6f41ef6d902.png)

I can close the window by clicking the close "x" in the top right of the window twice.

Resetting the Rstudio state by the instruction at https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-s-State made it so that I could use Rstudio again (for my tracking to help bug resolution, the backup directory is named "%localappdata%\RStudio-backup-2022-08-24T08-25").

**Comment by kevinushey** [comment] 2022-08-24 16:50
Thanks for the bug report! I was able to reproduce the issue with two separate tabs being open, but not the blank screen issue you've described.

The main thing I notice is that the newly-opened tab uses the full path rather than an aliased path:

<img width="177" alt="Screen Shot 2022-08-24 at 9 46 47 AM" src="https://user-images.githubusercontent.com/1976582/186476096-401f1e9f-97b7-46d9-86cd-d9789cfcee5a.png">

However, your example doesn't seem to use a folder within your home directory, so perhaps what you're seeing is slightly different? I'm not able to reproduce in a similar case.

If you hover your mouse over the editor tab, you should see the full file location being reported by the IDE. Can you share and compare the two file paths reported for the two tabs?

**Comment by billdenney** [comment] 2022-08-24 17:04
The original file is in "c:/git/pknca/tests/testthat" and the newly created file is in "c:/git/pknca/tests".  The working directory is also ""c:/git/pknca/tests".

**Comment by kevinushey** [comment] 2022-08-24 17:17
Thanks for clarifying. In that case, I might need more information to reproduce the problem. Can you provide any other details?

In addition, can you confirm that your packages are all up-to-date? (`update.packages(ask = FALSE)`)

**Comment by billdenney** [comment] 2022-08-24 18:11
I'm not sure what other details may help.  I'm not sure that the blank screen issue is related.

I work in a regulated environment, so I can't update my packages right now.  I'm pretty close to up-to-date.  My out of date packages are:

```
> old.packages()
              Package         LibPath                                          Installed    Built   ReposVer    
bookdown      "bookdown"      "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.27"       "4.2.1" "0.28"      
callr         "callr"         "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "3.7.1"      "4.2.1" "3.7.2"     
censReg       "censReg"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.5-34"     "4.2.1" "0.5-36"    
cluster       "cluster"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "2.1.3"      "4.2.1" "2.1.4"     
collapse      "collapse"      "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.8.6"      "4.2.1" "1.8.8"     
covr          "covr"          "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "3.5.1"      "4.2.1" "3.6.0"     
cubature      "cubature"      "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "2.0.4.4"    "4.2.1" "2.0.4.5"   
drake         "drake"         "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "7.13.3"     "4.2.1" "7.13.4"    
DT            "DT"            "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.23"       "4.2.1" "0.24"      
dtplyr        "dtplyr"        "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.2.1"      "4.2.1" "1.2.2"     
emmeans       "emmeans"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.7.5"      "4.2.1" "1.8.0"     
estimability  "estimability"  "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.4"        "4.2.1" "1.4.1"     
evaluate      "evaluate"      "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.15"       "4.2.1" "0.16"      
forcats       "forcats"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.5.1"      "4.2.1" "0.5.2"     
furrr         "furrr"         "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.3.0"      "4.2.1" "0.3.1"     
gert          "gert"          "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.6.0"      "4.2.1" "1.7.1"     
ggforce       "ggforce"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.3.3"      "4.2.1" "0.3.4"     
ggraph        "ggraph"        "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "2.0.5"      "4.2.1" "2.0.6"     
globals       "globals"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.15.1"     "4.2.1" "0.16.0"    
googlesheets4 "googlesheets4" "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.0.0"      "4.2.1" "1.0.1"     
graphlayouts  "graphlayouts"  "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.8.0"      "4.2.1" "0.8.1"     
haven         "haven"         "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "2.5.0"      "4.2.1" "2.5.1"     
Hmisc         "Hmisc"         "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "4.7-0"      "4.2.1" "4.7-1"     
hms           "hms"           "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.1.1"      "4.2.1" "1.1.2"     
httr          "httr"          "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.4.3"      "4.2.1" "1.4.4"     
knitr         "knitr"         "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.39"       "4.2.1" "1.40"      
MASS          "MASS"          "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "7.3-58"     "4.2.1" "7.3-58.1"  
modelr        "modelr"        "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.1.8"      "4.2.1" "0.1.9"     
narray        "narray"        "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.4.1.1"    "4.2.1" "0.5.0"     
nleqslv       "nleqslv"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "3.3.2"      "4.2.0" "3.3.3"     
nlme          "nlme"          "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "3.1-158"    "4.2.1" "3.1-159"   
parsnip       "parsnip"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.0.0"      "4.2.1" "1.0.1"     
pillar        "pillar"        "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.8.0"      "4.2.1" "1.8.1"     
plm           "plm"           "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "2.6-1"      "4.2.1" "2.6-2"     
posterior     "posterior"     "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.2.2"      "4.2.1" "1.3.0"     
qs            "qs"            "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.25.3"     "4.2.1" "0.25.4"    
RApiSerialize "RApiSerialize" "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.1.0"      "4.2.0" "0.1.1"     
rbibutils     "rbibutils"     "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "2.2.8"      "4.2.1" "2.2.9"     
RcppArmadillo "RcppArmadillo" "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.11.2.0.0" "4.2.1" "0.11.2.3.1"
RCurl         "RCurl"         "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.98-1.7"   "4.2.0" "1.98-1.8"  
readxl        "readxl"        "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.4.0"      "4.2.1" "1.4.1"     
reprex        "reprex"        "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "2.0.1"      "4.2.1" "2.0.2"     
rmarkdown     "rmarkdown"     "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "2.14"       "4.2.1" "2.15"      
rstudioapi    "rstudioapi"    "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.13"       "4.2.1" "0.14"      
rvest         "rvest"         "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.0.2"      "4.2.1" "1.0.3"     
scales        "scales"        "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.2.0"      "4.2.1" "1.2.1"     
stringr       "stringr"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.4.0"      "4.2.1" "1.4.1"     
survival      "survival"      "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "3.3-1"      "4.2.1" "3.4-0"     
tarchetypes   "tarchetypes"   "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.6.0"      "4.2.1" "0.7.0"     
targets       "targets"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.12.1"     "4.2.1" "0.13.1"    
tidygraph     "tidygraph"     "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.2.1"      "4.2.1" "1.2.2"     
tinytex       "tinytex"       "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.40"       "4.2.1" "0.41"      
TMB           "TMB"           "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.9.0"      "4.2.1" "1.9.1"     
tweenr        "tweenr"        "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "1.0.2"      "4.2.1" "2.0.1"     
V8            "V8"            "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "4.2.0"      "4.2.1" "4.2.1"     
viridisLite   "viridisLite"   "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.4.0"      "4.2.1" "0.4.1"     
xfun          "xfun"          "C:/Users/wdenn/AppData/Local/R/win-library/4.2" "0.31"       "4.2.1" "0.32"      
cluster       "cluster"       "C:/Program Files/R/R-4.2.1/library"             "2.1.3"      "4.2.1" "2.1.4"     
MASS          "MASS"          "C:/Program Files/R/R-4.2.1/library"             "7.3-57"     "4.2.1" "7.3-58.1"  
nlme          "nlme"          "C:/Program Files/R/R-4.2.1/library"             "3.1-157"    "4.2.1" "3.1-159"   
survival      "survival"      "C:/Program Files/R/R-4.2.1/library"             "3.3-1"      "4.2.1" "3.4-0"     
```

**Comment by romainfrancois** [comment] 2022-08-24 20:03
It might be related to https://github.com/rstudio/rstudio/issues/11697 that is perhaps fixed by https://github.com/rstudio/rstudio/pull/11727 in Elsbeth. 

I'll have a look soon, but maybe it's fixed in Elsbeth too. @billdenney do you have the same issue with an Elsbeth daily ? https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/windows/

**Comment by billdenney** [comment] 2022-08-24 21:00
It does look similar to #11697.  I'll try to test Elsbeth soon.

**Comment by romainfrancois** [comment] 2022-09-30 13:27
I believe it was fixed, moving to test in case it's a windows issue, but that worked for me on macOS with latest elsbeth daily.

**Comment by jonvanausdeln** [comment] 2022-10-03 17:05
I tried a few more cases on 2022.11.0-daily+221, and it does appear to resolve this issue as well.

@billdenney , please let us know if you are still seeing an issue.

**Closed by jonvanausdeln** 2022-10-03 17:05 UTC
Labels: bug

**Comment by billdenney** [comment] 2022-10-03 17:24
I've been using dailies for about a month, and I don't see this issue anymore.  Thanks for fixing it!
