### ISSUE TITLE
Rstudio crash keras tensorflow

### ISSUE THREAD

**Issue by Idriss0peaccel** [rstudio/rstudio#2102] opened 2018-02-01 11:24 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version : Version 1.1.383 
    OS Version      :  Windows 10
    R Version       :  3.4.2 (2017-09-28) x86_64-w64-mingw32/x64 (64-bit)

### Steps to reproduce the problem

Hello, i have Rstudio with Anaconda, i installed keras and tensorflow with these command:
```
install.packages("keras")
library(keras)
install_keras()
```
I created a small network

```

parametre    <- list("nbNeurones" = 2,
                         "epochs" = 32,
                         "dropout" =  1,
                         "units" = 2,
                         "batch_size" = 128,
                         "fonction" = "elu" )

networkTest1 <- function(parametre)
{
  unit           <- parametre$units 
  maxlen         <- parametre$maxlen
  nbNeurones     <- parametre$nbNeurones
  dropout        <- parametre$dropout
  fonction       <- parametre$fonction
  
  model <- keras_model_sequential()
  model %>%
    
    layer_dense(units = unit, input_shape = maxlen) %>%
    
    layer_dense(nbNeurones) %>%
    layer_dropout(dropout) %>%
    layer_activation(fonction) %>%
    
    layer_dense(1) %>%
    layer_activation("linear")
    
  ### Compile Model  (Configure a Keras model for training)
  model %>% compile(
    loss = "mean_squared_error",
    optimizer = "adam",
    metrics = "mean_squared_error"
  ) 
  return(model)
}
```

### Describe the problem in detail

when i run the networkTest1 i get this message
`2018-02-01 14:50:13.074157: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2`

and after few minutes Rstudio crash.

**Comment by kevinushey** [comment] 2018-02-01 17:40
When I run your example I just see a plain R error:

```
> networkTest1(parametre)
C:\Users\kevin\ANACON~1\envs\R-TENS~1\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-02-01 09:38:40.943299: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Error in py_call_impl(callable, dots$args, dots$keywords) :
  ValueError: The first layer in a Sequential model must get an `input_shape` or `batch_input_shape` argument.

Detailed traceback:
  File "C:\Users\kevin\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\models.py", line 432, in add
    raise ValueError('The first layer in a '
Calls: networkTest1 ... compose_layer.keras.models.Sequential -> <Anonymous> -> py_call_impl -> .Call
Execution halted
```

**Comment by kevinushey** [comment] 2018-02-01 17:43
After fixing your example to add a dummy `maxlen` argument I'm not able to reproduce the crash (the model is compiled successfully)

**Comment by Idriss0peaccel** [comment] 2018-02-01 19:54
hello, 
sorry for the variable maxlen I thought I checked everything.
Pushing a little more my tests I noticed that when I used my code in the root environment (or Anaconda3 environlent), the program is launched and arrived at certain time of calculation (in the console was displayed the epoch scrolling ) Rstudio crashed. In the r-tensorflow environment (created by the command install_keras() ) when i use the code Rstudio crash few minutes without anything to display in the console. 
Why i don't have a error message ?

**Comment by kevinushey** [comment] 2018-02-02 19:49
@Idriss0peaccel this sounds somewhat like a crash that was recently fixed in the latest version of `reticulate`. Can you try reinstalling it with:

```
devtools::install_github("rstudio/reticulate")
```

and let us know if you still see the issue?

**Comment by Idriss0peaccel** [comment] 2018-02-04 17:45
Hello, 
Reinstallation solved my problem, thank for your help.

**Comment by kevinushey** [comment] 2018-02-04 19:18
Awesome news! Thanks for reporting.

**Closed by kevinushey** 2018-02-04 19:18 UTC
