### ISSUE TITLE
Non-default window positioning leads to build menu appearing off-screen

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#1652] opened 2017-10-24 15:57 UTC
Swapping the **Environment, History, Connection** tab with **Console** -- e.g. the panels on the Upper Right move to the Lower Left -- leads the build menu to appear off screen. See screenshot for example:

![Build Menu Off-Screen](https://user-images.githubusercontent.com/833642/31953866-a0afae7e-b8a9-11e7-8cff-6c37da03299d.png)

**Comment by dfalty** [comment] 2017-10-25 17:06
I can't reproduce this on Mac version 1.2.134. What version of RStudio are you on? Also, do you have additional info to reproduce this?

**Comment by coatless** [comment] 2017-10-30 02:41
@dfalty This problem exists in both the "stable" and "daily" variants of RStudio. When I referred to the "Build" menu, I meant to say: "Build book"

I've recorded the exact steps using a clean install of the daily version 1.2.140

![rstudio_debug_menu](https://user-images.githubusercontent.com/833642/32152350-9318ee50-bcf1-11e7-8c50-0fd2513418fe.gif)

**Comment by dfalty** [comment] 2017-10-30 09:46
@coatless Thanks for the additional info! I'm also able to reproduce this on Mac 1.2.140.

**Comment by gtritchie** [comment] 2019-11-12 23:58
Fixed in 1.3 via #5714

**Closed by gtritchie** 2019-11-12 23:58 UTC
Labels: bug, reproducible

**Comment by tmcduff** [comment] 2020-02-24 18:26
version: Version 1.3.842
