### ISSUE TITLE
barplot cause rstudio crash

### ISSUE THREAD

**Issue by nefphys** [rstudio/rstudio#4189] opened 2019-01-22 03:45 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.463 
    OS Version      : win10 17134.523
    R Version       : 3.4.4 64-bit

### Steps to reproduce the problem
`x <- matrix(1:10,nrow=1)`
`colnames(x) <- c("中山","南皮","邺","平原","北海","晋阳","上党","濮阳","陈留","许昌")`
`barplot(height=x)`
then rstudio crashed
### Describe the problem in detail
perhaps chinese character cause this problem? i use this code in Rgui is right

**Comment by ronblum** [comment] 2019-01-22 18:33
@nefphys Thank you for raising the issue. I'm unable to reproduce this, though. Can you check if the problem occurs in R outside of RStudio?

**Comment by nefphys** [comment] 2019-01-23 05:57
> @nefphys Thank you for raising the issue. I'm unable to reproduce this, though. Can you check if the problem occurs in R outside of RStudio?
thanks, i test again in cmd, rgui, and rstudio, only crashed in rstudio, the rstudio show the error "R encountered a fatal error".

**Comment by nefphys** [comment] 2019-01-23 06:03
@ronblum thanks, i test again in cmd, rgui, and rstudio, only crashed in rstudio, the rstudio show the error "R encountered a fatal error". However, english characters in these code worked well.
`x <- matrix(1:10,nrow=1)`
`colnames(x) <- c("A","B","C","D","E","F","G","H","I","J")`
`barplot(height=x)`

**Comment by jmcphers** [comment] 2019-01-31 18:33
@nefphys Does this reproduce in the preview version of RStudio?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by nefphys** [comment] 2019-02-01 03:53
@jmcphers ,thanks, I installed the preview version , however, still crashed, so sad 😂

**Comment by jmcphers** [comment] 2020-05-28 17:02
Unfortunately we've never been able to repro this or received any other reports so closing. You might check to see if it repros in the latest release (just announced this week), 1.3.959.

**Closed by jmcphers** 2020-05-28 17:02 UTC
Labels: repro needed, windows
