### ISSUE TITLE
Fatal error with new R 4.1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by MatthieuStigler** [rstudio/rstudio#9381] opened 2021-05-20 19:17 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1106
    OS Version      : Ubuntu 20.04
    R Version       : R version 4.1.0 (2021-05-18)

### Steps to reproduce the problem

Simply running a ggplot call leads to crash, try:

```
library(ggplot2)
ggplot(freeny, aes(x=y))+geom_density()
```

Leading to error: *ERROR elf_dynamic_array_reader.h:61] tag not found*

### Describe the problem in detail

This seems to have just happened now with the change to R 4.1. 

### Describe the behavior you expected

- [yes ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [yes ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [yes ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ yes] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![Screenshot from 2021-05-20 12-14-40](https://user-images.githubusercontent.com/108840/119036127-3f506180-b965-11eb-8c94-a97b816b52e4.png)
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/6518311/diagnostics-report.txt)

**Comment by jmcphers** [comment] 2021-05-20 19:20
Duplicate of https://github.com/rstudio/rstudio/issues/9373. You'll need the preview release of RStudio to work with R 4.1: https://www.rstudio.com/products/rstudio/download/preview/

**Closed by jmcphers** 2021-05-20 19:20 UTC
