### ISSUE TITLE
Sorting by size in the Environment/File Pane is not correct

### ISSUE THREAD

**Issue by ckatsulis** [rstudio/rstudio#3195] opened 2018-07-20 16:16 UTC
### System details
N/A
    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem
1. Sort by Size Column
2. Observe sizes out of order
### Describe the problem in detail
![image](https://user-images.githubusercontent.com/7516330/43013335-3232b16a-8c0e-11e8-9b86-2985cdeb95ab.png)

### Describe the behavior you expected

Sizes should be in order

1. The output of sessionInfo() 
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                  LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8        LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8       LC_PAPER=en_US.UTF-8         
 [8] LC_NAME=en_US.UTF-8           LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8      LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] roll_1.0.7                 PerformanceAnalytics_1.5.2 xts_0.10-2.2               zoo_1.8-2                  TTR_0.23-3                 dygraphs_1.1.1.5          

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17       compiler_3.5.1     later_0.7.3        bitops_1.0-6       tools_3.5.1        digest_0.6.15      jsonlite_1.5       htmlTable_1.9      checkmate_1.8.5    lattice_0.20-35    shiny_1.0.5       
[12] curl_3.2           yaml_2.1.19        rJava_0.9-10       stringr_1.3.1      knitr_1.20         xlsxjars_0.6.1     htmlwidgets_0.9    grid_3.5.1         R6_2.2.2           RJSONIO_1.3-0      qmao_1.6.11       
[23] pander_0.6.2       magrittr_1.5       backports_1.1.2    promises_1.0.1     htmltools_0.3.6    mime_0.5           xtable_1.8-2       httpuv_1.4.4.2     quadprog_1.5-5     xlsx_0.6.1         stringi_1.2.3     
[34] RCurl_1.95-4.10    RcppParallel_4.4.0

```

**Comment by ronblum** [comment] 2018-07-20 16:51
@ckatsulis I'm unable to reproduce this on Ubuntu. What edition and version of RStudio are you using?

**Comment by ckatsulis** [comment] 2018-07-20 18:07
Ubuntu as well  Rstudio server.  sorry.

it appears it's only a problem when files sizes are above 1GB and mixed
with smaller sizes.  I removed the > GB files from the directory and it
sorts them fine

**Comment by ronblum** [comment] 2018-07-20 18:43
@ckatsulis No problem, and thank you for looking into it further! I was able to reproduce the issue on both RStudio Server on Ubuntu 16.04.4 and Red Hat 7.5, but it's not an issue with RStudio Desktop on MacOS 10.12.6 (Sierra).

**Comment by kevinushey** [comment] 2018-07-20 23:05
FWIW I'm not able to reproduce with the RStudio Server 1.2 builds, so perhaps (?) this has been fixed in the latest daily builds?

**Comment by ronblum** [comment] 2018-07-24 15:05
@kevinushey Are you using files large than 1 GB?

**Comment by kevinushey** [comment] 2018-07-24 15:34
Yes I was. I created 6 large files with:

```
mkdir -p ~/scratch/big
cd ~/scratch/big
for i in `seq 1 6`; do fallocate -l "$i"gb file_$i.txt; done
```

RStudio Server Pro on Ubuntu 16.04;

v1.1.453:

![screen shot 2018-07-24 at 8 31 28 am](https://user-images.githubusercontent.com/1976582/43149473-5401c752-8f1c-11e8-8239-9052af036560.png)

v1.2.850-1:

![screen shot 2018-07-24 at 8 33 34 am](https://user-images.githubusercontent.com/1976582/43149480-5ca6678c-8f1c-11e8-93f9-3824569606d4.png)

**Comment by BigTimeStats** [comment] 2018-09-26 15:05
I'm also having this issue on R 3.4.3, Rstudio 1.1.423, Windows 10 Server

![untitled](https://user-images.githubusercontent.com/29850965/46089207-0479d980-c17c-11e8-9c27-4f750450c80b.png)

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)
```

**Comment by jmcphers** [comment] 2019-11-12 23:52
Closing this since @kevinushey has sufficiently demonstrated that the problem doesn't exist in the Files pane any more.

@BigTimeStats You're looking at the Environment pane (and probably a different problem). Feel free to reopen as a new issue if you're still seeing it in > 1.2.5019!

**Closed by jmcphers** 2019-11-12 23:52 UTC
Labels: bug, reproducible, server
