### ISSUE TITLE
rstudio opens with a blank screen 

### ISSUE THREAD

**Issue by RobinHankin** [rstudio/rstudio#2755] opened 2018-05-08 07:26 UTC
Ubuntu linux,  RStudio 1.1.447 - Ubuntu 16.04+/Debian 9+ (64-bit)  downloaded today; R-3.5.0.

RStudio opens a blank window, repeatedly.  The menu headings (File, Edit, Code, View) are visible but pull down to reveal only blank black rectangles, with no text;  no sub-menus open.

I have reinstalled R from scratch and downloaded and re-installed RStudio several times.

**Comment by Stonebutcher** [comment] 2018-05-14 08:11
Windows Server 2012 R2  - RStudio 1.1.447 - R 3.5.0

I have the same problem on a Windows 2012 R2 server. After updating to R 3.5.0 and RStudio 1.1.447, RStudio can be started but only displays the main menu. The menu items can still be selected, but the window with the submenus no longer opens.

**Comment by Stonebutcher** [comment] 2018-05-14 08:40
I have solved the problem in the meantime by first uninstalling R version 3.5.0, then installing and testing version 3.4.4 again (so RStudio ran) and then installing version R 3.5.0 again.

**Comment by jmcphers** [comment] 2018-05-17 18:57
Sorry, we haven't been able to reproduce this. Do you see the same problem with the RStudio daily builds?

https://dailies.rstudio.com/

**Comment by RobinHankin** [comment] 2018-05-18 02:28
thanks for this jmcphers.  I actually resolved the issue late last night:  uninstall R-3.5.0, uninstall RStudio, install R-3.4.4, install RStudio, uninstall R-3.4.4, then re-install R-3.5.0, but using ./configure --enable-R-shlib=yes.

A simple reinstallation of R-3.5.0 and RStudio didn't do the trick for me but the process above seemed to work.

**Comment by andrew-schulman** [comment] 2018-06-10 22:34
I encountered this same problem with RStudio 1.1.383 and 1.1.453, r-base 3.2.3-4, Ubuntu 16.04 x86_64. It was caused by a problem in my ~/.Rprofile, which was trying to install some packages if they weren't installed, but was somehow getting caught in an installer loop (lots of /usr/lib/R/bin/exec/R processes, using up memory and download bandwidth).

Once I moved .Rprofile aside, RStudio started normally.

**Comment by msberends** [comment] 2019-02-11 13:27
I had this with remote desktop sessions (RDP) in Windows. The RStudio window opens completely black except for the menu headings (File, Edit, Code, View).

The solution was to open a remote session with colours of at least 32 bit (highest):

![image](https://user-images.githubusercontent.com/31037261/52566060-054c9880-2e09-11e9-803f-3eb86182dc1f.png)

**Comment by aminadibi** [comment] 2019-07-09 18:41
We're having same problem with a few of our windows machine within the past few months. We have not been able to reproduce the problem. Sometime disabling ipv6 solves the problem, but other times it does not help.

**Comment by MHeinrichs** [comment] 2019-08-27 11:17
Hi 
I can verify this issue: I'm running RStudioDesktop 1.2.1335 on Red Hat Enterprise Linux 7, running a rdp host via xrdp/xvnc. If I access the Linux-machine via remote desktop from a Windows machine I get a black RStuido screen, if the rdp-terminal is set to 16bit colors. If the terminal is set to 24 or 32 bits everything is fine. 
If any other information is needed, I can try to provide them.

Best regards Matthias

**Comment by jmcphers** [comment] 2019-11-20 00:25
Does switching to software rendering resolve the issue? (Newer releases of RStudio will automatically use software rendering over Remote Desktop).

https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by ronblum** [comment] 2020-01-03 17:43
Closing since there hasn't been any activity in more than a month. If the issue is still happening, please update the ticket. Thanks!

**Closed by ronblum** 2020-01-03 17:43 UTC
Labels: repro needed
