### ISSUE TITLE
Help not opening new window (on macOS)

### ISSUE THREAD

**Issue by CommunyAS** [rstudio/rstudio#14136] opened 2024-01-17 11:15 UTC
For a while (about two months?) now, there is an issue with opening a new window when clicking on the *Show in new window*-button of the Help-tab (see Screenshot).

![Screenshot 2024-01-17 at 12 05 07](https://github.com/rstudio/rstudio/assets/74900017/92d9b347-b9f4-46e9-9feb-184dd95c0454)

This seemingly is an issue for other users of RStudio too, since searching for it resulted in several help requests (also on Windows, not only macOS) of which, unfortunately, none was answered, i.e.
- https://community.rstudio.com/t/show-in-new-window-not-working/155850
- https://community.rstudio.com/t/help-pane-show-in-new-window-icon-does-nothing/180018/4

Having the possibility to open help pages in a separate window is great for checking out how packages, functions etc. work - It would be very helpful to efficiently work with RStudio.

### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.12.0+369
    OS Version      :  macOS 14.2.1 / macOS 13.6.3
    R Version       : 4.3.2

### Steps to reproduce the problem

Just search for the Help in R documentation in RStudio, click on the *Show in new window*-button…

### Describe the problem in detail

See initial description above.

### Describe the behavior you expected

No separate Help window opens.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2024-01-17 17:59
Duplicate of #14097. The issue will be fixed in the upcoming 2023.12.1 patch, per https://github.com/rstudio/rstudio/pull/14104.

**Closed by gtritchie** 2024-01-17 17:59 UTC
Labels: bug, duplicate, new
