### ISSUE TITLE
Autocompletion for undocumented S3 methods doesn't inherit help text from generic

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudio#14232] opened 2024-02-07 17:21 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0+397
    OS Version      : Windows
    R Version       : R 4.3.2

### Steps to reproduce the problem
1. Load the package that exports the S3 method , but does not document it explicitly (only documents the generic)
2. try to get autocompletion help text.

![image](https://github.com/rstudio/rstudio/assets/52606734/c56b127d-c8a7-4255-9729-7728674a2f6a)

Help text shows if tidyr is not loaded because the S3 method is not registered.

Also when I press F1 at the position of my cursor, help doesn't show up.

I get 

```
No documentation for  ‘nest.tbl_df’ was found in packages and library :
You can try ‘??nest.tbl_df’
```

That is because tidyr exports `nest.tbl_df()`, but doesn't document it. It only documents the generic.
![image](https://github.com/rstudio/rstudio/assets/52606734/83796bfd-5ca5-4e90-9391-3b6202f3db05)

A case that works as expected is `dplyr::mutate()`.

![image](https://github.com/rstudio/rstudio/assets/52606734/1026a8c6-88ab-4cc9-9f86-52439026f449)

that is because `mutate.data.frame()` is documented in the .Rd file
![image](https://github.com/rstudio/rstudio/assets/52606734/160a32ab-d06a-43c2-b5a7-1af7f00506d7)

### Describe the problem in detail

No autocompletion help text shows.

I tested this thoroughly and the pattern seems to hold for all functions I tested.

I was wondering if it was possible to tweak the logic a little and fall back on the generic's documented parameters if the method is not documented.

### Describe the behavior you expected

I would expect the help text to show, maybe inherit from the generic. See how I was able to get autocompletion for `pivot_longer()/wider` https://github.com/tidyverse/tidyr/pull/1540

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2024-02-07 20:10
Thanks; should be fixed in the next daily builds!

<img width="844" alt="Screenshot 2024-02-07 at 2 10 16 PM" src="https://github.com/rstudio/rstudio/assets/1976582/24dc09a3-ae54-4f41-96d5-0954759ece3a">

**Comment by olivroy** [comment] 2024-02-07 20:12
Wow. I am impressed. Thank you so much for all your hard work. Can't wait to try out the next dailies for the git pane, ggplot2 completion and this!

**Comment by olivroy** [comment] 2024-02-08 23:04
Works really well! thanks so much.

**Comment by kevinushey** [comment] 2024-02-08 23:10
Excellent -- thanks again for taking the time to test!

**Closed by kevinushey** 2024-02-08 23:10 UTC
Labels: bug

**Comment by olivroy** [comment] 2024-02-14 15:17
Hi @kevinushey ,

think I discovered a small bug.

https://github.com/rstudio/rstudio/blob/bfd6bf382d8ab57268a1bfc788a4d02c9221e1b9/src/cpp/session/modules/SessionHelp.R#L812

Error in strsplit(file, "/", fixed = TRUE) : argument is not a character. 

it seems to occur when typing.

Will let you know if I can pin point it.

**Comment by olivroy** [comment] 2024-02-14 19:55
I was able to find the reason.

it is when developing a package.

1. open a package project
2. `devtools::load_all()`
3. type a function in that package
4. request argument name completion

![image](https://github.com/rstudio/rstudio/assets/52606734/bf374baa-c983-4b6b-ac19-b798c713ee1d)

The error prints to console

**Comment by kevinushey** [comment] 2024-02-14 23:28
@olivroy, I wasn't able to reproduce with some of the packages I have available locally -- any chance you can share more details?

**Comment by olivroy** [comment] 2024-02-22 16:17
@kevinushey I think that #14309 breaks (again) this.

```r
library(dplyr)
mtcars |> 
  dplyr::filter(
    <tab>
  )
```

The help text doesn't show.

By sourcing the code  src/cpp/session/modules/SessionRCompletions.R in my R session, the S3 method issue comes back and doesn't work anymore.
![image](https://github.com/rstudio/rstudio/assets/52606734/159a2f1f-defa-4900-a35e-2cd2ab91fa03)

If you can't reproduce, it's probably because sourcing RStudio source code is probably not a good idea, but better safe than sorry!

**Comment by kevinushey** [comment] 2024-02-22 20:31
It seems to be working for me in the latest daily builds:

<img width="812" alt="Screenshot 2024-02-22 at 12 27 09 PM" src="https://github.com/rstudio/rstudio/assets/1976582/d35418b6-923c-49c0-8f65-a88d777f6552">

Can you provide any other context?

**Comment by olivroy** [comment] 2024-02-22 20:36
@kevinushey, the [+475 latest daily](https://[dailies.rstudio.com/rstudio/chocolate-cosmos/index.json](https://dailies.rstudio.com/rstudio/chocolate-cosmos/index.json)) appears to be with commit 08d8e552019bf123e310ad5725dc6826020530bf. #14231 happened right after. We can check back tomorrow with a version that includes this change.

**Comment by kevinushey** [comment] 2024-02-28 21:16
Still appears fine for me with 2024.04.0 Build 505:

<img width="801" alt="Screenshot 2024-02-28 at 1 15 49 PM" src="https://github.com/rstudio/rstudio/assets/1976582/b58b9e4c-91cd-418a-8c48-93fc5f478a0b">

@olivroy can you double-check as well?

**Comment by olivroy** [comment] 2024-02-28 21:22
all good on macOS! thanks for checking!
