### ISSUE TITLE
Enabling Visual Mode failed

### ISSUE THREAD

**Issue by HankNu** [rstudio/rstudio#8861] opened 2021-01-31 09:46 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.4.1103
    OS Version      : x86_64-redhat-linux-gnu (64-bit)
    R Version       : 3.6.0 (2019-04-26) -- "Planting of a Tree"

### Steps to reproduce the problem

To switch into visual mode for a given document, use the button at the top-right of the document toolbar (or alternatively the ⌃⇧ F4 keyboard shortcut).

### Describe the problem in detail

"Unexpected exception: Column 'version' not found" will appear in Console and RStudio is frozen.  According to the tip, to start new session will not work out. The only thing I can do is cancle enableing visual mode again at the start of new session and RStudio will work in source mode orderly.

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

![RStudio_003](https://user-images.githubusercontent.com/33976639/106380258-f2637200-63eb-11eb-99b8-834edcd601ab.png)

**Comment by ronblum** [comment] 2021-02-01 15:09
@HankNu Thank you for raising the issue! So that I can try to reproduce:
- What version of Red Hat are you using?
- Does this occur in all documents? From the image, it looks like it's happening with the default document.

**Comment by HankNu** [comment] 2021-02-04 01:25
@ronblum It is CentOS7 that operates on my another computer, and it occured in both default document and another. At first, I doubt the R version 3.6 that caused this problem, then I test in Windows 10 with R 3.6.0 which is ok. Now I am in Ubuntu 1804 with  R version 3.6.3 (2020-02-29) which is ok again. So the only cause will be CentOS7? Thanks a lot.

**Comment by jjallaire** [comment] 2021-07-21 01:54
This commit will allow us to not crash if we find a zotero database w/o a `version` (which appears to be what happened here): https://github.com/rstudio/rstudio/commit/f8b92802cb1c07e6ccbada64d6461923863f4f03

**Comment by astayleraz** [comment] 2021-08-13 17:56
I tested zotero with mac desktop version 2021-08.0 Build 305-3 and I was not seeing this issue. Closing the issue for now and hopefully, this fixes the issue for HankNu as well. Let us know if that is not the case.

**Closed by astayleraz** 2021-08-13 17:56 UTC
Labels: bug, repro needed, visual markdown editing, test

**Comment by HankNu** [comment] 2021-08-16 08:15
Because I get a new computer, I install new CentOS Stream 8. Now Enabling Visual Mode is no problem. 
Thanks anyway.

> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Stream 8

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.12.so
