### ISSUE TITLE
R.4.4.0 browser() incompatible with RStudio 2023.12.1

### ISSUE THREAD

**Issue by Bisaloo** [rstudio/rstudio#14590] opened 2024-04-25 10:49 UTC
![image](https://github.com/rstudio/rstudio/assets/10783929/ef08304c-28a7-4d66-8220-fdd06397f307)

### System details

- RStudio Edition : Desktop
- RStudio Version : RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-29) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
- OS Version      : Ubuntu 22.04.4
- R Version       : R 4.4.0

### Steps to reproduce the problem

Create any function with a `browser()` call and call it. E.g.,

```r
f <- function() {
  browser()
}
f()
```

### Describe the problem in detail

- This only happens within RStudio, and not when R is started from the terminal
- This is fixed in the latest RStudio dailies but a release may be required before many users upgrade to R 4.4.0 and get stuck on this issue

### Describe the behavior you expected

No error and warning.

Related to https://github.com/rstudio/rstudio/issues/14427?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-04-25 14:51
@Bisaloo Thank you for raising this! We're almost ready to release the next version, Chocolate Cosmos 2024.04.0, and as you note, the issue is resolved in it. Note that it changes were made in anticipation on R 4.4.0, but it won't have been certified on it yet.

**Comment by balthasars** [comment] 2024-04-26 15:13
> @Bisaloo Thank you for raising this! We're almost ready to release the next version, Chocolate Cosmos 2024.04.0, and as you note, the issue is resolved in it. Note that it changes were made in anticipation on R 4.4.0, but it won't have been certified on it yet.

Thanks for the information. FYI: This also occurs when you use `rstudioapi::documentOpen()` in one of your scripts.

**Comment by ronblum** [comment] 2024-04-26 15:47
@balthasars Can you provide an example using `rstudioapi::documentOpen()` that results in a problem? I tried in a few releases with R 4.4.0 but I couldn't reproduce.

**Comment by balthasars** [comment] 2024-04-26 16:10
> @balthasars Can you provide an example using `rstudioapi::documentOpen()` that results in a problem? I tried in a few releases with R 4.4.0 but I couldn't reproduce.

Just tried the newest Chocolate Cosmos daily (2024.04.0+735) and can confirm it's fine on there. Can't seem to be able to a minimal reproducible example from outside the context, sorry about that. 

This is probably not very helpful but the general pattern was a file like `source-script.R` to source some other files like `example.R` that in turn source other files kind of like so:

```r
rstudioapi::documentOpen(here::here("example.R"))
source(here::here("example.R"))
```

which then resulted in the same error as the OP. Was on Windows 10 in the latest stable version.

But I'm glad it's resolved :)

**Comment by ronblum** [comment] 2024-04-26 16:42
@balthasars Great, thank you for checking! And most likely* the build that you checked with is what we'll be releasing with, and it will be certified on R 4.4.0.

*I say "most likely" because that's what it will be, but I don't want to jinx the release. 🙂

**Comment by kevinushey** [comment] 2024-04-26 17:42
Thanks! I'm going to close this issue as it's resolved in the daily builds and also the (imminently coming) release of RStudio 2024.04.0, but please keep us appraised if you find other issues.

**Closed by kevinushey** 2024-04-26 17:42 UTC
Labels: bug, r versions, new
