### ISSUE TITLE
Error: Unable to establish connection with R session

### ISSUE THREAD

**Issue by statsandthings** [rstudio/rstudio#3066] opened 2018-06-25 13:04 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : Ubuntu 18.04
    R Version       : 3.5

### Describe the problem in detail
* Clean Install of Ubuntu 18.04
* Clean Install of R and R Studio

Within minutes of using R Studio I get `"Error: Unable to establish connection with R session"` and am unable to do anything in R Studio, and am not even able to close R Studio. When I click on the `x` or do a <kbd>CTRL</kbd>+<kbd>Q</kbd> I get a message `quitting R` but R never quits. I have to hard restart Ubuntu to get R Studio to close. If I browse *Chrome* I still have active internet.

**Comment by ronblum** [comment] 2018-06-26 16:57
@statsandthings Is there anything specific you are running when this happens, or does this occur even if you start up RStudio and do nothing?

**Comment by statsandthings** [comment] 2018-07-12 12:44
I started R Studio in a fresh session and let it sit idle for an hour. I then tried to close R Studio and couldn't. Next I tried to `library(tidyverse)` and got the *Unable to establish connection with R session* error.

It looks like the 'connection' is lost within 30-60 minutes of opening R. And for whatever reason when the connection is lost it is unable to reconnect. I am experiencing no other wifi issues on my network.

**Comment by statsandthings** [comment] 2018-07-19 19:20
I ended up installing the preview version 1.2.792 of R Studio and the issue has gone away. Please incorporate whatever was done (to fix this issue) into the final release.

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by jmcphers** [comment] 2019-11-19 21:31
We have done so!

**Comment by Mckay-R** [comment] 2020-01-18 05:39
I have the same issue on Windows 10. Mine started in November 2019. 
I literally cannot do anything on Rstudio, I keep getting the error message "unable to establish connection with R session." 
I have tried several solutions I found online, I still couldn't fix this issue. 
I used R everyday, I really need someone to help fix this issue for me.

**Comment by Mckay-R** [comment] 2020-01-18 05:40
> We have done so!

Hi Jonathan,

I sent you an email on the same issue. I would appreciate if you could respond.

**Comment by SimoneMusic8** [comment] 2020-02-19 20:38
Hi,
I have the same issue, have you solved it ?

**Comment by nas66im** [comment] 2020-03-12 00:19
Same issue here! Can't do anything on it😔

**Comment by fempet22** [comment] 2020-03-12 09:17
Unable to establish connection with R session please assist

**Comment by jmcphers** [comment] 2020-03-12 16:17
There are lots of things that can cause this. If you're affected, you might try installing RStudio 1.3, which will give you lots of information instead of the "unable to establish connection" error.

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by meara-algama** [comment] 2020-03-19 17:17
I've bee having the same issue, it happens several times a day, when I attempt to run a script. It's a real pain...

**Comment by T-CYH** [comment] 2020-03-20 08:09
I have installed RStudio 1.3 and the problem still persists, it shows Error: Unable to establish connection with R session in the console every time I run the code. I have R version 3.6.3 installed. What do you mean by RStuido 1.3 will give you lots of information instead of the "unable to establish connection" error?

**Comment by PRATIBHASORAM94** [comment] 2020-03-31 04:30
I'm an MTech last semester student. I was running a program regarding my final year project, and when I run the line write.table() to create a dataset from the previous data, my R session is aborted automatically and an error stating "unable to connect to R session". The program runs fine except when it reaches that particular line. I have R version 3.6.3 and RStudio 1.2.5033. Please help.

**Comment by hoplit11** [comment] 2020-04-19 05:40
In windows 10 go to security >firewall and network protection> allow an application thru the firewall >change configuration >Allow other aplication> put C:\ProgramFiles\RStudio\bin\rstudio.exe and select public and private necwork. >add >accept and restart the computer.

It work for me using RStudio-1.3.938.exe sorry for my bad english i hope it works for all of you.

**Comment by lucasmation** [comment] 2020-04-25 19:01
I am having the same problem.  I removed all my R's and Rstudio. Then did a fresh install of:
R4.0.0, then Rools40, then Rstudio Version 1.2.5042. the problem still occurs. 

Then I tried the suggestion above of using Rstudio 1.3 preview (I used version 1.3.947).  

It is not that it never works. It keeps alternating between working and not working, I could not detect any pattern

**Comment by maganod** [comment] 2020-04-30 02:30
I am also experiencing the same issue , uninstalled R many times and installed again from 3.6.1, 3.6.3, 3.6.4 and even 1.3 but I cant solve it. Can someone please help

**Comment by minnesotka** [comment] 2020-06-02 18:53
I echo the sentiment, happens on both fully up to date Mac and Windows 10. The code runs just fine in R console but not the R studio. Sometimes it takes a day or two of work to come to the stalling (when nothing happens forever when running a simplest line), other times it just stalls from the get go even for relatively small data sets and limited number of uploaded libraries. Restarting and closing other applications may or may not help. Has been happening since at least Fall 2019.

**Comment by scheum** [comment] 2020-06-19 22:56
This has been driving me crazy on Windows10, using local files. It works on the R, but not Rstudio.
I uninstalled/reinstalled R (4.0.1) and Rstudio (1.3.959) to no avail. I turned off and changed anti virus software settings (Windows Defender) which seemed to reduce crashing, but the errors continue. I pretty reliably have the "Unable to establish connection with R session" error occur if I do any of the following after not doing it for a while: type new code into a script, click install on the Packages tab, attempt to save a script, or run a line of code after pausing from running lines of code. But what seems to have gotten better is that after closing the window, the exact same action works.

**Comment by ronblum** [comment] 2020-07-21 15:42
I'm reopening because the issue still seems to be occurring in some cases. Or @jmcphers should this be a new issue?

**Comment by kevinushey** [comment] 2020-07-21 16:43
I think the problem here is that we don't have a reproducible example, and it's possible different users are encountering different issues that just so happen to be manifesting in similar ways.

Unfortunately, without a reproducible example there's just not a lot we can do.

**Comment by BarryDeCicco** [comment] 2020-08-13 00:08
I got this error when trying to start RStudio.  I ended up reinstalling it, and it worked.

**Comment by fernandovmacedo** [comment] 2020-09-07 02:52
> I think the problem here is that we don't have a reproducible example, and it's possible different users are encountering different issues that just so happen to be manifesting in similar ways.
> 
> Unfortunately, without a reproducible example there's just not a lot we can do.

Very likely. I can explain my specific issue and a solution.

I had a setup with R 4+ and Rstudio 1.3+ and suddenly this problem started to occur. Some days before my system were working fine, so I doubted that this was a bug introduced by R, Rstudio or a package. Just to be sure I've updated everything to the latest version and the problem kept ocurring.

The next suspect would be something that have changed on my operation system as a whole. I had not updated my windows 10, so probably it would be some software, likely malicious that was interfering with Rstudio.

Running windows defender it found two malicious software related to the "RelevantKnowledge" malware that infected my computer. After some steps removing it, my Rstudio came back to working properly.

I'm not willing to recreate the issue, but it can probably be done in a sandbox setting if one purposely infect a windows 10 OS with the RelevantKnowlege malware (I don't know how I got it exactly, but I belive you can download the same malware at https://www.relevantknowledge.com), after that I believe Rstudio will stop working.

**Comment by khizerkhan1991** [comment] 2020-09-07 04:44
This is the problem with R 4.x
I resolved this problem. 
- Uninstalled your R 
- Uninstalled your R Studio
- Installed R 3.4.2
- Installed R studio 1.1.463

**Comment by ManuelRangel-Rojas** [comment] 2020-09-21 15:26
khizerkhan1991  It totally works. Thaks!!

**Comment by Abdrandhawa** [comment] 2020-12-13 17:07
I have tried everything like uninstalling R and R studio then reinstalling R and R studio both repeatedly but nothing has worked.  don't even have any anti-virus. i tried to change the working directory  by choosing directory on the session menu but still same. 
its not importing any file. Its just making me mad. don't know what to do

**Comment by avialpha** [comment] 2020-12-26 08:17
> khizerkhan1991 It totally works. Thaks!!



> This is the problem with R 4.x
> I resolved this problem.
> 
> * Uninstalled your R
> * Uninstalled your R Studio
> * Installed R 3.4.2
> * Installed R studio 1.1.463

really worked thank you very much

**Comment by fipoucat** [comment] 2021-03-12 12:00
facing the same problem since a month, done all suggestions above, but still remains. R an R studio gurus please help

**Comment by dinilsonpedroza** [comment] 2021-06-03 21:37
I did everything that was suggested and it didn't work. I thought that with the Ubuntu update, the problem could be solved. Now, I believe that just formatting the PC again, the problem would stop happening. Well, but I want to give a suggestion here to people who are desperate. That's working for me: turn on the PC. Launch RStudio. The problem reappears. Exit RStudio. It doesn't matter, save the workspace or not. After exiting RStudio, click on the RStudio icon again. In my case the program works perfectly. This is not a definitive solution, but at least it has allowed me to work with RStudio.

**Comment by Hendrina1** [comment] 2022-02-18 08:16
I am having the same issue, it seems to occur for a specific project. I tried older version of R, but some won't even load my data. I considered saving my data files on my computer to try the codes in a 'new' project but since I can't even run a simple rdata code, I am stuck. After a whole day, it appeared to start working then the error came again.

Also every version of R I have installed since keeps crashing

**Comment by ronblum** [comment] 2022-02-18 12:21
@Hendrina1 Thank you for unstaling this! However, we no longer support version 1.1.463 of RStudio Desktop. Our [current release is version 2022.02.0+443 Prairie Trillium](https://www.rstudio.com/products/rstudio/download/), which was released yesterday. (We've changed the version method, but under the old numbering system, it would've been 1.6.) Are there any issues with this, or even the[ previous version, 2021.09.1 Ghost Orchid](https://www.rstudio.com/products/rstudio/older-versions/)?

**Comment by mikebessuille** [comment] 2022-06-13 18:22
The "unable to establish connection" error is a very generic error that might come about for many different reasons.  We've addressed some of these in recent releases (Prairie Trillium in particular).   This particular issue isn't really actionable the way it's written so closing this in preference to more specific problems.

**Closed by mikebessuille** 2022-06-13 18:22 UTC
Labels: bug, repro needed

**Comment by ajithramawickrama** [comment] 2023-04-06 02:36
I was getting this error even after trying so many installs uninstalls of both R and RStudio. Eventually disabling SELinux solved the issue

**Comment by mikebessuille** [comment] 2023-04-06 11:29
@ajithramawickrama that's great to hear that you were able to solve this problem!  SELinux is not yet supported though it is on our roadmap.
