### ISSUE TITLE
R-Studio starting only reports R not installed

### ISSUE THREAD

**Issue by tps800** [rstudio/rstudio#14454] opened 2024-03-20 10:04 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1+402
    OS Version      :  Windows 10 1809
    R Version       : 4.3.3, 4.2.3, 3.5.3

### Steps to reproduce the problem

Install R 4.3.2
Install R-Studio

Install R 4.3.3
Remove R 4.3.2

Start R-Studio. You'll be prompted by a dialog R is not installed. Possible actions:
- Open the default browser taking you to Rs website to download R.
- Do nothing.

R-Studio will, in neither case, start

### Describe the problem in detail

It is impossible to tell R-Studio R is installed, by changing the path to R

### Describe the behavior you expected

R-Studio starting, allowing to change the path to R, not just declining to start.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-03-20 11:47
@tps800 Thank you for raising the issue! Can you
- Provide the log files. They're located in `%localappdata%\RStudio\log`
- As a workaround, you can try the environment variable `RSTUDIO_WHICH_R` and point it directly at the executable.

**Comment by gtritchie** [comment] 2024-03-20 20:00
This is a duplicate of https://github.com/rstudio/rstudio/issues/14180 and will be fixed in the next release of RStudio (2024.04 / Chocolate Cosmos).

Details on the fix: https://github.com/rstudio/rstudio/pull/14197.

If you want to try it out before then, you can install a daily build from https://dailies.rstudio.com/. **Daily builds are for test purposes only and not recommended for general use.**

**Closed by gtritchie** 2024-03-20 20:00 UTC
Labels: bug, windows, startup
