### ISSUE TITLE
nested fenced code block messes up source highlighting in the editor

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#10079] opened 2021-11-12 17:43 UTC
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.1.0.199
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : R version 4.1.1 (2021-08-10)

### Steps to reproduce the problem

Open a new rmarkdown document and paste the following content

`````markdown
---
title: "Test"
output: html_document
---

# A Header

````{verbatim}
We can output arbitrary content verbatim.
  
```{r}
1 + 1
```

The content can contain inline code like
`r pi * 5^2`, too.
````

# Another header 

Some content
`````

### Describe the problem in detail

The source editor will not correctly recognized the nested chunk and it will mess up the highlighting
![image](https://user-images.githubusercontent.com/6791940/141510901-b1ece567-cf2c-4dd1-b92e-86d97083e242.png)

Example with the code chunk not being correctly highlighted, and headers not correctly found after the chunk.

### Describe the behavior you expected

This syntax is something rather new in **knitr**. Last version support nested chunks and some engine will benefit from this like the `comment` engine or the `verbatim` engine. 

WIth the current IDE behavior, it is rather hard to write and read such content. 

I would expect the highlighting of the Markdown document in the IDE to be the same as without nested chunk.

cc @yihui

**Comment by ronblum** [comment] 2021-11-12 18:57
Reproducible with older versions of RStudio as well, going back to RStudio Desktop 1.2.5042 on MacOS 12.

**Comment by kevinushey** [comment] 2021-11-12 19:12
I believe supporting this will require a few changes.

First, the chunk highlighter would need to become stateful, and track the number of backticks used in each chunk header / footer. That implementation lives here:

https://github.com/rstudio/rstudio/blob/main/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java

Second, the Ace highlight rules would need to become stateful as well. Those rules are activated here:

https://github.com/rstudio/rstudio/blob/686bc16e95ead41172a6b5ab9726a12007514c16/src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js#L58-L66

And the `embedRules()` helper lives here:

https://github.com/rstudio/rstudio/blob/686bc16e95ead41172a6b5ab9726a12007514c16/src/gwt/acesupport/acemode/utils.js#L98-L143

The `onMatch()` rule would need to both track and check the number of backticks that were matched, and only switch states when the "correct" closing number of backticks is seen.

**Comment by piiskop** [comment] 2023-03-06 19:36
It is 2023 and i have just reported the [same bug](https://github.com/rstudio/rstudio/issues/12788#issuecomment-1456166511).

**Comment by ronblum** [comment] 2023-07-19 14:54
This problem keeps popping up, including in #10703, #12788, #13384. Let's consolidate it in this issue.

Triage: Consider whether this should be higher than backlog-2, since it keeps coming up.

**Comment by bwu62** [comment] 2024-06-24 19:45
Also encountering this issue myself. Commenting here to bump and to subscribe to updates. Hope someone posts a resolution soon.

**Comment by kevinushey** [comment] 2024-07-02 07:03
Moving back to triage due to amount of user interest.

**Comment by rje42** [comment] 2024-07-03 08:26
I have encountered the same phenomenon with TikZ blocks.  See the image.
<img width="439" alt="Screenshot 2024-07-03 at 09 25 24" src="https://github.com/rstudio/rstudio/assets/5120639/8f75dd65-7347-4803-98c8-078c1f2ef71d">
Any fix would be greatly appreciated!

**Comment by ronblum** [comment] 2024-07-09 19:07
@rje42 What version of RStudio are you using?

**Comment by rje42** [comment] 2024-07-10 07:00
@ronblum the lastest one just downloaded: Version 2024.04.2+764. It still occurs!

**Comment by gtritchie** [comment] 2024-09-18 19:57
Verified in build 2024.10.0-186 on Mac. The expected region is now highlighted.

I opened a separate issue on code folding quirks in this scenario: #15191

**Closed by gtritchie** 2024-09-18 19:57 UTC
Labels: bug, r markdown, source editor, quarto, evaluate effort 🕐🗳🔎
