### ISSUE TITLE
Source column layout should be independent between RStudio instances

### ISSUE THREAD

**Issue by salim-b** [rstudio/rstudio#8107] opened 2020-10-19 19:42 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.949
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open _a single_ instance of RStudio and add one or more additional source columns, either 
   - by navigating to <kbd>Tools</kbd>→<kbd>Global Options…</kbd>→<kbd>Pane Layout</kbd>, clicking <kbd>Add Column</kbd> and <kbd>Apply</kbd>ing the changes, or
   - by choosing <kbd>View</kbd>→<kbd>Panes</kbd>→<kbd>Add Source Column</kbd>.

2. Open another RStudio instance. The source column layout is mirrored. Close one of the additional source columns in the new instance.

3. The corresponding source column is closed in the first RStudio instance as well. Super annoying!

### Describe the problem in detail

Both source column additions and removals seem to be shared between _all_ RStudio instances which seems to be a bad design choice.

### Describe the behavior you expected

I expected RStudio's source column layout to be independent between program instances.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment] 2020-10-19 20:07
Hi @salim-b thanks for bringing this issue up! We are storing the number of columns open so that the number of columns you have open remains consistent between sessions, but I do not expect columns to close because one is closed in another instance. I wasn't able to reproduce this in Ubuntu or MacOS, are you able to consistently reproduce this behavior?

**Comment by salim-b** [comment] 2020-10-19 20:40
Hey @melissa-barca

> are you able to consistently reproduce this behavior?

Yes. It happens _every single time_.

> We are storing the number of columns open so that the number of columns you have open remains consistent between sessions

So this is a single global number for all sessions/instances, right? Couldn't this be changed to a _per session/instance_ number? Other stuff like opened files etc. are also stored per session/instance AFAIC.

**Comment by melissa-barca** [comment] 2020-10-20 15:51
@salim-b there are definitely things we can do to make sure you don't lose a column when one is closed in another instance. I'm looking into this.

@rich-rstudio do you mind helping with a repro on this one?

**Comment by rich-rstudio** [comment] 2020-10-21 15:00
@melissa-barca I was able to reproduce on Ubuntu 20 and RStudio 1.4.954

**Closed** 2020-10-22 16:52 UTC
Labels: bug, reproducible, source editor

**Comment by salim-b** [comment] 2020-10-23 00:22
I can confirm that the source column layout is now async between _opened_ RStudio instances.

But the source column layout is still not saved on a per-project basis, i.e. still seems to be a _single_ global number for all sessions/instances. I guess this is what @melissa-barca pointed out in [this comment](https://github.com/rstudio/rstudio/pull/8143#issuecomment-713814434).

Should I open a separate issue for this (i.e. saving source column layout in `.Rproj.user/` and/or `.Rproj`)?

**Comment by melissa-barca** [comment] 2020-10-23 14:32
Thank you for confirming @salim-b! it looks like you found the right place to add your request.

**Comment by francisbarton** [comment] 2020-11-11 08:56
I was going to open a new issue but found this existing one here, which is close enough to my problem (I can reproduce the OP's issue).

If I have two RStudio projects/sessions open, and I have the additional source pane open in each one, if I then close one of the projects, this reverts to the "original" configuration without the extra source pane. This then *also closes the source pane in the other session*! If I then do Ctrl+1 to focus on Source, the original source quadrant pops up, and sometimes it seems to still display my open files, sometimes not. _So closing the source pane can lose my view of open, potentially unsaved files._

Luckily if I close the project and re-open, the unsaved files and work still seems to be there...

I feel like this issue is perhaps connected to my issue #8071 , in which I want an additional source pane displayed by default, without having to manually add it via the Global Options > Pane Layout menu each time.

**Comment by salim-b** [comment] 2020-11-11 10:49
> I'm going to upgrade to the latest and see if this fixes the issue for me.

this 👆

**Comment by francisbarton** [comment] 2020-11-11 11:16
> 
> 
> > I'm going to upgrade to the latest and see if this fixes the issue for me.
> 
> this 👆

LOL... yeah I'm sorry, I should have checked I was on the latest preview version before posting! Just done one quick test and it seems like it's not an issue for me now.

**Comment by kfeinauer** [comment] 2020-11-16 21:51
Verified fixed 1.4.1035
