### ISSUE TITLE
rserver auth redirect doesn't use www root path when X-Forwarded-Proto is set

### ISSUE THREAD

**Issue by ryanlovett** [rstudio/rstudio#8888] opened 2021-02-04 03:41 UTC
I'm using rserver in a jupyterhub single user environment with jupyter-server-proxy and a [patched jupyer-rsession-proxy](https://github.com/ryanlovett/jupyter-rsession-proxy/tree/www_root_path) with --www-root-path support. If X-Forwarded-Proto is set in the http headers, when a user visits the proxied path to rstudio for the first time, rserver will set the Location header to /auth-sign-in?appUri=%2F, even if www-root-path is set.

### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1522
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.3

### Steps to reproduce the problem
0. Have a proxy which happens to set X-Forwarded-Proto. This is present on mybinder.org for example. In my case I have an ssl terminating nginx proxy in front of jupyterhub that is setting it.
1. Invoke rserver in a user environment on a jupyterhub, e.g. `rserver --auth-none=1 --www-frame-origin=same --www-port=56789 --www-verify-user-agent=0 --database-config-file=/tmp/tmp_nt578pw --www-root-path=/user/me/proxy/56789/`
2. Visit {hub_url}/user/me/proxy/56789/
3. The user is redirected to {hub_url}/auth-sign-in?appUrk=%2F which produces a 404.

If one issues a curl request to {hub_url}/user/me/proxy/56789/ with all of the same headers except for X-Forwarded-Proto, the user is properly redirected the first time they visit the path to rstudio.

### Describe the problem in detail
With --www-root-path set to `/user/so-and-so/proxy/{some_port_num}/`, the user gets redirected to /auth-sign-in?appUri=%2F and not {www_root_path}/auth-sign-in?appUri=%2F. The former causes a 404.

### Describe the behavior you expected
The user is redirected to {hub_url}/{www_root_path}/auth-sign-in?appUri=%2F or just /{www_root_path}/auth-sign-in?appUri=%2F.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-02-09 16:16
@ryanlovett Thanks for filing this issue! Are you using the open source or professional version of RStudio?

**Comment by ryanlovett** [comment] 2021-02-09 17:43
@ronblum I'm using the open source version.

**Comment by ronblum** [comment] 2021-02-10 15:29
Thanks! I'll mark this for review as part of our ongoing development of RStudio.

**Comment by DavidSpek** [comment] 2021-02-18 10:58
I am running into a similar issue when trying to setup [images](https://github.com/kubeflow/kubeflow/pull/5582) for Kubeflow. I was using an Apache proxy in the image and experienced the `/auth-sign-in?appUri=%2F` when I had not set the `www-root-path`. After setting the `www-root-path` the auth redirection went to the proper URL. We would prefer to not use an Apache instance in the container image and rather use the URL rewriting built into Istio. During testing with Istio handling the URL rewriting I noticed that it does not seem compatible with setting the `www-root-path`. The problem for us at this point is that r-studio has a hardcoded redirect to `/auth-sign-in?appUri=%2F` that, in our case, doesn't seem fixable with the `www-root-path` setting. 

This is, of course, very specific to our environment for running images. However, I do think it highlights, along with the main topic of this issue, that the way the redirects are being handled for setting the cookie are not optimal.

**Comment by DavidSpek** [comment] 2021-02-18 12:17
Based on the comments in the following piece of code from the `Request.hpp` file, I think I might have found what could be causing problems (note, I am not a professional programmer nor do I have any experience with C++ so I am just going off the comments). 
```
   // Use the proxied URI when you need the closest guessing
   // of the address shown in the browser's address bar.
   // The host/port/protocol information returned here is always
   // correct but to get the path 100% right, a root path must
   // have been defined in the request or in an external header
   std::string proxiedUri() const;

   // The base URI will return:
   // - The internal URI when the root path is the default ("/")
   //   Empty is returned when `use = BaseUriUse::External`
   // - The proxied URI when the root path is defined as something else
   std::string baseUri(BaseUriUse use = BaseUriUse::Internal) const;

   // The path of the server as seen by the browsers, by default "/"
   // This is the path to be used for cookies or along with other path
   std::string rootPath() const;
   void setRootPath(const std::string& path) { rootPath_ = path; }
```
I believe `generateLoginPath` from `ServerLoginPages.cpp` is also relevant. Specifically, the line:
```
// generate url
   std::string signInPath = core::http::URL::uncomplete(request.baseUri(), auth::handler::kSignIn);
```

 To create the login path, `baseUri()` from `Request.hpp` is used. It seems as though to set the cookie, the `rootPath()` is being used, while it should probably be using the `proxiedUri()`. To me, it makes sense to use the URI that is based on the `path` header sent along with the request for setting cookies, as this is the address actually used by the client that is making the request.

**Comment by DavidSpek** [comment] 2021-02-18 14:59
I tried changing the `baseUri()` to `proxiedUri()` in the `generateLoginPath` section in `ServerLoginPages.cpp`, just to see if that would use the URI from the browser. However, it still redirected to `/auth-sign-in?appUri=%2F`.

**Comment by DavidSpek** [comment] 2021-02-18 15:15
It would seem that the functionality that is needed to avoid the `/auth-sign-in` redirect issues are available in R-Studio Server Pro. 
https://docs.rstudio.com/ide/server-pro/authenticating-users.html#proxied-authentication

Given that there are many environments where this functionality is somewhat necessary, is there an official way to start a discussion for adding proxied authentication to the open-source version of R-Studio?

**Comment by DavidSpek** [comment] 2021-02-23 21:14
Adding the `X-RStudio-Root-Path` header rather than `www-root-path` solves the 404 error I am seeing when proxying with Istio, even though they should be setting the same thing.

**Comment by Robinlovelace** [comment] 2021-03-16 08:32
Just checking in on this as could be useful for reproducible teaching with Binder planned with @vikkimaps and others, starting in summer. Am I right in thinking that the change in milestone from 1.5 to 1.6-1.7 means that there are no immediate plans to work on this @mikebessuille and that it will not be ready by then? 

Will be of great benefit to many people if its fixed sooner. Thanks.

**Comment by mikebessuille** [comment] 2021-03-16 12:34
unfortunately we don't have time to look at this until later this year.  It is not clear to me what changes we'd want to make and if this belongs in the open source product.

**Comment by DavidSpek** [comment] 2021-03-16 15:32
@mikebessuille I think the problem I describe in my previous comment (where `www-root-path` causes a 404 but the `X-RStudio-Root-Path` header does work) is an actual bug as both values should be doing the same thing.

**Comment by mikebessuille** [comment] 2021-05-04 13:31
@ronblum can you get someone to verify if this happens in both pro and open source server?  Jonathan says this is a recent regression, probably as of 1.4.

**Comment by mcg1969** [comment] 2021-06-04 15:00
I have found that setting the `X-RStudio-Proto` header to `https` solves the problem as well. As far as I can tell from the open-source code, it should be respecting `X-Forwarded-Proto`, but it's not. This seems to work for my scenario.

**Comment by ronblum** [comment] 2021-06-07 16:53
QA Note: To reproduce, a couple of options are possible:
1. Follow the steps above, with JupyterHub.
2. Use nginx as a path rewriting proxy with SSL termination.

[TY @jmcphers]

**Comment by mikebessuille** [comment] 2021-06-10 14:40
Related to https://github.com/rstudio/rstudio-pro/issues/2657

**Comment by mahsoud** [comment] 2021-07-25 09:55
Found that RStudio Server v1.4.1717; when deployed behind an AWS ALB that terminates SSL has an issue with sign in if since rstudio redirects always to HTTP, thus I am receiving "400 Bad Request: The plain HTTP request was sent to HTTPS port" from load balancer at redirect to /auth-sign-in

is this a separate issue?

**Comment by ronblum** [comment] 2021-12-23 14:13
The issue is raised as a [PSA in the Jupyter Community Forum ](https://discourse.jupyter.org/t/solved-latest-rstudio-will-not-work-with-jupyterhub-or-binder-use-r-version-4-0/10957/5), and marked as solved by using jupyter-rsession-proxy 2.0 or greater. Does this complete the circle?

**Comment by ryanlovett** [comment] 2022-01-04 19:09
Hi @ronblum. jupyter-rsession-proxy 2.0 has a workaround which rewrites the response from rserver. The issue is still present in rserver however.

**Comment by Armadik** [comment] 2022-05-27 14:07
I managed to get around this problem by changing the jupyter-server-proxy package
In part:
https://github.com/jupyterhub/jupyter-server-proxy/blob/main/jupyter_server_proxy/handlers.py

You need to add a header:
`headers['X-RStudio-Request'] = context_path + str(proxied_path)`

```
rstudio-server version
2022.02.0+443 (Prairie Trillium) for RHEL 8
```

**Comment by jprukner** [comment] 2022-07-21 12:16
I think this one could be related to https://github.com/rstudio/rstudio/issues/7953

**Comment by steverweber** [comment] 2022-09-01 22:36
I spent many hours on this one so posting this because perhaps helpful to others. A workaround for Jupyter-server-proxy is setting the `X-RStudio-Root-Path` header,
```
c.ServerProxy.servers['rstudio-server'] = {
        'command': ['.../bin/_proxy-rstudio-server.sh'],
        'request_headers_override': {
            'X-RStudio-Root-Path': f'/user/{user["name"]}/rstudio-server/',
        },
        'port': 0,
        'timeout': 30,
        'absolute_url': False,
        'new_browser_tab': True,
        'environment': { 'JPS_WWW_PORT':'{port}', 'JPS_BASE_URL':'/', 'JPS_APP': 'rstudio-server' },
        'launcher_entry': {
            'title': 'RStudio-server',
            'icon_path': '{{vars.jupyter_venv}}/share/jupyter/rstudio-logo.svg',
        }
    }
}
```

**Comment by sterlinm** [comment] 2023-05-31 02:59
> I spent many hours on this one so posting this because perhaps helpful to others. A workaround for Jupyter-server-proxy is setting the `X-RStudio-Root-Path` header,

I know it's been a while, but would you mind sharing what your `_proxy-rstudio-server.sh` script looks like? I think you've solved my problem but I can't quite get it working.

**Comment by s8weber-uw** [comment] 2023-05-31 12:20
@sterlinm Im using is `rstudio-server-2022.11.0-daily-214` IIRC when I tried a newer version it didn't work so I reverted.

**Comment by RRRajput** [comment] 2023-06-22 21:38
Is there any timeline on when this would be looked at?

**Comment by ryanlovett** [comment] 2023-06-28 01:05
@kevinushey This is worked around in jupyter-rsession-proxy as of https://github.com/jupyterhub/jupyter-rsession-proxy/pull/110. My inclination is to close this issue, and ask people to report still broken behavior at https://github.com/jupyterhub/jupyter-rsession-proxy/issues.

**Comment by kevinushey** [comment] 2023-06-28 18:13
Great -- thanks @ryanlovett!

**Closed by kevinushey** 2023-06-28 18:13 UTC
Labels: bug, triage, authentication
