### ISSUE TITLE
Feature request: support rendering matplotlib in the console

### ISSUE THREAD

**Issue by deliciouslytyped** [rstudio/rstudio#4965] opened 2019-06-17 23:24 UTC
This the feature request for some things mentioned at: https://community.rstudio.com/t/reticulate-rstudio-matplotlib/33219/9

Namely, it would be nice if things like matplotlib's `plt$show()` would also work in the console, as opposed to just in .Rmd files.

**Comment by ronblum** [comment] 2019-06-19 18:23
@deliciouslytyped Thank you for filing the issue. A few things:
1) Can you include a reproducible example of the steps to get to the issue? I've run through code from the Community page, but the code I tried worked.
2) Can you please provide the full environment you're working with?

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

Thanks!

**Comment by ronblum** [comment] 2020-01-03 18:45
Oops—this should've been marked as a feature request.

**Comment by deliciouslytyped** [comment] 2020-01-03 18:54
Have there been any changes implementing this since I filed the issue?
I'm not sure when I'll have time to take a look at this but I'll add it to my task list.

**Comment by deliciouslytyped** [comment] 2020-01-03 18:56
You do realize this had something to do with "automatically" showing plots, and not needing to render in the markdown mode? I don't remember the exact details, just checking.

**Comment by deliciouslytyped** [comment] 2020-01-03 20:57
I run the following snippet and nothing shows up:
```
library(reticulate)
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
plt <- import("matplotlib.pyplot")
fig <- plt$figure(figsize=c(14,8))
plt$plot(1:10,1:10)
plt$show()
```
reticulate: `1.14-9000`
python: `"3.7.5 (default, Oct 14 2019, 23:08:55) \n[GCC 8.3.0]"`
RStudio: `Version 1.2.1335` , I don't know what an edition is...the free one?
R version yields the following:
```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night  
```
I'm on NixOS and can provide a script reproducing the R environment, but I guess you dont use the Nix package manager?

**Comment by deliciouslytyped** [comment] 2020-01-03 20:58
If I run it without the `matplotlib$use("Agg", force = TRUE)` line the plot shows up in a separate window as expected.

**Comment by blairj09** [comment] 2020-02-07 19:06
RStudio Edition : Desktop Pro
    RStudio Version : 1.3.820-1
    OS Version      : macOS 10.15.3
    R Version       : 3.6.2

I'd like to expand on this issue. When editing and executing native Python code, matplotlib visualizations are rendered in the Plots pane:

![image](https://user-images.githubusercontent.com/10444878/74057266-cc55ee00-49a0-11ea-8738-e4af484ade49.png)

The script for the example above:
```python
import matplotlib.pyplot as plt
import numpy as np

x = np.random.normal(size = 1000)

plt.hist(x)
plt.show()
```

However, if you use `reticulate` and render matplotlib visualizations from R, they appear in an external window that also causes some odd RStudio behavior:

![image](https://user-images.githubusercontent.com/10444878/74057420-2060d280-49a1-11ea-8fbc-43ab9f47844d.png)

```r
library(reticulate)

plt <- import("matplotlib.pyplot")

x <- rnorm(1000)
plt$hist(x)
plt$show()
```

Notice in the screenshot that the R Session is blocked while the visualization is shown. If you attempt to close the visualization window, the R Session becomes unblocked but the window never actually closes and shows as _not responding_:

![image](https://user-images.githubusercontent.com/10444878/74057525-5dc56000-49a1-11ea-94b2-9842b5feca1f.png)

If the second window is forced to quit, the entire R session is aborted with the message 
```
R encountered a fatal error.
The session was terminated.
```

In my opinion, matplotlib visualizations generated from an R session should also render in the Plots pane, like they do when generated from python.

**Comment by kevinushey** [comment] 2020-02-07 19:14
The issue here is that currently, RStudio only injects its matplotlib hooks when the Python REPL is active:

https://github.com/rstudio/rstudio/blob/71cd0c27c5acc32b1ae0779e459d1ca039ced9e5/src/cpp/session/modules/SessionReticulate.R#L157-L179

We may want to always have this hook active when `matplotlib` is loaded.

**Comment by Doznkekz** [comment] 2020-02-21 19:05
I'm facing the exact same issues as @blairj09 
The code you provided @kevinushey works for me. Thank you so much! Would be amazing to have this integrated.

**Comment by kevinushey** [comment] 2020-08-26 21:47
Closed by https://github.com/rstudio/rstudio/issues/4965.

**Closed by kevinushey** 2020-08-26 21:47 UTC
Labels: backlog, enhancement, python

**Comment by deliciouslytyped** [comment] 2020-08-28 00:11
You mean #7619 ?

**Comment by kevinushey** [comment] 2020-08-28 05:51
Yes, sorry -- you are correct, the PR was https://github.com/rstudio/rstudio/pull/7619.

**Comment by dfalty** [comment] 2020-09-26 18:32
Verified both scenarios @blairj09 explained show up in the plots pane in RStudio with no issue. version 1.4.874
