### ISSUE TITLE
Lists inside tables don't indent on tab in Visual Editing

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#8731] opened 2021-01-12 23:39 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1103
    OS Version      : Red Hat 8.3
    R Version       : 4.0.3

### Steps to reproduce the problem

1. In Visual Markdown Editing mode, insert a table in an RMarkdown file.
2. Insert a list into one of the cells
3. Once there is at least one root level list item with text, attempt to indent another list item using tab.

### Describe the problem in detail

The editor moves the cursor to the next cell in the table.

### Describe the behavior you expected

The editor would take the "tab" action that is most relevant to the current cursor position (i.e. indent the current list item).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment] 2021-07-21 19:26
Closing as duplicate of https://github.com/rstudio/rstudio/issues/8935

**Closed by jjallaire** 2021-07-21 19:26 UTC
Labels: bug, in progress, visual markdown editing
