### ISSUE TITLE
YAML style chunk labels don't show up in document navigation menu in source mode

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#13818] opened 2023-10-19 14:35 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2023.12.0-daily+201 (2023.12.0-daily+201)
    OS Version      : macOS 13.5 (22G74)
    R Version       : 4.3.1

### Steps to reproduce the problem

Create a Quarto document with code chunks and label the chunks. Use a mix of old style (in curly braces) and YAML style chunk labels.

### Describe the problem in detail

YAML style chunk labels don't show up in document navigation menu in source mode. They show up in visual mode, and also old style labels do show up in both modes.

<img width="708" alt="Screenshot 2023-10-19 at 10 33 22 AM" src="https://github.com/rstudio/rstudio/assets/5965649/a60aeaf5-978b-4360-bbb0-fe55afde5886">

<img width="708" alt="Screenshot 2023-10-19 at 10 33 36 AM" src="https://github.com/rstudio/rstudio/assets/5965649/f91448f0-6be1-4fb3-8ce9-c0a1cbd9ee52">

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2023-11-06 22:28
I think this may be a duplicate of https://github.com/rstudio/rstudio/issues/13831?

**Comment by mine-cetinkaya-rundel** [comment] 2023-11-07 01:34
I think you're right @kevinushey

**Comment by jonvanausdeln** [comment] 2023-11-09 20:48
Closing as this is fixed in duplicate issee https://github.com/rstudio/rstudio/issues/13831

**Closed by jonvanausdeln** 2023-11-09 20:48 UTC
Labels: bug, regression, source editor
