### ISSUE TITLE
second inline equation in visual markdown get escaped

### ISSUE THREAD

**Issue by caeu** [rstudio/rstudio#8810] opened 2021-01-26 05:46 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 3.6.3
    OS Version      :  macOS Catalina 10.15.7 (19H114)
    R Version       : 1.4.1103

### Steps to reproduce the problem
Start a New R Notebook or R Markdown, activate visual mode, and type the below on the same line (not copy paste):
This equation would render $x=y^2$ but this one would not $x=y^2$

### Describe the problem in detail
The problem seems that only the first inline equation works. Any followup inline equation does not remove the escape from the pair of dollar signs after closing the equation. This how it looks like in source mode:

`This would work $x=y^2$ but this would not work \$x=y\^2\$`

Though adding a second inline equation would work using the 'insert menu' (unfortunately no direct shortcut)

### Describe the behavior you expected
Either it should work as expected, or maybe adding a the ability to assign shortcut to start an inline equation, rather than through (catch all).

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-01-26 16:16
@caeu Thank you for raising the issue! I can reproduce it in:
- RStudio Desktop 1.4.1507 on MacOS 11.1
- RStudio Server 1.4.1103 on SLES 15 SP2 using Chrome on MacOS 11.1

We'll review this as we continue development of RStudio.

**Comment by jjallaire** [comment] 2021-01-29 12:32
Fixed via: https://github.com/rstudio/rstudio/commit/2bce9bd186ddf77bea8dc38de79bf2c6054979df

**Comment by valerie-rstudio** [comment] 2021-02-01 22:32
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1535
    OS Version      : mac OS 11.1
    R Version       : 4.0.3

Verified that in both R Markdown files and R Notebooks multiple inline math equations written on the same line now appear correctly when typed in Visual Mode.

**Comment by R-Hannibal** [comment] 2021-02-12 16:27
Re-opening to test against the 1.4 Tiger-Daylily build.

**Comment by ronblum** [comment] 2021-02-16 16:09
Verified in RStudio Desktop 1.4.1106 Tiger Daylily on MacOS 11.3.

**Closed** 2021-02-16 16:09 UTC
Labels: bug, verified, visual markdown editing

**Comment by ronblum** [comment] 2023-02-16 14:16
@adambear91 This looks like the issue described at #12665. If so, it's fixed in [the latest dailies](https://dailies.rstudio.com/) for the upcoming Cherry Blossom release.

**Comment by adambear91** [comment] 2023-02-16 14:49
Ah, thank you!On Feb 16, 2023, at 9:16 AM, Ron Blum ***@***.***> wrote:﻿
@adambear91 This looks like the issue described at #12665. If so, it's fixed in the latest dailies for the upcoming Cherry Blossom release.

**Comment by ronblum** [comment] 2023-02-16 20:12
@adambear91 Just note that the dailies are meant for testing, not for production use.
