### ISSUE TITLE
improve hidpi support

### ISSUE THREAD

**Issue by jpritikin** [rstudio/rstudio#3715] opened 2018-10-20 13:49 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Ubuntu 18.04
    R Version       :  3.5

### Steps to reproduce the problem

I have a HiDPI laptop screen. I switch between 1080p (when docked) and my HiDPI resolution frequently. Every time I switch, I have to adjust the zoom in Rstudio to 100% or 150%.

### Describe the behavior you expected

Rstudio should detect my display resolution (like every other app) and fix the font size automatically.

**Comment by kevinushey** [comment] 2018-10-20 20:36
High DPI configurations should overall be better handled in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/). Would you be willing to give that a download and let us know if things appear improved in your case?

**Comment by jpritikin** [comment] 2018-10-21 22:06
My screen has 3200x1800 and it seems like RStudio only scales in integer 
multiples.

The menu titles are not scaled correctly either. See attached.

**Comment by kevinushey** [comment] 2018-10-22 21:28
Sorry, but your attachment didn't go through (e-mail attachments don't work with GitHub issues)

**Comment by jpritikin** [comment] 2018-10-22 21:33
Oops, here it is.
![screenshot from 2018-10-21 18-05-13](https://user-images.githubusercontent.com/2002771/47320821-8b598f00-d620-11e8-85d5-55612ec4c372.png)

**Comment by kevinushey** [comment] 2018-10-22 21:41
Thanks. Just to be clear, this is what you see with the latest preview release? Or was that screenshot with v1.1?

Do you have UI scaling turned on for your machine or anything similar?

**Comment by jpritikin** [comment] 2018-10-23 14:08
> Just to be clear, this is what you see with the latest preview release?

Version 1.2.1060

> Do you have UI scaling turned on for your machine or anything similar?

Maybe. How can I check?

**Comment by jmcphers** [comment] 2020-06-24 23:01
I'm closing this as it's been a year and a half since we had any info or reports and we haven't been able to reproduce ourselves.

@jpritikin you might try our new release, which uses an upgrade rendering engine and may resolve the issue:

https://www.rstudio.com/products/rstudio/download/preview/

**Closed by jmcphers** 2020-06-24 23:01 UTC
Labels: bug, repro needed
