### ISSUE TITLE
RStudio panes do not auto-refresh after resizing

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#6721] opened 2020-04-23 20:25 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.947
    OS Version      : Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Open RStudio with all 4 panes visible. RStudio window shouldn't be too small otherwise the problem will not show up. Try RStudio fullscreen with all 4 panes roughly equally sized.

2. Hide contents of Console pane by clicking on icon: 
![image](https://user-images.githubusercontent.com/12725868/80144462-369d2880-85b7-11ea-9ea0-9a939ba00b87.png)

3. Enlarge the hidden pane by clicking exactly on the indicated icon:
![image](https://user-images.githubusercontent.com/12725868/80144701-aad7cc00-85b7-11ea-8e15-7755a9821b1f.png)

4. The result – source pane is not loaded/auto-refreshed. Now click on the corresponding icon on source window:
![image](https://user-images.githubusercontent.com/12725868/80145328-aeb81e00-85b8-11ea-8351-2893ce89b8db.png)

5. The result – console pane is not loaded:
![image](https://user-images.githubusercontent.com/12725868/80145385-c4c5de80-85b8-11ea-90e4-3513b31744b9.png)

### Describe the problem in detail

Icons that resize panes work not as expected. Panes do not refresh automatically.

### Describe the behavior you expected

I expect behavior as in RStudio V1.2

**Comment by kevinushey** [comment] 2020-04-23 21:19
I can reproduce this on macOS as well. Note that the issue does not reproduce if you have the Accessibility option `[ ] Reduce user interface animations` enabled.

**Comment by kevinushey** [comment] 2020-04-23 21:29
Looks like this regressed with RStudio v1.3.734, in this PR:

https://github.com/rstudio/rstudio/commit/ca44a6b330fb042552791d243f999ee73d36eb34

@gtritchie would you be willing to take a look?

**Comment by gtritchie** [comment] 2020-04-23 22:56
@kevinushey Yup, looking into it.

**Comment by gtritchie** [comment] 2020-04-24 00:10
Here's the expected behavior, using 1.2.5042. It goes haywire starting in the third screenshot; in 1.2 the console fills the entire column. In 1.3 console is restored to its previous height but editor is blank.

<img width="786" alt="2020-04-23_16-58-38" src="https://user-images.githubusercontent.com/10569626/80161440-40a63380-8585-11ea-8d2c-851e3558c4f8.png">

<img width="782" alt="2020-04-23_16-59-03" src="https://user-images.githubusercontent.com/10569626/80161449-469c1480-8585-11ea-8d6e-20c6cf8cc33f.png">

<img width="787" alt="2020-04-23_16-59-30" src="https://user-images.githubusercontent.com/10569626/80161453-49970500-8585-11ea-90ae-a424b0c335de.png">

<img width="788" alt="2020-04-23_17-01-11" src="https://user-images.githubusercontent.com/10569626/80161459-4bf95f00-8585-11ea-9f82-13c1e43994db.png">

**Comment by gtritchie** [comment] 2020-04-25 17:26
Fixed in 1.3 via #6725

**Closed by gtritchie** 2020-04-25 17:26 UTC
Labels: bug, regression, workbench

**Comment by rich-rstudio** [comment] 2020-04-28 18:41
verified fixed on Version 1.3.951
