### ISSUE TITLE
Copy + paste breaks on macOS when clipboard managers installed

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1641] opened 2017-10-21 00:48 UTC
This has been reported in various places, although most recently https://support.rstudio.com/hc/en-us/community/posts/115009179688-RStudio-incompatible-with-clipboard-managers-on-MacOS-copy-paste-breaks-.

As far as I can tell, when other applications compete for clipboard access with RStudio, it can cause RStudio to get 'detached' from the pasteboard, so that attempts to copy + paste no longer succeed (although other sorts of weirdness have been reported by other users).

The related code lives around here: https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop-mac/GwtCallbacks.mm#L342-L360

Perhaps instead of requesting clipboard actions from the web view, we should just directly interact with the pasteboard ourselves.

**Comment by jmcphers** [comment] 2019-10-17 23:33
To my knowledge this hasn't been reported since we switched to QtWebEngine, and anecdotally I use a clipboard manager and have had no problems with it (across several macOS versions, RStudio versions >= 1.2, and clipboard manager versions). Closing unless we get further reports.

**Closed by jmcphers** 2019-10-17 23:33 UTC
Labels: bug

**Comment by kevinushey** [comment] 2019-10-17 23:53
I believe @jennybc has still observed issues sporadically, but we did ascertain it was related to some other clipboard-monitoring software installed on the machine.

**Comment by jennybc** [comment] 2019-10-18 01:42
I actually experienced this yesterday (unable to copy/paste but I could kill/yank with Ctrl-W/Ctrl-Y)! But restarting RStudio fixed it. I feel like I haven't seen this in a while. It's hard to say if the problem is gone or if my behaviour has changed to avoid the (risk of) this pain.

**Comment by kevinushey** [comment] 2019-10-21 14:58
IIRC we discovered that this was (potentially?) caused by GitKraken opening a surplus of file descriptors, and it seemed like opening so many file descriptors was the source of the problem.

**Comment by jennybc** [comment] 2019-10-21 15:28
s/GitKraken/SourceTree/

(The file descriptor leakage is why I switched to GitKraken.)

I don't remember a theory connecting these two particular things but we're putting this on ice any way.
