### ISSUE TITLE
Autocomplete doesn't prompt masked variables with native pipe

### ISSUE THREAD

**Issue by rjake** [rstudio/rstudio#9687] opened 2021-07-31 16:28 UTC
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.1717
    OS Version      : Windows
    R Version       : 4.1.0

### Steps to reproduce the problem
```r
library(tidyverse)

mpg |>
  mutate(x = manu...) # wait

mpg %>%
  mutate(x = manu...) # wait
```

### Describe the problem in detail
IntelliSense does't prompt me with variables from my data frame when I use the native pipe `|>` but they do when using the `magrittr` version `%>%`. When I start typing `manu`, it doesn't prompt me for `manufacturer`

![image](https://user-images.githubusercontent.com/14003618/127746067-5a997245-af75-4a86-bf3c-5a6dd948ce7e.png)

### Describe the behavior you expected
The columns of my data frame should show up for autocomplete.

![image](https://user-images.githubusercontent.com/14003618/127746076-7a8c1d5e-5db7-4838-8741-3c567c992a96.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-08-02 12:38
@rjake Thank you for raising this! I can reproduce this with the same release on MacOS 12 beta. However, it looks like this is fixed in the version current in development, Ghost Orchid 2021-08.0. If you're interested in trying it out, you can download [the latest daily builds](https://dailies.rstudio.com/) at https://dailies.rstudio.com/

Please note, though, that these builds are meant for testing purposes only and not for production use.

**Closed** 2021-08-02 12:38 UTC
Labels: autocompletion, bug
