### ISSUE TITLE
Error on saving - No such file or directory

### ISSUE THREAD

**Issue by chambox** [rstudio/rstudio#2037] opened 2018-01-23 09:56 UTC
### System details

    OS Version      : Ubuntu 16.04.3 LTS
    RStudio Version : 1.1.414
    R Version       : 3.4.3 (svn rev 73796)

### Steps to reproduce the problem

Open RStudio, make a new file and try to save it. When doing so, a popup emerges saying "No such file or directory."
The problem doesn't exist when RStudio is run as a superuser. It does appear both when working in and not in a project. It also existed in the previous version. It sometimes disappears and then comes back, but there's no clear pattern.

RStudio is installed by downloading the deb file and installing it using sudo as usual on a ubuntu system.

Fololowing errors are shown in the terminal when starting up rstudio from the terminal : 

QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
load glyph failed err=6 face=0x2cb9d70, glyph=2793
load glyph failed err=6 face=0x2cb9d70, glyph=2793
libpng warning: iCCP: known incorrect sRGB profile

Then even when typing, every time RStudio tries to save a temporary file, the error pops up again.

### Describe the behavior you expected
The file saving as it should.

This is a follow up to a previously reported problem : https://support.rstudio.com/hc/en-us/community/posts/115006836127--No-such-file-or-directory-RStudio-Server-error

1. The output of sessionInfo() 

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_BE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_BE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_BE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_BE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16   

2. The R code in question

Nothing specific

3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

When reopening RStudio to run the diagnostic report, the problem no longer existed. It automatically opened in the project where the problem was. When closing the project, the problem reappeared. The diagnostics report was run when it reappeared.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1655355/diagnostics-report.txt)

**Comment by JoFAM** [comment] 2018-01-23 09:59
Problem was first mentioned to me when helping out with the following project :

**Comment by kevinushey** [comment] 2018-01-23 16:47
This usually implies that, for some reason, your user account does not have write permissions to the folder at `~/.rstudio-desktop` (or `~/.rstudio` for RStudio Server). Does executing the following in the terminal

    sudo chown -R $(whoami) ~/.rstudio*

make a difference? Or, if this only reproduces in one particular project, you might need to run it on that project's (hidden) `.Rproj.user` folder, with e.g. this run from the terminal with the working directory as that project:

    sudo chown -R $(whoami) .Rproj.user

Unfortunately, we're still not sure what could cause RStudio to get into this state.

**Comment by JoFAM** [comment] 2018-01-23 16:56
@kevinushey This _usually_ implies that and was my first idea as well. But in that case the problem should be persistent, not appear at random. I might not have been clear enough, but we've been trying to get a consistent reproduction and failed to do so. It happens both in a project (sometimes) and when working without a project context (also sometimes). 

Other things we tried : 
 - When the problem wasn't there, opening a project or closing the one that's open. Sometimes this recreates the bug, sometimes not.
 - starting RStudio from the terminal versus starting it by clicking the icon. In both cases the problem occurs sometimes.
 - trying to save an already open file versus creating a new one. In both cases the problem occurs sometimes. 

The only thing that persistently prevents the problem from happening, is sudo rstudio.

I'll ask @chambox to test your suggestion and report back to you.

**Comment by chambox** [comment] 2018-01-27 00:48
I monitored rstudio for some days now after using `sudo chown -R $(whoami) ~/.rstudio*` and so far the problem seems to be solved!

**Comment by kevinushey** [comment] 2018-01-28 20:23
Glad to hear this resolved the issue. Let us know if it happens again and if you can isolate a reason as to why this occurred.

**Closed by kevinushey** 2018-01-28 20:23 UTC
Labels: bug, repro needed

**Comment by rupesh2017** [comment] 2018-04-05 02:10
root@greenseek-Vostro-14-5459:~# sudo chown -R $(whoami) ~/.rstudio*
chown: cannot access '/root/.rstudio*': No such file or directory

**Comment by Ahmedmohammed88** [comment] 2018-04-18 22:46
when I use lapply function i get this message Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file                            No such file or directory﻿

**Comment by jefferys** [comment] 2019-06-20 18:41
I am having a similar issue repeatedly but intermittently. I am repeatedly cleaning and building a package. This appears to affect only one project. An R console error message that occurred one of the times it happened (but not always) was:

`20 Jun 2019 18:30:48 [rsession-rstudio] ERROR system error 2 (No such file or directory) [path=, path=/srj/GitHub/Jefferys/CsawRun/CsawRun.Rproj]; OCCURRED AT: rstudio::core::FilePath rstudio::core::FilePath::childPath(const string&) const /home/ubuntu/rstudio/src/cpp/core/FilePath.cpp:973; LOGGED FROM: rstudio::core::FilePath rstudio::core::FilePath::childPath(const string&) const /home/ubuntu/rstudio/src/cpp/core/FilePath.cpp:976`

**Comment by jxu** [comment] 2020-10-18 22:41
I had the issue when restarting R session plus my filesystem was busy doing some backups.
