### ISSUE TITLE
Dragging file into console/source pane inserts filepath

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#14878] opened 2024-06-21 14:06 UTC
On macOS, clicking a file in Finder and dragging it into Terminal inserts the path to the file in Terminal. It'd be nice if the same happened in Rstudio. 

Cherry-on-top would be if the path RStudio inserted was *not* an absolute file path, but automatically resolved paths relative to the project directory, or inserted `~` for files outside the project but within the home directory.

**Comment by gtritchie** [comment] 2024-06-24 19:39
Closing as a duplicate of #4037.

**Closed by gtritchie** 2024-06-24 19:39 UTC
Labels: enhancement
