### ISSUE TITLE
rstudio 1.2+ crashes on launching, when performed from from windows remote desktop (windows 7)

### ISSUE THREAD

**Issue by chili1111** [rstudio/rstudio#4466] opened 2019-03-17 10:30 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio-1.2.1322.exe
    OS Version      :  Windows 7
    R Version       : 3.5.2 (64 bit)

When using windows remote desktop (windows 7), and I login to the server and try to launch Rstudio v1.2 it crashes immediately.  This does not happen when I reinstall various versions of Rstudio v1.1.  (On earlier versions of rstudio v1.2, I recall that it rstudio v1.2 did not crash, but black screens appeared in many of the rstudio windows (that were not part of my "main" monitor, and there are 4 screens).

Strangely, when I login directly to the machine at my work desk (no remote desktop), rstudio v1.2 loads no problems and I have no issues.

While I would like to provide diagnostics report, the output of this report contains sensitive work details, so at this stage am hesitant to do so (Apologies).  Also, the problem is extremely easy to reproduce - just launch rstudio v1.2 from within windows remote desktop (windows 7) and hopefully it's not just me.

**Comment by kevinushey** [comment] 2019-03-18 07:00
You might have better luck with software rendering -- try holding down the <kbd>Ctrl</kbd> key while RStudio is launched, and then select Software Rendering in the dropdown at the bottom.

**Comment by jmcphers** [comment] 2019-03-18 19:57
Will be curious to hear if this helps; we do try to default to software rendering over RDP for this reason.

https://github.com/rstudio/rstudio/blob/84b037e51f1489b68aa63ca9d7718f13ff8b2ab2/src/cpp/desktop/DesktopMain.cpp#L286-L290

**Comment by chili1111** [comment] 2019-03-22 10:47
Apologies for not replying sooner.  Yes; Rstudio v1.2 now loads successfully without crashing from a remote desktop session when software rendering is used!  Thank you for providing this workaround(?)

**Comment by kevinushey** [comment] 2019-03-22 11:43
Interesting. The page at https://docs.microsoft.com/en-us/windows/desktop/termserv/detecting-the-terminal-services-environment suggests we may also need to check a registry key at

> HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Terminal Server\GlassSessionId

for certain GPU-accelerated remote sessions.

**Comment by jmcphers** [comment] 2019-03-22 15:04
Okay, we'll treat this as a patch bug to add that check!

**Comment by jmcphers** [comment] 2019-04-03 16:48
Fixed via https://github.com/rstudio/rstudio/pull/4547.

**Closed by jmcphers** 2019-04-03 16:48 UTC
Labels: bug, desktop, windows

**Comment by ronblum** [comment] 2019-06-07 17:36
@chili1111 Would you be willing to check if the problem is resolved when setting rendering to "auto-detect" using the current [RStudio preview release](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by chili1111** [comment] 2019-06-18 02:19
@ronblum Apologies for the delay. I can confirm that the problem seems resolved on windows 7 when logging in remotely. The current Rstudio preview version works just fine.

**Comment by ronblum** [comment] 2019-06-18 20:21
@chili1111 No problem—thank you for checking, and for confirming the fix!
