### ISSUE TITLE
Columns in Viewer are very wide when variable labels are displayed

### ISSUE THREAD

**Issue by datarichard** [rstudio/rstudio#2383] opened 2018-03-13 03:55 UTC
### System details

    RStudio Edition : 
    RStudio Version : 1.1.383
    OS Version      : macOS 10.13.3
    R Version       : 3.4.3 Kite-Eating Tree

### Steps to reproduce the problem
View a dataframe/tibble with long variable labels. Drag the column separator to make it narrow and show more columns.
<img width="1280" alt="screen shot long variable label" src="https://user-images.githubusercontent.com/28824961/37321835-55ca1050-26ce-11e8-916f-dea5990b5d27.png">

### Describe the problem in detail
The column header in Viewer displays the variable name and the variable label. When the variable label is very long the Viewer cannot display many columns. If I drag the column separator the column header width does not change with the column width, leading to columns out-of-line. (see screenshot)
<img width="1280" alt="screen shot dragged column separater" src="https://user-images.githubusercontent.com/28824961/37321831-50a6a1f6-26ce-11e8-88af-39bddbce6155.png">

### Describe the behavior you expected
Dragging the column separator should keep the column header in-line.

**Comment by ronblum** [comment] 2018-03-13 18:42
@datarichard Thank you for raising the issue; we'll review it as we work on development and bug fixes.

**Comment by etienne-s** [comment] 2018-03-14 11:41
Duplicate of #1665?

**Comment by ronblum** [comment] 2018-03-14 13:19
@etienne-s Yes, it is—thank you!

**Closed by ronblum** 2018-03-14 13:19 UTC
Labels: bug
