### ISSUE TITLE
No autocomplete for code snippet when using snippet within a function

### ISSUE THREAD

**Issue by c-brendel** [rstudio/rstudio#13441] opened 2023-08-02 06:48 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1+524
    OS Version      : Microsoft Windows 10 Enterprise 10.0.19045 version 19045
    R Version       : 4.0.3 & 4.3.1

### Steps to reproduce the problem

Add the following code snippet to RStudio to copy directory paths from Windows Explorer and format them for use in R scripts:
```
snippet format_path
	"`r gsub('"', "", gsub("\\\\", "/", readClipboard()))`"
```

Then, try to use the code snippt within a function:
```
library(data.table)
fread()
```
![image](https://github.com/rstudio/rstudio/assets/77961465/1d8eac78-4c1e-41da-82bf-e5dd69111b04)

### Describe the problem in detail
In newer versions of RStudio (e.g. 2023.06.1+524), the snippet does not appear if I try to call it from within a function:
![image](https://github.com/rstudio/rstudio/assets/77961465/1d8eac78-4c1e-41da-82bf-e5dd69111b04)

The snippet does, however, appear as long as I don't try to use it within a function:
![image](https://github.com/rstudio/rstudio/assets/77961465/929e9f1f-20a2-4ab3-a309-def47cab180e)

I tried using both R versions 4.0.3 and 4.3.1, but got the same result.

### Describe the behavior you expected

In RStudio Version 2022.07.2+576 (and I think older versions), I could use the snippet from within a function:
![image](https://github.com/rstudio/rstudio/assets/77961465/ff3e6421-e1fd-45b8-be6c-dbfb6837e2d4)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by c-brendel** [comment] 2024-01-30 06:35
Commenting to keep issue open...

**Comment by anejzver** [comment] 2024-03-01 09:52
I'd appreciate a resolution as well, it makes using snippets a lot more tedious.
#13613

**Comment by olivroy** [comment] 2024-03-27 14:30
I used this feature a lot. (still present for RStudio 2024.04.0+558) Maybe regression introduced in https://github.com/rstudio/rstudio/pull/12605

For example I had repetitive variable creation statements.


```r
# creating many logical flags
library(dplyr)
mtcars |> 
  mutate(age = sample(0:15, size = nrow(mtcars), replace = TRUE)) |>
  mutate(
    age_0_5 = age |> between(0, 5),
    age_6_10 = age |> between(6, 10),
    age_11_15 = age |> between(11, 15),
    age_10_17 = age |> between
  )
```

with my snippet being: 

```
  snippet age
	age_${1:age_min}_${2:age_max} = age |> between(${1:age_min}, ${2:age_max}), 
```

There is probably a better way to achieve this without it, but I liked the snippet approach.

**Comment by kevinushey** [comment] 2024-08-20 18:55
Associated code: https://github.com/rstudio/rstudio/blob/2dbb4d489a25fbd698ace35286f6de677c413de6/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java#L411-L425

https://github.com/rstudio/rstudio/blob/2dbb4d489a25fbd698ace35286f6de677c413de6/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java#L289-L294

I think the main intention was to avoid providing snippet completions following extraction operators like `$`, but that later evolved to suppressing them within function calls as well. Maybe that's too aggressive?

**Comment by olivroy** [comment] 2024-08-21 12:39
Yes, I think it is a good idea to avoid snippets in extraction, such as `$` and `[`, but in function calls, it would be great if they were accepted. (I would be okay if they were simply present, but demoted)

**Comment by dlill** [comment] 2024-09-17 10:20
Hello everyone, thanks for raising this issue. I use snippets a lot inside data.table's `[` operator. An alternative solution would be to provide the users options for setting the desired behavior?

**Comment by olivroy** [comment] 2024-09-17 11:38
Agreed that inside `[` is desirable since RStudio doesn't do column string completion anyway

**Comment by olivroy** [comment] 2024-10-31 12:56
Looks great with the new daily! 2024.11.0+341. Will continue testing! Thanks for fixing

**Comment by gtritchie** [comment] 2024-11-06 20:55
Thanks @olivroy!

I've also done verification using build 2024.11.0-daily+345, and am closing this.

**Closed by gtritchie** 2024-11-06 20:55 UTC
Labels: bug, snippets
