### ISSUE TITLE
The Connections pane hangs indefinitely when attempting to re-establish a Spark connection via a New R Script.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#8198] opened 2020-10-26 21:55 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.972
    OS Version      : macOS 11.0 Beta (Big Sur)
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Login to the IDE > Navigate to Connections pane > New Connection > Spark > Select 'OK' on the New Connection dialogue.
2. After the connection is established, disconnect from the connection ('Disconnect from a connection' button) > Yes.
3. Select the Connect dropdown in the Connections pane > select New R Script.

### Describe the problem in detail
A 'Connecting' message and progress spinner appear in the Connections pane and hangs there indefinitely (never seen it clear, stopped timing after 5 minutes).

![Connections Pane Hang](https://user-images.githubusercontent.com/62304541/97232700-a4671e80-17ab-11eb-995b-48080b0cf5ea.jpg)

### Describe the behavior you expected
I'd expect the same behavior seen in 1.3.1093: A new R Script is opened with the connection code, but the Connections pane itself remains static until the code in the R Script is run by the IDE user.

![Connections Pane Correct](https://user-images.githubusercontent.com/62304541/97232831-e6906000-17ab-11eb-9542-761a99d252aa.jpg)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment] 2020-10-26 21:57
Adding this issue to 1.4 for consideration in the main release or patch since it is a regression from 1.3 functionality (it may not be serious enough for either, but I'd like it looked at 👍).

**Comment by kevinushey** [comment] 2020-10-27 19:11
I wasn't able to reproduce with macOS 10.15.7 (Catalina). Could this be specific to Big Sur?

**Comment by R-Hannibal** [comment] 2020-10-29 20:48
@kevinushey - Just re-tested after the Big Sur update to 11.0.1, and I'm still getting the same behavior. My ability to confirm on Catalina is limited since I updated to Big Sur without a Catalina back-up plan (😒).

@ronblum - if you have time could you confirm this issue? We're wondering if it is Big Sur specific (or if it's even consistent on Big Sur for you).

**Comment by mikebessuille** [comment] 2020-11-02 18:03
Is there a workaround?  Does restarting make this work?

**Comment by kevinushey** [comment] 2020-11-04 19:35
Assigning to @ronblum for attempt to repro.

**Comment by ronblum** [comment] 2020-11-04 20:24
I can't reproduce this on Big Sur nor Catalina. It take about 5 seconds until the connect completes, then another 5 seconds for objects to load (there aren't any), but the connection completes.

**Comment by kevinushey** [comment] 2020-11-18 18:40
I am still unable to reproduce, even with macOS 11.0.1.

**Comment by kevinushey** [comment] 2020-11-18 19:23
EDIT: after screen-sharing with @R-Hannibal, I realized I wasn't following the repro steps correctly. I _am_ able to reproduce following the steps properly. (I blame 2020 for my lack of reading comprehension...)

**Comment by R-Hannibal** [comment] 2020-11-18 19:28
This was on the latest Daily Build (1.4.1043), MacOS 11.0.1. Thanks for taking a look with me @kevinushey. 

Leaving in 1.4 for now, if this starts to spiral on us or the fix is deep in the codebase/risky I think we should move out of 1.4 as the use case which causes the issue seems pretty uncommon.

**Comment by kevinushey** [comment] 2020-11-18 19:32
This shouldn't be a risky fix -- I'm taking a look now and it looks like an unexpected null exception that "in theory" shouldn't be happening.

**Closed** 2020-11-18 23:07 UTC
Labels: bug, connections, regression

**Comment by melissa-barca** [comment] 2020-11-20 18:25
Verified in 1.4.1052-1
