### ISSUE TITLE
Autocomplete for integer column names missing backticks

### ISSUE THREAD

**Issue by dchiu911** [rstudio/rstudio#6687] opened 2020-04-17 17:57 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.944
    OS Version      : Windows 10 x64
    R Version       : 3.5.3

### Steps to reproduce the problem
Release RStudio screenshot
![screenshot_RStudio_1 2 5042](https://user-images.githubusercontent.com/8665632/79598921-8e103580-8099-11ea-9c3b-e9028321ba4a.PNG)

Preview RStudio screenshot
![screenshot_RStudio_1 3 944](https://user-images.githubusercontent.com/8665632/79599288-17276c80-809a-11ea-9dbc-a0949ceecaef.PNG)

### Describe the problem in detail

For non-syntactical column names, the autocomplete should wrap the name with backticks. This works for column names with spaces for example, but not when it is an integer (e.g. 1)

This bug was introduced somewhere around 1.3.937 or 1.3.938, I just installed 1.3.944 and verified that the problem persists, then reverted back to 1.2.5042 and saw that the problem did not appear.

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-04-21 18:05
@dchiu911 Thank you for raising the issue! I can reproduce it on MacOS 10.15.4. We'll review this issue a we continue RStudio development.

**Comment by ronblum** [comment] 2023-06-30 17:34
Closing as duplicate of #13290 but referencing it for the history.

**Closed by ronblum** 2023-06-30 17:34 UTC
Labels: bug, reproducible, autocompletion, regression
