### ISSUE TITLE
Crash with Nouveau driver

### ISSUE THREAD

**Issue by paulmenzel** [rstudio/rstudio#5818] opened 2019-12-03 13:22 UTC
### System details

    RStudio Edition : Desktop Server
    RStudio Version : 1.2.1335
    OS Version      : GNU/Linux 4.19.x
    R Version       : 3.6.1

Probably related to [*Troubleshooting RStudio Rendering Errors*](https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors).

RStudio 1.2.1335 crashes quite often under GNU/Linux with the Nouveau driver on the device below.

    $ lspci -nn -s 1:00
    01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF108GL [Quadro 600] [10de:0df8] (rev a1)
    01:00.1 Audio device [0403]: NVIDIA Corporation GF108 High Definition Audio Controller [10de:0bea] (rev a1)

The driver has concurrency issues, so the developers suggest to disable hardware acceleration. Using *Software* as *Rendering Engine* fixes the issue here too.

**Comment by kevinushey** [comment] 2019-12-03 17:06
You can also try using the proprietary drivers provided by NVIDIA as opposed to the Nouveau drivers.

**Comment by paulmenzel** [comment] 2019-12-03 17:14
> You can also try using the proprietary drivers provided by NVIDIA as opposed to the Nouveau drivers.

Thank you for the suggestion. We tried that path, and have too much trouble with proprietary third-party modules. The latest Linux kernel is often not supported on time (only LTS series), and they drop old devices from drivers. (I do not even want to spend time on looking up what driver version would be needed for Quadro 600 support.)

The Nouveau folks are working on a fix for the complicated multi-threading issue.

We decided to move to AMD graphics device, and hopefully the old baggage will phase itself out soon enough.

**Comment by paulmenzel** [comment] 2019-12-03 17:15
Not to mention, that RStudio should not crash on any system, so software rendering should be used on devices with Nouveau driver. (Especially in a multi-user environment, where users can start RStudio on different devices, it’s not a good idea to make this option user dependent.)

**Comment by ronblum** [comment] 2019-12-04 17:34
This appears to be a duplicate of #3781. Also, it includes a suggestion to set `QT_XCB_FORCE_SOFTWARE_OPENGL=1` as a possible solution, at https://github.com/rstudio/rstudio/issues/3781#issuecomment-510945125

**Closed by ronblum** 2019-12-04 17:34 UTC

**Comment by paulmenzel** [comment] 2020-01-03 14:01
I disagree, but I’ll reply in issue #3781.
