### ISSUE TITLE
Duplicated options for line wrapping while trying to activate Visual Editor

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12107] opened 2022-10-06 19:37 UTC
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.7.2.576
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

1. Open R Markdown document.
2. Try to activate the Visual Editor mode for the first time. A pop-up window appears with two options which state the same.

### Describe the problem in detail

Two options are the same. 

![image](https://user-images.githubusercontent.com/12725868/194402829-65fcb0dc-8417-4111-9bd8-94276ea838b4.png)

### Expected behaviour

I expect no duplicated options.

**Comment by romainfrancois** [comment] 2022-10-07 12:53
It's probably here: 

https://github.com/rstudio/rstudio/blob/8229045da7df6abf61c630a4c58af2a72d662a80/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/dialogs/VisualModeLineWrappingDialog.java#L113-L124

https://github.com/rstudio/rstudio/blob/8229045da7df6abf61c630a4c58af2a72d662a80/src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants_en.properties#L274

**Comment by romainfrancois** [comment] 2022-10-12 07:03
The 2 checkboxes seem to be about different things. `chkConfigureFile_` and `chkConfigureProject_ `.

**Comment by kevinushey** [comment] 2022-10-12 16:55
Looks like a regression from the i18n work.

https://github.com/rstudio/rstudio/commit/2796e02ef717f802178653f645905a66af53413d#diff-be3a065aac6dd12de71695129368d269f3f1c24f2d256d6457e11e0f7153a53bL120

https://github.com/rstudio/rstudio/commit/2796e02ef717f802178653f645905a66af53413d#diff-be3a065aac6dd12de71695129368d269f3f1c24f2d256d6457e11e0f7153a53bL129

Note that we previously distinguished the two buttons based on whether we wanted to apply the wrapping to only the document, or to the whole project.

**Comment by kevinushey** [comment] 2022-10-12 16:55
I'll fix this up.

**Comment by jonvanausdeln** [comment] 2022-10-20 20:00
@GegznaV , this should be fixed in the next release (later this year).  You can check on the latest daily build, found at https://dailies.rstudio.com/. Can you confirm if this has been resolved for you?

**Comment by GegznaV** [comment] 2022-10-25 10:11
Seems to be OK now:

![image](https://user-images.githubusercontent.com/12725868/197746360-510a2911-9c80-4c6d-8b57-1b7f963eee4b.png)


    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.12.0.286
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

**Comment by jonvanausdeln** [comment] 2022-10-26 15:54
@GegznaV Thank you for confirming!

**Closed by jonvanausdeln** 2022-10-26 15:54 UTC
Labels: bug
