### ISSUE TITLE
Crashes on 'Export' -> 'Copy to clipboard' -> 'copy plot'

### ISSUE THREAD

**Issue by benmarwick** [rstudio/rstudio#2831] opened 2018-05-22 18:29 UTC
### System details

    RStudio Edition : Desktop 
    RStudio Version :  1.2.654
    OS Version      : Windows 7
    R Version       : 3.5.0 

### Steps to reproduce the problem

First, run this code

```
library(ggplot2) # ggplot2_2.2.1.9000
ggplot(iris,
       aes(Sepal.Length,
           Sepal.Width)) +
  geom_point()
```
Second, in the plots pane, click 'Export' then 'Copy to clipboard', then on the popup, click 'copy plot'

### Describe the problem in detail

RStudio crashes when attempting to copy a plot to the clipboard from the Plot->Export->Copy to clipboard command

### Describe the behavior you expected

RStudio crashes, like so:

![image](https://user-images.githubusercontent.com/1262179/40382298-e8946352-5db2-11e8-979e-859dafb80621.png)

**Comment by jmcphers** [comment] 2018-05-22 20:19
Confirmed repro on Windows 7 x64.

**Comment by jmcphers** [comment] 2018-05-22 20:28
Appears to be segfaulting in Qt5WebEngineWidgets.dll, in `qt5webenginewidgets!QWebEnginePage::triggerAction`, with `NULL_POINTER_READ`.

**Comment by dcolette** [comment] 2018-06-26 14:40
I observed the same problem with Desktop RStudio Version 1.2.747, R version 3.4.4 and Windows 10 x64 using the exact same steps of above reproducible example and any attempt to display even a standard plot like and then copy it to clipboard:
x <- rnorm(10)
y <- rnorm(10)
plot(x, y)
Only difference is RStudio crashes without any warning message.

**Comment by dcolette** [comment] 2018-06-27 20:11
That's indeed only for bitmap.

**Comment by jmcphers** [comment] 2018-07-10 17:03
Looks like this is also a problem on Linux; see #3136.

**Comment by rmflight** [comment] 2018-07-10 17:20
Yep, confirmed on Linux, Ubuntu 16.04, RStudio v 1.2.778.

**Comment by kevinushey** [comment] 2018-07-10 17:41
I don't see the crash with RStudio v1.2.805 on Linux (using the Qt 5.11.1 build) so I suspect this issue may have been fixed with the Qt update.

**Comment by pascaloettli** [comment] 2018-07-11 01:16
@kevinushey  I confirm there is no crash with RStudio v1.2.805 on Ubuntu 18.04, but nothing is copied to the clipboard.

**Comment by kevinushey** [comment] 2018-07-11 17:59
I can also confirm that while we no longer have a crash, attempting to copy the plot through this mechanism fails to copy anything at all.

Note that copying the plot through the right click context menu (Right Click -> Copy Image) does work as advertised, so at least that is a way out for now.

@jmcphers: do you recall the motivation behind why we allowed for copying a plot as a bitmap vs. a metafile? Should we consider taking that out now and always copy as a metafile (or use the same codepath as Right Click -> Copy Image if possible)?

**Comment by jmcphers** [comment] 2018-07-11 18:09
I'm pretty sure Right Click -> Copy Image has never worked before. Copy Bitmap has always been somewhat problematic as it basically works by snipping out the region of the screen containing the plot, and can get it wrong in some mixes of DPI/zoom settings.

I think people are probably used to using Copy Bitmap for most plot exports (bitmaps are much more universally supported than metafiles) so there's likely to be some confusion if we take it out. I think we should keep the existing Copy Bitmap option, but try to wire it up to the browser's image copier as you suggest.

**Closed** 2018-07-11 22:49 UTC
Labels: bug, desktop, qtwebengine
