### ISSUE TITLE
automatic indentation not working properly in .R files

### ISSUE THREAD

**Issue by majazaloznik** [rstudio/rstudio#14829] opened 2024-06-12 07:42 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for windowsMozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.4.555
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : 4.3.2 (2023-10-31 ucrt)

### Steps to reproduce the problem
Type any sort of code which requires indentation and press enter 

### Describe the problem in detail
Pressing enter places the cursor in the correct position (in my case 2 spaces further than the previous line) *for one blink of the cursor*, then the cursor repositions itself all the way to the left. If you start typing right away (i.e. within about one second of pressing enter), the text is in the correct place, but a second later the text is positioned all they way to the left. At this point you can press Ctrl+I to correctly indent the line you are on. 

### Describe the behavior you expected
I would expect the cursor to remain in the correctly indented poistion. 

This are my settings to the degree they might be relevant:

![image](https://github.com/rstudio/rstudio/assets/7770285/054ca477-3aec-4005-be0e-5c521f3fe177)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-06-12 14:47
@majazaloznik Thank you for raising this! I'm unable to reproduce this, though, with the same version and option settings. Can you provide an example of code, however simple, that causes this? I realize that you say that this happens with any code, but I want to make sure that I reproduce exactly the same as you. Thanks!

**Comment by majazaloznik** [comment] 2024-06-12 15:20
it's really anything e.g.

```
df |>
pull(a)
```

what i have just noticed though, is that this doesn't happen in an unsaved file. But as soon as the file is saved, the cursor starts jumping back

**Comment by Robinlovelace** [comment] 2024-07-02 05:43
I have this too: confirmed!

**Comment by Robinlovelace** [comment] 2024-07-02 05:45
But cannot currently reproduce with reprex, so must be intermittent...

**Comment by kevinushey** [comment] 2024-07-02 07:01
Please let us know if the issue occurs again -- it's also possible it might depend on the document contents, so if the issue occurs, please share the contents of the document wherein you saw this.

**Comment by majazaloznik** [comment] 2024-07-20 19:04
I think I've figured it out 😅

It's the autosave setting... I had it set to "save and write changes" when editor is idle for 1000 ms. You can either extend the time to up to 10 seconds, or switch to jsut "backup unsaved changes" and the "issue" disappears. 

Sorry for the hassle 🙄

**Comment by kevinushey** [comment] 2024-07-22 03:24
Thanks! That makes sense, and we're most likely trimming horizontal whitespace on save (leading to the cursor position changing in that way).

Perhaps we shouldn't trim whitespace during autosave; instead, only do that on explicitly-triggered saves?

**Comment by ronblum** [comment] 2024-09-26 15:54
I'm unable to reproduce the problem, even after changing my autosave settings, etc., as described above. @majazaloznik or anyone else, would you be will to try out the latest Kousa Dogwood daily with the fix? They're available at https://dailies.rstudio.com/rstudio/kousa-dogwood/ . But please not that these are development builds meant only for testing, not production.

**Comment by ronblum** [comment] 2024-10-16 20:09
Closing. If anyone still runs into issues with this, please let us know!

**Closed by ronblum** 2024-10-16 20:09 UTC
Labels: bug, source editor, need help verifying

**Comment by egouldo** [comment] 2025-01-24 03:31
I've been having this issue for over a year now, it persists through most RStudio updates, but is intermittent so not always reproducible. Running `2024.12.0+467 Kousa Dogwood (desktop)` with the following:

``` r
sessioninfo::platform_info()
#>  setting  value
#>  version  R version 4.4.0 (2024-04-24)
#>  os       macOS Ventura 13.6.9
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Australia/Melbourne
#>  date     2025-01-24
#>  pandoc   3.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)
```

<sup>Created on 2025-01-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Quitting RStudio and re-opening it seems to fix the issue.
