### ISSUE TITLE
Menu bar is white in a dark theme

### ISSUE THREAD

**Issue by Tomas-Pe** [rstudio/rstudio#12844] opened 2023-03-15 17:15 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 
    RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
    OS Version      :  Windows 10
    R Version       :  4.1.1

### Steps to reproduce the problem
Update Rstudio to 2022.12.0 Build 353. 
Set a dark mode in Global Options -> Appearance

### Describe the problem in detail
The menu bar is white instead of dark-blue
![image](https://user-images.githubusercontent.com/68933557/225388377-c8d5b1d4-4f5a-489e-b5f6-92b7ebb223bc.png)
![image](https://user-images.githubusercontent.com/68933557/225388536-65794ae0-54c0-4f33-aa50-5f672f4ac653.png)

### Describe the behavior you expected
The menu bar should be dark in a dark mode, as in the previous Rstudio versions.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2023-03-15 17:37
Duplicate of #12247

**Closed by gtritchie** 2023-03-15 17:37 UTC
Labels: bug, duplicate, new
