### ISSUE TITLE
Empty document not produced for RMarkdown

### ISSUE THREAD

**Issue by webbedfeet** [rstudio/rstudio#6386] opened 2020-03-03 02:45 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.842
    OS Version      : Mac OS 10.13.6
    R Version       : 3.6.0

### Steps to reproduce the problem
File >  New File > R Markdown ...
Then in pop-up, press "Create Empty Document"
Then I get a pop-up error "No such file or document"
![image](https://user-images.githubusercontent.com/370335/75737897-dc769a00-5cce-11ea-86da-fb088da2bfd3.png)

### Describe the problem in detail
When I want to create a new R Markdown document, the pop-up window gives me the option to "Create Empty Document". When I press that button, I get an error stating that no such document exists.
### Describe the behavior you expected
A blank R Markdown document should open in the editor pane of RStudio

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-03-03 16:33
@webbedfeet Thank you for filing the issue. I can't reproduce it by default—only by removing the default template file. Can you check if the file at
`/Applications/RStudio-1.3.842.app/Contents/Resources/resources/templates/document.Rmd`
exists and has the correct read permissions?

**Comment by kevinushey** [comment] 2020-03-03 17:46
I believe this was addressed by @jmcphers with https://github.com/rstudio/rstudio/pull/6358. Do you see this behavior in the latest preview release?

**Comment by jmcphers** [comment] 2020-05-01 00:52
Indeed #6358 should address this (please feel free to reopen if it doesn't!)

**Closed by jmcphers** 2020-05-01 00:52 UTC
Labels: repro needed
