### ISSUE TITLE
Include index.qmd file in new Quarto projects

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11945] opened 2022-09-13 21:14 UTC
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : N/A
    OS Version      : N/A
    R Version       : N/A

### Steps to reproduce the problem

1. <kbd>File -> New Project</kbd>
2. <kbd>New Directory -> Quarto Project</kbd>
3. Pick a project name, such as `qoqo`
4. <kbd>Create Project</kbd>
    - Three files get created: `_quarto.yml`, `qoqo.Rproj`, and `qoqo.qmd`

### Describe the problem in detail

In Quarto Websites, Books, and Blogs, one of the files created is `index.qmd`. In a basic project, though, a qmd file with the project name is created, such as `qoqo.qmd`. However, Quarto project like to have an `index.qmd` file in them—see issue #11883 for an example. In addition, while it's useful to have a default sample page, there's no need for it to use the project name.

### Describe the behavior you expected

Include a default sample `index.qmd` file in new Quarto projects instead of a qmd with the project name.

I'm marking this as an enhancement, although arguably it's a bug because of issues that the current behavior could cause.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by petetronic** [comment] 2023-09-26 18:53
Quarto team commented that this is not a bug

**Comment by kevinushey** [comment] 2023-09-27 17:46
Should we close this issue?

**Closed** 2023-09-28 09:05 UTC
Labels: enhancement, quarto

**Comment by ronblum** [comment] 2023-09-28 09:11
I don't know why I thought that the index file was needed, short of the #11883.
