### ISSUE TITLE
Keyboard shortcuts stop working when one clicks inside a dataset

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#5389] opened 2019-09-10 22:34 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1335
    OS Version      :  Ubuntu
    R Version       : 3.6.0

When a data frame is viewed using the View() function (or the F2 shortcut), if one clicks inside it (i.e., clicks on any cell, for example, to copy its content), then all the keyboard shortcuts including the default and customized ones will stop working.

PS. This will be fixed if one clicks on the header of the active document (in this case a view of a data frame) or any other document.

**Comment by ronblum** [comment] 2019-09-11 13:56
@hzarkoob Thank you for raising this. What browser and OS are you connecting from? Also, what are a few shortcuts that don't work? I want to try out the same environment as yours and make sure to overlap with the shortcuts you've tried out when trying to reproduce.  Thanks!

**Comment by ronblum** [comment] 2019-09-11 14:18
@hzarkoob I can reproduce this using RStudio Server 1.2.1335 on Ubuntu using Google Chrome (but not Red Hat or Firefox). It appears to be fixed in the [latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/), though. What happens when you try that? (Note that preview builds are intended for testing purposes only.)

**Comment by hzarkoob** [comment] 2019-09-11 18:38
@ronblum I actually saw this in Firefox 69.0 (64 bit). I use Firefox on both Windows and iOS systems. I will try to check the latest RStudio Preview for the above issue and let you know.

**Comment by hzarkoob** [comment] 2019-09-11 23:22
@ronblum I noticed the latest RStudio preview is available for Ubuntu 14 and 18. I am using Ubuntu 16. Can I still try the latest RStudio preview?

**Comment by hzarkoob** [comment] 2019-09-13 22:45
I verified that it is fixed in the latest RStudio Preview, 1.2.1578.

**Comment by ronblum** [comment] 2019-09-16 15:22
@hzarkoob Excellent, I'm glad it's all set!

**Closed by ronblum** 2019-09-16 15:22 UTC
Labels: accessibility, repro needed
