### ISSUE TITLE
Fix autocompletion of numeric column names

### ISSUE THREAD

**Issue by dchiu911** [rstudio/rstudio#12555] opened 2023-01-10 18:38 UTC
### System details

    RStudio Edition : RStudio Desktop
    RStudio Version : 2022.12.0+353 Elsbeth Geranium (desktop)
    OS Version      : macOS Ventura 13.0
    R Version       : R version 4.2.2 (2022-10-31)

### Steps to reproduce the problem

```r
df <- tibble::tibble(`1` = "a")
df$1
```

### Describe the problem in detail

Autocompletion of a numeric column name is missing surrounding backticks.

### Describe the behavior you expected

Autocompletion should include backticks:

```r
df <- tibble::tibble(`1` = "a")
df$`1`
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-01-24 21:12
@dchiu911 Thank you for raising this! It looks like a regression, as this was working in RStudio Desktop 2022.07.2+576 but no longer since 2022.12.0+353.

Ref: #11689

**Comment by dchiu911** [comment] 2023-01-31 19:39
Thanks @ronblum looks like the regression may have occurred a while back as I reported this in #6687

**Comment by ronblum** [comment] 2023-06-30 17:35
Closing as duplicate of #13290 for consolidation but referencing this for the history.

**Closed by ronblum** 2023-06-30 17:35 UTC
Labels: bug, autocompletion, regression
