### ISSUE TITLE
crash at startup: OpenGL context creation failed

### ISSUE THREAD

**Issue by dnacombo** [rstudio/rstudio#9451] opened 2021-06-04 11:48 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Linux Mint 19.3 Cinnamon 
    R Version       : 3.6.2

### Steps to reproduce the problem

Attempt starting Rstudio after unexpected termination (having to kill it).

### Describe the problem in detail

After having had to kill rstudio for some reason (out of memory, or desktop crash), the computer sometimes turns into a state where rstudio won't start anymore until I reboot.
This is what I get when starting from a terminal: 
```
> rstudio
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
[21302:21302:20210604,132402.784453:ERROR process_memory_range.cc:86] read out of range
[21302:21302:20210604,132402.784497:ERROR elf_image_reader.cc:558] missing nul-terminator
[21302:21302:20210604,132402.784653:ERROR process_reader_linux.cc:445] no module mappings 0x7f1747c1f000
[21302:21302:20210604,132402.786943:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.787212:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.788549:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.788605:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.789165:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.789204:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.789278:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.789317:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.789358:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.789455:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.789514:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.789552:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21302:20210604,132402.789590:ERROR elf_dynamic_array_reader.h:61] tag not found
[21302:21309:20210604,132402.809022:ERROR directory_reader_posix.cc:42] opendir: No such file or directory (2)
Aborted (core dumped)

```
### Describe the behavior you expected

Rstudio IDE start up.

This is the [diagnostics-report.txt](https://github.com/rstudio/rstudio/files/6598184/diagnostics-report.txt)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-06-07 13:42
@dnacombo Thank you for raising the issue! RStudio appears to be returning the same issue as in #9456, so I'm linking the two,

**Comment by gtritchie** [comment] 2022-01-26 17:33
We'll want to re-test this with the Electron build when available.

**Comment by JJ** [comment] 2022-12-11 18:08
Same error here, Ubuntu 20.04:

```
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/xdg/xdg-gnome:/etc/xdg/rstudio/logging.conf'. Logging to '/home/jmerelo/.local/share/rstudio/log/rdesktop.log'.
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
[75216:75216:20221211,190630.963982:ERROR process_memory_range.cc:86] read out of range
[75216:75216:20221211,190630.964026:ERROR elf_image_reader.cc:558] missing nul-terminator
[75216:75216:20221211,190630.964174:ERROR process_reader_linux.cc:445] no module mappings 0x7f5bcf4f0000
[75216:75216:20221211,190630.965885:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.966030:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967083:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967118:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967491:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967523:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967550:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967576:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967604:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967659:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967684:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967710:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967736:ERROR elf_dynamic_array_reader.h:61] tag not found
[75216:75216:20221211,190630.967976:ERROR file_io_posix.cc:140] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[75216:75216:20221211,190630.967985:ERROR file_io_posix.cc:140] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
[75216:75217:20221211,190630.969458:ERROR directory_reader_posix.cc:42] opendir: No such file or directory (2)
```

**Comment by mikebessuille** [comment] 2022-12-16 18:56
@JJ what version of the IDE are you using?  Can you please try the very latest (released yesterday!) 2022.12.0?

**Comment by JJ** [comment] 2022-12-16 19:31
I was using the 2022.07.2 version; it came back after I restarted the
machine and it's not happened ever since. I will definitely upgrade and
report if the bug returns.

**Comment by drammock** [comment] 2022-12-27 23:39
it's possible that this is caused by a graphics driver update, which might explain why rebooting helps on Linux (where it's usually not needed). Cross-ref: https://github.com/qutebrowser/qutebrowser/issues/3566#issuecomment-363804194

I experienced it today w/ rstudio version 2022.12 and a reboot solved it.  I had done a `sudo apt grade` at some point, and I checked `/var/log/apt/history.log` and sure enough some `libnvidia-*` packages were updated today.

**Comment by kevinushey** [comment] 2023-01-05 06:54
For others affected by this:

1. Does the issue always occur after updating graphics drivers (or via `apt update` or similar)?
2. Does the issue always resolve after a system restart?

If so, I'm inclined to close as won't fix just because we honestly have very little hope of supporting situations like these.

**Comment by drammock** [comment] 2023-01-10 16:15
> If so, I'm inclined to close as won't fix just because we honestly have very little hope of supporting situations like these

that seems reasonable to me.  Is there any way to detect the situation (even with some false positives) and offer users a message saying something like "there's a chance this is due to a recently updated graphics driver, try rebooting"?  Might save some folks a lot of time.

**Comment by mikebessuille** [comment] 2023-02-22 15:19
Closing based on Kevin's recommendation.

**Closed by mikebessuille** 2023-02-22 15:19 UTC
Labels: bug, plots
