### ISSUE TITLE
Squares instead of arrows in data viewer when viewing more than 50 columns

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9221] opened 2021-04-12 17:54 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.1671
    OS Version      : Red Hat 8.3 via Chrome and Safari on MacOS 11.3
    R Version       : 3.6.3

### Steps to reproduce the problem

View a data frame with more than 50 columns, e.g.
```
df <- as.data.frame(matrix(0, ncol = 129, nrow= 500))
colnames(df) <- paste(1:129,LETTERS, sep = "_")
View(df)
```
[Cribbed from #9036]

### Describe the problem in detail

For viewing the next or previous columns, the arrows are replaced by squares:
<img width="303" alt="squares" src="https://user-images.githubusercontent.com/31009952/114438461-c99eec00-9b95-11eb-8c12-7a853ec92b29.png">

### Describe the behavior you expected

Arrows instead of squares.
<img width="272" alt="arrows" src="https://user-images.githubusercontent.com/31009952/114438634-0539b600-9b96-11eb-9e65-a73e46a842fe.png">

Note that this works fine in RStudio Desktop 1.4.1671 on MacOS 11.3, and worked on earlier version of RStudio Server, though I'm not sure when it changed.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-04-12 18:06
Bonus: Developer console: <img width="765" alt="console" src="https://user-images.githubusercontent.com/31009952/114440494-36b38100-9b98-11eb-8daf-419fe7703ab1.png">

**Comment by mikebessuille** [comment] 2021-09-29 18:01
Closing as duplicate of #9623

**Closed** 2021-09-29 18:01 UTC
Labels: bug, regression, data viewer
