### ISSUE TITLE
Notebook inline chunk output obstructs the notebook content

### ISSUE THREAD

**Issue by x1o** [rstudio/rstudio#7293] opened 2020-07-07 20:42 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Ubuntu 18.04.4 LTS
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Create a new R Notebook.
2. Run the `plot(cars)` chunk.
3. Fold the chunk.
4. Switch to some other tab.
5. Switch back.

### Describe the problem in detail

![Screenshot from 2020-07-07 23-27-10](https://user-images.githubusercontent.com/3007504/86840449-5ff42d80-c0ab-11ea-91ca-489c48d27d24.png)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-07-08 04:47
Thanks for the bug report and the reproducible example! I've reproduced this locally and we'll try to figure out what's going on.

**Comment by kevinushey** [comment] 2020-07-17 23:04
Logging some notes here.

When a fold is created, Ace tries to determine whether any widgets within should be hidden:

https://github.com/ajaxorg/ace/blob/5524d248e3f82a70539bc0fbcded626b1c48b7f7/lib/ace/line_widgets.js#L122-L125

That state later gets used during render here -- hidden widgets are displayed slightly off-screen; although perhaps not off-screen enough. This is what leads to widgets eventually being "stuck" at the top of the screen.

https://github.com/ajaxorg/ace/blob/5524d248e3f82a70539bc0fbcded626b1c48b7f7/lib/ace/line_widgets.js#L357-L360

However, when we sync the height of chunk outputs, we force line widgets that might be hidden to instead be visible:

https://github.com/rstudio/rstudio/blob/2a2a62b2e10e6223bb5c09125bc4074476ea1b24/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java#L341

In other words, the sequence of events is something like this:

1. A line widget is added to the document, to display some chunk output;
2. The chunk is folded. In response, Ace hides the chunk by displaying it off-screen.
3. The user switches documents (de-activating then re-activating the document).
4. In response, we call `syncHeight()`, which forces widgets hidden by Ace to again become visible.
5. We get a "stuck" widget: Ace tries to "hide" the widget by setting it somewhat off-screen, but we explicitly force that widget to be visible!

There are a few things we can do to fix this:

1. Ask Ace to explicitly manage the `display` style for the widget,
2. Force Ace to display "hidden" widgets even further off-screen (so that even if one is erroneously displayed, it's not drawn on-screen).

**Comment by kevinushey** [comment] 2020-07-20 22:28
Closed via https://github.com/rstudio/rstudio/pull/7380, and will be part of the next preview release (not yet up).

**Closed by kevinushey** 2020-07-20 22:28 UTC
Labels: backlog, bug, notebooks, reproducible

**Comment by R-Hannibal** [comment] 2020-07-22 21:41
@x1o, thanks again for finding and reporting this issue. 

We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by x1o** [comment] 2020-07-24 14:25
@R-Hannibal looks fixed.
