### ISSUE TITLE
Alt-Cmd-0 keyboard shortcut doesn't insert paragraphs in the visual editor

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8476] opened 2020-11-24 21:11 UTC
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1056
    OS Version      : MacOS 11.1, Windows 10, and Red Hat 8.2
    R Version       : 4.0.3

### Steps to reproduce the problem

In the visual editor, press <kbd>Alt-Cmd-0</kbd>.

### Describe the problem in detail

Nothing happens.

### Describe the behavior you expected

This should do the equivalent of `Insert -> Paragraph`. Note that this is the case on all platforms.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment] 2021-07-21 01:58
This command is actually not to insert a new paragraph, but rather to toggle the current block between heading and paragraph modes. So this is currently behaving as intended.

**Comment by astayleraz** [comment] 2021-07-28 00:10
Closing the issue as working as designed.

**Closed by astayleraz** 2021-07-28 00:10 UTC
Labels: bug, keyboard shortcuts, test, visual markdown editing
