### ISSUE TITLE
Opening Projects Crashes Program

### ISSUE THREAD

**Issue by thesadie** [rstudio/rstudio#5156] opened 2019-07-29 21:28 UTC
Both File > Open Project... and the Project menu drop down Open Project cause RStudio to freeze

Opened Rstudio from the terminal to get more information on the failure: `load glyph failed err=6 face=0x15fed00, glyph=2798`

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1    yaml_2.2.0    
```
Rstudio Version 1.1.456

**Comment by pascaloettli** [comment] 2019-07-30 08:05
Out of curiosity, is there any reason for you to use such an old version of RStudio and not upgrading to the current release?

**Comment by ronblum** [comment] 2019-07-30 15:23
@thesadie Thank you for raising the issue and providing useful information for reproducing it. Also, is this an issue with all projects or just some? And does creating a new project fail, as well?

In addition, there are more recent versions of RStudio. The latest 1.1.x version is 1.1.463, and the current production release is 1.2.1335. There is also preview available for an update that we are currently working on. It might be worth trying one of them out to see if that resolves the problem.

* [Previous RStudio release, 1.1.463](https://support.rstudio.com/hc/en-us/articles/206569407-Older-Versions-of-RStudio)
* [Current RStudio release, 1.2.1335](https://www.rstudio.com/products/rstudio/download/)
* [Latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/) (Note that Preview builds are intended for testing purposes only.)

**Comment by ronblum** [comment] 2019-07-30 15:25
@thesadie By the way, the `load glyph failed` issue is innocuous. It's a known nuisance (#4216).

**Comment by thesadie** [comment] 2019-07-30 16:12
It was for all projects. I can create a new project, just couldn't open without the failure using the two menu routes. I upgraded to the newest release and there is no longer that issue. I didn't upgrade out of laziness, I usually do once a bug forces me to.

**Comment by ronblum** [comment] 2019-07-30 16:26
@thesadie I admire your policy. I tend to be a little more adventurous (read: reckless) by upgrading software and operating systems as soon as new updates are out—and often, beta versions—which usually means a mixture of excitement and regret. :)

I'll close the issue, since it's resolved for you, but it'll be available here in case anyone runs into the same problem. Thanks!

**Closed** 2019-07-30 16:26 UTC
Labels: bug
