### ISSUE TITLE
System-wide keyboard shortcuts not working

### ISSUE THREAD

**Issue by Seviks** [rstudio/rstudio#6870] opened 2020-05-14 08:28 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio-1.3.958.exe
    OS Version      :  Windows 10
    R Version       :  4.0.0

### Steps to reproduce the problem
Add rstudio_bindings.json to %PROGRAMDATA%\RStudio\keybindings\

### Describe the problem in detail
Following: 5.16.5 Keybindings https://docs.rstudio.com/ide/server-pro/1.3.820-1/r-sessions.html#customizing-session-settings
I set keybindings and move them to %PROGRAMDATA%\RStudio\keybindings\

After restarting RStudio, the keybindings don't work. Moreover Tools->Modify Keyboard Shortcuts does not yield a dialog. If I delete %PROGRAMDATA%\RStudio\keybindings\rstudio_bindings.json, the dialog shows up again.

Tried with the following rstudio_bindings.json, as well with one containing only "{}":
```
{
    "quickAddNext": "Ctrl+D",
    "pasteLastYank": ""
}
```
%APPDATA%\Rstudio\keybindings was removed, so no user setting overrides system settings

%PROGRAMDATA%\RStudio\templates work well

Problem occurs also after uninstallation RStudio, cleaning all User- and programdata an reinstalling RStudio.

### Describe the behavior you expected
Keyboard shortcuts placed in  %PROGRAMDATA%\RStudio\keybindings\rstudio_bindings.json are recognized,  Tools->Modify Keyboard Shortcuts yields dialog

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-05-14 19:23
@Seviks Thank you for raising the issue! I'm unable to reproduce it though, in the same environment. Two things:
1) Can you confirm that it works in %APPDATA%? (I think that's where you got the file from, but I don't want to make an assumption.)
2) Does the Tools -> Modify Keyboard Shortcuts dialog come up if you munge the file, like adding a stray comma? It should show up without the custom shortcuts, but it should at least show up.

**Comment by gtritchie** [comment] 2020-05-14 19:37
@ronblum I was able to repro the problem as described. My keyboard shortcut stopped working and the dialog stopped appearing.

**Comment by gtritchie** [comment] 2020-05-14 19:41
My steps, on Windows 10 with latest 1.3 preview build:

- created a single keyboard shortcut using the dialog (I assigned Ctrl+Shift+Alt+F9 to "Check for RStudio Updates"
- verified that it works
- closed RStudio then moved %appdata%\RStudio\keybindings\rstudio_bindings.json to %programdata%\RStudio\keybindings\rstudio_bindings.json
- Start RStudio, and the shortcut no longer works, and I cannot invoke the modify shortcuts dialog

**Comment by Seviks** [comment] 2020-05-15 08:44
> 
> 
> @Seviks Thank you for raising the issue! I'm unable to reproduce it though, in the same environment. Two things:
> 
>     1. Can you confirm that it works in %APPDATA%? (I think that's where you got the file from, but I don't want to make an assumption.)
> 
>     2. Does the Tools -> Modify Keyboard Shortcuts dialog come up if you munge the file, like adding a stray comma? It should show up without the custom shortcuts, but it should at least show up.

1. It works in %APPDATA% and I take the file from there and move it to %programdata%. Also: The problem only occurs when I move the file. If I leave a copy in %appdata% everything works fine.

2. When I add a stry comma the dialog show up without the custom keybindings.

Another thing, maybe related: When I use Ctrl and a letter for a a custom keybinding in the dialog the letter is not taken correctly. The issue above happens with both, correct and incorrect taken keybindings. 
![Unbenannt](https://user-images.githubusercontent.com/4014268/82030282-8643b100-9698-11ea-8750-0ccd0f457799.PNG)
`{
    "checkForUpdates": "Ctrl+Shift+\u0012",
    "updatePackages": "Shift+R"
}`

**Comment by kevinushey** [comment] 2020-05-15 16:55
> Another thing, maybe related: When I use Ctrl and a letter for a a custom keybinding in the dialog the letter is taken incorrectly. The issue above happens with both, correct and incorrect taken keybindings.

I think this is fixed in the v1.4 dailies (and will be fixed in v1.3-patch) via https://github.com/rstudio/rstudio/blob/c661b483f99fbb8feb88f4041a3af6e3c4d7fc01/src/cpp/desktop/DesktopMain.cpp#L637-L643.

**Comment by jmcphers** [comment] 2020-05-15 22:07
> I think this is fixed in the v1.4 dailies (and will be fixed in v1.3-patch) via

FWIW I saw this behavior on a build made from master today.

**Closed** 2020-05-15 23:48 UTC
Labels: bug, keyboard shortcuts, user preferences

**Comment by R-Hannibal** [comment] 2020-06-02 14:16
Hey @Seviks, we have a fix in place for this issue in our upcoming release, currently accessible on our [Preview Page](https://rstudio.com/products/rstudio/download/preview/).

If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by Seviks** [comment] 2020-06-02 15:53
@R-Hannibal, with v1.3.1004-1 Preview it works. Thanks for the quick fix.

**Comment by R-Hannibal** [comment] 2020-06-03 14:28
Excellent, thanks for confirming @Seviks.
