### ISSUE TITLE
Change method of closing pop-up window after using 'Find'

### ISSUE THREAD

**Issue by rsangole** [rstudio/rstudio#2096] opened 2018-01-31 13:47 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.364
    OS Version      :  Sierra, 10.12.6
    R Version       : 3.4.0

### Steps to reproduce the problem
Open any .R file, search for a term not in the file. This should result in a pop-up window: "Find/Replace : No more occurances."

### Describe the problem in detail
Via the keyboard, the way to close this pop-up window today is by hitting `esc`.

### Describe the behavior you expected
I find this a bit clunky since while coding, our hards are squarely in the center of the keyboard. It would be a whole lot quicker if we could close this pop-up window by just hitting `enter/return` instead, which much requires less movement of the right hand.

Almost all pop-up windows in most applications close by hitting `enter/return` so it is also my first natural instinct when this particular pop-up shows up. Only to realize that it's behavior is not as expected (at least to me!)

Thoughts?

**Comment by kevinushey** [comment] 2018-01-31 17:35
Thanks for the bug report! I think I've found the root cause of this issue; I've pushed a fix for v1.2.

In the interim, it is possible to dismiss the dialog with <kbd>Spacebar</kbd> if you have enabled "Full Keyboard Access". If you haven't done so yet, you can do so with the Apple Keyboard preference pane (see near the bottom left of the dialog):

<img width="675" alt="screen shot 2018-01-31 at 9 34 08 am" src="https://user-images.githubusercontent.com/1976582/35637735-f62d5d8e-0669-11e8-9221-8934a65263c9.png">

**Comment by rsangole** [comment] 2018-01-31 22:21
Cheers, thanks!

**Closed** 2019-11-27 18:30 UTC
Labels: enhancement
