### ISSUE TITLE
Error 10048 and 10053 on RStudio Startup on Windows with Proxy

### ISSUE THREAD

**Issue by wtimmerman-fitp** [rstudio/rstudio#11395] opened 2022-06-09 15:10 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.06.0-daily+497 "Spotted Wakerobin" Daily (78ce5eff140c7fc8e06e2bff739571334d3c55e5, 2022-06-09) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36  (also others tested below);
    OS Version      : Windows 10 Pro 
    R Version       : 4.0.3 (also others tested below)

### Steps to reproduce the problem

1. Have system proxy running (details below)
2. Open an instance of RStudio normally in Windows 10. I have a few versions of R installed, using 4.0.3 in this case. This session works fine.
3. Open a second instance of RStudio. This results in the "Error Starting R" warning and the set of error messages, specifically:

From:
C:/Users/MyName/AppData/Local/RStudio/log/rsession-MyName.log

`2022-06-07T06:52:01.004631Z [rsession-MyName] ERROR system error 10048 (Only one usage of each socket address (protocol/network address/port) is normally permitted); OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::http::initTcpIpAcceptor(class rstudio::core::http::SocketAcceptorService<class rstudio_boost::asio::ip::tcp> &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &) src/cpp/session/http/SessionWin32HttpConnectionListener.cpp:122; LOGGED FROM: int __cdecl main(int,char *const []) src/cpp/session/SessionMain.cpp:2088`

After further testing (more below), i also received this error:
`2022-06-09T12:30:02.868925Z [rsession-myname] ERROR system error 10053 (An established connection was aborted by the software in your host machine) [request-uri: /help/library/stringr/html/str_match.html]; OCCURRED AT void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide\open-source-pipeline\main\src\cpp\session\http\SessionHttpConnectionImpl.hpp:156; LOGGED FROM: void __cdecl rstudio::session::HttpConnectionImpl<class rstudio_boost::asio::ip::tcp>::sendResponse(const class rstudio::core::http::Response &) C:\Users\jenkins\workspace\ide\open-source-pipeline\main\src\cpp\session\http\SessionHttpConnectionImpl.hpp:161`

### Describe the problem in detail

Results in the "Error Starting R" screen in RStudio and the problem report (copied further below for completeness)

A few other items for context:

1. Have installed and reinstalled RStudio. This first appeared after upgrading to the most recent version of RStudio (RStudio-2022.02.3-492); it still appeared after downgrading to RStudio-2021.09.3-396.exe. In total i've tested on these versions and got the same error:
    - 2021.09.3+391 (from daily builds)
    - 2021.09.3-396 (official release)
    - 2022.02.2+481 (from daily builds)
    - 2022.02.3-492 (official release)
    - 2022.06.0-daily-497 (from daily builds)
It does *not* occur on the recent Electron build: 2022.06.0-daily+496

2. it occurs whether i have had an RStudio project reopen or not.
4. Removing my .renviron, .rhistory, and .rprofile doesn't fix this.
5. If i have one instance of RStudio open and try opening an R console with R.exe, i can do so without any problem.
6. Occurs whether on 4.0.3 or 4.1.2, the two versions of R i've tested with.
7. I don't have any new R or system environmental variables I believe are mucking with this. see diagnostics report below.
8. I use a proxy (Clash for Windows), but the proxy settings are not in my system environmental variables, just in the windows proxy settings. When my proxy is turned off, i can open multiple RStudio instances without trouble. I've used this same proxy software for years without trouble, and I'd like to find a way for RStudio to keep working with this thing. Per Window's proxy settings window, my proxy settings are as follows:
address: 127.0.0.1 , port: 7890 (this is the port consistently)
excluded IPs: localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*
The checkbox for "Don't use the proxy server for local (intranet) addresses" is checked. My proxy also has a loopback option for proxying local traffic, but this is also unused. I upgraded my proxy software to the latest version to no avail.
I have previously used httr::set_config to set a proxy address and httr::reset_config() to clear that, but seems unrelated to the current circumstance.
9. I tried googling the error message. I get the basics about how a socket is in use, etc. etc., but it seems odd to me I haven't had problems in years of using RStudio together with a proxy until I recently upgraded R Studio.
10. [It looks related to this issue](https://github.com/rstudio/rstudio/issues/10488) based on some pointers others gave me. [Some other discussion here](https://community.rstudio.com/t/error-10048-on-rstudio-startup/139278)

Finally, error messages below:

### RStudio Version

RStudio 2022.06.0-daily+497, "Spotted Wakerobin" (78ce5eff, 2022-06-09) for Windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 1. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*C:/Users/myname/AppData/Local/RStudio/log/rsession-myname.log*

```
2022-06-09T14:51:37.778162Z [rsession-myname] ERROR system error 10048 (Only one usage of each socket address (protocol/network address/port) is normally permitted); OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::http::initTcpIpAcceptor(class rstudio::core::http::SocketAcceptorService<class rstudio_boost::asio::ip::tcp> &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &) C:\Users\jenkins\workspace\ide\open-source-pipeline\main\src\cpp\core\include\core/http/TcpIpSocketUtils.hpp:122; LOGGED FROM: int __cdecl main(int,char *const []) C:\Users\jenkins\workspace\ide\open-source-pipeline\main\src\cpp\session\SessionMain.cpp:2196
2022-06-09T14:51:37.778162Z [rsession-myname] ERROR system error 10048 (Only one usage of each socket address (protocol/network address/port) is normally permitted); OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::http::initTcpIpAcceptor(class rstudio::core::http::SocketAcceptorService<class rstudio_boost::asio::ip::tcp> &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &) C:\Users\jenkins\workspace\ide\open-source-pipeline\main\src\cpp\core\include\core/http/TcpIpSocketUtils.hpp:122; LOGGED FROM: int __cdecl main(int,char *const []) C:\Users\jenkins\workspace\ide\open-source-pipeline\main\src\cpp\session\SessionMain.cpp:2196

```

Diagnostics report: 
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/8871613/diagnostics-report.txt)                

### Describe the behavior you expected

In previous versions of RStudio (unknown to me now since I've reinstalled), I was able to open multiple RStudio instances without trouble.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2022-06-13 00:17
> I use a proxy (Clash for Windows), but the proxy settings are not in my system environmental variables, just in the windows proxy settings. When my proxy is turned off, i can open multiple RStudio instances without trouble.

There are a few potential changes in RStudio that could be causing this issue:

1. RStudio now tries to select a port in the range 49152–65535, rather than 8000-48000;
2. RStudio tries to bind to the selected socket first, to check that it's actually available for use (using QTcpSocket's bind implementation),
3. RStudio now also sets `SO_EXCLUSIVEADDRUSE` (https://github.com/rstudio/rstudio/blob/c20b426989c27cb1090226168bb40063cd71fdd2/src/cpp/core/include/core/http/TcpIpSocketUtils.hpp#L106-L114) to avoid allowing multiple RStudio instances to bind on the same socket.

Is it possible that your proxy is preventing RStudio (either the front-end or rsession.exe backend) from communicating on these ports?

**Comment by Waldi73** [comment] 2022-06-13 06:14
@kevinushey , I encounter the exact same problem as described above.
I noticed that if I open RStudio without proxy and then turn the proxy on, I can still create a new session without error. This is perhaps an answer regarding proxy preventing Rstudio to communicate on certain ports : doesn't seem to be the case as I can open a session.

**Comment by wtimmerman-fitp** [comment] 2022-06-13 07:22
Hi @kevinushey, 

First, thanks for the info and for your debug work on this--I know this issue isn't exactly reproducible on your end (I assume) without this specific software, which probably makes it a chore.

On @Waldi73 's point, I see the same behavior (if proxy is off when i start first session, then i turn proxy on, i can still open other RStudio sessions). I don't know enough to interpret what this means in this context, but let me know if this does or doesn't help to answer your last question.

For more background, my traffic goes to port 7890 for the proxy, then out on another port. Details below: this is what I see in my proxy logs when I open two RStudio windows, the first successfully and the second with the same error as in the original bug (note the 'failed to start Redir UDP Listener' item is a Windows-specific item and doesn't appear to be meaningful here, though I could be wrong: https://github-com.translate.goog/Dreamacro/clash/issues/1116?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)

```
time="2022-06-13T03:08:59-04:00" level=info msg="RESTful API listening at: 127.0.0.1:52756"
time="2022-06-13T03:08:59-04:00" level=warning msg="Failed to start Redir UDP Listener: not supported on current platform"
time="2022-06-13T03:08:59-04:00" level=info msg="Redirect proxy listening at: 127.0.0.1:7892"
time="2022-06-13T03:08:59-04:00" level=error msg="Start Redir server error: not supported on current platform"
time="2022-06-13T03:08:59-04:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-06-13T03:08:59-04:00" level=info msg="Start initial compatible provider Proxy"
time="2022-06-13T03:08:59-04:00" level=info msg="Start initial compatible provider Domestic"
time="2022-06-13T03:08:59-04:00" level=info msg="Start initial compatible provider GlobalTV"
time="2022-06-13T03:08:59-04:00" level=info msg="Start initial compatible provider Others"
time="2022-06-13T03:08:59-04:00" level=info msg="Start initial compatible provider AsianTV"
time="2022-06-13T03:09:12-04:00" level=info msg="[TCP] 127.0.0.1:52781 --> sn.webrootcloudav.com:443 using GLOBAL"
time="2022-06-13T03:09:14-04:00" level=info msg="[TCP] 127.0.0.1:52784 --> sn.webrootcloudav.com:443 using GLOBAL"
time="2022-06-13T03:09:18-04:00" level=info msg="[TCP] 127.0.0.1:52830 --> www.rstudio.org:443 using GLOBAL"
```

Over a few minutes of loading Outlook and being on a single github page, the port number will increment upwards from 50525 to 52707, skipping many numbers few along the way. This is of course in that range you mentioned earlier.

**Comment by wtimmerman-fitp** [comment] 2022-06-13 07:55
Alas, I'm now finding the workaround mentioned by @Waldi73 (open RStudio before the proxy app, then enable proxy, then continue to open RStudio instances without trouble) is not entirely consistent. Sometimes I'll get one more RStudio window open, then on the next I will receive the error mentioned in the original post. 

A few more thoughts:
 - @kevinushey  , should I add any particular local IP Address for RStudio to the list of local IP addresses excluded from the proxy?  (e.g., 172.16.\* something?) Unfortunately I don't see a range of ports I can limit my proxy to in its settings or config files; I can also try filing an issue there.

 - When i look at my RStudio diagnostics report again and what's in  C:/Users/myname/AppData/Local/RStudio/log/rdesktop.log, i see this line a number of times:

  `2022-06-09T09:34:33.970718Z [rdesktop] WARNING failed to find open port; defaulting to port 8789; LOGGED FROM: class QString __cdecl rstudio::desktop::Options::portNumber(void) const src/cpp/desktop/DesktopOptions.cpp:210`

**Comment by majazaloznik** [comment] 2022-06-21 07:35
I'm having the same issue as @wtimmerman-fitp and @Waldi73. I can only open multiple instances of RStudio if I turn off the proxy server. This is post updating Rstudio to 2022.02.3 Build 492 "Prairie Trillium" Release (1db809b8, 2022-05-20) for Windows.

**Comment by gtritchie** [comment] 2022-06-22 16:27
@kevinushey said he'd take a look at this, so assigned to him.

**Comment by gtritchie** [comment] 2022-06-22 20:43
@majazaloznik @Waldi73 : Are you using the same proxy software ("Clash for Windows") as @wtimmerman-fitp?

**Comment by majazaloznik** [comment] 2022-06-22 21:47
@gtritchie no, I'm behind a corporate firewall (i guess) and just have the proxy set using the windows proxy settings

**Comment by gtritchie** [comment] 2022-06-22 22:13
We can now reproduce the problem without running any proxy software.

Configure proxy as follows in Windows settings:

* turn off automatic proxy configuration
* configure manual proxy server at 127.0.0.1, port 7890, and check "Don't use the proxy server for local (Intranet) addresses".

As expected, I cannot browse the web (e.g. via Edge) because there's no proxy there to handle it, but RStudio starts first session fine, then fails when I try Session / New Session, 100% of the time.

![proxy](https://user-images.githubusercontent.com/10569626/175161372-6ecedd5e-ba91-45d0-b3b6-ead9751bb282.png)

**Comment by wtimmerman-fitp** [comment] 2022-06-23 12:11
> Also, just to check, is it this software? https://github.com/Dreamacro/clash

Indeed! Specifically one of the releases for Windows here, which I believe is using that internally: https://github.com/Fndroid/clash_for_windows_pkg/releases

**Comment by kevinushey** [comment] 2022-06-23 19:39
This issue should now be resolved in the current preview release of RStudio for Windows. It is available here:

https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-2022.07.0-preview-540.exe

Installer-less builds are here:

https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-2022.07.0-preview-540.zip

@wtimmerman-fitp, @Waldi73, would you be able to test using one of these builds of RStudio?

**Comment by nzdudeinsydney** [comment] 2022-06-24 06:54
I can reproduce the issue on 2022.02.3 (Build 492) and I also confirm that the issue no longer occurs with RStudio-2022.07.0-preview-540.exe.  

Are you able to please advise the anticipated release date (while acknowledging that things can slip)?

**Comment by majazaloznik** [comment] 2022-06-24 13:08
I can likewise confirm that the preview release resolves my issue, thanks for fixing it so quickly!

**Comment by ronblum** [comment] 2022-06-24 15:56
@nzdudeinsydney and @majazaloznik Thank you for verifying the fix! Regarding the release: We're in the final stretch, and hope to have to have the GA release in a few weeks. I can't guarantee a date, but if circumstances result in our taking longer than that, we'll be crestfallen. 🙂

**Closed by ronblum** 2022-06-24 15:56 UTC
Labels: bug, windows, regression, test
