### ISSUE TITLE
When Plot Zoom is opened as a window, RStudio does not open R file from the system call

### ISSUE THREAD

**Issue by aushev** [rstudio/rstudio#15556] opened 2024-12-24 08:51 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.12.0+467 "Kousa Dogwood" Release (cf37a3e5488c937207f992226d255be71f5e3f41, 2024-12-11) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.12.0+467 Chrome/126.0.6478.234 Electron/31.7.6 Safari/537.36, Quarto 1.5.54 (C:/Program Files/Quarto/bin/quarto.exe)
    OS Version      :  Windows 11 Pro v. 23H2
    R Version       :  4.4.0

### Steps to reproduce the problem
1. Open RStudio
2. Execute any code that produces a plot, for example `ggplot(iris, aes(x=Sepal.Length,y=Petal.Width))+geom_point()`
3. In the Plot pane, click Zoom to open "Plot Zoom" window
4. From the system (for example, in Windows Explorer or other file manager), call default Open action for any RStudio-associated file such as .R or .Rmd - by double-clicking on it or through context menu.

### Describe the problem in detail
Instead of opening the file in RStudio, it only activates Plot Zoom window. 

### Describe the behavior you expected
Expected to open the file in RStudio. If Plot Zoom window is not opened, the same steps result it normal opening of the file.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-12-24 16:11
@aushev Thank you for raising this! This is a duplicate of #15457 , although with .Rdata instead of .R and .Rmd. It's fixed in build 2024.12.1.522, which is available [in the daily builds](https://dailies.rstudio.com) if you'd like to try it out. Please note that these are meant for development and testing purposes, not production.

**Closed by ronblum** 2024-12-24 16:11 UTC
Labels: bug, new
