### ISSUE TITLE
Shortcut Alt+- in source editor : strange behaviour after Rstudio + R upgrades

### ISSUE THREAD

**Issue by Brufico** [rstudio/rstudio#12457] opened 2022-12-18 00:52 UTC
Hello, I updated  R and Rstudio, and that affected the effect of the shortcut `Al=+-`

### System details

    RStudio Edition :  Desktop
    RStudio Version : RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
    OS Version      :  Windows 10 Professionnel, Version 21H2, Build 19044.2364, Windows Feature Experience Pack 120.2212.4190.0
    R Version       :  R version 4.2.2 (2022-10-31 ucrt) -- "Innocent and Trusting", Platform: x86_64-w64-mingw32/x64 (64-bit)

### Steps to reproduce the problem : 
Open an .R file in the editor, press the shortcut `Alt+-` (enter an assignment operator) using the "minus" key on the main keyboard (the "6" key)

- Sorry, I should have mentioned earlier : I have a **french** keyboard, so pressing the "6" key (without pressing "Shift") normally returns `-` (minus sign).

### Describe the problem in detail : 
If in the shortcut the (-) (minus) key is pressed on the numeric keypad, the shortcut works as expected (enter an assignment operator `<- ` ).  However, if the main keyboard key (- / 6) is pressed instead of the keypad `-`, nothing happens.

### Describe the behavior you expected:
I got used to enter assignments using `Alt+-` on the main keyboard, and I expected this key combination to keep working. (I also use a laptop - which i did not update yet - without a numeric keypad attached). 

### What I tried
* tried "Modify keyboard shortcut" and pressed `Alt+-` on the main keyboard ==> No effect. The new shortcut was not even listed as customized in the dialog box
* tried "Modify keyboard shortcut" with new shortcut `Alt+_` ==> This time lost completely the binding to the "enter assignment" action. I had to reset the shortcuts.

### Another issue, maybe related (?)
Also since today's upgrade, at the start of R/Rstudio, i get the following error : 
`Error in file.exists(pythonPath) : 
  file name conversion problem -- name too long?`

(Note: I do not have Python on my system)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Brufico** [comment] 2022-12-18 10:58
Sorry, I should have mentioned : I have a **french** keyboard, so pressing the "6" key (without pressing "Shift") results in `-` (minus sign). 
Bruno

**Comment by IACPouembout** [comment] 2022-12-19 03:33
Hello, I have the same issue with my french keyboard since the Rstudio update, the shortcut `Alt+-` works only on the numeric keybard but is not working with the main keyboard.

**Comment by ronblum** [comment] 2022-12-19 15:50
@Brufico and @IACPouembout thank you for raising this! It looks like we had a similar issue in #7169, with a German (QWERTZ) keyboard. Just to confirm—are you using an AZERTY keyboard?

**Comment by Brufico** [comment] 2022-12-20 13:02
@ronblum,
Yes Ron, AZERTY Keyboard.
Best.

**Comment by IACPouembout** [comment] 2022-12-20 22:08
> @Brufico and @IACPouembout thank you for raising this! It looks like we had a similar issue in #7169, with a German (QWERTZ) keyboard. Just to confirm—are you using an AZERTY keyboard?

Yes, AZERTY keyboard for me.
Best wishes and merry christmas !

**Comment by bencfd** [comment] 2022-12-21 10:09
I noticed the same problem, and with the _Zoom Out_ shortcut as well (`Ctrl+-`). Rolling back to RStudio 2022.07.2 solved it. I'm using an AZERTY keyboard on Windows.
The keyboard shortcuts work like a charm with RStudio 2022.12.0 and an AZERTY keyboard on macOS (`Opt+-` for assignment operator; `Cmd+-` for Zoom Out).

**Comment by ronblum** [comment] 2022-12-21 15:18
Thanks for the info! I marked this for me to reproduce with AZERTY keyboard mapping, and to quickly relearn my high school French. (Je ne parle pas français. Je sais seulement cinq mots en français: Je, ne, parle, pas, et français.)

**Comment by ATerracol** [comment] 2022-12-22 09:14
Same here on a french AZERTY keyboard (on a laptop, without a dedicated numpad).
Running Ubuntu 22.10 if that matters.

**Comment by ronblum** [comment] 2022-12-29 14:25
I can reproduce the problem in RStudio Desktop 2022.12.0+353 using an AZERTY keyboard. Findings:

Failure
- Windows "AZERTY" layout, in which<kbd>–</kbd> is on the same key as <kbd>6</kbd>.
- MacOS "French - PC" layout, which is equivalent to the above.

Success
- MacOS "ABC - AZERTY" layout, in which <kbd>–</kbd> is on its own key, just to the left of <kbd>Delete</kbd>.

Note: On Windows, nothing happens. On MacOS, a pipe (<kbd>|</kbd>) appears, which is the same as what <kbd>AltGr</kbd> results in.

**Comment by ronblum** [comment] 2022-12-29 14:29
Reported by @token42 https://github.com/rstudio/rstudio/issues/12506#issuecomment-1367365890
>Thanks, this actually helped! I was actually using Czech and UK QWERTY keyboard, those do not work. But for some reason Czech QWERTZ works fine. I'll mess around with the keyboard settings a bit more, thank you!

**Comment by mikmart** [comment] 2023-01-25 23:26
Since 2022-12 I have also been having issues with keyboard shortcuts. Particularly `Ctrl+'` and `Ctrl+Shift+/` no longer work at all. I'm on QWERTY Finnish layout.

**Comment by dpprdan** [comment] 2023-01-28 19:10
+1 on the `Ctrl+Shift+/` not working anymore - this time on a [QWERTZ German keyboard layout](https://en.wikipedia.org/wiki/German_keyboard_layout). The `/` key is on the `Shift + 7`, so now this will execute "Zoom Packages", since the shortcut for that is `CTRL + Shift + 7`. The shortcut for `Reflow Comment` is now `Ctrl + Shift + #`. 

This is indeed shown in the menu:
![grafik](https://user-images.githubusercontent.com/1423562/215286020-4c4e3aaa-390e-4e6f-aafe-d988c872baa0.png)

But not in the Keyboard Shortcuts Help
![grafik](https://user-images.githubusercontent.com/1423562/215286107-a223347d-1249-40ea-bb07-24f89aa943f4.png)

Nor in the Modify Keyboard Shortcuts menu
![grafik](https://user-images.githubusercontent.com/1423562/215286154-3177fe4b-69d0-4fff-8fff-c3b66bff6e4a.png)

This is from today's daily

```
RStudio 2023.03.0-daily+277 "Cherry Blossom" Daily (3d5918dca30a51e6c5b2805b7d2d73169b62d6fd, 2023-01-28) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/99.9.9 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
```

`Alt + -` works fine BTW, `Ctrl+'` is apparently not defined, but Ctrl + ` (backtick) "Focus Console Output" doesn't seem to work.

**Comment by gtritchie** [comment] 2023-01-28 19:22
> but Ctrl + ` (backtick) "Focus Console Output" doesn't seem to work.

Focus Console Output is working. It is an accessibility feature for screen-reader users. If you don't have a screen reader running, the only visible indication is the console cursor changing from focused to non-focused.

**Comment by gtritchie** [comment] 2023-01-28 19:33
I just logged an issue with there being no focus indicator for the console output region. Even though it's a feature intended for non-visual users, we should still be showing a focus rectangle.

**Comment by Farewe** [comment] 2023-03-26 11:45
Hello, I am bumping this issue on on the `Alt + -` / assignment operator issue for French keyboards. This is an important quality of life issue for users, I wish it could be fixed for the next RStudio release; it was not fixed in the last update 2023.03.

**Comment by mikmart** [comment] 2023-04-24 09:22
I hope this issue receives some attention soon. I've been holding back to version 2022.07.1 to avoid this, which was a minor inconvenience. But now that version is no longer compatible with the new graphics engine in R version 4.3.0, so I'm also being held back on upgrading my R version, which is a bigger problem.

**Comment by mikmart** [comment] 2023-04-24 10:06
I've found that with a Finnish QWERTY layout and a keybinding mapped to `Ctrl + '` I currently need to actually press `Ctrl + ä` to activate it. Looks like it's assuming I'm on a US layout.

**Comment by MarionCoves** [comment] 2023-06-23 07:49
Hi there,
Same french AZERTY keyboard, same problem ! 
--> My answer to it👍 

I modified the keyboard shortcut from "Alt+-" to "Ctrl+Shift+6" (already meant to zoom plots but it can do both I guess)
It works  ٩(◕‿◕)۶  little arrow's back !

**Comment by Farewe** [comment] 2023-11-22 10:28
Hello, 

the assignment operator shortcut has been broken for a year now for all French AZERTY keyboards.

There also appears to be many issues with shortcuts for what I'd call non-English QWERTY layouts. 

Can we hope for a fix in the near future please? Would that be possible to include the most common keyboard layouts in tests of Rstudio builds to avoid repeating these issues in the future?

**Comment by gtritchie** [comment] 2023-11-22 16:39
Sorry this issue has lingered for so long. I'm going to take a look.

**Comment by gtritchie** [comment] 2023-11-23 21:09
Another similar issue: #7543

**Comment by gtritchie** [comment] 2023-11-23 22:25
Research note: I was curious if this is/was working in RStudio Server (to make sure I don't break something that is working).

Nope. <kbd>Alt</kbd>+<kbd>-</kbd> doesn't work on French AZERTY keyboard on any of the following Server releases (hitting with Chrome on Windows-11):

* 1.4.1743
* 2021.09.4 Build 403
* 2022.02.4 Build 500
* 2022.07.2 Build 576
* 2022.12.0 Build 353
* 2023.03.2 Build 454
* 2023.06.2 Build 561
* 2023.09.1 Build 494

**Comment by gtritchie** [comment] 2023-11-24 19:46
FYI I've got a fix for this specific shortcut. It probably won't make it into the next release as we're very close to code complete and not taking many changes, but I'll ask. Otherwise it'll be in the release after that (early spring release is my guess).

**Comment by ronblum** [comment] 2024-03-13 17:38
I've got a French PC AZERTY layout in which the `-` is on the same key as `6`. However, instead of the assignment operator, I get a bar `|` instead. But this might be correct behavior, though, because that's what `Alt+6` is normally expected to return and it's taking precedence.

Regular keys:
![Image](https://github.com/rstudio/rstudio/assets/31009952/6f6f7d17-7b8f-46e5-b835-62ecd675c41e)

Opt keys:
![Image](https://github.com/rstudio/rstudio/assets/31009952/a5b1c171-3c68-40f5-ba48-f9eb732a1f64)

Looking at other layouts: It works in a German QWERTZ keyboard, but the `-` key doesn't have anything assigned to it when pressing `opt`.

So if anyone would be willing to try this out and report on what they're seeing, that would be much appreciated! The [dailies for the current release](https://dailies.rstudio.com/) (Chocolate Cosmos) are available to try out. Please note that they're for testing and development purposes only, not production.

**Closed** 2024-04-09 11:52 UTC
Labels: bug, key bindings, locale, need help verifying

**Comment by Farewe** [comment] 2024-06-01 12:42
Hello, I just want to confirm that as of version 2024.04.1 of Rstudio, I can apply the shortcut `alt + -` (with the `6` / `-` key) to the assignment operator and it works properly. Thanks for fixing this!

@ronblum just to comment on this:

> I've got a French PC AZERTY layout in which the - is on the same key as 6. However, instead of the assignment operator, I get a bar | instead. But this might be correct behavior, though, because that's what Alt+6 is normally expected to return and it's taking precedence.

Normally it's not `Alt + 6` that is supposed to return the bar `|` on a French keyboard, it is `Alt gr + 6`. The `Alt gr` key is generally located on the right side of the keyboard, whereas the `Alt` key is on the left side. 

![](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/KB_France.svg/1600px-KB_France.svg.png)
