### ISSUE TITLE
Collapse arrow for section headers no longer visible after inserting div

### ISSUE THREAD

**Issue by DanOvando** [rstudio/rstudio#14642] opened 2024-05-02 16:33 UTC
### System details

    RStudio Edition : 
    RStudio Version : 2024.04.0+735 (2024.04.0+735)
    OS Version      :  macOS 14.4.1 (23E224)
    R Version       :  4.4.0

### Steps to reproduce the problem

1. Open RStudio

2. Open a .qmd file

3. Add section header (e.g. `# Results` )

4. Add a div after the section header, followed by another section header
```
# Results

::: {#refs}
:::

# Figures

```

### Describe the problem in detail

Code folding arrows disappear from section headers following inclusing of a div in quarto document. See screenshot below; code folding arrow present for `# References`, but not for `# Figures`. If div is removed, code folding arrow returns to `# Figures`

![Screenshot 2024-05-02 at 9 30 21 AM](https://github.com/rstudio/rstudio/assets/8096183/e6f86260-6f55-4a4b-a619-98b46f4fdfbb)

### Describe the behavior you expected

Code folding arrows should still be present in section headers of .qmd files opened in the RStudio IDE following inclusion of a div. 

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-05-02 16:51
@DanOvando Thank you for raising the issue! I can also reproduce this in RStudio Desktop 2023.03.2+454 on Windows 11 using R 4.3.3. We'll review this issue as we continue development of RStudio.

**Comment by gtritchie** [comment] 2024-05-09 20:20
On RStudio 2023.12.1+402 this scenario doesn't entirely work for me.

The arrow for the second header is missing, but still there for the first header:

![Image](https://github.com/rstudio/rstudio/assets/10569626/12f03941-f7dc-427e-992b-fe57bdbe3d3f)

**Comment by kevinushey** [comment] 2024-09-12 17:12
This seems to be working for me in the latest daily builds (available at https://dailies.rstudio.com/rstudio/kousa-dogwood/).

<img width="517" alt="Screenshot 2024-09-12 at 10 10 39 AM" src="https://github.com/user-attachments/assets/9a08d639-3272-445d-824c-78d5e894019b">

Is anyone else able to test + confirm?

**Comment by gtritchie** [comment] 2024-09-17 21:35
I repro'd on `2024.04.0+735`, `2024.04.1+748`, and `2024.04.2+764`, but it did not repro on `2024.09.0-375` (RC for cranberry-hibsicus) or a recent daily build of the next release (`2024.10.0+182`).

Closing as fixed.

**Closed by gtritchie** 2024-09-17 21:35 UTC
Labels: bug, source editor, quarto
