### ISSUE TITLE
SOCI and Packaging

### ISSUE THREAD

**Issue by stephensrmmartin** [rstudio/rstudio#6533] opened 2020-03-26 04:47 UTC
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : Latest git
    OS Version      : Arch linux 64bit
    R Version       : 3.6.3

# The problem
Currently, Rstudio is getting harder and harder to package. In the past year, the Rstudio source has been increasingly bundling large libraries (Qt, boost). Thankfully, the team has allowed for build-time configuration to disable this, or permit packagers to link to system libraries and use system headers. To be frank, this trend of bundling more and more dependencies with rstudio is making packaging much more difficult than it should be. 

SOCI is a recent addition to the codebase. Rstudio's build system wants to now bundle SOCI itself, and seemingly requires it to be installed in /opt/rstudio-tools at compile time. Moreover, the install-soci script requires root, and will install it to /opt. The cmake path is then hard coded to check this directory for SOCI. This needs to change. SOCI is fairly stable, and there is already a package available for us to use.

Like with Qt and boost, there should be an option to use the system-installed SOCI library and headers. In the very _least_, cmake should be configured to look for SOCI lib and includes in a subdirectory of the source tree at compile time. But ideally, there should be an option to find SOCI as a system library.
If there is already a means to change where cmake looks for SOCI (without patching...), please let me know. But if not, there should be a compile-time option for this (or... stop bundling external libraries, and rely on packagers to provide the dependencies and to specify the correct compile-time options like any other FOSS project).

**Comment by stephensrmmartin** [comment] 2020-03-31 22:42
For the time being, I am using this patch; this could probably be added as a pull request:

```
From 40f01db1d748d5df0bc3dfd1552a2c91943408e7 Mon Sep 17 00:00:00 2001
From: Stephen Martin <stephensrmmartin@gmail.com>
Date: Tue, 31 Mar 2020 14:55:34 -0700
Subject: [PATCH] Use system SOCI library on request.

---
 src/cpp/CMakeLists.txt | 15 ++++++++++-----
 1 file changed, 10 insertions(+), 5 deletions(-)

diff --git a/src/cpp/CMakeLists.txt b/src/cpp/CMakeLists.txt
index 9fff318025..598f34fd87 100644
--- a/src/cpp/CMakeLists.txt
+++ b/src/cpp/CMakeLists.txt
@@ -372,8 +372,10 @@ else()
 endif()
 
 set(SOCI_INCLUDE_DIR "${RSTUDIO_TOOLS_SOCI}/include")
-include_directories(SYSTEM ${SOCI_INCLUDE_DIR})
-include_directories(SYSTEM ${SOCI_INCLUDE_BUILD_DIR})
+if(NOT RSTUDIO_USE_SYSTEM_SOCI)
+    include_directories(SYSTEM ${SOCI_INCLUDE_DIR})
+    include_directories(SYSTEM ${SOCI_INCLUDE_BUILD_DIR})
+endif()
 
 # database library includes
 if (UNIX)
@@ -394,6 +396,9 @@ endif()
 # find SOCI libraries
 if(UNIX)
    set(SOCI_LIBRARY_DIR "${RSTUDIO_TOOLS_SOCI}/build/lib")
+   if(NOT APPLE AND RSTUDIO_USE_SYSTEM_SOCI)
+      set(SOCI_LIBRARY_DIR "/usr/lib")
+   endif()
    set(CMAKE_INSTALL_RPATH "${SOCI_LIBRARY_DIR}")
    if (NOT APPLE)
       set(LIB_SUFFIX ".so")
@@ -404,8 +409,8 @@ if(UNIX)
       set(SOCI_LIB_SYMLINK ".4.0${LIB_SUFFIX}")
       set(SOCI_LIB_SUFFIX ".4.0.0${LIB_SUFFIX}")
    endif()
-   file(GLOB_RECURSE SOCI_LIBRARIES "${SOCI_LIBRARY_DIR}/*${LIB_SUFFIX}")
-   file(GLOB_RECURSE SOCI_SYMLINK_LIBRARIES "${SOCI_LIBRARY_DIR}/*${SOCI_LIB_SYMLINK}")
+   file(GLOB_RECURSE SOCI_LIBRARIES "${SOCI_LIBRARY_DIR}/*soci*${LIB_SUFFIX}")
+   file(GLOB_RECURSE SOCI_SYMLINK_LIBRARIES "${SOCI_LIBRARY_DIR}/*soci*${SOCI_LIB_SYMLINK}")
 else()
    set(SOCI_LIBRARY_DIR "${RSTUDIO_TOOLS_SOCI}/build/${SOCI_ARCH}/lib")
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
@@ -436,7 +441,7 @@ message(STATUS "SOCI libraries found under ${SOCI_LIBRARY_DIR}.")
 
 # ensure the soci libraries are installed with the installation package on Linux
 # on OSX, the needed depdencies are copied into the Frameworks directory
-if(UNIX AND NOT APPLE)
+if(UNIX AND NOT APPLE AND NOT RSTUDIO_USE_SYSTEM_SOCI)
    install(PROGRAMS "${SOCI_LIBRARY_DIR}/libsoci_core${SOCI_LIB_SUFFIX}" DESTINATION ${RSTUDIO_INSTALL_BIN})
    install(PROGRAMS "${SOCI_LIBRARY_DIR}/libsoci_sqlite3${SOCI_LIB_SUFFIX}" DESTINATION ${RSTUDIO_INSTALL_BIN})
    install(PROGRAMS "${SOCI_LIBRARY_DIR}/libsoci_postgresql${SOCI_LIB_SUFFIX}" DESTINATION ${RSTUDIO_INSTALL_BIN})
-- 
2.26.0
```

**Comment by stephensrmmartin** [comment] 2020-03-31 23:58
Related bug:
serverdatabase uses rstudio_boost:: instead of boost::
Patch here:

```
From 6511e6ce3fef2fe628cbb436e30289829351f088 Mon Sep 17 00:00:00 2001
From: Stephen Martin <stephensrmmartin@gmail.com>
Date: Tue, 31 Mar 2020 16:30:47 -0700
Subject: [PATCH] Use boost, not rstudio_boost

---
 src/cpp/server_core/ServerDatabase.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/cpp/server_core/ServerDatabase.cpp b/src/cpp/server_core/ServerDatabase.cpp
index ad04faadb1..1ba5771076 100644
--- a/src/cpp/server_core/ServerDatabase.cpp
+++ b/src/cpp/server_core/ServerDatabase.cpp
@@ -199,7 +199,7 @@ boost::shared_ptr<IConnection> getConnection()
    return s_connectionPool->getConnection();
 }
 
-bool getConnection(const rstudio_boost::posix_time::time_duration& waitTime,
+bool getConnection(const boost::posix_time::time_duration& waitTime,
                    boost::shared_ptr<IConnection>* pConnection)
 {
    return s_connectionPool->getConnection(waitTime, pConnection);
-- 
2.26.0


```

The latest git now compiles with these two patches.

**Comment by kfeinauer** [comment] 2020-04-01 15:47
@stephensrmmartin I am taking a look at this. It looks like we can get away with using the system packages for all RStudio-supported Linux distros except for opensuse, where we will still need to compile from source. However, the common case should just be grabbing this from the system.

**Comment by kfeinauer** [comment] 2020-04-01 17:21
@stephensrmmartin Unfortunately after digging into this more, it looks like we'll have to ship our own compiled version of SOCI. We are relying on certain interfaces that are not available in every package repo, and we depend on boost integration functionality, which doesn't seem to exist in any of the precompiled system package that I tested.

However, we can still provide a means for forcing compile to the system libraries, like your patch accomplishes. I'll look into integrating similar functionality.

**Comment by stephensrmmartin** [comment] 2020-04-01 17:26
Thank you.

**Comment by jmcphers** [comment] 2020-04-01 17:48
@stephensrmmartin We can take your patch largely as-is if you're willing to submit a CLA as detailed in CONTRIBUTING: https://github.com/rstudio/rstudio/blob/master/CONTRIBUTING.md

**Comment by stephensrmmartin** [comment] 2020-04-01 18:16
Can do. Again - I do worry about not using the find_library functionality, just in case there are any libraries with *soci* in it. If someone could help me do that, I wouldn't mind trying it. 
I should send the CLA to jj@rstudio ?

**Comment by kfeinauer** [comment] 2020-04-01 19:01
Yes, please send the CLA to JJ. Much appreciated!

We could just grab the exact libraries that we are interested in, instead of using glob recurse.

The libraries we need are:

`libsoci_core.so`
`libsoci_sqlite3.so`
`libsoci_postgresql.so`

I can make that change on the branch we have going for this change: https://github.com/rstudio/rstudio/tree/feature/allow-system-soci

**Comment by kfeinauer** [comment] 2020-04-01 19:27
@stephensrmmartin changed to find_library in this commit: https://github.com/rstudio/rstudio/commit/80399eddd539c6ff7ad15260212149b99d5de591

**Comment by stephensrmmartin** [comment] 2020-04-01 19:50
Awesome; I can test that today. I'll send the CLA in sometime today also (hopefully). My scanner is... not cooperating.

**Comment by stephensrmmartin** [comment] 2020-04-01 20:56
What about the second linked [patch](https://github.com/rstudio/rstudio/issues/6533#issuecomment-606948914)

**Comment by stephensrmmartin** [comment] 2020-04-01 20:58
Ah nevermind: https://github.com/rstudio/rstudio/commit/48111a92bc881320f56a88cadfed6ca39da18f3a
Thanks for patching it up!

**Comment by stephensrmmartin** [comment] 2020-04-01 22:57
Just tested the feature/allow-system-soci branch. Compiles and runs without error! Thanks for the quick turnaround.

**Comment by kfeinauer** [comment] 2020-04-02 21:49
@stephensrmmartin We noticed an error when running some of our professional applications and noted that due to how the loader works on Linux, we are unable to use `RPATH` for SOCI. This necessitates statically linking.

Would ripping out all of the dynamic linking (shared objects) for SOCI cause you any pain here? Would it suit you to link statically to your own build of SOCI? I was planning on simply using `find_library` to search for `libsoci_core.a` and others, instead of linking to the shared objects.

**Comment by stephensrmmartin** [comment] 2020-04-02 23:22
Hm, let's back up a moment. Why are you unable to use RPATH for SOCI? Other than setuid'd programs ignoring rpath/runpath/ld_library_path, I'm unsure why dyn linking would be a problem (and if you need setuid exec bits set, there's likely a better way to avoid that problem anyway).

As for ripping out SO's, it would defeat the purpose of using the system lib in the first place. It would be painful, since the soci package includes .so's, rather than .a's. So I'd have to compile it myself within the source tree, or as a separate package, which, again, defeats the purpose of using the system lib. **If** you don't support both methods, I just request that the bundling/compilation of the static soci can take place *within the source tree* of rstudio itself (_compiling rstudio should never require touching anything outside its source directory, and especially nowhere requiring sudo privs as the current scripts do_).  Use a git submodule for it; or expect its source within a directory for compilation; just something other than requiring its presence at compile time in /opt.

**Comment by kfeinauer** [comment] 2020-04-03 14:55
Several RStudio applications initially start as root, and then lower privileges to a less privileged user (like `rstudio-server`) during the majority of their lifetime (while still maintaining the ability to regain root privilege if absolutely needed).

However, these applications frequently launch child processes, so at this point they are considered to be running in a secure execution context, as defined here: http://man7.org/linux/man-pages/man8/ld.so.8.html

> Secure-execution mode
>        For security reasons, if the dynamic linker determines that a binary
>        should be run in secure-execution mode, the effects of some
>        environment variables are voided or modified, and furthermore those
>        environment variables are stripped from the environment, so that the
>        program does not even see the definitions.
> 
> The process's real and effective user IDs differ, or the real and
>           effective group IDs differ.  This typically occurs as a result of
>           executing a set-user-ID or set-group-ID program.

Therefore, when the loader loads the `.so` files for the child processes, `RPATH` is completely ignored.

I chose to compile SOCI outside of the build tree similar to how we do Boost due to the prior art there - I'll discuss with some folks if moving it into the build tree is something we want to do. If not, I should be able to support falling back to the `.so` files if the `.a` files are not present.

**Comment by stephensrmmartin** [comment] 2020-04-03 20:29
Thank you for supporting the .so method.

It wouldn't be that hard for me to support .a files and static linking on my end _if_ it looked for them within the source tree somewhere. We largely patch out the bundled libs when possible for two reasons: 1) It's, so far, been unnecessary to have them [system libs have worked fine], so there's much less system bloat to just use system libs [esp. wrt qt and boost]. 2) The scripted build process defined in the source tree pollutes the build environment, and is opposed to best practices. If you can only build a source project in a chroot to avoid polluting root and home with untracked files, then that source project is against best practices. Hence: Ideally, either the build process is fully contained within the source tree, or needed deps are available in the repos.

As for LD problems; I think a long-term solution would be:
1) Allow system libs at compile time
2) When bundling libraries, pull any needed libraries into a standard directory within the source tree at compile time (git submodules are good for this; but a script would do too). The key part here is: _within the source tree_. This is simply to adhere to good practice - Compiling source shouldn't require running scripts that touch / in particular, but generally not anything outside the source tree anyway. It pollutes the environment and requires chroots to avoid it.
3) When bundling libraries: Install to /opt/rstudio{-server}/lib, or /usr/lib/rstudio{-server}/lib. Then one could use a fixed RPATH or RUNPATH, and that would work with suid binaries (I think RPATH/RUNPATH are only failing for you because with SUIDs, it doesn't expand $ORIGIN).

I'm unsure why you need suid binaries though; it seems fairly rare nowadays that one needs suid binaries. Seems like most daemons will start as root, deescalate, and that doesn't trigger the secure-execution problem as far as I know. Is there a way to reproduce the error using rstudio-server free?

**Comment by kfeinauer** [comment] 2020-04-03 20:48
Good point about the `$ORIGIN` expansion - that makes sense as to why `RPATH` was not working. The approach you mentioned for bundling libraries is a great idea to think about for the future if we start pulling in more dependencies (we try to keep the list as small as possible)!

RStudio launches executables on behalf of other users, which run as that particular user. So for example we start as root, give up root privilege, then launch a binary as another user, which requires us to fork and then change users, which requires a real user of root.

I think you may be able to trigger this issue by running the open source version on centos7 with one of the daily builds when trying to launch a session, but I haven't tested this for sure. At any rate, at least for this dependency for now, it was very easy to just switch to static linking for our distributable, which I've done in https://github.com/rstudio/rstudio/pull/6586.

**Comment by jmcphers** [comment] 2020-04-07 17:01
#6586 caused most Linux builds to fail with this error:

```
[2020-04-07T10:37:23.309Z] /usr/bin/ld: /opt/rstudio-tools/soci/build/lib/libsoci_core.a(backend-loader.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
[2020-04-07T10:37:23.309Z] //lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
[2020-04-07T10:37:23.309Z] collect2: error: ld returned 1 exit status
[2020-04-07T10:37:23.309Z] src/cpp/core/CMakeFiles/rstudio-core-tests.dir/build.make:863: recipe for target 'src/cpp/core/rstudio-core-tests' failed
[2020-04-07T10:37:23.309Z] make[2]: *** [src/cpp/core/rstudio-core-tests] Error 1
[2020-04-07T10:37:23.309Z] CMakeFiles/Makefile2:360: recipe for target 'src/cpp/core/CMakeFiles/rstudio-core-tests.dir/all' failed
[2020-04-07T10:37:23.309Z] make[1]: *** [src/cpp/core/CMakeFiles/rstudio-core-tests.dir/all] Error 2
```

It has been reverted to get the builds healthy again, so reopening this until we have the right change.

**Closed** 2020-04-08 16:06 UTC
Labels: enhancement

**Comment by R-Hannibal** [comment] 2020-08-31 17:54
@stephensrmmartin, thank you for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by stephensrmmartin** [comment] 2020-08-31 18:15
@R-Hannibal Could you tell me which git commit would be a good test? Or is it just the current master?

**Comment by R-Hannibal** [comment] 2020-08-31 18:45
@stephensrmmartin - the commit is in the latest batch of Daily builds, anything recent from the 1.4 branch.

**Comment by stephensrmmartin** [comment] 2020-08-31 23:28
@R-Hannibal I am unsure what fix was put in place. Did this undo the changes I had previously made?

1) It is currently searching for libsoci_.* in `/opt/rstudio-tools/soci/{include, build/lib}` for the libraries.
2) These directories do not exist.
3) They would exist if I ran the script, but I am not going to trample on root for the sake of running a packaging script.
4) There needs to be a way to either A) Set a location for SOCI libraries (i.e., just look in /usr/lib, and /usr/include for headers; as you would any other library) or B) Have an *in-tree* directory for libs to be symlinked. Building a package *should not require root privs, nor should it touch root in an untracked way*. 

What do you suggest I do? We are not going to run any scripts that require the modification of root (this is very, very bad practice). We are not going to run any scripts that require root privs. And I submitted a prior patch with a `-DRSTUDIO_USE_SYSTEM_SOCI` patch that globs for soci libs in /usr/lib. That approach worked for us. Is there some new fix that I am missing? Do I need to reapply my patch? Is there a cmake -D declaration that will tell rstudio where to look for these bundled libs if desired?

**Comment by kfeinauer** [comment] 2020-09-01 15:06
@stephensrmmartin I had changed your method of globbing in `/usr/lib` in favor of using the `find_library` CMAKE mechanism. 

```
find_library(SOCI_CORE_LIB NAMES "libsoci_core.a" "soci_core" PATHS "${SOCI_LIBRARY_DIR}" NO_DEFAULT_PATH)
find_library(SOCI_SQLITE_LIB NAMES "libsoci_sqlite3.a" "soci_sqlite3" PATHS "${SOCI_LIBRARY_DIR}" NO_DEFAULT_PATH)
find_library(SOCI_POSTGRESQL_LIB NAMES "libsoci_postgresql.a" "soci_postgresql" PATHS "${SOCI_LIBRARY_DIR}" NO_DEFAULT_PATH)
```

The `SOCI_LIBRARY_DIR` is set to `/usr/lib` per your earlier request when `RSTUDIO_USE_SYSTEM_SOCI` is set for the invocation of CMAKE. This will cause all of the libraries to be found under `/usr/lib` - note that we are statically linking, so we are looking for the `.a` files.

**Comment by kfeinauer** [comment] 2020-09-01 15:14
Also @stephensrmmartin it should be mentioned that nothing has changed since we worked on this together many months back in April - we are just now in the process of doing more in-depth QA verification for this 1.4 release so that's why Mario reached out to make sure this was working as you would expect.

**Comment by stephensrmmartin** [comment] 2020-09-01 17:48
Ah, you know the problem? My v1.4 branch checkout does not include whatever commits you are talking about. I apologize.

I checked out the v1.4 branch from here, but it does not include commits past March 13. It appears the `master` branch does have these changes, so I will use that to test.

I'll get back to you once I test it out. It looks like it globs for both .a and .so files (the latter, implicitly, thanks to find_library). That's good news.

**Comment by stephensrmmartin** [comment] 2020-09-01 18:05
It works; great job! Cmake is kind enough, it seems, to dynamically link when .so is found, and statically link when .a is found. I have no .a's on my system (aside from gcc and clang), but linking was successful. It built, installed, and started just fine. I tested this on rstudio-server, but I presume the desktop release would also work.

This was tested on commit bdf0b8b38b1c36d5c41003f0fe934a8f90d209a9

**Comment by kfeinauer** [comment] 2020-09-01 18:19
Excellent! Thanks Stephen!

**Comment by R-Hannibal** [comment] 2020-09-01 18:34
Marking this issue as verified, thanks so much for the assist @stephensrmmartin!
