### ISSUE TITLE
Visual Mode replaces newlines with spaces and makes other changes to Rmd file

### ISSUE THREAD

**Issue by skranz** [rstudio/rstudio#7938] opened 2020-10-01 16:51 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.890
    OS Version      :  Windows 10
    R Version       : 4.02

### Steps to reproduce the problem

Create a Rmd file in source mode with the content:

```
line1
line2
line3
```
Change to visual mode and then back to source mode. Then my source file looks like
```
line1 line2 line3
```
The line breaks are replaced by spaces. 

### Describe the problem in detail

Updated: I did not see this behavior described here:

https://rstudio.github.io/visual-markdown-editing/#/markdown?id=markdown-output

There are also other rewrites that would be great if they could be disabled, like I often use blocks starting like
```
#< info
```
A roundtrip source-visual-source mode changes such a line to
```
\#\< info
```
But I guess that is part of the Pandoc Markdown specs.

### Describe the behavior you expected

It would be great if visual mode would keep the source RMD file as much as possible as it is. Perhaps a warning could be shown if an automatic rewrite takes place. That would reduce the risk that users unknowingly save such undesired rewrites.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-10-01 17:22
Duplicate of https://github.com/rstudio/rstudio/issues/7922. This is intentional, based on the way the Pandoc AST functions. https://rstudio.github.io/visual-markdown-editing/#/markdown?id=markdown-output

**Closed by kevinushey** 2020-10-01 17:22 UTC
