### ISSUE TITLE
Diagnostics Toggles not Working

### ISSUE THREAD

**Issue by jhuntergit** [rstudio/rstudio#4253] opened 2019-02-01 14:52 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Preview Version 1.2.1256
    OS Version      : Windows 7 Professional
    R Version       : 3.5.1

### Steps to reproduce the problem

[![diagnostic options][1]][1]

  [1]: https://support.rstudio.com/hc/en-us/article_attachments/201696637/Screen_Shot_2015-04-30_at_1.54.08_PM.png

Enable all diagnostics in the `Tools -> Global Options -> Code -> Diagnostics` options panel as shown above. Then enter code into an `*.R` script with typos, non-whitespace, missing arguments, etc. Sample provided:

```
libbbrary(tidyverse)

x<-2+1

add_number <- function(x, y) {
  x + y
}

add numbers(1)
```

### Describe the behavior you expected

At some point in the past code I wrote was noticed by R Studio to contain errors, and there were symbols (warning signs, red x, etc.) put in the margins to clue me in to the errors in my code/syntax. Those symbols are no longer there at all, and I figured I needed to toggle the diagnostics back on. But the diagnostics aren't toggled off. They're all on as shown in the image far above. 

How do I get these warning and informational symbols back? Any idea what may be the issue?

**Comment by ronblum** [comment] 2019-02-06 15:19
@jhuntergit Thanks for raising this. Is this problem occurring after saving the file? The diagnostics don't kick in until after you first save the file. That only way I'm able to reproduce this issue is for new, unsaved scripts.

**Comment by jhuntergit** [comment] 2019-02-07 20:35
It does occur whether the script is saved or not. It's only happening on one of my computers as well. Can't repro it on other similar setups. I'll probably just ignore it for now.

**Comment by jmcphers** [comment] 2019-04-03 17:03
Closing since we don't have a repo (but please feel free to reopen if you get more details!)

**Closed by jmcphers** 2019-04-03 17:03 UTC
Labels: repro needed

**Comment by sebiii96** [comment] 2019-11-16 10:13
For me the diagnostics also only show when I save the file
