### ISSUE TITLE
Console automatically jumping back to most recent line

### ISSUE THREAD

**Issue by fjcarton** [rstudio/rstudio#2500] opened 2018-03-26 06:21 UTC
Dear RStudio,

While using your great app, I stumbled upon something that might be worth changing or creating an option for it. It has to do with the fact that the console pane jumps back down, when a new entry is added to it. This happens also if it is an entry of the program itself. Currently I'm using h2o and with the progress bars included into this package, it is impossible to scroll up, while the code is running, in order to check previous code since every second it jumps down to add a "=" to the progress bar.

Is there a way to stop this or could be please make a way to stop this, since it bothers me a lot.

With kind regards

**Comment by jjallaire** [comment] 2018-03-26 10:11
We in theory have code that should prevent this (when the console is scrolled up we should be suppressing automatic scrolling) but clearly this isn't working in your case. Could you provide information on the version/platform of RStudio you are using?

**Comment by fjcarton** [comment] 2018-03-26 10:36
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.9 (Santiago)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2     rsparkling_0.2.2 h2o_3.10.4.6     dplyr_0.7.3      sparklyr_0.6.3  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10    compiler_3.4.1  dbplyr_1.1.0    plyr_1.8.4      bindr_0.1       bitops_1.0-6    base64enc_0.1-3 tools_3.4.1    
 [9] digest_0.6.12   jsonlite_1.5    tibble_1.3.4    nlme_3.1-131    lattice_0.20-35 pkgconfig_2.0.1 rlang_0.1.2     psych_1.7.3.21 
[17] shiny_1.0.5     DBI_0.7         rstudioapi_0.6  yaml_2.1.14     parallel_3.4.1  withr_2.0.0     httr_1.3.1      stringr_1.2.0  
[25] rprojroot_1.2   grid_3.4.1      glue_1.1.1      R6_2.2.0        foreign_0.8-69  reshape2_1.4.2  tidyr_0.7.1     purrr_0.2.3    
[33] magrittr_1.5    backports_1.0.5 htmltools_0.3.5 assertthat_0.1  mnormt_1.5-5    mime_0.5        xtable_1.8-2    httpuv_1.3.5   
[41] config_0.2      stringi_1.1.2   openssl_0.9.6   RCurl_1.95-4.8  lazyeval_0.2.0  broom_0.4.2

**Comment by jjallaire** [comment] 2018-03-26 10:43
RStudio desktop or server? If server what browser are you using to access
it?

Which version of RStudio?

**Comment by fjcarton** [comment] 2018-03-26 10:58
Aaah, its a Studio server on version 1.0.143 running in Firefox 40.0.3 on a Red Hat Enterprise Linux Server release 6.9.

**Comment by jjallaire** [comment] 2018-03-26 12:40
Okay, the v1.0 release series is nearly 18 months old. It's fairly likely that this has been fixed in the most recent release (v1.1). @pyltime Can you confirm whether this is likely to be fixed? If not let's see what we might still need to do here.

**Comment by jmcphers** [comment] 2019-11-19 23:17
We can't reproduce this in the latest 1.2 release (1.2.5019). Feel free to reopen if you're still seeing it!

**Closed by jmcphers** 2019-11-19 23:17 UTC
Labels: repro needed
