### ISSUE TITLE
Regression in wide data.frame display 

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#8821] opened 2021-01-27 16:29 UTC
Create a wide data frame and `View` it:

```
lst <- 1:100 
names(lst) <- num2str(1:100) 
df <- rbind(lst)
View(df)
```

The left/right cols buttons at the data view look like empty squares, and after you click 'right' the col index display is wrong:
![image](https://user-images.githubusercontent.com/73080/106021282-4b21ca80-60cd-11eb-8191-25f20c4fcc82.png)

-->

### System details

    RStudio Edition : Server
    RStudio Version : 1.4
    OS Version      : ubuntu 18
    R Version       :  3.4

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by OfekShilon** [comment] 2021-01-27 19:06
On RStudio desktop the right/left icons are fine - but the column range is still wrong:
![image](https://user-images.githubusercontent.com/73080/106040709-7fa08100-60e3-11eb-9e3d-50e19aa12cdf.png)

**Comment by ronblum** [comment] 2021-01-28 15:55
@OfekShilon Thank you for raising the issue! I can reproduce the icon issue in RStudio Server on
- Red Hat 8.3
- Ubuntu 20.04
- SLES 15 SP2, with a mixture of 1.4.1103 and 1.4.1514. I can also reproduce the range issue in RStudio Desktop 1.4.1507 on MacOS 11.1, on the second page (click on the right arrow). We'll review this as we continue development of RStudio

**Comment by noahlove** [comment] 2021-02-26 18:41
Issue persists in 1.4.1106 on Ubuntu 20.04

**Comment by OfekShilon** [comment] 2021-09-25 12:01
Any plans to fix this?

**Comment by ronblum** [comment] 2021-09-27 13:05
@OfekShilon I can't reproduce this anymore in the latest preview of [Ghost Orchid 2021.09](https://www.rstudio.com/products/rstudio/download/preview/) (formerly 1.5). Can you reproduce the issue with this build? Note that previews are meant for testing purposes, but we're getting ready to imminently release this as the final release.

**Comment by OfekShilon** [comment] 2021-09-28 20:44
@ronblum I'm able to personally install only the desktop version - and it seems ok. The version with the full display problem was a server one, and I'm unable to verify it.  
Anyway, good to know this was addressed. Thanks!

**Comment by ronblum** [comment] 2021-09-29 13:10
@OfekShilon You're welcome! I tried it in RStudio Server 2021.09+351 on Ubuntu 20.04 via Firefox on Ubuntu 20.04, so this covers server, too. Thank you for checking with RStudio Desktop!

**Comment by mikebessuille** [comment] 2021-09-29 17:59
Duplicate of #9623

**Closed by mikebessuille** 2021-09-29 17:59 UTC
Labels: bug, reproducible, data viewer
