### ISSUE TITLE
Data viewer doesn't auto refresh on source data changing

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#7066] opened 2020-06-08 20:21 UTC
In the R console:
```
1. d <- c(1,0)
2. View(d)
3. d <- c(2,0)
```

Notice that the data doesn't update and you have to View(d) again to see it. This must have been broken in the last performance PR on the DataViewer. Instinct says this should be fairly trivial to fix and some watcher just got lost in the mix.

**Comment by jmcphers** [comment] 2020-06-08 20:25
Reported several times on community forum: https://community.rstudio.com/t/the-data-viewer-does-not-auto-refreshing/68696

**Comment by adamconroy** [comment] 2020-06-18 22:02
I actually can't reproduce this anymore. I wonder what happened. Could I get a quick sanity check @dfalty or @ronblum ?

**Comment by dfalty** [comment] 2020-06-22 15:08
Hey @adamconroy, I can reproduce this on my desktop (Mac 10.15.2) on 1.3.1039 but it looks fixed on 1.4.497 for me. Maybe something in 1.4 fixed this?

**Comment by adamconroy** [comment] 2020-06-22 17:17
Thanks Darby. I'll play around with different versions and distros. I have a feeling it might be a heisenbug (goes away when I look at it in a dev environment) because the debug/logging infrastructure shunts away the error condition.

**Comment by kevinushey** [comment] 2020-06-26 19:42
Here's the JS callstack when the exception occurs:

<img width="857" alt="Screen Shot 2020-06-26 at 12 03 58 PM" src="https://user-images.githubusercontent.com/1976582/85892077-21a26880-b7a5-11ea-9ba9-8ab61819cb4f.png">

It's worth noting that this exception in older versions of RStudio as well (tested back to v1.1). It seems like (as @adamconroy said) there are multiple copies of this `DataEditingTarget` class receiving data update events here, but only one is actually "live".

We can get a stack trace for each instantiation:

<img width="896" alt="Screen Shot 2020-06-26 at 12 38 16 PM" src="https://user-images.githubusercontent.com/1976582/85894691-1998f780-b7aa-11ea-90db-165a1be9cc05.png">

<img width="892" alt="Screen Shot 2020-06-26 at 12 38 31 PM" src="https://user-images.githubusercontent.com/1976582/85894698-1e5dab80-b7aa-11ea-8645-162b809ce5ae.png">

Note that in the first case, we're getting an instantiation as part of `getDefaultNamePrefix()`; in the second case, we're getting it as part of just `getEditingTarget()`. That points to code here:

https://github.com/rstudio/rstudio/blob/075c2c67982312ad20b1659ad070751f68f776a4/src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java#L466-L468

_In theory_, these should be receiving GWT-injected objects here:

https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetSource.java#L58-L74

But it seems like those calls to `get()` are actually producing separate editing targets. Because of that, we end up with multiple editing targets attached to the same document, but with one of those targets being left half-initialized (but still listening for and incorrectly-handling events).

**Comment by kevinushey** [comment] 2020-06-26 21:12
I wonder if this comes down to `isActive_` not being set in `onActivate()`? See e.g.

https://github.com/rstudio/rstudio/blob/bd1aa6f3290651ece6ba121c46afd00a4fc378ca/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java#L120-L145

We set the flag in the constructor, but it seems like that flag should be set / unset in `onActivate()` / `onDeactivate()`.

**Comment by adamconroy** [comment] 2020-06-26 21:33
will give it a go! most of this file hasn't been touched in 5-6 years but I wouldn't be surprised if a change somewhere else broke this.

**Comment by adamconroy** [comment] 2020-06-26 21:38
Look at that, it works...making a PR now. Great find! We still get the UmbrellaException sadly but at least the DataViewer updates.

**Closed** 2020-06-26 21:57 UTC
Labels: data viewer, reproducible

**Comment by R-Hannibal** [comment] 2020-06-29 14:35
Verified Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows 10 - Desktop 

Compared functionality between 1.3.1045 and 1.3.1054 builds, pre-fix `View(d)` has to be run a 2nd time to update the data, with the fix the data is updated immediately after running `d <- c(2,0)`.
