### ISSUE TITLE
RStudio 1.3.093 crashes on Mac OS X Catalina 10.15.7 when rebuilding library

### ISSUE THREAD

**Issue by gilbertocamara** [rstudio/rstudio#8319] opened 2020-11-09 11:42 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.3.093
    OS Version      :  Mac OS X Catalina 10.15.7 
    R Version  :  4.0.3
    Hardware: Mac Mini 3.2 6-core I7 with 32 GB memory

### Steps to reproduce the problem
RStudio is crashing randomly, but most often when rebuilding a package

### Describe the problem in detail
I am developing an R package (github.com/e-sensing/sits). After executing a function, finding a bug and fixing it, I run BUILD to rebuild the package. I am getting the following error:

"Error: C stack usage 7969216 is too close to the limit"
"Error saving session (options): R execution error"
WARNING: "Forcing suspend of process in spite of all session data not being fully saved". 

Then a pop-up window appears with the message: "R encountered a fatal error. The session was terminated". 

### Describe the behavior you expected
This behavior is new and has started since I upgraded Mac OS X Catalina. I had not seen such behaviour in earlier versions of Mac OS X. I have tried to downgrade RStudio to version 1.2, but the problem remains. 

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5510154/diagnostics-report.txt)

**Comment by kevinushey** [comment] 2020-11-09 19:13
Do you have the latest version of the `cpp11` package installed? (We had a similar issue reported that was related to an older version of that package which should now be fixed)

**Comment by gilbertocamara** [comment] 2020-11-09 19:24
Hi Kevin, I installed the latest version of the cpp11 package, but the crash continues. I have also tried to reproduce the problem in "plain R" (outside of RStudio), but the R code works fine. So, I am at a loss to understand what is happening.

**Comment by ronblum** [comment] 2020-11-10 16:56
@kevinushey I'm unable to reproduce this, both on Catalina 10.15.7 on a MacBook Pro with 16GB RAM, or on Big Sur 1.0.1 beta 20B5022a on a MacBook Pro with 32 GB RAM, both using RStudio Desktop 1.3.1093. To include the step to fix a broken function, I first changed from `int` to `intx` in the code for `apply_transition_matrix`.

**Comment by gilbertocamara** [comment] 2020-11-10 17:00
I think I found the problem by debugging step by step. The problem is caused by an error in the function read_delim of the "readr" package. A similar problem has been reported here: https://github.com/tidyverse/readr/issues/1141. It appears that "readr" is leaking memory, which causes RStudio to crash. I'll build a MRE and report as an issue in the "readr" github. Thanks for the support.

**Comment by kevinushey** [comment] 2020-11-10 19:27
Thanks! We'll close the issue on our side.

**Closed by kevinushey** 2020-11-10 19:27 UTC
Labels: bug, build pane

**Comment by benjaminhlina** [comment] 2020-11-17 02:39
@gilbertocamara have you been able to resolve this issue with readr on your end? The session crashing is so inconsistent to the point that I can't even make a reprex for it because it sometimes works and sometimes crashes. See the newest update of tidyverse/readr#1141.
