### ISSUE TITLE
Install of RStudio 1.2.5006 nuked an installed custom theme

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#5480] opened 2019-09-27 19:18 UTC
grabbed 1.3.5006 & fired it up

I had `rstudioapi::addTheme("https://raw.githubusercontent.com/patrickshox/Mojave-Dark-RStudio-Theme/master/Mojave%20Dark.rstheme", apply=TRUE, force=TRUE)` already installed (and working apart from some theme elements not being themed).

upon fire-up the theme was not active nor present/installed.

it worked fine on re-install (and was there on rstudio shutdown/restart).

Latest macOS Vista beta.

**Comment by kevinushey** [comment] 2019-09-27 19:24
I wonder if this is caused by going from a v1.3 daily build back to a v1.2 release build? Due to changes in how preferences are handled.

**Comment by jmcphers** [comment] 2019-09-27 19:26
Very likely. RStudio 1.3 stores themes in a different location, and RStudio doesn't know to read themes from that location, so themes you install in 1.3 won't be visible in 1.2. @hrbrmstr does that align with your experience?

**Comment by hrbrmstr** [comment] 2019-09-27 20:28
Nay. I only run Dailies on the system this happened on.

**Comment by hrbrmstr** [comment] 2019-09-27 20:52
wait

my "download latest daily" script downloaded 1.2

so that's what this was.

Now the question is

Why is https://www.rstudio.org/download/latest/daily/desktop/mac/RStudio-latest.dmg pointing to a 1.2 daily?

**Comment by hrbrmstr** [comment] 2019-09-27 20:52
apologies for the confustion

**Comment by kevinushey** [comment] 2019-09-27 21:32
The problem is that this links to "the most recently generated build", which may be either a v1.3 "daily" build or, as in the case, a v1.2 patch release.

We should probably ensure that our `RStudio-latest.dmg` link only gets updated if the version number truly has been incremented from the previous release, or something similar.

**Comment by jmcphers** [comment] 2019-10-17 17:45
This is no longer tracking a product bug, so closing. @hrbrmstr thanks for reporting, and I think that the 1.2/1.3 theme locations explain the behavior you saw (please feel free to reopen/comment if this isn't the case!)

**Closed by jmcphers** 2019-10-17 17:45 UTC
Labels: bug
