### ISSUE TITLE
When in Project and Restart R, Working Dir Changes

### ISSUE THREAD

**Issue by abfleishman** [rstudio/rstudio#7288] opened 2020-07-07 15:19 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.3.959
    OS Version      :  Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem
- Open an RStudio project
- run some code 
- use the `session` menu to `Restart R`
- check working directory and it is no longer the project directory, it is the default working directory  
### Describe the problem in detail
When you restart R from the session menu, while in a studio project, the working directory changes to the default working directory for the system not the project directory.  This is not the most useful screenshot, but It shows that I just restarted R and that the working dir changed and is not the project that I am in.
![image](https://user-images.githubusercontent.com/9219852/86803036-79a16080-c02a-11ea-8eef-2163a747c937.png)

### Describe the behavior you expected
No change in working dir

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-07-17 14:50
@abfleishman Thank you for filing the issue! I'm unable to reproduce it, though. What happens when you're not in a session?

**Comment by abfleishman** [comment] 2020-07-17 22:43
@ronblum This issue was happing and quite annoying a few weeks ago, but sometime since when I opened it and now, it stopped happening! I just tried to reproduce and couldn't.

**Comment by ronblum** [comment] 2020-07-20 18:57
@abfleishman As much as I'd like to understand what went wrong, I'm glad it's working now! I'll close the issue. Let us know if it starts to happen again. Thanks!

**Closed by ronblum** 2020-07-20 18:57 UTC
Labels: bug, repro needed
