### ISSUE TITLE
Viewer pane fails to recongnize local web contents on Windows

### ISSUE THREAD

**Issue by yutannihilation** [rstudio/rstudio#3577] opened 2018-10-01 22:02 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1013
    OS Version      :  Windows 10
    R Version       :  3.5.1
    Locale          : Japanese_Japan.932

### Steps to reproduce the problem

```r
reprex::reprex({print(1)})
```

### Describe the problem in detail

With Preview version of RStudio, `reprex::reprex()` will launch a web browser, not Viewer pane. I fixed once this problem on reprex's side (https://github.com/tidyverse/reprex/pull/75), but now it occurs again. Are there any changes on how to determine a content is local or remote?

### Describe the behavior you expected

Open the document in Viewer pane.

**Comment by kevinushey** [comment] 2018-10-01 22:06
What is the value of `getOption("viewer")` in your session?

**Comment by yutannihilation** [comment] 2018-10-01 22:10
Here's the result:

```
> getOption("viewer")
function (url, height = NULL) 
{
    if (!is.character(url) || (length(url) != 1)) 
        stop("url must be a single element character vector.", 
            call. = FALSE)
    if (identical(height, "maximize")) 
        height <- -1
    if (!is.null(height) && (!is.numeric(height) || (length(height) != 
        1))) 
        stop("height must be a single element numeric vector or 'maximize'.", 
            call. = FALSE)
    invisible(.Call("rs_viewer", url, height))
}
<environment: 0x0000024e428d1288>
```

**Comment by kevinushey** [comment] 2018-10-01 22:13
Strange; I can't reproduce the issue (output shows up in the Viewer pane as expected for me).

One other thing I can think of checking -- what is the output of `tempdir()` on your system?

Also, can you confirm that the 'viewer' function is indeed being called? E.g. with `trace(getOption("viewer"))`. If not, then you're probably being routed to browseURL (`trace(getOption("browser"))`)

**Comment by yutannihilation** [comment] 2018-10-01 22:32
Hmm, I thought there's some chnage around `rs_viwer` or `realPath`, but it seems there has been no change for years. Strange...

https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/src/cpp/session/modules/viewer/SessionViewer.cpp#L271

https://github.com/rstudio/rstudio/blob/4febd2feba912b2a9f8e77e3454a95c23a09d0a2/src/cpp/core/system/PosixSystem.cpp#L155

**Comment by kevinushey** [comment] 2018-10-01 22:32
I think RStudio is getting confused by the so-called Windows 'short' path name. Compare e.g.

```R
contents <- "<html><body>Hello, world!</body></html>"

dir <- tempfile("html-")
dir.create(dir)
file <- file.path(dir, "reprex.html")
writeLines(contents, con = file)

viewer <- getOption("viewer")

# opens in Viewer
viewer(normalizePath(file, winslash = "/"))

# opens in external browser
viewer(shortPathName(file))
```

And compare e.g.

```R
> normalizePath(file)
[1] "C:\\Users\\kevin\\AppData\\Local\\Temp\\RtmpGWdb7r\\html-1fd4230037c8\\reprex.html"
> shortPathName(file)
[1] "C:\\Users\\kevin\\AppData\\Local\\Temp\\RTMPGW~1\\HTML-1~3\\REPREX~1.HTM"
```

**Comment by yutannihilation** [comment] 2018-10-01 22:45
I'm confused, it seems the opposite of what I found on https://github.com/tidyverse/reprex/pull/75...?

And both `viewer(normalizePath(file, winslash = "/"))` and `viewer(shortPathName(file))` open in external browser on my Environment.

**Comment by kevinushey** [comment] 2018-10-01 22:51
That's surprising :-/

Normally, RStudio is supposed to check to see whether the HTML file lives within a sub-directory of the R temporary directory; if it does, RStudio will open it within the Viewer pane.

I'm not sure what else could be causing this. Do you see the same behavior in RStudio v1.1, or does the file properly open in the viewer in that case?

**Comment by yutannihilation** [comment] 2018-10-01 23:36
> Do you see the same behavior in RStudio v1.1

Sorry, this happens on RStudio v1.1, too. So, the change is maybe because of some change introduced in reprex package, not in RStudio. Maybe I should close this issue for now, and file a new one again after some investigation... Sorry for the mess.

However, different from your case, none of the following opnes in Viewer pane:

``` r
viewer(normalizePath(file))
viewer(normalizePath(file, winslash = "/"))
viewer(shortPathName(file))
```

Only this worked:

``` r
viewer(file)
```

**Comment by kevinushey** [comment] 2018-10-01 23:45
This is all pretty surprising to me; I'm not sure what the underlying cause of this behavior could be.

For posterity, how do the file paths differ in each case?

**Comment by yutannihilation** [comment] 2018-10-02 01:12
> how do the file paths differ in each case?

I think it's basically same as yours. I've left from in front of my Windows today, so I'll post tomorrow, maybe.

**Comment by yutannihilation** [comment] 2018-10-02 12:04
Here's the result:

``` r
dir <- tempfile("html-")
dir.create(dir)
file <- file.path(dir, "reprex.html")
writeLines(contents, con = file)
#> Error in writeLines(contents, con = file): object 'contents' not found

file
#> [1] "C:\\Users\\HIROAK~1\\AppData\\Local\\Temp\\RtmpuCO9hS\\html-244634e38a8/reprex.html"
normalizePath(file)
#> [1] "C:\\Users\\hiroaki-yutani\\AppData\\Local\\Temp\\RtmpuCO9hS\\html-244634e38a8\\reprex.html"
normalizePath(file, winslash = "/")
#> [1] "C:/Users/hiroaki-yutani/AppData/Local/Temp/RtmpuCO9hS/html-244634e38a8/reprex.html"
shortPathName(file)
#> [1] "C:\\Users\\HIROAK~1\\AppData\\Local\\Temp\\RTMPUC~1\\HTML-2~1\\REPREX~1.HTM"
```

<sup>Created on 2018-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kevinushey** [comment] 2018-10-02 16:54
So in your case, it works with the short path version of your home directory, but not the long-path version? But it doesn't work if other elements in the path are short-path versions?

**Comment by kevinushey** [comment] 2018-10-02 17:27
I can reproduce on a user account where the user name gets truncated to the 'short' pathname version. It looks like there's a bug where RStudio doesn't canonicalize the home directory correctly in some cases when it's represented as a short path name.
This might be tricky to get right in RStudio (I don't think we're comfortable fixing this for v1.2) but you should be able to work around it with something like:

```R
short_home <- function(path) {
  path <- normalizePath(path)
  tmpdir <- normalizePath(tempdir())
  if (regexpr(tmpdir, path, fixed = TRUE) == 1)
    path <- sub(tmpdir, tempdir(), path, fixed = TRUE)
  path
}
```

**Comment by yutannihilation** [comment] 2018-10-03 00:14
Thanks, I didn't think username part matters...

Also thanks for the workaround. I will propose it to reprex package.

**Comment by jennybc** [comment] 2018-10-19 22:38
@kevinushey Can you give me exact info on what Rstudio regards as the filepath for session temp directory when deciding if a file can be opened in the Viewer pane? I gather I need to do *post hoc* regex substitution, but I still a bit uncertain re: my target.

**Comment by jmcphers** [comment] 2020-01-03 00:48
The check is here:

https://github.com/rstudio/rstudio/blob/063457a32b589ac7d723785e1e62bd4c210d1a41/src/cpp/session/SessionModuleContext.cpp#L2319-L2335

**Comment by kevinushey** [comment] 2020-02-13 23:44
Another report: https://community.rstudio.com/t/how-to-have-reprex-render-in-viewer-tab

**Comment by yihui** [comment] 2020-05-25 21:36
I have spent several hours on debugging an issue on Windows (https://github.com/rstudio/blogdown/issues/404) that I think is similar to this one, but I still haven't had a clue. The URL is supposed to be opened in the viewer, but _sometimes_ it is opened in the system browser instead. To reproduce the issue, `install.packages('blogdown')` and run this in any non-empty directory:

```r
servr::httw()
```

Then keep trying this for a few times:

```r
blogdown:::touch_file(list.files()[1]); servr::httw()
```

Most of the time, the URL is correctly opened in the viewer, but sometimes the web browser of the system will start, and it opens a URL of this pattern:

```
http://127.0.0.1:5932/?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A24654
```

I may be able to figure out a more minimal example (the example above has been minimized from https://github.com/rstudio/blogdown/issues/404), but I want to report it at this point to see if any of you could have an idea. Basically, what `servr::httw()` does is to refresh the browser (`location.reload()`) when it detects changes in modification times of files under the current working directory. When the viewer fails to open the URL (but starts the system browser instead), I try to run `location.reload()` in the RStudio DevTools, and indeed it opens the system browser instead of refreshing the viewer.

I'm wondering how RStudio decides a URL should be opened in the viewer or the external browser. I guess it won't help even if I know this, because running `location.reload()` in the DevTools shouldn't have opened the external browser...

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
[5] LC_TIME=English_United States.1252
system code page: 936

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.0 tools_4.0.0
```

**Comment by kevinushey** [comment] 2020-06-09 23:23
Thanks @yihui! I've taken a closer look and think I have an idea as to what's going on here -- it looks like there's a race condition in:

1. Responding to the file-changed event caused by touching files in the currently-watched directory, and

2. Requesting a new URL be viewed in the Viewer pane.

It looks like, in some cases, these two events can get interleaved in an unexpected order, causing RStudio to think the "current" viewer URL is the "old" viewer URL. Because it doesn't recognize the "current" viewer URL, it chooses to open that URL in an external browser rather than the RStudio viewer.

RStudio checks for viewer URLs here: https://github.com/rstudio/rstudio/blob/ea3c518b0eb1f60327f8504f12dff8e95767755f/src/cpp/desktop/DesktopWebPage.cpp#L436-L442

So my guess is that, in some cases, the Viewer URL as known by the RStudio backend is becoming out-of-sync with what is actually displayed in the Viewer pane.

**Comment by yihui** [comment] 2020-06-10 02:10
@kevinushey Thanks for the investigation and explanation! I have made sure that users cannot start multiple local web servers in the case of **blogdown**, so it is no longer an issue to **blogdown** users.

**Comment by mikebessuille** [comment] 2022-06-13 18:32
hopefully this won't be a problem with electron version.  No action's been taken on this so closing this for now.  See also #11252

**Closed by mikebessuille** 2022-06-13 18:32 UTC
Labels: bug, windows, backlog
