### ISSUE TITLE
If the YAML header in an Rmd file is not at the beginning of the file, the completion and syntax highlighting might not work.

### ISSUE THREAD

**Issue by ujtwr** [rstudio/rstudio#14945] opened 2024-07-09 01:11 UTC
Although the YAML header in an Rmd file can be located anywhere in the document and even be split into multiple parts, it will be integrated and processed during rendering. However, if the YAML header does not start from the first line of the document, code highlighting and completion will not work in that YAML header section.

In cases where you want to reflect the execution results of code chunks in the YAML header, you might place a separated YAML header in the middle of the document. Editing such YAML headers can be problematic in these cases.

### System details

    RStudio Edition : Server
    RStudio Version : 2024.04.2 Build 764
    OS Version      :  Ubuntu Linux 22.04 (Server) & Chrome (Windows)
    R Version       :  4.4.1

### Steps to reproduce the problem

1. Create New Rmd file.
1. Add something like Text or code chunk above YMLA header, or Add another YAML header anywhere in the document.

### Describe the problem in detail

Except for YAML header blocks starting from the first line of the document, code highlighting and completion won't work.

![image](https://github.com/rstudio/rstudio/assets/42717412/dfe75e37-cb74-403c-9d7d-db445908e4c1)

![image](https://github.com/rstudio/rstudio/assets/42717412/c05ec13a-958d-4ef6-a737-e57e41a46592)

### Describe the behavior you expected

Regardless of where it is located or how many parts it's divided into, YAML headers are highlighted and autocompleted in all blocks.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-07-12 10:51
@ujtwr Thank you for raising the issue! I can reproduce this as early as RStudio Desktop 2022.12.0+353, so it looks like this has been the case for a while, if not from the start. I'll mark this for review.

**Comment by jthomasmock** [comment] 2024-07-31 21:08
Hi @ujtwr -- thank you for the feature request here!

Per the RMarkdown user guide: https://arc.net/l/quote/judzgsdp

> The YAML metadata (also called the YAML header) ... is placed at the **very beginning of the document** 

YAML frontmatter should be placed at the front/top of the document for RMarkdown and [Quarto](https://quarto.org/docs/authoring/front-matter.html) and other [tooling](https://docs.github.com/en/contributing/writing-for-github-docs/using-yaml-frontmatter)

We also are unlikely to modify the highlighting of YAML later in the document as there's a good risk that this could introduce a regression for people documenting YAML options for example.

I'm going to close this one as not planned, but again I appreciate you taking the time to open this request and look forward to future request!

**Closed by jthomasmock** 2024-07-31 21:08 UTC
Labels: bug, r markdown
