### ISSUE TITLE
Saving a new untitled file over an existing Untitled.R renders the IDE unusable on Catalina

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#5999] opened 2020-01-10 22:35 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.900 through 1.3.730
    OS Version      : MacOS 10.15.2 and 10.15.3 beta (Catalina)
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Remove the file "Untitled.R", if it exists.
2. Create a new file in RStudio Desktop.
3. Put anything in it, even just the letter “x”.
4. Save it, keeping the name “Untitled.R”.
5. Close the file.
6. Create a new file in RStudio Desktop.
7. Put anything it, such as the letter “y”.
8. Save it, keeping the name “Untitled.R”.
9. Agree to replace the file.

### Describe the behavior you expected

The new file is saved with the name "Untitled.R" and RStudio continues to run normally.

### Describe the problem in detail

The mouse looks like a little hand and nothing works—clicking on anything does nothing, and the only way to exit is with Force Quit. The file is not overwritten with the new content. This only happens with “Untitled.R”, and only if it the file already exists. The permissions of the existing file aren't an issue, even with `chmod 777`. 

This works fine on MacOS 10.14.6 Mojave. On Catalina, this works fine in RStudio Desktop 1.1.463. Also, it was previously working on Catalina—perhaps only in 10.15.1? I'm not sure. Finally, if the existing Untitled.R file is open, it can be modified and saved with no issues.

Diagnostics report, run from the command line while the RStudio Desktop was unusable:
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4048330/diagnostics-report.txt)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2020-04-22 20:00
I could not reproduce this, even on the same macOS. :-/

**Comment by kevinushey** [comment] 2020-04-22 21:14
Was also unable to repro.

**Comment by xihaoli** [comment] 2020-06-14 21:51
Same issue here. Could someone please fix this issue? Thanks.

**Comment by gtritchie** [comment] 2020-06-15 19:08
I just repro'd this with RStudio Desktop v1.3.1019 on macOS 10.15.5. Everything inside the main window was frozen and unresponsive. Had to force-kill.

Second attempt didn't repro the issue. Third attempt did. Possibly either sheer timing, or some differences in where I used mouse vs. keyboard?

**Comment by gtritchie** [comment] 2020-06-15 19:11
I was able to repro with RStudio 1.2.5042, so not a recent regression.

**Comment by kevinushey** [comment] 2020-06-15 19:24
> I just repro'd this with RStudio Desktop v1.3.1019 on macOS 10.15.5. Everything inside the main window was frozen and unresponsive. Had to force-kill.

Can you also try attaching the Instruments Time Profiler to see if we can get a useful stacktrace of what's going on when this aoccurs?

**Comment by gtritchie** [comment] 2020-06-16 17:47
If I ever get it to happen again... Now I can't repro after many attempts. :-(

**Comment by ronblum** [comment] 2020-06-18 13:28
@kevinushey and @gtritchie I can reproduce this 100% of the time. I don't know how to use Time Profiler, though.

**Comment by gtritchie** [comment] 2020-06-18 15:45
@ronblum Can you document precise details of repro steps? Maybe make it more obvious what I was doing differently between repro and non-repro.

**Comment by ronblum** [comment] 2020-09-18 13:29
@gtritchie Shoot, sorry I missed this. 
To reproduce
1. In RStudio Desktop, create a new R script file.
2. Enter some text in the source editor.
3. Go to the "Save file" dialog.
    - The default filename will be "Untitled.R"
4. Click on "Save".
    - The file will be saved properly as "Untitled.R", and the dialog will close
5. Create a new R script file.
6. Enter some text in the source editor, different from the previous file.
7. Go to the "Save file" dialog.
    - The default filename will be "Untitled.R"
8. Click on "Save"
    - The file will appear to be saved properly as "Untitled.R", and the dialog will close.
   - However, the original file will not be overwritten or updated—the previous contents remain.
   - The IDE will not become unusable, and the only way to quit it is with Force Quit.

This is no longer an issue in MacOS 11 beta Big Sur, both for RStudio Desktop 1.3.1091 and 1.4.840. It appears to be a MacOS 10.15.6 Catalina issue.

**Comment by mine-cetinkaya-rundel** [comment] 2020-11-18 22:38
I'm seeing the same thing with `Untitled.Rmd` as well. Details below:

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1043
    OS Version      : macOS Catalina 10.15.7
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open a new R Markdown document with File > New File... > R Markdown, then hit OK to create an Rmd
2. Knit the Rmd, which will prompt the Save File dialogue. Save it as `Untitled.Rmd`. This should knit just fine.
3. Repeat Step 1.
4. Repeat Step 2, and in the Save File dialogue click Replace. Document doesn't knit and RStudio freezes.

**Comment by ronblum** [comment] 2021-02-17 17:13
This works on Big Sur, spec. MacOS 11.1 and 11.3. However, it is still an issue in Catalina, spec. MacOS 10.15.7, as of RStudio Desktop 1.4.1106. Although it works in Big Sur, I suggest we consider this, since Catalina is supported.

**Comment by mikebessuille** [comment] 2021-12-10 19:26
Very specific use case (saving untitled.R over top of an existing one), on a specific older version of MacOS.  I'm inclined to close this issue.

**Comment by ronblum** [comment] 2021-12-10 19:51
Agreed. It was only on Catalina, and in the past two years we've gotten Big Sur and Monterey.

**Comment by mikebessuille** [comment] 2021-12-10 20:09
Closing per above.

**Closed by mikebessuille** 2021-12-10 20:09 UTC
Labels: bug
