### ISSUE TITLE
Dragging corner visible on plot copied to clipboard

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#3353] opened 2018-08-22 05:13 UTC
Hello, 

Please find below the description of an issue with the `Copy to Clipboard...` function.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.915
    OS Version      : Ubuntu 18.04
    R Version       : 3.51

### Steps to reproduce the problem

    plot(1,1)

Then go to `Plots` pane --> `Export` --> `Copy to Clipboard...`. I choose to save a 401x401 image.

### Describe the problem in detail

On the copied plot, the dragging corner (i.e. bottom right corner) is visible on the resulting bitmap:

![bitmap](https://user-images.githubusercontent.com/6613954/44443785-7eb2bd80-a614-11e8-9ee9-22d6074981b7.png)

### Describe the behavior you expected
No dragging corner on the bitmap.

**Comment by ronblum** [comment] 2018-08-22 14:34
Confirmed on Ubuntu 18.04 and Windows 10, though not on MacOS 10.14 Mojave.

**Comment by kevinushey** [comment] 2018-08-23 23:53
Thanks for the bug report! Should be fixed with https://github.com/rstudio/rstudio/commit/cf68e58e63292be01c14c1a8144fdffac2c242f8.

**Comment by pascaloettli** [comment] 2018-08-30 02:12
Bug still exists in version `1.2.937`

**Comment by jmcphers** [comment] 2018-09-04 21:37
I think this is fallout from the Qt change, and needs to be addressed in 1.2.

**Comment by kevinushey** [comment] 2018-09-04 21:48
I'm not able to reproduce in the latest daily builds (v1.2.954). @pascaloettli can you provide any more information?

**Comment by pascaloettli** [comment] 2018-09-05 01:26
@kevinushey  I tried with v1.2.954 and I continue to have the gripper on the bottom right corner, as well as the left and top border. The size of the plot doesn't have any impact on this.
I use Qt5 provided by Xenial, i.e. 5.9.5. But if I run `ldd /usr/bin/rstudio`, the first line says 

> /usr/bin/rstudio: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr/bin/rstudio)

This is probably the culprit. Sorry for the inconvenience.

For reference, here is the complete output of `ldd`

> /usr/bin/rstudio: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr/bin/rstudio)
> 	linux-vdso.so.1 (0x00007ffc26161000)
> 	libQt5WebEngineWidgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5 (0x00007f9356d91000)
> 	libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007f9356b22000)
> 	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f9356898000)
> 	libQt5WebEngineCore.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5 (0x00007f93503c5000)
> 	libQt5WebChannel.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5 (0x00007f93501a7000)
> 	libQt5Positioning.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5 (0x00007f934ff49000)
> 	libQt5Quick.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5 (0x00007f934f900000)
> 	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f934f574000)
> 	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f934ed2d000)
> 	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f934e5c4000)
> 	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f934de79000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f934dc5a000)
> 	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f934da57000)
> 	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f934d850000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f934d648000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f934d42b000)
> 	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f934d1c3000)
> 	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f934cd80000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f934c9f2000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f934c654000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f934c43c000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f934c04b000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f9357831000)
> 	libQt5QuickWidgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5 (0x00007f934be39000)
> 	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f934bbec000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f934b9e8000)
> 	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f934b6d2000)
> 	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f934b31b000)
> 	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f934ae7a000)
> 	libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007f934ab36000)
> 	libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007f934a907000)
> 	libsmime3.so => /usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007f934a6db000)
> 	libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007f934a49e000)
> 	libevent-2.1.so.6 => /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6 (0x00007f934a24d000)
> 	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f9349f15000)
> 	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f9349d13000)
> 	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f9349aeb000)
> 	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f93498e8000)
> 	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f93496de000)
> 	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f93494db000)
> 	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f93492c9000)
> 	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f93490c3000)
> 	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f9348eb3000)
> 	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f9348ca9000)
> 	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f9348aa3000)
> 	libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1 (0x00007f934889f000)
> 	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f934865a000)
> 	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f93483a6000)
> 	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f9348174000)
> 	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f9347ed6000)
> 	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f9347ca4000)
> 	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f9347a3c000)
> 	libre2.so.4 => /usr/lib/x86_64-linux-gnu/libre2.so.4 (0x00007f93477b5000)
> 	libavcodec.so.57 => /usr/lib/x86_64-linux-gnu/libavcodec.so.57 (0x00007f9346095000)
> 	libavformat.so.57 => /usr/lib/x86_64-linux-gnu/libavformat.so.57 (0x00007f9345c3e000)
> 	libavutil.so.55 => /usr/lib/x86_64-linux-gnu/libavutil.so.55 (0x00007f93459b1000)
> 	libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f9345767000)
> 	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f9345461000)
> 	libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f9345259000)
> 	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f9344e98000)
> 	libminizip.so.1 => /usr/lib/x86_64-linux-gnu/libminizip.so.1 (0x00007f9344c8d000)
> 	libwebpdemux.so.2 => /usr/lib/x86_64-linux-gnu/libwebpdemux.so.2 (0x00007f9344a88000)
> 	libwebp.so.6 => /usr/lib/x86_64-linux-gnu/libwebp.so.6 (0x00007f934481f000)
> 	libxslt.so.1 => /usr/lib/x86_64-linux-gnu/libxslt.so.1 (0x00007f93445e2000)
> 	liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007f934438a000)
> 	libQt5Qml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (0x00007f9343d8d000)
> 	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f9343a41000)
> 	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007f9343830000)
> 	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f93435ac000)
> 	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f934333a000)
> 	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f9341791000)
> 	libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007f934158c000)
> 	libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007f9341388000)
> 	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f9341184000)
> 	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f9340f7e000)
> 	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f9340d51000)
> 	libswresample.so.2 => /usr/lib/x86_64-linux-gnu/libswresample.so.2 (0x00007f9340b32000)
> 	libcrystalhd.so.3 => /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3 (0x00007f9340917000)
> 	libva.so.2 => /usr/lib/x86_64-linux-gnu/libva.so.2 (0x00007f93406f6000)
> 	libzvbi.so.0 => /usr/lib/x86_64-linux-gnu/libzvbi.so.0 (0x00007f934046b000)
> 	libxvidcore.so.4 => /usr/lib/x86_64-linux-gnu/libxvidcore.so.4 (0x00007f934015a000)
> 	libx265.so.146 => /usr/lib/x86_64-linux-gnu/libx265.so.146 (0x00007f933f4d9000)
> 	libx264.so.152 => /usr/lib/x86_64-linux-gnu/libx264.so.152 (0x00007f933f134000)
> 	libwebpmux.so.3 => /usr/lib/x86_64-linux-gnu/libwebpmux.so.3 (0x00007f933ef2a000)
> 	libwavpack.so.1 => /usr/lib/x86_64-linux-gnu/libwavpack.so.1 (0x00007f933ed00000)
> 	libvpx.so.5 => /usr/lib/x86_64-linux-gnu/libvpx.so.5 (0x00007f933e8b1000)
> 	libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f933e608000)
> 	libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f933e3dd000)
> 	libtwolame.so.0 => /usr/lib/x86_64-linux-gnu/libtwolame.so.0 (0x00007f933e1ba000)
> 	libtheoraenc.so.1 => /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1 (0x00007f933df7b000)
> 	libtheoradec.so.1 => /usr/lib/x86_64-linux-gnu/libtheoradec.so.1 (0x00007f933dd5d000)
> 	libspeex.so.1 => /usr/lib/x86_64-linux-gnu/libspeex.so.1 (0x00007f933db43000)
> 	libshine.so.3 => /usr/lib/x86_64-linux-gnu/libshine.so.3 (0x00007f933d938000)
> 	librsvg-2.so.2 => /usr/lib/x86_64-linux-gnu/librsvg-2.so.2 (0x00007f933d700000)
> 	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f933d4ac000)
> 	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f933d18f000)
> 	libopenjp2.so.7 => /usr/lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f933cf39000)
> 	libmp3lame.so.0 => /usr/lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007f933ccc2000)
> 	libgsm.so.1 => /usr/lib/x86_64-linux-gnu/libgsm.so.1 (0x00007f933cab5000)
> 	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f933c88f000)
> 	libssh-gcrypt.so.4 => /usr/lib/x86_64-linux-gnu/libssh-gcrypt.so.4 (0x00007f933c61c000)
> 	libopenmpt.so.0 => /usr/lib/x86_64-linux-gnu/libopenmpt.so.0 (0x00007f933c254000)
> 	libbluray.so.2 => /usr/lib/x86_64-linux-gnu/libbluray.so.2 (0x00007f933c004000)
> 	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f933bc9f000)
> 	libgme.so.0 => /usr/lib/x86_64-linux-gnu/libgme.so.0 (0x00007f933ba53000)
> 	libchromaprint.so.1 => /usr/lib/x86_64-linux-gnu/libchromaprint.so.1 (0x00007f933b840000)
> 	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f933b630000)
> 	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f933b41f000)
> 	libvdpau.so.1 => /usr/lib/x86_64-linux-gnu/libvdpau.so.1 (0x00007f933b21b000)
> 	libva-x11.so.2 => /usr/lib/x86_64-linux-gnu/libva-x11.so.2 (0x00007f933b015000)
> 	libva-drm.so.2 => /usr/lib/x86_64-linux-gnu/libva-drm.so.2 (0x00007f933ae12000)
> 	libnvidia-tls.so.340.107 => /usr/lib/x86_64-linux-gnu/tls/libnvidia-tls.so.340.107 (0x00007f933ac0f000)
> 	libnvidia-glcore.so.340.107 => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.340.107 (0x00007f9337ffb000)
> 	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f9337ddf000)
> 	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f9337ac4000)
> 	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f93378af000)
> 	libsoxr.so.0 => /usr/lib/x86_64-linux-gnu/libsoxr.so.0 (0x00007f933764c000)
> 	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f9337441000)
> 	libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f9337238000)
> 	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f9337014000)
> 	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f9336c76000)
> 	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f9336a69000)
> 	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f9336853000)
> 	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f9336606000)
> 	libcroco-0.6.so.3 => /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3 (0x00007f93363cb000)
> 	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f93361c3000)
> 	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f9335f1e000)
> 	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f9335d1b000)
> 	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f9335b0e000)
> 	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f93358c3000)
> 	libmpg123.so.0 => /usr/lib/x86_64-linux-gnu/libmpg123.so.0 (0x00007f9335664000)
> 	libvorbisfile.so.3 => /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 (0x00007f933545c000)
> 	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f933512d000)
> 	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f9334f10000)
> 	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f9334b92000)
> 	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f933497f000)
> 	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f9334749000)
> 	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f9334515000)
> 	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f9334294000)
> 	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f933407f000)
> 	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f9333e4f000)
> 	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f9333c4b000)
> 	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f9333a23000)
> 	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f9333808000)
> 	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f93335b4000)
> 	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f93333ab000)
> 	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f93330d5000)
> 	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f9332ea3000)
> 	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f9332c9f000)
> 	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f9332a94000)
> 	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f9332847000)
> 	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f9332640000)
> 	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f933243c000)
>

**Comment by jmcphers** [comment] 2018-09-05 17:11
Do you still see the issue when you use RStudio's bundled version of Qt?

**Comment by pascaloettli** [comment] 2018-09-06 03:58
I still have issue when using RStudio's bundled version of Qt. If I am the only one facing this issue, we could close it.

**Comment by pascaloettli** [comment] 2018-09-19 01:28
If I want to be able to copy a plot to the clipboard, I have to use version `1.1.456 `. But this version doesn't allow me to use [Japanese input](https://github.com/rstudio/rstudio/issues/3015).

**Comment by kevinushey** [comment] 2018-09-19 03:54
Something else you could try is a plain old right click -> copy image to copy the plot to the clipboard.

**Comment by pascaloettli** [comment] 2018-09-19 07:43
@kevinushey This one works. Thank you

**Closed** 2018-09-26 00:32 UTC
Labels: bug, regression

**Comment by sergionemirovsky** [comment] 2019-05-06 13:08
have the same bug in version 1.2.1335 (Build 4 (f1ac3452)) for Ubuntu 18.04.
![image](https://user-images.githubusercontent.com/50327890/57227094-ee23de00-6fe6-11e9-948b-ef6f0a64751d.png)

**Comment by kevinushey** [comment] 2019-05-20 17:02
@sergionemirovsky can you please open a new issue?
