### ISSUE TITLE
Ctrl-Shift-2 does not maximize console pane

### ISSUE THREAD

**Issue by Peder2911** [rstudio/rstudio#3915] opened 2018-11-16 10:22 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1114
    OS Version      :  Ubuntu 18.04
    R Version       :  3.4.4

### Steps to reproduce the problem
Attempt to maximize console pane by pressing ctrl-shift-2.
Nothing happens, but i can get a maximized view by first maximizing code editor with ctrl-shift-1, and then switching to two.

### Describe the behavior you expected
Maximized console pane.

**Comment by pascaloettli** [comment] 2018-11-16 10:39
I cannot reproduce (`Desktop` edition, version `1.2.1124`, Ubuntu `18.04`, R `3.5.1`)

**Comment by Peder2911** [comment] 2018-11-19 11:30
I was able to reproduce on:
R 3.5
Rstudio 1.2.111
MacOs 10.13 High Sierra

I am using a custom theme, https://github.com/randy3k/dotfiles/blob/master/.R/rstudio/themes/Wombat.rstheme. Could this be causing the problem?

**Comment by pascaloettli** [comment] 2018-11-20 01:36
Still cannot reproduce. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd> works on:

    RStudio Edition : Desktop
    RStudio Version : 1.2.1143
    OS Version      : Ubuntu 18.04
    R Version       : 3.5.1
    Theme           : Wombat (https://github.com/randy3k/dotfiles/blob/master/.R/rstudio/themes/Wombat.rstheme)

    RStudio Edition : Desktop
    RStudio Version : 1.2.1114
    OS Version      : MacOS 10.14.1 Mojave
    R Version       : 3.5.1
    Theme           : Wombat (https://github.com/randy3k/dotfiles/blob/master/.R/rstudio/themes/Wombat.rstheme)

**Comment by Peder2911** [comment] 2018-11-20 14:49
`Ctrl` + `Shift` + `1` also works for me, but not `Ctrl` + `Shift` + `2`.

**Comment by kevinushey** [comment] 2018-11-20 16:39
Is it possible that you have some OS-level binding for <kbd>Ctrl+Shift+2</kbd> that is taking precedence over RStudio's attempt to handle the keys?

**Comment by pascaloettli** [comment] 2018-11-21 00:08
Sorry, I wanted to say <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>2</kbd>

**Comment by Peder2911** [comment] 2018-11-23 10:10
That would be weird considering i tried this on two separate OS-es. I'll check.
I am using a Norwegian keyboard on both systems, could that be causing it?

**Comment by kevinushey** [comment] 2018-11-26 17:56
Ahhh, that seems likely. What do you see when you press Ctrl + Shift + 2 in e.g. https://keycode.info/? For example, I see:

![screen shot 2018-11-26 at 9 55 55 am](https://user-images.githubusercontent.com/1976582/49032472-7c0abb80-f161-11e8-8f02-68c86d205c49.png)

**Comment by Peder2911** [comment] 2018-11-26 19:50
I see this:
<img width="647" alt="screen shot 2018-11-26 at 20 49 38" src="https://user-images.githubusercontent.com/31591780/49038320-e866d880-f1bc-11e8-89d3-56bd88f12c22.png">

**Comment by kevinushey** [comment] 2018-11-26 21:20
That's surprising (I would've expected them to be different key codes in this case). Although it's possible that this is an RStudio-only issue. We'll have to dig in a bit more...

Just to confirm, if you temporarily switch to a US keyboard layout, do the keybindings work?

**Comment by Peder2911** [comment] 2018-11-29 10:14
Aha! Yes, they do. If i change to a US keyboard layout the bindings work as expected. This seems to be a problem related to the keyboard layout.

**Comment by jmcphers** [comment] 2019-12-04 20:27
We've had no other reports of this in > 1 year so closing. @Peder2911 Sorry if this still repros for you. :-/

**Closed** 2019-12-16 18:56 UTC
Labels: bug, repro needed

**Comment by CarloAlfred** [comment] 2022-03-18 21:22
I have the same problem (with a Danish keyboard). I think that there is a usable (stupid!) solution:

Go to Tools -> Modify Keyboard Shortcuts.
Find "Zoom Console".
Click the shortcut.
Press Ctrl+Shift+2.
Then I get Ctrl+Shift+' as the shortcut, but this is OK since it now works when I press Ctrl+Shift+2. (The 2 must be interpreted as ' - but that does not matter!)

**Comment by pulplyrics** [comment] 2022-05-19 19:23
Carlo Alfred's suggestion fixed the issue for me! (UK keyboard layout)

**Comment by juju-bowow** [comment] 2022-08-24 13:20
> Carlo Alfred's suggestion fixed the issue for me! (UK keyboard layout)

This suggestion also fixed the issue for me on UK keyboard layout 👍 Thank you @CarloAlfred and @pulplyrics 🙏
Before this fix, pressing the shortcut would simply print a '2' in the console.

(R 4.2.1 | RStudio 2022.07.1 Build 554 | Windows 10 Build 19044.1889)
