### ISSUE TITLE
Inconsistent Rmarkdown chunk background shading

### ISSUE THREAD

**Issue by lboller** [rstudio/rstudio#2992] opened 2018-06-12 21:34 UTC
RStudio appears to incorrectly shade the background of Rmarkdown chunks at times, i.e. the shading extends into markdown areas or does not appear inside of parts of a code chunk. This typically appears when sections of code are folded, as shown in the image below. The behavior is inconsistent, therefore I am having trouble coming up with a reproducible example.

![image](https://user-images.githubusercontent.com/1630748/41318458-5dc867fe-6e66-11e8-9c90-e9a286b83b17.png)

**Comment by jmcphers** [comment] 2019-11-19 21:33
We haven't seen this in over a year. Has anyone found a reproducible example with recent builds of RStudio? (1.2.5019 or newer)

**Comment by lboller** [comment] 2019-11-19 22:13
Still happens to me regularly. I see it on the daily build that I am running (1.3.476).

Having trouble coming up with a reproducible example. One type of behavior that seems reproducible is that folded headers are shaded grey if the section contains code chunks. Not sure if this behavior is intended or not. 

![image](https://user-images.githubusercontent.com/1630748/69191051-b5190a00-0aef-11ea-9898-8f98e6c944ad.png)

![image](https://user-images.githubusercontent.com/1630748/69191064-bcd8ae80-0aef-11ea-94f8-503cfce056af.png)

I often see that shading in other chunks is mis-aligned, again usually happens when folding code.

![image](https://user-images.githubusercontent.com/1630748/69191144-ea255c80-0aef-11ea-97d5-b0c3fddbaf02.png)

**Comment by lboller** [comment] 2019-11-19 22:16
Note that the correct shading is restored once I start typing in the incorrectly shaded regions.

![image](https://user-images.githubusercontent.com/1630748/69191361-543e0180-0af0-11ea-8d73-ab51938d505d.png)

**Comment by kevinushey** [comment] 2019-11-19 22:26
I can reproduce the shading on the header line -- it occurs when attempting to folder a header that contains a chunk. However, I cannot reproduce the mis-aligned background highlight issue.

Any chance you're able to find a way to reproduce the behavior?

**Comment by kevinushey** [comment] 2019-11-19 22:31
It looks like this is a reproducible example for the misaligned background highlight. Using the following document:

`````

# Header 1

```{r}

```

# Header 2

Prose

```{r}

```
`````

Try the following steps:

1. Create a fold on the `# Header 2` line.
2. Delete the chunk boundary for the first chunk.
3. Unfold the fold for `# Header 2`.

The chunk highlight at this point will be inconsistent.

![Screen Shot 2019-11-19 at 2 30 06 PM](https://user-images.githubusercontent.com/1976582/69192266-18e40880-0ad9-11ea-907d-5d9755bf4a24.png)

This works as expected in v1.1, but not v1.2, so it's a recent regression.

**Comment by kevinushey** [comment] 2019-12-03 16:23
Note to self: https://github.com/rstudio/rstudio/blob/933801d7558baef7fcc4ceae71fb066c74cb505f/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java#L111-L116

**Closed** 2020-02-04 22:12 UTC
Labels: ace, bug, reproducible

**Comment by dfalty** [comment] 2020-02-25 19:48
Verified 1.3.867
