### ISSUE TITLE
RStudio 1.2.5001 points to wrong version of R

### ISSUE THREAD

**Issue by tobiasgerstenberg** [rstudio/rstudio#5442] opened 2019-09-20 18:28 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001
    OS Version      : macOS Mojave 10.14.6
    R Version       : 3.6.1 (2019-07-05) -- "Action of the Toes"

### Steps to reproduce the problem

Load any library in RStudio 1.2.5001.

### Describe the problem in detail

After upgrading to RStudio Version 1.2.5001 (from 1.2.1335-1), RStudio now points to the wrong version of R (3.5 instead of 3.6).

```
library("tidyverse")

Error: package or namespace load failed for ‘tidyverse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/glue/libs/glue.so':
  dlopen(/usr/local/lib/R/site-library/glue/libs/glue.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib
  Referenced from: /usr/local/lib/R/site-library/glue/libs/glue.so
  Reason: image not found
```

Note how RStudio points to `/Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib` instead of `/Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libR.dylib`. 

Running R in the terminal and loading packages still works fine, so does using an older version of RStudio (1.1.463). RStudio 1.2.1335-1 worked fine as well, but I can't find that version online anymore to downgrade.

**Comment by ronblum** [comment] 2019-09-20 20:54
@tobiasgerstenberg Thank you for raising this. It's a duplicate of #5238, which had been closed and verified, but it appears to still be an issue, which I'll reopen.

In the meantime, you can [download 1.2.1335 here](https://download1.rstudio.org/desktop/macos/RStudio-1.2.1335.dmg).

**Closed by ronblum** 2019-09-20 20:54 UTC

**Comment by kevinushey** [comment] 2019-09-21 02:40
What is the output of:

```
otool -L /usr/local/lib/R/site-library/glue/libs/glue.so
```

when run in a terminal? I suspect the issue here is the mixture of libraries built for R 3.5 (in a Homebrew installation?) versus your current R version.

**Comment by tobiasgerstenberg** [comment] 2019-09-22 23:31
this is the output of running this command: 

```
usr/local/lib/R/site-library/glue/libs/glue.so:
	glue.so (compatibility version 0.0.0, current version 0.0.0)
	/Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib (compatibility version 3.5.0, current version 3.5.2)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1560.12.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

**Comment by kevinushey** [comment] 2019-09-23 17:25
> 	/Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib (compatibility version 3.5.0, current version 3.5.2)

It looks like you're trying to use packages compiled for R 3.5 in your R 3.6 session. You'll need to resolve your library paths and figure out what's going on.

**Comment by tobiasgerstenberg** [comment] 2019-09-23 18:46
I've set my library path in `~/.Renviron` as 

```
R_LIBS=/usr/local/lib/R/site-library
```

with past versions of RStudio, it wasn't a problem if packages were compiled under different versions of R.

**Comment by kevinushey** [comment] 2019-09-23 20:55
I'm surprised that this worked -- I think you ultimately got lucky. I wouldn't recommend using a single library path across different versions of R.

**Comment by tobiasgerstenberg** [comment] 2019-09-23 20:59
ok, sounds good. i'll reinstall all packages under 3.6 then. thanks for your help!

**Comment by tobiasgerstenberg** [comment] 2019-09-24 21:36
reinstalling all packages resolved the issue.

**Comment by kevinushey** [comment] 2019-09-24 21:42
Glad to hear it! Sorry for the trouble and frustration, but our hands are tied based on changes Apple is making regarding requirements for notarized software.

**Comment by tobiasgerstenberg** [comment] 2019-09-24 21:44
no worries -- thanks for your help!
