### ISSUE TITLE
Empty Rmd file freezes RStudio 1.4 in Bookdown project

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#8453] opened 2020-11-22 18:09 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1048
    OS Version      : Windows 10
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Create a new `Bookdown` project.
2. Create a new empty Rmd document.
3. Save empty Rmd document in a project as, e.g., `00--empty-file.Rmd`
4. Try to close RStudio (it hangs until you try to close it again).
5. Try to open this project (sometimes some pales do not load, the expressions are not evaluated in the Console, and there are problems to close the project/exit RStudio).

I add the project in which the problem reproduces on my PC:
[bookdown-demo-proj.zip](https://github.com/rstudio/rstudio/files/5579973/bookdown-demo-proj.zip)

### Describe the problem in detail

After **step 4**, RStudio hangs in this state:
![01--rs-hangs-on-trying-to-close](https://user-images.githubusercontent.com/12725868/99911374-94842100-2cfc-11eb-89ae-33af8e3eddf9.gif)
Until this button is clicked again:
![image](https://user-images.githubusercontent.com/12725868/99911386-a9f94b00-2cfc-11eb-8702-e320e84f3d07.png)

The issues after performing **step 5** are illustrated below (I began to record the screen about 20 seconds after opening the project).
As you can see, some panes do not initialize, mathematical calculations are not evaluated in the console.
The green bar below is a time line:
![02-rs-hangs-after-restart](https://user-images.githubusercontent.com/12725868/99911415-ec228c80-2cfc-11eb-98d0-3b1eb179785f.gif)

### Describe the behavior you expected

I expect RStudio to work without freezing when empty Rmd files are present in an RStudio project.

I used only an empty Rmd file, but other situations should be tested too. E.g., no freezing should be present with:

- Empty files with other extensions.
- Rmd files that have no headings (that start with `#`) in the text.
- other non-bookdown projects.

*** 
- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment] 2020-11-23 20:07
@GegznaV, thanks for finding and reporting this.

This is a pretty odd issue. I'm able to reproduce this on the latest daily build (1.4.1060) on Windows 10 using the steps you provided (I just did it with a new `bookdown` project rather than the zip provided to make sure it wasn't something project specific, but thank you for providing the project zip!). Seems specific to `bookdown` at the moment as I haven't been able to reproduce in other project types (I also have not tried ALL project types).

The only note I'll add is that after this issue occurs, when the IDE is re-launched I'm seeing variable behavior: Most common is what you outlined, IDE attempts to re-open with the project open and panes don't load, console is blank, environment pane is spinning, etc. After closing/re-launching the IDE again, the IDE opens normally without the project open. I've also seen it (less commonly) open successfully on the 1st relaunch.

**Comment by R-Hannibal** [comment] 2020-11-23 20:49
I am NOT able to reproduce this on `1.3.1093`, so it looks like it is in fact a regression.

**Comment by mikebessuille** [comment] 2020-11-23 21:40
Kevin, could you please look at this, since it's a regression?  If it's a risky fix we should move it out of 1.4, because there is a clear workaround and no data loss, and will only happen in specific edge-case circumstances.  But as a regression we should consider it for 1.4 if there's an obvious and low-risk fix.

**Comment by kevinushey** [comment] 2020-11-23 22:13
Thanks for the bug report! I've reproduced this on macOS and will take a look.

**Closed** 2020-11-23 22:30 UTC
Labels: backlog, bug, regression, reproducible

**Comment by melissa-barca** [comment] 2020-11-24 17:35
Verified in 1.4.1063
