### ISSUE TITLE
Some (useful!) buttons not working in RStudio 1.2.x under ubuntu 18.04 using gnome

### ISSUE THREAD

**Issue by sjcowtan** [rstudio/rstudio#5067] opened 2019-07-04 19:34 UTC
Hi there,

I installed the latest stable rstudio desktop on a machine running ubuntu 18.04, gnome, and R3.4.4 with current versions of the packages for knitr and dependencies. Some of the buttons and down arrows on the toolbars are working, but some are not responding in any way to the mouse. For example, specific to knitr, the insert chunk, properties and run buttons on the knitr toolbar don't work but compile does (the same functions are fine from the top menu bar). Outside of knitr, the list dropdown in the environment pane doesn't work either, and some other things, which I forget, because I am now on a different machine. This behaviour is both odd and undesirable :slight_smile:

**Comment by ronblum** [comment] 2019-07-10 15:37
@sjcowtan Thank you for filing this—I agree, it's undesirable. I'm unable to reproduce the issue, though, with the same configuration. What version of Gnome are you using?

**Comment by sjcowtan** [comment] 2019-07-15 14:40
GNOME 3.28

**Comment by jmcphers** [comment] 2019-11-12 19:30
We haven't had any other reports of this and haven't been able to reproduce for several months, so closing. @sjcowtan If you're seeing it, feel free to reopen, but please tell us more about your RStudio version and share some screenshots so we can see what's going on.

**Closed by jmcphers** 2019-11-12 19:30 UTC
Labels: repro needed
