### ISSUE TITLE
Alt Gr key (ISO Level 3 Shift) interpreted as Left key

### ISSUE THREAD

**Issue by sdittmar** [rstudio/rstudio#5130] opened 2019-07-20 08:26 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Linux Debian 9
    R Version       : 3.5.2

### Steps to reproduce the problem
Push Alt Gr Key.

### Describe the problem in detail
When I push the Alt Gr key on a German keyboard, the cursor moves one place to the left. That is particularly painful since the Alt Gr key is needed on a German keyboard to type curly brackets. The effect only occurs in R-Studio and not in any other programs every since I upgraded to v1.2.1335 a few days ago. Interestingly, the functional effect of the Alt Gr key remains in place. That means if I move one character to the right from where I want to insert a curly bracket, I can use the normal combination of Alt Gr and the 7 key to insert a curly bracket in the correct position after the cursor moved one position to the left in the same process.

I checked Linux and R-Studio keyboard shortcuts to see if something there might cause any problems (I don't usually use these functionalities), but there is nothing defined for the relevant key. In fact, if I try to set up a keyboard shortcut in R-Studio and push the Alt Gr key, the shortcut reads "Left".

This is the /etc/default/keyboard file I am using:

XKBMODEL="pc105"
XKBLAYOUT="de"
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"

### Describe the behavior you expected

Cursor does not move when I push the ISO level 3 shift key (Alt Gr).

**Comment by ronblum** [comment] 2019-07-22 16:37
@sdittmar Thank you for raising the issue and the helpful description. This appears to be a duplicate of #4584. I'll add your information to it. If you feel this is not a duplicate, please let us know. Thanks!

**Closed by ronblum** 2019-07-22 16:37 UTC
