### ISSUE TITLE
Rstudio dataframe viewer does not retain the filtered rows after expanding column more than 50.

### ISSUE THREAD

**Issue by vinaychuri** [rstudio/rstudio#7534] opened 2020-08-06 03:35 UTC
### System details

 RStudio Edition : Desktop
RStudio Version : 1.3.1056
OS Version : Mac OS Catalina
R Version : 4.0

### Steps to reproduce the problem
1) View a dataframe with more than 50 columns
2) Filter for few rows either with the search glass option OR the Filter option within the dataframe viewer window.
3) Viewer will now show only filtered rows but only the first 50 columns.
4) Click on the small arrow icons to display the remaining columns i.e 51+ columns
5) The Viewer will now show columns from 51 onwards but the row filters are removed and all dataframe records are displayed. The filter input text fields is also removed.

### Describe the problem in detail
Rstudio data frame viewer does not retain the filtered rows after expanding columns more than 50 columns.

### Describe the behavior you expected
Once the user has set the filter criteria and filtered rows are displayed , the user should be allowed to column-scroll to view more columns on the filtered rows.
Also, the filter input text fields should continue to be displayed in case the user wants to add more filter criteria for other columns.

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-08-06 15:59
@vinaychuri Thank you for filing the issue! We'll review it as we continue development of RStudio.

Note: this is not a regression, as it goes back at least as far as 1.2.5040.

**Comment by iago-pssjd** [comment] 2020-09-08 16:24
I can reproduci it on Debian 9 with RStudio 1.3.1073.

I would like to add a consequence/side effect of this issue. If you want to filter on, let's say, the first column, one can only do it while vieweing the first 50 columns, but it is not possible to see any other columns filtered by the first one.

**Comment by francisbarton** [comment] 2020-09-23 22:02
Seems like a duplicate of #6147

**Comment by ronblum** [comment] 2020-09-24 14:25
That it is.

**Closed by ronblum** 2020-09-24 14:25 UTC
Labels: bug, data viewer, duplicate, reproducible
