### ISSUE TITLE
Encoding issue in notebook chunk output (attaching tidyverse packages)

### ISSUE THREAD

**Issue by iflow** [rstudio/rstudio#10789] opened 2022-03-15 21:00 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version : 2022.02.0 Build 443
    OS Version      :  Windows 10
    R Version       :  4.1.3

### Steps to reproduce the problem

1. Create a new markdown or notebook file
2. Insert a chunk code to load _tidyverse_, i.e. `if(!require(tidyverse)) install.packages("tidyverse"); library(tidyverse)`
3. Run the R chunk
4. Encoding issues appear in the chunk output

### Describe the problem in detail

Instead of the green check character, we get some strange characters, i.e.
`âˆš ggplot2 3.3.5`

![grafik](https://user-images.githubusercontent.com/232415/158470741-a92d81a2-788f-497d-aca7-a6ef95caf3f2.png)

This happens only in R-Studio in the code chunk output, but also in Console output.
It doesn't seem to be an issue of R or the package itself, because it works in other IDE and also in the R-GUI as expected.

The issue in R-Studio firstly appeared, after updating the R version from 4.1.2 to 4.1.3.
I also tried to reinstall R. I also updated all packages and R-Studio itself, without success.

**R-Studio settings:**

- Global options > Code > Saving > Default text encoding > UTF-8 (also tried switching the encoding several times)
- Appearance > Editor font > Lucida Console (also tried different fonts)

**Output of Sys.getlocale()**
```
> Sys.getlocale()
[1] "LC_COLLATE=German_Austria.1252;LC_CTYPE=German_Austria.1252;LC_MONETARY=German_Austria.1252;LC_NUMERIC=C;LC_TIME=German_Austria.1252"
```

### Describe the behavior you expected

There should be some kind of green check (v) character in front of the attached packages.

![grafik](https://user-images.githubusercontent.com/232415/158470982-39d62b78-f265-4b39-92e6-ae21ea5ae328.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-03-16 18:12
@iflow Thank you for raising this! I'm unable to reproduce it, though, using the same configuration.

@timtmok Do you have any suggestions of what else I might try to force the error?

**Comment by timtmok** [comment] 2022-03-17 15:37
@ronblum You might be able to reproduce it by selecting a different editor font in the Appearance options. It's likely that the selected font doesn't support the checkmark used in the output.

**Comment by kevinushey** [comment] 2022-03-17 20:39
The output of `Sys.getlocale()` might be useful as well, in case the active locale makes a difference here. (I notice that part of the message printed to the console is not in English.)

**Comment by kevinushey** [comment] 2022-03-17 20:47
I see this with RStudio 1.4.1717 as well, using the latest versions of tidyverse, and also with older versions of R. I suspect there was a change in either the tidyverse package (or one of its dependencies) that is causing this.

**Comment by kevinushey** [comment] 2022-03-17 20:48
It also seems like the text itself is UTF-8, but has incorrectly been marked as latin1 instead.

<img width="219" alt="Screen Shot 2022-03-17 at 1 47 53 PM" src="https://user-images.githubusercontent.com/1976582/158892540-45e2939a-8cc4-4297-94f2-55af51c9736a.png">

**Comment by iflow** [comment] 2022-03-18 07:41
I have updated the bug description, based on your comments.

My setup:
- R-Studio setting: _Global options > Code > Saving > Default text encoding > UTF-8_ (also tried switching the encoding several times)
- R-Studio setting: _Appearance > Editor font > Lucida Console_ (also tried different fonts)
- Sys.getlocale: `[1] "LC_COLLATE=German_Austria.1252;LC_CTYPE=German_Austria.1252;LC_MONETARY=German_Austria.1252;LC_NUMERIC=C;LC_TIME=German_Austria.1252"`
- The notebook file is actually UTF-8 - I checked it with a different editor: Notepad++
- The characters are only wrong in RStudio! If I load the tidyverse package in other editors, like R-GUI or Jetbrains Dataspell, the encoding seems to be correct.

**Comment by panporter** [comment] 2022-03-30 09:49
Same here.

```
sessioninfo::os_name()
#> [1] "Windows 10 x64 (build 19044)"
 
#RStudio.Version()$long_version
# [1] "2021.09.2+382"
 
version
#>                _                          
#> platform       x86_64-w64-mingw32         
#> arch           x86_64                      
#> os             mingw32                    
#> system         x86_64, mingw32            
#> status                                    
#> major          4                          
#> minor          1.2                        
#> year           2021                       
#> month          11                         
#> day            01                         
#> svn rev        81115                      
#> language       R                           
#> version.string R version 4.1.2 (2021-11-01)
#> nickname       Bird Hippie
getOption("encoding")
#> [1] "native.enc"
localeToCharset()
#> [1] "ISO8859-1"
Sys.getlocale()
#> [1] "LC_COLLATE=German_Germany.1252;LC_CTYPE=German_Germany.1252;LC_MONETARY=German_Germany.1252;LC_NUMERIC=C;LC_TIME=German_Germany.1252"
```
The problem might be more fundamental, the impact might be bigger.

Encoding problems arise elsewhere as well:

I might have falsely blamed R-DBI for a strange encoding problem that occurs only running chunks in RStudio but not while Knitting: https://github.com/r-dbi/odbc/issues/489

**Comment by kevinushey** [comment] 2022-03-30 21:52
This particular issue (with printing of checkmarks on loading tidyverse) seems to be a recent regression in the crayon package. You can try installing an older version with:

```
remotes::install_version("crayon", version = "1.4.2")
```

Then, restart R, and see if loading `tidyverse` prints checkmarks as expected.

**Comment by iflow** [comment] 2022-05-31 18:15
I recently updated from R 4.1.3 to R 4.2.0 and the issue disappeard. 

![grafik](https://user-images.githubusercontent.com/232415/171256490-1cb783cc-b45c-4758-889a-28b03c4d49d4.png)

**Comment by kevinushey** [comment] 2022-05-31 18:48
Thanks for confirming!

**Closed by kevinushey** 2022-05-31 18:48 UTC
Labels: bug, r versions
