### ISSUE TITLE
RStudio fails to open Sweave file

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rstudio#14777] opened 2024-06-03 13:12 UTC
### System details

    RStudio Edition : Desktop 
    RStudio Version : 2024.04.1+748 (2024.04.1+748)
    OS Version      :  MacOS Sonoma 14.5 on M3
    R Version       :  4.4.0

### Steps to reproduce the problem

Trying to open the vignette from my `tables` package that is currently here:  https://github.com/dmurdoch/tables/blob/d59c0b21f529417197ac2afd8798cbdda97cdea9/vignettes/tables.Rnw, or the subset of it shown below fails.

```
\documentclass[12pt]{article}

\usepackage{Sweave}

\usepackage[authoryear,round,comma]{natbib}
\bibliographystyle{plainnat}

%\VignetteIndexEntry{About the tables package}

\begin{document}


Example:  Use a custom function and \code{sprintf()} to display a standard error in parentheses.
\begin{center}
<<results=tex>>=
stderr <- function(x) sd(x)/sqrt(length(x))
fmt <- function(x, digits, ...) {
  s <- format(x, digits=digits, ...)
  is_stderr <- (1:length(s)) > length(s) %/% 2
  s[is_stderr] <- sprintf("$(%s)$", s[is_stderr])
  s[!is_stderr] <- latexNumeric(s[!is_stderr])
  s
}
toLatex( tabular( Format(fmt(digits=1))*(F+1) ~ X*(mean + stderr) ) )
@
\end{center}

\end{document}
```

A dialog box opens with the message `Error while opening file.  (TypeError) : Cannot read properties of undefined (reading 'count')`

### Describe the problem in detail

After some more experimentation, it seems the file needs to be named with a `.Rnw` extension; it is fine if I rename it to `.txt`.

I've tried removing more text; the problematic bit seems to be the function definition in the code chunk. I can open it when I remove things down to just this text:
```
\documentclass[12pt]{article}

\begin{document}

<<results=tex>>=
fmt <- function(x, digits, ...) 
  s[is_stderr] <- sprintf("$(%s)$", s[is_stderr])
  s[!is_stderr] <- latexNumeric(s[!is_stderr])
@

\end{document}
```
but RStudio seems unstable:  adding a brace `{` at the end of the `fmt <- function(x, digits, ...) ` line causes the whole line to disappear.

### Describe the behavior you expected

The file should be editable.  There's nothing particularly weird in the problematic bit.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2024-06-03 15:21
We've made some fixes around Sweave in an upcoming patch. We're still performing final testing, but if you want to give it a try and report back, this build is _probably_ going to be the next official release: https://s3.amazonaws.com/rstudio-ide-build/electron/macos/RStudio-2024.04.2-762.dmg

**Comment by gtritchie** [comment] 2024-06-03 15:27
I reproduced the problem with 2024.04.1+748 (current official release), but was able to successfully open the file with the release candidate for patch 2 (the one I linked to in my previous comment).

Closing as a duplicate of #14646.

**Closed by gtritchie** 2024-06-03 15:27 UTC
Labels: bug, new

**Comment by dmurdoch** [comment] 2024-06-03 15:57
Thanks, that does fix it.

**Comment by olivroy** [comment] 2024-06-03 16:44
@gtritchie is there plan to incorporate the latest quarto patch (1.4.555) to the RStudio patch?

**Comment by gtritchie** [comment] 2024-06-03 17:05
No, this patch (2024.04.2) is in final verification, so we won't be updating quarto.

**Comment by gtritchie** [comment] 2024-06-03 17:11
I just opened https://github.com/rstudio/rstudio/issues/14779 to nudge us to update it for the 2024.07 release.
