### ISSUE TITLE
The current version of RStudio does not correctly show the columns that are currently in display in the viewer pane

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [rstudio/rstudio#9036] opened 2021-02-26 18:07 UTC
### System details

    RStudio Edition : 
    RStudio Version : 1.4.1106
    OS Version      :  Ubuntu 18.04
    R Version       :  4.0.2

### Steps to reproduce the problem
Please run the lines below:
```
df <- as.data.frame(matrix(0, ncol = 129, nrow= 500))
colnames(df) <- paste(1:129,LETTERS, sep = "_")

```

### Describe the problem in detail
The current version of RStudio does not correctly show the columns that are currently in display in the viewer pane.
Please see screenshot below. The output is currently displayed as 79 - 50.
![RStudio_minorbug](https://user-images.githubusercontent.com/37449624/109337760-602d7d00-7876-11eb-904c-22d8ed06096a.png)

### Describe the behavior you expected
The correct output should be 79 - 129

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2021-02-26 18:12
Confirmed this works as expected on RStudio 1.3.1093 on macOS.

**Comment by mikebessuille** [comment] 2021-03-01 18:38
Regression, should fix for Juliet Rose

**Comment by adamconroy** [comment] 2021-03-03 19:22
This appears to have been caused by the jQuery update here: https://github.com/rstudio/rstudio/commit/5e9982d70dbdfe054d051e26a6d7ec98d01c59da

Investigating.

**Comment by ronblum** [comment] 2021-03-15 18:51
The last column displayed is now correct. However, the first digit is one lower than it should be. That is, in the example above:
* The first page should be 1-50, but it's showing 0-50
* The second page should be 51-80, but it's showing 50-100
* The third and final page should be 80-129, but it's showing 79-129.

**Comment by adamconroy** [comment] 2021-04-09 18:12
@ronblum im so used to counting from zero I didn't even notice! fixed in this quick commit https://github.com/rstudio/rstudio/commit/ca273e00cd3b0563ed3140a23f44dc604f914f69

feel free to ping me directly if anything else is awry, ill fix it immediately!

**Comment by ronblum** [comment] 2021-04-12 17:44
Verified in RStudio Desktop 1.4.1671 and RStudio Server 1.4.1671 on Red Hat 8.3 using Chrome and Safari on MacOS 11.3.

**Closed by ronblum** 2021-04-12 17:44 UTC
Labels: bug, data viewer, regression
