### ISSUE TITLE
Running usethis::use_pkgdown_travis() hangs

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#7924] opened 2020-09-30 17:34 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.861
    OS Version      : Ubuntu 20.04
    R Version       :  4.0.2

### Steps to reproduce the problem

1. Create a new project (R package)
2. touch `.Rprofile`
3. Run `usethis::use_pkgdown()`
4. Run `usethis::use_pkgdown_travis()`

The Console then hangs. For the steps above I get a screen

![rstudio-bug](https://user-images.githubusercontent.com/1267747/94719362-fbafd580-034a-11eb-9a95-c74cc0e01602.png)

Running the above code in a terminal raises an error as the pkg isn't a git repo. 

If I run the above code in an actual git repo I get

![rstudio-bug2](https://user-images.githubusercontent.com/1267747/94719446-12eec300-034b-11eb-875d-187cbbd69a45.png)

### Describe the problem in detail

The console than permanently hangs and I need to kill RStudio

Note: I've been having lots of issues with RStudio IDE crashing - hence trying the bleeding edge. This is the first time I've been 
able to nail down a reproducible issue (on my side).

### Describe the behavior you expected

Not hanging.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-09-30 17:40
Here's what I see (on macOS):

<img width="442" alt="Screen Shot 2020-09-30 at 10 40 15 AM" src="https://user-images.githubusercontent.com/1976582/94720446-56284200-0309-11eb-85c9-b518189fcc6d.png">

I wonder if the attempt by usethis to copy things to the clipboard is hanging / failing on your machine?

**Comment by kevinushey** [comment] 2020-09-30 17:41
Does the issue reproduce if you use:

```
clipr::write_clip("hello")
```

**Comment by csgillespie** [comment] 2020-09-30 17:55
> Does the issue reproduce if you use:
> 
> ```
> clipr::write_clip("hello")
> ```

Yes it does.

For info, I can open and RStudio terminal, launch R and that's fine

---

 * I use i3 as tiling manager

**Comment by kevinushey** [comment] 2020-09-30 18:00
Thanks for confirming! Unfortunately, I don't know why this would be failing -- you might need to step into the `clipr` sources to see how it's trying to copy things to the clipboard, and what invocation is failing. IIRC `clipr` tries to use `xsel` or `xclip` on Linux with X11.

**Comment by csgillespie** [comment] 2020-09-30 18:27
Dug into the source of `clipr`. The following
```
system2("xsel", "--clipboard")
```
causes RStudio to hang. It works fine in `RStudio terminal > R` Running `xsel --clipboard` in a Linux terminal also works.

I could raise an issue with {clipr}, but this seems an RStudio problem?

---

A workaround (for me) is  {clipr} first checks, if xclip is installed (before falling back to `xsel`). Solution, install `xclip`!

**Comment by kevinushey** [comment] 2020-09-30 20:42
I think `clipr` should change how it invokes `xsel`; e.g. this works for me:

```
system("xsel --clipboard --output", intern = TRUE)
```

The documentation states that the behavior depends on whether input / output are ttys:

```
       By default, this program outputs the selection without modification if both standard input  and
       standard  output  are  terminals (ttys). Otherwise, the current selection is output if standard
       output is not a terminal (tty), and the selection is set from standard input if standard  input
       is not a terminal (tty). If any input or output options are given then the program behaves only
       in the requested mode.

       If both input and output is required then the previous selection is  output  before  being  re‐
       placed by the contents of standard input.
```

so I think it's important for `clipr` to be explicit here.

**Comment by ronblum** [comment] 2020-10-02 15:30
@kevinushey I'm marking this as a bug because of the difference between running this in RStudio and running it in R.

**Comment by kevinushey** [comment] 2020-10-02 21:17
Ultimately, I believe this issue needs to be fixed outside of RStudio (since the issue is ultimately a bad interaction between RStudio and the `xsel` program; at least as invoked in certain circumstances).

**Closed by kevinushey** 2020-10-02 21:17 UTC
Labels: bug
