### ISSUE TITLE
Source editor display issue when Emoji is present in file.

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#1701] opened 2017-11-01 16:18 UTC
@trestletech Found this and I was able to reproduce it on Mac 1.2.142. Once I removed the emojis in the file, I didn't see the issue anymore.

![editor](https://user-images.githubusercontent.com/15237845/32284714-125f14f4-bef6-11e7-9286-336ccbd2733f.gif)

I changed the js file to txt so I could attach it.
[movies.txt](https://github.com/rstudio/rstudio/files/1434804/movies.txt)

**Comment by trestletech** [comment] 2017-11-01 17:23
Just to be clear, the issue was not with git but was that the file was actually being mutated in ways other than what was represented in the RStudio editor. IE when I opened up the file in vim, it showed what the RStudio git diff showed, not what the RStudio editor showed.

**Comment by dfalty** [comment] 2017-11-01 17:41
@trestletech You are correct. Updated the ticket to better reflect this.

**Comment by kevinushey** [comment] 2017-11-01 18:41
So somehow, the buffer open in RStudio became out-of-sync with the actual file contents on disk?

What emojis were available in the file? I think some other users have reported this sort of weirdness with emojis that require more than one character.

It'd be great if we could get a minimally reproducible example (a small document containing emojis that exhibits this same behavior when edited in RStudio)

**Comment by trestletech** [comment] 2017-11-01 18:52
I had created 👍 and 👎 emojis externally and copied and pasted them in. I then found that editing certain lines (but perhaps not others?) would inject the text into the wrong place in the file. I was using vim mode.

This may be a separate issue, but when I do the following, it looks like it perhaps deletes one of two bytes of the emoji, which leaves the editor confused.

1. Paste a thumbs up emoji from above into an empty editor in RStudio using vim mode
2. Exit insert mode, go back and highlight the "second half" of the emoji.
3. Press `x`.
4. Add some characters at the beginning of the line and the end.

When I did that on my IDE nothing showed up, but when I viewed the file in another editor there was just a stray byte left lingering.

**Comment by kevinushey** [comment] 2017-11-02 18:59
Here's a reproducible example:

1. Create a new text document in R, and save it some where (e.g. `hello.txt`),
2. Copy and paste "👍: Hello!" into the editor,
3. Save the document,
4. From a terminal, run `watch hello.txt` (so we can see the 'true' contents of the file),
5. Place the caret on the 'H', and type 'Goodbye!' so the text reads "👍: Goodbye! Hello!"
6. Notice that the text contents are now out-of-sync.

<img width="191" alt="screen shot 2017-11-02 at 11 50 12 am" src="https://user-images.githubusercontent.com/1976582/32344427-0fab98a8-bfc4-11e7-978d-6435df6edcf2.png">
<img width="201" alt="screen shot 2017-11-02 at 11 50 18 am" src="https://user-images.githubusercontent.com/1976582/32344428-0fd35460-bfc4-11e7-8336-a9ca60623c0a.png">

I suspect the issue is that our `save_document_diff` routine is computing incorrect offsets for files containing multibyte emojis like this:

<img width="362" alt="screen shot 2017-11-02 at 11 51 35 am" src="https://user-images.githubusercontent.com/1976582/32344491-4698fb26-bfc4-11e7-809e-09fb33327f8e.png">

Note that the 4 there (the offset) is wrong -- this should actually be 3; I suspect the offset is being computed incorrectly because JavaScript tells us the length of 👍 is 2, even though it's just one character:

<img width="104" alt="screen shot 2017-11-02 at 11 54 05 am" src="https://user-images.githubusercontent.com/1976582/32344567-8e32b72e-bfc4-11e7-811c-7acbb7b237f7.png">

Unfortunately, http://blog.jonnew.com/posts/poo-dot-length-equals-two seems to suggest that counting the number of characters in a JavaScript string is actually surprisingly difficult. It might be better to just properly accommodate the fact that we're counting the number of code points, not characters, here:

https://github.com/rstudio/rstudio/blob/1867b7d59a747f0bebda18a9e1f9f8da83c083a5/src/cpp/session/modules/SessionSource.cpp#L498-L508

**Comment by kevinushey** [comment] 2017-11-02 19:05
We could also consider bringing in https://github.com/orling/grapheme-splitter to properly count the number of graphemes in a JavaScript string.

**Comment by kevinushey** [comment] 2019-09-04 22:13
Marking as v1.3-preview as the underlying problem (document is corrupted when editing a document containing emojis) is worth fixing before release.

**Closed** 2019-10-24 23:46 UTC
Labels: ace, bug, medium, reproducible
