### ISSUE TITLE
RStudio crashes in certain situations with non-ASCII characters in R scripts

### ISSUE THREAD

**Issue by arne-henningsen** [rstudio/rstudio#14700] opened 2024-05-14 16:20 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.0+735 "Chocolate Cosmos" Release (a00d0e775dbc93e0d79a1bf474e3e8e8de677383, 2024-04-24) for Ubuntu Jammy Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2024.04.0+735 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.4.553
    OS Version      : Ubuntu 22.04.4 LTS
    R Version       : 4.4.0 (2024-04-24)

The file "diagnostics-report.txt" is attached below.

### Steps to reproduce the problem
(a) Create an R script with the following content:
```
table( dat$, dat$år )
```
(b) Move the cursor to the first line of the R script between the dollar sign and the comma.
(c) press the 'tab' key.

### Describe the problem in detail
R / RStudio crashes: "R encountered a fatal error. The session was terminated." and "Unexpected  exception [...]" (see attached screenshot)
![Screenshot_20240514_175916](https://github.com/rstudio/rstudio/assets/19424748/5c34535f-c574-49d3-a7b8-68b1be19df56)

The error only occurs in RStudio's "Files" pane. It does **not** occur in RStudio's "Console" or in basic R.

The error also occurs if a data.frame 'dat' actually exists. As a command for creating a data.frame is unnecessary for reproducing the bug, I omitted it to keep the reproducible example minimal.

It seems to me that the bug always occurs when one uses the 'tab' key for auto-completion in a command with a non-ASCII character in an argument.

### Describe the behavior you expected
Do not crash but show a 'menu' for selecting a variable.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/15311171/diagnostics-report.txt)

**Comment by ronblum** [comment] 2024-05-14 16:39
@arne-henningsen Thank you for raising this! This looks like a duplicate of #14625, which is fixed in the just-published patch, 2024.04.1+748, so I would recommend updating to it. https://posit.co/download/rstudio-desktop/

**Closed by ronblum** 2024-05-14 16:39 UTC
Labels: bug, new

**Comment by arne-henningsen** [comment] 2024-05-14 19:17
Thanks a lot! I can confirm that this bug has been fixed in version 2024.04.1+748 :-)
