### ISSUE TITLE
Viewer no longer open in the new window for DT::datatable

### ISSUE THREAD

**Issue by 1DanielG** [rstudio/rstudio#6893] opened 2020-05-16 11:03 UTC
### System details

RStudio Edition :  Desktop
RStudio Version :  1.3.958-3
OS Version      :  Windows 10 x64
R Version       :  R version 4.0.0 (2020-04-24)

### Steps to reproduce the problem
Run any command that sends an interactive output to the HTML widget

```
library(DT)
datatable(data.frame(x = Sys.Date()))
```

### Describe the problem in detail
Referring to Viewer Pane not working issue [see #6737](https://github.com/rstudio/rstudio/issues/6786) the underlying R bug is fixed in R-devel (1.3.958-3) but the `show in the new window` function in the viewer pane is not working 
### Describe the behavior you expected
Open the viewer pane in the new window (Chrome)

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by R-Hannibal** [comment] 2020-05-19 15:54
Thank you @1DanielG for reporting this issue. This looks like a re-occurrence or different manifestation of #6737. Closing this issue and re-opening #6737 to continue the investigation there.

**Comment by R-Hannibal** [comment] 2020-05-19 19:09
Re-opening.

This looks like a new issue and not a re-occurrence of #6737. Re-opening so we can look to address this in a future release.

**Comment by DanVal80** [comment] 2020-05-27 18:21
I am having the same issue with plotly objects. Clicking "show in new window" (in v1.3.959) when a plotly object is displayed, does not open the browser anymore.

**Comment by jmcphers** [comment] 2020-06-10 23:29
I reproduced this on Windows with R 4.0.0 and RStudio 1.3.1014 (current preview), but did not reproduce on MacOS with the dailies.

**Comment by jmcphers** [comment] 2020-06-11 23:54
More investigation notes: I thought this was going to be a simple issue w/ failing to send the URL to the desktop, but it actually appears to be an issue happening on the Qt side.

**Comment by jmcphers** [comment] 2020-06-12 21:02
There's definitely something wrong here in Qt land (Qt is dropping session URLs on the floor and not opening them natively nor with an external URL opener) but #7118 should sufficiently address this by not using session URLs for opening these files.

**Closed** 2020-06-15 18:01 UTC
Labels: bug, viewer pane

**Comment by R-Hannibal** [comment] 2020-07-02 18:07
@1DanielG - Thanks so much for reporting this issue. Just tested and it's looking fixed to me on the latest preview (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). Please let us know if you're getting different results or have any other issues.

Verified Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows 10 x64 - Desktop

Comparison test between 1.3.959 vs 1.3.1054, 'Show in new window' button in the viewer pane is non-functional on the old build, works as expected on the latest preview.
