### ISSUE TITLE
Flatpak and Appimage

### ISSUE THREAD

**Issue by GuckicheLorraine** [rstudio/rstudio#15051] opened 2024-08-12 15:26 UTC
Hello !
Would it be possible to push a flatpak build or appimage pretty please ? So it can be used with immutable systems ?

Have a nice day !

(NB : I just reposted the request because I forgot to change the label).

(NB 2 : The labels didn't saved even tho I clicked on it)

**Comment by gtritchie** [comment] 2024-08-19 16:28
Closing as a duplicate of #3079.

**Closed by gtritchie** 2024-08-19 16:28 UTC
Labels: enhancement, new
