### ISSUE TITLE
RStudio 1.4 runs interactive code out of order when commands are entered manually one after another

### ISSUE THREAD

**Issue by eipi10** [rstudio/rstudio#8837] opened 2021-01-28 18:25 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4-1103
    OS Version      :  Windows Server 2016 Standard v1607 / Mac OS 10.15.6
    R Version       :  4.0.3

### Steps to reproduce the problem

Step 1. Put the following code in an R script:

```
library(tidyverse)

#1. 
a = map(1:1e3, ~quantile(1:.x))

#2.
b = diamonds %>% 
  group_by(cut) %>% 
  summarise(across(where(is.numeric), ~ map(1:1e4, quantile(.))))

#3.
c = randomForest::randomForest(cut ~ ., data=diamonds[1:1e4,])

#4.
d = lm(Petal.Width ~ Species, data=iris)
```

Step 2. Run `library(tidyverse)` just to get the packages we need loaded. Now run each line of code individually by placing the cursor at `#1.` in the code above and type ctrl-enter 4 times in row (on Windows) or command-enter 4 times in a row (on Mac). The key is that you need to enter each command fast enough that the previous command hasn't completed before you enter the new one. That's why I've written the code above so that some statements take a couple of seconds to run. Here's the output I get when I type ctrl-enter four times at a "typical" pace for this type of thing:

```
> #1. 
> a = map(1:1e3, ~quantile(1:.x))
> #2.
> b = diamonds %>% 
+   group_by(cut) %>% 
+   summarise(across(where(is.numeric), ~ map(1:1e4, quantile(.))))
`summarise()` regrouping output by 'cut' (override with `.groups` argument)
> #4.
> d=lm(Petal.Width ~ Species, data=iris)
> #3.
> c=randomForest::randomForest(cut ~ ., data=diamonds[1:1e4,])
```

Note that statement 4 is run before statement 3. I can reproduce the above incorrect ordering over and over again on both Windows and Mac OS. I was seeing this in my real code and it's reproducible there as well. 

### Describe the problem in detail

See above.

### Describe the behavior you expected

When I type ctrl-enter four times in a row, the statements should be run in the order they are written (1,2,3,4) rather than out of order (1,2,4,3).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2021-01-28 19:26
Thanks for the bug report! I can reproduce reliably with this script:

```
#1.
print(1); Sys.sleep(1)

#2.
print(2); Sys.sleep(1)

#3.
print(3); Sys.sleep(1)

#4.
print(4); Sys.sleep(1)
```

**Comment by kevinushey** [comment] 2021-01-28 19:46
Tracked this down; looks like a regression caused by https://github.com/rstudio/rstudio/commit/2f49492485b87d468ca2e0928304cf0612de2460.

**Comment by kevinushey** [comment] 2021-01-28 20:13
The problem occurs because when we fix up console input, we take the next piece of console input here, from the _front_ of the queue:

https://github.com/rstudio/rstudio/blob/70c9a064530c2e469f61c1bb601e7c33232a2a51/src/cpp/session/SessionConsoleInput.cpp#L172-L173

but then we place it at the _back_ of the queue here:

https://github.com/rstudio/rstudio/blob/70c9a064530c2e469f61c1bb601e7c33232a2a51/src/cpp/session/SessionConsoleInput.cpp#L263-L266

and so this causes pending input to be improperly re-arranged.

**Comment by eipi10** [comment] 2021-01-28 20:25
You guys are fast! Thanks for tracking down the problem and for creating a much simpler reproducible example.

**Comment by R-Hannibal** [comment] 2021-02-12 16:30
QA Note: Should be verified on both desktop and server.

**Comment by astayleraz** [comment] 2021-02-12 16:51
I verified in Version 1.4.1106-4 and Version 1.4.1564-1 the code is running in the correct order now. Closing as fixed.

**Closed by astayleraz** 2021-02-12 16:51 UTC
Labels: bug, regression, reproducible, test
