### ISSUE TITLE
Copy Plot to Clipboard - pasting bitfile option not working correctly in latest build

### ISSUE THREAD

**Issue by kevinbop** [rstudio/rstudio#12466] opened 2022-12-19 22:45 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version :  RStudio 2022.12.0+353 "Elsbeth Geranium" 
    OS Version      :  Windows 10
    R Version       :   R version 4.2.2 (2022-10-31 ucrt) -- "Innocent and Trusting"

### Steps to reproduce the problem
I have:
-  produced a plot  which has appeared in the Plots tab of RStudioIDE correctly.
-  selected the Export>Copy to Clipboard Option and the window opens correctly.
-  pressed the Copy Plot button to export the plot to the clipboard (with BitMap button selected)

### Describe the problem in detail

When the plot is pasted into either Excel or Word it includes a bitmap portion of the IDE and excludes part of the plot .
Attached PDF shows the Export pop 
[Copy to Plot to Clipboard Paste Issue .pdf](https://github.com/rstudio/rstudio/files/10263286/Copy.to.Plot.to.Clipboard.Paste.Issue.pdf)

### Describe the behavior you expected

A complete bitmap copy of the plot was expected to be pasted.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-12-20 14:55
@kevinbop Thank you for raising this! 

I can reproduce this in
- RStudio Desktop 2022.12.0+353 on Windows 11 with Word

It works in
- RStudio Desktop 2022.07.2+576 with Word
- RStudio Desktop 2022.12.+353 on MacOS 13.2 with Word

Note that part of the pane is included in the image, so this might be a regression of issue #3853.

**Comment by jgutman** [comment] 2022-12-20 15:40
I think the user-submitted PR you're referring to was only merged in Cherry blossom, so no. copy plot to clipboard functionality was revamped in Electron, so this could be an electron bug

**Comment by jgutman** [comment] 2022-12-20 22:48
Also saw  report on twitter of export plots not working for some windows users with 2022.12.0 https://twitter.com/ScienceGirl_KJS/status/1604870779480547328?t=UDeHbJR8Quohs6tuNYn73Q&s=19

**Comment by kevinbop** [comment] 2022-12-21 00:34
Thanks @ronblum for  confirming the problem.

My solution was also to revert to the previous RStudio version I was running:
RStudio 2022.07.2+576

**Comment by banbh** [comment] 2023-01-07 20:05
I had exactly this problem (same RStudio version on the same OS). Like @kevinbop I downgraded to a version from [Daily build: 2022.07.2+576.pro12](https://dailies.rstudio.com/version/2022.07.2+576.pro12/) but I wanted to add that the version under **RStudio Desktop Electron** suffered the same problem; the version under **RStudio Desktop** works as expected.

**Comment by peter-devoil** [comment] 2023-01-11 08:52
Confirmed in Linux 2022.12.0+353

**Comment by Jay-Turtle** [comment] 2023-02-10 16:23
I had same issue. Changed the view (Zoomed out) and now it works fine.

**Comment by sharon-wang** [comment] 2023-02-22 19:32
Ready for test! Please see the QA notes and suggested steps in #12732

**Comment by ronblum** [comment] 2023-02-24 18:14
@sharon-wang This works in RStudio Desktop. The problem occurs in RStudio Server (I tried with both Chrome and Firefox). Is this fix for RStudio Desktop only, or should it apply to the server as well?

**Comment by sharon-wang** [comment] 2023-02-24 18:32
@ronblum Ah I didn't realize this was reproducible in Server as well! This fix is electron-only and only applies to RStudio Desktop. I can take a look into Server

**Comment by ronblum** [comment] 2023-02-24 18:44
@sharon-wang OK! I'll open a new issue for RStudio Server, since this was all about the desktop app. I'll check if this is a regression or existing behavior in the server.

Verified in RStudio Desktop 2023.03.0-daily+358 on MacOS 13.2 and Ubuntu 22.04.2.

**Comment by ronblum** [comment] 2023-02-24 18:59
Sorry @sharon-wang, I jumped the gun. On Windows 11, this is failing with 2023.03.0-daily+358; instead, a small empty image is pasted in Word.

**Comment by sharon-wang** [comment] 2023-02-24 19:05
@ronblum that sounds like this bug: https://github.com/rstudio/rstudio/issues/5103

Could you try pasting in a different application, like Google Docs or Slack? If the image shows up correctly, then the fix for the problem in this issue is resolved (at least for Desktop), and the small empty image issue will be investigated as part of #5103.

**Comment by ronblum** [comment] 2023-02-24 19:12
@sharon-wang Ah yes, in Word "Paste Special" as bitmap works, as does pasting in Slack. You can see my name all over the other issue, so you'd think I'd remember. 😄 

Closing as verified.

**Closed by ronblum** 2023-02-24 19:12 UTC
Labels: bug, regression, plots
