### ISSUE TITLE
Save / Save As greyed out

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#5722] opened 2019-11-08 01:42 UTC
Intermittently I've found myself unable to save scripts because the 'save' / 'save as' menu options are greyed out. Sometimes reloading the project helps, not always. In the example pictures below I wanted to save an existing script with a different name then edit it, essentially forking it. Unable to do so, I pasted the whole thing into a new script and could then save (which prompts the Save As dialogue box) but not save as directly.
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1 

RStudio preview version 1.2.5013
```

![RstudioBugSaveAs1](https://user-images.githubusercontent.com/4599748/68442458-e3105d00-0185-11ea-89fd-5c53297094b4.jpg)
![RstudioBugSaveAs2](https://user-images.githubusercontent.com/4599748/68442462-e60b4d80-0185-11ea-886d-34817bde4e72.jpg)

**Comment by pascaloettli** [comment] 2019-11-08 02:39
Sorry for the naive question, but is it the Desktop or the Server version? On the pictures, it looks like RStudio is running In Firefox

**Comment by SimonDedman** [comment] 2019-11-08 08:57
Hi Pascal,
This is desktop version on xubuntu 19.10 (need to update that!). Just looks
somewhat unusual as I have it set to hide titlebars when maximised. Gives
me a teeny bit more real estate :)

**Comment by HanOostdijk** [comment] 2020-03-15 17:22
Similar problem described in [6475](https://github.com/rstudio/rstudio/issues/6475)

**Comment by kevinushey** [comment] 2020-03-16 19:03
Closing in favor of https://github.com/rstudio/rstudio/issues/5722 which as a reproducible example.

**Closed by kevinushey** 2020-03-16 19:03 UTC
Labels: bug, repro needed
