### ISSUE TITLE
Wrong keyboard layout in 'keyboard shortcuts' menu with German keyboard

### ISSUE THREAD

**Issue by tobimaki** [rstudio/rstudio#2712] opened 2018-04-27 09:21 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.447 (rstudio-xenial-1.1.447-amd64.deb)
    OS Version      :  Debian 9.3 stretch
    R Version       :  3.4.4

     Other    : Keyboard - German (qwertz); Operating system default language - English (UK)
  
### Steps to reproduce the problem
First to clarify, the keyboard layout is recognised properly in RStudio, e.g. typing in the Console or the Script file all keys produce what they should, however, setting keyboard shortcuts is buggy.

Go to Tools -> Global Options -> Code -> 'Keybindings' (Modify Keyboard Shortcuts...)
try setting a shortcut that would be e.g. 'Ctrl + Shift + <' (Ctrl = Strg on German keyboard), or involve 'Shift + :' and many other non-letter keys.

### Describe the problem in detail
 As examples (applies to several keys): the '<' key produces a ',' - the ':' key produces a ';' etc...,
which looks to me as though somehow the keyboard settings are different for this menu. No idea why, or if this could be related to having a German keyboard and a English (UK) locale.

### Describe the behavior you expected
keys should produce the expected output

**Comment by kevinushey** [comment] 2018-07-11 22:32
This is indeed an issue with how RStudio handles key inputs. In particular, when translating JavaScript character codes into the associated key that was typed, RStudio assumes an English keyboard layout. This implies that pressing a key that uses the keycode 188 is translated to the <kbd>,</kbd> key, as this is the case on an English (U.S.) keyboard layout.

Of course, this isn't true on German keyboards as this instead translates to <kbd><</kbd>.

Fortunately, alternate APIs exist to ask what key was actually typed by the user, so I'll see if we can make use of this instead to provide a better representation of the pressed key.

**Comment by kevinushey** [comment] 2018-07-12 19:15
Unfortunately the APIs that provide us the necessary information here are unreliable with Qt. 😞

**Comment by ronblum** [comment] 2020-03-27 16:52
I can confirm that this is fixed in RStudio Desktop 1.3.929 on MacOS 10.15.4 with a German standard (QWERZ) keyboard. However, I can't find a proper keyboard—virtual or physical—for a Debian VM. @tobimaki would you be willing to check whether this is now fixed in Debian? The latest 1.3 Middlemist Red preview is available at https://rstudio.com/products/rstudio/download/preview/ .  Thanks!

**Comment by tobimaki** [comment] 2020-03-31 11:21
I just tested this on a fresh Debian 9(.12) install in virtualbox, and sorry, it is not entirely working here. Might be virtualbox related, but I fear not (see attached video). Entering a shortcut seems to work in the beginning, but then only a white box is where the key should be, and the shortcut is then also not recognised (not working). I only tested this for very few characters, but several are affected.
I also noticed that at least for 'go to end of line' the shortcut 'Ctrl + e' only starts working after the line was selected an highlighted green, not sure if this is intended that way.

Haven't been working with RStudio in a while - sorry if this test is a bit slipshot, and please get a short video showing the behaviour [here](https://filehorst.de/d/dFtCDaxw) (wait until counter has timed out and then click the link).

Does not belong here, but I noticed that for the .deb package r-base is currently not a dependency, which it should probably be, as R Studio won't start without it.

**Comment by ronblum** [comment] 2020-04-21 20:19
@tobimaki Thank you for checking! I'll reopen the ticket.

**Comment by jmcphers** [comment] 2020-04-25 17:53
This long-standing issue does not meet the bar for 1.3. We will consider for the patch release.

**Comment by mikebessuille** [comment] 2020-07-16 17:27
Does the 1.3.1056 build just released in July 2020 fix this?  We believe it fixes the white box issue.

**Comment by tobimaki** [comment] 2020-07-28 07:36
Just tested this with 1.3.1070.

Sorry, the behaviour is different, but it is not fixed. Basically the German keyboard layout is being ignored completely, so that it seems to behave as in the beginning:
< key-press results in ,
SHIFT + < results in SHIFT + .
etc.

No white boxes, but at the moment I can't produce the corresponding characters.

**Comment by adamconroy** [comment] 2020-10-15 18:35
Sadly I'm going to advise pushing this to 1.5 (but then look at it soon after shipping 1.4). Unfortunately the testing matrix and the amount that would have to be changed here goes above the bar of what I'm comfortable with this close to shipping. There is a difference between "german keyboard on windows RStudio Server" and "german keyboard on debian RStudio desktop" unfortunately and the changes needed would require testing all permutations for regressions.

**Comment by jmcphers** [comment] 2020-10-15 19:29
> the amount that would have to be changed here

What needs to be changed, exactly? Did you figure out what the fix should be?

Also: did you try to repro with one of the trial Qt 5.15 builds? (Since this issue is downstream from Qt there's some hope it was addressed there).

**Comment by adamconroy** [comment] 2020-10-16 21:10
I originally was trying the keyCode solution after some research but saw that the Kevin also tried this and that it was not sufficient. As the issue seems to stem from Qt filtering the key codes (possibly different in various OSes from my testing) it was looking like we'd have a pretty big test matrix for changes that relied on specific OS+distribution setups.

However! Recommending testing on the latest Qt builds was great and, at the least, it appears to work flawlessly on MacOS on Qt 5.15. I'm still working on getting a Linux build working for me but it's promising.

**Comment by adamconroy** [comment] 2020-10-19 19:14
Tested on the Qt 5.15 builds both on all 3 major operating systems and it appears to be resolved! No white boxes and the correct German characters appear.

**Closed by adamconroy** 2020-10-19 19:14 UTC
Labels: backlog, bug, reproducible
