### ISSUE TITLE
rJava::.jinit() terminates R session of RStudio when using R 4.2.0

### ISSUE THREAD

**Issue by gk-crop** [rstudio/rstudio#11076] opened 2022-04-27 11:12 UTC
When calling rJava::.jinit() in the RStudio console then RStudio shows the dialog "R Session Aborted" (R encountered a fatal error). 
This happens with R 4.2.0, but not with previous R versions.  

In plain R or when sourcing the command as local job in RStudio there is no error.

### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.1 Build 461
    OS Version      :  Windows 10 Pro, 21H2, 64 bit
    R Version       :  4.2.0 (2022-04-22 ucrt, x86_64-w64-mingw32/x64)
    Java Version  : 11.0.12 (Temurin - Eclipse Foundation amd64) 

### Steps to reproduce the problem

Start RStudio
execute in the console:
```
install.packages("rJava") # if rJava is not installed yet
rJava::.jinit()
```

Alternatives:
- create a file `checkJava.R` that contains `rJava::.jinit()`
- type `source("checkJava.R")`

### Describe the problem in detail

When executing the code or sourcing it, RStudio reports that the R session aborted.

### Describe the behavior you expected

R session should not crash.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/8571445/diagnostics-report.txt)

**Comment by kevinushey** [comment] 2022-04-27 18:08
Thanks for the bug report -- I can reproduce this as well. The crash is happening in a call to `do_getlocale()` in R:

![image](https://user-images.githubusercontent.com/1976582/165590219-d04e8143-bd26-4677-bd77-915ac669b7c8.png)

For whatever reason, this is crashing RStudio:

```
Sys.getlocale(cateogry = "LC_MESSAGES")
```

As a temporary workaround, you could use the following:

```

replacement <- function(category = "LC_ALL") {
  
  if (identical(category, "LC_MESSAGES"))
    return("")
  
  category <- match(category, .LC.categories)
  if (is.na(category)) 
    stop("invalid 'category' argument")
  .Internal(Sys.getlocale(category))
  
}

base <- asNamespace("base")
environment(replacement) <- base
unlockBinding("Sys.getlocale", base)
assign("Sys.getlocale", replacement, envir = base)
lockBinding("Sys.getlocale", base)

library(rJava)
rJava::.jinit()
```

We'll need to investigate further.

**Comment by kevinushey** [comment] 2022-04-28 19:02
It looks like this happens because the RStudio R session is compiled with MSVC, rather than gcc. For MSVC, an invalid parameter handler is registered as described in:

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/invalid-parameter-functions?view=msvc-170

It seems like this handler is not registered by default for applications built using MinGW / gcc, so crashes are not triggered in such a case.

If we wanted to match the behavior of R, we would likely want to disable this by registering a no-op handler via `_set_invalid_parameter_handler()` (or make sure behavior configurable in some way).

**Comment by kevinushey** [comment] 2022-04-28 19:30
There should also be a fix coming to the next patched release of R 4.2.0, available from:

https://cran.r-project.org/bin/windows/base/rpatched.html

That hasn't been published yet, but hopefully will soon. (Thanks to Tomas Kalibera for taking a look so quickly.)

**Comment by mikebessuille** [comment] 2022-05-02 17:58
Leaving this in SW for now, hoping this is fixed in R and we can just re-test it.

**Comment by jgutman** [comment] 2022-05-09 17:53
Tested in Windows 10 running R version 4.2.0 Patched (2022-05-06 r82327 ucrt) with RStudio Desktop 2022.6.0.374 and rJava 1.0.6. 

`rJava::.jinit()` runs successfully with the latest R patch

**Closed by jgutman** 2022-05-09 17:53 UTC
Labels: bug, test

**Comment by hsiaoyi0504** [comment] 2022-07-06 20:47
I meet the issue again for R4.2.1 patch.

**Comment by GabryS3** [comment] 2022-07-13 04:54
Hi, is this issue been fixed in the latest R (R 4.2.1 - June, 2022) & RStudio (2022.07.0+548) versions??
I also had an issue of RStudio crashing every time I load the xlsx package with R version 4.2.0 & RStudio version 2022.02.3....I am not sure if this is related...but I would love to know whether this is fixed in the latest R/RStudio versions before updating...
Thanks
Gabriella

**Comment by Phylloxera** [comment] 2022-07-22 16:20
Hi, is there a patched version for Mac or just windows?

**Comment by kevinushey** [comment] 2022-07-22 17:22
This issue specifically tracks the issue of using rJava with R 4.2.0 on Windows; if you're having trouble with rJava with a different platform (e.g. macOS) then please file a new issue with more details.

**Comment by powerguo** [comment] 2023-01-19 20:55
Hi all, 

I believe I encountered this issue again running on 4.2.2 Patched with RStudio 2022.12.0+353 "Elsbeth Geranium" Release. 

Every time I try to load a package R Studio just crashes with the encountered fatal error message. Please let me know if I can provide any diagnostics to help resolve the issue. 

Thanks!

**Comment by mikebessuille** [comment] 2023-01-20 14:48
@jgutman it sounds to me like the latest comment is a different issue; what do you think?

**Comment by jgutman** [comment] 2023-01-20 17:40
Yes, should definitely be a different issue, and we would likely need more info from @powerguo here

**Comment by mikebessuille** [comment] 2023-01-20 18:39
@powerguo would you mind creating a new issue for this with the details of what you're seeing?  You can create it in https://github.com/rstudio/rstudio/issues.   Thank you!
