### ISSUE TITLE
RStudio enters Alt-keys together with special characters on Windows

### ISSUE THREAD

**Issue by dpprdan** [rstudio/rstudio#4247] opened 2019-01-31 09:57 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1256
    OS Version      : Windows 10 x64 (build 17134)
    R Version       : 3.5.2

### Steps to reproduce the problem

Enter a special character in RStudio Desktop on Windows (in source editor, console, search field, ...) via an [alt code](https://en.wikipedia.org/wiki/Help:Entering_special_characters#Windows_-_Alt_code). I.e. hold down the Alt key and type e.g. `0150` in the Num Pad to enter an en dash `–`. Instead of the en dash the following sequence will be entered: `0150–`. 

### Describe the behavior you expected

I'd expect that only the requested character would be entered, i.e. only the en dash in the example mentioned above without the `0150` characters. 

IIRC this used to work in earlier versions of RStudio.

**Comment by GegznaV** [comment] 2019-02-01 12:45
The same issue.

**Comment by ronblum** [comment] 2019-02-01 16:09
@dpprdan and @GegznaV Thank you for reporting this. I reproduced the problem. We'll review it as we continue on development of RStudio.

**Comment by jmcphers** [comment] 2019-02-08 16:36
@ronblum did you confirm that this works as expected on 1.1?

**Comment by ronblum** [comment] 2019-02-08 21:10
Ah! Yes, it works correctly there, so this is as regression.

**Comment by jmcphers** [comment] 2019-02-14 01:36
Appears to be a problem with the way we're hosting QtWebEngine. Happens everywhere in RStudio's web UI (so not an issue with the Ace input in the editor/console), but not in system dialogs (like the file dialog). 

Does not reproduce in the Qt nanobrowser, so not a WebEngine bug.

**Comment by jmcphers** [comment] 2019-02-14 04:55
Update: it looks like this is a regression in Qt 5.12. Everything works fine in 1.2.1114, which uses Qt 5.11, but not in 1.2.1208, which uses 5.12.

My local dev builds of nanobrowser and RStudio (which are currently on 5.11 but otherwise have current sources from master) also work correctly.

**Comment by kevinushey** [comment] 2019-02-14 17:41
I don't see this issue with a version of RStudio built against Qt 5.12.1, so fortunately this seems like a bug that has been fixed on the Qt side (and so will be fixed when we update Qt)

**Comment by jmcphers** [comment] 2019-03-06 17:17
Should be fixed in the latest preview, 1.2.1320 (via Qt 5.12.1 update in https://github.com/rstudio/rstudio/pull/4314).

**Closed by jmcphers** 2019-03-06 17:17 UTC
Labels: bug, desktop, regression, reproducible, windows
