### ISSUE TITLE
Save a new file into a network share/volume gives an error (Windows)

### ISSUE THREAD

**Issue by randrade-bgene** [rstudio/rstudio#13004] opened 2023-04-17 13:14 UTC
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.3.0.386
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.2.3 (2023-03-15 ucrt)

### Steps to reproduce the problem
    1) Create a new file. 
    2) Go to file -> save 
    3) Select a network volume and save the script in any folder inside it, for example \\192.168.1.100\Projects\Erase.R
    4) RStudio will display an error message saying "Error saving /192.168.1.100/Projects/Erase.R: The system cannot find the path specified"

### Describe the problem in detail
    When I try to save a new file created directly in RStudio into a network folder the application gives an error saying it cannot find the specified path.

    I noticed that the path in the error message does not have the double backslashes ("\\") before the address of the network volume, for example \\192.168.1.100
### Describe the behavior you expected
    I was hoping my file would be saved with no error.

Output of sessionInfo()
> sessionInfo() 
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.utf8  LC_CTYPE=French_France.utf8   
[3] LC_MONETARY=French_France.utf8 LC_NUMERIC=C                  
[5] LC_TIME=French_France.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] rstudioapi_0.14

loaded via a namespace (and not attached):
[1] compiler_4.2.3 tools_4.2.3 

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/11250538/diagnostics-report.txt)

**Comment by gtritchie** [comment] 2023-04-17 17:49
Duplicate of #12652 and #12935

**Closed by gtritchie** 2023-04-17 17:49 UTC
Labels: bug, duplicate, new

**Comment by ronblum** [comment] 2023-04-26 21:05
QA Note: See also #13004.
