### ISSUE TITLE
Daily build, visual markdown editor: cannot access all Zotero items

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rstudio#7720] opened 2020-09-03 09:55 UTC
### System details

```
RStudio Edition : Desktop
RStudio Version : 1.4.774
OS Version : Linux Mint 20 (~Ubuntu 20.04)
R Version : 4.0.2
```

### Steps to reproduce the problem

1. Use the attached Zotero database: [zotero.sqlite.zip](https://github.com/rstudio/rstudio/files/5167663/zotero.sqlite.zip) (to be unzipped first)
1. Open Zotero (I use `5.0.89`, you could create a separate profile to reproduce, see starting zotero with `zotero --ProfileManager`)
1. Visual Markdown Editor: press ctrl+shift+F8 (insert citation)
1. In the citations dialog, go to the Zotero collection by clicking on 'Zotero'. Inspect both collections.

### Describe the problem in detail

While collection 'articles' shows its three items, the other one ('myset') shows nothing (while it has 18 items in Zotero).

### Describe the behavior you expected

All Zotero items should be displayed.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by florisvdh** [comment] 2020-09-03 10:12
Note, given #7720, an interesting Zotero item to test for the current issue, is `@bondNewBookTitle1967`. It had been added specifically to the 'myset' collection, and was never trashed. It cannot be found, it seems

![afbeelding](https://user-images.githubusercontent.com/19164640/92102178-8c43d600-edde-11ea-8263-c8e1f45c34c5.png)

**Comment by dragonstyle** [comment] 2020-09-15 15:45
Thanks for reporting this issue and providing the great reproducible case for me. Since you reported it, we've done a lot of work on our local Zotero support and the issue has been addressed by those changes (see below).

![Screen Shot 2020-09-15 at 11 44 11 AM](https://user-images.githubusercontent.com/261654/93233362-f9ddf380-f748-11ea-8b17-756dac9d4b4a.png)

![Screen Shot 2020-09-15 at 11 44 06 AM](https://user-images.githubusercontent.com/261654/93233363-fa768a00-f748-11ea-920a-19ccb5467309.png)

**Closed by dragonstyle** 2020-09-15 15:45 UTC
Labels: backlog, visual markdown editing

**Comment by R-Hannibal** [comment] 2020-09-15 16:47
@florisvdh, thanks again for finding and reporting this (and other 😉) issues. We truly appreciate community members like yourself who help us to improve the RStudio experience.

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by florisvdh** [comment] 2020-09-23 16:11
I confirm that this works! (tested in 1.4.823) :+1:

**Comment by kfeinauer** [comment] 2020-11-16 17:12
Community verified.

**Comment by ahmoreira** [comment] 2021-01-22 11:31
Hi, thank you very much for the new functionalities in RStudio 1.4!

I am having exactly the same issue as described by florisvdh. 
I am using RStudio in my Desktop, version 1.4.1103, and R version 4.0.2. My OS is Windows 10. 
Should I open a new issue?
