### ISSUE TITLE
Encoding issue in YAML header of R Markdown document

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#2676] opened 2018-04-20 17:15 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.447
    OS Version :      Windows 10
    R Version :       3.4.4 (2018-03-15)

	
### Steps to reproduce the problem

1. Open a new R Markdown document.
2. Delete all contents.
3. Create a YAML header and include non-English letters in it, e.g.:

```yaml
---
title: "ą č ę ė į š ų ū ž abc"
subtitle: "я д ы ж"
output:
  html_document: default
---
```

4. Change the output format by pushing triangle of "Knit" button then, e.g., "Knit to Word" (find animated figure below). Non-English letters get distorted.

![rs rmd yaml bug1](https://user-images.githubusercontent.com/12725868/39064325-d2da5cb4-44d6-11e8-8a24-8f3cd455966f.gif)

### Describe the problem in detail

Non-English letters get distorted in R Markdown document's YAML header when the output format is changed using "Knit" button. This indicates an encoding issue.

### Describe the behavior you expected

I expect the text is left intact (i.e., no distortion in non-English letters).

**Comment by ronblum** [comment] 2018-04-20 18:26
This is a duplicate of #1537—but thank you for raising it.

**Closed by ronblum** 2018-04-20 18:26 UTC
