### ISSUE TITLE
RStudio seems to ignore my global options setting and converts my tabs to spaces

### ISSUE THREAD

**Issue by mowshowitz** [rstudio/rstudio#1980] opened 2018-01-16 20:23 UTC
I use spaces to indent but RStudio always converts spaces into tabs. This is even though I have the "Insert spaces for tab" global option selected.

[Here's](https://i.imgur.com/zBCr5zg.png) my settings in case I'm overlooking something. I've [posted on SO](https://stackoverflow.com/questions/48268178/how-can-i-prevent-rstudio-from-turning-my-spaces-into-tabs-it-seems-to-ignore-m) and the user who tried helping me replicated the issue and couldn't find a solution.

**Comment by jmcphers** [comment] 2018-01-17 00:39
We weren't able to reproduce this, but based on that screenshot it looks like you're on an older release (1.0). We're about to release a new stable version (later this week); would you be willing to let us know if the bug reproduces in that version?

https://www.rstudio.com/products/rstudio/download/preview/

If it does reproduce there, can you tell us more about when the conversion is occurring? You can turn on whitespace character display in Code -> Display.

- do tabs turn into spaces when you press the Tab key?
- do they turn into spaces when the file is saved?
- do they turn into spaces when the file is closed and reopened?

**Comment by jmcphers** [comment] 2019-11-12 19:11
Been well over a year without reproducible steps or any other reports, so closing.

**Closed by jmcphers** 2019-11-12 19:11 UTC
Labels: repro needed
