### ISSUE TITLE
Possible runaway disk recursion in R Notebooks

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9155] opened 2021-03-25 23:54 UTC
### System details

    RStudio Edition : Either
    RStudio Version : 1.4.1106

### Steps to reproduce the problem

We don't know how to reproduce this problem. It occurs when executing an R Notebook chunk that outputs text. It has only been observed on EFS, and may be correlated with the directory containing notebook output being missing or deleted by some other process. 

### Describe the problem in detail

When the problem occurs, the system log fills up with tens of thousands of log entries that look like this:

```
Mar  9 19:09:58 ip-172-31-23-42 rsession-user[1234]: ERROR system error 2 (No such file or directory) [path: /mnt/efs/username/project_path/.Rproj.user/shared/notebooks/59146859-file_name/1/34AB090D913dc6b3/cuwdmhri2wafb/000002.csv]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::openForWrite(std::shared_ptr<std::basic_ostream<char> >&, bool) const src/cpp/shared_core/FilePath.cpp:1482; LOGGED FROM: void rstudio::session::modules::rmarkdown::notebook::ChunkExecContext::onConsoleText(int, const string&, bool) src/cpp/session/modules/rmarkdown/NotebookExec.cpp:429
```

This exhausts the system's resources, and it is no longer possible to use RStudio or sometimes even connect to the system with ssh.

### Describe the behavior you expected

No runaway resource-exhausting behavior.

@jcheng5 noticed on a customer call that the method that's spewing these logs has possible recursion, on this line:

https://github.com/rstudio/rstudio/blob/6507229293465e3d2e17b8a501d4a8e83344612c/src/cpp/session/modules/rmarkdown/NotebookExec.cpp#L415-L421

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2021-03-25 23:57
Internal support ticket: 57613

**Comment by astayleraz** [comment] 2021-04-08 00:30
I tested this with Version 1.4.1666-2 and EFS file system setup and was not able to reproduce the issue or run into any other issues while sanity testing the R console and running chunks. Closing issue.

**Closed by astayleraz** 2021-04-08 00:30 UTC
Labels: notebooks, support, test

**Comment by jcheng5** [comment] 2021-04-08 08:22
We've asked the customer to upgrade to a build with #9171, and to change lock types to advisory. Haven't heard from them since.

**Comment by amcpherson** [comment] 2021-05-29 11:14
I am having this issue on 1.4.1106, how do i access Version 1.4.1666-2?

**Comment by kevinushey** [comment] 2021-05-30 18:24
@amcpherson: please try the [preview release](https://www.rstudio.com/products/rstudio/download/preview/).

**Comment by amcpherson** [comment] 2021-06-01 13:36
I can confirm that this still happens with v1.4.1717-3

**Comment by kevinushey** [comment] 2021-06-01 19:36
Can you share any other details of the environment you're working in, or a reproducible example?

**Comment by amcpherson** [comment] 2021-06-02 16:39
I am running the following singularity command to execute rstudio:

```
module load singularity/3.6.2

mkdir -p /scratch/mcphersa1/home/mcphersa1

singularity exec --bind=rsession.conf:/etc/rstudio/rsession.conf --bind=rserver.conf:/etc/rstudio/rserver.conf \
  --bind ./tmp:/tmp \
  --bind ./packages:/packages \
  --bind myrun:/run \
  --bind=/juno/work \
  --bind var_lib_rstudio-server:/var/lib/rstudio-server \
  --no-home --bind=/scratch/mcphersa1/home/mcphersa1:/home/mcphersa1 \
  --env DISABLE_AUTH=true --env PASSWORD='test' \
  tidyverse_4.0.4.sif \
  /usr/lib/rstudio-server/bin/rserver --auth-none=0 --auth-pam-helper-path=pam-helper
```

The tidyverse_4.0.4.sif singularity image was built using:

```
singularity pull docker://amcpherson/tidyverse:4.0.4
```

rsession.conf is:
```
session-timeout-minutes=0
r-libs-user=/packages
```

rserver.conf is:
```
rsession-which-r=/usr/local/bin/R
www-address=127.0.0.1
www-port=8877
```

Most of my rmarkdowns fail at some point.   They load large amounts of data into tibbles, then do some ggplots, nothing special though the cells that usually fail are often longer running and use larger tibbles.
