### ISSUE TITLE
Opening Global Options takes ages

### ISSUE THREAD

**Issue by Thermi** [rstudio/rstudio#1889] opened 2017-12-29 22:53 UTC
Whenever I open the Global Options, Rstudio takes ages to open the dialog. It seems to take a long time in "Reading options...".
Processor load ist low while it does that, so it seems it is waiting for a lock or something. What's up with that?

**Comment by kevinushey** [comment] 2017-12-31 18:18
Can you also let us know what version of RStudio + what operating system you're running on? You might also try downloading and installing the preview release, as we have a number of fixes in there for issues of this form.

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by Thermi** [comment] 2018-01-01 20:18
It's 1.1.383 on Arch Linux.  1.1.408 takes a long time, too.

**Comment by kevinushey** [comment] 2018-01-02 16:39
Some other information that might be useful...

Can you try attaching a debugger to the `rsession` process? From the terminal, you can run:

    sudo gdb -p `pidof rsession`

(assuming you only have one `rsession` instance running and have the `pidof` utility installed; if not, just use `Sys.getpid()` from the R session to the the associated PID)

Then, run the following to ask GDB to log any generated output to a file:

    set logging file rsession-gdb.txt
    set logging on
    continue

Then, allow the process to continue running, then try opening the Global Options dialog. While the R session is 'stuck', try interrupting the process a few times, to see what the threads are up to (from the gdb REPL, use <kbd>Ctrl + C</kbd> to interrupt the process, and enter `bt` to print the backtrace).

After the Global Options dialog has successfully opened, you can detach the debugger and copy the `rsession-gdb.txt` file to e.g https://gist.github.com and provide us a link.

**Comment by Thermi** [comment] 2018-01-02 19:03
GDB debug output is attached. Disregard the fancy binary character lines they're because I got a fancy .gdbinit file.

Opening the global options afterwards (after they were already opened once) is instant.

[rsession-gdb.txt](https://github.com/rstudio/rstudio/files/1598404/rsession-gdb.txt)

**Comment by kevinushey** [comment] 2018-01-02 22:12
Strange -- it seems like the `rsession` process itself is mostly just waiting around as well.

Is the RStudio IDE itself responsive while waiting for the Global Options pane to open? (Can you open other panes, or type in the editor, or interact with the menu bars -- that sort of thing?)

You might also look at the request log, using <kbd>Ctrl + `</kbd>, after trying to open the Global Options dialog. In my case, I see:

![screen shot 2018-01-02 at 2 11 19 pm](https://user-images.githubusercontent.com/1976582/34502096-da59ca2a-efc6-11e7-83c1-84ea51c8c627.png)

The bars are short in my case as the requests finish almost instantly -- I'm curious if it's different on your side.

**Comment by Thermi** [comment] 2018-01-04 21:10
get_events is VERY long. when that happens. I need to scroll sideways several times to see it all.
An export of it is attached.
[get_event_export.txt](https://github.com/rstudio/rstudio/files/1604725/get_event_export.txt)

**Comment by kevinushey** [comment] 2018-01-11 20:25
Sorry for taking so long to get back to this. Unfortunately, I still don't have a great idea as to what could be going on even with the debug output :-/

The only thing that comes to mind is that we've seen on some occasions where RStudio could get hung up attempting to scan for fonts, and this can be very slow on some systems with a large number of fonts installed (or with a large number of auxiliary files installed in the font directories).

Any chance that (or something similar) could be true in your case?

**Comment by Thermi** [comment] 2018-01-11 20:48
Yes. I have a lot of fonts installed. A single package has installed 923 fonts, for example and there are a lot more.

**Comment by kevinushey** [comment] 2018-01-12 16:26
That could definitely be the culprit then. Which package(s) do you have installed that are providing these fonts, just for context? I'll see if I can replicate on my own machine.

**Comment by mamafanfan** [comment] 2018-01-26 15:40
exactly same problem as described by OP. (debian buster + rstudio 1.1.419). Here is my [rsession-gdb.txt ](https://gist.github.com/mamafanfan/bafe29643a024f8701695a34224ea638). Thanks in advance looking into this.

**Comment by josswright** [comment] 2018-08-29 06:39
Just to note that I'm also still seeing this in Arch Linux again, and yes with a significant number of fonts installed.

**Comment by kevinushey** [comment] 2018-08-31 20:34
It could be useful to see either a stack trace or even an strace during the time RStudio is hanging. Can we try and figure out what the `rstudio` and `rsession` processes are doing during this time?

**Comment by josswright** [comment] 2018-08-31 20:47
An `strace` definitely shows the rstudio process stepping through every font on my system -- I'd guess that it's going at a rate of about five a second:

```
openat(AT_FDCWD, "/usr/share/fonts/TTF/DejaVuMathTeXGyre.ttf", O_RDONLY) = 27
fcntl(27, F_SETFD, FD_CLOEXEC)          = 0
fstat(27, {st_mode=S_IFREG|0644, st_size=577708, ...}) = 0
mmap(NULL, 577708, PROT_READ, MAP_PRIVATE, 27, 0) = 0x7f1a72c11000
close(27)                               
```
... repeated for every font in the (admittedly rather large) collection of fonts on my system.

**Comment by cribari** [comment] 2018-09-11 11:27
I am also experiencing this problem. I run Arch + KDE PLasma and also Manjaro KDE, and in both I also have a large number of fonts installed, including the ttf-google-fonts-git Arch package.

**Comment by kupiqu** [comment] 2018-10-15 22:58
> I am also experiencing this problem. I run Arch + KDE PLasma and also Manjaro KDE, and in both I also have a large number of fonts installed, including the ttf-google-fonts-git Arch package.

Exactly the same in KDE neon with google fonts in $HOME/.fonts

Wondering if there a way to workaround this by hidding/masking that folder to RStudio, perhaps in a config file or so :/

**Comment by dangelob** [comment] 2018-11-03 20:29
I have the same issue here with fedora 29, R v3.5.1 and Rstudio 1.1.463

**Comment by kupiqu** [comment] 2018-11-05 17:51
> Do you have a large number of fonts installed? Have you tried the [preview release](https://www.rstudio.com/products/rstudio/download/preview/)?

Unfortunately, the issue is not fixed but translated from Opening Global Options to Rstudio startup. With current preview release and my current fonts it takes about 50 seconds for rstudio from launch to iddle, and the same takes about 8 seconds after I eliminate the folder $HOME/.fonts

**Comment by kevinushey** [comment] 2018-11-05 18:32
Thanks; it's definitely unreasonable for RStudio to take that long to launch. I'll see if there's something reasonable we can do to improve this.

**Comment by kevinushey** [comment] 2018-11-08 18:21
Should now be fixed in latest daily builds (the font cache is now built on a separate thread and should no longer impede startup)

**Closed by kevinushey** 2018-11-08 18:21 UTC

**Comment by kevinushey** [comment] 2018-11-09 15:35
Twenty minutes is definitely too long. I'm surprised -- just how many fonts are installed on your system? Is it common for users on Arch / other Linux distro's to install a kitchen sink's worth of fonts?

Either way, would you mind filing this as a separate issue?

**Comment by josswright** [comment] 2018-11-09 15:49
I do have, probably, an unusual number of fonts installed -- 3.4G in my /usr/share/fonts -- although I'm not sure how unusual I am in that. I suspect that anyone doing serious graphic design might have far more. For reference, `fc-list :mono | wc -l` lists 505 monospace fonts installed.

Having said that, I just checked with a relatively idle system and it took my Thinkpad X270 (Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz) just over five minutes before that CPU thread ended. Far less than 20 minutes, but it still seems quite a load for each startup of RStudio.

I'll open a new issue, although it's obviously far less urgent thanks to the recent fix. Thank you!

**Comment by spmorton** [comment] 2019-01-12 05:52
I too have this issue, just installed the latest release 1.1.463. This issue has been reported for over a year, and is kind of disappointing to see as Rstudio is a fantastic tool.

**Comment by kupiqu** [comment] 2019-01-12 09:05
> I too have this issue, just installed the latest release 1.1.463. This issue has been reported for over a year, and is kind of disappointing to see as Rstudio is a fantastic tool.

This does not happen in the preview version https://www.rstudio.com/products/rstudio/download/preview/

**Comment by spmorton** [comment] 2019-01-12 15:51
Why Java? its slow, its clunky its crap! write it fully POSIX compliant and it is just as portable.

**Comment by gtritchie** [comment] 2019-01-12 17:49
RStudio is shipped on Windows, Mac, Linux, and web (RStudio Server) from a single codebase. Much of it is Posix C++ (with alternatives as needed on Windows) and R. The bulk of the front-end UI is Javascript transpiled from Java using Gwt. RStudio doesn’t use the JVM. On web, the UI is hosted in your web browser, of course. On desktop it is Qt and Chromium (for 1.2).
