### ISSUE TITLE
Clicking "Home" from file tab when in "Home" directory terminates R session

### ISSUE THREAD

**Issue by life-droid** [rstudio/rstudio#7665] opened 2020-08-26 21:43 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      :  Windows 10
    R Version       :  4.0.2

### Steps to reproduce the problem
Launch RStudio
Navigate to the File tab of the Plots pane
If in "Home" directory, click home
If not in "Home" directory click home twice

 Note: If it doesn't occur straight away click Home again, eventually it crashes

### Describe the problem in detail
Clicking the "Home" button in the File tab of the "File/Plots/Packages/Help/Viewer" pane when already in the "Home" directory causes R to abort. A popup window then comes up saying R terminated unexpectedly.

### Describe the behavior you expected
I would expect the directory not to refresh but RStudio not to crash.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5132878/diagnostics-report.txt)

**Comment by kevinushey** [comment] 2020-08-26 22:43
Thank you for the bug report! I was able to reproduce with v1.3.1075 as well. Do you see this issue in the latest v1.4 daily builds? https://dailies.rstudio.com

I wasn't able to reproduce in v1.4; I wonder if this is some version of the crash described in https://github.com/rstudio/rstudio/pull/7641.

If so, that might make that PR a candidate for backporting to v1.3.

**Comment by life-droid** [comment] 2020-08-26 23:37
Hi Kevin,

I am not sure if it is related to #7641 but when I reloaded the UI via right-click after two reloads it crashed. See attached diagnostic report. I will try with the Daily Build shortly.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5133166/diagnostics-report.txt)

**Comment by life-droid** [comment] 2020-08-26 23:47
With the daily build the issue does not seem to be present.

System details
RStudio Edition : Desktop
RStudio Version : 1.4.747
OS Version      :  Windows 10
R Version       :  4.0.2

**Comment by mikebessuille** [comment] 2020-09-01 17:39
Closing as duplicate of #7641

**Closed** 2020-09-01 17:38 UTC
Labels: backlog, bug, files pane, regression

**Comment by gtritchie** [comment] 2020-09-01 18:11
Fixed in v1.3-apricot-nasturtium by #7671.

**Comment by mikebessuille** [comment] 2020-09-01 18:35
Per Gary, removing the duplicate label.  The fix was the same, but QA should test these symptoms independently from the other issue.

**Comment by R-Hannibal** [comment] 2020-09-03 21:04
Verified Fixed on: RStudio Version - 1.3.1087, R Version - 4.0.2, Windows 10 x64 - Desktop 

Verified through a comparison test between current stable (1.3.1073) and current preview. I was only enable to elicit the crash by spamming the home button with clicks, but it reliably reproduced the issue (eventually) on the old build. No amount of spam-clicking has produced the crash after the fix, marking 'verified'.
