### ISSUE TITLE
Emojis in code not correctly displayed

### ISSUE THREAD

**Issue by jemeurer** [rstudio/rstudio#15287] opened 2024-10-08 07:39 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  2024.04.2 Build 764
    OS Version      :  Windows 11 x64 (build 22631)
    R Version       : 4.4.1 (2024-06-14 ucrt)

### Steps to reproduce the problem
⏰ ❓   🔎
Insert these emojis in R code within RStudio and try to type something.

### Describe the problem in detail
Using any emoji in text as displayed above produces problems when working in the same line of code. If i set the text cursor behind the last element, it is displayed 2 to 3 spaces before and is somehow distroted (can't show this with a screenshot). I cannot reasonably work in the same line, instead I copy code outside RStudio and copy it back because my other text editors manage these kind of emojis regulalry. I simply loaded them into R and tried to renamed the objects/values but I took so much time because of the distoreted display and my workaround.

### Describe the behavior you expected
RStudio treating the emojis as regular text.
Any option to deal with emojis as own category would be great (like own reges category, although not feasible for you, I know). 

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-10-08 15:53
@jemeurer Thank you for raising this! This looks like a duplicate of #14900, which is the result of external issue https://github.com/ajaxorg/ace/issues/5431 in Ace, which RStudio inherits. I'm closing this as a duplicate, but I'll add your emoji example to it.

**Closed by ronblum** 2024-10-08 15:53 UTC
Labels: bug, new
