### ISSUE TITLE
Function 'descdist' works in RGui but does not provide plot in Posit / RStudio

### ISSUE THREAD

**Issue by yemoH** [rstudio/rstudio#14774] opened 2024-05-31 16:18 UTC
### System details
    RStudio Edition : Desktop
    RStudio Version : 2024.04.1 Build 748
    OS Version: Microsoft Windows 10 Pro - Version 10.0.19045 Build 19045
    R Version:  4.4.0

### Steps to reproduce the problem
I downloaded packages 'systemfonts' and 'ragg'. 
Selected 'Tools > Global Options' from Posit’s main menu bar. Clicked the 'Graphics' menu at the top of the interface and, under the Backend option, I selected 'AGG' . This change should ensure that Posit renders the previews of any plots with the ragg package.
Executed the following code:

`
library(fitdistrplus)
x <- c(37.50,46.79,48.30,46.04,43.40,39.25,38.49,49.51,40.38,36.98,40.00,
38.49,37.74,47.92,44.53,44.91,44.91,40.00,41.51,47.92,36.98,43.40,
42.26,41.89,38.87,43.02,39.25,40.38,42.64,36.98,44.15,44.91,43.40,
49.81,38.87,40.00,52.45,53.13,47.92,52.45,44.91,29.54,27.13,35.60,
45.34,43.37,54.15,42.77,42.88,44.26,27.14,39.31,24.80,16.62,30.30,
36.39,28.60,28.53,35.84,31.10,34.55,52.65,48.81,43.42,52.49,38.00,
38.65,34.54,37.70,38.11,43.05,29.95,32.48,24.63,35.33,41.34)
fitdistrplus::descdist(x, discrete = FALSE)
`
The numerical analysis is shown but the graph is not shown and Posit hangs, does not respond to actions.

By setting the Backend option to '(Default)' I'm able to plot the Cullen and Frey graph.

Full discussion on Posit Community with multiple people trying the reported bug. [https://forum.posit.co/t/function-descdist-works-in-rgui-but-not-in-rstudio/187342/4](url)

### Describe the problem in detail
Posit completes the numerical analysis, but doesn't plot a Cullen and Frey graph.
Posit 'hangs' with the processor at a high power usage.

### Describe the behavior you expected
I expect the viewer window to show a Cullen and Frey graph.

Note: I receive an error when I try to write an Diagnostics report.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report). 
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2024-06-03 16:22
R 4.4.0 has known plotting issues on WIndows. Try installing the R patch (this is an R issue, not an RStudio issue). See #14603 for more details.

**Comment by gtritchie** [comment] 2024-06-03 16:22
Closing as a duplicate of #14603.

**Closed by gtritchie** 2024-06-03 16:22 UTC
Labels: bug, new
