### ISSUE TITLE
Error Starting R

### ISSUE THREAD

**Issue by smkuhlani** [rstudio/rstudio#10151] opened 2021-11-29 07:50 UTC
![Error in R](https://user-images.githubusercontent.com/34687653/143827710-39d98abf-f595-431e-90d8-a4ec0b32b781.jpg)

### System details

    RStudio Edition :  Desktop
    RStudio Version : 4.1.2
    OS Version      : 
    R Version       : 4.1.2

### Describe the problem in detail
RE-installed R-Studio but cannot re-intall it. I get the Error meesag: Error Starting R. The R session failed to start. The R session process exited with code 10. The rest of the message is in the attached image.  
I am using windows 10.

### Describe the behavior you expected
Expeted the R stuio to display normally.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by smkuhlani** [comment] 2021-11-29 07:52
THIS IS THE FULL ERROR REPORT

## R Session Startup Failure Report

### RStudio Version

RStudio 2021.09.1+372, "Ghost Orchid" (8b9ced18, 2021-11-08) for Windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 10. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*C:/Users/Siyabusa/AppData/Local/RStudio/log/rsession-Siyabusa.log*

```
2021-11-28T19:36:57.625267Z [rsession-Siyabusa] ERROR system error 39 (The disk is full) [lock-file: C:/Users/Siyabusa/AppData/Local/RStudio/rs-14-migration.lock]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::LinkBasedFileLock::acquire(const class rstudio::core::FilePath &) src/cpp/core/file_lock/LinkBasedFileLock.cpp:447; CAUSED BY: system error 40 (Unknown error (40)); OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::`anonymous-namespace'::writeLockFile(const class rstudio::core::FilePath &) src/cpp/core/file_lock/LinkBasedFileLock.cpp:370; LOGGED FROM: class rstudio::core::ProgramStatus __cdecl rstudio::session::Options::read(int,char *const [],class std::basic_ostream<char,struct std::char_traits<char> > &) src/cpp/session/SessionOptions.cpp:234
2021-11-29T06:47:43.997371Z [rsession-Siyabusa] WARNING FileLock classes not yet initialized; please call 'FileLock::initialize()' and 'FileLock::cleanUp()' as appropriate; LOGGED FROM: bool __cdecl rstudio::core::FileLock::verifyInitialized(void) src/cpp/core/file_lock/FileLock.cpp:113
2021-11-29T06:47:44.017377Z [rsession-Siyabusa] ERROR system error 39 (The disk is full) [lock-file: C:/Users/Siyabusa/AppData/Local/RStudio/rs-14-migration.lock]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::LinkBasedFileLock::acquire(const class rstudio::core::FilePath &) src/cpp/core/file_lock/LinkBasedFileLock.cpp:447; CAUSED BY: system error 40 (Unknown error (40)); OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::`anonymous-namespace'::writeLockFile(const class rstudio::core::FilePath &) src/cpp/core/file_lock/LinkBasedFileLock.cpp:370; LOGGED FROM: class rstudio::core::ProgramStatus __cdecl rstudio::session::Options::read(int,char *const [],class std::basic_ostream<char,struct std::char_traits<char> > &) src/cpp/session/SessionOptions.cpp:234

```

**Comment by ronblum** [comment] 2021-11-29 14:22
@smkuhlani Thank you for raising this! Before we continue, the log file includes the following:
> ERROR system error 39 (The disk is full)

Can you confirm that there is adequate space on the disk drive?

**Comment by smkuhlani** [comment] 2021-11-29 19:07
Yes, I have adequate space 18Gig!

**Comment by kevinushey** [comment] 2021-11-29 20:05
> 2021-11-29T06:47:43.997371Z [rsession-Siyabusa] WARNING FileLock classes not yet initialized; please call 'FileLock::initialize()' and 'FileLock::cleanUp()' as appropriate; LOGGED FROM: bool __cdecl rstudio::core::FileLock::verifyInitialized(void) src/cpp/core/file_lock/FileLock.cpp:113

This looks like an RStudio internal error -- we're trying to use file locks before initializing. That's evidently happening here:

https://github.com/rstudio/rstudio/blob/bf77550cbeeabfc6ad92794d31038baa4c80c3c0/src/cpp/core/r_util/RUserData.cpp#L82-L85

And based on this output:

> 2021-11-28T19:36:57.625267Z [rsession-Siyabusa] ERROR system error 39 (The disk is full) [lock-file: C:/Users/Siyabusa/AppData/Local/RStudio/rs-14-migration.lock]; OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::LinkBasedFileLock::acquire(const class rstudio::core::FilePath &) src/cpp/core/file_lock/LinkBasedFileLock.cpp:447; CAUSED BY: system error 40 (Unknown error (40)); OCCURRED AT class rstudio::core::Error __cdecl rstudio::core::`anonymous-namespace'::writeLockFile(const class rstudio::core::FilePath &) src/cpp/core/file_lock/LinkBasedFileLock.cpp:370; LOGGED FROM: class rstudio::core::ProgramStatus __cdecl rstudio::session::Options::read(int,char *const [],class std::basic_ostream<char,struct std::char_traits<char> > &) src/cpp/session/SessionOptions.cpp:234

It looks like RStudio is trying to use link-based lockfiles, but those aren't functioning as expected. However, I was under the impression that we should be using advisory file locks by default on RStudio Desktop.

https://github.com/rstudio/rstudio/blob/bf77550cbeeabfc6ad92794d31038baa4c80c3c0/src/cpp/core/file_lock/FileLock.cpp#L42-L52

So the underlying issue is most likely that file locks are not being properly initialized when migrating user state in this scenario.

**Comment by kevinushey** [comment] 2021-11-29 20:07
I think the simplest fix here would be to remove the `verifyInitialized()` check and just allow `FileLock::initialize()` to be idempotent?

I'm guessing this issue could be reproduced if someone tried to install an older version of RStudio (maybe 1.2?) and then upgraded to the latest release.

**Comment by kevinushey** [comment] 2021-11-29 20:08
Marking as PT because IMHO the fix is "obvious" and if I'm correct this issue could potentially affect anyone upgrading from an older RStudio release.

**Comment by englianhu** [comment] 2021-12-16 16:25
> These links workable to me when startup blank page.
> 
> * Continuing the discussion from [GitHub SSH doesn't work](https://community.rstudio.com/t/github-ssh-doesnt-work/124418/2):
> * Continuing the discussion from [Linux penguin RStudio Startup Blank Page](https://community.rstudio.com/t/linux-rstudio-startup-blank-page/124168/2):
> * [Very common RStudio/git problem+solution: "error: unable to read askpass response from 'rpostback-askpass'" STAT545-UBC/Discussion#93 (comment)](https://github.com/STAT545-UBC/Discussion/issues/93#issuecomment-391606351)

source: https://github.com/rstudio/rstudio/issues/9854#issuecomment-995972092

**Comment by ronblum** [comment] 2022-01-04 22:21
I now (unfortunately) have a Windows 10 laptop which reproduces the error reliably, and it occurs even if I downgrade to 1.4.1717.

Note: I get error code -1073740791, though, but following steps to address this on Windows—chkdsk, sfc, etc.—don't make a difference.

**Comment by ronblum** [comment] 2022-01-05 15:21
I was able to recover by reseting the user state. I was then able to restore the previous state, and it continued to work.

@smkuhlani You might consider reseting RStudio Desktop's state using the instructions at https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State It worked when I backed up both Local data at `%localappdata%\RStudio` and Roaming data at `%appdata%\RStudio`, though it's possible that only one is necessary to back up an restore. The steps are:

1) Make sure RStudio Desktop is closed.
1) Back up the two directories by renaming them, as described in the article, for example `RStudio_BAK1`.
2) Start RStudio—this should now work.
3) Close RStudio
4) Back up the two new `RStudio` directories that were created using a new name, e.g. `RStudio_BAK2`.
5) Restore the previous preferences, etc., by renaming the two previously backed up directories—say, `RStudio_BAK1`—back to `RStudio`.
6) Restart RStudio, which should now continue to work.

**Comment by smkuhlani** [comment] 2022-01-05 17:42
Yes, it's now working well. Thank you!

**Comment by ronblum** [comment] 2022-01-12 19:57
I haven't been able to reproduce the problem since resetting the state. I'll leave this open for the moment to try to force the issue again with a previous release before claiming that the fix works.

**Comment by ronblum** [comment] 2022-01-21 22:03
I haven't been able to reproduce the original problem, both with builds before and after the fix. I'm closing this, since the fix isn't showing any side effects. Should the problem recur, we can always reopen, but I don't expect that to happen.

**Closed** 2022-01-21 22:03 UTC
Labels: bug, test
