### ISSUE TITLE
unexpected token '->' in multi-line string assignment with `->`

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/rstudio#8307] opened 2020-11-06 15:39 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.904, "Wax Begonia" (5a13c579, 2020-10-05) for Ubuntu Bionic
    OS Version      : Archlinux
    R Version       : 4.0.3

### Steps to reproduce the problem

Just type:

```R
'unexpected token ->
' -> x
```

### Describe the problem in detail

I get the visual error:

![unexpected_token](https://user-images.githubusercontent.com/19862384/98384566-d39c4c00-2045-11eb-85d7-f6287647607d.png)

### Describe the behavior you expected

I did not expect that snippet to trigger that error, as it is valid R code.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ramiromagno** [comment] 2020-11-06 15:42
If you are wondering why one would have a string on lhs of `->`, please see:

https://github.com/docopt/docopt.R#Usage

**Comment by ronblum** [comment] 2020-11-06 16:34
@ramiromagno Thank you for raising the issue. I can reproduce this in RStudio Desktop 1.4.1002 and 1.3.1093 on MacOS 11.0.1 Beta (20B5012d). However, I can't reproduce it in 1.2.5042, so I'm marking this as a regression, even though the issue was present in 1.3. We'll review this as we continue development of RStudio.

**Comment by kevinushey** [comment] 2020-11-10 00:45
Closed by https://github.com/rstudio/rstudio/pull/8309.

**Comment by valerie-rstudio** [comment] 2021-02-01 22:12
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1533
    OS Version      : mac OS 11.1
    R Version       : 4.0.3

Verified that typing `'unexpected token ->
' -> x` into an R script no longer causes error indicator to appear.

**Closed by valerie-rstudio** 2021-02-01 22:12 UTC
Labels: bug, diagnostics, regression, reproducible, test
