### ISSUE TITLE
When in debugger, any action in console changes active document

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#9918] opened 2021-10-05 12:46 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.12.0 Build 91
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

1. Add the following code to a file, save it, and source it:

    ```R
    a <- function() b()
    b <- function() c()
    c <- function() {
      x <- 10
      browser()
      x
    }
    a()
    ```

1. Open a new document.
1. Type 1 in the console and press enter.
2. The active tab moves away from the new document and back to the source file

### Describe the behavior you expected

Running code in the console shouldn't change the active tab

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hadley** [comment] 2021-10-05 17:15
I'm pretty sure this is a reasonable recent regression, and it's super annoying when debugging.

**Comment by jmcphers** [comment] 2021-10-05 17:58
The debugger does this intentionally in many cases; e.g. if you use a stepping command then it switches you back to the source window so you can see where the instruction pointer has moved. However, it shouldn't be doing it for _any_ statement you run.

**Comment by hadley** [comment] 2021-10-05 18:32
Ah makes sense!

**Comment by valerie-rstudio** [comment] 2021-10-07 20:55
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 2021.12.0-daily+110
    OS Version      : mac os 11.5.2
    R Version       : 4.1.1

Verified that in the case outlined above, the focus now remains on the new document and does not return to the source file after typing into the console and pressing enter.

**Comment by jcrodriguez1989** [comment] 2021-12-03 18:05
This is also happening in 
```
RStudio Workbench
2021.09.0 Build 351.pro6
© 2009-2021 RStudio, PBC
"Ghost Orchid" Release (50423e45, 2021-09-23) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
```
and it is really annoying.
Is there a way of disabling the Source Viewer forever?

Thanks,

**Comment by kevinushey** [comment] 2021-12-03 19:57
@jcrodriguez1989; the situation should be improved in the latest [daily builds](https://dailies.rstudio.com). Would you be willing to test and report back?

**Comment by avraam-inside** [comment] 2021-12-08 08:51
> @ jcrodriguez1989 ; ситуация должна быть улучшена в последних [ежедневных сборках](https://dailies.rstudio.com) . Вы бы хотели протестировать и доложить?

Gentlemens, I use a full-fledged docker layer roker/r studio:4.1.1, respectively, I would like to know when the official release will be released? Because using R with such a debugger is a very big pain(

**Comment by slipkid90515** [comment] 2022-04-08 21:19
Just got a new computer and have been experiencing this same issue. Is there a more formalized workaround besides the daily builds?

**Comment by kevinushey** [comment] 2022-04-11 17:05
This should already be resolved in the latest release (2022.02.1). If you're still having trouble, please file an issue with more details.

**Comment by jgutman** [comment] 2022-05-10 22:30
For re-testing:

1. Add the following code to a file, save it, and source it:

```
a <- function() b()
b <- function() c()
c <- function() {
  x <- 10
  browser()
  x
}
a()
```

2. While in the debugger, open a new document.

3. Type `1` in the console and press enter. The focus should stay on the new document.

4. Type `n` in the console and press enter. Since this is a debugger command, the focus should move back to the file containing the function being debugged.

**Comment by RWParsons** [comment] 2023-08-02 02:24
> For re-testing:
> 
> 1. Add the following code to a file, save it, and source it:
> 
> ```
> a <- function() b()
> b <- function() c()
> c <- function() {
>   x <- 10
>   browser()
>   x
> }
> a()
> ```
> 
> 2. While in the debugger, open a new document.
> 3. Type `1` in the console and press enter. The focus should stay on the new document.
> 4. Type `n` in the console and press enter. Since this is a debugger command, the focus should move back to the file containing the function being debugged.

I have getting this problem when using the above test. It returns me to the old document when doing step 3.

I'm using:
```
RStudio Workbench
2023.03.0 Build 386.pro1
© 2009-2023 RStudio, PBC
"Cherry Blossom" Release (5d34bebb, 2023-03-10) for Ubuntu Bionic
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
```

Is there any solution currently available or should I create a new issue?

**Comment by ronblum** [comment] 2024-03-13 20:16
Verified in RStudio Desktop 2024.04.0-daily+573 on MacOS 14.4 using the example above.

**Comment by kevinushey** [comment] 2024-08-14 22:52
It looks like this issue is still present in RStudio Workbench -- I was able to reproduce on an internal RStudio Pro instance.

RStudio 2024.04.2+764.pro1 "Chocolate Cosmos" Release (653611509504ac6640465e42d455d05dce98e1c4, 2024-06-05) for Ubuntu Jammy
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36, Quarto 1.4.555 (/usr/lib/rstudio-server/bin/quarto/bin/quarto)

**Comment by ronblum** [comment] 2024-08-26 18:29
Verified in
- Posit Workbench 2024.08.0+351.pro61 on Ubuntu 24 via Edge in Windows 11
- RStudio Desktop 2024.08.0+351 on Windows 11 (regression check)

**Closed by ronblum** 2024-08-26 18:29 UTC
Labels: bug, debugging, console
