### ISSUE TITLE
RStudio won't start in a Remote Desktop session

### ISSUE THREAD

**Issue by s-andrews** [rstudio/rstudio#6490] opened 2020-03-18 14:39 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Win10 v1809
    R Version       :  3.6.2

### Steps to reproduce the problem
Open an RDP session to the machine running RStudio

### Describe the problem in detail
RStudio doesn't start.  You get an error dialog saying: "LoadLibrary failed with error 87: The parameter is incorrect.

Starting the same RStudio on the same computer when sat at the console works just fine.
### Describe the behavior you expected
RStudio is able to start over RDP.

This problem has been reported for other programs which use OpenGL2 eg:

https://social.technet.microsoft.com/Forums/windowsserver/en-US/c8295ef8-3711-4576-9293-2c4965280165/opengl-and-remote-desktop?forum=winserverTS

I thought I could work round this by going into the settings for RStudio and opting to use the software renderer, however this doesn't solve the issue and the same error persists.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2020-03-18 16:22
Haven't tried to repro (don't have a config for this at the moment). Note to RStudio folks, "RDP" in this case is remote desktop protocol, not RStudio Desktop Pro. :-)

**Comment by gtritchie** [comment] 2020-03-18 16:38
Are you able to try RStudio 1.3 and see if that works? https://rstudio.com/products/rstudio/download/preview/

**Comment by gtritchie** [comment] 2020-03-18 16:47
I wasn't able to repro, able to connect and launch RStudio (both 1.2.5033 and 1.3.911). I am running Windows-10 1909 so maybe that's a factor.

**Comment by s-andrews** [comment] 2020-03-18 16:49
> Are you able to try RStudio 1.3 and see if that works? https://rstudio.com/products/rstudio/download/preview/

I tried the new version, but get the same error.

**Comment by s-andrews** [comment] 2020-03-18 16:50
> 
> 
> I wasn't able to repro, able to connect and launch RStudio (both 1.2.5033 and 1.3.911). I am running Windows-10 1909 so maybe that's a factor.

There may also be a hardware factor to this.  All of the reported cases I've seen have been using ATI graphics cards.  Some people have said that things were fixed if they renamed one of the ati driver files in System32, but I can't do that, and I suspect that if that does work then it's because it's just breaking all OpenGL.

**Comment by gtritchie** [comment] 2020-03-18 17:17
Ok. I have limited ability to try other scenarios (I'm remoting into my laptop which has NVIDIA and Intel integrated graphics, coming from Remote Desktop app on a Mac). Let's see if our QA people have access to additional hardware configs.

**Comment by kevinushey** [comment] 2020-03-18 18:55
Does explicitly forcing software rendering make a difference? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by s-andrews** [comment] 2020-03-19 09:08
> Does explicitly forcing software rendering make a difference? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

I don't think so.  I'd explicitly set it to use software rendering already.  I've also tried setting ```QMLSCENE_DEVICE=softwarecontext``` in my environment which also didn't help.  It's a little difficult to troubleshoot now as I'm not physically next to the machine any more as I'm having to work remotely.

**Comment by eslerm** [comment] 2020-03-30 23:56
I am having the same issue.

```
RStudio Edition : Desktop
RStudio Version : 1.2.5033
OS Version      : Win2019 v1809
R Version       : 3.6.3
GPU             : RX 570
```
Windows installed my GPUs driver. I attempted to install the latest version of Radeon Software ([Adrenalin 2020 Edition 20.3.1](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-20-3-1)) for Windows 10 (1809). The driver install fails with the same error RStudio gives: `LoadLibrary failed with error 87: The parameter is incorrect`.

Running Geek3d's GPU Caps Viewer to get OpenGL's version number also failed with the same error. Although,`C:\Windows\System32\opengl32.dll` does exist.

There is [a forum post about this issue on the RStudio Community posted 21 days ago](https://community.rstudio.com/t/error-opening-rstudio-loadlibrary-failed-with-error-87-the-parameter-is-incorrect/56005).

**Comment by eslerm** [comment] 2020-03-30 23:58
Fix was to remove/rename a file named `atig6pxx.dll`. In my case it was in the path ~`C:\Windows\System32\DriverStore\FileRepository\c0318724.inf_amd64_3e17...`

**Comment by s-andrews** [comment] 2020-03-31 08:15
I'd seen a similar fix reported but was reluctant to do anything inside System32.  I just tried and found that on this work machine, even with elevated privileges I can't change that file so I'm still stuck.

**Comment by s-andrews** [comment] 2020-03-31 08:38
I just came across this post:

https://superuser.com/questions/1516486/windows-10-loadlibrary-failed-with-error-87-on-remote-desktop-session

..which is exactly the same thing.  They said that they cured it by updating to the latest ATI drivers.  I've asked our IT to update my machine so I'll see if that fixes it.

**Comment by s-andrews** [comment] 2020-03-31 10:47
I tried updating the ATI drivers, but got the same error as before.  I got our IT to remove the ```atig6pxx.dll``` file and now RStudio starts and works over RDesktop!

**Comment by jmcphers** [comment] 2020-04-30 22:24
Closing since this wound up being an external driver issue. Thanks for keeping us in the loop!

**Closed by jmcphers** 2020-04-30 22:24 UTC
Labels: repro needed, windows

**Comment by sneumann** [comment] 2020-10-05 08:22
Hi, we are experiencing the same, and haven't tried the workaround yet. 
While it may not an Rstudio issue, is there any way to get towards the underlying cause ? Is rstudio using any 3rd party components (e.g. framework, embedded browser) that could cause the failure, and maybe some different initialisation could fix the issue ? Yours, Steffen

**Comment by ck37** [comment] 2020-10-30 16:06
I can confirm the same issue while connected via Windows remote desktop and opening the latest version of RStudio (1.3.1093). I'm using windows 10 pro and have an AMD FirePro V4900 graphics adapter. I resolved it by renaming "atig6pxx.dll" in Windows\System32 to "__atig6pxx.dll".

**Comment by bobydo** [comment] 2020-11-01 13:17
Hi, we are experiencing the same, and haven't tried the workaround yet.
Please found underlying issue and provide a config for RStudio? Or include extra library?

**Comment by jqiriazi** [comment] 2021-08-16 19:34
Confirming that renaming `atig6pxx.dll` worked.
RStudio v1.4.1717
Graphics Card: Radeon Pro WX 3100

**Comment by pboesu** [comment] 2021-09-09 09:36
A slightly kludgy workaround for situations where a driver update / dll renaming is not possible is to have a Windows batch script that starts RStudio with a delay, so RStudio can start while the remote client is disconnected.

i.e. save sth like the following as a `.bat` script  

```
TIMEOUT 10
"C:\path\to\rstudio.exe"
```

1. Execute the script
2. log out of the Remote Desktop session *before the timeout expires*
3. RStudio should start on the host
4. log in again to use RStudio.


```
RStudio Edition : Desktop
RStudio Version :  1.2.1335
OS Version      : Win10 Pro 20H2
R Version       :  3.6.2
```

**Comment by JamesTruscott** [comment] 2022-06-27 10:29
The time-delay batch script just saved me a 5 mile round trip to work. Thanks for the idea!

**Comment by ublzesc** [comment] 2022-07-06 16:33
It is a fantastic idea! I cannot run executables on my work machine but translating it to R, and doing it on the console did the trick:
Sys.sleep(10)
shell.exec("RStudio")
