### ISSUE TITLE
Changing extension on save prompts twice

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2221] opened 2018-02-17 14:56 UTC
1. Open new file in script edit
2. Press Cmd + S
3. Rename to "myfile.md"
4.  <img width="545" alt="screen shot 2018-02-17 at 8 55 31 am" src="https://user-images.githubusercontent.com/4196/36342194-51a1264c-13c0-11e8-95d1-bf28c3f86b08.png">
5.  <img width="436" alt="screen shot 2018-02-17 at 8 55 45 am" src="https://user-images.githubusercontent.com/4196/36342196-5b2f35d2-13c0-11e8-8ba7-6a067e30f40a.png">

(I realise these are coming from two different places, and I can avoid the problem by changing the file type, but I often forget and find this small friction annoying)

**Comment by ronblum** [comment] 2018-02-19 16:19
Reproduced in 1.1.423, but it looks like the problem is fixed in 1.2.350—only the prompt with the yellow triangle pops up.

**Comment by jmcphers** [comment] 2018-02-22 05:28
Closing since it's fixed in 1.2. @hadley please let us know if you still see it after you move to 1.2!

**Closed by jmcphers** 2018-02-22 05:28 UTC
Labels: bug
