### ISSUE TITLE
Autocomplete picks wrong list level when subsetting multilevel list and deleting backwards

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4447] opened 2019-03-14 13:03 UTC
**Steps to reproduce:**
* Create some multi-level list object, e.g.
```r
l = list( a = list(q = list(z=1, x=2), w = list(ww=list(www=1), wwww=0)), b = list(r=10) )
```
* Type the list object name in the console, start subsetting it with `$`, get to a second or deeper-level object, e.g.
```r
l$a$q$
```
* Press tab to show drop-down autocomplete menu.
* Start deleting until reaching the first level, e.g. `l$`.
* Optionally, press tab again once the level is reached.

**Expected behavior:** should show the subsettable options available under the level it’s currently under.

**Actual behavior:** keeps showing the options available under the level on which tab was first pressed.

**Reproducible:** most of the times.

**Setup:** R 3.5.1, RStudio 1.2.1322, running on windows 10.

**Comment by kevinushey** [comment] 2019-03-14 16:02
Thanks for the bug report! I can reproduce this; it looks like this is a long-standing issue as I can reproduce back in RStudio v1.0 as well.

**Comment by david-cortes** [comment] 2021-02-08 11:24
Still reproducible in the latest daily build.

**Comment by david-cortes** [comment] 2021-02-22 15:24
@ronblum : the bot somehow didn't receive the last message.

**Comment by mikebessuille** [comment] 2021-02-22 21:44
We had a look at this, and it's awfully specific.  Realistically we will not get to this in the next few releases, so we are closing this, to ensure we can devote efforts towards issues that have larger impact.

**Closed by mikebessuille** 2021-02-22 21:44 UTC
Labels: autocompletion, bug
