### ISSUE TITLE
[FR] Find and replace in whole project

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/rstudio#2582] opened 2018-04-04 05:16 UTC
From time to time I'm missing the ability to rename something not only in one file but the whole project. Are there plans to implement such a feature?

**Comment by ronblum** [comment] 2018-04-04 16:30
@fabiangehring Are you looking for something similar to #2066, but defined by project instead of directory tree?

**Comment by fabiangehring** [comment] 2018-04-28 22:07
Yes, exactly. Wasn‘t aware of this similar other issue.

**Comment by gorkang** [comment] 2018-08-30 12:29
Should close this issue as it is a duplicate of  #2066 ?

**Comment by kevinushey** [comment] 2018-08-30 16:35
Yes, let's -- thanks.

**Closed by kevinushey** 2018-08-30 16:35 UTC
Labels: enhancement
