### ISSUE TITLE
Blank window in Fedora 35

### ISSUE THREAD

**Issue by opmc2** [rstudio/rstudio#10072] opened 2021-11-11 17:43 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.1+372 "Ghost Orchid" Release (2021-11-08) for CentOS 8
    OS Version      : Fedora 35
    R Version       : 4.1.1 (2021-08-10) -- "Kick Things"

### Steps to reproduce the problem
Launch RStudio (from cmd line or using icon).
### Describe the problem in detail
Launching RStudio (from cmd line or using icon) results in an empty and unresponsive window opening. Launching from the cmd line with `--no-sandbox` option works fine.
### Describe the behavior you expected
RStudio to display usual subwindows in open window and to respond.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2021-11-11 19:51
My understanding is that it's a glibc issue. See https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468 for an example of this issue filed for Ubuntu.

**Comment by opmc2** [comment] 2021-11-12 09:33
Thanks. This thread also seems to be about the same issue: https://github.com/rstudio/rstudio/issues/9854

**Comment by ronblum** [comment] 2021-11-12 14:49
@opmc2 Thank you for raising this! Yes, this appears to be a duplicate of #9854. Note that there some suggestions for temporary workarounds, although I don't know if they apply to Fedora.

**Closed by ronblum** 2021-11-12 14:49 UTC
