### ISSUE TITLE
R Console continues to run after closing a Plumber API or Shiny App

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#8176] opened 2020-10-23 18:57 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.4.999 (MacOS open Source build, c3bd072b)
    OS Version      : Mac OS 11 beta (Big Sur)
    R Version       : 4.0.3

### Steps to reproduce the problem
1. Open a new Plumber API file.
2. Select the Run API button in the Source Editor.
3. Close the Plumber API dialogue (NOT the file in the Source Editor).

### Describe the problem in detail
The 'STOP' icon in the R console continues to display, suggesting that the console is still running, and the 'Run API' button in the source editor becomes 'Reload API'.

![PlumberAPIissue](https://user-images.githubusercontent.com/62304541/97041317-00743d80-1535-11eb-8223-333c455dbc86.jpg)

### Describe the behavior you expected
Testing on `1.4.967`, after closing the API dialogue, no STOP button is displayed in the console and the source editor button stays 'Run API'. I would expect this same behavior from the QT build.

### Notes

- This issue appears to be more widespread than just effdecting Plumber API files. Similar behavior occurs with a Shiny Web Application file (Run App > Close Dialogue > Stop button stays on the console, Run App becomes Reload App).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2020-10-24 00:10
Nice find @R-Hannibal! I _think_ this is caused by the `unload` event not firing properly in Qt 5.15.1 (needs investigation); we rely on it to signal to the main window that the satellite has been closed and that the Shiny application should be stopped.

**Comment by gtritchie** [comment] 2020-10-27 20:25
I'll grab this one to investigate for the Qt 5.15 update.

**Comment by gtritchie** [comment] 2020-10-29 16:13
Resolving as out-of-scope now that we're not upgrading to 5.15 for RStudio 1.4.

**Closed by gtritchie** 2020-10-29 16:13 UTC
Labels: backlog, macos, out of scope, qtwebengine
