### ISSUE TITLE
Add Hotkey to invoke View() on highlighted area

### ISSUE THREAD

**Issue by TomWien** [rstudio/rstudio#11070] opened 2022-04-26 19:31 UTC
[proposed enhancement] I spend a lot of time isolating tibbles and data frame names and typing <name> %>% View(), or interrupting portions of a pipeline to add in a View() statement to diagnose what is happening.  It would be really useful to be able to just highlight the object name (or code block that returns an object) and press a hotkey to invoke View().

**Comment by jmcphers** [comment] 2022-04-26 23:22
Duplicate of: https://github.com/rstudio/rstudio/issues/3320

Until this gets some attention from the dev team, though, I bet you'll find this addin useful: https://github.com/MilesMcBain/breakerofchains

**Closed by jmcphers** 2022-04-26 23:22 UTC

**Comment by dracodoc** [comment] 2022-04-26 23:36
You can also use [my addin](https://github.com/dracodoc/mischelper), assign a hot key to `view data frame`, which basically do what you want, you just need to select the expression you want (not just name, any expression or code block is fine).

**Comment by TomWien** [comment] 2022-04-27 13:36
@jmcphers @dracodoc Thanks for the leads to the add-ins.  Looked for a previous enhancement request and did not find 3320 - sorry, I always look before shooting.  Thanks for the quick replies.
