### ISSUE TITLE
Visual editor incorrectly tries to escape square brackets

### ISSUE THREAD

**Issue by GabriellaS-K** [rstudio/rstudio#10131] opened 2021-11-24 14:29 UTC
### System details

    RStudio Edition : Desktop 
    RStudio Version :2021.09.1 Build 372
    OS Version      :  Mac OS Monterey 12.0.1 (21A559)
    R Version       :  4.1.1 (2021-08-10) -- "Kick Things"

### Steps to reproduce the problem

Create an R Markdown file with this:

```markdown
We want square brackets to be retained, in this confidence interval: [-0.49, -0.32]
```

Flip to the visual editor and back again...

Now, it looks like this:
```markdown
We want square brackets to be retained, in this confidence interval: \[-0.49, -0.32\]
```

### Describe the problem in detail

With the former, we get the desired output when building to HTML:
<img width="535" alt="Screenshot 2021-11-24 at 14 27 22" src="https://user-images.githubusercontent.com/32248649/143256793-138c048c-7c1d-4ebd-8734-0e8627fee8a2.png">

But after we've flipped back and forth to the visual editor we get this:

<img width="454" alt="Screenshot 2021-11-24 at 14 27 34" src="https://user-images.githubusercontent.com/32248649/143256794-92669aa1-5182-48af-a660-bfa4c5a93fa0.png">

:(

### Describe the behavior you expected

We want the square brackets to be left untouched :)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-11-24 16:32
@GabriellaS-K Thank you for raising this! I can reproduce this in RStudio 2021.09.1+372 on MacOS 12.1. 

I'm guessing that this is related to #10075, which also affects brackets, but that's tied to citations. So in case there's a reason for using the backslashes here, or the problem is in a different part of the code, I'm leaving this open instead of closing as a duplicate.

**Comment by jjallaire** [comment] 2021-12-02 17:40
Addressed with https://github.com/rstudio/rstudio/commit/aa08d43d76294920c98052538bb7d4b62dfcde28

**Closed** 2021-12-07 15:31 UTC
Labels: bug, visual markdown
