### ISSUE TITLE
Rfast::Dist() causes Rstudio-Tab call of doc to freeze the app until kill

### ISSUE THREAD

**Issue by Melkiades** [rstudio/rstudio#6693] opened 2020-04-19 14:30 UTC
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.5033
    OS Version      :  Linux LTS 18.04
    R Version       : 3.6.2 (2019-12-12)

### Steps to reproduce the problem
It is enough to run the following: library(Rfast); library(tidyverse) and then take a function like mutate_all() and try to tab-complete it and to press again tab to call the function variable documentation and Rstudio freezes until killing. This is somehow connected with Rstudio because just from terminal it is not freezing the session.

### Describe the problem in detail
The problem of course it is also related to the package Rfast and I filed an issue there about it but, as it works for normal r sessions, they pointed out how this problem is related to Rstudio specifically. [Here](https://github.com/RfastOfficial/Rfast/issues/19) is the other issue.
The freezing itself is like the console is busy in background without any red stop sign. you can still click on everything but it is like the system is locked in a background infinite process. 

### Describe the behavior you expected
It should just show the tab completion of the tidyverse functions w/o any freezing.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-04-21 17:38
@Melkiades Thank you for raising the issue! I can reproduce this in 1.3 (currently in preview) as well. We'll review this as we continue development of RStudio.

**Comment by gabrielodom** [comment] 2020-10-14 17:19
I am having this issue as well for RStudio v 1.3.1073.

Session info:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Rfast_2.0.1        RcppZiggurat_0.1.5 Rcpp_1.0.5         forcats_0.5.0      stringr_1.4.0      dplyr_1.0.2       
 [7] purrr_0.3.4        readr_1.3.1        tidyr_1.1.2        tibble_3.0.3       ggplot2_3.3.2      tidyverse_1.3.0   

loaded via a namespace (and not attached):
 [1] cellranger_1.1.0 pillar_1.4.6     compiler_4.0.2   dbplyr_1.4.4     tools_4.0.2      jsonlite_1.7.1  
 [7] lubridate_1.7.9  lifecycle_0.2.0  gtable_0.3.0     pkgconfig_2.0.3  rlang_0.4.7      reprex_0.3.0    
[13] cli_2.0.2        DBI_1.1.0        rstudioapi_0.11  parallel_4.0.2   haven_2.3.1      withr_2.2.0     
[19] xml2_1.3.2       httr_1.4.2       fs_1.5.0         generics_0.0.2   vctrs_0.3.4      hms_0.5.3       
[25] grid_4.0.2       tidyselect_1.1.0 glue_1.4.2       R6_2.4.1         fansi_0.4.1      readxl_1.3.1    
[31] modelr_0.1.8     blob_1.2.1       magrittr_1.5     backports_1.1.9  scales_1.1.1     ellipsis_0.3.1  
[37] MASS_7.3-53      rvest_0.3.6      assertthat_0.2.1 colorspace_1.4-1 stringi_1.5.3    munsell_0.5.0   
[43] broom_0.7.0      crayon_1.3.4    
```

**Comment by Melkiades** [comment] 2021-02-05 11:23
I just do not load Rfast anymore, but the freezing is still happening if I do

**Comment by kevinushey** [comment] 2021-02-05 19:11
I think this is actually a duplicate of https://github.com/rstudio/rstudio/issues/6645, and may need to be fixed in `Rfast` itself.

**Closed by kevinushey** 2021-02-05 19:11 UTC
Labels: autocompletion, bug, console
