### ISSUE TITLE
R CMD build ("Install and Restart") fails

### ISSUE THREAD

**Issue by goranbrostrom** [rstudio/rstudio#1625] opened 2017-10-18 13:07 UTC
I'm building a package in RStudio with devtools. When I click on "Install and Restart",
R CMD INSTALL --no-multiarch --with-keep.source eha
is run and ends with
Warning in file(con, "w") :
cannot open file '/usr/local/lib/R/site-library/eha/doc/index.html': No such file or directory
Error in file(con, "w") : cannot open the connection
ERROR: installing vignettes failed

Running devtools::install(build_vignettes = TRUE) works ok, because it eventually runs
...CMD INSTALL .../eha_2.5.0.9000.tar.gz

The same events occur at the command line (unix prompt).

R CMD INSTALL should be applied to the tarball, not to a directory, right?

This is an RStudio issue (according to Hadley). RStudio  1.1.383, latest versions of everything.

**Comment by kevinushey** [comment] 2017-10-18 16:13
This is actually intentional -- we directly build and install from the directory to ensure faster iteration times.

Does your package contain a custom configure / cleanup script or something similar that affects how your package is built and installed?

**Comment by goranbrostrom** [comment] 2017-10-18 17:13
Must admit that I am slightly confused: It worked nicely on my home computer, both in RStudio and on the command line! The same environments (but ubuntu 16.04 vs. 17.04), pulled from github (goranbrostrom/eha). The same .Rbulidignore,  etc.

**Comment by goranbrostrom** [comment] 2017-10-18 17:51
I found a difference: On my work machine a directory 'build' was present, with a file 'vignettes.rds' inside (no idea where it came from).  I removed it, and all is fine. But where did 'build' come from?

**Comment by kevinushey** [comment] 2017-10-23 21:44
If I recall correctly, the `build` directory is used during package build / install for vignettes and is normally created by `R CMD build`. It's normally supposed to be only part of the built tarball, though -- it shouldn't show up in your original package sources.

**Comment by mhofert** [comment] 2019-06-05 14:10
1) Get source code:
    cd ~/Downloads
    wget https://cran.r-project.org/src/contrib/qrmtools_0.0-10.tar.gz
    tar -xzf qrmtools_0.0-10.tar.gz # unpack
    rm qrmtools_0.0-10.tar.gz
2) Open RStudio
3) File -> Open Project... -> choose unpacked folder 'qrmtools' in ~/Downloads
4) Build -> Build Source Package
5) Build -> Check Package
6) Build -> Install and Restart. => Fails with:

    ** installing vignettes
    Warning in file(con, "w") :
      cannot open file '/usr/local/R/library/00LOCK-qrmtools/00new/qrmtools/doc/index.html': No such file or directory
    Error in file(con, "w") : cannot open the connection
    ERROR: installing vignettes failed
    * removing ‘/usr/local/R/library/qrmtools’
    * restoring previous ‘/usr/local/R/library/qrmtools’

    Exited with status 1.

The executing command shown is `R CMD INSTALL --no-multiarch --with-keep.source qrmtools` which also fails from the Terminal. However, replacing 'qrmtools' by the tarball 'qrmtools_0.0-10.tar.gz' works (and is also in line with `R CMD build`, `R CMD check --as-cran`, `R CMD install` for installing packages). Note that this is under R-3.6.0 on macOS 10.14.5 (but I neither of that should matter). The question is: Why do you not install from the tarball per default? (which would also leave no trace in 'qrmtools' [I see `qrmtools.Rproj`, for example]). 

Note:
- This may be related: https://github.com/r-lib/devtools/issues/1625 
- I work with Emacs & ESS for many years, but I'm a complete newbie in RStudio. If the above workflow is wrong for installing a package from source, please let me know (as I frequently get asked by students and in the future want to share the "correct" way of doing things).

**Comment by jmcphers** [comment] 2020-05-28 16:27
We never figured out what was going on here or got other reports in over a year, so closing.

**Closed by jmcphers** 2020-05-28 16:27 UTC
Labels: repro needed

**Comment by zekrom-vale** [comment] 2021-11-23 17:49
In my case, I had code outside of functions and it always errored out with the same error:
```
i Updating RCollect documentation
i Loading RCollect
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
```

It fails if I build or run `devtools::document()`.  The issue is that this is the first package I have created and I had no clue that was the issue.  I really only want the documentation feature as other things are breaking like having to use require every time I define a function.  (I have no clue the proper way to do this...).

**Comment by zekrom-vale** [comment] 2021-11-23 18:09
Never mind found out that roxygen2 changes the DESCRIPTION so you need to use `@import`.

**Comment by lofung** [comment] 2022-03-22 05:14
i find it funny when the R community closing things they have not figured out but buggered people all over the years.

similar problem in 2022.

**Comment by kevinushey** [comment] 2022-03-22 17:07
> i find it funny when the R community closing things they have not figured out but buggered people all over the years.

Can you share a reproducible example, or some other information that might assist us in understanding what the issue is, and how we might fix it?

**Comment by pepijn-devries** [comment] 2024-07-31 23:58
> If I recall correctly, the `build` directory is used during package build / install for vignettes and is normally created by `R CMD build`. It's normally supposed to be only part of the built tarball, though -- it shouldn't show up in your original package sources.

Just had the same problem. Deleting the obsolete 'build' folder from my project solved the issue. Took me I while to figure this out. Thanks for reporting here.
