### ISSUE TITLE
Pop-out Terminal tab as a separate window

### ISSUE THREAD

**Issue by zx8754** [rstudio/rstudio#6910] opened 2020-05-19 06:13 UTC
Just like in **Source** panel files tabs can be popped out as a separate window, can we have **Terminal** to pop out, too?

Sometimes I work locally and remotely via ssh concurrently, and while working locally on **Console** I'd like to keep an eye on the process of scripts running on **Terminal**.

**Comment by lrnv** [comment] 2020-05-19 14:26
This has been asked a lot. See #2833

**Comment by gtritchie** [comment] 2020-05-19 16:13
I'm going to resolve this as a duplicate of #2833; that issue is tracking the more general request for popping out any pane types.

**Closed by gtritchie** 2020-05-19 16:13 UTC
Labels: duplicate
