### ISSUE TITLE
Filtering and sorting doesn't work for columns great than 50 in the data viewer

### ISSUE THREAD

**Issue by docal555** [rstudio/rstudio#13328] opened 2023-07-06 18:47 UTC
Loaded a dataframe with 89 columns. When you skip past the first 50 columns nothing works. Cannot filter, cannot sort. If you have a dataframe with e.g. 89 columns and you skip, numbering starts with 40. Like counting from 1 to 89, once you reach 50 you have to resume at 40. This is kind of frustrating. Past the first 50 columns everythings seems to be at random. Random sorting, random filtering

### System details

    RStudio Edition : Version 2023.06.1+438 (2023.06.1+438)
    RStudio Version : 
    OS Version      : 13.4.1 (22F82)
    R Version       : R version 4.3.1

### Steps to reproduce the problem
Load a dataframe with more than 50 columns, try to sort or filter. Nothing works

### Describe the problem in detail
Load a dataframe with more than 50 columns, try to sort or filter. Nothing works.

### Describe the behavior you expected
Skip to 51 and the column starts with 51 and not 40. Let´s me filter or sort. Maybe concentrate more on R again and not on Python integration

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-07-06 19:22
There are three issues here:

1) Filtering past 50 columns: I can reproduce this—filtering doesn't work in RStudio Desktop 2023.06.1+524. This worked correctly in version 2023.03.2+454.
2) Sorting past 50 columns: I cannot reproduce this, as sorting works correctly for me. Can you provide a sample dataset with which this is happening?
3) Numbering of the last frame: This is addressed in issue #13301.

Note: Tested in part using a dataset of random numbers:
`df <- as.data.frame(matrix(runif(n=3290, min=1, max=20), nrow=10))`

Triage: I recommend this for Desert Sunflower, but we should consider this for the next patch of 2023.06.2.

**Comment by docal555** [comment] 2023-07-07 03:47
<img width="709" alt="Bildschirmfoto 2023-07-07 um 05 44 07" src="https://github.com/rstudio/rstudio/assets/45333547/1d889bb8-5052-4f7b-bb82-5bd8e65514cc">

Last column "FB_ACQ_Punkte" is sorted.

As soon as I skip past 50 columns the behavior becomes somehow random.

**Comment by kevinushey** [comment] 2023-07-07 15:37
IMHO we should fix this for the next patch.

**Comment by ronblum** [comment] 2023-07-07 19:23
Aha! @docal555 I see what you mean—I thought you mean that sorting isn't working at all. It's that after sorting, traversing to the next 50 columns, etc., restores the original order of the data frame instead of keeping the most recent sort. Is that correct? Rather than random, per se. If so, this is another example of "higher maths" behavior 😆 in the Data Viewer, rather than a new bug. I'll open a separate issue for it.

Checked with
```df <- as.data.frame(matrix(10:1, nrow=10, ncol = 190))```
(much easier to see than with the random matrix I used above.)

Initial view:
<img width="304" alt="initial" src="https://github.com/rstudio/rstudio/assets/31009952/be1d1934-db46-4e4b-b31c-360793c16556">

Sorted by column 1 (or any column, since they're all the same):
<img width="306" alt="sorted" src="https://github.com/rstudio/rstudio/assets/31009952/bb1a946e-0d45-4d89-9191-78a9ee9377d6">

After going to the next 50 columns:
<img width="347" alt="next_page" src="https://github.com/rstudio/rstudio/assets/31009952/06cedfb0-c6ff-4ded-8aa5-eb859b690312">

**Comment by kevinushey** [comment] 2023-07-07 20:51
I think the issue is also that the sorting is incorrect after you've started paginating? So if you scroll to the next 50 columns, and then try to click and sort by a column, the values aren't actually sorted correctly.

**Comment by docal555** [comment] 2023-07-08 04:52
Yes, as Kevin said, once you skip to 50+ sorting does not work and filtering also not. And again, skipping to 50+ and then the column numbering starts at 40 (with my dataframe with 89 columns) is "annoying"

**Comment by docal555** [comment] 2023-07-08 05:03
I have tried Version 2023.09.0-daily+203 (2023.09.0-daily+203) now. Once you skip past 50 it is still a complete "mess". Filtering does not work. It shows the filter, but when e.g. selecting a numeric column the filter shows as selection "TRUE/FALSE". And then it becomes completely random (see screenshot). You start having 2 filter fields, and other columns do not have a filter field at all
<img width="727" alt="Bildschirmfoto 2023-07-08 um 07 02 17" src="https://github.com/rstudio/rstudio/assets/45333547/7e1284cc-03f6-404a-afd1-8886037a1830">

**Comment by docal555** [comment] 2023-07-08 05:12
btw. I installed not the official Version 2023.06.1+524 (2023.06.1+524) - nothing works there either. No proper sorting and also no proper filtering.

**Comment by docal555** [comment] 2023-07-08 05:28
Switched "back" to Version 2023.03.2+454 (2023.03.2+454). There is still this annoying thing when you skip to 51 that it "resets" and starts at 40 (with a dataframe with 89 columns). But at least the other stuff seems (!!!) to work. I think this is not a marginal issue what RStudio has here. At least I start questioning the correctness of the results when using RStudio and it might not only be me that this let´s me look into using VS Code also for R.

**Comment by ronblum** [comment] 2023-07-10 13:21
@kevinushey I'm looking at the example of the QA notes at #13339, as well as my notes above which I had filed as #13338. As far as I can tell, in these examples, the sorting is lost when moving to the next page. But if a new column is sorted, it will get sorted correctly. However, the screenshots of @docal555's data show that while the column is shown as sorted (by the little blow arrow), the data isn't getting sorted properly. Is there something different about our test data and @docal555's data, am I somehow lucking out and not hitting the "improper sort" bug, or am I totally missing something?

**Comment by ronblum** [comment] 2023-07-10 19:50
QA: Use @kevinushey's example, which reproduces consistently, as my original doesn't capture it.

```
.rs.writeUiPref("data_viewer_max_columns", 15L)
data <- replicate(100, 0:9, simplify = FALSE)
for (i in seq_along(data)) {
  data[[i]] <- (data[[i]] + i) %% 10
}

names(data) <- paste0("V", 1:100)
df <- as.data.frame(data)
View(df)
```

**Comment by francisbarton** [comment] 2023-07-12 15:38
Linked to issue #6147 I think

**Comment by jonvanausdeln** [comment] 2023-07-12 23:53
Verified on [2023.09.0-daily+215](https://dailies.rstudio.com/version/2023.09.0-daily+215)
Windows 11

Sorting and Filtering work when viewing columns past the 50 column window.  

Note - this does not fix #6147 (nor the other related/duplicate issues)

@docal555 , if you would like to try the fix its available in the daily build mentioned above. But note, these builds are for testing only and not production use.  This fix will also be included in the next path for 2023.06

**Closed by jonvanausdeln** 2023-07-12 23:53 UTC
Labels: bug, regression, viewer pane

**Comment by singing-scientist** [comment] 2023-10-16 05:14
Identical problem for me.

### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1+524
    OS Version      : 13.6 (22G120)
    R Version       : 4.3.1 (2023-06-16)

### Steps to reproduce the problem

(1) load a tibble with over 50 columns
(2) click '>>' to go to the last columns
(3) sort by any column with multiple values
(4) observe nonsorted values

### Describe the problem in detail

When viewing beyond column 50 and sorting by column value, view fails to sort.

![Screenshot 2023-10-16 at 12 54 40 PM](https://github.com/rstudio/rstudio/assets/12587124/15a8be5b-fa32-4cb5-b857-727b45a13c70)

### Describe the behavior you expected

Values should have sorted, with identical values clustered together in the column.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by singing-scientist** [comment] 2023-10-18 03:47
Thanks a ton @ronblum!

**Comment by ronblum** [comment] 2023-10-18 15:26
My pleasure! Let us know if you run into any issues.
