### ISSUE TITLE
Cursor switches to typeover, gets stuck, glitches around

### ISSUE THREAD

**Issue by petyaracz** [rstudio/rstudio#5107] opened 2019-07-16 14:16 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macos 10.14.4 
    R Version       : 3.6.0

### Steps to reproduce the problem

This problem is completely baffling to me and I'm unable to retrace the steps apart from 
- you have to keep editing a script for a while (but "while" varies a lot)
- you have to keep moving the cursor around (maybe!)

The only way to stop this is to restart RStudio. I have now seen this with two different OS versions on two different machines with macos.

### Describe the problem in detail

The cursor starts glitching. Behaviours include:

- selecting everything up to $ (so that the next thing you type replaces the line)
- overwriting text instead of inserting
- cursor disappearing

### Describe the behavior you expected

- typing along

**Comment by ronblum** [comment] 2019-07-16 14:52
@petyaracz Thank you for raising the issue. I'm trying to reproduce it. Do you have a sense for the what was the shortest amount of time it took for the issue to occur? I want to make sure I'm allowing a sufficient amount of time when testing. Thanks!

**Comment by petyaracz** [comment] 2019-07-16 14:55
Very sorry, I have no idea. It seems to crop up more often in my current project / configuration.

This might be because I

- copy-paste a vast amount
- use shift a lot to select
- use opt+shift to change selection word-by-word.

This might be helpful.

**Comment by ronblum** [comment] 2019-07-16 16:06
@petyaracz Thanks! This is useful—I will try using the methods you've been using, as well as let the edit the script with long period in between edits, using these method, to see if I can reproduce.

**Comment by ronblum** [comment] 2019-07-17 15:40
@petyaracz I wasn't able to reproduce it, including by trying out a bunch of code and cutting, pasting, and selecting in the ways you describe. When you say that the problem occurs on in "my current project / configuration," do you mean that it's only occurring in one project?

**Comment by petyaracz** [comment] 2019-07-17 19:27
@ronblum No, it happens over multiple R source files, independent of the file. I don't use projects so that's probably not a factor.

I suggest we close this issue and if I can provide steps to replicate the problem I reopen it?

**Comment by dmurdoch** [comment] 2019-07-17 20:37
I'm seeing something like this too, but like @petyaracz am finding it frustrating to find a reprex.  I have seen it very early in a session.  My MacOS is 10.13.6, so it's not 10.14.x specific.  I'm on the same RStudio version.  I mainly see it in the console, not in the source editor.

I have a feeling it might be related to text completion.

**Comment by kevinushey** [comment] 2019-07-17 21:39
Could you by any chance share a screencast of the behavior you're seeing when the issue occurs, just so we know exactly what's going on?

**Comment by dmurdoch** [comment] 2019-07-17 22:46
I don't know how to make a screencast, but it just happened, and here's a description:

I was using the up arrow key in the console to retrieve past commands for editing.  On one attempt (I don't know what was special about it), the previous command came up with the second half highlighted.  I typed a letter, and it replaced the highlighted half of the command with that letter, but further typing just kept replacing at the same location, so no new text could be entered.  

I've been there before, and I know that using the mouse to click on the line resets things to normal.

I tried to upload a screenshot I took of the half-highlighted console, but got a "Something went really wrong, and we can't process that file." message from github.  I'll try again now...same problem.

**Comment by dmurdoch** [comment] 2019-07-17 22:58
Got it again by closing RStudio, re-opening, clicking in the console, typing a command (which was fine), and hitting the up arrow again.  This time I noticed that the highlighting started at the location of the mouse cursor.  (I hadn't been using the mouse after selecting the console, just the keyboard up arrow.)  Typing left the new text highlighted which is why it was replaced. 

Switched to Chrome and this time I can upload screenshots.  Here's the half-highlighted text:

![Screen Shot 2019-07-17 at 6 48 39 PM](https://user-images.githubusercontent.com/1935680/61417287-a9f56980-a8c4-11e9-9284-a332c8964f42.png)

Here's after I typed "a":

![Screen Shot 2019-07-17 at 6 48 54 PM](https://user-images.githubusercontent.com/1935680/61417292-b11c7780-a8c4-11e9-8c2f-91c5e1f640bd.png)

And here I typed "b":
![Screen Shot 2019-07-17 at 6 49 06 PM](https://user-images.githubusercontent.com/1935680/61417296-b5e12b80-a8c4-11e9-804b-00f201e24a93.png)

**Comment by petyaracz** [comment] 2019-07-17 23:05
This is very similar to what I've seen, except in the source editor. I couldn't replicate the exact behaviour @dmurdoch found, though.

**Comment by kevinushey** [comment] 2019-07-18 23:49
I _think_ I have a reproducible example now. If you have time, I'd appreciate if you could let me know if you see the same thing.

1. Open RStudio, and open an R document with some code (contents shouldn't matter).
2. Open another application. On macOS, just opening e.g. System Preferences should work.
3. While that application is open and is the 'active' window, click on the RStudio source pane. (I did this by tapping with my macOS Trackpad)
4. Start typing, or trying to move the cursor.

If you start typing, you should see the inserted character get 'replaced' as new characters are typed; if you try moving the selection around with the arrow keys, the cursor seems to bounce back to the original position but with the text selected where the cursor should have moved.

**Comment by kevinushey** [comment] 2019-07-18 23:49
And, for whatever reason, I do not see this behavior in v1.3 [daily builds](https://dailies.rstudio.com) of RStudio.

**Comment by dmurdoch** [comment] 2019-07-19 00:17
Yes, that sequence works repeatedly for me too.  It didn't work the first couple of tries, but I might not have been following the instructions exactly.  The symptoms do look a lot like what I was seeing, though without highlighting half the line.

I tried it in the console, and didn't see anything.  Then I went back to the source pane, and got this on the next try:

![Screen Shot 2019-07-18 at 8 10 50 PM](https://user-images.githubusercontent.com/1935680/61500268-75eb7880-a998-11e9-972c-e0488b1abac3.png)

That box in the middle is supposed to be code completion I think, but it really looks messed up.

**Comment by petyaracz** [comment] 2019-07-19 12:21
@kevinushey 's steps work for me too. I could replicate the issue a few times.

In this setup, I can stop the weird behaviour by clicking somewhere else in the source editor. In my previous experience this didn't always help.

**Comment by maxheld83** [comment] 2019-07-20 18:55
I can also reproduce the problem with RStudio 1.2.1555 on macOS 10.14.5.

I can *not* reproduce the issue with the current daily 1.3.323.

Ping me if a screencast/gif is helpful, though I think @kevinushey has this reprex'ed.

Pretty weird glitch; must only affect very few users. I searched several times over the weeks and couldn't find fellow sufferers so I thought, eh, must be on my end.

**Comment by kevinushey** [comment] 2019-07-21 04:29
I think I understand what's going on now. It looks like, it one does a quick click to focus RStudio from another window (e.g. a tap on the editor surface), the document receives a mouse down event, but _not_ an accompanying mouse up event.

Because of this, RStudio believes the mouse is still held down, and treats it as though the user is clicking + holding the mouse, and this screws up any future attempts to type or scroll.

Hopefully we'll be able to find a simple solution to this...

**Closed** 2019-07-22 18:30 UTC
Labels: bug

**Comment by ronblum** [comment] 2019-07-31 20:36
I can't reproduce the original issue, so I can't confirm the fix. So, @petyaracz @maxheld83 and @dmurdoch—can any of you check if this works in[the latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by maxheld83** [comment] 2019-08-01 07:40
I can confirm that the issue appears solved in Version 1.2.1565.
I was just able to still reproduce it on Version 1.2.1555.

**Comment by petyaracz** [comment] 2019-08-01 08:54
I can also confirm that the issue appears solved in the v1.2.1565-5 Preview Release.

**Comment by ronblum** [comment] 2019-08-01 14:22
Great—thank you both fo confirming!

**Comment by dantonnoriega** [comment] 2019-08-15 22:06
I think this is the same problem as covered in #4782. I just updated and will confirm if it solved things for me.

**Comment by grasshoppermouse** [comment] 2020-04-13 14:01
I have this problem in the console on RStudio 1.2.5019, "Elderflower" (fba733f0, 2019-10-24), and MacOS 10.14.6:

<img width="87" alt="Screen Shot 2020-04-12 at 6 52 40 AM" src="https://user-images.githubusercontent.com/7534138/79126159-4796a000-7d54-11ea-9b9d-b3a9a529348c.png">

I couldn't reproduce using the issue using the app switching procedure mentioned above, but holding the mouse down while typing does create the same kind of glitch.

**Comment by kevinushey** [comment] 2020-04-13 18:39
@grasshoppermouse: that should be resolved in the v1.3 [preview release](https://www.rstudio.com/products/rstudio/download/preview/).

**Comment by antaldaniel** [comment] 2024-06-07 09:38
I repeatedly have the same problem, mainly on Ubuntu, but also on Windows, and through many versions of RStudio, going back for years.
