### ISSUE TITLE
allow for clickable links from console-generated output

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2530] opened 2018-03-28 21:15 UTC
It'd be handy if we could generate clickable links for certain kinds of console output; primarily for source references. Some example cases:

`testthat` output, with links of the form:

    test-file.R:42: failure: a thing happened

Source references, e.g.

    1: expect_match(arg_descriptions[["a"]], "Description for a") at 
    /Users/kevin/r/pkg/reticulate/tests/testthat/test-help-handlers.R:33

`pkgdown` output, e.g.

    Building 'man/with.python.builtin.object.Rd'
    Writing  'reference/with.python.builtin.object.html'

The two most common places where these types of outputs will appear are in the Console (for direct console output), and in the Build pane. If possible, a generic solution that post-processes console output would likely be most appropriate, since we could re-use that in both scenarios.

cc: @hadley

**Comment by hadley** [comment] 2018-03-28 21:22
I suspect this might also be useful in usethis if when we inform a user that we have modified a file for them.

**Comment by gtritchie** [comment] 2018-03-28 21:31
See also #1941

**Comment by hadley** [comment] 2018-04-03 21:17
This would also be useful in shiny, where they're printing their own stack traces.

**Comment by hadley** [comment] 2018-04-04 16:58
Ideally, this would also work for http(s) urls, where clicking on them would open in the system browser.

**Comment by gtritchie** [comment] 2019-04-30 23:56
Same as #1941

**Comment by colearendt** [comment] 2020-04-08 03:30
This would also be useful in the terminal

**Comment by gtritchie** [comment] 2020-04-08 16:47
Ah, in RStudio 1.2 hyperlinks in the terminal do work (in that if the terminal displays something recognized as a link, you can click on it to launch it in the browser). This stopped working in 1.3, however. I'll open an issue on that.

**Comment by hadley** [comment] 2021-02-05 14:07
Please keep this alive 😄

**Comment by mikebessuille** [comment] 2021-10-04 19:56
high priority for Hadley - consider soon

**Comment by t-kalinowski** [comment] 2021-10-04 20:07
Maybe every function that's printed? For a long time I've had something like this in my .Rprofile:
```R
print.function <- function (x, ..., style = prettycode::default_style()) 
{
    prettycode:::print.function(x, style = style)
    if (length(fi <- getSrcFilename(x, full.names = TRUE))) 
        cat("file: ", fs::path_rel(fi), "\n", sep = "")
}
```
This gives output like this when I'm in an R package:
```R
> keras::k_dot
function(x, y) {
  keras$backend$dot(
    x = x,
    y = y
  )
}
<environment: namespace:keras>
file: R/backend.R
```
It would be great if that link at the end was clickable!

**Comment by hadley** [comment] 2021-10-04 22:12
It would be very useful to be able to annotate output with two types of links:

-   source code (e.g. `tests/testthat/test-foo.R:5`). These would generally (but not always) be project-local, would open in the script editor (or activate the tab if already open), and should navigate to a line, if specified.
-   external links (e.g. [`http://rstudio.com`](http://rstudio.com)), would open in external web browser.

And there are two more types that would be useful but are less important:

-   viewer links, like external links but open in the viewer.
-   help links, that open specified documentation in the help pane.

There are two ways such annotations could be provided:

-   Regexp based parsing of console output so (e.g. `<https?://.*?>` would be an external link and `[^ ]+\\.[rR]:(0-9)+` would be a source code link).

-   ANSI escape code (probably using [iTerm's proprietary extension](https://iterm2.com/documentation-escape-codes.html)).

There are pros and cons for both approaches. Regexp based parsing would add links to existing code without developer effort but would have some false positives and negatives, and there's no obvious way to support viewer links. ANSI escapes would be 100% accurate, but would require work by developers to take adavantage of.

There are a number of places where the tidyverse team would take advantage of such links:

-   Where we're already displaying srcrefs, particularly in tracebacks produced by by rlang and in testthat errors. These links making debugging faster and more fluid because you can easily jump directly from the error to the underlying source code. These are mostly useful for package developers.

-   In errors that require more explanation, e.g. in vctrs (as below), when we're wrapping web APIs that provide informative urls on error, and in "sitrep" functions, which give users a **sit**uation **rep**ort on the package and its environs.

        #> rlang::inform(vctrs:::incompatible_attrib_bullets())
        x Some attributes are incompatible.
        ℹ The author of the class should implement vctrs methods.
        ℹ See https://vctrs.r-lib.org/reference/faq-error-incompatible-attributes.html#

    We have used such links in relatively few places, but would be likely to include more (especially in deprecation messages) if we could produce live links.

**Comment by romainfrancois** [comment] 2022-01-25 13:51
Can we consider this a duplicate of #1941 (with its pull request here: #10416).

**Comment by mikebessuille** [comment] 2022-01-25 15:01
Does 1941 include support for source code links as well as external?  If it does, and it resolves all the main aspects of the request, then I think we can consider it a duplicate.

**Comment by romainfrancois** [comment] 2022-01-25 15:32
yes, e.g. `cli::style_hyperlink("go", "file://{file path}", params = c(line = <line>, col = <col>))`, it's just a bit clunky that we have to prefix with `file://` and use the absolute path. 

https://github.com/r-lib/testthat/pull/1544 is an example use.

**Comment by mikebessuille** [comment] 2022-02-17 16:36
Closed as duplicate of https://github.com/rstudio/rstudio/issues/1941

**Closed by mikebessuille** 2022-02-17 16:36 UTC
Labels: enhancement, console, backlog
