### ISSUE TITLE
RStudio infinite loop asking to restart R when I run install.packages("rmarkdown")

### ISSUE THREAD

**Issue by slowkow** [rstudio/rstudio#8799] opened 2021-01-25 16:41 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Mac OS X 10_15_7
    R Version       : 4.0.3

```
RStudio
Version 1.4.1103
© 2009-2021 RStudio, PBC
"Wax Begonia" (458706c3, 2021-01-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

### Steps to reproduce the problem

1. Run `install.packages("rmarkdown")`
2. Pop-up asks to restart R before installing.
3. Click "Yes" to restart R.
4. RStudio restarts, go to step 2.

The loop is from Steps 2-4.

### Describe the problem in detail

Instead of installing the package, RStudio shows a pop-up message asking to restart R before installing the package.

If I click "Yes", then it restarts and immediately shows the pop-up message again. If I click "Yes" again, then it again restarts and shows the pop-up. The infinite loop continues as long as I keep clicking "Yes".

If I click "No", then it seems to install the package and then it's done. But, if I run the `install.packages("rmarkdown")` command again, then I get the pop-up again.

Here's a video showing what happens:

https://vimeo.com/504434815

Description:

1. Run `install.packages("rmarkdown")`
2. Pop-up asks to restart R before installing.
2. Click "Yes" to restart R.
3. RStudio restarts, then go back to step 2.
4. At 0:18, I click "No" and it seems to install and finish.
5. Then, at 0:26 I run `install.packages("rmarkdown")` again and we're back in the loop.

The infinite loop continues as long as we click "Yes". Clicking "No" breaks the loop.
We can enter the loop again if we run `install.packages("rmarkdown")`.

### Describe the behavior you expected

After clicking "Yes", I would expect that the pop-up would not be displayed a second time.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-01-25 18:23
Two recent duplicates:
- #8710 
- #8799

**Comment by ronblum** [comment] 2021-01-25 18:25
This is a duplicate of #2656.

**Closed by ronblum** 2021-01-25 18:25 UTC
