### ISSUE TITLE
allow location of project-specific state (.Rproj.user) to be configured

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3375] opened 2018-08-27 02:51 UTC
See e.g. https://community.rstudio.com/t/rstudio-and-google-drive/693

Tools that automatically synchronize the contents of a folder can cause havoc with RStudio, as RStudio and that tool end up fighting for access to files within the `.Rproj.user` folder.

Some tools allow the user to configure which files should and shouldn't be synchronized, but many don't, and it's usually not clear to the user that the issue here is caused by competing access between RStudio and the associated tool.

One solution here would involve offloading project-specific state to a different folder, but it's not clear what the right choice of folder would be:

1. Should it be the user's "application data" folder? What if these are on different filesystems?
2. Should this be configurable by the user? (Perhaps a new setting in the `.Rproj` file?)

**Comment by jjallaire** [comment] 2018-08-27 10:29
One reason that this data is currently within the project folder itself is so that when the folder is copied or moved it retains this context. If we moved it to "application data" it would be nice if we preserved some mechanism for having the context follow along during copies and moves.

**Comment by gtritchie** [comment] 2018-08-27 16:56
For example, I recently did some work for the rstudio.cloud team to leverage metadata in .Rproj.user when projects are copied around. This specific use case is very unlikely to overlap with use of Dropbox, OneDrive, etc. just wanted to mention it as a test case https://github.com/rstudio/rstudio-pro/pull/559.

**Comment by kevinushey** [comment] 2018-08-27 17:51
One option would be to store something like a project GUID in the `.Rproj` file and use that to map back to some folder location on the filesystem.

**Comment by Narciandi** [comment] 2019-02-20 12:45
From my experience as an (ignorant) user (I came too from reading this issue https://community.rstudio.com/t/rstudio-and-google-drive/693), the only problem is the persistence of the error message. 

I never had to take any action other than closing the message box. **Maybe the option to supress this particular message box would be enough for us Google Drive users**. Also, the message refers to a saving operation:

![imagen](https://user-images.githubusercontent.com/19656549/53092475-3027a280-3515-11e9-8882-e724503edd89.png)

**Perhaps another simple solution could be to include the option to cancel RStudio's autosaving feature in a project?** (As far as I know this option is not included).

![imagen](https://user-images.githubusercontent.com/19656549/53092661-9f04fb80-3515-11e9-901d-14c010da1237.png)

**Comment by kevinushey** [comment] 2019-04-09 21:02
Relaying some extra information from the community forums; it's possible to ignore specific file extensions with Google Drive / Backup and Sync. Here are the steps:

1. Open the Google Drive / Backup and Sync preferences dialog,
2. Click on the `My <Computer>` tab on the left,
3. Click the 'Change' button near the right side of the dialog,
4. Click the 'Advanced Settings' dropdown,
5. Add '.Rproj.user' to the set of ignored extensions.

![Screen Shot 2019-04-09 at 1 59 33 PM](https://user-images.githubusercontent.com/1976582/55835062-1267ca00-5ad0-11e9-9007-fd8d8430edeb.png)

**Comment by coniliakis** [comment] 2019-10-23 11:55
> Relaying some extra information from the community forums; it's possible to ignore specific file extensions with Google Drive / Backup and Sync. Here are the steps:
> 
> 1. Open the Google Drive / Backup and Sync preferences dialog,
> 2. Click on the `My <Computer>` tab on the left,
> 3. Click the 'Change' button near the right side of the dialog,
> 4. Click the 'Advanced Settings' dropdown,
> 5. Add '.Rproj.user' to the set of ignored extensions.
> 
> ![Screen Shot 2019-04-09 at 1 59 33 PM](https://user-images.githubusercontent.com/1976582/55835062-1267ca00-5ad0-11e9-9007-fd8d8430edeb.png)

Hello, could you confirm that this process works with latest version of Rstudio? In the community it has been reported that conflicting files are replicating. I am not sure if this has to do with some added feature of auto-save or file organisation (using scripts outside the project folder

**Comment by brshallo** [comment] 2020-09-09 22:37
Just wanted to point to the relevant thread for OneDrive / synced Sharepoint documents that requires similar steps to those @kevinushey detailed for Google Drive: https://answers.microsoft.com/en-us/msoffice/forum/all/onedrive-and-r-project-sync-with-folder-rprojuser/91ccc7e9-b133-44f9-99a9-1bfcc737d9bd (though users there did not indicate success).

**Comment by ltelesca** [comment] 2021-12-06 18:32
> Relaying some extra information from the community forums; it's possible to ignore specific file extensions with Google Drive / Backup and Sync. Here are the steps:
> 
> 1. Open the Google Drive / Backup and Sync preferences dialog,
> 2. Click on the `My <Computer>` tab on the left,
> 3. Click the 'Change' button near the right side of the dialog,
> 4. Click the 'Advanced Settings' dropdown,
> 5. Add '.Rproj.user' to the set of ignored extensions.
> 
> ![Screen Shot 2019-04-09 at 1 59 33 PM](https://user-images.githubusercontent.com/1976582/55835062-1267ca00-5ad0-11e9-9007-fd8d8430edeb.png)

This problem is back with the new version of Google Drive where the selective Sync option has been removed. Has any procedure/solution been proposed?

**Comment by kevinushey** [comment] 2021-12-06 21:29
Is petitioning Google to bring this option back an option?

**Comment by DesiQuintans** [comment] 2023-04-05 01:23
I'd also like the option to have .RProj.user kept on my local drive. 

In my current job we work inside mapped network drives. Most of my colleagues store their R projects on these networked drives, but I don't because _RStudio performs significantly slower if its .Rproj file is stored in the mapped drive_. 

Sometimes it's a 2-3 second lag between showing a new pane. Sometimes it's an "RStudio is initialising" message when a new session is started, which I'd never seen before. The difference is entirely to do with where the .RProj file is located; I can copy the same project from my local drive to the mapped drive and reliably get the same UI slow-down.

I'm assuming this is because the contents of .Rproj.user gets updated, and project information has to pass back and forth to the mapped drive at the mercy of my internet connection's upload speed (which can be limited especially if I'm working off-site on the required VPN).

**Comment by adayim** [comment] 2024-06-25 07:51
Same problem here. It is extremely slow if the project is opened directly from the project folder (on the network drive), but it works fine if Rstudio is opened in local folders with the project directory set to the network drive via VPN. Not all the cloud drive supports selective synchronising. My current solution is manually set the working directly but open Rstudio in local directory. It would be good if some alternatives can be provided.

**Comment by olivroy** [comment] 2024-06-25 12:24
I think this was implemented recently #14778?

**Comment by gtritchie** [comment] 2024-06-25 17:56
> I think this was implemented recently https://github.com/rstudio/rstudio/issues/14778?

Yes, looks like an unintentional duplicate issue. Normally we'd keep the original (this one) but since all the conversation about the actual fix is happening there, will close this as a duplicate of #14778.

**Closed by gtritchie** 2024-06-25 17:56 UTC
Labels: enhancement, projects
