### ISSUE TITLE
Project within a git tracked project inherits git configuration settings

### ISSUE THREAD

**Issue by harrismcgehee** [rstudio/rstudio#2250] opened 2018-02-21 22:10 UTC
### System details

    RStudio Edition : Server Pro
    RStudio Version : 1.1.353
    OS Version      :  RHEL 7

### Steps to reproduce the problem

1. Start a new project from Git Repo by cloning.
2. Create a subfolder. Create a new child project that starts in the subfolder.
3. In the child project, navigate to Tools > Project Options > Git/SVN

### Describe the problem in detail
The origin is already set to the parent project and is unchangeable in the child project.

### Describe the behavior you expected
I expected to be able to configure the git repo of the subfolder independently of the parent project.  Instead, it appears that RStudio is navigating up the file tree to find a `.git` folder to use.

**Comment by ronblum** [comment] 2018-02-23 19:45
@harrismcgehee This is the expected behavior and mirrors `git`. However, since this is being actively worked on with the Support Team (25647), I will close it in this queue to avoid redundancy.

**Closed by ronblum** 2018-02-23 19:45 UTC
