### ISSUE TITLE
Electron: Starting RStudio Desktop displays error and message about Passthrough and node_controller

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10782] opened 2022-03-15 13:56 UTC
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily+209 (Electron)
    OS Version      : Ubuntu 18.04.5/20.04.4, RHEL 8.3, openSUSE 15.3
    R Version       : 4.0.2/3.6.3/4.0.3/4.1.3

### Steps to reproduce the problem

1. Install RStudio Desktop Electron.
2. In terminal: `rstudio`
    - RStudio Desktop starts.
    - In the terminal, two messages appear, the first one an error:
```
[3492:0315/092313.087560:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is desktop, ANGLE is 
Gtk-Message: 09:24:53.565: GtkDialog mapped without a transient parent. This is discouraged.
```
3. Quit RStudio Desktop.
4. In terminal: `rstudio`
    - RStudio Desktop starts.
    - In the terminal, one error appears:
```
[7859:0315/093258.271080:ERROR:node_controller.cc(585)] Trying to re-add dropped peer E9B2B0D96F03C8A9.B037B6B6C79A4ED0
```

### Describe the problem in detail

Error and information messages are displayed at start up. Note that the first message, the "Passthrough" error, appears every time that RStudio Desktop is started. However, the "node_controller" message only appears the first time that it's started.

Note:
- That's on Ubuntu 18.04.5 with R 4.0.2.
- Only the "Passthrough" message appears on Ubuntu 20.04.4 with R 3.6.3 or 4.0.2, RHEL 8.3. with R 4.0.3, and openSUSE 15.3 with R 4.1.3.

### Describe the behavior you expected

No errors/messages.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-03-15 18:26
Note: I originally put in one of the wrong error messages (belonging to #10784). Fixed above.

**Comment by ronblum** [comment] 2022-05-26 13:53
Some updates and more details on errors. I turned off hardware acceleration, which has more errors. But in all cases, the IDE seems to be working.

One common error that's in all options with Electron, and only with Electron, is:
```
[3024:0526/061214.551256:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

----


**UBUNTU 22 ELECTRON**
*Ubuntu 22 Electron: Auto detect*
```
vmware@vmware:~$ rstudio
[3583:0526/090516.915190:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
[3583:0526/090517.073864:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

*Ubuntu Electron 22: DesktopGL*
```
vmware@vmware:~$ rstudio
[2457:0526/084934.867930:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
[2457:0526/084934.943276:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
vmware@vmware:~$ 
```

*Ubuntu Electron 22: OpenGL for Embedded Systems*
```
vmware@vmware:~$ rstudio
[3058:0526/090351.054091:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=desktop-gl,angle=none),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[3058:0526/090351.100145:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[3090:0526/090351.600756:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=desktop-gl,angle=none),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[3090:0526/090351.651796:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[3104:0526/090351.944697:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

*Ubuntu Electron 22: Software*
```
vmware@vmware:~$ rstudio
[3222:0526/090428.158774:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

---

**UBUNTU 22 QT**
*Ubuntu 22 Electron: All options*
```
vmware@vmware:~$ rstudio
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/xdg/xdg-ubuntu:/etc/xdg/rstudio/logging.conf'. Logging to '/home/vmware/.local/share/rstudio/log/rdesktop.log'.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

---


**UBUNTU 20 ELECTRON**
*Ubuntu 20 Electron: Auto detect*
```
vmware@ubuntu:~$ rstudio
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2160:0526/061003.919756:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
[2160:0526/061003.955465:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

*Ubuntu 20 Electron: Desktop OpenGL*
```
vmware@ubuntu:~$ rstudio
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2623:0526/061112.673315:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
[2623:0526/061112.704751:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

*Ubuntu Electron 20: OpenGL for Embedded Systems*
```
vmware@ubuntu:~$ rstudio
[2818:0526/061142.032570:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=desktop-gl,angle=none),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[2818:0526/061142.045268:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[2860:0526/061142.321216:ERROR:gl_factory.cc(128)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=desktop-gl,angle=none),(gl=egl-gles2,angle=none),(gl=egl-angle,angle=swiftshader)].
[2860:0526/061142.325019:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2868:0526/061142.375881:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

*Ubuntu 20 Electron: Software*
```
vmware@ubuntu:~$ rstudio
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[3024:0526/061214.551256:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

**Comment by mikebessuille** [comment] 2022-09-26 16:43
Kevin believes these warnings are okay, working as designed.  CLosing; can revisit if other symptoms arise.

**Closed by mikebessuille** 2022-09-26 16:43 UTC
Labels: bug, electron

**Comment by kevinushey** [comment] 2022-09-26 18:34
To elaborate a bit, as long as RStudio works in the default configuration (no rendering errors in a "factory-fresh" RStudio installation) I think we're fine. Users should only touch the rendering engine settings if they're seeing issues; _caveat emptor_ applies here.

**Comment by raffaem** [comment] 2023-01-02 20:42
> To elaborate a bit, as long as RStudio works in the default configuration (no rendering errors in a "factory-fresh" RStudio installation) I think we're fine. Users should only touch the rendering engine settings if they're seeing issues; _caveat emptor_ applies here.

I have this error with RStudio 2022.12.0+353 installed from the AUR and open source NVIDIA drivers:
```
❯ /usr/lib/rstudio/rstudio --no-sandbox 1_figure_1.R
[15637:0102/214023.265875:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
```

RStudio starts, but there are A LOT of graphic glitches. The cursor is bigger than the text, and when I delete a character the character before it gets deleted. So I think the cursor is misplaced or something.

I think this should be re-opened.

**Comment by kevinushey** [comment] 2023-01-04 03:50
> I have this error with RStudio 2022.12.0+353 installed from the AUR and open source NVIDIA drivers:

What other options for open-source graphics drivers are available for you? Do the default graphics drivers (nouveau?) work for you? Does forcing software rendering make a difference? Do you see these sorts of graphical glitches in any other Electron-based applications (e.g. Visual Studio Code)?

**Comment by raffaem** [comment] 2023-01-19 07:51
> > I have this error with RStudio 2022.12.0+353 installed from the AUR and open source NVIDIA drivers:
> 
> What other options for open-source graphics drivers are available for you? Do the default graphics drivers (nouveau?) work for you? Does forcing software rendering make a difference? Do you see these sorts of graphical glitches in any other Electron-based applications (e.g. Visual Studio Code)?

After an update to the NVIDIA drivers, a lot of the graphics issue were solved, but there are still some.

For example, flickering when scrolling, and black toolbar menus:

![2023-01-19T08:47:00](https://user-images.githubusercontent.com/54762742/213385059-6645e027-7397-4991-9df1-63cf0095ded7.png)

**Comment by raffaem** [comment] 2023-01-19 07:54
> > I have this error with RStudio 2022.12.0+353 installed from the AUR and open source NVIDIA drivers:
> 
> What other options for open-source graphics drivers are available for you? Do the default graphics drivers (nouveau?) work for you? Does forcing software rendering make a difference? Do you see these sorts of graphical glitches in any other Electron-based applications (e.g. Visual Studio Code)?

Moreover, starting with `QT_QPA_PLATFORM=xcb` environment variable, doesn't have any effect anymore.

It used to render with XWayland. 

I guess this is because the interface is not rendered with QtWebEngine anymore but with Electron instead?

Is this from 2022.12? Is this change documented?
