### ISSUE TITLE
RStudio uses different path to application (e.g., `rsync`, `ffmpeg`, ...)

### ISSUE THREAD

**Issue by kalaschnik** [rstudio/rstudio#10551] opened 2022-02-09 21:08 UTC
I was working with FFmpeg in R, and I realized that RStudio points to a different instance than R running in the Terminal.

Is that a bug, or can I change that somewhere within RStudio?

I am in favor of the actual terminal location: `/usr/local/bin/`

<img width="865" alt="image" src="https://user-images.githubusercontent.com/9831678/153290061-3e4251c5-ca94-4260-903f-b62463061d1b.png">

**Comment by kalaschnik** [comment] 2022-02-14 17:28
I just noticed that some other commands are affected; e.g., `rsync`
- bash: `which rsync` → `/usr/local/bin/rsync`
- R shell: `system("which rsync")` → `/usr/local/bin/rsync`
- RStudio: `system("which rsync")` → `/usr/bin/rsync`

That is very strange. Seems RStudio is not respecting that actual $PATH order in `/etc/paths` ?

**Comment by kevinushey** [comment] 2022-02-14 21:13
What is the output of `Sys.getenv("PATH")` versus `echo $PATH` in your terminal?

RStudio does explicitly read and load paths from `/etc/paths` and `/etc/paths.d/`, and there should be a fix in the preview release of RStudio regarding the ordering of those path entries.

**Comment by kalaschnik** [comment] 2022-02-15 11:33
**Terminal**
```
❯ cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

❯ echo $PATH
/Users/steven_kalinke/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/opt/X11/bin:/Library/Apple/usr/bin:/Users/steven_kalinke/.fig/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
```

**RStudio**
```
> Sys.getenv("PATH")
[1] "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/munki:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/RStudio 4.app/Contents/MacOS/postback"
```

Indeed for some reason `/usr/bin` happens first in RStudio, which may cause the issue over shadowing my actual commands in `/usr/local/bin`

**Comment by kevinushey** [comment] 2022-02-15 17:15
That does indeed sound like something that may be resolved in the preview release of RStudio: https://www.rstudio.com/products/rstudio/download/preview/

I see, with RStudio 1.4.1717:

```
> Sys.getenv("PATH")
[1] "/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/usr/local/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/RStudio-1.4.1717.app/Contents/MacOS/postback"
```

And with the preview release at https://www.rstudio.com/products/rstudio/download/preview/:

```
> Sys.getenv("PATH")
[1] "/Users/kevin/.yarn/bin:/Users/kevin/.config/yarn/global/node_modules/.bin:/Users/kevin/bin:/opt/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/kevin/.fzf/bin:/usr/local/bin:/Applications/RStudio-2022.02.0+431.app/Contents/MacOS/postback"
```

(There's a bunch of extra stuff, but most importantly the order of PATH elements is now correct)

**Comment by kalaschnik** [comment] 2022-02-16 16:08
Unfortunately, this is not fixed for me with the new version, I even checked with waldo to check the outputs of `Sys.getenv("Path")`:

```
> waldo::compare(old_path, Sys.getenv("Path"))
✓ No differences
```

**Comment by jgutman** [comment] 2022-03-02 16:34
Able to reproduce this in RStudio Desktop 2022.06.0-daily+167 on Mac OS 12.2. 
`Sys.getenv("PATH")` begins with `/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:` which notably reverses the precedence of `/usr/bin` and `/usr/local/bin` and does not correspond to my system path. The order of paths in the RStudio terminal appears to be correct, and aligned with my system path (with some expected modifications).

**Comment by kevinushey** [comment] 2022-03-02 17:57
For future investigation, the PATH on macOS is initialized here: https://github.com/rstudio/rstudio/blob/14601ca5cc3d6e2466a8a153d1283409d687b236/src/cpp/session/modules/SessionPath.cpp#L94-L154

**Comment by jgutman** [comment] 2022-03-10 15:48
@kalaschnik We are continuing to investigate why this is happening. As a workaround until a fix is available, you should be able to use a `.Renviron` file to set the value of PATH yourself directly, based on the desired value you see when running R outside of RStudio.

**Comment by t-kalinowski** [comment] 2022-03-15 18:42
related: https://github.com/rstudio/rstudio/issues/10311

**Comment by JosiahParry** [comment] 2022-03-25 03:13
I am having a related problem where the `$PATH` in RStudio is different than that from the terminal 

From the IDE

```r
system("echo $PATH")
#> "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/RStudio.app/Contents/MacOS/postback"
```

From the shell

```
echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by mikebessuille** [comment] 2022-04-04 15:43
related ? https://community.rstudio.com/t/how-to-get-rstudio-ide-to-use-the-correct-terminal-path-in-mac-os-x/131528

**Comment by jgutman** [comment] 2022-04-04 15:52
Yeah, this is the same issue, I will comment on the post with a temporary workaround. Whenever we do manage to fix this, I think it's very important to backport the fix to any supported releases

**Comment by kevinushey** [comment] 2022-04-05 00:21
I think I know what's going on here.

When RStudio is launched in the "typical" way (that is, from the Finder, and not from a Terminal), it gets the "default" PATH for desktop applications -- that is, something like `/usr/bin:/bin:/usr/sbin:/sbin`.

However, when we try to build the PATH, we always attempt to _append_ path components to this path list. In particular, here:

https://github.com/rstudio/rstudio/blob/90f66db9871af41073ac6a6e012a312ecd301e3e/src/cpp/session/modules/SessionPath.cpp#L122-L125

This implies that paths like `/usr/local/bin` would be placed at the end of the path list, rather than the beginning.

This doesn't affect RStudio when launched from a terminal, because in that case the current PATH is inherited, and that would normally have path components in the correct order. For example:

```
 env -i /bin/sh -l -c 'echo $PATH'
/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
```

The current scheme we have (where we try to "merge" /etc/paths and /etc/paths.d back into the PATH) seems doomed to failure, because we can't know what the correct ordering for path elements is.

Some potential solutions:

1. Launch `rsession` through a login shell, and let that shell take care of setting the PATH appropriately,
2. Move the PATH construction to the desktop front-end, and manually construct the PATH depending on whether RStudio is connected to a tty (that is, was launched from a terminal),
3. Find a way to communicate the state required for (2) down to `rsession`, and use that to construct the PATH,
4. Just always prepend `/usr/local/bin` to the PATH if it's not already there (rather than append).

**Comment by jgutman** [comment] 2022-04-05 12:21
Oh, I see. Yeah when I was walking through the code I saw we prepend to the path but I couldn't understand how/what the path was initialized to in the first place. Note that prepending won't work, because it's not only that the path elements are out of order, but some path elements are missing completely, e.g. /opt/homebrew

**Comment by kevinushey** [comment] 2022-04-05 21:26
We have a couple candidate PRs that we're working through, but FWIW a potential workaround would be to manually take care of setting the PATH either in your `~/.Renviron` or `~/.Rprofile`; e.g.

```
PATH=/usr/local/bin:$PATH
```

or

```
Sys.setenv(PATH = paste("/usr/local/bin", Sys.getenv("PATH"), sep = ":"))
```

**Comment by kevinushey** [comment] 2022-04-06 17:32
Note: because this issue only affects macOS desktop, and can be relatively easily worked around, we've opted to fix this in SW but not backport the fix.

However, the merged change should ensure the PATH you see in your RStudio R sessions matches that seen within a regular terminal, so modifications made to your shell `.profile` files should now be reflected in RStudio sessions.

**Comment by jgutman** [comment] 2022-04-27 20:54
Verified in 2022.06.0-daily+322 RStudio Desktop on Mac OS 12.3

**Closed by jgutman** 2022-04-27 20:54 UTC
Labels: bug, macos, test
