### ISSUE TITLE
Feature request: Allow renaming the taskbar RStudio label

### ISSUE THREAD

**Issue by DanChaltiel** [rstudio/rstudio#13997] opened 2023-11-28 09:59 UTC
Hi,

When you are starting RStudio with a project, the OS taskbar label is set to the working directory:

![image](https://github.com/rstudio/rstudio/assets/15105152/2fcb7b2a-88e7-4f68-8a87-9b124add044d)

As you can see, as the path is always too long, it is impossible to tell which project I'm working on by reading the label.

In Chrome (on Win10 at least), if you right-click on the top header, you can click on "Nommer la fenêtre", which means "Name the window" in French. This allows you to choose the label in the taskbar.

![image](https://github.com/rstudio/rstudio/assets/15105152/c36bb50b-80d2-4424-a2b0-9733e0db0aa6)

It would be great if RStudio offered the same feature, as it would allow us to organize multiple windows side by side.

It would be even better if you could set the label in the project option or in the `.Rproj` file.

**Comment by gtritchie** [comment] 2023-11-28 23:12
This is a duplicate of https://github.com/rstudio/rstudio/issues/1909 (which, by coincidence, I started working on today).

**Comment by gtritchie** [comment] 2023-11-28 23:13
Closing as duplicate of #1909.

**Closed by gtritchie** 2023-11-28 23:13 UTC
Labels: enhancement, duplicate, new
