### ISSUE TITLE
Some FiraCode ligatures drawn inconsistently between quoted and unquoted code

### ISSUE THREAD

**Issue by rinkjames** [rstudio/rstudio#11907] opened 2022-09-05 12:41 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version :  2022.07.1 Build 554
    OS Version      :  macOS 12.5.1 (21G83)
    R Version       :  4.2.1 (2022-06-23) -- "Funny-Looking Kid"

### Steps to reproduce the problem

1. Install latest FiraCode font onto macOS, e.g. using Homebrew.

```
brew install font-fira-code
```
2. Set the editor font to FiraCode.

<img width="590" alt="Screenshot 2022-09-05 at 14 19 05" src="https://user-images.githubusercontent.com/13288151/188448418-d40b1807-7c44-4b09-bf96-8992314811cf.png">

3. Copy paste the following into the editor pane,

```
cat("
        .= .- := =:=
        == != === !== =/=

    <<- <-- <- <-> -> --> ->>
<=< <<= <==    <=> => ==> =>> >=>
    >>= >>- >-     -< -<< =<<
        <~~ <~ ~~~ ~> ~~>

     <<< << <= <>  >= >> >>>
            <| <|> |>

            <$ <$> $>
            <+ <+> +>
            <* <*> *>

    ")

        .= .- := =:=
        == != === !== =/=

    <<- <-- <- <-> -> --> ->>
<=< <<= <==    <=> => ==> =>> >=>
    >>= >>- >-     -< -<< =<<
        <~~ <~ ~~~ ~> ~~>

     <<< << <= <>  >= >> >>>
            <| <|> |>

            <$ <$> $>
            <+ <+> +>
            <* <*> *>
```
4. Notice discrepancies in ligatures between the quoted and unquoted code, e.g. equivalence ligatures on lines 3 and 20, or arrow ligatures on lines 5 and 22.

<img width="318" alt="Screenshot 2022-09-05 at 14 39 37" src="https://user-images.githubusercontent.com/13288151/188451440-5af65e08-a488-4956-8c6c-e25403071950.png">

### Describe the problem in detail

Using FiraCode v6.2, some (not all) ligatures appear to be drawn inconsistently between quoted and unquoted code.

### Describe the behavior you expected

I expected all ligatures to be drawn consistently, even outside of strings.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2022-09-06 18:24
This is because the tokenizer for R code only recognizes R syntax. For example, `<->` is two R tokens (`<-` and `>`) they are tokenized separately and so displayed separately.

I think this is the expected behavior.

**Comment by ronblum** [comment] 2022-09-06 19:34
Closing as by design according to R, but let us know if you still have any concerns.

**Closed by ronblum** 2022-09-06 19:34 UTC
Labels: bug, external, by design

**Comment by rinkjames** [comment] 2022-09-07 06:20
> This is because the tokenizer for R code only recognizes R syntax. For example, `<->` is two R tokens (`<-` and `>`) they are tokenized separately and so displayed separately.
> 
> I think this is the expected behavior.

Thanks for confirming this for me.
