### ISSUE TITLE
Rstudio crashes during matrix multiplication

### ISSUE THREAD

**Issue by tuberculo** [rstudio/rstudio#7031] opened 2020-06-02 23:21 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Ubuntu 20.04
    R Version       : 3.6.3 

### Steps to reproduce the problem
Run this command:
```
library(tidyverse)

resul <- readRDS("resul_2015.rds")
Serie2015 <- readRDS("Serie2015.rds")
Balance <- sapply(unique(resul$Simulação), function(x) as.matrix(Serie2015[c(resul[resul$Simulação == x, "Usina"][[1]])]) %*% resul[resul$Simulação == x, "Potência"][[1]])
```

### Describe the problem in detail
I get the message: 
"R session Aborted
R encountered a fatal error"

The same command works flawlessly in pure R and in RKward. It also works in a separate job in Rstudio.

### Describe the behavior you expected
No crash.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by tuberculo** [comment] 2020-06-02 23:24
resul_2015.rds: https://drive.google.com/file/d/1wc7sJaCFo7cJ1OwyxXYjTSNpgNRKwsDE/view?usp=sharing
Serie2015.rds: https://drive.google.com/file/d/15E9ZJ62jHJ-CmvTvJzv_obnXuTADBsEM/view?usp=sharing
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4720156/diagnostics-report.txt)

**Comment by ChristK** [comment] 2020-06-03 17:46
A simpler example
```r
set.seed(42L)
a <- matrix(rnorm(1e6), 1e3, 1e3)
b <- matrix(rnorm(1e6), 1e3, 1e3)
a %*% b # After a few repetitions this line crashes Rstudio server v1.3.959, but not R via ssh
a %*% b
a %*% b
a %*% b
a %*% b
a %*% b
a %*% b
```

I have same system details as the reported from OP but I run R v4.0

**Comment by rmflight** [comment] 2020-06-03 18:14
Using R 4.0.0, RStudio v1.4.390 (daily from last week) and Pop!OS 20.04 (mod of Ubuntu 20.04), I can't reproduce this using @ChristK example.

**Comment by rmflight** [comment] 2020-06-03 19:10
@ChristK still runs just fine. Ran `gamlss::pb(x)` 8 times in a row without issue in RStudio.

**Comment by kevinushey** [comment] 2020-06-03 19:32
From your diagnostics report:

```
Session Information
--------------------------------------------------
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pt_BR.UTF-8        LC_COLLATE=pt_BR.UTF-8    
 [5] LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=pt_BR.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3   
```

The use of a threaded OpenBLAS might be the cause.

**Comment by rmflight** [comment] 2020-06-03 19:34
For reference, here is what I have:

```
Matrix products: default
BLAS:   /software/R-4.0.0/lib/R/lib/libRblas.so
LAPACK: /software/R-4.0.0/lib/R/lib/libRlapack.so
```

**Comment by kevinushey** [comment] 2020-06-03 19:36
I can reproduce if I install that version of OpenBLAS via:

```
sudo apt install libopenblas-pthread-dev
```

on Ubuntu 20.04. So I'd recommend switching back to a non-threaded BLAS library for now.

**Comment by tuberculo** [comment] 2020-06-03 20:56
I removed the package libopenblas0-pthread and installed libopenblas0-serial. It is running fine now. Thank you.

**Comment by ChristK** [comment] 2020-06-03 23:22
Confirming that my problem also resolved by using another BLAS library (MKL).

**Closed** 2020-07-16 20:14 UTC
Labels: bug, linux
