### ISSUE TITLE
Fix rsession and r unit tests during build

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#4867] opened 2019-05-30 16:42 UTC
Currently, if these tests are run during a Jenkins build, Jenkins will hang and the build will never complete. Investigate why this is occurring and mitigate this issue if possible so that we can consistently run these tests during the build.

**Comment by jmcphers** [comment] 2019-06-12 18:30
The problem is that the R session is not exiting after running the tests. This used to work, so not sure what broke. The mechanism used to run the test is a `run-script` command line parameter for the R session, which was added specifically to support tests.

https://github.com/rstudio/rstudio/blob/b5223edafd1f1c7adab28b5bdb975e0da5854ee8/src/cpp/rstudio-tests.in#L103-L105

This parameter causes us to use the supplied script instead of reading the console. When the script has been read into R, `RReadConsole` returns 0, which tells R that we're done (sort of like pressing `^D` in terminal R). 

https://github.com/rstudio/rstudio/blob/b5223edafd1f1c7adab28b5bdb975e0da5854ee8/src/cpp/r/session/RScriptCallbacks.cpp#L51-L55

This used to cause R to exit, but now apparently it doesn't.

**Comment by jmcphers** [comment] 2019-06-12 23:24
A fun issue to puzzle through; it turns out that it didn't "break" so much as it was typically run on machines where we'd turned off the prompt to save the workspace on exit, which hangs the process. We should never save the workspace when exiting from a script run.

**Comment by kfeinauer** [comment] 2019-06-13 15:14
Something is still going awry with the rsession tests themselves causing Jenkins build failures. Would you like to take a look? Sample failing build: https://buildmaster.rstudioservices.com/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/detail/master/1496/pipeline/66

**Comment by jmcphers** [comment] 2019-12-02 23:50
Haven't seen this in months so closing. From a recent build:

```

[2019-12-02T18:12:58.568Z] + cd package/linux/build-Server-RPM/src/cpp

[2019-12-02T18:12:58.568Z] + ./rstudio-tests --scope core

[2019-12-02T18:12:58.568Z] Running core tests...

[2019-12-02T18:12:59.924Z] Using asio type: epoll

[2019-12-02T18:12:59.924Z] Spawning 1000 child procs

[2019-12-02T18:13:02.434Z] ===============================================================================

[2019-12-02T18:13:02.434Z] All tests passed (2103644 assertions in 30 test cases)

[2019-12-02T18:13:02.434Z] 

[2019-12-02T18:13:02.434Z] Running server_core tests...

[2019-12-02T18:13:02.434Z] ===============================================================================

[2019-12-02T18:13:02.434Z] All tests passed (10 assertions in 1 test case)

[2019-12-02T18:13:02.434Z]
```

**Closed by jmcphers** 2019-12-02 23:50 UTC
Labels: builds, developer
