### ISSUE TITLE
Unexpected error when `__sizeof__` is malformed when running Python

### ISSUE THREAD

**Issue by dfalbel** [rstudio/rstudio#13491] opened 2023-08-14 18:26 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2023.09.0-daily+303
    OS Version      : MacOS Ventura 13.5
    R Version       : 4.3.1

### Steps to reproduce the problem

Execute the folling in the reticulate repl:

```
class Obj:
  def __init__ (self):
    self.x = 1
  
  def __sizeof__(self):
    return 1/0

obj = Obj()
```

Once `obj` is created we get an error:

```
── Python Exception Message ──────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 6, in __sizeof__
ZeroDivisionError: division by zero

── R Traceback ───────────────────────────────────────────────────────────────────────────────────────────────────────────────
     ▆
  1. ├─reticulate::repl_python()
  2. │ ├─base::tryCatch(repl(), interrupt = identity)
  3. │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  4. │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  5. │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  6. │ └─reticulate (local) repl()
  7. │   └─reticulate:::readline(prompt = prompt)
  8. └─.rs.reticulate.detectChanges("__main__")
  9.   ├─changedObjects$append(.rs.reticulate.describeObject(var, newObjects))
 10.   └─.rs.reticulate.describeObject(var, newObjects)
 11.     └─sys$getsizeof(object)
 12.       └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
```

### Describe the problem in detail

Once `obj` is defined, the IDE is triggered to call `.rs.reticulate.describeObject` which tries to obtain the object size via:

https://github.com/rstudio/rstudio/blob/cfeca707fc75e11785736cab48e0fd6bef49496f/src/cpp/session/modules/SessionReticulate.R#L1618-L1620

`sys.getsizeof` calls the `__sizeof__` that can raise errors.

### Describe the behavior you expected

Unless the user explicitly calls `sys.getsizeof()` we shouldn't expose the error to the user.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by lucaverteramo** [comment] 2024-04-11 12:49
I believe the issue is still not solved (bumping it for the bot)

**Comment by kevinushey** [comment] 2024-04-11 18:07
Any thoughts on what the right solution here is? Do we need to catch errors when invoking sizeof and return 0 or NA on error, or something similar?

Or is there a way to get the "internal" size of an object, bypassing any dunder methods defined for the class?

**Comment by t-kalinowski** [comment] 2024-04-11 20:07
I don't know of another way. 

What do we use `size` for? Would it be a big loss to blanket return `NA` for Python object sizes? 

The only other way I think of is to setup error handlers:

```r
last_error <- reticulate::py_last_error()
size <- tryCatch(
          sys$getsizeof(object), 
          python.builtin.BaseException = function(e) {
            reticulate::py_last_error(last_error) # restore previous exception
            NA_integer_
         })
```

**Comment by kevinushey** [comment] 2024-04-12 05:12
I think the size here is just for reporting a size in the Environment pane, so it's probably fine for that to be unknown / NA if we couldn't compute it. (Reporting the object size in Python is perilous anyhow, given that objects can be shared...)

**Comment by lucaverteramo** [comment] 2024-04-12 12:06
Could it be related to a bug in the AnnData Python package instead? If the unexpected behaviour is only present when subsetting using this package (see [#1332](https://github.com/rstudio/reticulate/issues/1332#issuecomment-1712127023)

**Comment by t-kalinowski** [comment] 2024-04-12 12:14
In that case, if the bug is so rare it only applies to AnnData in practice, then perhaps the fix is to advise users to call:
```r
reticulate:::py_register_load_hook("anndata", function() {
  reticulate::py_run_string(local = TRUE, r"---(
    AnnData.__sizeof__ = lambda: -2147483648 # R NA_integer_
  )---")
})
```
( and suggest a PR to AnnData )

**Comment by kevinushey** [comment] 2024-04-12 16:50
I think I agree with that. I imagine the implicit contract in `__sizeof__` is that it would return a number, or perhaps some sentinel value for "unknown" sizes (like None?). Either way, I don't think it should throw an exception.

**Comment by jthomasmock** [comment] 2024-04-17 20:53
@t-kalinowski do you mind commenting on their repo given your knowledge of the problem space here?

**Comment by jthomasmock** [comment] 2024-10-18 15:26
@kevinushey and @ronblum -- perhaps we can move this to test given Tomasz thinking it's been resolved upstream 🎉

**Comment by ronblum** [comment] 2024-10-21 20:55
I'm not getting the division by 0 message in the original post. Instead, I'm getting the AnnData message described in the upstream issue using the code at https://github.com/rstudio/reticulate/issues/1332#issue-1574999066. Checked in RStudio Desktop 2024.11.0-daily+309 on Windows 11 with reticulate 1.39.0 and Python 3.12.

```
>>> Error in repl() : AttributeError: 'AnnData' object has no attribute '_X'
  File "<string>", line 1
    Error in repl() : AttributeError: 'AnnData' object has no attribute '_X'
    ^^^^^^^^^^^^^^^
SyntaxError: illegal target for annotation
>>> 
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  AttributeError: 'AnnData' object has no attribute '_obsm'. Did you mean: '_obs'?
Run `reticulate::py_last_error()` for details.
```

**Comment by kevinushey** [comment] 2024-10-24 22:40
Fixed in https://github.com/rstudio/rstudio/commit/772adcf3e19b543acb3a12ce61d35fa4eb7694d4.

**Closed** 2024-10-25 16:42 UTC
Labels: bug, python
