### ISSUE TITLE
No display of the help topic when pressing the F1 button over a Python symbol

### ISSUE THREAD

**Issue by stanreb** [rstudio/rstudio#5982] opened 2020-01-08 17:10 UTC
Hello, 

I recently installed Reticulate v1.14 on RStudio v1.2.5033 with Python v3.8.0 (r-miniconda) and R v3.4.2. I run Mac OS 10.14.
Unfortunatetly, I get no display of the help topic when pressing the F1 button over a Python symbol, contrary to what is described [here](https://rstudio.github.io/reticulate/articles/rstudio_ide.html). 
I get the same issue whether coding in R scripts, in Python chunks of R Markdowns, or in Python scripts.

How could I solve this ?
Thanks for your help.

**Comment by kevinushey** [comment] 2020-01-08 20:46
I've moved this issue to the RStudio repository as this would need to be fixed on the RStudio side.

**Comment by stanreb** [comment] 2020-01-09 06:56
Thank you very much

**Comment by Fred-Wu** [comment] 2020-01-09 09:05
I had this issue too. However, it turns out that F1 only opens the help if you select the autocomplete first then press F1, rather than finish the line by youself. 

For example, if you type np.random.randn(), then press F1, then it won't open the help. 
But if you type np.random.ran (here bunch of suggestions come up, and select randn), then press F1, it works.

**Comment by stanreb** [comment] 2020-01-09 09:11
Absolutely. This is what I also figured out.
But it does work with R code.

**Comment by Fred-Wu** [comment] 2020-01-09 09:30
> Absolutely. This is what I also figured out.
> But it does work with R code.

From my experiences with Spyder and VSCode, autocomplete for Python is very poor. They don't even show suggestions for some functions in the package, or very slow to show, for example, pandas. But RStudio does a good job compared to other IDEs.

**Comment by kevinushey** [comment] 2020-01-11 05:08
Thanks for the extra feedback. To be clear, this is a bug as <kbd>F1</kbd> should work in this context as well; I've marked this for the v1.4 milestone as we aim to make a number of Python-related bugfixes + improvements there.

**Comment by kevinushey** [comment] 2020-07-09 23:09
Closed via https://github.com/rstudio/rstudio/pull/7258.

**Comment by R-Hannibal** [comment] 2020-08-18 20:38
@stanreb, thanks again for finding and reporting this issue. 

We have a fix in place in our latest Daily build of the upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by melissa-barca** [comment] 2020-11-10 22:59
@kevinushey I see this working in Python script files but nothing happens when I try to repro in the Console. Should it work here? 
![image](https://user-images.githubusercontent.com/5323711/98743548-3eb78c80-237e-11eb-83dc-c9164ffe90ca.png)

**Comment by kevinushey** [comment] 2020-11-10 23:12
@melissa-barca it should definitely work there as well. Thanks for catching that; I'll re-open the issue!

**Closed** 2020-11-12 23:47 UTC
Labels: bug, python, verifying

**Comment by melissa-barca** [comment] 2020-11-13 15:38
Verified in 1.4.1027
