### ISSUE TITLE
Dark theme causes blinking white pixel with large vertical window dimension

### ISSUE THREAD

**Issue by AshesITR** [rstudio/rstudio#4464] opened 2019-03-16 10:25 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1327 (current preview)
    OS Version      : Windows 7 x64
    R Version       : R 3.5.1

### Steps to reproduce the problem

 1. Chose a dark theme for RStudio (e.g. Solarized Dark)
 2. Make the window height large (produced with 2160px -- maximized on a 4k monitor without taskbar)
 3. Focus the console window so the cursor starts blinking

### Describe the problem in detail

After following the steps, the cursor alternates with a white pixel.
This can be captured as a screenshot if timed right:

![2019-03-16 11_15_19-RStudio](https://user-images.githubusercontent.com/2363178/54473870-dc3f6f00-47dd-11e9-93a2-7051eaaf9721.png)

The bug does not show with a smaller window height.

### Describe the behavior you expected

No white blinking pixel

**Comment by kevinushey** [comment] 2019-03-16 18:59
I think this is a duplicate of https://github.com/rstudio/rstudio/issues/4390.

**Closed by kevinushey** 2019-03-16 18:59 UTC
