### ISSUE TITLE
Error: package or namespace load failed for ‘org.Hs.eg.db’

### ISSUE THREAD

**Issue by pablo-rodr-bio2** [rstudio/rstudio#9228] opened 2021-04-13 16:00 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      :  Ubuntu 20.04
    R Version       :  4.1 (devel)

### Steps to reproduce the problem
In a new R session inside Rstudio, try to load this library:

`library(org.Hs.eg.db)`
### Describe the problem in detail
If I tried to load this BioConductor package unto my Rstudio R session, it fails with this message:
```
Error: package or namespace load failed for ‘org.Hs.eg.db’:
 .onLoad failed in loadNamespace() for 'org.Hs.eg.db', details:
  call: l$contains
  error: $ operator is invalid for atomic vectors
```
If I enter in an R session in my terminal, this error doesn't exist and the library is fully loaded

```
> library(org.Hs.eg.db)
Loading required package: AnnotationDbi
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min

Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: IRanges
Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following objects are masked from ‘package:base’:

    expand.grid, I, unname
```
This is in my personal workstation, no distributed system whatsoever, where I have full admin privileges
### Describe the behavior you expected

Loading the library into my R session

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2021-04-13 18:22
Duplicate of https://github.com/rstudio/rstudio/issues/9219; caused by a bad update of the RSQLite package.

In the interim, you can either disable the connections observer:

```
options(connectionObserver = NULL)
```

or install an older version of RSQLite; e.g. with:

```
remotes::install_version("RSQLite", "2.2.5")
```

**Closed by kevinushey** 2021-04-13 18:22 UTC

**Comment by siddikiicb** [comment] 2021-04-15 17:46
Just follow this step.
options(connectionObserver = NULL) # problem in loading databases using RSQLite
library(org.Hs.eg.db) # then call the library.

.Problem solved.
Let me know.
Best wishes
Siddik

**Comment by pablo-rodr-bio2** [comment] 2021-04-21 08:26
Thanks both of you! It worked with this workaround.

**Comment by kevinushey** [comment] 2021-04-22 16:24
And it looks like RSQLite has also now been updated on CRAN, so if you update to the latest version the issue should now be resolved. Sorry for the trouble!
