### ISSUE TITLE
Spelling: Enable spell check for md documents

### ISSUE THREAD

**Issue by slopp** [rstudio/rstudio#6988] opened 2020-05-28 17:58 UTC
The 1.3 in-line spell check feature is awesome, but is not available when editing mark down documents. A temporary workaround is to change the file type to Rmd, but this is slightly annoying especially in the context of editing blogdown content (where switching to Rmd adds a step in the rendering preview pipeline). 

Ideally, auto spell check would be enabled for markdown, or there would be an option to enable it just as there is an option for RMD.

**Comment by jmcphers** [comment] 2020-05-29 15:48
@adamconroy Depending on your level of ambition, we could also consider:

a) A user pref which indicates the file types for which spell check is enabled by default
b) A doc property with accompanying command that allows you to toggle real time spellchecking on/off for a single buffer (just as we have for word wrap, rainbow parens, etc.)

**Comment by adamconroy** [comment] 2020-05-29 23:07
Big fan of B over A in general for this feature. I like it.

**Comment by jmcphers** [comment] 2020-06-22 21:26
Moving this to Giant Goldenrod since it's not a bug.

**Closed** 2020-06-30 23:58 UTC
Labels: enhancement, spellcheck

**Comment by R-Hannibal** [comment] 2020-07-18 01:21
Hey @slopp, this enhancement request should be addressed in the [latest preview](https://rstudio.com/products/rstudio/download/preview/) build 1.3.1058.

If you get a chance will you take a look at that build and confirm the enhancement is working/addressing your needs?

**Comment by R-Hannibal** [comment] 2020-07-22 16:13
Excellent, thanks for the assist @slopp.
