### ISSUE TITLE
Text rendering issue with {ggtext} — RStudio 1.4.x

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#7010] opened 2020-05-30 12:49 UTC
RStudio 1.4.419; vanilla R 4.0.1 session (no env/profile); Catalina 10.5.5

Code:

```r
library(ggtext)
library(ggplot2)

ggplot() +
  geom_blank() +
  labs(title = "Yay a title with some words") +
  theme(plot.title = element_markdown(
    family = "EconSansCndBol", face = "bold")
  )
```

It matters not what graphics device I choose in  `General -> Graphics -> Backend`, the above renders like this in all of them:

![image](https://user-images.githubusercontent.com/509878/83328922-8aed9500-a254-11ea-936b-eae92d0d1b36.png)

When I use R.app (so, Quartz, but — again — that doesn't help in RStudio) I get:

![image](https://user-images.githubusercontent.com/509878/83328939-a193ec00-a254-11ea-8201-bc384ed5d66e.png)

I'm not seeing any R error messages; no JS console messages in RStudio; no error messages in Console.app

Tagging @clauswilke since this involves {ggtext} but the bad rendering is happening only in RStudio 1.4.419.

**Comment by clauswilke** [comment] 2020-05-30 15:21
This probably means that font metrics are not properly reported by grid. Does this work with other fonts?

Considering that only the spaces look wrong, the problem might also be that a space is reported to have no width. I'm using code like the following to figure out how wide a space should be. What does it return in your case?

``` r
library(grid)

fontsize <- 12
fontfamily <- "Helvetica"
fontface <- "plain"

convertWidth(grobWidth(textGrob(
  label = " ",
  gp = gpar(
    fontsize = fontsize,
    fontfamily = fontfamily,
    fontface = fontface,
    cex = 1
  )
)), "pt", valueOnly = TRUE)
#> [1] 3.346487
```

<sup>Created on 2020-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hrbrmstr** [comment] 2020-05-30 15:39
If I run the code in `R.app` or just `R` from terminal I get `10.0375`. In RStudio (same version as above) I get `0.7528125`.

**Comment by clauswilke** [comment] 2020-05-30 16:13
Ah, I suspect I know what's going on. Probably the RStudio graphics device has moved to using systemfonts, and systemfonts doesn't report a width for spaces, it only reports an `x_advance` value. The fix would be to use the same in gridtext. The code I'm currently using is a dirty hack, implemented because systemfonts wasn't available at the time. 

``` r
library(systemfonts)
#> Warning: package 'systemfonts' was built under R version 3.6.2

fontsize <- 12
fontfamily <- "Helvetica"

glyph_info(
  " ",
  family = fontfamily,
  size = fontsize
)
#>   glyph index width height x_bearing y_bearing x_advance y_advance       bbox
#> 1           3     0      0         0         0         3         0 0, 0, 0, 0
```

<sup>Created on 2020-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kevinushey** [comment] 2020-05-30 16:32
Reproducing this is a little weird. I can only reproduce if I'm using the `agg` device, _but_ after I've activated that device once in a session, the issue reproduces even if I switch back to the default device.

Regardless, this reproduces the issue independently of RStudio for me:

```
ragg::agg_png("test.png")
p <- ggplot() +
  geom_blank() +
  labs(title = "Yay a title with some words") +
  theme(plot.title = element_markdown(
    family = "EconSansCndBol",
    face = "bold"
  ))
print(p)
dev.off()
system("open test.png")
```

so I suspect the issue is independent (other than the weirdness switching graphics devices in a single session).

**Comment by clauswilke** [comment] 2020-05-30 16:38
@kevinushey This makes sense. ragg uses systemfonts for font lookup. And gridtext caches font metrics. I think this is definitely not an RStudio bug. I can (and probably should) change gridtext to use systemfonts, but a separate question (for ragg) is whether a grob containing a space should report a non-zero width.

cc @thomasp85

**Comment by hrbrmstr** [comment] 2020-05-30 20:51
I did have AGG set as the default each time, so that was my bad for not
stopping/starting RStudio each time.

**Comment by jmcphers** [comment] 2020-06-01 19:25
Not an RStudio issue, so closing here (thanks @clauswilke @hrbrmstr for the thorough investigation!)

**Closed by jmcphers** 2020-06-01 19:25 UTC

**Comment by thomasp85** [comment] 2020-06-04 08:53
This should be fixed in the development version of ragg. The graphic engine is a bit hazy on whether bearings should be included when calculating string width and I apparently opted for the opposite of the base devices. I've switched it now

**Comment by clauswilke** [comment] 2020-06-04 19:12
I can confirm that I get decent-looking text with the development version of ragg and the default settings.

``` r
library(ggplot2)
library(ggtext)

p <- ggplot() +
  geom_blank() +
  labs(title = "Yay a title with some words") +
  theme(plot.title = element_markdown(
    family = "Comic Sans MS",
    face = "bold"
  ))

ragg::agg_png("test.png")
print(p)
invisible(dev.off())
```

<sup>Created on 2020-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Result:

![test](https://user-images.githubusercontent.com/4210929/83800451-0f814e80-a66d-11ea-9bab-4c298d849aaf.png)

Things look even better at higher resolution, e.g.:
``` r
ragg::agg_png("test.png", width = 2000, height = 2000, res = 300)
print(p)
invisible(dev.off())
```
![test](https://user-images.githubusercontent.com/4210929/83800636-596a3480-a66d-11ea-9718-47ba598ffaba.png)

**Comment by thomasp85** [comment] 2020-06-06 09:11
Just for clarification. Your use of "decent", does that imply worse text performance than what you see on the other devices?

**Comment by clauswilke** [comment] 2020-06-06 15:27
I was worried about the resolution-dependent results returned by ragg, but upon further reflection I think ragg does exactly the right thing. The result looks good. If you compare text rendered at, say, 72 dpi vs text rendered at 300 dpi and then downscaled to 72 dpi, you can see that the metrics are slightly different for both spaces and letter shapes, and somehow it balances out for an overall decent result that takes up approximately the same amount of overall space:

<img width="761" alt="Screen Shot 2020-06-06 at 10 17 38 AM" src="https://user-images.githubusercontent.com/4210929/83947861-35c6fb80-a7df-11ea-949f-a9a0bf3981e5.png">

**Comment by thomasp85** [comment] 2020-06-06 17:18
That’s good to hear. It is expected that there’s some difference depending on the resolution as different prepared sizes may be chosen. For small sizes alignment to the pixel grid becomes very important whereas this is less so for high-res/bigger sizes
