### ISSUE TITLE
Keyboard shortcut help not displaying

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#11376] opened 2022-06-07 15:58 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.3+492, 2022.02.2+485
    OS Version      : macOS 11.6.6 (Big Sur / Intel)
    R Version       : Any

### Steps to reproduce the problem

Reported by @jennybc; so far I can't repro on macOS 12.4; don't have a Big Sur machine to try it on.

- Start desktop IDE
- Make sure screen-reader / accessibility mode is OFF
- (1) Help / Keyboard Shortcuts Help
- (2) invoke via Option+Shift+K
- (3) invoke via Command Palette ("Keyboard Shortcuts Help")

### Describe the problem in detail

- (1) nothing happens
- (2) inserts an Apple glyph into the console
- (3) get error:

![Screen Shot 2022-06-07 at 8 48 51 AM](https://user-images.githubusercontent.com/10569626/172425671-35f44981-d8ae-4f57-8b94-c5d93d306371.png)

With screen reader mode on, the feature is working (we show keyboard shortcut help in system web browser when accessibility is enabled).

### Describe the behavior you expected

- keyboard shortcut help shown in a popup

![Screen Shot 2022-06-07 at 9 55 58 AM](https://user-images.githubusercontent.com/10569626/172426606-f43875b4-23ec-4f99-9f40-e9b50f980954.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-06-24 12:45
@gtritchie I'm unable to reproduce this issue, both with screen reader /accessibility turn off and on.

**Comment by jennybc** [comment] 2022-12-22 03:15
I am still on Big Sur 😬 and I still see exactly what was reported earlier. But I would understand if the fact that this involves a rather old OS makes this a wontfix.

**Comment by gtritchie** [comment] 2023-04-27 15:45
Last working in the 2021.09.4-403 release, stopped working in the 2022.02.0-443 release.

**Comment by ronblum** [comment] 2023-05-02 17:53
Verified in RStudio Desktop 2023.05.0-daily+325 on MacOS 13.4. Checked with Vim, Emacs, Sublime, and default key bindings.

**Closed by ronblum** 2023-05-02 17:53 UTC
Labels: regression, key bindings
