### ISSUE TITLE
Autocompletion doesn't work for columns in data frame imported from SPSS

### ISSUE THREAD

**Issue by JamesGillerITS** [rstudio/rstudio#14672] opened 2024-05-08 17:54 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  2024.04.0 Build 735
    OS Version      :  Windows 10 Pro (Version 22H2)
    R Version       : 4.0

### Steps to reproduce the problem

Read data using `read_sav` from the [Haven](https://haven.tidyverse.org/index.html) package (version 2.5.4).
Try to use autocompletion to access columns in the data set.

### Describe the problem in detail

Typing the first few characters of the data set variable name triggers autocompletion normally.

![dataset_autocomplete](https://github.com/rstudio/rstudio/assets/93404827/fab5bf3f-f33b-40bd-a70e-d11f9c2a95ba)

When trying to use `$` to access a column, autocompletion results in `(No matches)`.

![dataset_no_matches](https://github.com/rstudio/rstudio/assets/93404827/3d84ce76-df61-44b1-bb81-86226c9d74fb)

Autocompletion works with built in dataset `mtcars`, and another SAV file found on Github: https://github.com/UtrechtUniversity/R-data-cafe/blob/master/exercises/practiceFileReading/data/mtcars.sav

The problem only became apparent after installing the latest version of RStudio.

### Describe the behavior you expected

I expected to see a tooltip with a list of column names for my data set, and to be able to autocomplete code to access columns using `$`.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-05-08 19:40
@JamesGillerITS Thank you for raising this! I'm unable to reproduce the issue, though. I've tried importing a few SPSS datasets and autocomplete works. Can you provide a sample input file that we can use to reproduce the issue?

**Comment by laivincent528** [comment] 2024-05-08 21:07
Thank you for posting this! I was having the exact same issue and thought that I was just going mad. I'm not able to provide a sample file at this time, but in case it's helpful I am able to create a dataframe containing variables from the original dataset and autocompletion does work on it. The dataset that was giving me issues is also pretty large, with over 7000 columns. When downgrading RStudio versions, the autocompletion works as expected. I hope this helps at all!

**Comment by ronblum** [comment] 2024-05-09 13:50
@laivincent528 How did you create the dataframe--was it also by importing using `read_sav()`?

**Comment by ronblum** [comment] 2024-05-09 13:58
Also, I tried both a 10K x 10K dataframe created in R and the same importing with `read_sav()` but both give me the column names.

**Comment by JamesGillerITS** [comment] 2024-05-09 17:56
> @JamesGillerITS Thank you for raising this! I'm unable to reproduce the issue, though. I've tried importing a few SPSS datasets and autocomplete works. Can you provide a sample input file that we can use to reproduce the issue?

Hi @ronblum, unfortunately I can't provide the data file in question, as it contains confidential information. As with @laivincent528, I can select a subset of the columns in the data into another variable, which can then be used with autompletion normally. It may be an issue with some particular variable(s) in the data.

**Comment by kevinushey** [comment] 2024-05-09 19:03
Thanks, but unfortunately unless you can provide us with an example that can help us reproduce the issue locally, we will be unable to fix this issue.

**Comment by kevinushey** [comment] 2024-05-09 19:10
Much appreciated! Please keep us informed.

**Comment by PanosChatzi** [comment] 2024-05-13 09:42
Hi all. I have noticed the exact same issue and I was worried that there was something wrong with my laptop or installation.

Like in James case, accessing the data with dollar sign ($) doesn't provide any matches using the current desktop version of RStudio ("2024.04.0+735"), however, it seems to work in a previous version in Posit cloud ("2023.12.1+402.pro1"). Also, this issue seems to occur when exporting data to '.sav' format using the current version of SPSS (v29). When I tried some older '.sav' files it worked okay.

Please, find attached a '.sav' file downloaded from the internet which works (manipulate.sav), and a sample dataset exported from SPSS v29 (test_data.sav) which doesn't work.

Let me know if that helps.

**Comment by kevinushey** [comment] 2024-05-13 17:09
Thanks! I was able to reproduce the issue locally; this is a regression from recent work to support variable labels in the completion popup display. We'll take a look.

**Comment by PanosChatzi** [comment] 2024-05-14 09:12
Glad it helped! Thanks!

**Comment by kateto** [comment] 2024-05-20 00:09
Same problem here. I think it may be related to labels (`haven_labelled` class) --- when I use `zap_labels()` on the tibble containing the SPSS-imported data, autocomplete starts working again.

**Comment by melindahiggins2000** [comment] 2024-05-29 21:29
I agree. I just upgraded my RStudio yesterday to "2021.04.1 Build 748" running on `R version 4.4.0 (2024-04-24 ucrt); Platform: x86_64-w64-mingw32/x64; Running under: Windows 11 x64 (build 22000)`. When I read in a SPSS dataset using `df <- haven::read_sav("dataset.sav")`, the auto-complete no longer works for the resulting data frame which is of class: `"tbl_df"     "tbl"        "data.frame"`. I look forward to downloading the bug-fix when ready. Thank you.

**Comment by melindahiggins2000** [comment] 2024-05-31 12:32
> I agree. I just upgraded my RStudio yesterday to "2021.04.1 Build 748" running on `R version 4.4.0 (2024-04-24 ucrt); Platform: x86_64-w64-mingw32/x64; Running under: Windows 11 x64 (build 22000)`. When I read in a SPSS dataset using `df <- haven::read_sav("dataset.sav")`, the auto-complete no longer works for the resulting data frame which is of class: `"tbl_df" "tbl" "data.frame"`. I look forward to downloading the bug-fix when ready. Thank you.

This morning, I rolled back to the previous RStudio version `RStudio-2024.04.0-735.exe` and still have the same issue. However, I then rolled back one more version to `RStudio-2023.12.1-402.exe` and autocompletion now works for a SPSS dataset read in using `haven_2.5.4` where the dataset includes labeled variables of class `"haven_labelled" "vctrs_vctr"     "double"`.

`sessionInfo()`

```
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22000)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] haven_2.5.4 dplyr_1.1.4

loaded via a namespace (and not attached):
 [1] gtable_0.3.4       compiler_4.4.0     tidyselect_1.2.1  
 [4] Rcpp_1.0.12        ggstats_0.5.1      tidyr_1.3.1       
 [7] scales_1.3.0       yaml_2.3.8         fastmap_1.1.1     
[10] GGally_2.2.1       ggplot2_3.4.4      R6_2.5.1          
[13] plyr_1.8.9         generics_0.1.3     knitr_1.45        
[16] forcats_1.0.0      tibble_3.2.1       munsell_0.5.0     
[19] pillar_1.9.0       RColorBrewer_1.1-3 rlang_1.1.3       
[22] utf8_1.2.4         xfun_0.42          cli_3.6.2         
[25] magrittr_2.0.3     digest_0.6.35      grid_4.4.0        
[28] rstudioapi_0.15.0  hms_1.1.3          lifecycle_1.0.4   
[31] vctrs_0.6.5        evaluate_0.23      glue_1.7.0        
[34] fansi_1.0.6        colorspace_2.1-0   rmarkdown_2.26    
[37] purrr_1.0.2        tools_4.4.0        pkgconfig_2.0.3   
[40] htmltools_0.5.7   
```

**Comment by hsbizahlenzauber** [comment] 2024-06-14 12:23
Maybe this MWE help. I think it's not an issue of SPSS import but of variable attributes.

data(mtcars)


#try autocompletion, it works as expected in RStudio editor

#mtcars$
  

#  Give attribute to variable in data.frame

attr(mtcars$cyl, "labels") <- c("few"=4, "some"=6, "many"=8)


#try autocompletion, it does not work as expected in RStudio editor anymore

#mtcars$

**Comment by melindahiggins2000** [comment] 2024-06-14 12:46
@hsbizahlenzauber Thank you for your suggestion. Unfortunately, many of my SPSS files have 3000-4000+ variables and trying to fix attributes one at a time is not feasible. Until a patch becomes available, I have rolled back to an earlier version that works. I do appreciate your post and suggestion!

**Comment by hsbizahlenzauber** [comment] 2024-06-14 12:52
I agree that it's a bug. My comment was only intended to help find the cause.

**Comment by kevinushey** [comment] 2024-06-14 16:48
Looks like this should be fixed in the latest daily builds via https://github.com/rstudio/rstudio/pull/14788.

**Comment by ronblum** [comment] 2024-06-24 13:46
Verified in RStudio Desktop 2024.07.0-daily+245 on Windows 11. If anyone tries it out (for testing purposes only, not production use), please let us know!

**Closed by ronblum** 2024-06-24 13:46 UTC
Labels: bug, autocompletion, regression

**Comment by hsbizahlenzauber** [comment] 2024-06-25 07:49
Thanks a lot. For my system everthing is fine now.
