### ISSUE TITLE
cygheap mismatch detected when running GNU tools in RStudio terminal

### ISSUE THREAD

**Issue by mbojan** [rstudio/rstudio#6809] opened 2020-05-05 15:28 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.956
    OS Version      : Windows 10
    R Version       : 4.0.0

### Steps to reproduce the problem

Open the Tools/Terminal

### Describe the problem in detail

I mentioned that problem in #6801 and it persists when, fllowing the suggestion from #6801, I installed the preview version of RStudio. I was getting similar errors earlier, but now with a more informative message:

```
      0 [main] cut (11840) C:\rtools40\usr\bin\cut.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x180316408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```

Similar errors pop-up when I try to run `locate`, `which` and so on.

Following the instruction however, Windows does not find any instance of `cygwin1.dll` on my system using file search. Rebooting did not help. I can find tools like `cut.exe` both in Rtools and in Git for Windows (I have both in my `PATH`). 

### Describe the behavior you expected

I would like to execute these commands in the RStudio terminal.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2020-05-05 16:07
Closely related to #6696

**Comment by mbojan** [comment] 2020-05-05 16:18
Indeed, might be basically the 💥 for 💣 mentioned there...

**Comment by kevinushey** [comment] 2020-05-05 17:19
Does removing Git for Windows from your PATH make a difference?

It would be helpful to know the whole PATH seen in the terminal; e.g. the output of:

```
echo $PATH | tr ':' '\n'
```

may be helpful.

**Comment by mbojan** [comment] 2020-05-05 17:30
Here is the `PATH` as seen in the terminal. I can't use `tr` due to the same fatal error, but I `strsplit`ted it in R:

```
 [1] "/c/rtools40/usr/bin"                                                                
 [2] "/c/Program Files/R/R-4.0.0/bin/x64"                                                 
 [3] "/c/Rtools/bin"                                                                      
 [4] "/c/Program Files (x86)/Common Files/Oracle/Java/javapath"                           
 [5] "/c/ProgramData/Oracle/Java/javapath"                                                
 [6] "/c/WINDOWS/system32"                                                                
 [7] "/c/WINDOWS"                                                                         
 [8] "/c/WINDOWS/System32/Wbem"                                                           
 [9] "/c/WINDOWS/System32/WindowsPowerShell/v1.0"                                         
[10] "/c/WINDOWS/System32/OpenSSH"                                                        
[11] "/c/Program Files (x86)/Calibre2"                                                    
[12] "/c/Program Files/Predictive Solutions/PS IMAGO PRO/5/IBM/SPSS/Statistics/25/JRE/bin"
[13] "/c/ProgramData/chocolatey/bin"                                                      
[14] "/cmd"                                                                               
[15] "/c/Program Files/Docker/Docker/resources/bin"                                       
[16] "/c/ProgramData/DockerDesktop/version-bin"                                           
[17] "/c/Users/mbojanowski/AppData/Local/Microsoft/WindowsApps"                           
[18] "/c/Users/mbojanowski/AppData/Local/Programs/MiKTeX 2.9/miktex/bin/x64"              
[19] "/c/Program Files (x86)/Oni"                                                         
[20] "/c/Users/mbojanowski/AppData/Local/Pandoc"                                          
[21] "/c/Program Files/RStudio/bin/rpostback"                                             
[22] "/c/Program Files/RStudio/bin/postback"                                              
[23] "/bin"                                                                               
[24] "/c/Program Files/RStudio/bin/msys-ssh-1000-18"  
```

Note that `[3]` is vacuous because that dir no longer exists.

**Comment by gtritchie** [comment] 2020-05-05 17:39
See also: #6696

**Comment by jeroen** [comment] 2020-05-05 17:40
@mbojan @gtritchie as a test can you run this in your rstudio terminal tab:

```sh
PATH="/usr/bin:$PATH"
```

After that the problem is probably gone.

**Comment by mbojan** [comment] 2020-05-05 17:43
Indeed @jeroen ! So where is the initial mess coming from? Git Bash? I don't think I understand this...

**Comment by jeroen** [comment] 2020-05-05 17:44
No it's a bug in rstudio. In bash `/usr/bin` should always be on the front of the path.

**Comment by mbojan** [comment] 2020-05-05 17:45
I'm looking at:

```
$ which -a which
/usr/bin/which
/c/rtools40/usr/bin/which
/bin/which
```

Does that mean there are different versions of the GNU tools in these places?

**Comment by mbojan** [comment] 2020-05-05 17:47
I do have `PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"` in `.Renviron` as adivsed by Rtools.

**Comment by jeroen** [comment] 2020-05-05 17:48
@mbojan yes indeed. Try looking at `cygpath -m /` to see where `/` actually is. It is the git4win bash, but that one first on the path, and so things get mixed up.

**Comment by mbojan** [comment] 2020-05-05 17:52
OK, I see it is so.

So what would be the best warkaround apart from manually modifying `PATH` after launching RStudio?

**Comment by jeroen** [comment] 2020-05-05 17:54
I hope they'll fix it on their end :-)

**Comment by mbojan** [comment] 2020-05-05 17:58
Yeah :)

 Is there any location that RStudio Terminal expects a `.bashrc`  (or else) to reside?

**Comment by gtritchie** [comment] 2020-05-06 01:33
> Is there any location that RStudio Terminal expects a .bashrc (or else) to reside? I could modify the PATH there.

If you're using git-bash it looks for `~/.bash_profile`, but that's nothing to do with RStudio itself.

**Comment by gtritchie** [comment] 2020-05-07 16:25
Fixed via #6828 (this fix is in 1.3-patch, and will be in master/1.4 shortly)

**Closed by gtritchie** 2020-05-07 16:25 UTC
Labels: desktop, terminal, windows

**Comment by R-Hannibal** [comment] 2020-06-03 14:46
Hey @mbojan, we have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).
  
If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by mbojan** [comment] 2020-06-04 17:40
Thanks @R-Hannibal , I'll try and post the results here.

**Comment by R-Hannibal** [comment] 2020-07-06 21:56
Verified Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows 10 x64 - Desktop/Server 

Tested the fix along with the additional areas listed in [QA Notes](https://github.com/rstudio/rstudio/pull/6828#issue-414453310), comparison testing between 1.3.959 and 1.3.1054. Fix looks both successful and stable.

**Comment by edonnachie** [comment] 2020-07-17 11:10
This fix does not work for me:
RStudio Version - 1.3.1054, R Version - 4.0.2, Windows Server 2016 x64

**Comment by R-Hannibal** [comment] 2020-07-17 15:56
@edonnachie - could you provide us with some more detail on your environment, what you're seeing/how you are reproducing the issue? 

Our internal testing indicated this issue was fixed in the latest [stable release](https://rstudio.com/products/rstudio/download/) of the IDE. Not to say what you're seeing is invalid, but reproduction or environment variables of the issue may have shifted and any additional detail you can provide will help us to verify what you're seeing is in fact this same issue or perhaps a new one caused by our code-fix. Thanks for your help.

**Comment by edonnachie** [comment] 2020-07-17 21:44
I believe the problem is that I'm trying to use make, which is only provided by RTools. The Git version of bash is not compatible with binaries from RTools40 (see the error message in the problem description above). I did not have such a problem with RTools35, or indeed with the archaic UnixUtils.

The solution for me is to set `C:/rtools40/usr/bin/bash.exe` as my default terminal. This does allow me to call the git binary (which is added to the PATH).

**Comment by gtritchie** [comment] 2020-07-17 21:59
@edonnachie Great detective work; yes, I can reproduce that problem by running `make`.

We have an open request to provide an option to use RTools40 as the default shell in the terminal (maybe even make it the default, when detected), but likely won't get to it soon: #6810

Configuring it manually as you have done is a reasonable approach in the meantime; I also updated the Terminal support article to mention this as well: https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal#rtools

**Comment by edonnachie** [comment] 2020-07-17 22:24
Thank you, that helps a lot.

I've added the following to my `rstudio-prefs.json` and everything is good:

```
	"windows_terminal_shell": "custom",
	"custom_shell_command": "c:/rtools40/usr/bin/bash.exe",
	"custom_shell_options": "--login -i"
```

**Comment by VincentHin** [comment] 2021-01-05 10:05
I'm getting the same error message as @mbojan in beginning of this thread in Rstudio terminal, for example:

`R CMD config CFLAGS`

results in:

`
1 [main] make (2744) C:\rtools40\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180348408/0x180316408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
`

If I set the Custom Shell binary to `C:/rtools40/usr/bin/bash.exe` in Terminal Options (suggested by @edonnachie) it cannot find  `R`:
`
hin001@L0603730 MSYS ~
$ R CMD config
--login: R: command not found
`

Any suggestions on how to fix this?

I'm running:
Rstudio version: 1.3.1093
R version 4.0.2 (2020-06-22)
Windows 10 enterprise v 1909

I have in my .Renviron file:  `PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"` and running Sys.getenv("PATH") gives:

`
 "C:\\rtools40\\usr\\bin;C:\\Program Files\\R\\R-4.0.2\\bin\\x64;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Program Files\\Git\\cmd;C:\\Users\\hin001\\AppData\\Local\\Microsoft\\WindowsApps"
`

but when in run `echo $PATH` in Rstudio terminal it's prepended with some additional paths: 
`
/mingw64/bin:/usr/bin:/c/Users/hin001/bin:/c/rtools40/usr/bin:/c/Program Files/R/R-4.0.2/bin/x64:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/MiKTeX 2.9/miktex/bin/x64:/cmd:/c/Users/hin001/AppData/Local/Microsoft/WindowsApps:/c/Program Files/RStudio/bin/postback:/bin://WURNET.NL/Homes/hin001:/c/Program Files/RStudio/bin/msys-ssh-1000-18
`
