### ISSUE TITLE
Opening a project from the terminal results in errors

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#12893] opened 2023-03-23 16:53 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03
    OS Version      : Ubuntu 22.04
    R Version       : 4.2.2

### Steps to reproduce the problem

Open the terminal from Nautlius (the default folder browser) or other .
In the terminal open a project with `rstudio project.Rproj`.

### Describe the problem in detail

If I open the project via the graphical interface I can open it normally. 
This is not limited to one project.
I can open rstudio if I don't specify a *.Rproj (`rstudio`) and then I open the project I'm interested from the top right menu.

This is a new machine with none or very few configurations (the only that might be is that the user is provided by Windows while the computer is a Linux so it has a REALM domain and the terminal is user@REALM@Computer).
I have rig installed to change R versions and I installed the latest updated via `apt install ./rstudio*.deb`

My bash profile doesn't have much configured: a openssl key, a few alias, conda deactivated by default.
This user has not root permissions. 

<details>
<summary>Diagnosis and log report</summary>

This is the automatic report generated by RStudio:

### RStudio Version

RStudio 2023.03.0+386 "Cherry Blossom " (3c53477a, 2023-03-09) for Ubuntu Jammy

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 1. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Logs

*/home/lrevilla@irsicaixa.es/.local/share/rstudio/log/rsession-lrevilla@irsicaixa.es.log*

```
2023-03-23T16:13:23.696346Z [rsession-lrevilla@irsicaixa.es] ERROR system error 2 (No such file or directory); OCCURRED AT rstudio::core::Error rstudio::core::FilePath::getChildren(std::vector<rstudio::core::FilePath>&) const src/cpp/shared_core/FilePath.cpp:931; LOGGED FROM: rstudio::core::Error rstudio::session::projects::ProjectContext::startup(const rstudio::core::FilePath&, std::string*) src/cpp/session/projects/SessionProjectContext.cpp:268
2023-03-23T16:13:23.696703Z [rsession-lrevilla@irsicaixa.es] ERROR system error 2 (No such file or directory) [path: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::makeCurrentPath(bool) const src/cpp/shared_core/FilePath.cpp:1400; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2248
2023-03-23T16:13:23.696703Z [rsession-lrevilla@irsicaixa.es] ERROR system error 2 (No such file or directory) [path: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::makeCurrentPath(bool) const src/cpp/shared_core/FilePath.cpp:1400; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2248

```
                
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/11053367/diagnostics-report.txt)

</details>

### Describe the behavior you expected

I would expect being able to open a project via rstudio project.Rproj, but perhaps this is not expected.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by pbreheny** [comment] 2023-03-31 13:51
Same as #12495

**Comment by gtritchie** [comment] 2023-03-31 14:31
Duplicate of #12495.

**Closed by gtritchie** 2023-03-31 14:31 UTC
Labels: bug, duplicate, new
