### ISSUE TITLE
The "help" pane becomes unresponsive after entering in any "demo" page

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#13263] opened 2023-06-20 05:26 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.0 Build 421
    OS Version      : Ubuntu 22.04.2 LTS
    R Version       : 4.3.1 (2023-06-16)

### Steps to reproduce the problem
Using the defaults settings:

1. Trigger the help for any function (for example `?filter` in the stats package)
2. In the "help" pane, click the "home" button (i.e., Show R Help)
3. The "home" page is now displayed
4. Return to the `filter` function help page with the back button
5. Click on "Index" at the bottom
6. Click on "Code demos"
7. Click the "home" button. Nothing happens
8. Type `?filter`. Nothing happens

### Describe the problem in detail
Once entered the "demo" mode, the "help" pane is completely locked. RStudio must be closed and reopened in order for the "help" pane to be responsive again.

### Describe the behavior you expected
The "help" pane to be responsive after entering the "demo" mode.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment] 2023-07-06 19:32
This seems to have changed since moving to Electron. The previous behaviour would open the code demo in the default browser. Now, it is opening within the pane and cannot navigate back.

An interesting piece that might help is that the URL to the code demo goes to the rsession, which redirects to the code demo. Both run on local host but different ports.

**Comment by ronblum** [comment] 2023-08-01 13:36
Checked in 2023.09.0-daily+290. Now, instead of a failure, the correct help page is opened in a web browser—similar to #13392 but at least the contents are shown instead of 127.0.0.1.

**Comment by timtmok** [comment] 2023-08-16 19:46
@ronblum This sounds like it is expected if the page loads correctly in the user's browser. I tried this in Prairie Trillium (pre-Electron) and it opens in the browser.

**Comment by ronblum** [comment] 2023-08-16 21:33
Confirmed!

**Closed** 2023-08-24 21:55 UTC
Labels: bug, help pane
