### ISSUE TITLE
Mouse scrolling sometimes stops working

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#7845] opened 2020-09-21 17:31 UTC
Windows 10, RStudio 1.3.1073

This is an issue I cannot reliably reproduce.

Sometime this summer I started noticing that I can work in RStudio for a while and suddenly the mouse scrolling would stop working. I would no longer be able to scroll up/down in any of the panes. Outside of RStudio I would still be able to scroll with my mouse. Both the laptop's trackpad two-finger scroll would stop working, and also using a USB mouse with an actual scrolling wheel wouldn't work.  I didn't pay too much attention to it initially because I attributed it to having an old laptop.

I have a brand new laptop and I've had this issue twice this week. I still cannot reproduce it consistently, it just happens suddenly. Closing and re-opening RStudio seems to always fix it.

**Comment by R-Hannibal** [comment] 2020-09-24 17:26
@daattali - thanks for finding and reporting this issue.

I haven't been able to reproduce the issue thus far on my Windows 10 laptop (as you mentioned it appears the issue is inconsistent, so I may just not have hit the right conditions to reproduce it yet). Have you noticed any patterns at all in the occurrence of the issue (only happens after sleep, after RStudio has been running for awhile, etc.)? 

If it occurs again and you can grab a video of it and add it to the issue report ([Video to gif converter](https://ezgif.com/video-to-gif)), that may help us to track this down as well.

**Comment by daattali** [comment] 2020-09-24 17:29
I only get the issue after RStudio had been running for a while, but that's because my RStudio is usually just always open. Couldnt find any other patterns unfortunately

**Comment by R-Hannibal** [comment] 2020-10-15 21:14
@daattali - I still haven't been able to reproduce this issue unfortunately (tried a soak test by leaving the IDE running on my Windows laptop overnight, but still not getting it).

This is a tough one to tackle currently due to our inability to reproduce the issue in-house and the lack of reports from other users experiencing the same issue (often with more data-points it helps to identify the pattern of causal factors which produce the issue). Curious if you're still seeing this issue on our [latest daily builds](https://dailies.rstudio.com/) of the upcoming 1.4 release of RStudio? 

Please let us know if you're still seeing the issue there and/or provide a gif of the issue occurring and we'll take another look at this.

**Comment by daattali** [comment] 2020-10-15 21:59
A GIF won't show you much information, since you can't see that I'm scrolling with my fingers on the mouse. You can close this issue if you don't want to have open non repro issues.

**Comment by kevinushey** [comment] 2020-10-15 22:31
Other things worth checking:

1. Where exactly are you trying to scroll? Source pane, console pane, elsewhere?
2. Does your ability to scroll depend on what pane you're trying to scroll? (source; console; Files pane; etc)
3. Can you identify any patterns around how you're using RStudio? E.g. developing a Shiny application; working with an R Markdown document; something else?
4. Does it depend on what other applications you have open?

Thus far we haven't had any reports of this issue so it may be something unique to the way you've configured your system.

**Comment by daattali** [comment] 2020-10-15 22:47
1. All of the above. Help files, Environment, git, source, console, everywhere within RStudio
2. Unable to scroll in all panes
3. I'm almost always doing Shiny work. Not doing Rmd
4. I only have Chrome open with 1-5 tabs and a Notepad window, and sometimes PuTTY. Nothing exceptional

Non deterministic issues are a real pain..... really, if nobody else is experiencing this, we can chalk this up to random errors on my system and close.

**Comment by mikebessuille** [comment] 2020-11-09 18:45
We have no additional reports on this issue and cannot reproduce in house.  If additional detail becomes available we can reopen the issue.

**Comment by daattali** [comment] 2020-12-31 06:12
It's happening to me now again, on a different machine.

I don't know what I did to get to this point. Scrolling was working for me all day, I went to shower and eat and came back and now it doesn't. I'm not running any jobs in RStudio, not using database connections, not doing anything unusual.

I know it sounds crazy so I hooked up an external mouse and took a video with two RStudio sessions where you can visibly see me trying to scroll. In the old session scrolling doesn't work.

Video: https://imgur.com/CtsJ0zZ

**Comment by kevinushey** [comment] 2021-01-04 19:39
Thanks! We believe you; the challenge remains figuring out how to reproduce this issue locally for us.

Did your computer go to sleep / shut down in that interval? Could the issue somehow be triggered by that? Is there anything you can do to "escape" that state, beyond restarting RStudio altogether?

**Comment by daattali** [comment] 2021-01-04 21:17
The computer stayed awake the entire time. I haven't found any way to fix any RSstudio instance affected by this, only closing the process and opening a new IDE "solves" it.

**Comment by ztreisman** [comment] 2021-03-27 19:04
I've also had this issue, running 1.3.1093 on Ubuntu 20.04. After closing and reopening RStudio, the scroll wheel works again. Chrome, Terminal, Files and OpenOffice were also open.

**Comment by alankjackson** [comment] 2021-06-12 03:30
I recently started having this same issue. 
RStudio Version 1.3.959
Ubuntu 18.04.5 LTS
Closing Rstudio and then restarting it seems to work.
No idea why it started happening.

**Comment by doliv071** [comment] 2021-12-17 18:41
I am having this issue as well. Interestingly if I have multiple Rstudios open it will happen on one but not all of them.

**Rstudio Version:**
RStudio 2021.09.0+351 "Ghost Orchid" Release (077589bcad3467ae79f318afe8641a1899a51606, 2021-09-20) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**R version:**
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.1                         
year           2021                        
month          08                          
day            10                          
svn rev        80725                       
language       R                           
version.string R version 4.1.1 (2021-08-10)
nickname       Kick Things

**Comment by daattali** [comment] 2021-12-17 21:45
I still get this issue sometimes as well, but I don't know how to reproduce it

**Comment by doliv071** [comment] 2021-12-17 22:03
I will keep an eye on it and see if I can reproduce. I suspect it might be caused by a crash/restart situation which I have been having related to issue #7310 ...

**Comment by Lvulis** [comment] 2022-03-11 21:19
Have been experiencing this as well. 
RStudio Version 1.4.1717;
Windows 20H2 19042.1526

**Comment by mikebessuille** [comment] 2022-03-15 13:48
@gtritchie any chance this is a QT bug which could be fixed by Electron?

**Comment by gtritchie** [comment] 2022-03-15 14:23
It's a possibility but we won't know unless we can reliably reproduce.

**Comment by fmongela** [comment] 2022-04-13 11:38
Have been experiencing this as well, not reproducible, very annoying !
Windows 10 Pro 21H2 19044.1586
RStudio 2022.02.0+443

**Comment by daattali** [comment] 2022-04-13 20:33
Glad to see I wasn't imagining things :p

**Comment by doliv071** [comment] 2022-04-13 22:18
In the interest of hopefully coming up with a reproducible example, can we start collecting `sessionInfo()` when this happens?

I now have a project that will consistently stop scrolling which makes me suspect it is related to the packages I have loaded.

here is my current scroll-locked session info https://pastebin.com/MKpqMSwQ

**Comment by daattali** [comment] 2022-04-14 01:43
If you can get a project to deterministically get this issue, it would be helpful to try it on a different machine or a newer RStudio version. If that still happens, you have a great test case to give RStudio to work with!

**Comment by mikebessuille** [comment] 2022-04-14 12:59
reopening as it's clearly still an issue.  However, I'm not sure we can do anything about it without some help with a reproduction case, as all our internal efforts to reproduce have failed.

**Comment by kevinushey** [comment] 2022-04-14 16:38
There's a chance this will be fixed with the move to Electron as well.

**Comment by netique** [comment] 2022-04-24 13:30
Maybe it is slightly OT, but has anyone spotted a different scrolling speed in the Electron version? Qt behaves the same as the rest of the system (on macOS, but I remember it affected Windows as well). Like it is away faster, recognizably so, and it makes the usage uncomfortable at least (this and the "Open in new Window" issue are the reason why I stopped using the Electron version). From my observation it seems that maybe the app is not paying much attention to the dynamics of scrolling, i.e. the distance is not mapped linearly to the actual arc distance of the scroll wheel or distance of the finger on a touchpad.

**Comment by maciasd** [comment] 2022-04-26 23:25
I have had this issue for months. I deleted and updated both my R and Rstudio to the latest versions and also changed my DPI settings, which others had suggested may be the reason the trackpad stops working. 

Please help. This is extremely annoying.

**Comment by kevinushey** [comment] 2022-04-26 23:41
If you're willing to test, we have daily builds of RStudio built with Electron available for each platform here:

https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/windows/
https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/macos/
https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/bionic/

(Alternatively, take a look at the URLs at https://dailies.rstudio.com/ and replace 'desktop' with 'electron' as appropriate.)

These are not yet ready for public preview, but might be worth giving some early testing.

**Comment by ronblum** [comment] 2022-07-13 14:47
Update: As we're switching to the Electron framework, we're hoping that switching over resolves the issue. If anyone is will to try it out, that would be very helpful, since we haven't been able to reproduce the issue internally. 

Electron builds as [a preview of the most recent release, Spotted Wakerobin 2022.07.0+548](https://www.rstudio.com/products/rstudio/download/preview/#:~:text=Desktop%20Electron%20Version). For the Elsbeth Geranium release currently in development, [the RStudio Desktop builds are all Electron-based](https://dailies.rstudio.com/#:~:text=Open%20Source-,RStudio%20Desktop,-Windows%2010%2B). Please note that these are meant for testing and development purposes, not production.

Regarding the scrolling speed, please see issue #11578.

**Comment by dle081984** [comment] 2022-07-25 16:13
I just had this issue today.  I'm on Windows 11 home edition with chrome, MS teams, slack, and command prompt open.  My RStudio session has been running for a few days but the scrolling was working this morning.  I first noticed it after running some code that threw an exception and put RStudio in debug mode.  I can still scroll in the script pane but everything else (help, console, environment, etc.) doesn't work.

**Comment by mikebessuille** [comment] 2022-07-25 17:35
@dle081984 can you confirm whether you were running the Electron version?  We believe this is fixed in our electron-based IDE per https://github.com/rstudio/rstudio/issues/7845#issuecomment-1183319449.  Would be great to hear if that resolves your issue!

**Comment by Lvulis** [comment] 2022-07-25 17:53
Just as a followup this hasn't occurred at all for me since March and I am now on "Prairie Trillium" Release (1db809b8, 2022-05-20) for Windows.

**Comment by dle081984** [comment] 2022-07-25 18:08
@mikebessuille I am running "Prairie Trillium" Release (1db809b8, 2022-05-20) for Windows.

**Comment by ronblum** [comment] 2022-08-12 15:53
Although we believe that this issue is fixed by Electron, I'll hold off on closing this at the moment. If anyone tries one of the in-development builds from [the current release (2022.11.0)](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/macos/) and continues to run into this issue, please let us know!

**Comment by mikebessuille** [comment] 2022-09-19 14:40
We believe this has likely been fixed by the move to Electron, so closing this.  If you still see it happening and are running an Electron build (2022.11), please comment and we can reopen.

**Closed by mikebessuille** 2022-09-19 14:40 UTC
Labels: bug, not reproducible, repro needed, electron

**Comment by weraborek** [comment] 2022-11-08 11:49
Just happened to me. I can scroll outside of R studio, and I can use the side bar to move up and down the script/console. But I cannot scroll within R studio. This has never happened to me before, and was fixed by Rstudio restart. 
The working directory in which the .Rproj file lives is on a remote drive (Google drive) which is linked using the Drive app and which is available for offline access. The connection with this drive very occasionally drops for a second or two. This should be solved y the fact that the workign directory is available for offline access (i.e. saved locally). I am adding this information, because in my experience all sort of weird inexplicable stuff happens to Rstudio with network drives, especially if the connection is not very very stable. 

**R version**                           
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          2.2                              
year           2022                             
month          10                               
day            31                               
svn rev        83211                            
language       R                                
version.string R version 4.2.2 (2022-10-31 ucrt)
nickname       Innocent and Trusting    

**OS**
Windows !0 Pro, 10.0.19045 

**R studio**
"Spotted Wakerobin" Release (e7373ef8, 2022-09-06) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by kevinushey** [comment] 2022-11-08 16:56
Should be fixed in the daily builds of RStudio (https://dailies.rstudio.com)
