### ISSUE TITLE
Cells in numeric columns in data viewer not right-aligned

### ISSUE THREAD

**Issue by petrbouchal** [rstudio/rstudio#6314] opened 2020-02-25 12:05 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.863 (daily build)
    OS Version      : MacOS 10.15.3
    R Version       : 3.6.2

### Steps to reproduce the problem

```
View(iris)
```

also integers:
```
x <- iris
x$y <- 1L
View(x)
```

### Describe the problem in detail

Numbers in cells in the data viewer are not right-aligned. This is true of doubles and integers.

This has been the case for a while but I am not aware when exactly it appeared; certainly present in both the current preview release and daily build.

I managed to fix this in developer tools by temporarily editing the `numberCell` style in dtstyles.css, adding a `display: block` parameter, as per https://stackoverflow.com/questions/17367121/css-right-align-rule-not-working. But this file lives inside the RStudio "application" so would be overwritten with every update.

The locale in my R session is "en_US.UTF-8" so nothing strange there; I suspect this is caused by something odd about the rendering engine on my machine (since there are no other reports of this issue), though I am not aware of anything specific that could cause this. But I wonder if adding the above line to the dtstyles.css might help without breaking anything else.

### Describe the behavior you expected

Numbers in numeric columns should be right-aligned (not sure what the intended behaviour is on column headers).

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-02-25 20:12
This appears to be a regression. Numbers were right-aligned with v1.1, but not v1.2 (tested on macOS).

**Comment by kevinushey** [comment] 2020-02-25 20:16
Setting `display: block` does indeed fix the issue here. I suspect that the behavior of `text-align: right` differs between the rendering engine used by RStudio v1.1 and RStudio v1.2+.

**Comment by kevinushey** [comment] 2020-02-25 20:17
@jmcphers assigning to you just because this should be an easy and safe fix but feel free to punt if you'd rather leave this out of v1.3.

**Closed** 2020-02-28 17:43 UTC

**Comment by rich-rstudio** [comment] 2020-03-04 17:49
verified in Version 1.3.885

**Comment by petrbouchal** [comment] 2020-03-04 20:27
Thanks for the quick fix. I am afraid I am still seeing a glitch in some cases - here is a reprex:

```
library(tibble)
repdf <- tibble(current_gross = c(21141357.67, 9013743.43, 0, 6907082.5, 0, 0, 1963860.93,
142800, 0, 0, 0, 12099636.99, 0, 0, 0, 165630.1, 5809580.09, 0, 6124426.8, 0))
View(repdf) # rows 1 and 12 misaligned
repdf_15 <- repdf[1:15,]
repdf_16 <- repdf[1:16,]
View(repdf_15)  # all correctly aligned to the right
View(repdf_16)  # rows 1 and 12 misaligned
```
In the code inspector, it seems this arises from the interaction between the `numberCell` and `largeCell` CSS classes: in the misaligned case above, the div has the `largeCell` class after the `numberCell` class, which seems to override something from `numberCell` - although the calculated `text-align` parameter still shows up as `right`, it i not reflected in the display. I am just not clear in which cases the numberCell class is added - it seems to have something to do with how tibble prints decimals and how that is treated by DT.
