### ISSUE TITLE
Rsutdio enters infinite loop after typing system("top")

### ISSUE THREAD

**Issue by erlisR** [rstudio/rstudio#3739] opened 2018-10-25 07:37 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      :  x86_64-apple-darwin15.6.0
    R Version       :  R version 3.5.0 (2018-04-23)

### Steps to reproduce the problem
system("top") 
system2("top")

### Describe the problem in detail
Rstudio enters on an infinite loop and doesn't stop neither using the Rstudio "Exit" button nor via esc.

### Describe the behavior you expected
Typing q on the console should quit top.

**Comment by pascaloettli** [comment] 2018-10-25 08:43
Not reproducible with RStudio `1.2.1065` running on macOS `High Sierra (10.13.6)`. Pushing `esc` stops the commend.

**Comment by kevinushey** [comment] 2018-10-25 14:47
In general, if you want to run a command that can accept keyboard input from the user, you should prefer running it within the Terminal pane (since RStudio doesn't forward stdin / stdout with processes launched with `system()`)

**Comment by ronblum** [comment] 2018-10-29 14:52
Closing given note above, and also since it works in 1.2 on both MacOS Desktop and Server (spec. Ubuntu 16.04.5).

**Closed by ronblum** 2018-10-29 14:52 UTC
