### ISSUE TITLE
RStudio crashes on Ubuntu 20.04

### ISSUE THREAD

**Issue by jenslaufer** [rstudio/rstudio#6782] opened 2020-04-30 14:28 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5042 / 1.4.285
    OS Version      :  Ubuntu 20.04
    R Version       :  4.0.0 (2020-04-24)

### Steps to reproduce the problem

1. Upgrade from Ubuntu 19.10 to 20.04

2. Install RStudio
```shell
apt update
apt install gdebi-core
apt install r-base r-base-dev
wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5042-amd64.deb
gdebi https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5042-amd64.deb
rstudio
```

I tried latest stable + latest daily build

### Describe the problem in detail

RStudio starts but freezes with white background

Error message:

```shell
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
Received signal 11 SEGV_MAPERR 0000000000e6

```

### Describe the behavior you expected

RStudio starts normally without freezing

Issue seems related to [#6723](https://github.com/rstudio/rstudio/issues/6723), [#6379](https://github.com/rstudio/rstudio/issues/6379), [#6727](https://github.com/rstudio/rstudio/issues/6727)

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by satmandu** [comment] 2020-04-30 15:19
Does ```QT_QPA_PLATFORM=xcb rstudio``` work for you?

AFAIK rstudio doesn't work as a Wayland app, but needs to use the x11 compatibility to run.

**Comment by jenslaufer** [comment] 2020-04-30 15:56
Thanks @satmandu for your quick reply.

I got the same error. 

I tried this:

```script
QT_QPA_PLATFORM=xcb rstudio
```
_and_

```script
QT_QPA_PLATFORM=xcb && rstudio
```

**Comment by kevinushey** [comment] 2020-04-30 17:03
To the best of our knowledge, this crash is caused by a new version of glibc that is incompatible with the version of Qt used by RStudio. See e.g.

https://bugzilla.redhat.com/show_bug.cgi?id=1773289

It should be fixed in the daily builds of RStudio, if you want to test: https://dailies.rstudio.com. We also hope to fix this with the v1.3 release of RStudio.

As an aside: I cannot reproduce this crash in my Ubuntu 20.04 VM. What version of `glibc` do you have installed? For example, I see:

```
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by hansmrtn** [comment] 2020-04-30 17:17
> To the best of our knowledge, this crash is caused by a new version of glibc that is incompatible with the version of Qt used by RStudio. See e.g.
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1773289
> 
> It should be fixed in the daily builds of RStudio, if you want to test: https://dailies.rstudio.com. We also hope to fix this with the v1.3 release of RStudio.
> 
> As an aside: I cannot reproduce this crash in my Ubuntu 20.04 VM. What version of `glibc` do you have installed? For example, I see:
> 
> ```
> $ ldd --version
> ldd (Ubuntu GLIBC 2.31-0ubuntu9) 2.31
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.
> ```

`$ ldd --version` shows I have an identical version to your VM. Further investigation reveals that crashing seems to be an issue related to screen-resolution / dpi(?). On a 4k screen, I can reproduce the issue by changing the RStudio window size. Lowering the monitor resolution seems to fix the issue.

**Comment by kevinushey** [comment] 2020-04-30 17:34
Thanks for the extra information. I was able to reproduce after switching to a high DPI monitor. Indeed, attempting to resize the window causes the crash to occur.

**Comment by jenslaufer** [comment] 2020-05-01 06:15
It works on 2560x1600 and crashes 3840x2400.

**Comment by statnmap** [comment] 2020-05-02 09:22
On my side, I do have a multiple screens installation with a HiDPI screen and a 1920*1080 one. I tried to open Rstudio on the low resolution screen with deb from Ubuntu 18 in the dailies:
- version 1.4.285: A window opens, stays black and not respond
- version 1.4.290: A window opens, stays black, not respond and crash `segmentation error (core dumped)`
- version 1.4.292: A window opens, stays black, not respond and crash `segmentation error (core dumped)`
- version 1.4.293: A window opens, stays black, not respond and crash `segmentation error (core dumped)`
- version 1.4.294: Starts fails with  `error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`. Seems like a regression to me.

Even while reducing the resolution on the main screen alone, I got the same messages. 
If this can help...

**Comment by satmandu** [comment] 2020-05-02 15:14
For what it is worth, I was wondering if a newer version of Qt might help, since they appear to be putting in HiDPI fixes, (and FYI 5.15 which is supposed to be released in weeks is supposed to be a LTS branch.)

So I wrote up a quick [script & patch](https://gist.github.com/satmandu/a450a6a97259f8fd5597ccdf351023ea#file-rstudio-1-3-patch) to compile the [rstudio 1.3-patch branch](https://github.com/rstudio/rstudio/tree/v1.3-patch) for focal with the Qt 5.14.2 release using a local docker install (based upon the excellent [in-tree dockerfile ](https://github.com/rstudio/rstudio/blob/master/docker/jenkins/Dockerfile.bionic-amd64) used for building debian packages for bionic).

My build changes (evident in my [patch](https://gist.github.com/satmandu/a450a6a97259f8fd5597ccdf351023ea#file-rstudio-1-3-patch)):
* Use system boost for build
* Use system patchelf (0.10)
* Use openjdk-11
* Use Qt 15.14.2
* Patch from 1.4 to allow usage of R-4.0

Here is the info: https://gist.github.com/satmandu/a450a6a97259f8fd5597ccdf351023ea

FYI I'm no longer getting black boxes in menus. I'm using this on a ChromeOS/Crostini environment setup with a ubuntu/focal VM, and on a HiDPI screen. (Well, my screen "looks like" 1903x1269 and the native resolution is 3k x 2k)

![Screenshot 2020-05-02 at 11 07 06](https://user-images.githubusercontent.com/1096701/80867940-234c2600-8c65-11ea-9e54-c79307c7f5e8.png)

**Comment by gtritchie** [comment] 2020-05-02 16:01
There’s an (unofficial) existing branch off master for building with Qt 5.14.2, feature/qt-5-14-2

I say “unofficial” since we are not currently planning to take a new Qt for RStudio 1.4 but have been evaluating it.

**Comment by statnmap** [comment] 2020-05-04 11:04
May this be related to R4.0 ?
I have had this answer on Twitter
> [On Ubuntu 20.04] I'm still working with Rstudio Version 1.2.5042 and R version 3.6.3 (2020-02-29).

**Comment by dr-emacs** [comment] 2020-05-05 10:50
I can reproduce the crashes with the latest builds for 18.04 (1.2, 1.3, and 1.4) on 20.04.
The problem ist related to high screen resolutions - in my case it is reproducible with 4K and vanishes with 2K resolutions.

**Comment by iacobus42** [comment] 2020-05-05 13:22
> To the best of our knowledge, this crash is caused by a new version of glibc that is incompatible with the version of Qt used by RStudio. See e.g.
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1773289
> 
> It should be fixed in the daily builds of RStudio, if you want to test: https://dailies.rstudio.com. We also hope to fix this with the v1.3 release of RStudio.
> 
> As an aside: I cannot reproduce this crash in my Ubuntu 20.04 VM. What version of `glibc` do you have installed? For example, I see:
> 
> ```
> $ ldd --version
> ldd (Ubuntu GLIBC 2.31-0ubuntu9) 2.31
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.
> ```

Running pop_os 20.04 with the same versions of `glibc` and it still "whites out" on a HiDPI display when running the daily (rstudio-1.4.309).

**Comment by statnmap** [comment] 2020-05-05 14:17
On my side, with the last version (1.4-309), my Rstudio now opens up with the entire interface.  
But as soon as I click on the interface, it crashes.   
I started rstudio from the terminal and I got this error, which is the same error as in the bugzilla issue:

   ../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230

**Comment by gtritchie** [comment] 2020-05-05 15:03
We have reproduced the crash and are working on a fix.

**Comment by chandelsman** [comment] 2020-05-06 17:49
In case this helps anyone:

I was having a similar problem with Rstudio (1.2.5042) crashing on pop!_os 20.04 with a 4k monitor. The app would stop responding and the interface would turn white. similar to @statnmap I could eliminate the problem at lower resolutions. I installed today's daily build (1.4.315) and had the same issues. 

I launched Rstudio from the terminal and got the warning below:  

`Gtk-Message: 10:13:54.873: Failed to load module "appmenu-gtk-module"`

I installed the Gtk 3 appmenu module

`sudo apt install appmenu-gtk3-module`

Rstudio daily build is working as expected. I haven't tried with version 1.2.5042

**Comment by iacobus42** [comment] 2020-05-06 20:46
> In case this helps anyone:
> 
> I was having a similar problem with Rstudio (1.2.5042) crashing on pop!_os 20.04 with a 4k monitor. The app would stop responding and the interface would turn white. similar to @statnmap I could eliminate the problem at lower resolutions. I installed today's daily build (1.4.315) and had the same issues.
> 
> I launched Rstudio from the terminal and got the warning below:
> 
> `Gtk-Message: 10:13:54.873: Failed to load module "appmenu-gtk-module"`
> 
> I installed the Gtk 3 appmenu module
> 
> `sudo apt install appmenu-gtk3-module`
> 
> Rstudio daily build is working as expected. I haven't tried with version 1.2.5042

This did not resolve the issue for me on pop_os 20.04 and the currently daily (1.4.314). I instead got an error message in the terminal referencing chromium when it crashed.

**Comment by kevinushey** [comment] 2020-05-06 20:58
If you need a workaround, you can try:

```
export RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox"
rstudio
```

See https://chromium.googlesource.com/chromium/src.git/+/51.0.2662.1/docs/linux_sandboxing.md for more details.

**Comment by dr-emacs** [comment] 2020-05-07 13:04
Using the workaround --disable-seccomp-filter-sandbox solves the issue for me - tested with 1.4.296.

**Comment by lepennec** [comment] 2020-05-08 12:04
Same issue with the latest fedora FC32.

**Comment by gtritchie** [comment] 2020-05-08 17:00
Update: I have identified the nature of the problem on our (RStudio) end and am working on a fix. In the meantime the `--disable-seccomp-filter-sandbox` mentioned earlier is a good workaround.

The fix will make its way into daily builds (1.4), and the upcoming 1.3-patch release. The 1.3-patch is not yet available via public builds.

**Closed** 2020-05-11 16:53 UTC
Labels: desktop, in progress, linux

**Comment by dr-emacs** [comment] 2020-05-12 17:49
I just downloaded 1.4.325 and disabled the workaround. The daily version works now as expected.
Thanks a lot!

**Comment by gtritchie** [comment] 2020-05-12 19:09
@dr-emacs Thanks for checking, and glad it is working. Sorry this took so long to unravel!

**Comment by gtritchie** [comment] 2020-05-12 19:17
To reiterate, this is now fixed starting with daily build 1.4.325. The fix will also be in the first bug-fix release for 1.3 (known as 1.3-patch) but no builds available for that yet.

We will are not currently planning to fix this for RStudio 1.2 (any version).

**Comment by djnavarro** [comment] 2020-05-25 23:05
Just a comment to say thank you @gtritchie! I've been experiencing this issue and glad there's a fix in the works!

**Comment by santoshbs** [comment] 2020-05-30 10:33
I am having the same issue on Fedora 32. BTW, is there a installer for Fedora in general?

**Comment by santoshbs** [comment] 2020-05-30 10:39
I had the same issue on Fedora 32 and the latest daily build helped. Many thanks!

**Comment by R-Hannibal** [comment] 2020-06-03 14:53
Hey @jenslaufer, we have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).

If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by jenslaufer** [comment] 2020-06-03 15:24
Hey, perfect. Thanks so much. I will check it.
Regards
Jens

Mario Ferrini <notifications@github.com> schrieb am Mi., 3. Juni 2020,
16:54:

**Comment by jenslaufer** [comment] 2020-06-05 13:07
Hey it works perfectly. Thanks again!

**Comment by CodyStarke** [comment] 2020-06-17 17:29
Hi 
I downloaded the latest preview build for RStudio, however i keep getting this message after RStudio crashes (all 1.3 versions). 

[5149:5149:20200617,132518.348389:ERROR process_memory_range.cc:86] read out of range
[5149:5149:20200617,132518.348484:ERROR elf_image_reader.cc:558] missing nul-terminator
[5149:5149:20200617,132518.348927:ERROR process_reader_linux.cc:445] no module mappings 0x7f675facb000
[5149:5149:20200617,132518.355210:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.355762:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.372145:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.372298:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.375074:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.375189:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.375285:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.375385:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.375487:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.375686:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.375804:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.375900:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5149:20200617,132518.375997:ERROR elf_dynamic_array_reader.h:61] tag not found
[5149:5150:20200617,132518.410279:ERROR directory_reader_posix.cc:42] opendir: No such file or directory (2)
Segmentation fault (core dumped)

**Comment by gtritchie** [comment] 2020-06-17 18:57
@CodyStarke Not sure what the core problem is, but it is a different one that this issue was tracking, namely `syscall 0230` problem. Recommend you open a new issue with all the details, thanks!

**Comment by JJGabe** [comment] 2020-06-28 21:32
> Hey @jenslaufer, we have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).
> 
> If you get the chance will you let us know if the issue is resolved for you in that build?

I am just jumping in on this post but wanted to say that upgrading to the most recent daily (1.3.1039 in my case) seems to have fixed this issue for me. I have also set my rendering engine to "Desktop OpenGL" based on other solutions I read; I have not experimented with these two changes to see if they are both necessary.

**Comment by markushaun** [comment] 2020-06-30 12:39
> Hey @jenslaufer, we have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).
> 
> If you get the chance will you let us know if the issue is resolved for you in that build?

This worked very well for me. Thank you!

**Comment by MavropaliasG** [comment] 2020-07-23 04:43
Thank you @R-Hannibal , what would be the best way to install this in arch Linux? Would you recommend installing Rstudio through AUR or through the website (it does not have an arch Linux build..). Will Rstudio update itself on Arch Linux if I install it through here https://rstudio.com/products/rstudio/download/preview/ or will I have to check the website and re-install newer versions manually? Thanks

**Comment by R-Hannibal** [comment] 2020-07-23 14:45
Hey @MavropaliasG , thanks so much for reaching out! I am no linux OS expert by any stretch, BUT, I reached out to our amazing support team about your questions and got some info:

The reason you don't see a download link for Arch on our site (for either [Stable](https://rstudio.com/products/rstudio/download/), [Preview](https://rstudio.com/products/rstudio/download/preview/), or [Daily](https://dailies.rstudio.com/) builds) is that we do not [officially support](https://rstudio.com/about/platform-support/) it. Now, that does NOT mean that you can't use RStudio on Arch Linux, it just means we can't guarantee things will work 100%/as well as they would if you were using the IDE on an officially supported OS, and we can't formally advise on how to install/configure/etc.

That being said, it looks like our community site is a good source of information on RStudio + Arch Linux as I'm seeing a [number of posts ](https://community.rstudio.com/search?q=%22arch%20linux%22)on this topic.

And for the last question on RStudio self-updating, our products do not self-update, so you would have to manually download/re-install for new versions. I hope some of that is helpful, apologies I can't be of more direct help.

**Comment by MavropaliasG** [comment] 2020-07-23 16:36
Thank you very much @R-Hannibal

**Comment by ClovisG** [comment] 2020-09-04 15:06
Hi,
I'm reopening this issue since the proposed solution didn't work for me. I have the same behavior, only segfaulting:
`$ rstudio 
Segmentation fault (core dumped)
$ ls -lh core
-rw------- 1 clovis clovis 4,0G sept.  4 17:04 core`

Here are the versions I'm using:
`$ rstudio --version
1.4.779

$ qmake --version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu

$ R --version
R version 4.0.2 (2020-06-22) -- "Taking Off Again`

Any relevant needed?

**Comment by debnam-john** [comment] 2020-09-19 06:06
@ClovisG 
> Hi,
> I'm reopening this issue since the proposed solution didn't work for me. I have the same behavior, only segfaulting:
> `$ rstudio Segmentation fault (core dumped) $ ls -lh core -rw------- 1 clovis clovis 4,0G sept. 4 17:04 core`
> 
> Here are the versions I'm using:
> `$ rstudio --version
> 1.4.779
> 
> $ qmake --version
> QMake version 3.1
> Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
> 
> $ R --version
> R version 4.0.2 (2020-06-22) -- "Taking Off Again
> 
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description: Ubuntu 20.04.1 LTS
> Release: 20.04
> Codename: focal`
> 
> Any relevant needed?

I've tried this so far on the public release version and it's working again.
[](https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors)

I disabled the GPU for rendering to get it to start then changed the global options (General -> Advanced - OS Integration). I just selected "Software" as the rendering engine and left the rest alone. Hope this helps you for now until the roll out a complete fix for this without having to do these workarounds.

**Comment by mohammadreza-sheykhmousa** [comment] 2020-09-22 10:10
just solve the issue by installing from *dpkg* for debian-based linux systems:

`sudo dpkg -i ^C
sudo apt ^Cdate
sudo dpkg -i rstudio-1.3.1093-amd64.deb `

**Comment by ambijat** [comment] 2020-09-30 13:08
I got this problem from an entirely new method. I had uninstalled nvidia drivers using with 610 card and reverted back to nouveau drivers. And, the crash thing happened. The reason I reverted was because my OBS studio was unable to catch the xwindow. So, I intalled back and it worked.

**Comment by R-Hannibal** [comment] 2020-10-15 20:52
@ambijat - thanks for reaching out, sorry to hear you're still experiencing crash issues with the IDE.

Do you mind filing a [new issue report](https://github.com/rstudio/rstudio/issues/new?template=bug_report.md) with the RStudio/OS/etc. version information and reproduction steps? I think it may be a different issue (perhaps same crash with different causal conditions), and having a new issue report to work from will help us to isolate it.

**Comment by Sanjayavidbrio** [comment] 2021-04-26 18:58
https://computingforgeeks.com/how-to-install-r-and-rstudio-on-ubuntu-debian-mint/


sudo apt -y install r-base

--- Ubuntu 18.04 / Linux Mint 19 / Debian 10 ---
sudo apt -y install wget
wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5042-amd64.deb
sudo apt install ./rstudio-1.2.5042-amd64.deb

**Comment by JOduMonT** [comment] 2021-09-07 17:31
with lxqt, I simply had to add XCB
`apt install -y xcb`

**Comment by okeep** [comment] 2022-04-26 20:01
I know this is an old issue, but I just had it crop up with the latest pop_os (version 22.04 LTS). The previous workaround `--disable-seccomp-filter-sandbox` fixed the issue. Just thought I would put that here in case anyone else runs into the same issue when upgrading their linux OS.

**Comment by sfernandez-pricesmart** [comment] 2022-05-12 13:55
> I know this is an old issue, but I just had it crop up with the latest pop_os (version 22.04 LTS). The previous workaround `--disable-seccomp-filter-sandbox` fixed the issue. Just thought I would put that here in case anyone else runs into the same issue when upgrading their linux OS. The command (so that other's don't have to go looking) is:
> 
> ```
> export RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox"
> rstudio
> ```

Thanks, @okeep. I was having the same problem with the latest pop_os too. It solved the problem for me.

**Comment by kevinushey** [comment] 2022-05-12 17:46
For reference, the issue should be resolved in the latest daily builds of RStudio. Builds for Ubuntu 22.04 (and derivatives) are available here:

https://dailies.rstudio.com/rstudio/spotted-wakerobin/desktop/jammy/

**Comment by sanjmeh** [comment] 2022-05-27 15:31
@kevinushey the link doesn't work. 
Am still struggling on a hung up rstudio on ubuntu 20. Happened several times earlier but this time its not coming out of the hang. Seems linked to graphics as after I ran a dygraphs it is not exiting even when I closed the browser tab several times.
Is this a different issue or same?

**Comment by sanjmeh** [comment] 2022-05-27 15:33
The site (https://dailies.rstudio.com/rstudio) seems not working.

**Comment by jmcphers** [comment] 2022-05-27 15:36
It was temporarily down this morning due to a DNS issue! Should be back online shortly.

**Comment by yojetsharma** [comment] 2024-04-25 11:35
> If you need a workaround, you can try:
> 
> ```
> export RSTUDIO_CHROMIUM_ARGUMENTS="--disable-seccomp-filter-sandbox"
> rstudio
> ```
> 
> See https://chromium.googlesource.com/chromium/src.git/+/51.0.2662.1/docs/linux_sandboxing.md for more details.

I followed this because my rstudio would crash when running scRNA seq analyses but now I cannot even start rstudio:
```
2024-04-25T11:15:55.903666Z [rsession-user] WARNING Abort requested; LOGGED FROM: bool rstudio::session::connection::checkForAbort(rstudio_boost::shared_ptr<rstudio::session::HttpConnection>, rstudio_boost::function<void()>) src/cpp/session/http/SessionHttpConnectionUtils.cpp:135
2024-04-25T11:31:14.237099Z [rsession-user] ERROR asio.netdb error 1 (Host not found (authoritative)); OCCURRED AT rstudio::core::Error rstudio::core::http::initTcpIpAcceptor(rstudio::core::http::SocketAcceptorService<rstudio_boost::asio::ip::tcp>&, const string&, const string&) src/cpp/session/http/SessionPosixHttpConnectionListener.cpp:88; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2302
2024-04-25T11:31:14.237099Z [rsession-user] ERROR asio.netdb error 1 (Host not found (authoritative)); OCCURRED AT rstudio::core::Error rstudio::core::http::initTcpIpAcceptor(rstudio::core::http::SocketAcceptorService<rstudio_boost::asio::ip::tcp>&, const string&, const string&) src/cpp/session/http/SessionPosixHttpConnectionListener.cpp:88; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2302
```

**Comment by ronblum** [comment] 2024-04-25 13:28
@yojetsharma Can you please file a new issue for this? Thanks!
