### ISSUE TITLE
Calling Update from Package tab hangs

### ISSUE THREAD

**Issue by macek2** [rstudio/rstudio#4267] opened 2019-02-05 03:07 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2 (most recent preview)
    OS Version      : Mac OS High Sierra
    R Version       : 3.5.2

### Steps to reproduce the problem
Select Packages Tab,
Click update button

### Describe the problem in detail
Update just hangs
![screen shot 2019-02-04 at 7 06 35 pm](https://user-images.githubusercontent.com/44280497/52251097-06814100-28b0-11e9-8cdf-c4daac6ebf98.jpg)

**Comment by macek2** [comment] 2019-02-05 03:09
Deleting my .rstudio-desktop folder seems to fix the issue.

**Comment by macek2** [comment] 2019-02-05 03:59
Can confirm. This happens when adding a secondary repository in settings.

**Comment by pascaloettli** [comment] 2019-02-05 05:09
Related: #3349

**Comment by ronblum** [comment] 2019-02-06 14:12
@macek2 Can you send me the repositories you're using, with the output of `getOption("repos")`? It would help in trying to reproduce the issue. I'm unable to reproduce it: I tried with one primary and two secondary repositories, all CRAN mirrors, and the pane was processing for about thirty seconds before the package list appeared:
```
> getOption("repos")
                            CRAN                          RStudio                              MTU 
"https://ftp.uni-sofia.bg/CRAN/"       "https://cran.rstudio.com"          "https://cran.mtu.edu/" 
attr(,"RStudio")
[1] TRUE
```
But it completed successfully. The delay is expected, as covered in #3349, but it should complete.

**Comment by macek2** [comment] 2019-02-08 07:20
Unfortunately we are using an internal cran-like repo with our companies packages. That could very well be the issue.

**Comment by ronblum** [comment] 2019-02-08 21:12
Perhaps it's worth trying just the company's repo as the primary, with no secondary repos, just to get an idea of the behavior. @javierluraschi do you have any thoughts or suggestions?

**Comment by jmcphers** [comment] 2020-02-12 00:47
No progress on this one in over a year (nor any way for us to reproduce it in our environment) so closing for now.

**Closed by jmcphers** 2020-02-12 00:47 UTC
Labels: repro needed
