### ISSUE TITLE
YAML-style chunk options for plots are ignored when using hyphenated options (fig-height, fig-width)

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#11708] opened 2022-08-05 14:19 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : '2022.7.1.554'
    OS Version      :  Mac OS X 12_4_0
    R Version       :  4.2.0

### Steps to reproduce the problem

Using source mode or visual mode, modify plot dimensions with traditional `knitr` chunk options and YAML-styled `#|` options:

````
---
format: html
editor_options: 
  chunk_output_type: inline
---

This modifies appearance of plot
```{r, fig.width=12, fig.height = 5}
plot(mtcars$disp, mtcars$mpg)
```

But this doesn't:

```{r}
#| fig-width: 12
#| fig-height: 5
plot(mtcars$disp, mtcars$mpg)
```
````

### Describe the problem in detail

When using `knitr` chunk options only using the older syntax `r, fig.width=12, fig.height=5` modifies the appearance of inline plots in Quarto. Hashpipe/YAML style: `#| fig-width: 12` doesn't modify the appearance.

![image](https://user-images.githubusercontent.com/29187501/183095733-c2a25e50-0453-4241-938a-b56b5eafbd40.png)

### Describe the behavior you expected

Both `knitr` style and YAML style chunk options do the same thing when rendering - would be ideal if that also affected interactive behavior in RStudio.

Tagging @debruine who reported the behavior initially - I was able to reprex.

https://twitter.com/lisadebruine/status/1555506264519630849?s=21&t=9xOZw-tSkKLd8IayCK0ajw

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by andresrcs** [comment] 2022-08-05 22:06
Since you are already into this, have you noticed a big difference in proportions between the plots shown in the code editor and the plots that get rendered into HTML? I first thought it was because of this issue but even using knitr chunk options I get a noticeable difference as if they were using different units. For "difference in proportions" I mean, for example, the text being way bigger in the HTML output relative to the rest of the plot than in the code editor.

**Comment by JMLuther** [comment] 2022-09-17 17:04
Also an issue on windows version. Same behavior as OP.
Would like to transition to this style of code in .qmd, but I rely on interactively adjusting the figure dimensions in RStudio. This is the bug that is keeping me from doing so.

```
─ Session info ───────────────────────────────────────────────────────────────────────────────
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
```

**Comment by csthiago** [comment] 2022-11-05 06:24
Same issue (windows)

 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 22000)
 system   x86_64, mingw32
 ui       RStudio
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)

**Comment by vancleve** [comment] 2022-11-13 23:03
I'm also seeing this.
```
RStudio 2022.07.2 Build 576
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin21.6.0 (64-bit)
Running under: macOS Monterey 12.6
```

**Comment by GegznaV** [comment] 2023-01-31 13:05
Similar issue: https://community.rstudio.com/t/does-figure-size-in-quarto-qmd-documents-in-rstudio-need-to-be-specified-twice/158661

**Comment by GegznaV** [comment] 2023-01-31 13:07
What is the progress towards solving the issue??

**Comment by caparks2** [comment] 2023-07-13 00:25
Same issue:

https://stackoverflow.com/q/76674526/11417996

**Comment by atakanekiz** [comment] 2023-08-25 08:45
> Also an issue on windows version. Same behavior as OP. Would like to transition to this style of code in .qmd, but I rely on interactively adjusting the figure dimensions in RStudio. This is the bug that is keeping me from doing so.
> 
> ```
> ─ Session info ───────────────────────────────────────────────────────────────────────────────
>  version  R version 4.2.1 (2022-06-23 ucrt)
>  os       Windows 10 x64 (build 19044)
>  system   x86_64, mingw32
>  ui       RStudio
>  rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
> ```

Agreed, I'm in the same boat. Solving this would be great for facilitating my transition to qmd. I would appreciate it if someone can comment on the latest on this issue.

**Comment by kevinushey** [comment] 2023-10-03 22:49
I think this has already been resolved in the latest daily builds. @jthomasmock, I notice in your example you're using `fig-width` instead of `fig.width` -- is that intentional, or a typo?

**Comment by jgutman** [comment] 2023-10-04 14:37
[The Quarto docs](https://quarto.org/docs/computations/execution-options.html) suggest using `fig-width` and `fig-height` for YAML execution options, which become `fig.width` and `fig.height` in `knitr`, so I believe @jthomasmock's example is correct

**Comment by jgutman** [comment] 2023-10-04 15:10
@kevinushey this still looks broken to me in 2023.12.0-daily+119 (using Quarto 1.3.450 and R 4.3.1). You're actually right that it renders correctly when the yaml chunk options are set to `fig.width` and `fig.height`, but that's actually a bug, as Quarto recommends `fig-width`, `fig-height`, `fig-cap`, `fig-alt`, etc. so we should support both

**Comment by jthomasmock** [comment] 2023-10-04 15:42
Yah, Jackie's updated title is a better summary. 

- YAML style in terms of location IE 
	- Chunk ```` ```{r fig.height} ````
	- YAML: hashpipe, `#| fig.height`
- YAML style in terms of syntax
	- `fig-height` instead of `fig.height`

The YAML style syntax for chunk options is not respected, as tested on `v2023.09.0+463`

**Comment by jgutman** [comment] 2023-10-04 16:00
I think this could be addressed somewhere around here: https://github.com/rstudio/rstudio/blob/11a635527f0329fc29d5b8d5e890196dcd7654ea/src/cpp/session/modules/rmarkdown/NotebookExec.cpp#L206

**Comment by kevinushey** [comment] 2023-10-04 17:22
Ah, thanks -- I misunderstood that. Does Quarto document all of the translations it does for "Quarto" options to "knitr" options?

**Comment by jgutman** [comment] 2023-10-04 17:49
I'm not sure if that documentation exists. But there are a few things I am aware of: 

https://github.com/quarto-dev/quarto-cli/blob/1d7e53c99d62b9e2b5ffc1fa16cc5d3b4d0b6d6e/src/resources/rmd/execute.R#L263-L277

This is more of a documentation of translation from knitr into quarto, and I think is why something like `#| fig.width: 12` still renders successfully. This isn't exhaustive though because for example: `#| out.width: 50%` and `#| out-width: 50%` both work. 

This [documentation](https://quarto.org/docs/computations/r.html#output-formats) mentions that 
> One source of the difference in syntax is that Quarto is more closely aligned with [Pandoc](https://pandoc.org/) format names and options (thus the use of - as a word separator rather than _).

This [documentation](https://quarto.org/docs/computations/execution-options.html#figure-options) mentions that 
> How do these sizes make their way into the engine-level defaults for generating figures? This differs by engine:
> For the Knitr engine, these values become the default values for the fig.width and fig.height chunk options. You can override these default values via chunk level options.
But it's not clear how many options that kind of translation applies to

**Comment by kevinushey** [comment] 2023-10-04 18:05
Nice find! https://github.com/quarto-dev/quarto-cli/blob/1d7e53c99d62b9e2b5ffc1fa16cc5d3b4d0b6d6e/src/resources/rmd/execute.R#L262-L278 seems like a great starting point, at least. I've also asked on the Quarto-dev channel for other pointers.

**Comment by jgutman** [comment] 2023-10-04 18:18
Looks like we can potentially use the `knitr:::fix_options` function, but it would require the very latest version of `knitr` and is not an exported function currently

**Comment by jonvanausdeln** [comment] 2023-10-16 20:57
Verified with [2023.12.0-daily+170](https://dailies.rstudio.com/version/2023.12.0-daily+170)
Windows 11, MacOS 12.6

Chunks now render consistently.

**Closed by jonvanausdeln** 2023-10-16 20:57 UTC
Labels: bug, plots, quarto

**Comment by andrewheiss** [comment] 2023-10-16 22:27
Confirmed that this works on macOS 14.0 too 

(The syntax highlighting of the inline chunk options is a nice touch too!)

<img width="933" alt="image" src="https://github.com/rstudio/rstudio/assets/73663/8a8c9463-9db3-4803-a6e7-e813b0a49e9f">

**Comment by andrewheiss** [comment] 2023-10-16 22:29
(Though the Quarto tab completion of YAML keys doesn't work in this daily build, but that's definitely a separate issue)

**Comment by kevinushey** [comment] 2023-10-16 22:33
> (Though the Quarto tab completion of YAML keys doesn't work in this daily build, but that's definitely a separate issue)

Is this a regression? If so, a bug report would definitely be appreciated!

**Comment by andrewheiss** [comment] 2023-10-16 22:47
> > (Though the Quarto tab completion of YAML keys doesn't work in this daily build, but that's definitely a separate issue)
> 
> Is this a regression? If so, a bug report would definitely be appreciated!

Yeah, but only in untitled, unsaved .qmd files. Issue opened here: https://github.com/rstudio/rstudio/issues/13804
