### ISSUE TITLE
RStudio App Issue on HPC Open OnDemand

### ISSUE THREAD

**Issue by lab396** [rstudio/rstudio#11828] opened 2022-08-24 14:26 UTC
Hello! We are using RStudio App in Open OnDemand in our HPC Cluster. When a session launches, the following key file is created on the node  /tmp/rstudio-server/session-rpc-key. This appears to be hard coded in the rstudio source code. If another user comes along on the same node, they won't be able to write to that location. Any idea how to fix?

**Comment by jmcphers** [comment] 2022-08-24 15:55
Are you using the professional version of RStudio (RStudio Workbench), or the open source version?

What specific errors or problems are you seeing arising from the conflict?

**Comment by lab396** [comment] 2022-08-24 16:11
We are using the open source version 2022.07.0-548 . The issue is that the rpc key file (/tmp/rstudio-server/session-rpc-key) is owned by the user launching rserver. This prevents another user from launching and running their own instance of rserver on the same machine. We are looking for a command line option or environment variable or something to change the location of the session-rpc-key to be user-specific.

**Comment by jmcphers** [comment] 2022-08-24 18:03
The location is hardcoded right now:

https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/cpp/server_core/SecureKeyFile.cpp#L116

You could change this to use `$TMPDIR` if you are comfortable recompiling. 

What error message are you seeing, specifically? I think your best bet (since the location is hardcoded) is to have a session init hook or other tool that makes it possible for all users to read the file; that way subsequent users, even though they can't create the file, will be able to use it. (Presumably you have a second level security system to prevent users from accessing each others' servers?)

**Comment by jpetucci** [comment] 2022-08-25 13:06
@jmcphers , I'm working with @lab396 on this. Here is the error message from the rserver.log file:
`2022-08-11T16:21:42.159584Z [rserver] ERROR system error 2 (No such file or directory) [path: /tmp/rstudio-server/session-rpc-key]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::openForRead(std::shared_ptr<std::basic_istream<char> >&) const src/cpp/shared_core/FilePath.cpp:1462; LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:786`

This occurs when /tmp/rstudio-server/session-rpc-key exists but is owned by another user with 0600 permissions

**Comment by steverweber** [comment] 2022-09-06 20:59
@lab396 did you find an older version without this issue?

**Comment by camillescott** [comment] 2022-09-07 19:17
Running into this problem at UC Davis HPCCF as well. This is a major blocker for rstudio-server in HPC environments. We can hack around it, but making this configurable like `--secure-cookie-key` and others would be much preferable.

**Comment by steverweber** [comment] 2022-09-09 01:20
Sadly i don't have time to build and package a binary to support a dynamic cookie path.
Here is a lazy BAD idea but seemed to pass my basic testing.

```
/usr/lib/rstudio-server/bin/rserver \
    --verify-installation=0 \
    --server-daemonize=0 \
    --server-user=$USER ...
for i in 1 2 3 4 5 ; do
chmod g+rw /tmp/rstudio-server/session-rpc-key || true
sleep 1
done
```

**Comment by m4ge** [comment] 2022-09-09 17:39
We are experincing the same issue and I'm currently working on a patch that will set the path using `--session-rpc-key-file` option in a similar way to the existing `--secure-cookie-key-file`. Happy to do a PR if that would be of interest to the project.

**Comment by mikebessuille** [comment] 2022-09-19 17:17
This is a feature of Workbench, not of RStudio Server (open source).  You could use Workbench, or you could use RStudio Cloud, which is optimized for educational use cases.   If you reach out to sales@rstudio.com, you can get a free license of Workbench if using it in an educational institution for education purposes. (I believe there are discounts available for universities when using it or research, as well).

**Comment by mikebessuille** [comment] 2022-09-19 17:17
Closing per above.

**Comment by steverweber** [comment] 2022-09-19 23:29
Big thanks to @jmcphers for the correct solution.

**Comment by jmcphers** [comment] 2022-09-23 22:17
If you want to try a build with the fix, you can get one here now: https://dailies.rstudio.com/

(These are early builds of our 2022.11 release, due out in -- you guessed it -- November.)

**Comment by steverweber** [comment] 2022-09-26 16:15
I also confirmed the fix.

**Comment by kevinushey** [comment] 2022-09-26 18:32
Great to hear! Thanks everyone for taking the time to confirm the fix.

**Closed by kevinushey** 2022-09-26 18:32 UTC
