### ISSUE TITLE
Various ways of creating a new file have inconsistent menus and default file names

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#10338] opened 2022-01-11 14:41 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.0-daily+365 "Prairie Trillium" Daily (11f024759345d724ed4d910978bc6e654938fcb8, 2022-01-10) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_1_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : macOS 12.1
    R Version       : 4.1.2

### Steps to reproduce the problem

There are three ways to create a new file:

1. File menu on top > New File
2. New file icon with green + sign on top left corner of editor pane
3. Blank File menu in the File pane

### Describe the problem in detail

Each of these menus have a different set of options. (1) is the most comprehensive so maybe others should match that. But it's possible it's also too long for the positions of (2) and (3). In that case, at a minimum, (2) and (3) should match.

Also, new files generated with (3) are named oddly, IMO. For example, new Quarto Document's default name is `UntitledQMD.qmd`, I think it should just be `Untitled.qmd`.

### Describe the behavior you expected

I expected the menus to match and generate documents with the same default name.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-01-11 19:56
@mine-cetinkaya-rundel Funny, a duplicate of the main issue was just filed: #10325. I'll keep this open, though, for the last part, the oddly named files.

**Comment by ronblum** [comment] 2022-05-13 19:19
Verified that the default file name is now `Untitled.qmd` instead of `UntitledQMD.qmd`.

**Closed by ronblum** 2022-05-13 19:19 UTC
Labels: bug, files pane
