### ISSUE TITLE
Stuck on Copilot authentication "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"

### ISSUE THREAD

**Issue by DavidBlairs** [rstudio/rstudio#13431] opened 2023-07-30 21:23 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version :  2023.09 Desert Sunflower
    OS Version      : Windows 10
    R Version       : R version 4.2.2

### Steps to reproduce the problem

I click on "sign in" and begin the authentication process. The screen is stuck on "authenticating..." and an error appears in the console. 

### Describe the problem in detail

The error message that appears is: 
`unhandledRejection {"type":"system","errno":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY","code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}`

### Describe the behavior you expected

I expect for it to authenticate and allow me to use the copilot support. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-07-31 05:46
@DavidBlairs Thank you for raising this! How far along are you able to get through the sign in/authentication process? For example, do you get as far as this sign-in screen, etc.?

![copilot_auth](https://github.com/rstudio/rstudio/assets/31009952/2222cc59-433e-4573-8aeb-b4a3a8feb4e7)

**Comment by DavidBlairs** [comment] 2023-07-31 10:20
Hello @ronblum. I am able to get to the stage where this screen appears:

![image](https://github.com/rstudio/rstudio/assets/54111529/12017760-9d0c-4929-af2e-fba031d0651d)

I can then go through GitHub and approve access to my account and everything seems fine on their end. After completing all those steps, this is when I get the error in the terminal.

**Comment by ronblum** [comment] 2023-07-31 10:24
Thanks for the info!

**Comment by kevinushey** [comment] 2023-07-31 16:40
Some users have reported this issue when there's a network proxy in the way:

https://github.com/orgs/community/discussions/8866

@DavidBlairs, could that be the cause in your case?

**Comment by kevinushey** [comment] 2023-07-31 17:10
Unfortunately, not that I'm aware of. We'll try to investigate and see if there's anything we can do on our side, but I suspect we're at the mercy of any network proxies in front of RStudio / Copilot.

**Comment by DavidBlairs** [comment] 2023-08-01 11:28
@kevinushey no worries. I'll close this for now, let me know if anything else comes to mind.

**Comment by kevinushey** [comment] 2023-08-16 21:44
Looking at the copilot.vim sources, it looks like we can pass some extra networking details when activating the Copilot agent:

https://github.com/github/copilot.vim/blob/a24c3fd686ecf53b81d7d259994691508a69ebf6/autoload/copilot/agent.vim#L440-L472

**Comment by kevinushey** [comment] 2023-08-16 22:16
It also looks like the Copilot Agent itself might be smart enough to pick up on proxy settings if you've defined an appropriate URL in the `https_proxy` environment variable. You could try making sure that environment variable is set when you launch R, e.g. in your `.Renviron`?

**Comment by kevinushey** [comment] 2023-08-22 21:17
I've made a change here:

https://github.com/rstudio/rstudio/blob/25e779e6c4fa0f88e54c1824e4aa2329739aa4cd/src/cpp/session/modules/SessionCopilot.cpp#L320-L342

You should be able to set up a network proxy + an authentication provider using code of the form:

```
options(rstudio.copilot.networkProxy = list(
    host = I(<host>),
    port = I(<port>),
    username = I(<user>),
    password = I(<password>)
))

options(rstudio.copilot.authProvider = list(
   url = I(<url>)
))
```

replacing each entry in `<>` with the "correct" value for your proxy / authentication provider.

If you can confirm this works, we can think about ways to improve the user experience here.

**Comment by kevinushey** [comment] 2023-08-29 16:44
I believe it would be for the proxy itself. This is mostly drawing on the documentation for the Copilot vim extension:

https://github.com/github/copilot.vim/blob/172955782814a49fbebca2d1a2ccce2059103329/doc/copilot.txt#L77-L82

**Comment by ronblum** [comment] 2023-09-06 21:42
@DavidBlairs I'm glad the whitelisting helped! I tried this out with a network proxy (Squid on MacOS 14) with username and password authentication, but I can't reproduce the problem in earlier builds. I'll close this, but if anyone runs into this issue, please let us know!

**Closed by ronblum** 2023-09-06 21:42 UTC
Labels: bug, copilot
