### ISSUE TITLE
Problem wtih "R Package Using devtools"

### ISSUE THREAD

**Issue by Cervangirard** [rstudio/rstudio#5152] opened 2019-07-29 06:57 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      :  Linux Mint 19.1 Tessa
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Click on file
2. Choose new project
3. Choose new directory
4. Choose R Package using Devtools
5. Choose a name and click on create project

### Describe the problem in detail

You can see a error because `devtools::create()` function doesn't exist anymore. 
![image](https://user-images.githubusercontent.com/37626302/62027577-4fbaa980-b1de-11e9-94ce-e5df4bd3fc65.png)
```
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  objet 'create' introuvable
```

We can replace this function by `usethis::create_package()`.

### Describe the behavior you expected

A new R package using devtools, something like : 
![image](https://user-images.githubusercontent.com/37626302/62027729-b93ab800-b1de-11e9-80f0-a5a60dc25d49.png)

Thanks you.

**Comment by ronblum** [comment] 2019-07-29 17:02
@Cervangirard Thank you for copying over the issue description! And I can reproduce it in MacOS Desktop 1.1.463 and 1.2.1564.

@jmcphers This change is described in https://github.com/r-lib/devtools/issues/2083
> Yes, devtools::create() no longer exists and is replaced by usethis::create_package().

It not only conflicts with RStudio 1.2.x, but also 1.1.x. And other places, such as the [_R packages_ book](http://r-pkgs.had.co.nz/package.html#projects). 🤨

**Comment by jimhester** [comment] 2019-07-30 16:15
`devtools::create()` was deprecated for almost a year, but I have added it back for now https://github.com/r-lib/devtools/commit/bf02cdaf86f0f8503745ef029a973233f9be7cff

**Comment by kevinushey** [comment] 2019-07-30 16:52
Thanks. Note that it does not need to remain exported if you'd rather remove it from the public interface of devtools (RStudio accesses it with `:::`)

**Comment by jimhester** [comment] 2019-07-30 17:57
Yeah, I decided it would be too weird to have it not be exported.

**Comment by jmcphers** [comment] 2019-08-13 17:52
Closing since devtools::create has been restored. Thanks @jimhester!

**Closed by jmcphers** 2019-08-13 17:52 UTC
Labels: bug, external
