### ISSUE TITLE
data viewer displays wrong data for lists with duplicate names

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#7561] opened 2020-08-10 11:38 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.5042
    OS Version      : Ubuntu 14.04.5 LTS
    R Version       : 3.4.0

### Steps to reproduce the problem
1. Run the following in the console:
 `aa<-list( n1=list(a=1, b=2), n1=list(a=3,b=4))`

### Describe the problem in detail
`aa` is displayed correctly in the console and in the environment pane, but *not* in a data viewer:
![image](https://user-images.githubusercontent.com/73080/89778771-bd4e2500-db16-11ea-859b-0cbe9a1b7135.png)

Note the 2nd list element displayed is in fact the 1st. It becomes more apparent if you click the hover icon to the right of data viewer elements - it seems the data viewer gets the contents via `aa[["n1"]]` for both `aa[[1]]` and `aa[[2]]`.

### Describe the behavior you expected
Different elements displayed for aa[[1]] and aa[[2]]

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-08-10 16:05
@OfekShilon Thank you for raising the issue! I can reproduce it in RStudio Desktop 1.4.673 (dev) on MacOS 10.15.6. We'll review this as we continue developing RStudio.

**Comment by OfekShilon** [comment] 2020-08-11 20:03
@ronblum  Thanks. When prioritizing, please note that this is an intentionally simple repro and in real life this issue can (and did) bite in far less direct ways. It either make the user draw wrong conclusions from data or make debugging rather frustrating.

**Comment by OfekShilon** [comment] 2020-11-08 10:51
@ronblum  will this be fixed in 1.4?

**Comment by kevinushey** [comment] 2020-11-09 17:51
No, it won't.

**Comment by mikebessuille** [comment] 2020-11-09 18:20
Closing this as a duplicate of https://github.com/rstudio/rstudio/issues/2966

**Closed** 2020-11-09 18:20 UTC
Labels: bug, duplicate, object viewer
