### ISSUE TITLE
No Terminal in RStudio Server

### ISSUE THREAD

**Issue by dlukes** [rstudio/rstudio#2465] opened 2018-03-21 13:19 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.442
    OS Version      : Ubuntu 16.04.3 LTS
    R Version       : 3.4.1 (2017-06-30) -- "Single Candle"

### Steps to reproduce the problem

Click on the *Terminal* tab in RStudio Server.

### Describe the problem in detail

A terminal should open. It doesn't :)

I filed [an issue a while back in the old support system](https://support.rstudio.com/hc/en-us/community/posts/115009415688-Slow-startup-of-new-Terminal-due-to-websocket-error) which described how opening a terminal is slow because the WebSocket connection fails and RStudio has to switch back to RPC, which only happens after a timeout.

In the meantime, I upgraded from RStudio Server 1.1.383 to 1.1.442 and now the terminal completely fails to start.

This is what *Terminal diagnostics* say:

```
Global Terminal Information
---------------------------
Loaded TerminalSessions: 0

Terminal List Count: 1
Handle: 'D6D503FB' Caption: 'Terminal 1' Session Created: true
```

And I get the following output in the console:

```
Terminal not found after switching
WebSocket connect error, switching to RPC
Unable to switch back to RPC mode
```

So it looks like the problem in the old issue got worse -- the switch back to RPC fails.

I'm wondering whether this might have anything to do with SSL configuration? If so, any suggestions on how to debug the WebSocket connection with respect to that?

On the other hand, I have a Shiny server running on the same box and that works perfectly fine, even though Shiny also uses WebSockets (I think?).

**Comment by gtritchie** [comment] 2018-03-21 15:44
Marking as a duplicate of #2207 and added some troubleshooting/data gathering suggestions to that issue.

**Closed by gtritchie** 2018-03-21 15:44 UTC
Labels: duplicate
