### ISSUE TITLE
No panes on MacOS since 1.2.1207

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#4086] opened 2018-12-24 10:05 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.
    OS Version      :  MacOS 10.14.2
    R Version       :  3.5.1 and 3.5.2

Since 1.2.1207 when starting RStudio I only get a grey screen with no panes. The menu is displayed,
but clicking on any menu items does not display any dropdown menus.
I tested on two different machines.
What can I do to make the latest versions work again?

**Comment by neuwirthe** [comment] 2018-12-26 10:42
Resizing makes the panes visible again.

**Comment by ronblum** [comment] 2018-12-26 16:47
Reproduced on MacOS 10.14.2 Mojave with RStudio Desktop 1.2.1210 and 1.2.1606-6.

Resizing make the panes visible, but you can't resize too much: too big makes part of the display becomes hidden, and too small creates a black background and border. In addition, the location to click is offset from the buttons, checkboxes, etc., so that you can't really click on them.
![mac_screen](https://user-images.githubusercontent.com/31009952/50451759-fb77e000-0903-11e9-9517-582d0bf9a85e.gif)

**Comment by kevinushey** [comment] 2018-12-28 04:51
False start on a workaround -- will have to investigate further.

**Comment by neuwirthe** [comment] 2018-12-28 13:44
1.2.1213 still has the problem

**Comment by kevinushey** [comment] 2018-12-28 19:40
We are aware. Please use the preview release until we've resolved this issue in the daily builds.

**Comment by kevinushey** [comment] 2019-01-07 21:43
This is resolved in the preview release + current dailies (thanks to @jmcphers's work in rolling back to old Qt) but we'll have to make sure to re-evaluate this when we bump to Qt 5.12.1.

**Comment by jmcphers** [comment] 2019-01-08 17:51
I'm going to close this for now since it's not currently an issue. We can re-open if it turns out to be a problem when we take the next Qt bump.

**Closed by jmcphers** 2019-01-08 17:51 UTC
Labels: bug, qtwebengine
