### ISSUE TITLE
Dynamically created files don't display output inline

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#7191] opened 2020-06-22 16:13 UTC
### System details

    RStudio Edition : RSP
    RStudio Version : 1.3.1039
    OS Version      :  Ubuntu 18.04
    R Version       : 3.6.3

### Steps to reproduce the problem

```
text <- c("---", "title: \"Sample\"", "output: html_document", "---", 
"", "```{r setup, include=FALSE}", "knitr::opts_chunk$set(echo = TRUE)", 
"```", "", "## Title", "", "```{r hey, message=FALSE}", "x <- 1", 
"```")
rstudioapi::documentNew(paste(text, collapse="\n"), "rmarkdown")
```

Now put your cursor on line 13 and press Cmd+Enter to execute that line.

### Describe the problem in detail

Rather than the output of the line appearing inline in the RMD, it appears in the console output. We do NOT notice this problem if the RMD is created through the traditional "New > R Markdown" flow. Only if the file is created dynamically as above.

I've confirmed that 

```
rstudioapi::readRStudioPreference("rmd_chunk_output_inline")
[1] TRUE
```

### Describe the behavior you expected

I expected the chunk output to be displayed inline in the RMD.

I _believe_ that this issue did not exist in 1.3.1013. We've been running that in production and didn't have any problems, but as soon as we bumped to 1031 or 1039 we started seeing this issue.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

[Originally filed by @trestletech and movedover from RStudio Pro repository.]

**Comment by jmcphers** [comment] 2020-06-22 21:58
I think this might just be a misunderstanding of how this is supposed to work.

The reason no output appears in the editor is that neither one of these chunks _have_ output (their R statements do not print any values). If you add something to the chunk that has output, you'll see it correctly. For example, just adding a line `x` to the end of the second chunk:

```r
> rstudioapi::documentNew(paste(text, collapse="\n"), "rmarkdown")
> text <- c("---", "title: \"Sample\"", "output: html_document", "---", 
+           "", "```{r setup, include=FALSE}", "knitr::opts_chunk$set(echo = TRUE)", 
+           "```", "", "## Title", "", "```{r hey, message=FALSE}", "x <- 1", "x",
+           "```")
> rstudioapi::documentNew(paste(text, collapse="\n"), "rmarkdown")
```
![image](https://user-images.githubusercontent.com/470418/85339255-a08f5c80-b498-11ea-9c7f-8ac2b146bab0.png)

**Comment by jmcphers** [comment] 2020-06-22 22:06
@trestletech Does the above seem right to you?

**Comment by trestletech** [comment] 2020-06-22 22:10
🤦  yup. I went back and confirmed that this was indeed broken on 1031 but is now fixed on 1039. Sorry for the distraction!

**Closed by trestletech** 2020-06-22 22:10 UTC
Labels: bug, r markdown
