### ISSUE TITLE
Path autocompletion inconsistent with RMarkdown + Project folder

### ISSUE THREAD

**Issue by matthewgson** [rstudio/rstudio#9822] opened 2021-09-07 12:57 UTC
I found that the default file path (current working directory) for RStudio's autocompletion is set to the project's location, while R & Python's working directory on RMarkdown is the current file location. 

For example, say I opened a project located at a folder named `'my_project'`, and I'm currently working on `.rmd` file that is located at `'my_project/markdowns'`, then R and Python console working directory is set as `"my_project/markdowns"` meanwhile the RStudio autocompletion thinks that I'm currently at `'my_project'` folder. 

This makes it hard for users to use autocompletion for file path setting. I'm wondering if this is a known issue and I hope this may be fixed.

OS : macOS 11.5.2
My RStudio version: 

RStudio 2021-08.0.324-0 "Ghost Orchid" Daily (cc1e34cfbcb83289eecbb724f74ca3f015776a5f, 2021-08-18) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

**Comment by mikebessuille** [comment] 2021-09-07 17:49
duplicate of #9184

**Comment by mikebessuille** [comment] 2021-09-07 17:50
Thanks for logging this; we'll consider this as another vote for the bug to be fixed.  Marking this as duplicate and closing.

**Closed** 2021-09-07 17:49 UTC
