### ISSUE TITLE
git: In commit panel, "stage line" and "stage selection" buttons don't work unless "context" is "all lines"

### ISSUE THREAD

**Issue by hughjonesd** [rstudio/rstudio#5476] opened 2019-09-27 08:04 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5001
    OS Version      :  Mac OS 10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem

Make changes to a file in a project with git enabled. Click "commit"

If you select a line in the file at the bottom of the window, a button "stage line" is shown. If you select multiple lines, "stage selection" is shown. Click one of these.

### Describe the problem in detail

Nothing happens.

I discovered today that you *can* make these buttons work, by changing the context dropdown to "all lines".

### Describe the behavior you expected

I'd expect the buttons to work whatever the state of the context dropdown. Or, if they can only work when context is "all lines" for whatever reason, then make that clear somehow. 

This bug has been around in several previous versions of RStudio.

**Comment by ronblum** [comment] 2019-10-03 16:50
@hughjonesd Thank you for reporting the issue! I am able to reproduce it, and we'll review it as we address bugs during ongoing development of RStudio.

**Comment by gregleleu** [comment] 2019-10-15 17:15
Hi, it's not a recent bug, it's been like that for a while. Most of the time I stage everything and unstage the chunks I want to leave out, this works more often than staging the chunks I want.
Hope it helps

**Comment by julianbarg** [comment] 2020-03-10 13:57
@gregleleu I find myself not being able to unstage individual lines in addition to not being able to stage lines. This is on Rstudio Desktop version 1.2.5033 for Ubuntu 18.04, R version 3.6.3

**Comment by salim-b** [comment] 2020-05-28 20:17
This has been an issue for several years now (at least on Ubuntu/Linux) and the issue still persists with latest RStudio version 1.3.959 on Ubuntu 20.04.

> Most of the time I stage everything and unstage the chunks I want to leave out, this works more often than staging the chunks I want.

I'd suggest to use a separate Git client for the time being, like e.g. [Git Cola](https://git-cola.github.io/). Saves you a lot of headaches (and/or time). :wink:

**Comment by julianbarg** [comment] 2021-02-08 16:19
I think everybody can live with many of those git features not being there--after all, you can always use another Git client. Maybe removing some of the buttons and deliberately scaling down Git support is the way to go? RStudio doesn't need to be a full-scaled git client.

**Comment by salim-b** [comment] 2021-02-08 18:10
> I discovered today that you _can_ make these buttons work, by changing the context dropdown to "all lines".

The principle is: The <kbd>Stage line/selection</kbd> and <kbd>Discard line/selection</kbd> buttons do work as long as all changes are grouped by a single line context (e.g. within the default 5 lines as long as all changes are not more than 5 lines apart from each other).

> I think everybody can live with many of those git features not being there (...)

Personally, I would _really_ love this feature to work without always having to switch line context or falling back on another git client. For me, individual line/selection staging is pretty essential.

But of course, if you're not willing to fix this, I'd also be in favor of only displaying _working_ buttons.

**Comment by Mosk915** [comment] 2021-06-11 22:06
I'm running into this same issue on Server Pro.  I'm running version 1.3.1073-1 on Ubuntu 18.04.  Interestingly, on another server running version 1.3.959-1 and Red Hat 7.6, there is no issue.  I'm not sure if the issue is due to the different RStudio versions or the different Linux distros, but one comment above says the issue does occur on an Ubuntu machine running 1.3.959, so it seems like it may only be an issue on Ubuntu but not Red Hat.

Short of a fix, I would advocate for leaving the buttons since they do still work when the context is all lines and being able to break up lines into multiple commits is useful to be able to do.

**Comment by moodymudskipper** [comment] 2023-12-20 10:21
This has been a source of annoyance for me for as long as I can remember, I see the ticket has been upvoted quite a bit, is there any plan to tackle this at some point ?

**Comment by kevinushey** [comment] 2023-12-20 18:42
Placing back into triage for reconsideration.

**Comment by olivroy** [comment] 2024-02-06 16:48
With a recent daily, Stage / Unstage  line / selection do not work as intended. Stage / Unstage chunk / all lines still seem to work properly.

**Comment by kevinushey** [comment] 2024-02-06 16:51
@olivroy can you please elaborate, perhaps with a reproducible example?

**Comment by kevinushey** [comment] 2024-02-06 17:03
I think I was able to successfully reproduce; in particular, it looks like it requires a file with multiple changes in different chunks.

**Comment by olivroy** [comment] 2024-02-06 17:06
yes, exactly, if I click on Unstage line / selection, when there is a staged chunk, nothing happens!
![image](https://github.com/rstudio/rstudio/assets/52606734/c1237457-82c9-4825-99f5-22ae40cb8ed0)

I will let you know if I find other situations!

**Comment by kevinushey** [comment] 2024-02-06 19:41
There's a potential fix for this coming to the next daily builds; fingers crossed that this nips it in the bud!

**Comment by olivroy** [comment] 2024-02-08 19:08
Just tried the latest daily 2024.0+426! This appears fixed. Hooray!

**Comment by kevinushey** [comment] 2024-02-08 22:20
Awesome news -- many thanks for taking the time to test and report back!

**Comment by ronblum** [comment] 2024-02-22 14:35
Thanks @olivroy for checking!

Also confirmed that this is fixed in RStudio Server 2024.04.0-daily+475 on Ubuntu 22 via Chrome on MacOS 14.3.
- Checked that initially, all changed and unchanged lines are displayed correctly (all ustaged)
- Checked staging individual lines and selections, including noncontiguous selections
- Checked all contexts, from five lines to all
- Checked that the staged lines show up when viewing staged lines
- Checked that unstaging lines works, and that they show up when viewing unstged lines

Note: Previously a fifty-line context also worked, even though five through twenty-five did not.

**Closed by ronblum** 2024-02-22 14:35 UTC
Labels: bug, reproducible, vcs
