### ISSUE TITLE
Removing extra source pane closes files

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8353] opened 2020-11-12 08:10 UTC
**Steps to reproduce:**
* Open several R files in the editor.
* Add a new column to the layout having `Source` type (`Tools` -> `Global Options` -> `Pane Layout` -> `Add column`).
* Move some opened file from the default source pane into the new source pane.
* Remove the newly added column (same settings page from where it was added).

**Expected behavior:** should move the files that were opened to the next available source pane.

**Actual behavior:** the files are no longer opened in RStudio.

**Setup:** RStudio 1.4.953.

**Comment by melissa-barca** [comment] 2020-11-12 14:25
Thanks for reporting this! I can confirm this is not the intended functionality and was working properly in previous versions of 1.4

**Comment by melissa-barca** [comment] 2020-11-12 14:51
My mistake, this is actually the intended functionality. We assume the user has closed the column with the intent of closing the files. Only files with unsaved changes are preserved.

**Comment by melissa-barca** [comment] 2020-11-12 14:55
Reopening because it looks like unsaved changes are no longer being saved.

**Closed** 2020-11-12 19:47 UTC
Labels: source columns

**Comment by kfeinauer** [comment] 2020-11-13 15:46
Verified 1.4.1027
