### ISSUE TITLE
RStudio Viewer with rstan running in parallel: "The process cannot access the file because it is being used by another process"

### ISSUE THREAD

**Issue by daltonhance** [rstudio/rstudio#7046] opened 2020-06-05 16:33 UTC
## System details
    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Windows 10
    R Version       : 4.0.0

### Steps to reproduce the problem
This seems to happen with just about any Stan model since upgrading to the latest RStudio. The user may not notice with models that run very quickly.

It can be reproduced using the example model and data here: https://github.com/stan-dev/example-models/tree/master/knitr/lotka-volterra

```
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

lynx_hare_df <- read.csv("hudson-bay-lynx-hare.csv")

N <- length(lynx_hare_df$Year) - 1
ts <- 1:N
y_init <- c(lynx_hare_df$Hare[1], lynx_hare_df$Lynx[1])
y <- as.matrix(lynx_hare_df[2:(N + 1), 2:3])
y <- cbind(y[ , 2], y[ , 1]); # hare, lynx order
lynx_hare_data <- list(N = N, ts = ts, y_init = y_init, y = y)

reproducible_example <- stan("lotka-volterra.stan",
                                    data = lynx_hare_data,
                                    chains = 3)
```

This model takes about 22 seconds to run on my machine. If you are similarly spec'ed you'll have to be quick to reproduce, but not that quick.

### Describe the problem in detail
Once the model starts sampling the viewer tab will be automatically switched to. It will display the message: "Click the Refresh button to see progress of the chains." If I hit the Refresh button _while the Stan model is running_, the window will display the message: "The process cannot access the file because it is being used by another process." Once the model has finished running, if I hit the Refresh button, it will display the expected information: the progress of the chains and the elapsed time.

### Describe the behavior you expected
If I reinstall the previous version of RStudio, but keep everything else the same, I get the expected behavior. The expected behavior that when I hit the Refresh button while the Stan model is running the progress of the chains will be updated. This allows the user to monitor the chains in progress and get a sense of when the model will finish. Without this information, the user is flying blind until the model is finished.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mttinker** [comment] 2020-06-05 17:16
I have experienced the identical problem since upgrading to the latest versions of R (4.0) and RStudio (1.3.959), with same System details - also re-installed all libraries and latest version of Rtools, but problem remained. Happens with any Stan model run in parallel. Reverting to previous release of RStudio (1.2.5042) also fixes the problem for me.

**Comment by cbreiss** [comment] 2020-06-06 07:22
Same issue here - any hints on fixing it?

**Comment by kevinushey** [comment] 2020-06-08 23:18
```
> reproducible_example <- stan("lotka-volterra.stan", data = lynx_hare_data, chains = 3)
Error: cannot allocate vector of size 11126.2 Gb
```

Is that expected?

**Comment by daltonhance** [comment] 2020-06-08 23:27
No. That looks to be an R 4.0.0/Rtools40 conflicting with earlier installations. I ran into the same issue after first upgrading. 

There are several threads on the Stan forums dealing with this and related issues, although it may be enough to delete your Makevars.win. See:
https://discourse.mc-stan.org/t/dealing-with-r-4-0/14586/1
https://discourse.mc-stan.org/t/error-cannot-allocate-vector-of-size-17348-7-gb/14615/23

**Comment by mttinker** [comment] 2020-06-08 23:28
My recollection is that this was also an error message I got (the impossibly large vector size) before I updated all libraries after installing R 4.0, and specifically before I updated to the latest Rtools.  If you get that error message it is possible that rstan is still using the Rtools3.5 compiler, and you need to update to Rtools 4.  Once I had all the updated libraries, including updated Rtools, I no longer got the "cannot allocate vector of size 11126.2 Gb" error, but instead got the "The process cannot access the file because it is being used by another process." viewer window error.  Ahh, I see Dalton just replied with the same info...

**Comment by kevinushey** [comment] 2020-06-08 23:34
Thanks -- I reinstalled `rstan` + all its dependencies (using latest binaries from CRAN) and I can successfully reproduce the issue now. I'll try to dig deeper!

**Comment by kevinushey** [comment] 2020-06-09 05:01
Here's a smaller reprex:

```
# create dummy file with (invalid) HTML
path <- tempfile("viewer-", fileext = ".html")
writeLines("<html>Hello!</html>", con = path)

# try to invoke viewer with open connection to file
conn <- file(path, "r+")
rstudioapi::viewer(path)
close(conn)
```

The error occurs because we no longer use R's help server for reading files; instead, we use our own handler, as per https://github.com/rstudio/rstudio/pull/6804. With that change, our attempt to open the file here fails, as the file is already opened by R.

For posterity, this is the call that is failing:

https://github.com/rstudio/rstudio/blob/33cd4e0685a6f1f022a090676206209b50f066f0/src/cpp/shared_core/FilePath.cpp#L1384-L1391

Note that this works fine if we open a connection in R only for reading:

```
conn <- file(path, "r")
```

Based on the documentation here:

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea

> You cannot request an access mode that conflicts with the sharing mode that is specified by the dwShareMode parameter in an open request that already has an open handle.

IIUC, because we're trying to open the file only for reading, but R already has an open handle for both reading and writing, our open attempt fails. I can confirm this is the case as changing this line:

https://github.com/rstudio/rstudio/blob/33cd4e0685a6f1f022a090676206209b50f066f0/src/cpp/shared_core/FilePath.cpp#L1386

to read `GENERIC_READ | GENERIC_WRITE` fixes the issue.

Ultimately, there are two potential fixes here:

1. Use `GENERIC_READ | GENERIC_WRITE` when opening the file, just to avoid access failures due to incompatible access modes on already-open handles;

2. Revert #6804 and rely on R's help handler (which is now fixed for R 4.0.1).

@jmcphers: let me know if you have a preferred path forward.

**Comment by jmcphers** [comment] 2020-06-09 16:18
R 4.0.0 installations are already widespread so if we turn this off we're going to get a bunch of issues filed until everyone updates on Windows. IIRC 6804 only kicks in for R > 4.0.0 -- would it be easy to change it so that it kicks in for _exactly_ 4.0.0?

**Comment by mttinker** [comment] 2020-06-09 16:37
Sorry to ask an uninformed question, but I just noticed that R 4.0.1 was released - is this issue going to still occur with that version of R, or will updating to 4.0.1 fix it?

**Comment by jmcphers** [comment] 2020-06-09 16:43
Yes, it is going to occur. The problem is that RStudio has a workaround for a bug in R 4.0.0, and that workaround triggers another bug (this one). RStudio needs to remove or revise its workaround (as outlined by @kevinushey) to fix this.

**Comment by mttinker** [comment] 2020-06-09 16:48
Ahhh, now I see. That is a conundrum...

**Comment by jmcphers** [comment] 2020-06-12 18:36
@kevinushey I'll take this one.

**Closed** 2020-06-15 18:01 UTC
Labels: bug, regression, stan

**Comment by R-Hannibal** [comment] 2020-06-29 14:10
@daltonhance, thanks so much for finding and reporting this issue. We have a fix in place in our latest preview build 1.3.1054 (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). 

If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by daltonhance** [comment] 2020-06-30 21:54
I can confirm that after updating to R 4.0.2 and the preview build that this issue is resolved.

**Comment by R-Hannibal** [comment] 2020-07-01 14:07
Excellent, thanks for the follow up @daltonhance and for filing such a detailed issue report.
