### ISSUE TITLE
RStudio incorrectly displays a diagnostic message "no symbol ... in scope" when formula saved as variable

### ISSUE THREAD

**Issue by CameronBieganek** [rstudio/rstudio#5995] opened 2020-01-10 17:59 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : MacOS 10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem

With the following code,

```r
df <- data.frame(x = rnorm(10), y = rnorm(10))

my_formula <- y ~ x

X <- model.matrix(my_formula, df)
```

we get an incorrect diagnostic error message:

![image](https://user-images.githubusercontent.com/8310743/72174391-49407880-339f-11ea-9f52-d9ac45d67c8f.png)

### Describe the problem in detail

See above, which contains a minimal working example.

### Describe the behavior you expected

The variable `my_formula` is clearly in scope, so there should be no diagnostic error message.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-01-10 20:29
@CameronBieganek Thank you for reporting the issue! I can confirm it in RStudio Desktop and Server 1.2.5033 on MacOS 10.15 and Red Hat 7, respectively. However, it isn't an issue in RStudio Desktop 1.3.730 on MacOS 10.15, so I'm marking this as resolved. 

If you're interested, you can try out [the latest RStudio daily development builds](https://dailies.rstudio.com/). However, please note that development builds are intended for testing purposes only.

**Closed by ronblum** 2020-01-10 20:29 UTC
