### ISSUE TITLE
LoadLibrary failure when launching RStudio Version 1.3.1093

### ISSUE THREAD

**Issue by gmukherjee98** [rstudio/rstudio#8318] opened 2020-11-09 09:29 UTC
The issue tracker is not for questions. If you have a question, please feel free to ask it on our community site, at https://community.rstudio.com/c/rstudio-ide.

I get the following message on installing R4.0.03, RStudio Version 1.3.1093 and Julia 1.5.2

Would appreciate any feedback
Kind regards,

Error: package or namespace load failed for ‘stats’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Program Files/R/R-4.0.3/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.

During startup - Warning message:
package ‘stats’ in options("defaultPackages") was not found 
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Program Files/R/R-4.0.3/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.
Warning: namespace ‘JuliaCall’ is not available and has been replaced
by .GlobalEnv when processing object ‘prob’

**Comment by kevinushey** [comment] 2020-11-09 19:12
Dupe of https://github.com/rstudio/rstudio/issues/8317.

**Closed by kevinushey** 2020-11-09 19:12 UTC
