### ISSUE TITLE
Particular pane layout not working on server (but fine on desktop)

### ISSUE THREAD

**Issue by macek2** [rstudio/rstudio#4964] opened 2019-06-17 18:57 UTC
### System details

    RStudio Edition : Server
    RStudio Version : Tested on 1.1 and 1.2
    OS Version      : Ubuntu
    R Version       : 3.5.2

### Steps to reproduce the problem
In global options, attempt to set the pane layout to the following configuration:

![Screen Shot 2019-06-17 at 11 53 49 AM](https://user-images.githubusercontent.com/44280497/59629143-0a8f5c00-90f7-11e9-9946-2e27eedf6bc7.jpg)

### Describe the problem in detail
Console remains on left, and viewer/plot do not move to correct pane.

**Comment by macek2** [comment] 2019-06-17 19:01
It seems that viewer is the main culprit here. Moving Viewer to the bottom right pane works

**Comment by pascaloettli** [comment] 2019-06-19 10:37
RStudio Edition : Server
    RStudio Version : 1.1.463, 1.2.1522, 1.3.260
    OS Version      : Ubuntu 18.04.2 (server), macOS 10.14.5 (client) 
    R Version       : 3.6.0
    Interface       : Firefox 67.0.2

Reproducible on: `1.1.463`
Not Reproducible on: `1.2.1522` and `1.3.260`

**Comment by ronblum** [comment] 2019-06-19 19:08
@macek2 What version of RStudio Server 1.2 are you using? I'm able to reproduce it as late as 1.2.1335, which is the latest release. However, I can't reproduce it with 1.2.1541, [the current RStudio Preview](https://www.rstudio.com/products/rstudio/download/preview/). What do you get if you use the preview?

Note: with enough moving around I was able to get Viewer to interfere only if it's in the lower left and work fine if it's in the upper right.

**Comment by macek2** [comment] 2019-06-19 19:12
I'm using 1.2.1335-1

**Comment by ronblum** [comment] 2019-06-20 17:53
@macek2 That sounds reasonable. I'll close the issue as fixed in the upcoming version of 1.2. When you it's released and you upgrade, please let us know if you still run into the issue. Thanks!

**Closed by ronblum** 2019-06-20 17:53 UTC
Labels: bug, repro needed

**Comment by gtritchie** [comment] 2019-06-20 18:03
I haven't read this issue in detail, but possibly fixed by this (which was put in 1.2-patch): https://github.com/rstudio/rstudio/pull/4502

**Comment by ronblum** [comment] 2019-06-20 18:23
@gtritchie Aha! This is a duplicate of #2101.
