### ISSUE TITLE
rstudio 2022.12.0+353 fails to find conda installed R (works with 2022.07) on Ubuntu 18.04

### ISSUE THREAD

**Issue by gdevenyi** [rstudio/rstudio#12508] opened 2022-12-30 18:03 UTC
### RStudio Version

RStudio 2022.12.0+353 "Elsbeth Geranium " (7d165dcf, 2022-12-03) for Ubuntu Bionic

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code 127. 

Error output:

```
/usr/lib/rstudio/resources/app/bin/rsession: error while loading shared libraries: libR.so: cannot open shared object file: No such file or directory

```

Standard output:

```
[No output emitted]
```

### Logs

*/home/gdevenyi/.local/share/rstudio/log/rsession-gdevenyi.log*

```
rstudio-0.js#-1::eval
Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e
User-Agent: Mozilla/5.0 (X11  Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

```

**Comment by gdevenyi** [comment] 2022-12-30 18:03
Reverting to 2022.07 and running in the same environment successfully finds libR.so and runs.

rstudio-desktop 2022.12 installed from conda feedstock works.

**Comment by ronblum** [comment] 2023-01-04 15:48
@gdevenyi Thank you for raising this! I'll mark this for review as we continue development of RStudio.

**Comment by howff** [comment] 2023-02-14 08:44
Also reported here https://community.rstudio.com/t/setting-rstudio-which-r-fails-to-find-libr-so/157920

This is definitely a regression from version 2022.07.2.576 which worked fine.

Using RSTUDIO_WHICH_R to specify the R executable (which happens to be in a conda environment) but RStudio fails to run it, saying it can't find libR.so. Running that same executable directly works fine. Old versions of RStudio work fine. The latest version of RStudio fails. I can't even set LD_LIBRARY_PATH to say where libR.so is, because RStudio now seems to throw away that variable. Unlike RStudioServer there's no option to preserve it.

**Comment by amizeranschi** [comment] 2023-03-24 19:31
I am running into the same issue (error while loading shared libraries: libR.so) now with RStudio 2023.03.0 on Ubuntu 22.04, having R installed via conda and configured via RSTUDIO_WHICH_R. 

Can also confirm that version 2022.07.2.576 works fine.

**Comment by zqun1** [comment] 2023-05-05 16:10
A few days ago, I accidentally updated R on my Ubuntu22.04. And now I have the same problem with RStudio 2023.03.0 on Ubuntu 22.04 as described here: https://stackoverflow.com/questions/76102591/how-to-change-r-version-in-rstudio-inside-a-conda-environment-in-ubuntu?newreg=6dfacc1b9054432aaf97c440b4bf037c. Also redirected from there to vote for the bug fix. Again confirm that version 2022.07.2.576 works fine. 
Could the RStudio team fix the error with the newest version of RStudio please?

**Comment by abalter** [comment] 2023-05-31 16:37
I'm having the same issue except I can't seem to find any version of rstudio that will work for me. I'm going to raise a separate issue.

Note: Using Ubuntu 22.04 in WSL2. My R executable is installed with conda (micromamba).

**Comment by gdevenyi** [comment] 2023-08-31 02:37
Bug still alive and well in 2023.06.2-561

**Comment by kevinushey** [comment] 2024-03-20 16:17
This may be a duplicate of https://github.com/rstudio/rstudio/issues/13184. If so, I would expect to see this issue resolved in the latest daily builds of RStudio, available for testing at https://dailies.rstudio.com.

**Comment by abalter** [comment] 2024-03-20 17:02
I'll try to test this today or this evening.

**Comment by gdevenyi** [comment] 2024-03-20 19:04
I can confirm `rstudio/2024.04.0-daily-624` on Ubuntu 22.04 can load R from conda environments.

**Comment by ronblum** [comment] 2024-03-20 19:11
@gdevenyi Woo hoo! Commenting in a [Hacker News post](https://news.ycombinator.com/item?id=39764887#39768008) isn't usually how we prioritize issues, but it worked in this case. 😄

**Closed by ronblum** 2024-03-20 19:11 UTC
Labels: bug, r versions

**Comment by gdevenyi** [comment] 2024-03-20 19:43
> @gdevenyi Woo hoo! Commenting in a [Hacker News post](https://news.ycombinator.com/item?id=39764887#39768008) isn't usually how we prioritize issues, but it worked in this case. 😄 

Sometimes, you need to do what gets results 😁

**Comment by kevinushey** [comment] 2024-03-20 22:06
In our defense, we did fix the underlying issue before the Hacker News post :-)

Either way, apologies it took so long for us to get to the bottom of the issue, but we're glad to hear things are now working!
