### ISSUE TITLE
Popping out individual panes (e.g. console)

### ISSUE THREAD

**Issue by phillyo** [rstudio/rstudio#2833] opened 2018-05-23 12:15 UTC
Currently, it is possible to pop out the source pane using the "Show in new window" button. This will pop out the current tab into a separate window. It would be really useful if all the panes could be popped out to be displayed in their own, dedicated window. For example, when working on two screens, I'd like to have the console pane on my secondary screen and all my files in the source tab on the primary screen.

**Comment by ronblum** [comment] 2018-05-23 13:56
@phillyo Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio.

**Comment by Nova-Scotia** [comment] 2019-02-21 14:50
I send this request! I always want to display my data.frames in a separate window and would prefer to set a default under "Global Options". The default could allow a user to choose to always view data sets in a new window. Thanks for considering this request!

**Comment by dwhdai** [comment] 2019-04-12 15:34
I think the ability to pop out the console would be great, especially for people who have multi-monitor setups.

**Comment by hzarkoob** [comment] 2019-07-25 23:33
I second this request too. Ideally it should be possible to tear out any and all panes, including the console and the files pane. In addition to the benefit mentioned above, this will allow users to use the standard OS or browser (in case of RStudio server) keyboard shortcuts to switch between panes.

Thank you for looking into this!

**Comment by 579amal** [comment] 2019-09-06 00:00
I was searching for the same today morning. Seems like it's not there yet.

**Comment by freddie090** [comment] 2019-10-07 11:11
Trying to think of a reason why popping out the editor is fine, but the console would cause an issue (and hence why it isn't yet a feature) ... I further this request! It would be even cooler if it was possible to pop out two panes to a single window.

**Comment by gomfy** [comment] 2019-11-19 16:56
I second this request too. Thank you for considering it.

**Comment by maciejmotyka** [comment] 2019-12-10 16:15
Yes, please! It would solve #5498 for instance. Users could take advantage of tiling window managers like e.g. i3wm.

**Comment by mghassany** [comment] 2020-04-12 18:08
I second this request too. Please!

**Comment by teecrow** [comment] 2020-04-17 16:30
+1 to this...would be very useful to choose which Rstudio Panes go on which monitor (or in which window).

**Comment by TheAndrewLucore** [comment] 2020-04-24 15:07
Consider this another +1. This or even the ability to pop out the entire Source pane instead of just individual scripts.

**Comment by lrnv** [comment] 2020-05-19 14:25
Consider one more +1. At least allow to get out the console pane to have source / console / rest on separate monitors. Is this even considered by developpers or not ?

**Comment by gtritchie** [comment] 2020-05-19 16:12
> Is this even considered by developers or not

Yes, we see these requests and want to do them but there are many competing things to do!

**Comment by fabeit** [comment] 2020-05-29 08:30
+1. Is there a way to have View(df) display in a new window and not on the source pane?

**Comment by valuat** [comment] 2020-06-03 22:19
+1. Having the Plots pane on a separate window would be awesome: 1 monitor for Source, another for Console and the last for Plots. Perfect.

**Comment by hengtangum** [comment] 2020-06-16 03:03
+1

**Comment by grabearummc** [comment] 2020-07-16 20:52
+1

**Comment by Zenginee** [comment] 2020-07-18 14:59
+1

**Comment by jacksonmluckey** [comment] 2020-07-29 18:22
+1

**Comment by umairrafique85** [comment] 2020-09-17 14:43
Another +1. It would seriously help even in single display settings.

**Comment by SFlantua** [comment] 2020-09-29 11:13
+1

**Comment by JimmyAusDS** [comment] 2020-11-24 12:50
+1 for the ability to detach all panes to separate windows, but especially detaching the variable view tab from the source pane! We appreciate your efforts!

**Comment by tsbarr** [comment] 2020-12-15 15:11
+1

**Comment by corneliagru** [comment] 2021-01-03 13:20
+1

**Comment by conmccann1** [comment] 2021-01-06 17:07
+1

**Comment by paulmelki** [comment] 2021-02-03 09:04
+1

**Comment by christopherball** [comment] 2021-02-09 16:56
+1

**Comment by ronblum** [comment] 2021-02-10 20:38
All y'all providing the +1s—I'm glad to see the enthusiasm! But also, in case you haven't already, give a thumbs up 👍 in the initial request at the top. It's one of the things we take into consideration when deciding on which features to implement. Popularity doesn't guarantee implementation, but it helps. 😄

**Comment by slager** [comment] 2021-03-03 16:54
+1

**Comment by spirosbax** [comment] 2021-03-25 10:35
+1

**Comment by juanvillada** [comment] 2021-04-02 21:49
+1

**Comment by juanvillada** [comment] 2021-04-02 21:56
+1

**Comment by jonhersh** [comment] 2021-07-02 04:43
+1!

**Comment by jjfantini** [comment] 2021-08-31 22:27
+1

**Comment by evgeniou** [comment] 2021-09-15 09:23
+1 for the console... it would be great!

**Comment by danielye8** [comment] 2021-10-15 00:28
+1

**Comment by jzadra** [comment] 2021-11-17 21:02
+1 this is sorely needed!

**Comment by sahil5695** [comment] 2021-11-24 00:20
+1

**Comment by alohacocoa** [comment] 2022-01-04 07:50
+1 for popping out the console!

**Comment by evgeny-vlasov** [comment] 2022-01-10 13:25
+1

**Comment by jrussell9000** [comment] 2022-01-11 18:23
+1

**Comment by farteins** [comment] 2022-01-27 11:36
+ 1

**Comment by DeuceWallaces** [comment] 2022-02-15 18:41
The source and plot popouts are nice, but being able to deconstruct the 4 major panes would be fantastic.

**Comment by joshua-theisen** [comment] 2022-04-12 13:33
+1

**Comment by kmshort** [comment] 2022-05-18 00:28
I have 2 monitors, one sitting in vertical orientation. It's perfect for an undocked console window. :)
Pleeeease 👍

**Comment by jmcphers** [comment] 2022-05-19 22:30
I noticed today that this is (quite literally) also the number one feature request for VS Code, which (needless to say) doesn't have this feature yet either. 

https://github.com/microsoft/vscode/issues/10121

**Comment by lrnv** [comment] 2022-05-20 08:53
@jmcphers You are right. In fact, this is a requested feature of any IDE, it is just that some are better at it than others (otherwise said, some have code bases that are easier for this thing than others). 

The problem is more or less the following : what these IDEs call *panes* would be more appropriately handled as *windows*, directly by the window manager: these editors are doing a job that should not theirs to do (managing the placement of windows on the screen). Pycharm is e.g. very good at allowing people to swich between "considering things as panes and handling them itself" or "considering things as windows and giving them back to the WM", letting you choose for each pane/window what you prefer. This is IMHO the best behavior, although probably the hardest to code.

**Comment by CevallosT-D** [comment] 2022-05-26 17:47
+1

**Comment by j-hoefner** [comment] 2022-06-23 10:23
+1

**Comment by odros** [comment] 2022-07-27 09:54
This would definitely increase the versatility of this already fantastic IDE!

**Comment by JesusSierralaya** [comment] 2022-08-13 10:54
+1

**Comment by zickyls** [comment] 2022-09-26 16:31
+1

**Comment by sarpcebeci** [comment] 2022-10-07 16:39
+1

**Comment by hoeoek** [comment] 2022-12-16 07:01
I'm also on a two-monitor setup, with one being vertical. I would LOVE to be able to detach the console!

**Comment by jzadra** [comment] 2022-12-16 17:01
It would be nice to just have every single pane or even every single tab pop out!

**Comment by jbwettergreen** [comment] 2023-03-07 12:10
+1

**Comment by Delta-43** [comment] 2023-04-14 07:58
+1 Please implement this feature

**Comment by doraemoniloveu** [comment] 2023-04-19 01:46
+1 It is not convenient when I want to edit two different scripts in the same time, please implement this function

**Comment by gtritchie** [comment] 2023-04-19 22:54
> +1 It is not convenient when I want to edit two different scripts in the same time, please implement this function

RStudio can have multiple scripts visible simultaneously. This issue requests showing other panes such as the Console in a separate window, which is not currently possible.

The main window can show multiple source panes via "source columns". Use View / Panes / Add Source Column or File / Open File in New Column. More on source columns in [this blog post](https://posit.co/blog/rstudio-1-4-preview-multiple-source-columns/).

You can also move a script you have open in the main window to a new window via "Show in New Window" (see screenshot below with an arrow pointing to the icon that does that). Or you can drag the document's tab from the main window and drop it on the desktop to create a new window.

For example, here you can see 4 different scripts at the same time, some in the main window, some in separate windows.

<img width="2560" alt="Screenshot 2023-04-19 at 16 43 33" src="https://user-images.githubusercontent.com/10569626/233216335-436e54f1-ec80-4228-90ec-e27b9fe42fc2.png">
<img width="576" alt="Screenshot 2023-04-19 at 16 46 43" src="https://user-images.githubusercontent.com/10569626/233216358-8c31e1ff-f495-45a1-baf2-bce01cbbab4f.png">

**Comment by odros** [comment] 2023-04-20 12:01
I don't know if something has changed, all of us in the thread are unaware (or blind, to say the least) or if I interpret something wrongly, but I have console, variable explorer and editor panes undocked as I type this:

![image](https://user-images.githubusercontent.com/44981224/233358372-ce6aff81-e8c9-4a39-866b-349b0aab23a9.png)

You just have to go to the three-lines-icon of any pane/tab and click 'Undock' (example for console follows):

![image](https://user-images.githubusercontent.com/44981224/233359619-8032d3cd-9389-4107-b00e-d65476a4d342.png)

**Comment by joshua-theisen** [comment] 2023-04-20 12:15
What OS and RStudio version are you using? I don't have that on Windows 11, RStudio 2023.03.0
![image](https://user-images.githubusercontent.com/49253139/233362832-f2682ff8-289a-406d-aa98-1e5ec01f6270.png)

**Comment by JulianMF-lab** [comment] 2023-04-24 16:47
+1

**Comment by geodevm** [comment] 2023-06-15 00:29
+1

**Comment by jzadra** [comment] 2023-06-15 05:46
This has been requested since 2018.  It's not happening.

**Comment by abduazizR** [comment] 2023-07-19 17:22
+1

**Comment by Arethusag** [comment] 2023-09-13 16:36
+1 for pop-out tab on all panes. having the source pane on main monitor and console, environment etc... on other monitors is currently not possible

**Comment by peterjosephkidd** [comment] 2023-09-22 09:38
+1

**Comment by abduazizR** [comment] 2023-10-31 14:08
+1

**Comment by BAlmeidaS** [comment] 2023-11-14 17:08
+1 on this one :pray:

**Comment by jjfantini** [comment] 2023-11-14 19:09
@BAlmeidaS unfortunately, probs not going to happen... it been open for 5 years now.

I used to be a die hard Rstudio user. After a little struggling I would highly recommend you move to VSCode/Cursor IDE :D

**Comment by kmshort** [comment] 2023-11-14 21:39
Re:vscode - I like the inline rendering of the rmarkdown and live
plotting/package help, environment view, etc.  Are there vscode plugins to
allow that?

**Comment by Vetrarsol** [comment] 2024-02-06 09:13
I know that adding comments to this ticket doesn't mean it'll get done any faster (or at all), but that said, PLEASE implement this, it would be a real life-saver. Thanks!

**Comment by jonbry** [comment] 2024-04-27 19:32
Console messages in a separate pane will make it much easier to read long console messages and copy them for sharing/troubleshooting, It's been great to see Posit increase support for more languages/integrations and one side effect is that console messages have become more important and longer.

**Comment by jzadra** [comment] 2024-06-20 20:32
Since it's been 6 years, I sort of doubt this is happening.

**Comment by Cleiti** [comment] 2024-07-15 11:15
:( 
what if it happens

**Comment by jonbry** [comment] 2024-07-15 12:44
> Since it's been 6 years, I sort of doubt this is happening.

It only took 8 years for VS Code to get [floating editor windows](https://github.com/microsoft/vscode/issues/10121), so I still have hope.

**Comment by maximilian-leitheiser** [comment] 2024-07-18 13:58
+1

**Comment by jthomasmock** [comment] 2024-07-31 20:59
Howdy folks, I don't want to get people's hopes up about this feature, so I will close this one as "Not Planned". 

It's never fun to say no, but while this is theoretically possible, we've estimated the effort as several months' worth of truly focused development, at the cost of other work in RStudio. It would also be an extremely "invasive" change to the RStudio codebase that could introduce additional regression risk to core areas of the IDE.

**Closed by jthomasmock** 2024-07-31 20:59 UTC
Labels: enhancement, console, layout
