### ISSUE TITLE
Add button or menu item in the Files Pane to create a new R script in the directory viewed in the Files Pane

### ISSUE THREAD

**Issue by maskypy40** [rstudio/rstudio#7344] opened 2020-07-14 09:46 UTC
I frequently want to create a new R script in the directory I am viewing in the Files Pane.
Most times it is not the (set) working directory I am viewing. I have projects which consists of lots of directories with R scripts, so setting the working directory is more a hindrance than an helpful tool.

To create a new R script in that directory I go to the File menu | New file | R script and it gives me a new R script, which can be saved. When saving that new R script R Studio shows me a dialogue with the default directory, which is not the directory I am viewing in the Files Pane (that's where I want it). Thus I have to manually navigate to that directory to save the new R script. 

I was wondering whether this rather cumbersome way to save my R script could be turned into a simple click on a button or an additional menu item in the Files Pane.

**Comment by jmcphers** [comment] 2020-07-14 15:59
Duplicate of https://github.com/rstudio/rstudio/issues/1564.

**Closed by jmcphers** 2020-07-14 15:59 UTC

**Comment by maskypy40** [comment] 2020-07-15 10:12
After searching a lot I hadn't find #1564. 
Had I found it, I wouldn't have opened this one.
