### ISSUE TITLE
Python results do not show in REPL, but only appear after quit REPL in RStudio Preview Version 1.3.1058 and Daily Version 1.4.614

### ISSUE THREAD

**Issue by Fred-Wu** [rstudio/rstudio#7381] opened 2020-07-18 14:11 UTC
I am excited to test the RStudio daily build features especially the one to show python objects in the environment. 
However, in the current preview Version 1.3.1058 and daily build Version 1.4.614, python results won't show in REPL through `reticulate`, but only appear after quit REPL. 

Also when I `source_python()`, all the python objects are imported to R Global Environment, is this an intended feature? 
 
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.1058 and 1.4.614
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.2

### Describe the problem in detail

```
> reticulate::repl_python()
Python 3.7.7 (/usr/lib/anaconda3/bin/python)
Reticulate 1.16.9000 REPL -- A Python interpreter in R.
>>> import numpy as np
>>> import pandas as pd
>>> import datatable as dt
>>> 
>>> df = pd.DataFrame({'A': np.random.rand(5), 
...                    'B': ['a', 'b', 'b', 'a', 'b']})
>>> df
>>> print("Hello, World")
>>> quit
          A  B
0  0.710678  a
1  0.481517  b
2  0.221885  b
3  0.156073  a
4  0.960261  b
Hello, World
```

**Comment by kevinushey** [comment] 2020-07-18 22:03
> Also when I source_python(), all the python objects are imported to R Global Environment, is this an intended feature?

Can you please file this as a separate issue?

It looks like this might actually be an issue in the development version of `reticulate` -- I cannot reproduce with the CRAN release (1.16). I can reproduce in RStudio v1.2 as well with the development version of `reticulate`.

**Comment by kevinushey** [comment] 2020-07-20 22:48
This should now be fixed in the development version of `reticulate` -- please upgrade and let me know if you still see an issue.

**Closed by kevinushey** 2020-07-20 22:48 UTC
Labels: backlog, bug, python

**Comment by Fred-Wu** [comment] 2020-07-21 05:35
> This should now be fixed in the development version of `reticulate` -- please upgrade and let me know if you still see an issue.

Thanks for the quick fix. I can confirm that the issue has been resolved after upgrading to the development version of `reticulate`.

**Comment by R-Hannibal** [comment] 2020-08-27 17:17
Marking this issue as verified and external based on the comment trail indicating that the issue was resolved by upgrading to the latest version of `reticulate`.
