### ISSUE TITLE
Save/open window appears behind the IDE on Linux

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11160] opened 2022-05-09 15:25 UTC
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily+374
    OS Version      : Red Hat 8.5, Ubuntu 20.04.3
    R Version       : 4.0.3, 4.1.2

### Steps to reproduce the problem

1. If open, close RStudio Desktop.
2. Start RStudio Desktop.
3. <kbd>File -> Open File</kbd>
    - The "Open File" window opens up in front (correct).
4. <kbd>Esc</kbd>
    - The "Open File" window closes.
5. <kbd>File -> Open File</kbd>
    - The "Open File" window opens behind the IDE (incorrect).

### Describe the problem in detail

After the first time, anytime a file window opens, such as with open file, save, and save as, it appears behind the IDE.

### Describe the behavior you expected

The window appears in front of the IDE, as with Qt version and on MacOS.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2022-05-09 15:50
Duplicate of #11100. Related to Electron issue https://github.com/electron/electron/issues/32857.

**Closed by gtritchie** 2022-05-09 15:50 UTC
Labels: bug, duplicate, source editor
