### ISSUE TITLE
Ctrl + Enter and code style

### ISSUE THREAD

**Issue by rjake** [rstudio/rstudio#7256] opened 2020-07-01 15:50 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.3.869
    OS Version      :  Windows 10
    R Version       :  4.0.0

### Steps to reproduce the problem
I've noticed that Ctrl + Enter sometimes errors out at the bottom if the pattern is mismatched re: code touching the parentheses or not.

Here's an example
```r
library(tidyverse)

mpg %>% 
  mutate(
    x1 = "ok here") %>% 
  mutate(
    x2 = "not ok") # use Ctrl + Enter in this line
```
### Describe the problem in detail
I evaluated the following acceptable styles
```r
# fine
annotate("text", 
         label = "plot mpg vs. wt")

# fine
annotate(
  "text",
  label = "plot mpg vs. wt"
)

# not fine
annotate("text",
  label = "plot mpg vs. wt"
)
```
### Describe the behavior you expected
I expect the code to work in either configuration.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by francisbarton** [comment] 2020-07-02 11:34
This drives me crazy too.

**Comment by kevinushey** [comment] 2020-07-21 19:06
Closing as dupe of https://github.com/rstudio/rstudio/issues/6248.

**Closed by kevinushey** 2020-07-21 19:06 UTC
Labels: backlog, bug, source editor
