### ISSUE TITLE
Source panel marking non-ASCII characters in qmd file as "unexpected token"

### ISSUE THREAD

**Issue by harry-xm** [rstudio/rstudio#15316] opened 2024-10-15 03:17 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.09.0+375
    OS Version      : macOS 15.0.1
    R Version       : 4.3.3

### Steps to reproduce the problem

1. Open a qmd file.
2. Parse a csv file with readr.
3. Reference a column with non-ASCII characters.

### Describe the problem in detail

The non-ASCII characters are marked in red, and its hover tooltip shows `unexpected token '区'`. However, the notebook can be rendered or executed successfully.

### Describe the behavior you expected

RStudio 2024.04.2 with the same version of R did not have this issue, so it seems to be a regression.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2024-10-15 03:48
Can you please share a readily reproducible example?

**Comment by kevinushey** [comment] 2024-11-08 18:35
It looks like this occurs because the character is not considered an identifier by the standard library on macOS. For example:

```c
#include <locale.h>
#include <stdio.h>
#include <wchar.h>
#include <wctype.h>

int main() {
	setlocale(LC_ALL, "en_US.UTF-8");
	wchar_t ch = L'区';
	printf("iswalnum(): %i\n", iswalnum(ch));
	return 0;
}
```

On macOS, this gives me:

```sh
$ clang test.c; ./a.out
iswalnum(): 0
```

On my Linux VM, this gives me:

```sh
$ gcc test.c; ./a.out
iswalnum(): 1
```

Hopefully this will be fixed in an upcoming update to macOS, but if not, we could try to work around it.

**Closed** 2024-12-23 19:20 UTC
Labels: bug, regression, locale
