### ISSUE TITLE
RStudio server drop down menus not showing on Ubuntu 20.04.4

### ISSUE THREAD

**Issue by nbafrank** [rstudio/rstudio#11007] opened 2022-04-18 00:44 UTC
### System details

    RStudio Edition : Server
    RStudio Version : rstudio-server-2022.02.1-461-amd64.deb
    OS Version      : Ubuntu 20.04.4
    R Version       : 4.0.2

### Steps to reproduce the problem
Just starting a project shows this issue

### Describe the problem in detail

I cannot see the dropdown menus I can click on them but the rendering disappears. I have to close any notebooks, scripts, to actually see them. Once I have any file/notebook open, I cannot see them anymore.

### Describe the behavior you expected

To be able to use the dropdown menus without any issue

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-04-19 16:39
@nbafrank Thank you for raising the issue! I haven't been able to reproduce this, though. A few questions:
1) What operating and browser are you using to connect to RStudio Server?
2) What desktop environment are you using? Plasma, GNOME, etc.

Note: This might be a duplicate of #7585.

**Comment by nbafrank** [comment] 2022-04-19 22:23
I connect remotely to it. I use OsX Monterey/Safari to it. It was working previously

**Comment by nbafrank** [comment] 2022-04-22 00:10
@ronblum let me know if you make any progress :)

**Comment by nbafrank** [comment] 2022-04-23 16:30
Update: this issue is solved when using Firefox. It exists only in Safari so far.

**Comment by zhihuai1982** [comment] 2022-04-25 03:10
here is the same problem
https://github.com/rstudio/rstudio/issues/10821 

you can fix it by install the lastest bulid of rstudio sever
https://dailies.rstudio.com/rstudio/spotted-wakerobin/server/bionic/

**Comment by gtritchie** [comment] 2022-04-25 14:49
Duplicate of #10821.

**Closed by gtritchie** 2022-04-25 14:49 UTC
Labels: bug, duplicate
