### ISSUE TITLE
quarto render button does not find extensions embedded at the project level

### ISSUE THREAD

**Issue by andrewpbray** [rstudio/rstudio#13961] opened 2023-11-18 17:24 UTC
I'm running into unexpected behavior when rendering a file that uses a custom format that is installed at the project level. Say you have a default website with one new file, `slides/deck1.qmd` and a custom revealjs format, `storybook`, installed at the project level.

```
├── _quarto.yml
├── about.qmd
├── index.qmd
├── styles.css
├── _extensions
|   ├── mcanouil
|       ├── storybook
|           ├── _extension.yml
|           ├── ... and so on...
├── slides
|   ├── desk1.qmd
```

When I open up `desk1.qmd` in RStudio and click the Render button, I get:

``` bash
ERROR: NotFound: No such file or directory (os error 2), stat '/Users/andrewbray/Desktop/testwebsite/slides/_extensions/mcanouil/storybook/mcsb.svg'

NotFound: No such file or directory (os error 2), stat '/Users/andrewbray/Desktop/testwebsite/slides/_extensions/mcanouil/storybook/mcsb.svg'
```

Which makes it look like it's looking for the extension at the document level. It works just fine if I render the entire project or if I run `quarto render slides/deck1.qmd`. Is this the intended behavior?

MWE found here:

<https://github.com/andrewpbray/testwebsite>

### Versions
I'm running quarto 1.3.433 and RStudio 2023.09.1+494 (2023.09.1+494).

_Originally posted by @andrewpbray in https://github.com/quarto-dev/quarto-cli/discussions/7452_

**Comment by andrewpbray** [comment] 2023-12-01 21:56
Hello, I just wanted to check and see: is there somewhere else I should post this?

**Comment by petetronic** [comment] 2024-01-12 20:26
@andrewpbray Thank you for raining this issue! I was able to reproduce the issue and I've marked it for review by the team.

**Comment by kevinushey** [comment] 2024-01-22 17:58
@dragonstyle -- I suspect the issue here is that RStudio sets the working directory as the `slides` sub-directory when rendering:

```
==> quarto preview deck1.qmd --to storybook-revealjs --no-watch-inputs --no-browse
```

Is it RStudio's responsibility to set the working directory to the project directory here, or should quarto be able to look for extensions at the quarto project root?

**Comment by dragonstyle** [comment] 2024-01-22 18:03
It is definitely Quarto's job to find project level extensions (and resolve them properly). This looks like a Quarto bug and I can reproduce this outside of Rstudio in a simple terminal.

I think we should transfer this to the `quarto-cli` repo if you're ok with that?

**Comment by dragonstyle** [comment] 2024-01-22 18:11
(I've opened a Quarto issue and updated the discussion thread which originated the bug, you are safe to close this issue as this is definitely not a RStudio bug).

**Comment by kevinushey** [comment] 2024-01-22 18:41
Great -- thank you for taking a look so quickly!

**Closed by kevinushey** 2024-01-22 18:41 UTC
Labels: bug, quarto
