### ISSUE TITLE
searching for citations removes previously selected ones with visual editor

### ISSUE THREAD

**Issue by LDSamson** [rstudio/rstudio#8521] opened 2020-12-02 22:13 UTC
Hi Rstudio developers, I really love the new Rstudio version with the visual markdown editor. Here is a small problem I encountered when using the newly integrated citation panel and adding multiple citations. I couldn't find any .previous reports about this yet.

### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1056
    OS Version      :  Windows 10
    R Version       :  4.0.2

### Steps to reproduce the problem
Open a new markdown template and connect a bibliography with at least two citations. Switch to the new visual editor. Open the 'add citation' window (ctr+shift+f8). Click once on the `+` sign next to a random citation to add it to the 'selected citation keys' box. Now use the search box to search for a second citation. 

### Describe the problem in detail
The first citation key that was selected is deleted from the selection as soon as you start typing to search for a second citation.

### Describe the behavior you expected
Selected citations should not be erased from the 'selected citation keys' box when searching for additional ones in the citation selection window. This would especially be helpful when using large bibliographies.

I hope this is enough information to reproduce the problem. 

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-12-02 23:08
Thank you @LDSamson ! Yes, this is enough information. I can confirm this in RStudio Desktop 1.4.1071 on MacOS 11.1. It looks like it's working fine, though, when searching externally (PubMed, etc.). We'll review this as we continue development of RStudio.

**Comment by dragonstyle** [comment] 2021-03-06 18:50
Thanks for reporting this issue- the fix should be in tomorrow's daily build!

**Comment by ronblum** [comment] 2021-03-18 17:43
[Note above—it was only an issue with the current bibliography. Conducting a new search in external sources like PubMed or DataCite is no problem.]

Confirmed fixed in RStudio Desktop 1.4.1627 on MacOS 11.3 and RStudio Server 1.4.1620 on Ubuntu 20.04 using Chrome on MacOS 11.3.

**Closed** 2021-03-18 17:43 UTC
Labels: bug, visual markdown editing
