### ISSUE TITLE
RStudio displays Chinese when installing packages.

### ISSUE THREAD

**Issue by will-gt** [rstudio/rstudio#11577] opened 2022-07-08 00:40 UTC
### System details
    RStudio Edition : Desktop
    RStudio Version : 2022.02.3 Build 492
    OS Version      : Windows 10.
    R Version       : 4.2.1

### Steps to reproduce the problem
R displays English but RStudio displays Chinese when installing packages.

### Describe the problem in detail
I work in China but the language of my PC is English and the region was set in US.
When I installed packages, the information about installation was displayed in English in R 4.2.1, but in Chinese in Rstudio.

### Describe the behavior you expected
Rstudio displays English as installing a package.

<img width="469" alt="1234" src="https://user-images.githubusercontent.com/72987274/177893794-21bbaa46-1aa0-4d95-ac15-c78aa6c90f1e.png">
<img width="579" alt="123" src="https://user-images.githubusercontent.com/72987274/177893797-41bfbb6b-ea47-4544-8ded-041d6d02f799.png">

**Comment by ronblum** [comment] 2022-07-08 13:11
@zheng-ya Thank you for raising this! A couple of questions:
1) What do you get with `Sys.getlocale()`?
2) Did this work correctly in previous versions of R and RStudio?

**Comment by zheng-ya** [comment] 2022-07-09 03:31
@ronblum  Thank you for getting back to me. 

**1. Sys.getlocale() return** 

[1] "LC_COLLATE=English_United States.utf8;LC_CTYPE=English_United States.utf8;LC_MONETARY=English_United States.utf8;LC_NUMERIC=C;LC_TIME=English_United States.utf8"

**2. Did this work correctly in previous versions of R and RStudio?**

It works correctly in the newest RStudio Version (2022.02.3 Build 492) and R version 4.1.3. 

When I update R to 4.2.0 and upper version, this bug appears.

**Comment by ronblum** [comment] 2022-07-11 12:41
@zheng-ya Thank you for the information! I'm unable to reproduce—even if I change the region on Windows to Chinese (Simplified).

@timtmok and @jgutman do you have any suggestions of what might be going on, spec. in the change from 4.2.0 to 4.2.1? There are [some changes in 4.2.1](https://cran.r-project.org/doc/manuals/r-release/NEWS.pdf) related to UTF-8 and ASCII in 4.2.1, so perhaps one of those is causing the issue?

**Comment by timtmok** [comment] 2022-07-11 12:52
@zheng-ya It's likely due to you connecting to the Chinese CRAN mirror. The server is returning messages in its locale instead of the one you have set locally. You can further confirm this by running `chooseCRANmirror()` in the console and setting it to another country's mirror and running the package install again.

**Comment by zheng-ya** [comment] 2022-07-12 01:47
@timtmok @ronblum  Thank you for your patience. It seems this bug has nothing to do with CRAN mirror, but with RStudio, because the information on the installation of the package was displayed in English in R 4.2.1 and it was changed to Chinese when I use RStudio (R 4.2.1 loaded).  I also changed the mirror to US's mirror, but it did not work.

Please see the attached image.
<img width="866" alt="4343" src="https://user-images.githubusercontent.com/72987274/178390741-ce8e8d68-73c1-4f91-b3c4-44f5f0ffe864.png">

**Comment by timtmok** [comment] 2022-07-12 20:24
I don't know of what else that could be the cause. It might be something else that is checking the system's locale instead of using R's locale or who knows what. It is certainly difficult to reproduce but I bet we could do the reverse and change the system's region to something else and see if the package install change's language.

I'd set this as a lower priority since it's isolated to this use.

**Comment by zheng-ya** [comment] 2022-07-13 00:39
@timtmok Thank you Tim.

**Comment by kevinushey** [comment] 2022-07-14 19:28
My guess is that this issue would reproduce in other contexts, not just when installing packages. We'd need more information to know for sure, but we'd have a couple issues related to localization being handled different in RStudio compared to "vanilla" R. For example: https://github.com/rstudio/rstudio/issues/10308

**Comment by zheng-ya** [comment] 2022-07-15 13:58
@kevinushey  Yeap, this issue reproduces in many notifications or warnings of package installation and execution.  Hope it is fixed in the future.

**Comment by kevinushey** [comment] 2022-07-15 17:20
@zheng-ya for posterity, can you please share a couple other examples?

**Comment by elvisjade** [comment] 2022-08-04 08:03
I have the same problem, the error message in console is in Chinese, but I want it to be in English

**Comment by weiningai** [comment] 2022-09-09 02:17
I updated my R today and this problem occurred to me, too. I resolved this issue by following this part "How do I change the console language in R?" from the following link. It worked for me. Note that you need to authorize you as a user to modify the Rconsole file.
https://www.theburningofrome.com/advices/how-do-i-change-my-r-language-to-english/

**Comment by zheng-ya** [comment] 2022-11-24 06:37
@weiningai Apologize for my delay in replying. It's been a busy winter. I just tried the solution and it WORKS!!!  This problem has bothered me for too long and finally be done. Thank you very much for your kind sharing!! 谢谢老铁！ 你的英文真好嘿嘿

**Closed** 2022-12-16 05:26 UTC
Labels: bug, locale
