### ISSUE TITLE
Columns get misaligned with header in viewer with sf files

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#3670] opened 2018-10-14 14:12 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1053
    OS Version      : Windows 10 Pro
    R Version       : 3.5.1

### Steps to reproduce the problem
- Read a sf file
- View the sf file with `View(sf_file)`

### Describe the problem in detail
Columns get misaligned with their respective headers

![image](https://user-images.githubusercontent.com/14981085/46917829-d6c0cd00-cf90-11e8-8bbc-735e8c2604e8.png)

### Describe the behavior you expected
I expect to see columns aligned with their headers.

![image](https://user-images.githubusercontent.com/14981085/46917855-0bcd1f80-cf91-11e8-9c36-2b3208fec6bc.png)

**Comment by ronblum** [comment] 2018-10-15 14:07
@andresrcs Can you provide a sample data set and code snippet so we can try to reproduce the issue? Thanks!

**Comment by andresrcs** [comment] 2018-10-15 14:52
Ok, this is the sample data [sf_file.zip](https://github.com/rstudio/rstudio/files/2479236/sf_file.zip)

```
map <- readRDS("sf_file.rds")
View(map)
```

**Comment by ronblum** [comment] 2018-10-16 16:01
Thanks @andresrcs! I reproduced this on MacOS Mojave 10.14.1. I'll tag it as a reproducible bug.

**Comment by ateucher** [comment] 2018-10-16 17:05
There was an issue raised a while ago about not needing to show the geometry column when `View()`ing `sf` objects, which is probably relevant here: https://github.com/rstudio/rstudio/issues/2039

**Comment by kevinushey** [comment] 2018-10-16 18:29
Standalone reprex:

```R
set.seed(123)
n <- 200
k <- 2
column <- list(list(matrix(rnorm(n * k), nrow = n, ncol = k)))
df <- tibble::data_frame(x = 1, y = column)
View(df)
```

Basically, if one of the columns is too large, it breaks the alignment between headers and columns. The main thing I notice is that the column hosting the row names seems to be too small, and that throws out alignment for the rest of the columns

**Comment by kevinushey** [comment] 2018-10-16 18:57
Given that this only occurs in very rare cases (overly large list columns) I'm inclined to punt out of v1.2. @jmcphers what do you think?

**Comment by kevinushey** [comment] 2018-11-02 21:48
@adamconroy IIUC this might be fixed as part of the work you're doing for https://github.com/rstudio/rstudio/issues/1771; is that correct?

**Comment by jmcphers** [comment] 2018-12-14 22:19
I can repro in 1.2.1156, but not in 1.2.1194 (desktop or server). I think this one's been fixed by @adamconroy's recent changes. @ronblum @andresrcs feel free to reopen if you're still seeing issues!

**Closed by jmcphers** 2018-12-14 22:19 UTC
Labels: bug, regression, reproducible
