### ISSUE TITLE
Rstudio desktop free preview 1.2.1329 - can't select text in editor window

### ISSUE THREAD

**Issue by rgayler** [rstudio/rstudio#4488] opened 2019-03-20 23:18 UTC
I just upgraded from 1.2.1327 to 1.2.1329 and can no longer select text in (at least) the editor window. Click-drag does not select text. Double-click does not select text. Editing is almost unusable.

The behaviour survived a restart of Rstudio and a reboot of the computer. Other programs were fine.

I reverted to 1.2.1327 and the problem disappeared.

I am running the Ubuntu 18+ versions of Rstudio.

My computer is running Ubuntu 18.04 4-bit.

**Comment by gtritchie** [comment] 2019-03-21 00:05
I just installed 1.2.1329 (Bionic) on a clean install of Bionic + r_base, and am able to select text in the editor via click-drag, double-click, and so on.

So something else is going on here.

**Comment by rgayler** [comment] 2019-03-21 00:17
Any suggestions what I might try to do to investigate this? (Although I am
mid-project and behind-deadline at the moment, so ...)

**Comment by gtritchie** [comment] 2019-03-21 03:31
I recommend posting what you've encountered on the community page and see if anybody else reports the same. That might give us more data to work with in understanding what you are experiencing. https://community.rstudio.com/c/rstudio-ide

**Comment by rgayler** [comment] 2019-03-21 03:33
Thanks. Will do.

**Comment by rgayler** [comment] 2019-03-21 11:15
I have just reproduced the problem on a different computer running Ubuntu 18.04. The two computers showing the same problem are not identically configured, but I do generally install the same things on both - so there may be something relatively uncommon that I am doing on both that interacts with whatever changed between 1.2.1327 and 1.2.1329

**Comment by gtritchie** [comment] 2019-03-21 16:12
Which keybinding are you using for the editor? E.g. Default, Vim, Emacs, Sublime Text.

Does this problem only happen in the editor pane? How about the Console?

Reproduce the problem again, then `Help / Diagnostics / Write Diagnostics Report` and attach the generated file to this issue. Review it first to make sure there isn't anything in there you need to redact for privacy reasons.

Here's a brief example of what I'm trying:
![2019-03-21_09-08-42 (1)](https://user-images.githubusercontent.com/10569626/54766837-4038ad80-4bb9-11e9-9fc7-7c3a05248c91.gif)

**Comment by gtritchie** [comment] 2019-03-21 16:40
There were 3 changes made between 1.2.1327 and 1.2.1329.

Two of them are related to using themes. What theme do you have selected in Tools / Global Options / Appearance? I've got the default selected (Textmate). If you've got a different one, does the problem still happen if you switch back to Textmate?

The other change would prevent saving a file if you did `options(repos = NULL)` then tried to save a file, so seems quite unlikely it is a factor.

**Comment by gtritchie** [comment] 2019-03-21 16:46
FYI, I also tried installing 1.2.1327, using it a bit, then uninstalling it and installing 1.2.1329 and it still worked (selection-wise).

**Comment by jjallaire** [comment] 2019-03-25 14:58
I think I am seeing the same thing. 

I updated to the preview yesterday (from either 1.2.1300 or 1.2.1320, not sure which I was running) and now find my IDE in a state where no syntax highlighting works and text selections are impossible! Here's a video:

![noselection](https://user-images.githubusercontent.com/104391/54929976-d1c35a80-4eec-11e9-9f5e-004e5dcb1ab4.gif)

The only thing I see in the JS console is this:

<img width="822" alt="Screen Shot 2019-03-23 at 11 09 27 AM" src="https://user-images.githubusercontent.com/104391/54929749-72fde100-4eec-11e9-95a0-dcfafd99273c.png">

Interestingly, if I switch to another theme (I tried "Solarized Dark") then everything works fine. If I think explicitly switch back to TextMate, everything works fine (and there is no error in the JS console when I do a reload). 

So something to do with having no theme explicitly set in preferences? Maybe this commit from 8 days ago: https://github.com/rstudio/rstudio/commit/8c9a28ed4989b7ec8e835fa47dd7e59b99f15ffd

**Comment by kevinushey** [comment] 2019-03-25 15:54
I see a similar query for the theme that works fine:

<img width="522" alt="Screen Shot 2019-03-25 at 8 54 27 AM" src="https://user-images.githubusercontent.com/1976582/54934365-9f5d3180-4edb-11e9-8363-6ec8f7970a8a.png">


although curious is that your case has the double-slash in the URL.

**Comment by kevinushey** [comment] 2019-03-25 16:18
It might be related to this older commit: https://github.com/rstudio/rstudio/commit/eafd6b78ab14c7de8c3b4d358bda8ac6beadd3e3#diff-ecbf3c3e6509a5a8a5a76289bbd60514

It looks like we previously expected / used leading slashes in the theme URLs, and have since removed them. However, I suspect the saved URLs might still contain these leading slashes, and so when these old themes get used the issue comes up.

@rgayler, can you confirm whether changing the editor theme fixes the issue for you?

**Comment by gtritchie** [comment] 2019-03-25 16:23
I see a slightly different failure; no double-slash, but there's an extra "ace" in the path. This is thrown when the Options dialog tries to load the theme preview (and is on 1.3 dev build, so that might be a factor).

![2019-03-25_09-21-40](https://user-images.githubusercontent.com/10569626/54936365-91a9ab00-4edf-11e9-95fa-1137a57d68ca.png)

**Comment by kevinushey** [comment] 2019-03-25 16:48
That's almost surely a v1.3-ism. Ace has some code that tries to auto-load the textmate theme on startup that took some work to cauterize in v1.2; I expect we'll need the same in v1.3.

**Comment by gtritchie** [comment] 2019-03-25 16:50
Yes, I've only been able to repro with 1.3. Opening a separate issue to track that one.

**Comment by jmcphers** [comment] 2019-03-25 17:04
>  However, I suspect the saved URLs might still contain these leading slashes, and so when these old themes get used the issue comes up.

That's very possible. I was able to reproduce @jjallaire's issue by hand-modifying my `user-settings` to introduce a leading `/` in the theme name.

**Comment by kevinushey** [comment] 2019-03-25 17:09
I've got the following repro steps:

1. Clean out `~/.rstudio-desktop`;
1. Install RStudio v1.2.900, and change the theme (so that theme settings get persisted);
1. Install the latest preview, and observe no theming in the IDE.

The issue does indeed resolve after changing the theme a second time.

On our side, I think the simplest fix is to just trim out a potential leading slash here:

https://github.com/rstudio/rstudio/blob/eb68de9642a45e0aca110e1702ef4f4cfd9c6941/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceTheme.java#L60-L63

**Comment by jmcphers** [comment] 2019-03-25 17:11
I was also able to repro this by hand-editing the `~/.rstudio-desktop/monitored/user-settings/user-settings` file directly. 

@MariaSemple, what do you think about making a change here for 1.2?

**Comment by jmcphers** [comment] 2019-03-27 22:36
Should be fixed by #4506 (note: merged to patch branch so not yet part of a public build)

**Closed by jmcphers** 2019-03-27 22:36 UTC
Labels: themes

**Comment by rgayler** [comment] 2019-03-27 23:48
My apologies for not responding earlier - I have been unavailable all week

**Comment by ronblum** [comment] 2019-06-07 15:29
Verified in RStudio Desktop 1.2.1539 on MacOS 10.14.6 and Ubuntu 18.04.2.
