### ISSUE TITLE
Scrollbars not visible

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#2251] opened 2018-02-21 22:19 UTC
On my Mac, I don't see any scrollbars in the editor, console, file browser, etc.

![image](https://user-images.githubusercontent.com/86978/36508540-9a1f9f24-1722-11e8-931d-246c037250d0.png)

Not sure if it's relevant, but my computer is configured to always display scroll bars, under System Preferences -> General.

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.358
    OS Version      : macOS 10.13.2 (17C205)
    R Version       : 3.4.3

**Comment by kevinushey** [comment] 2018-02-21 22:28
Duplicate of https://github.com/rstudio/rstudio/issues/1953.

In the daily builds, we have scrollbars disabled entirely because that was better than the alternative (sticky scrollbars showing up everywhere) but the situation is definitely not ideal!

**Closed by kevinushey** 2018-02-21 22:28 UTC

**Comment by vkozloff** [comment] 2019-07-11 18:36
Is there any chance this could be fixed in a later version? I'm having a lot of trouble scrolling through large data sets when I use the View() function

**Comment by GillinTokyo** [comment] 2021-08-11 09:32
RStudio Edition : Desktop and Cloud
RStudio Version : Version 1.4.1717
OS Version      : macOS Big Sur
Missing scrollbars
Hello, just wondering if anyone ever came up with a fix for this?

**Comment by DRG01** [comment] 2023-11-17 08:26
I notice that the implication is that this is happening on Macs. But it is still happening on Windows based machines in 2023.
