### ISSUE TITLE
Selecting a dark editor theme does not switch GUI elements to dark mode and displays some illegible text

### ISSUE THREAD

**Issue by ptschanz** [rstudio/rstudio#11176] opened 2022-05-11 07:25 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.02.2 Build 485
    OS Version      :  Windows 11
    R Version       :  4.2.0

### Steps to reproduce the problem
1. Fresh installation of Windows 11
2. Applying all Windows updates
3. Installation of R 4.2.0
4. Installation of R Studio 2022.02.2 Build 485
5. Selecting a dark editor theme, such as "Idle Fingers"

### Describe the problem in detail
After a fresh installation of Windows 11 and the newest R Studio version, I can only switch to a dark editor theme, but the GUI elements stay in the light theme. Also, the text in the "Files" pane can hardly be read.

![image](https://user-images.githubusercontent.com/28808801/167791191-8b98adf1-824d-4694-b202-bd957473152e.png)

I tried reinstalling several times, but it didn't help.

### Describe the behavior you expected
The GUI elements should also switch to dark mode, like this:
![image](https://user-images.githubusercontent.com/28808801/167792094-4cfa1d7e-17fd-42cf-8c68-d4f34df1e7e8.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by werkstattcodes** [comment] 2022-05-11 09:42
Just to add that I am experience the same issue on windows 10. I had filed a post on rstudio's community page [here](https://community.rstudio.com/t/rstudio-2022-02-2-485-issue-with-appearance/136576).

**Comment by kevinushey** [comment] 2022-05-11 18:05
Does changing the RStudio theme: in Tools -> Global Options... -> Appearance make a difference? (E.g. try changing it to "Sky" and back to "Modern")

<img width="607" alt="Screen Shot 2022-05-11 at 11 04 29 AM" src="https://user-images.githubusercontent.com/1976582/167916627-772edf20-afa7-4de3-81cc-4a5a67f84efa.png">

Or, does switching to a light theme and then later back to a dark theme make a difference? (Or, do you see some "dark" themes work as expected, while others do not?)

**Comment by ptschanz** [comment] 2022-05-11 20:10
Changing between "Modern" and "Sky" or between light and dark themes does not solve the problem. It seems that all the light themes are displayed correctly, but all the dark themes not. It's not just that the GUI does not switch to dark mode, but also the pane that displays "Files", "Help", etc shows text really strange. For example the blue hyperlinks (see picture above), but also in the help function (see below). No problem with the light themes.

![image](https://user-images.githubusercontent.com/28808801/167937632-6176a099-66f0-432e-be56-b3d01921bb07.png)

**Comment by heteyszabolcs** [comment] 2022-05-13 09:36
I experience exactly the same. Temporary solution is that you right click on file names, select Inspect element, and then you set a different color for the filenames. Although, if you re-enter RStudio the issue is still not solved.

**Comment by heteyszabolcs** [comment] 2022-05-13 09:37
I experience exactly the same. Temporary solution is that you right click on file names, select Inspect element, and then you set a different color for the filenames. Although, if you re-enter RStudio the issue is still not solved.

**Comment by ptschanz** [comment] 2022-05-13 15:27
I just found out a "hack" that solves the problem, and which might help developers to understand the bug. It seems that what you do in a previous installation of R Studio (even after de-installation) affects what happens in a new installation of R Studio.

Here are the steps that I can reproduce to fix the problem:

1. Uninstall R Studio 2022.02.2 Build 485
2. Install R Studio 2021.09.0 Build 351
3. Select a dark theme (I used "Idle Finger") -> now the GUI elements are displayed correctly, but still some problems in the pane ("Files" ok, not with illegible hyperlinks, but the  "Help" pane shows blurry text in the function description)
4. Uninstall R Studio 2021.09.0 Build 351
5. Install R Studio 2022.02.2 Build 485

Now everything looks the way it should. But as soon as you try to switch back and forth between themes, the dark theme is corrupted again!

I hope this helps the developers to understand the cause of the problem and others to temporarily fix the issue.

**Comment by kevinushey** [comment] 2022-05-13 18:59
Marking for triage since it looks like this is a bug that would affect anyone updating from PT to SW after release.

**Comment by mluerig** [comment] 2022-05-16 14:00
I have the same issue on a freshly installed windows 10, no previous installations of Rstudio on the machine: https://community.rstudio.com/t/dark-themes-are-not-being-fully-applied-in-rstudio/136977/2

**Comment by mluerig** [comment] 2022-05-16 14:18
as suggested above, I tried to install older versions (after removing the user data folders for Rstudio), but I keep getthing this: 
![image](https://user-images.githubusercontent.com/15648068/168613770-7199dbba-0b4b-4d94-a4ee-fb59b9faa54b.png)

**Comment by ptschanz** [comment] 2022-05-16 15:58
I had this too when trying with a version older than 2021.09.0 Build 351 but it worked with  2021.09.0 Build 351 in my case.

**Comment by kevinushey** [comment] 2022-05-16 22:19
I still haven't been able to reproduce this locally.

If you're still having trouble, can you please share the output of:

```
.rs.api.getThemeInfo()
```

while you have a dark theme active? It's possible that RStudio is incorrectly inferring that a "dark" theme is actually a "light" theme.

**Comment by kevinushey** [comment] 2022-05-16 22:28
I'd also be curious to know whether usage of `rsthemes` is a common ground -- e.g. has everyone experiencing this issue used `rsthemes` in the past?

**Comment by kevinushey** [comment] 2022-05-16 22:48
Finally, if you right click somewhere in the IDE surface and click Inspect Element in the context menu, you should be able to view the DOM used by RStudio.

![image](https://user-images.githubusercontent.com/1976582/168694647-afacf18f-5eac-4adf-aa1e-e06dbd0c41d7.png)


Do you see the "rstudio-themes-dark-menus" class applied on the body element? Or, the "rstudio-themes-dark" class applied to the associated div (see highlight in picture)?

**Comment by werkstattcodes** [comment] 2022-05-17 07:17
> 
Can't answer for the OP, but in my case, when using the "Express" theme (a dark theme which comes with RStudio), I have the following DOM:
![image](https://user-images.githubusercontent.com/9595585/168751898-90217b22-2d33-4c8d-9f12-5054d32b8928.png)

**Comment by kevinushey** [comment] 2022-05-17 16:33
@werkstattcodes, thank you! Your output in https://github.com/gadenbuie/rsthemes/issues/86#issuecomment-1128508501 also confirms that RStudio is incorrectly concluding the theme is a light theme (ie: not dark).

Do you see the same behavior for RStudio's built-in dark themes?

Could you also share a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report)?

Do you know if the installed theme file has a comment header with the contents:

```
/* rs-theme-is-dark: TRUE */
```

(this is what RStudio reads to infer if a theme is dark)

Finally, does resetting RStudio's state make a difference? See https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State for more details. In particular, you need to rename (or remove) the folder located at:

```
C:\Users\<username>\AppData\Local\RStudio
```

**Comment by ptschanz** [comment] 2022-05-18 06:33
Below the requested output before and after working correctly and the diagnostic report. I have never used `rsthemes`

### Output before it "breaks"
This is the output when R Studio is correctly displaying a built-in dark theme (using the above hack).

`.rs.api.getThemeInfo()`

```
$editor
[1] "Idle Fingers"

$global
[1] "Modern"

$dark
[1] TRUE

$foreground
[1] "rgb(255, 255, 255)"

$background
[1] "rgb(50, 50, 50)"
```
![image](https://user-images.githubusercontent.com/28808801/168970402-c2e035ee-dc41-4aa6-8418-32b6e5e61048.png)

### Output after it "breaks"
This is the output after I switch to another theme and than back to the same theme as above:

`.rs.api.getThemeInfo()`

```
$editor
[1] "Idle Fingers"

$global
[1] "Modern"

$dark
[1] FALSE

$foreground
[1] "rgb(255, 255, 255)"

$background
[1] "rgb(50, 50, 50)"
```
![image](https://user-images.githubusercontent.com/28808801/168972675-aeea2b68-1044-482c-ac36-50c440bf8933.png)


[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/8713741/diagnostics-report.txt)

**Comment by kevinushey** [comment] 2022-05-18 06:42
Thanks! There are a lot of errors in the logs of the form:

> WARNING rs-theme-is-dark value is not a valid boolean string  for theme "Monokai" (C:/Program Files/RStudio/resources/themes/monokai.rstheme);

Can you please share the contents of that file? Also, do you recall ever intentionally modifying the installed theme files, or anything like that?

**Comment by ptschanz** [comment] 2022-05-18 06:51
I did a fresh installation of Windows 11 (formating all drives) and then installed R Studio. The first thing I did was to change the theme and then the problem already happened. I am also dual booting with Linux Mint where it works fine.

Here the file:

[monokai.zip](https://github.com/rstudio/rstudio/files/8713840/monokai.zip)

**Comment by kevinushey** [comment] 2022-05-18 07:19
Thanks. I have some idea as to what the problem could be and will take a look tomorrow.

**Comment by kevinushey** [comment] 2022-05-24 21:37
@ptschanz, we have a candidate fix for this coming in the next daily builds. If you have time, would you be able to test the next builds available at https://dailies.rstudio.com/? (Please wait until build 442 is available.)

Thanks!

**Comment by ptschanz** [comment] 2022-05-25 19:08
@kevinushey thanks for your quick reponse and fix to the raised issue!

After installation of build 442, the theme is first display incorrectly (the same as before), but after switching themes at least once, everything is displayed correctly (GUI panels dark, no dark blue hyperlinks anymore, no blurry text in help pane). I can now switch back and forth between times and all is perfect!

**Comment by kevinushey** [comment] 2022-05-25 19:16
@ptschanz That's great news; thank you for taking the time to test and report back!

**Closed by kevinushey** 2022-05-25 19:16 UTC
Labels: bug, themes, test

**Comment by sternenklar** [comment] 2022-07-14 16:47
I have the same issue on a newly installed Windows 10 system. Changing between themes doesn't solve it.

**Comment by tucker-furniss** [comment] 2022-12-16 19:58
I am still having this issue with the most recent official release, RStudio 2022.12.0 (build 353), installed on Windows 10. The theme is applied everywhere except the menu bar, which is still white. Is this just me or is this a common problem?

**Comment by ronblum** [comment] 2022-12-16 22:11
@tucker-furniss Does issue #12247 describe what you're seeing?

**Comment by tucker-furniss** [comment] 2022-12-16 22:47
Yes, I believe so. Although on my system the menu bar stays light whether my Windows theme is light or dark (it is normally set to dark). 
![image](https://user-images.githubusercontent.com/81191951/208201277-481ab66c-f9b1-459b-8a49-2ae6760d0136.png)

**Comment by tucker-furniss** [comment] 2022-12-19 21:24
If it is any help, version 2022.02.1 Build 461 does not have the issue. I've reverted back to that version for now. 
There also seems to be a bug in the newest stable release (2022.12.0) that causes a small white dot or checkbox square to appear on the screen. Sometimes it disappears when clicked, other times it persists until RStudio is restarted. Probably an unrelated issue, but I can't find much about it on the web other than two expired posts on the Posit Community website ([post 1](https://community.rstudio.com/t/small-white-rectangle-appearing-on-upper-left-side-of-rstudio-what-the-heck/145072), [post 2](https://community.rstudio.com/t/rstudio-windows-and-mac-bug-little-square/148064)).
