### ISSUE TITLE
RStudio fails to launch on Big Sur 11.2.2

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#9072] opened 2021-03-08 15:45 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1603-1 (Pro) and 1.4.1620 (Open Source)
    OS Version      : MacOS 11.2.2 (20D80)
    R Version       : 3.6.3, 4.0.2, 4.0.4

### Steps to reproduce the problem

Opening RStudio Pro fails to launch with "Error Starting R" messaage.

![image](https://user-images.githubusercontent.com/5420529/110343273-56381680-7ffa-11eb-9848-2b5ae1488e16.png)

```
08 Mar 2021 15:35:57 [rsession-garrick] ERROR generic error 8 (Exec format error) [r-home: /Library/Frameworks/R.framework/Resources, r-archs: , rsession-archs: ]; OCCURRED AT rstudio::core::Error rstudio::r::session::(anonymous namespace)::validateCompatible(const std::string &) src/cpp/r/session/RSession.cpp:270; LOGGED FROM: int main(int, char *const *) src/cpp/session/SessionMain.cpp:2200
08 Mar 2021 15:40:40 [rsession-garrick] ERROR generic error 8 (Exec format error) [r-home: /Library/Frameworks/R.framework/Resources, r-archs: , rsession-archs: ]; OCCURRED AT rstudio::core::Error rstudio::r::session::(anonymous namespace)::validateCompatible(const std::string &) src/cpp/r/session/RSession.cpp:270; LOGGED FROM: int main(int, char *const *) src/cpp/session/SessionMain.cpp:2200
08 Mar 2021 15:43:02 [rsession-garrick] ERROR generic error 8 (Exec format error) [r-home: /Library/Frameworks/R.framework/Resources, r-archs: , rsession-archs: ]; OCCURRED AT rstudio::core::Error rstudio::r::session::(anonymous namespace)::validateCompatible(const std::string &) src/cpp/r/session/RSession.cpp:270; LOGGED FROM: int main(int, char *const *) src/cpp/session/SessionMain.cpp:2200
```

### Describe the problem in detail

I just updated Big Sur to 11.2.2 (from a previous version of Big Sur). RStudio Desktop Pro 1.4.1603-1606 all fail to launch. The earliest failing version is 1.4.1603-1 (`b843b8d65fd6e6f3821c0dadbf63aeab-19`). The latest version of RStudio Desktop Pro that works for me is 1.4.1598-2 (build id `859cdc242160a8f6298aa11e96644e01-19`).

I also checked the latest Open Source version an 1.4.1620 fails with the same message. I didn't work through past versions, though.

I tried creating a diagnostics report but because RStudio fails to launch, the report is not created.

I reinstalled both R 3.6.3 and R 4.0.4, but I see the same issue with both versions.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report). (Not possible.)
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-03-08 16:05
@gadenbuie Does the currently released version, 1.4.1106-5, work?

**Comment by ronblum** [comment] 2021-03-08 17:27
Update: reproduced with RStudio Desktop 1.4.1620 on MacOS 11.2.2, works on MacOS 11.2.1 and 11.3 beta. RStudio Desktop 1.4.1106 works fine.

**Comment by jmcphers** [comment] 2021-03-08 17:35
Also reported on the community forum: https://community.rstudio.com/t/update-on-r-rstudio-support-for-apple-silicon-macs/95582/10

**Comment by gregleleu** [comment] 2021-03-08 20:15
I had the same problem with version 1.6.1620 on Big Sur 11.2.2, but **it went away on 11.2.3** (also updated command line tools, which for some reason had broken version control in Rstudio, could be related)

**Comment by kevinushey** [comment] 2021-03-09 02:52
@gadenbuie do you still see this with 11.2.3?

**Comment by valerie-rstudio** [comment] 2021-03-09 05:10
Confirmed that after updating to Mac OS 11.2.3 and updating command line tools `xcode-select --install`, RStudio 1.4.1620 now launches.

**Comment by kevinushey** [comment] 2021-03-09 06:16
I think this might be due to the way we use `lipo` here:

https://github.com/rstudio/rstudio/blob/c9e657d4ec627de12757ac1df903f305e906daeb/src/cpp/core/system/Architecture.cpp#L33

`lipo` is likely only available if the user has command line tools installed, so we should probably switch to a method that doesn't rely on those tools being available.

**Comment by kevinushey** [comment] 2021-03-10 02:45
To be safe, testing should be done with both Xcode and CLT uninstalled.

**Comment by astayleraz** [comment] 2021-03-24 22:31
I verified in Version 1.4.1646 mac 11.2.3 and CLT and xcode uninstalled, I was able to open rstudio. Closing issue.

**Closed by astayleraz** 2021-03-24 22:31 UTC
Labels: bug, macos, reproducible, test
