### ISSUE TITLE
Prefer .Rproj name, if specified, over working directory in UI

### ISSUE THREAD

**Issue by fh-mthomson** [rstudio/rstudio#15501] opened 2024-12-09 23:29 UTC
### System details

    RStudio Edition : Server
    RStudio Version : Posit Workbench 2024.09.0+375.pro3, “Cranberry Hibiscus” (341a7627)
    OS Version      :  Linux (ubuntu2204)
    R Version       :  4.1.3 (but any)

### Steps to reproduce the problem

In **Workbench**:

1. Create two `.Rproj` files in different directories, named as `<folder>__<subfolder>.Rproj`:
```
➜  demo_projects tree
.
├── 1_this_project_not_the_other
│   └── this_part
│       └── 1_this_project_not_the_other__this_part.Rproj
└── 2_this_project_not_the_other
    └── this_part
        └── 2_this_project_not_the_other__this_part.Rproj
```
2. Open each `.Rproj` in a new Workbench Session
3. Go to the Home screen:

Unable to know which is which (either Sessions or Projects):
![Image](https://github.com/user-attachments/assets/35da41a6-315f-4a4c-b237-d8a108ed6c5a)

Unless you click on `Info` to see the detailed Working Dir:

![Image](https://github.com/user-attachments/assets/b9abc0cf-d380-4a2b-a1c4-b2e4f93ce586)

![Image](https://github.com/user-attachments/assets/de183074-41e3-4927-ad21-3f4f667f7cfb)
 
### Describe the problem in detail

From the [release notes of 2024.04.0](https://docs.posit.co/ide/news/#rstudio-2024.04.0):
> The working directory of a background job now defaults to the .Rproj location when a project is open. (#12600)

However, this gets confusing when the immediate working directory (e.g., `this_part`) is consistent across multiple projects, especially if the "unique" part of the folder path is at the beginning of the string, which gets truncated in the Workbench UI.

Per the screenshot above, both are "named" `this_part` (the folder name), despite the `.Rproj` name being more detailed (e.g., `2_this_project_not_the_other__this_part.Rproj`).

### Describe the behavior you expected

Each project appears by their `.Rproj` name:
1. `1_this_project_not_the_other__this_part`
2. `2_this_project_not_the_other__this_part`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by fh-mthomson** [comment] 2024-12-09 23:49
Adding that this is not a theoretical / academic example:

- we leverage a template generation workflow that commits N template files for a given `{project, project_type}` at `repo/<project>/<project_type>/<project>__<project_type>.Rproj`
- So, not being able to switch between / restore recent projects from the Home page means users typically need to: Create a new session (no project) -> Find .Rproj in RStudio UI (open project or find in Files pane) -> Launch a new session 
- The impact is amplified by using Workbench w/ the k8s Launcher, since opening the wrong session has a non-trivial cost (start pod with wrong RStudio project, close/terminate it, start new pod with correct RStudio project)

**Comment by gtritchie** [comment] 2024-12-10 21:42
This is a duplicate of https://github.com/rstudio/rstudio/issues/1909.

In the 2024.04 release, we added the custom project name feature to help with these scenarios.

In Project Options, you can provide a different name, and it will be shown in the UI instead of using the folder name.

![screenshot of project options showing custom name feature](https://github.com/user-attachments/assets/845cc693-f17c-4ba6-936d-9998a3888203)

GIve this a try and see if it improves the situation!

**Comment by gtritchie** [comment] 2024-12-10 21:43
Closing as a duplicate of #1909. If you don't agree that it's a duplicate let me know and I'll reopen for further discussion.

**Closed by gtritchie** 2024-12-10 21:43 UTC
Labels: enhancement, duplicate, projects

**Comment by fh-mthomson** [comment] 2024-12-10 21:49
thank you for sharing that! 

I think it's _slightly_ different where we'd like `folder_name/project_name.Rproj` to _automatically_ show `project_name`, rather than an _option_ I can configure to show `project_name` instead of `folder_name`.

I, perhaps incorrectly, had assumed that if the user manually specifies the name of the relevant `.Rproj` file, it's a signal to the RStudio IDE that should be displayed as the project name.

**Comment by gtritchie** [comment] 2024-12-10 21:57
Historically, there have been issues with having the name of the `.Rproj` file differ from the name of the containing folder, so renaming the `.Rproj` was not recommended.

I don't know offhand if that's still the case, and the problems may only be relevant on RStudio Desktop, not Server.

Looking closer, even with the custom name feature, the list of active sessions is still confusing in your scenario.

For example, here I've got a session running with the project "My Fancy Name", but the custom name is only shown in the Projects area, not the active sessions area:

![Image](https://github.com/user-attachments/assets/91b62e36-6f65-4e45-a42b-9275dba7bbc2)

**Comment by fh-mthomson** [comment] 2024-12-10 22:53
Thank you! 
> Historically, there have been issues with having the name of the .Rproj file differ from the name of the containing folder, so renaming the .Rproj was not recommended. I don't know offhand if that's still the case, and the problems may only be relevant on RStudio Desktop, not Server.

If it's helpful, we've definitely had folks leveraging `folder_name` ≠ `project_name.Rproj` on both Mac and Workbench before all folks moved over to the latter, so fortunately seems to be reasonably well supported in recent times :) 

I think I'd still suggest that the name `display_name = coalesce(custom_name, project_name, folder_name)` be the default descriptive project in the RStudio IDE, rather than only `display_name = coalesce(custom_name, folder_name)`

Example (top right only shows the less descriptive `folder_name`), when you open the project for the first time: 

![Image](https://github.com/user-attachments/assets/e8f44925-1b0a-4b70-9fb7-036815d3bf23)

Fortunately, the UI _does_ a nice job of disambiguating once you've opened the same `folder_name` across multiple projects:
![Image](https://github.com/user-attachments/assets/71ae4385-e55a-4690-8fee-9819e0b7715d)

**Comment by gtritchie** [comment] 2024-12-10 23:06
> If it's helpful, we've definitely had folks leveraging folder_name ≠ project_name.Rproj on both Mac and Workbench before all folks moved over to the latter, so fortunately seems to be reasonably well supported in recent times :)

Yes, I asked around and the consensus was that it should be fine. If there were problems, it was a long time ago, and you're not the only ones who change the project-file name to be different than the folder name.

I'll add your suggestions on display_name scheme leveraging the project-file name to the rstudio-pro issue.
