### ISSUE TITLE
Visual markdown mode does not always recognize correct line when running code with Ctrl-Enter

### ISSUE THREAD

**Issue by skranz** [rstudio/rstudio#7946] opened 2020-10-02 12:15 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.894
    OS Version      :  Windows 10
    R Version       :  4.0.2

### Steps to reproduce the problem

Unfortunately, the bug only seems to occur rarely, and I have not yet found the steps to reproduce it.

### Describe the problem in detail

I was working on a Markdown file in visual modus and after some while running a line in an R chunk with Ctrl-Enter (or `Run Selected Lines`) did not any more detect the correct line. See the image:

![rstudio_bug](https://user-images.githubusercontent.com/1413022/94921166-0471ea00-04b8-11eb-99ce-58b0031352e5.PNG)

I had selected the line `dat = readRDS("sem.Rds")` and pressed Ctrl-Enter. But RStudio seemingly send the lines in the markdown text below to the R console, i.e.

```
b) In dat We have one observation for each combination of date 
```
When this error happened for one chunk, it happened for all chunks. After restarting RStudio everything worked again as expected. I was working quite a while before the error occured. Unfortunately, I could not replicate any particular step that led to this problem.

### Describe the behavior you expected

The correct line should be passed to the R console

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-10-02 14:35
@skranz Thank you for raising the issue! I tried this a bunch of times, but could not reproduce the issue. However, as reported, the problem is intermittent. I'll mark it as an issue to review as we continue development of the feature.

**Comment by mikebessuille** [comment] 2020-10-05 17:25
Several engineers have tried reproducing internally and have not yet been successful.  Moving this out of 1.4 until we have a more consistent reproduction scenario.

**Comment by jmcphers** [comment] 2020-10-14 15:48
Also reported by @hadley:
![image](https://user-images.githubusercontent.com/470418/96013329-fac27d80-0df9-11eb-9a89-b5f7d785fc61.png)

**Comment by jmcphers** [comment] 2020-10-14 15:53
Moved back to 1.4 since we now have > 1 user reporting this issue.

**Comment by skranz** [comment] 2020-10-17 07:54
I have found an example that consistently generates the bug on my computer with the newest RStudio daily build.

## System
RStudio Edition : Desktop
RStudio Version : 1.4.949
OS Version      :  Windows 10
R Version       :  4.0.2

## Steps to reproduce the problem
Open the Rmd file in the attached ZIP first in source mode. Then change to visual mode (but don't save) and run the line `1+1` in the 2nd chunk via Ctrl-Enter. This consistently generates the bug, i.e. the wrong line is passed to the R console.

[test.zip](https://github.com/rstudio/rstudio/files/5395165/test.zip)

**Comment by kevinushey** [comment] 2020-10-19 17:52
Thanks! Here's a slightly more distilled reproducible example:

`````
doc <- "
Hello, world!

```{r}
1 + 1
```
"

file <- tempfile("visual-mode-", fileext = ".Rmd")
writeLines(doc, con = file)
file.edit(file)
`````

Run that code, switch the opened `.Rmd` file into visual mode, and then try to run the first chunk. In my case, nothing runs at all. I also see an assert firing here:

<img width="1920" alt="Screen Shot 2020-10-19 at 10 52 29 AM" src="https://user-images.githubusercontent.com/1976582/96492928-30e86e80-11f9-11eb-80f8-b580d557b7f2.png">

**Comment by jmcphers** [comment] 2020-10-19 21:41
@kevinushey I can't repro with those steps. :-/ Are you on master?

![image](https://user-images.githubusercontent.com/470418/96514833-1aeaa600-1219-11eb-9709-4e243e9b4724.png)

**Comment by kevinushey** [comment] 2020-10-19 22:05
Yep, I'm seeing this on master (with a local desktop development build). Let me know if a quick screenshare would be helpful.

**Comment by kevinushey** [comment] 2020-10-19 22:10
The behavior I see with the most recent daily is different, but still "wrong" in a strange way. The right line is selected for execution, unless the cursor is at the end of the last line in the chunk. In that case, RStudio tries to submit the chunk header to the console.

**Comment by jmcphers** [comment] 2020-10-21 18:23
@kevinushey Using your example and a whole lot of debugging I think I've finally figured out what's going on here. The key is actually the blank line at the top of the doc. When we switch into visual mode, that line gets removed (try switching into and out of visual mode after running that snippet and you'll see it disappear) as a side effect of Pandoc rewriting the Markdown into canonical mode. However, the chunk's opinion of its position is derived from the version of the doc prior to the Pandoc rewrite, so it's off by a line, resulting in (probably) all of the ill effects observed here.

**Closed** 2020-10-22 21:21 UTC
Labels: backlog, bug, in progress, visual markdown editing

**Comment by kfeinauer** [comment] 2020-11-13 22:01
Verified fixed 1.4.1027

**Comment by sayeedahmed** [comment] 2022-11-19 23:40
In my case, a cell got corrupted as shown in the image.
Once corrected, I was able to switch to Visual mode.

<img width="287" alt="image" src="https://user-images.githubusercontent.com/17581120/202875846-86c6e708-3a0f-492f-a322-80a3d97a2326.png">

**Comment by ronblum** [comment] 2022-11-21 14:48
@sayeedahmed Thank you for raising this! Can you open a new issue for the behavior you're seeing?
