### ISSUE TITLE
Fedora RPM RStudio broken under Gnome/Xorg

### ISSUE THREAD

**Issue by rsbivand** [rstudio/rstudio#7217] opened 2020-06-25 07:46 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Fedora 32 under Xorg
    R Version       : 4.0.2

See: https://community.rstudio.com/t/fedora-rpm-rstudio-broken-under-gnome-xorg/70806

The published RPM (https://download1.rstudio.org/desktop/centos8/x86_64/rstudio-1.3.959-x86_64.rpm) works under Gnome/Wayland on Fedora 31/32, but freezes non-reproducibly when Gnome is set to use Xorg not Wayland. 

Why does this matter? Because Teams does not (yet) permit screen sharing under Wayland, but does under Xorg. However, since the RStudio IDE freezes under Gnome/Xorg (set the Fedora login to Xorg rather than Wayland - https://docs.fedoraproject.org/en-US/quick-docs/configuring-xorg-as-default-gnome-session/) unpredictably, it cannot be used for screen sharing through Teams. I'd be grateful for tips other than switching to Windows 10 after duplicating my whole teaching environment there.

Re-checking with the crash-handler on, the entries are empty, with:
```
$ od -b ~/.r/crashpad_database/settings.dat
0000000 163 144 120 103 001 000 000 000 001 000 000 000 000 000 000 000
0000020 000 000 000 000 000 000 000 000 322 326 133 036 153 121 272 113
0000040 207 220 222 164 031 027 372 014
0000050
```
Typically, the whole RStudio window goes blank apart from the top menu line, is unresponsive, and has to be killed, for example from the system monitor. To check the running session interface, use e.g.:
```
loginctl show-session 2 -p Type
```

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

Not a crash, a freeze, with no apparent activity from  the crash handler (see above).

- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-06-25 13:32
@rsbivand Thank you for raising the issue! I'll mark it as a bug to review.

**Comment by rsbivand** [comment] 2020-06-25 13:41
@ronblum Thanks. I realise that Gnome and QT5 are only distant relatives, and that this isn't RStudio's fault really (Teams should have reached Wayland capability for screen sharing). Any help would be welcome!

**Comment by chrisvwn** [comment] 2020-06-30 09:19
I actually have this same problem while using Wayland on Fedora 32. I also cannot reproduce it. It happens randomly - so far has happened as I click on non-remarkable code in the editor.

**Comment by rsbivand** [comment] 2020-07-05 16:27
@chrisvwn - yes, I see this too, unfortunately. But it less problematic than Xorg just not working. It looks as though more work is needed urgently on Wayland and Xorg for Fedora 32. Trying to help by building from source doesn't work either, as source builds fail for me immediately on F32.

**Comment by gtritchie** [comment] 2020-07-05 17:18
Can you try the latest preview build from https://rstudio.com/products/rstudio/download/preview/ just to see if it behaves any differently?

**Comment by rsbivand** [comment] 2020-07-05 17:26
Thanks, I'll try Monday morning my time. Do the changes affect both Wayland
and Xorg?

Roger

Roger Bivand
Falsensvei 32
5063 Bergen

søn. 5. jul. 2020, 19:18 skrev Gary <notifications@github.com>:

**Comment by gtritchie** [comment] 2020-07-05 17:47
Nothing specifically changed for this issue, just a minor Qt update but it did fix an issue related to new glibc on various recent distros that was leading to blank UI as described here so curious if it helps.

**Comment by rsbivand** [comment] 2020-07-06 07:01
With preview 1.3.1054 no blank UI (yet) on Xorg, which was more sensitive. Have mostly run knit of existing files, but will try editing during the day.

**Comment by chrisvwn** [comment] 2020-07-06 09:06
@rsbivand Noted. Indeed it seems less severe with Wayland.

I will also try the preview and let you know if the problem recurs.

**Comment by gtritchie** [comment] 2020-07-07 00:28
If this proves to have solved the issue, then this will be a duplicate of #6379. Leaving open for a bit longer, let me know how it is going (@rsbivand and @chrisvwn).

**Comment by chrisvwn** [comment] 2020-07-07 08:07
@rsbivand So far so good. I haven't encountered a repeat of the problem yet.

**Comment by gtritchie** [comment] 2020-07-07 16:19
Great, I'm going to resolve this as a duplicate. Let me know if it reoccurs and I will reopen.

Duplicate of #6379

**Closed by gtritchie** 2020-07-07 16:19 UTC
Labels: bug, duplicate, linux, triage
