### ISSUE TITLE
Help pane trying open webpage

### ISSUE THREAD

**Issue by Danny-dK** [rstudio/rstudio#13586] opened 2023-09-05 14:28 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0 (daily build)
    OS Version      : Windows 10
    R Version       :  4.2.2

### Steps to reproduce the problem

Run `?summarize()`. The help page of this function opens in the help pane viewer of rstudio (yay). Then click on one of the links in the help text, for example under 'Useful functions' click on the underlined `mean()`. I would expect this to open in the help viewer pane of Rstudio, but instead a webpage is trying to load in my webbrowser (firefox). `http://12some numbers5/help/library/base/html/mean.html`, but does not actually show anything.

### Describe the behavior you expected
To open help pages in the help viewer pane of rstudio, not the web-browser. Am I missing an option?

Within Rprofile.site the option `options(help_type="html")` was uncommented and  `options(help_type="text")` was commented. Switching that to have the html one commented and the text one active, does not seem to do anything. When I open Rstudio and `getOption("help_type")`, it still shows "html" as a response. In my R_USER folder (home folder) the .Rprofile is similarly setup but also no effect.

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.

- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2023-09-05 18:38
Thanks for the bug report -- I think this issue will be fixed in the upcoming daily builds (hopefully to be published tomorrow).

**Comment by ronblum** [comment] 2023-09-06 15:10
Closing this as a duplicate of #13392. @Danny-dK this should be working in the latest builds (currently 2023.09.0-401) but less know in #13392 if you still run into problems!

**Closed by ronblum** 2023-09-06 15:10 UTC
Labels: bug, new
