### ISSUE TITLE
Electron installer-less version (daily build) can't find an R installation

### ISSUE THREAD

**Issue by Vivek-Prakash-US** [rstudio/rstudio#11141] opened 2022-05-05 13:44 UTC
### System details

    RStudio Edition : Desktop installer-less
    RStudio Version : Electron 2022.06.06-daily-365
    OS Version      : Windows 10
    R Version       : 4.2.0

### Steps to reproduce the problem
Download the zip file from here: 
https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2022.06.0-daily-356.zip

Extracted to:
C:\Users\\######\Downloads\rstudio

Double click the rstudio.exe file

### Describe the problem in detail
Error message pops up

![image](https://user-images.githubusercontent.com/19595852/166935712-58c03add-7676-4d31-b918-687d5ca2a3a9.png)

### Describe the behavior you expected
I repeated the above steps using the non-electron version:
https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-2022.06.0-daily-356.zip 
and it's working fine.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2022-05-05 16:04
See also: #11059

**Comment by timtmok** [comment] 2022-06-03 14:31
This looks to be addressed by the fix for #11059. I could not reproduce this in build 461. I also attempted to change the saved R bin path to an invalid path and the IDE will show the choose R dialog when it sees that the path is invalid.

**Closed** 2022-06-03 14:32 UTC
Labels: bug, in progress, electron

**Comment by Vivek-Prakash-US** [comment] 2022-06-03 19:23
Still having failures to find R for installer-less electron build 469 and installer-less non-electron build 470.  The most recent version which starts up properly is the non-electron build 468 (also installer-less zip version).

Before launching each version I delete the RStudio directories under appdata/roaming and appdata/local, and (as far as I know) there's no .rprofile lurking anywhere either.

I'm not sure if this could effect things or not, but I have an installation of R 3.6.3 that was installed by my IT department aeons ago. I installed 4.2.0 myself (without admin), but RStudio has always loaded whatever most recent version of R I'd installed.

**Comment by jmcphers** [comment] 2022-06-03 20:14
@Vivek-Prakash-US I think you're hitting this (separate) issue: https://github.com/rstudio/rstudio/issues/11349

**Comment by Vivek-Prakash-US** [comment] 2022-08-11 14:44
I figured out a solution that in retrospect was rather simple.

First, note that I don't have admin, so R 4.2.1 installs to
_C:\Users\my_username\AppData\Local\Programs\R\R-4.2.1_

I unzip the daily electron build (Elsbeth Geranium 2022.11.0-daily-97.zip) to 
_C:\Users\my_username\Downloads\programs\rstudio_
and double-click the rstudio.exe icon. This generates the same error as above.

Before crashing Rstudio creates some folders and log files. There is a file created titled _rdekstop.2022-08-11.log_ at the location _C:\Users\my_username\AppData\Local\RStudio\log_ that contains the following lines:


`{"level":"error","message":"Command failed: reg query HKEY_LOCAL_MACHINE\\SOFTWARE\\R-Core /s /v InstallPath /reg:32\nERROR: The system was unable to find the specified registry key or value.\r\n"}
{"level":"error","message":"Command failed: reg query HKEY_LOCAL_MACHINE\\SOFTWARE\\R-Core /s /v InstallPath /reg:64\nERROR: The system was unable to find the specified registry key or value.\r\n"}
{"level":"error","message":""}`

I looked for those registry entries and they don't exist. There's no R-Core folder at all under HKEY_LOCAL_MACHINE\SOFTWARE. There is one however under HKEY_CURRENT_USER\SOFTWARE . I'm guessing it's there because I don't have admin?

Anyhoo, I was able to fix the problem by directly entering the correct R paths in
_C:\Users\my_username\AppData\Roaming\RStudio\config.json_ , specifically this entry:

`"platform": {
		"windows": {
			"rBinDir": "C:/Users/my_username/AppData/Local/Programs/R/R-4.2.1/bin/x64",
			"preferR64": true,
			"rExecutablePath": "C:/Users/my_username/AppData/Local/Programs/R/R-4.2.1/bin/x64/R.exe"
		}`

And that tweak allows RStudio to start right up.
