### ISSUE TITLE
Changing casing of filename from rstudio.app to RStudio.app (MacOS)

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11078] opened 2022-04-27 19:07 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily+333 (Electron)
    OS Version      : MacOS 12.4
    R Version       : 4.2.0

### Steps to reproduce the problem

Download the RStudio Desktop DMG file and open it.

### Describe the problem in detail

The file name in Electron is all lower case.

### Describe the behavior you expected

It would be cool if we could make use the casing of the product name, spec. `RStudio.app` instead of `rstudio.app`. This is the case with Qt:

<img width="284" alt="case" src="https://user-images.githubusercontent.com/31009952/165601110-14f85e4d-62dd-45aa-a5b5-173027be66bc.png">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2022-04-27 19:24
Duplicate of #11071

**Closed by gtritchie** 2022-04-27 19:24 UTC
Labels: bug, macos, duplicate
