### ISSUE TITLE
After closing a project the working directory does not come back to the default value

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#3358] opened 2018-08-23 18:35 UTC
After closing a project the working directory does not come back to the default value instead remains in the last opened project working directory.

This doesn't happen in the desktop windows version 

### System details

    RStudio Edition : Server
    RStudio Version : 1.2.915
    OS Version      : Ubuntu Server 16.04.5 LTS
    R Version       : 3.4.4

**Comment by kfeinauer** [comment] 2018-08-23 18:56
I cannot reproduce this. Could you provide a more detailed account of how you are closing projects, and what your working directory values are from inside/outside the project? Also, have you overridden the default working directory from `~` within the `Global Options` dialog?

You could also try moving your `~/.rstudio/monitored/user-settings/user-settings` file temporarily to see if resetting your options has any affect.

**Comment by andresrcs** [comment] 2018-08-24 03:32
My default working directory is '~' if I open any project and then click on "Close Project" the working directory keeps set to the project working directory.

    getwd()
    # "/home/andres/leadTime"

I have tried reseting my user-settings as you said but didn't work.

![image](https://user-images.githubusercontent.com/14981085/44563482-12bf7a80-a724-11e8-8618-bd4bff09ff75.png)

**Comment by kfeinauer** [comment] 2018-08-24 13:53
@ron Are you able to repdocue this? Perhaps an issue specific to Ubuntu 16?

**Comment by ronblum** [comment] 2018-08-24 19:38
No, I can't reproduce it. I tried two builds, 1.2.856 and 1.2.924, and Ubuntu 16.04.5; and 1.2.91 on Ubuntu 18.04. They all return to the default directory when projects are closed, both when projects are opened in the same sessions or new sessions.

**Comment by ronblum** [comment] 2018-08-24 19:40
@kevinushey Ignore that—that's desktop in Ubuntu. I'm able to reproduce this on Ubuntu 16.04.5 server.

**Comment by ronblum** [comment] 2018-08-24 19:56
With RStudio Server 1.2.924:
1) Reproducible on Ubuntu 16.04.5 
2) Not reproducible on Red Hat 7.5
3) Quitting and restarting the session returns to the default directory

**Comment by kfeinauer** [comment] 2018-08-28 15:06
Fixed by https://github.com/rstudio/rstudio/commit/78649aaed74abc17ce40817b23d133edae77d51b.

**Closed** 2018-08-28 15:06 UTC
Labels: bug, reproducible

**Comment by andresrcs** [comment] 2018-10-19 13:07
This problem has returned in build 1.2.1062

**Comment by kfeinauer** [comment] 2018-10-19 14:51
@andresrcs I am unable to reproduce with the same repro steps with RStudio Server 1.2.1062 (https://s3.amazonaws.com/rstudio-ide-build/server/trusty/amd64/rstudio-server-1.2.1062-amd64.deb). Have your repro steps / environment changed at all since the last time we looked at this?

**Comment by kfeinauer** [comment] 2018-10-19 15:09
@andresrcs you could also try temporarily renaming your `~/.rstudio` folder to reset your state to see if that fixes the issue? If so, we'd ideally want to figure out a set of repro steps from a clean state so we can diagnose what's going on.

**Comment by andresrcs** [comment] 2018-10-19 15:14
Yeah, you´re rigth, this is happening in a diferent way now. 

1. Open a project.
2. Reboot server (My AWS server turns off automatically at night and turns on again by the morning).
2. Open a RStudio terminal >>> The project is closed but the working directory is the same.

**Comment by kfeinauer** [comment] 2018-10-19 15:47
I can reproduce with these steps:

- Start a session
- Open project
- Kill `rsession process (`sudo kill -9 $(pidof rsession)`)
- Refresh browser window

I will dig into this more deeply (and likely create a new issue for this). In the meantime, you could work around the issue by having the node itself initiate shutdown (and consequently explicitly or implicitly invoking `sudo rstudio-server stop` to cleanly shutdown the service), instead of forcefully stopping your AWS instance.

**Comment by kfeinauer** [comment] 2018-10-19 16:10
This will be tracked in #3709

**Comment by kfeinauer** [comment] 2018-10-19 16:30
As you can see in the discussion of #3709 this is actually expected behavior for now, so my suggestion about attempting to do a clean shutdown of RStudio before turning off the AWS instance seems to be the best solution for now.

**Comment by andresrcs** [comment] 2018-10-19 16:37
I understand that not restoring the default project is a desirable behavior but, can you also restore the default working directory when this happens?

**Comment by kfeinauer** [comment] 2018-10-19 16:53
Agreed @andresrcs that we could restore the working dir - will tackle this in #3220
