### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#5310] opened 2019-08-28 01:38 UTC
It would be nice to press F11 and have RStudio behave similarly to how Chrome, Firefox and VSCode behave when you press F11. (Essentially hide the OS title, menu bar, dock, etc)

This would be especially useful on laptops where there is limited screen real estate to work with.

**Comment by ronblum** [comment] 2019-08-28 21:27
@t-kalinowski Thank you! Confirmed on Windows 10. I'll mark this as an enhancement to review during ongoing development of RStudio.

**Comment by t-kalinowski** [comment] 2019-12-14 17:48
two notes:
1) just noticed this is probably a duplicate of #3243 (though that issue frames the feature request as a windows specific issue)
2) On Linux (running gnome shell), I was able to achieve this through a combination of https://extensions.gnome.org/extension/1732/gtk-title-bar/ and https://extensions.gnome.org/extension/545/hide-top-bar/

**Comment by jmcphers** [comment] 2020-01-08 06:31
Indeed, it's a dupe of #3243; we'll use that to track the issue.

**Closed by jmcphers** 2020-01-08 06:31 UTC
Labels: enhancement
