### ISSUE TITLE
Visual Editor turns citekeys into plain text when editing

### ISSUE THREAD

**Issue by samuelmehr** [rstudio/rstudio#9993] opened 2021-10-22 16:56 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : macOS 10.15.7
    R Version       : 4.1.1

### Steps to reproduce the problem / Describe the problem in detail
In Markdown text with citations, editing a block of citekeys changes the text from a citekey (e.g. `@Author2020`) to plain text within the block of citekeys (e.g. `\@Author2020`). This can be reproduced by inserting a few citations from a Zotero library (or entering them manually), and then trying to edit one or more of the citekeys.

### Describe the behavior you expected
I think citekeys should be editable directly (while remaining actually citekeys, as opposed to being converted to plain text) as this is a common action when editing an R Markdown document.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-11-05 14:32
@samuelmehr Thank you for raising this! I can't reproduce it, though, in eith
- RStudio Desktop 1.4.1717 on MacOS 12
- RStudio Desktop 2021.09.0+351 on MacOS 12

Would it be possible to get a screen recording so that I can see the exact steps you're going through? Thanks!

**Comment by samuelmehr** [comment] 2021-11-05 15:02
Sure thing, here you go. Thanks for following up!

https://user-images.githubusercontent.com/41483946/140531959-22bd6c95-dc8b-491f-8853-9238e2272866.mov

**Comment by ronblum** [comment] 2021-11-08 15:50
@samuelmehr Thank you! This was very helpful. I can reproduce it in both
- RStudio Desktop 1.4.1717 on MacOS 12
- RStudio Desktop 2021.09.1+371 on MacOS 12
- RStudio Server 2021.09.0+351 on Ubuntu 20.04 via Safari on MacOS 12

Just typing a new citation, and multiple citations in a row, doesn't seem to be a problem. The exact steps I can reproduce this with are:

Behavior 1:
1. Enter one citation, e.g. `@entry1`
2. Place the cursor to the left of the <kbd>@</kbd> of the entry
3. Start another citation by typing <kbd>@</kbd> and complete the entry, e.g. `@entry2, @entry1`
    - The original entry is considered text, not a citation, while the new citation works
<img width="138" alt="behavior1" src="https://user-images.githubusercontent.com/31009952/140773513-da728581-58e0-4932-ac49-7417fcc2934f.png">

Behavior 2:
1. Enter two citations, separated by a comma or semicolon, e.g. `@entry1, @entry2`
2. Place the cursor to the left of the <kbd>@</kbd> of the second entry
3. Start another citation by typing <kbd>@</kbd> and complete the entry, e.g. `@entry1, @entry3, @entry2`
    - The new entry is considered text, not a citation
<img width="195" alt="behavior2" src="https://user-images.githubusercontent.com/31009952/140773552-9a5671fa-1bf6-4f97-ac1f-3afd6b2733c8.png">

**Comment by samuelmehr** [comment] 2021-11-08 15:54
yes, those two definitely were issues I ran into. I believe, but am not sure, that a further one involved deleting the ending `]` to a group of citations and then adding a new citation, wherein the new entry would similarly be plain text. But I haven't been able to reproduce this. 

One thing is that the Zotero library associated with my document is large and loads sluggishly, so I wonder if it had something to do with that, i.e. RStudio doesn't "realize" that I'm typing a real citation because the library hasn't finished loading, and defaults to plain text instead. (just speculating, in case the sluggish loading is a useful fact)

**Comment by ronblum** [comment] 2021-11-08 15:56
@samuelmehr Thanks! One of my instances has a very small Zotero library, and the other doesn't have any Zotero entries—I used bogus citations that don't—and the problem occurred in both cases.

**Comment by dragonstyle** [comment] 2021-12-07 19:14
We've made some improvements that should address these issue in these commits: 

- 9f08d897f87833f7d21232db417b4bfb79dc8b3e 
- 1a0cf2e0bf899da5cca8bceca3c8074be6a9d219

This should make it far more reliable to type sequences of citations, though it is important to note that back to back `@` aren't valid citations, so when you type that, the elements may be unhighlighted as they have become invalid.

I've slightly amended the (helpful!) repro case from previous comments:

Behavior 1:
1. Enter one citation, e.g. `@entry1`
2. Place the cursor to the left of the <kbd>@</kbd> of the entry
3. Type a space, then back arrow.
4. Start another citation by typing <kbd>@</kbd> and complete the entry, e.g. `@entry2, @entry1`
   
Behavior 2: 
1. Enter two citations, separated by a comma or semicolon, e.g. `@entry1, @entry2`
2. Place the cursor to the left of the <kbd>@</kbd> of the second entry
3. Type a space, then back arrow. (or alternatively, place the cursor to the right of the first entry, then type space)
4. Start another citation by typing <kbd>@</kbd> and complete the entry, e.g. `@entry1, @entry3, @entry2`

These should both be working in builds that include these commits.

**Comment by ronblum** [comment] 2021-12-09 16:44
Also, here's a workaround if running into the original issue with double at sign, `@@`:
1. Repeat the problem that occurs with `@@`. (In the source editor it'll appear as `@\@`.)
2. Finish writing the new citation, such that everything seems right visually, except that the original citation is no longer being treated as one.
3. Delete the `@` from the old, nonworking citation.
4. Type `@`.

The original entry is now a citation again.

**Comment by ronblum** [comment] 2021-12-09 16:47
Closing as "by design" because the visual editor is behaving as expected, taking into account `@@` is invalid and thus treats the second `@` as a literal. But once it's a literal, it's always a literal.

**Closed by ronblum** 2021-12-09 16:47 UTC
Labels: bug, visual markdown, test

**Comment by Robinlovelace** [comment] 2022-05-12 22:37
Heads-up @ronblum and after installing the latest version of RStudio today, I can confirm that this is still an issue, at least on my desktop. Just tested. Please re-open, citations also seem completely absent in the latest versions...

**Comment by ronblum** [comment] 2022-05-13 15:59
Thanks @Robinlovelace ! You probably already saw this in 7876—it'd be great if you could file an issue for the citations being absent.

I'll ask about the original issue, since I thought it was by design.

**Comment by ronblum** [comment] 2022-05-13 16:09
@Robinlovelace Which behavior are you still seeing, since changes were made to resolve some things, and one aspect is by design?

**Comment by Robinlovelace** [comment] 2022-05-13 16:40
I'll give it a go, thanks for the heads-up. Quick summary: in some .Rmd documents the Citations dialogue does not appear for some reason... Worth trying again on latest daily version?

**Comment by ronblum** [comment] 2022-05-13 16:52
Oh! I think I misunderstood: Do you mean that the problem is what you've covered in #11198? Or are there other issues from above?

**Comment by Robinlovelace** [comment] 2022-05-13 16:56
Yes the only issue I'm having (as of yesterday late evening after realizing that it was only some .Rmd documents that failed) is https://github.com/rstudio/rstudio/issues/11198

**Comment by Robinlovelace** [comment] 2022-05-13 16:58
I left the message here before realising it only affected some .Rmds. But the affected Rmds to turn citekeys into plaintext as a byproduct of not having any Citations dialogue. I know https://github.com/rstudio/rstudio/issues/11198 is not reproducible, can try to make it so but pretty busy ATM so just wanted to document my experience in case of use/interest to others.

**Comment by ronblum** [comment] 2022-05-13 17:14
Thanks! I tagged #11198 as a bug to review, in case something stands out even if it's only reproducible in one case.
