### ISSUE TITLE
Spell check support article out of date, doesn't work as described

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9052] opened 2021-03-03 22:38 UTC
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.x
    OS Version      : Any
    R Version       : Any

### Steps to reproduce the problem
- Tools / Global Options / Spelling, click the ? next to main dictionary language dropdown
- Goes to https://support.rstudio.com/hc/en-us/articles/200551916
- Follow the steps in this support article to try and add a custom language dictionary (e.g. ko_KR.aff and ko_KR.dic, attached to this issue).

### Describe the problem in detail
- The language does not show in the UI

### Describe the behavior you expected
- Article should accurately describe how to accomplish this with supported IDE versions
- Article should cover details on all three desktop platforms (it currently doesn't mention macOS)

### Notes
- From a support ticket: (58429)
- If I copy the Korean aff/dic to `%appdata%\RStudio\Dictionaries\custom` on Windows-10 then it will appear as a custom dictionary but haven't been able to make it appear as a language

[ko_KR.zip](https://github.com/rstudio/rstudio/files/6079681/ko_KR.zip)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by valerie-rstudio** [comment] 2021-03-11 17:45
### Steps for Mac:
1. Place new language .aff and .dic files into the directory `~/.config/rstudio/dictionaries/languages-system`
2. Open RStudio and navigate to Tools > Global Options > Spelling and select the new language from the drop down menu.
3. Verify the new language works by open a new R markdown file, typing something in the new language, and saving the file.


### Notes:
- I can get Korean to show as an option in the language drop-down using the above steps, and I am no longer seeing Korean be highlighted red. However, I am unsure if it's highlighting any misspellings in red, as I was unable to find any examples of misspelled Korean online, and I do not know the language.
- The guide at https://support.rstudio.com/hc/en-us/articles/200551916 needs to be updated to include the Mac instructions

**Comment by gtritchie** [comment] 2021-03-11 22:54
Still doesn't seem to be working for me on Windows or Mac.

Mac, put the 2 dictionary files in `~/.config/rstudio/dictionaries/languages-system`.
Windows, put them in `%appdata%\rstudio\dictionaries\languages-system`.

Create an R script, paste in this, and save it.

```
# Words in various languages, with correct on left, incorrect on right

# US English
# mountane mountain
# todey today

# Korean
# 요세   요새
# 설겆이   설거지
# 오랫만에   오랜만에
# 바꼈다   바뀌었다
# 어의없다   어이없다
```

With default English (US) dictionary, all the Korean words and the two misspelled English words have red-squiggles.

Now select the Korean dictionary. It is at the bottom of the list and does not have a friendly name:

![2021-03-11_14-04-43](https://user-images.githubusercontent.com/10569626/110865991-54c85180-8279-11eb-8f39-78abcc80b781.png)

Resave the file to trigger a spell check. In Microsoft Word with Korean proofing tools, the leftmost Korean word is flagged as misspelled and the right is not, as expected.

In RStudio, there are no red squiggles on either the English or Korean words.

**Comment by gtritchie** [comment] 2021-03-11 23:33
One more data point, if I turn off real-time spellchecking and use the old on-demand checking with F7, then it does correctly flag the incorrect Korean words and skip the correct ones.

**Comment by adamconroy** [comment] 2021-03-12 02:19
Interesting. We've seen this before due to the encoding format of the dictionaries. I'll take a gander tomorrow.

**Comment by adamconroy** [comment] 2021-03-12 20:11
There is something wrong here. Even with the dictionary added as a custom one it is still parsing the words the same way. This is a bug that will have to be fixed but I think it's out of scope for Juliet Rose. We have had issues with custom characters for German and other dictionaries that have non-ASCII characters (our dictionaries were encoded incorrectly) and there may be something similar here.

As part of fixing this I will add the Korean dictionary as one of our shipped defaults so we know it's tested and supported.

**Comment by mikebessuille** [comment] 2021-03-15 17:14
Need to investigate the regression, not just update the documentation.

**Comment by adamconroy** [comment] 2021-03-22 20:43
Just so all the context from the research is here:

The change happened in this PR https://github.com/rstudio/rstudio/pull/5269
to address the config changes here https://github.com/rstudio/rstudio/issues/5162

I don't recall exactly why languages-system was dropped (perhaps @jmcphers remembers) but I think it may have been due to how we prepackage our zipped dictionaries and have them listed in their own structure.

I'm going to spend a little more time delving into exactly why the frontend dictionary is being so persnickity about non-ASCII characters. With German/Italian etc we were able to "fix" this by ensuring all the encodings were set correctly. I suspect something extra is happening with Korean due to the mixed viable encodings with the news article. This problem will continue to plague us until it's fully fixed so I'm going to take tomorrow to get to the bottom of it.

**Comment by adamconroy** [comment] 2021-03-24 18:39
After more investigation I think we're running into some limitations in how many implementations of Hunspell (clearly with some flaws) are working. Since the CPP Hunspell is working I don't think I should spend much more time on this at the moment but for referencing back in the future:

Somehow the way that Typo.js is interpreting the very large ruleset it's interpreting the misspelled words as correct. In fact, many spellcheckers that I tested today are doing the same, including Google Docs (though I couldn't tell if it was actually testing anything in Korean even though it purported to). The best online Korean spellchecker I found was here: https://alldic.daum.net/grammar_checker.do It even had (what appears to be) sensical suggestions.

https://github.com/rstudio/rstudio/blob/0899d13386fd5e61ec847cc62a6eb252702a5ebc/src/gwt/src/org/rstudio/studio/client/common/spelling/typo.js#L679 This is returning true. Due to complexity for how the rules are constructed and my lack of understanding of them I think our best suggestion for languages that Typo.js is fully incompatible with is just to have them turn off real-time spellchecking for now.

Sadly, the number of issues that Typo.js has is pushing me to rip it out entirely. The CPP Hunspell works perfectly and there isn't a huge reason not to just leverage that. I was overly ambitious with my first project at RStudio and ended up using a flawed package (that doesn't seem to be maintained anymore. I actually don't think this would be a huge project and we can leverage all the linting and performance work that was done, just send the requests to the backend instead of Typo.js.

**Comment by valerie-rstudio** [comment] 2021-04-02 17:11
@adamconroy 

### Need More Info
- Should the [support article](https://support.rstudio.com/hc/en-us/articles/200551916) now contain the correct, up to date instructions for adding a dictionary and include the Mac instructions?
- Should the Korean dictionary now be included by default?
- Are the repro steps for this still - import a custom language and verify on-demand spellchecking is working for the imported language?

**Comment by adamconroy** [comment] 2021-04-02 19:54
> Should the support article now contain the correct, up to date instructions for adding a dictionary and include the Mac instructions?

Yes

> Should the Korean dictionary now be included by default?

No. In fact, Korean will not work for Realtime spellchecking until my PR is merged https://github.com/rstudio/rstudio/pull/9161
I will be nice later on down to the line to include even more dictionaries but I think that would be separate from this ticket and would require confirming with native speakers which dictionaries seem worth adding.

> Are the repro steps for this still - import a custom language and verify on-demand spellchecking is working for the imported language?

It would be to follow the instructions in the support article and make sure that a dictionary will show up as a primary language option. Let me know if it doesn't work! There was no code change for this, just trying to get the instructions to line up with the way it's been for a long time now.

**Comment by valerie-rstudio** [comment] 2021-04-02 20:37
### Verify Failed

### Failure Points
- It looks like by default we now support more than just the English languages listed. So this portion of the support article may need to be updated to reflect that:
![Screen Shot 2021-04-02 at 3 35 35 PM](https://user-images.githubusercontent.com/75644399/113452236-38778a80-93c9-11eb-9a2d-7d12c3c84a7d.png)
- The [support article ](https://support.rstudio.com/hc/en-us/articles/200551916)instructions do not provide the location of the `dictionaries/languages-system directory` for the MacOS or Windows 10 platforms. The current platforms are shown in the screenshot below: 
![Screen Shot 2021-04-02 at 3 22 25 PM](https://user-images.githubusercontent.com/75644399/113451517-bd61a480-93c7-11eb-8e3c-4ab54d075b19.png)
- It looks like the link to [OpenOffice Wiki ](https://wiki.openoffice.org/wiki/Dictionaries)may no longer be a good source of additional language dictionaries, as most of the links on that page now are broken. We may want to provide a link to some other source of dictionary files.
![Screen Shot 2021-04-02 at 3 30 14 PM](https://user-images.githubusercontent.com/75644399/113451795-57295180-93c8-11eb-85b0-981ebd63fd85.png)
- The link to the [OpenMedSpel](https://www.e-medtools.com/Hunspel_openmedspel.html) dictionary example now points to a site with a 526 error. May want to find a different example of a custom dictionary.
![Screen Shot 2021-04-02 at 3 32 19 PM](https://user-images.githubusercontent.com/75644399/113451933-a4a5be80-93c8-11eb-8990-0cc1314ce227.png)

**Comment by gtritchie** [comment] 2021-06-09 22:19
I have updated the article:

- added note at beginning saying this is updated for juliet-rose
- fixed documentation on where to put custom language dictionaries on Mac and Windows (removed mention of Window-XP, 7 and 8 and just said "Windows-10; but would still work for 7 and 8 if somebody tries)
- changed link for where to find dictionaries to point to "About Hunspell" page's list of possible sources
- updated link for OpenMedSpel dictionary
- new screenshot of the Spelling Options dialog pane (one in article was old and missing several widgets added in last few versions)

**Comment by valerie-rstudio** [comment] 2021-06-14 15:33
### Verified Fixed

Verified that the [support article](https://support.rstudio.com/hc/en-us/articles/200551916) is now up to date and includes instructions for mac, linux, and windows.

**Closed by valerie-rstudio** 2021-06-14 15:33 UTC
Labels: bug, documentation, spellcheck, test
