### ISSUE TITLE
Daily version of RStudio crashes using R (ARM version) on M1 MacBook

### ISSUE THREAD

**Issue by yashkal** [rstudio/rstudio#9396] opened 2021-05-23 08:22 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.5.46
    OS Version      : macOS BigSur 11.3.1
    R Version       : 4.1.0 (2021-05-18)

### Steps to reproduce the problem

1. Install RStudio Daily Build
2. Install R using `brew install r`
3. Open RStudio

### Describe the problem in detail

I am trying to get RStudio to work on my MacBook Pro (ARM) using the latest version of R. According to this [discussion](https://community.rstudio.com/t/update-on-r-rstudio-support-for-apple-silicon-macs/95582/11), it seems as if RStudio should be able to run the ARM version of R.  I am able to run R through the command line, but the R session fails to start on RStudio daily build however.

Here is diagnostic information

```
Attempting to launch R session...
  R_HOME=/opt/homebrew/Cellar/r/4.1.0/lib/R
  R_DOC_DIR=/opt/homebrew/Cellar/r/4.1.0/lib/R/doc
  R_INCLUDE_DIR=/opt/homebrew/Cellar/r/4.1.0/lib/R/include
  R_SHARE_DIR=/opt/homebrew/Cellar/r/4.1.0/lib/R/share
  DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/Cellar/r/4.1.0/lib/R/lib:/Users/yashkalebere/lib:/usr/local/lib:/usr/lib:::/lib
  PATH=/opt/homebrew/Caskroom/miniforge/base/bin:/opt/homebrew/Caskroom/miniforge/base/condabin:/opt/homebrew/opt/blast@2.2/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/bin:/Users/yashkalebere/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/blast@2.2/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/Users/yashkalebere/homebrew/bin:/opt/homebrew/opt/fzf/bin
  HOME=/Users/yashkalebere

R session launched, attempting to connect on port 44407...
dyld: could not load inserted library '/opt/homebrew/Cellar/r/4.1.0/lib/R/lib/libR.dylib' because no suitable image found.  Did find:
        /opt/homebrew/Cellar/r/4.1.0/lib/R/lib/libR.dylib: mach-o, but wrong architecture
        /opt/homebrew/Cellar/r/4.1.0/lib/R/lib/libR.dylib: stat() failed with errno=1


Connected to R session, attempting to initialize...
```

Below are some logs that may be important:

#### R Version

```
platform       aarch64-apple-darwin20.4.0
arch           aarch64
os             darwin20.4.0
system         aarch64, darwin20.4.0
status
major          4
minor          1.0
year           2021
month          05
day            18
svn rev        80317
language       R
version.string R version 4.1.0 (2021-05-18)
nickname       Camp Pontanezen
```

#### RStudio Version

```
RStudio 1.5.46, "Ghost Orchid" (96d655e6, 2021-05-19) for macOS

Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
```

#### Process Output

```
dyld: could not load inserted library '/opt/homebrew/Cellar/r/4.1.0/lib/R/lib/libR.dylib' because no suitable image found. Did find:
/opt/homebrew/Cellar/r/4.1.0/lib/R/lib/libR.dylib: mach-o, but wrong architecture
/opt/homebrew/Cellar/r/4.1.0/lib/R/lib/libR.dylib: stat() failed with errno=1
```

#### Recent Log

```
15 May 2021 21:52:24 [rsession-yashkalebere] ERROR system error 48 (Address already in use); OCCURRED AT rstudio::core::Error rstudio::core::http::initTcpIpAcceptor(SocketAcceptorService<boost::asio::ip::tcp> &, const std::string &, const std::string &) src/cpp/session/http/SessionPosixHttpConnectionListener.cpp:103; LOGGED FROM: int main(int, char *const *) src/cpp/session/SessionMain.cpp:2029
18 May 2021 10:21:19 [rsession-yashkalebere] WARNING Abort requested; LOGGED FROM: bool rstudio::session::connection::checkForAbort(boost::shared_ptr<HttpConnection>, const boost::function<void ()>) src/cpp/session/http/SessionHttpConnectionUtils.cpp:150
23 May 2021 05:47:34 [rsession-yashkalebere] WARNING Private command disabled, unsupported $HISTCONTROL: [ignoredups]; LOGGED FROM: bool rstudio::core::terminal::PrivateCommand::output(const std::string &) src/cpp/core/terminal/PrivateCommand.cpp:247
```

### Describe the behavior you expected

Expected to see RStudio open without errors

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-05-24 13:34
@yashkal Thank you for raising this! Is this also occurring with [the current 1.4 Juliet Rose preview](https://www.rstudio.com/products/rstudio/download/preview/) as well, or does it work OK?

**Comment by yashkal** [comment] 2021-05-24 19:33
I just attempted and the preview release isn't working either 😕. Similar errors.

**Comment by ronblum** [comment] 2021-05-26 17:36
@kevinushey Could this have something to do with installing using Homebrew vs. the installer at https://cran.r-project.org/?

**Comment by kevinushey** [comment] 2021-05-26 17:44
@yashkal, can you confirm the output of the following from the terminal?

```
file /opt/homebrew/Cellar/r/4.1.0/lib/R/lib/libR.dylib
```

**Comment by kevinushey** [comment] 2021-05-26 17:45
And also, the output of:

```
file /Applications/RStudio.app/Contents/Macos/*
```

**Comment by yashkal** [comment] 2021-05-27 05:16
This is after downloading latest RStudio ver 1.5.54.

```
➥ file /opt/homebrew/Cellar/r/4.1.0/lib/R/lib/libR.dylib
/opt/homebrew/Cellar/r/4.1.0/lib/R/lib/libR.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

```
➥ file /Applications/RStudio.app/Contents/Macos/*
/Applications/RStudio.app/Contents/Macos/RStudio:        Mach-O 64-bit executable x86_64
/Applications/RStudio.app/Contents/Macos/diagnostics:    Mach-O 64-bit executable x86_64
/Applications/RStudio.app/Contents/Macos/mac-terminal:   a /usr/bin/osascript script text executable, ASCII text
/Applications/RStudio.app/Contents/Macos/pandoc:         directory
/Applications/RStudio.app/Contents/Macos/postback:       directory
/Applications/RStudio.app/Contents/Macos/r-ldpath:       Bourne-Again shell script text executable, ASCII text
/Applications/RStudio.app/Contents/Macos/rpostback:      Mach-O 64-bit executable x86_64
/Applications/RStudio.app/Contents/Macos/rsession:       Mach-O 64-bit executable x86_64
/Applications/RStudio.app/Contents/Macos/rsession-arm64: Mach-O 64-bit executable arm64
```

Not sure if this helps track down the problem, but it works fine with `brew install --cask r`, which instead downloads x86_64 R. It crashes when only the arm64 R version is installed though.

**Comment by mikebessuille** [comment] 2021-06-07 17:28
Need to consider whether we will need to patch this, if it affects a lot of users or if there is no workaround.

**Comment by astayleraz** [comment] 2021-06-24 19:56
I was not able to reproduce this on an m1 with R 4.1.0 installed via brew install and testing on version 1.5.105.

**Comment by mikebessuille** [comment] 2021-06-30 15:20
Looks like this has only been reported by one user - given how extensively the desktop is used on Mac and M1, this seems like a problem in that specific environment which we have not been able to reproduce in-house.  We will close this issue; we can re-open it if additional users encounter the problem, or if new information comes up that allows us to reproduce.

**Closed by mikebessuille** 2021-06-30 15:21 UTC
Labels: backlog, bug, m1
