### ISSUE TITLE
RStudio does not load document history on startup

### ISSUE THREAD

**Issue by GeoffLP** [rstudio/rstudio#2683] opened 2018-04-23 15:28 UTC
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by GeoffLP** [comment] 2018-04-23 15:39
RStudio Edition : Desktop
RStudio Version : 1.1.447
OS Version      : Windows 10
R Version       : 3.4.2

Steps to reproduce the problem.  I checked Global Options, Resore previously opened source documents at startup is checked.  I updated to latest version of RStudio.  I renamed directory Users\Geoff\AppData\Local\Rstudio-Desktop to force a new version of directory to be created

Describe problem in detail.  Following a crash of R while using RStudio I had to a hard reset, subsequently I find that when opening an RStudio project the script files used are not opened, although the workspace is loaded.  The first time I open an old Rproject these files are shown, but subsequently they are lost.  Creating a new project produces the same behaviour.  After creating a newUsers\Geoff\AppData\Local\Rstudio-Desktop I note that files such as RStudio-Desktop\project_settings\last-project-path are empty.  It suggests that R studio is not writing the appropriate files.

**Comment by Schumzy** [comment] 2018-04-26 15:57
I have a similar issue:
Steps to reproduce and Problem description are the same as original post

Expected Behaviour: On open of R studio, to have all 4 panels showing and the previous source files open as well

RStudio Edition: Desktop
Rstudio Version: 1.1.442
OS Version: Windows 10
R Version x64 3.4.4

**Comment by filups** [comment] 2018-04-27 19:28
same

**Comment by dfalty** [comment] 2018-04-30 17:31
For projects, this information is stored within the `.Rproj.user` in your project directory. If you rename that directory (it is hidden), open the project, open source files, close/reopen project, does it then work correctly? Does this only happen after a crash? I'm wondering if it's getting corrupted somehow.

You can take a look at the file that is created in `<projectDirectory>/.Rproj.user/<id>/sources/prop/INDEX`.

**Comment by Schumzy** [comment] 2018-04-30 18:12
@dfalty I understand how the proj.user file works. My other laptop was set up and working (it had a previous rstudio) but when I moved to a new PC and new rstudio these issues started.

It simply is not opening file history on start up. It's a bug... simple as.

**Comment by dfalty** [comment] 2018-04-30 18:52
Unfortunately, I can't reproduce on Windows 10 with version 1.1.442 or 1.1.447. Do any errors appear in the logs when reproducing the issue? https://support.rstudio.com/hc/en-us/articles/200554756-RStudio-Application-Logs

**Comment by jrk1** [comment] 2018-04-30 18:55
I have the same problem. Re-installs did not help.

**Comment by filups** [comment] 2018-04-30 18:55
Removing/renaming the .Rproj.user folder has no effect for me. I don't really know if this is directly the result of Rstudio crashing, but I suspect that it is related. I've been running a lot of bayesian models and sometimes they crash Rstudio; sometimes they freeze Windows (so for me that could be the cause, rather than RStudio actually crashing). As stated above, other projects that weren't open when the crashing/freezing was happening still work as expected.

**Comment by jrk1** [comment] 2018-04-30 18:59
I never had any crashing or similar. So, at least in my case, there must be another reason.

**Comment by filups** [comment] 2018-04-30 19:10
It looks like the error is getting logged. Here's the most recent one: 
30 Apr 2018 18:35:13 [rsession-Phil] ERROR system error 32 (The process cannot access the file because it is being used by another process) [path=C:/Users/[username]/OneDrive/Density/.Rproj.user/E227DA36/sources/prop/410EA0A2]; OCCURRED AT: rstudio::core::Error rstudio::core::FilePath::open_w(rstudio_boost::shared_ptr<std::basic_ostream<char> >*, bool) const C:\Users\Administrator\rstudio\src\cpp\core\FilePath.cpp:1144; LOGGED FROM: rstudio::core::Error rstudio::session::source_database::put(rstudio_boost::shared_ptr<rstudio::session::source_database::SourceDocument>, bool) C:\Users\Administrator\rstudio\src\cpp\session\SessionSourceDatabase.cpp:798

SOLUTION [for me]: I completely exited OneDrive, renamed the .Rproj.user folder, opened the project, opened the scripts I wanted, closed the project. Then when I re-opened it, the scripts opened as well. It still works after re-starting OneDrive, also.

**Comment by jrk1** [comment] 2018-04-30 20:51
My error:
30 Apr 2018 20:32:11 [rsession-JRK] ERROR system error 5 (Access is denied) [path=C:/Users/JRK/OneDrive/gian/.Rproj.user/7101AFBD/sources/s-54619AAE]; OCCURRED AT: rstudio::core::Error rstudio::core::FilePath::remove() const C:\Users\Administrator\rstudio\src\cpp\core\FilePath.cpp:692; LOGGED FROM: void rstudio::session::source_database::{anonymous}::onQuit() C:\Users\Administrator\rstudio\src\cpp\session\SessionSourceDatabase.cpp:914

**Comment by jrk1** [comment] 2018-04-30 22:08
So, I just figured out that the error only occurs with projects stored on onedrive. Until recently, this was never a problem though. I think there may have been a Windows 10 update ca. a week ago. Maybe that has changed the permission onedrive gives to other programs?

**Comment by filups** [comment] 2018-04-30 22:34
This doesn't affect all of my projects that are on OneDrive, though.

**Comment by GeoffLP** [comment] 2018-05-01 10:32
I repeated the solution from jrk1. After renaming the .Rproj.user directory I had to create a new project in the parent directory, but after closing the project and re-opening the document history is back.  
I wonder if the problem might be linked to Microsoft  OneDrive Files On-Demand, I had not realised that my files were no longer on local machine, have changed this to Always keep on this device, although it definitely started after RStudio crashed.

**Comment by jrk1** [comment] 2018-05-01 12:48
I also just changed the option to "keep on this device", but it is still not working. GeoffLP, does it now generally work for you again? And if yes, could you give some more details on your solution?

**Comment by GeoffLP** [comment] 2018-05-01 13:16
I thought is was solved, but I have just opened the project again and no document history shows!!! 
So this does not solve the problem, although it seemed to for a short period.  
I checked the file /.Rproj.user/<id>/sources/prop/INDEX and it contained the reference to the R script that should have opened (10a_Tkit_P_mismatch3_GM.R), it contained
O%3A%2FOneDrive%2FWork%2FSmallTasks%2F2018%2FMacNutPaper%2F2ndDraft%2F10a_Tkit_P_mismatch3_GM.R="D6190280" I don't know what the other directories contain.

I suspect that the problem may be in the User Application part of Windows.  I have always found that if I open an old project on a different computer the document history does not load, the details must be  in  /Users/<name>/AppData/Local/RStudio-Desktop/  but I don't know where.  I tried re-naming this directory and creating a new one, but this did not solve the problem.

**Comment by jrk1** [comment] 2018-05-01 16:53
Is there any way to get R-Studio programmers involved in this thread?

**Comment by Schumzy** [comment] 2018-05-02 17:07
Yeah, I reporoduced the same as @jrk1 same errors. I then decided to create a new project on my local drive and it worked fine, but when I created a new proj on onedrive, it didn't work again.

Right now not sure why it can't be reproduced... And yes we need the devs to get involved.

**Comment by jrk1** [comment] 2018-05-04 16:46
So, how do we get their attention?

**Comment by gtritchie** [comment] 2018-05-04 17:03
You've got our attention. Just a question of time on our end. OneDrive has caused problems in the past, but haven't yet looked into what's going on with their latest iteration.

Does the problem happen with a daily build of RStudio 1.2? I suspect it will still happen, but would be a good data point. Be warned 1.2 is still under active development so build-to-build quality can vary considerably. https://dailies.rstudio.com/

**Comment by jrk1** [comment] 2018-05-04 17:49
Great, thank you for following up on this. I just tried with the newest build and have the same problem. Same error according to the logs:

04 May 2018 17:44:10 [rsession-JRK] ERROR system error 5 (Access is denied) [path=C:/Users/JRK/OneDrive/gian/.Rproj.user/7101AFBD/sources/s-54F5613D]; OCCURRED AT: class rstudio::core::Error __cdecl rstudio::core::FilePath::remove(void) const C:\jenkins\workspace\IDE\windows\src\cpp\core\FilePath.cpp:671; LOGGED FROM: void __cdecl rstudio::session::source_database::`anonymous-namespace'::onQuit(void) C:\jenkins\workspace\IDE\windows\src\cpp\session\SessionSourceDatabase.cpp:968

**Comment by filups** [comment] 2018-05-04 18:01
Do other file streaming services (Dropbox, Google File Stream, etc.) work better with Rstudio? Is the simple solution here to avoid OneDrive?

**Comment by jrk1** [comment] 2018-05-04 18:02
No idea. Work wise I have to use Onedrive...

**Comment by gtritchie** [comment] 2018-05-08 15:57
Thanks. I will try and setup an environment to test this in the next couple of days. First thing I do when configuring a development VM for Windows is uninstall and disable OneDrive, so need a separate VM to try this out on. :-)

**Comment by gtritchie** [comment] 2018-05-08 16:48
Also, just to be sure, is this OneDrive (consumer) we are talking about? The one that ships with Windows-10? Or is it OneDrive for Business (which is really SharePoint)?

**Comment by jrk1** [comment] 2018-05-08 16:52
Thank you for following up on this. I believe that I am using the one that ships with Win 10. My version is "Version 2018 (Build 18.065.0329.0002)"

**Comment by filups** [comment] 2018-05-08 17:26
I'm using OneDrive for Business via an Office 365 subscription through my university. It also shows "Version 2018 (Build 18.065.0329.0002)". 

(jrk1 - you can tell if it's personal or business by the icon color in the taskbar: personal is white, business is blue: https://support.office.com/en-us/article/which-version-of-onedrive-am-i-using-19246eae-8a51-490a-8d97-a645c151f2ba )

**Comment by jrk1** [comment] 2018-05-08 17:30
Good to know. That means I am using the Business version as well.

**Comment by gtritchie** [comment] 2018-05-08 17:43
Ok, I don't have MS-Office, will have to ask around.

**Comment by GeoffLP** [comment] 2018-05-09 09:04
I think I am using One Drive personal, it came with Office 365 home. It is version 2018 (Build 18.065.0329.0002). I am currently using Files On-Demand, and wonder if this is part of the problem as I think the R Studio problem started when Microsoft introduced this feature.

**Comment by Schumzy** [comment] 2018-05-14 15:36
@gtritchie I am using the one that shipped with windows, I simply signed in with my old (business) sign up

**Comment by Schumzy** [comment] 2018-05-14 15:37
And also my windows 10 is the home version.

**Comment by gtritchie** [comment] 2018-05-14 16:35
Thanks for added data (and your patience!). I ended up being mostly away from work last week, so didn't get a chance to look into it.

**Comment by jrk1** [comment] 2018-05-14 20:57
Something weird happening here. Suddenly it loads the scripts again. Let's see how long it will last.

**Comment by jrk1** [comment] 2018-05-15 12:29
Second day in, it still works. I really don't know why. I ran some updates, maybe that is why? One Drive version is the same as before.

**Comment by filups** [comment] 2018-05-15 12:38
Mine also started working again a couple days ago. Hopefully it lasts...

**Comment by jrk1** [comment] 2018-05-16 14:37
Great, after a large win10 update, Rstudio doesnt load projects from onedrive at all anymore:
"This site can’t be reached.127.0.0.1 refused to connect."

**Comment by filups** [comment] 2018-05-16 14:53
It is working for me (at least today) on Windows 10 Home, Version 1803, build 17134.48.

**Comment by jrk1** [comment] 2018-05-16 15:17
It still works when I open projects from within R-Studio. I probably just have to re-install it.

**Comment by mjwebster** [comment] 2018-06-01 21:47
I started having the same problem a couple weeks ago, including the error message "The process cannot access the file because it is being used by another process." We are using OneDrive for Business and that's where I've been storing my R projects. It was working fine until a couple weeks ago. Turns out that about the same time as my problems started, my company turned on something called "Files On-Demand" -- https://support.office.com/en-gb/article/learn-about-onedrive-files-on-demand-0e6860d3-d9f3-4971-b321-7092438fb38e

And I think that might be part of the problem.  There's a way to set the status of a directory for this on-demand thingy and the default setting is "linked to a cloud file".  But one of the other options  is "Always store on this device."  I created a new directory and set it to that instead of the default.  Then created a new R project in that directory, with a couple dummy source files. Closed it and when I reopened the project, the source files opened up just like they were supposed to. I tried this a couple different ways and consistently found it works. Without that setting, though, the source files don't show up on open. 

I can't seem to get my EXISTING projects to work, even after changing the status of the directory that it's stored in. So I'm guessing I'll have to rebuild those projects. Interestingly, some projects that I haven't opened for three or four weeks (or more) were untouched by this problem. When I opened a couple of them today the source files appeared as they were supposed to. The only projects I'm having trouble with are ones I've worked with over the last couple of weeks.

**Comment by Schumzy** [comment] 2018-06-07 19:13
@dfalty @gtritchie Today it works. I did have a windows 10 update in between though. Hopefully we are back to regular scheduled programming.

**Comment by GeoffLP** [comment] 2018-06-07 20:39
Yes my one works again now, at least for new projects or ones that I open and then close again. Also had a Windows 10 update so hope that fixed the problem

**Comment by gtritchie** [comment] 2018-06-07 21:18
Fingers crossed; we've seen a number of issues with Windows-10 updates recently; hopefully some are problems for more than just RStudio and are being fixed by Microsoft as time goes by!

**Comment by kevinushey** [comment] 2018-07-23 22:34
Given that we haven't heard any new reports on this issue with RStudio v1.2, I think we can close this -- please re-open if you're still having any trouble.

(For the issue with OneDrive with Files On-Demand, I think the only solution will either be for OneDrive to provide a mechanism for selectively synchronizing certain files / folders, so that e.g. `.Rproj.user` within a project folder is not moved to the cloud. We could consider a solution where the `.Rproj.user` folder is configured to use a different path, but that's somewhat out of scope for v1.2)

**Closed by kevinushey** 2018-07-23 22:34 UTC
Labels: bug, repro needed, windows

**Comment by mwm-cbus** [comment] 2020-11-23 16:17
I'm back to something similar with OneDrive, in my case with having apparently random sets of files opening every time I start RStudio.
I'm seeing this as a long history of past workspaces being reopened, because I recently reloaded all my files from OneDrive after some syncing problems on my box.

_I can see in .Rproj.user/####X###/sources/  what looks like the behavior responsible._
that every time I open , it appears to use the most recent folder "s-XXXXXXXX" and renames it
then when I close RStudio, it deletes that folder. 

By opening, deleting the undesired file windows, opening the one I actually want (maybe doesn't matter),  and closing RStudio,  
it worked through all of those apparently old file state folders one-by-one until none were left.
Now it appears to behave properly.

**I think a OneDrive solution would be to synchronize delete, if you are willing.  That is, turn on the option to delete on OneDrive when you delete locally.**
Then the old history files and folders can't come back from remote.

**Comment by mwm-cbus** [comment] 2020-11-23 16:20
An RStudio solution might be to not re-use the past folders,
or perhaps to prompt if if is more than a certain date, such as. . .
"You have last-opened-file history from more than one month ago.  Do you want to use this history now?"   --- if No --- "Would you like to delete this history information?"

**Comment by JLMarcelino** [comment] 2022-09-01 10:06
I'm having the exact same problem. Apparently, at random, my project doesn't load the scripts but keeps the history and environment data. I don't use OneDrive, only Google Drive. Could this be a new issue with Google Drive?

**Comment by pvsundar** [comment] 2024-06-18 05:56
<html>
<body>

setwd("C:/Users/sundar/OneDrive - UW/MY-RESEARCH/HBR-PM-ROLE/JULIUS") Warning message: In readLines(file, skipNul = TRUE, encoding = "bytes") :   cannot open compressed file 'C:/Users/sundar/OneDrive - UW/MY-RESEARCH/HBR-PM-ROLE/renv/library/R-4.3/x86_64-w64-mingw32/rmarkdown-UW1-240-4593853/DESCRIPTION', probable reason 'No such file or directory'
--
 
> | >
>


</body>
</html>
