### ISSUE TITLE
shortcut keys do not work 

### ISSUE THREAD

**Issue by elgabbas** [rstudio/rstudio#4613] opened 2019-04-10 15:17 UTC
Hello,

I found that many shortcut keys do not work in the most recent version of RStudio. These include move focus to *** and show **** under View menu.
![RStudio0](https://user-images.githubusercontent.com/7375051/55891224-795eaf00-5bb4-11e9-9aeb-31317f0db32e.jpg)

Please see also: https://github.com/rstudio/rstudio/issues/4608

**Edit [other issues]:**
- it seems that I can not paste text into the console using right click then paste. It works with the shortcut Ctrl + v. The paste option of the right click only works if the text copied is from the console itself (not always!). If I copy something from a browser or from the R code, it does not work.
- **Select all**: the use of right click on the console and _select all_ also selects the plot (or help, etc.) and previous code & output exist in the console (not only the code written in the console). The use of  Ctrl+a seems to work fine.
![RStudio1](https://user-images.githubusercontent.com/7375051/55893162-07886480-5bb8-11e9-803d-0d12d39e94e7.jpg)
- **Select all**: The same selection (plot and previous code & output exist in the console) occurs if click on select all on the history tab or using Ctrl+a.
- I can not copy any line of code from the history tab

**_System information_**
```
Operating system: Windows 10 Pro
RStudio Edition : Desktop
RStudio version: 1.2.1335
R Version       : 3.5.3
```

Ahmed

**Comment by dfalty** [comment] 2019-04-11 15:48
Thanks for creating a separate ticket @elgabbas. Unfortunately, I can't reproduce the issues in my Win10 environment with 1.2.1335. 

The only thing that I can reproduce is a know limitation with copying history. https://github.com/rstudio/rstudio/issues/3219

Are you running win 10 through a VM or another method that could possibly cause this?

**Comment by elgabbas** [comment] 2019-04-15 12:43
No, I am running a normal windows 10 pro installation. The previous version of RStudio worked perfectly well on the same machine.
I have tried RStudio on another windows 10 PC without these issues.

**Comment by jmcphers** [comment] 2020-04-27 22:19
We haven't been able to reproduce this (and haven't had any reports) in over a year, so closing.

**Closed by jmcphers** 2020-04-27 22:19 UTC
Labels: repro needed
