### ISSUE TITLE
Unable to retrieve python variables from R in Rmarkdown even tho it retrieves just fine when knitting. (reticulate)

### ISSUE THREAD

**Issue by PierreV23** [rstudio/rstudio#14767] opened 2024-05-30 11:04 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.1-748
    OS Version      : Zorin OS 16.3
    R Version       : 4.4.0

### Steps to reproduce the problem
copy code displayed at https://bookdown.org/yihui/rmarkdown-cookbook/eng-python.html (30-05-2024) to a .Rmd file and then try to run the code blocks.

### Describe the problem in detail
`py$x` gives error: `Error: Unable to access object (object is from previous session and is now invalid)`
more info: trying to run `print(py)` returns `<pointer: 0x0>` (i dont know if this is correct)

### Describe the behavior you expected
Expected the `x` variable from python to be printed out from the R block. When knitting R(studio) does succeed retrieving and printing `py$x`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-06-10 13:54
@PierreV23 Thank you for raising this! I'm seeing inconsistent results
- Sometimes everything works properly.
- Sometimes I get the following
```
> py$x
NULL
> py$y <- head(cars)
Error in `$<-.python.builtin.object`(`*tmp*`, y, value = list(speed = c(4,  : 
  Unable to assign value (object reference is NULL)
```

There might be other results. This occurs in both RStudio Desktop 2023.12.1+402 and 2024.07.0-daily+188.pro20.

**Comment by PierreV23** [comment] 2024-06-12 14:59
Mentioned code used to work on my windows install of rstudio. 
Today rstudio asked me to update so i did, thought i'd try to run the code and it started throwing the same errors as on my linux laptop.
So theres defenitely a bug since a couple of months.

**Comment by kevinushey** [comment] 2024-10-11 20:57
I'm not able to reproduce. The error:

> Error: Unable to access object (object is from previous session and is now invalid)

most likely implies you restarted the R session, and unfortunately RStudio does not support serialization and deserialization of Python objects the same way as R objects.

**Comment by ronblum** [comment] 2024-10-17 17:13
Closing. If you have any updates, please let us know.

**Closed by ronblum** 2024-10-17 17:13 UTC
Labels: bug, python, r markdown, evaluate effort 🕐🗳🔎
