### ISSUE TITLE
Jump to Matching Bracket - Display doesn't follow cursor

### ISSUE THREAD

**Issue by dcomtois** [rstudio/rstudio#4674] opened 2019-04-19 19:33 UTC
I've noticed that when I use CTRL-P to "Jump to Marching Bracket", the cursor does shift to right place in the source, but the display does not follow the cursor. Instead, it stays where it is and I need to move the cursor (left or right arrow for instance) in order for the display to actually jump to the active line.

I mainly use the Windows version, but the same behavior was observed in the very latest build for Ubuntu (ver. 1.3.124).

**Comment by kevinushey** [comment] 2019-04-19 20:30
This looks like a regression in v1.2; marking for v1.2-patch.

**Comment by kevinushey** [comment] 2019-05-23 21:51
Fixed via https://github.com/rstudio/rstudio/pull/4676.

**Closed by kevinushey** 2019-05-23 21:51 UTC
Labels: bug, reproducible
