### ISSUE TITLE
F1 doesn't show help and throws error on dataset autocomplete

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2356] opened 2018-03-08 21:23 UTC
### System details

    RStudio Edition : Server and Desktop
    RStudio Version : 1.1.383, 1.1.423, 1.1.442
    OS Version      : Mac, Windows, and Linux variants
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Type `iris` at the console, and wait for help topic autocompletions to appear.
2. Select an autocompletion with the arrow keys, e.g. `iris`
3. Press F1 to see help on the dataset.

### Describe the problem in detail

No help appears, and the following error message is displayed at the console:

> Error in find.package(if (is.null(package)) loadedNamespaces() else package,  : 
  there is no package called ‘package:datasets’

(Clicked F1 multiple times for screenshot to show error + autocompletion)

<img width="642" alt="iris_no_help" src="https://user-images.githubusercontent.com/31009952/37176924-d9ebe7a0-22eb-11e8-81f1-3b18075ae1b7.png">

### Describe the behavior you expected

Help on the dataset, `iris`, should appear in the Help pane, with no error message.

Cf. #2261 and #2348.

**Comment by jmcphers** [comment] 2018-03-08 22:14
@kevinushey Does it look like we need to extend the fix in #2261 in some way, or is this a different bug?

**Comment by kevinushey** [comment] 2018-03-08 22:18
I think this may be a different issue -- I'll take a look.

**Comment by kevinushey** [comment] 2018-03-08 22:49
I'm surprised to find out that this actually reproduces back in RStudio v1.0. I guess users don't press <kbd>F1</kbd> when the help menu is showing very often :-)

**Comment by kevinushey** [comment] 2018-03-08 22:52
Should be fixed with https://github.com/rstudio/rstudio/commit/1e5e7dc0b1c7395d35fd376ddfb86e2c6215dce8. It looks like we only trimmed the `package:` prefix in certain code paths; we should be doing that universally.

**Comment by jmcphers** [comment] 2018-03-08 23:26
Okay, thanks for jumping on that! Given that it is not a regression in 1.1 and hasn't ever been reported before to the best of my knowledge, I don't intend to backport it (let me know if you disagree).

**Comment by jmcphers** [comment] 2019-12-06 05:07
Closing since we appear to have fixed this a couple of years ago.

**Closed** 2019-12-06 05:07 UTC
Labels: bug, reproducible
