### ISSUE TITLE
"Run All Chunks Above" skips `eval=FALSE` but not `eval=var` when variable is `FALSE`

### ISSUE THREAD

**Issue by kiernann** [rstudio/rstudio#9808] opened 2021-09-02 20:43 UTC
When knitting a document, you can use variables in the chunk options.

A chunk like this is ignored both when knitting and when using the "Run All Chunks Above" command.

```` markdown
```{r eval=FALSE}
summary(cars)
```
````

But if the user defines `var` as a logical value, like so:

```r
var <- FALSE
```

Then the chunk below is _not_ run when knitting but _is_ run using the "All Above" shortcut.

```` markdown
```{r eval=var}
summary(cars)
```
````

**Comment by cderv** [comment] 2021-09-03 08:27
Thanks for the report ! 

I think this is a known issue and a duplicate of https://github.com/rstudio/rstudio/issues/6675

**Closed** 2021-09-03 14:43 UTC
