### ISSUE TITLE
using Shift + Delete (backspace) behaves oddly in terminal

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9249] opened 2021-04-20 23:49 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.dev
    OS Version      : macOS 11.2.3
    R Version       : 4.0.5

### Steps to reproduce the problem

Create a new bash terminal, type some text (e.g. `echo hello`), then start deleting text with Shift + Backspace. Then press enter.

### Describe the problem in detail

Two characters are removed from view, but 'hell' is printed instead.

https://user-images.githubusercontent.com/1976582/115476491-d4412d00-a1f6-11eb-9f6e-76220c4596f5.mov

### Describe the behavior you expected

Only a single character should be removed from view.

### Notes

This happens most often when typing capital letters (e.g. `$THE_NAME_OF_A_VARIABLE`) and then pressing backspace to delete after making a typo in that variable name.

`zsh` has a similar but weird behavior, where some characters are passed over but not deleted.

https://user-images.githubusercontent.com/1976582/115476645-26824e00-a1f7-11eb-9fa5-c645c1dd0a2f.mov

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2021-04-22 23:15
Marking as regression since problem started with v1.4 (both wax-begonia and tiger-daylily) did not repro with 1.1, 1.2, or 1.3.

**Comment by gtritchie** [comment] 2021-04-22 23:42
Research note: problem goes away if you turn off "Local terminal echo".

Problem does not happen on Windows (which currently doesn't support 'Local terminal echo').

**Comment by gtritchie** [comment] 2021-04-29 22:13
Started happening in build 1.4.542 (2020-07-06), which contained this change: #7275

**Comment by kevinushey** [comment] 2021-06-02 20:02
As a note, I've seen this repeatedly in customer calls (where the command that appeared visible in the terminal differed from the command that was eventually executed). I think this issue is a bit more pervasive than we might have initially suspected.

**Comment by jmcphers** [comment] 2021-06-02 20:51
I've also seen it a bunch, and I never use Shift + Backspace/Delete.

**Comment by gtritchie** [comment] 2021-06-14 03:00
Did some poking at this, and the problem is definitely related to the local-echo feature (and possibly also related to the newer xterm's more asynchronous nature where sending text to be rendered has a completion callback that we don't currently use).

The local echo code is quite sensitive to specific output patterns, and a maintenance headache (and I wrote it!). Be nice to eliminate, honestly, rather than continue battling it, but it does make the terminal feel more responsive, especially on Server.

**Comment by kevinushey** [comment] 2021-06-14 18:43
IMHO I think the responsiveness of the terminal without local echo is just unfortunately not good enough; local echo is fairly essential (especially for RSP + higher latency environments).

**Comment by kevinushey** [comment] 2021-06-14 18:45
I'm not familiar with how local echo is currently implemented, but is there any hope of maintaining two "parallel" terminal input streams; one being the "truth" via the regular RPC implementation, and one being the "local echo" version? And if these go out of sync, we can just periodically sync back the "truth" to the visible console input buffer? So that even if local echo is temporarily "wrong", we can still recover after syncing back.

**Comment by gtritchie** [comment] 2021-06-14 19:30
I agree, I was just whining.

**Comment by gtritchie** [comment] 2021-06-14 19:53
> is there any hope of maintaining two "parallel" terminal input streams; one being the "truth" via the regular RPC implementation, and one being the "local echo" version?

Perhaps, I'll think that through.

**Comment by rich-rstudio** [comment] 2021-08-02 16:05
verified on Daily Version 2021-08.0.289

**Closed by rich-rstudio** 2021-08-02 16:05 UTC
Labels: bug, regression, terminal, test
