### ISSUE TITLE
Remove libpq dependency in RStudio Desktop

### ISSUE THREAD

**Issue by 2011** [rstudio/rstudio#8968] opened 2021-02-13 10:46 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : Linux 5.4.80 #1 SMP GenuineIntel GNU/Linux
    R Version       : 3.4.1

### Steps to reproduce the problem

Version 1.3.1093 did not dynamically link to libpq (from PostgreSQL), but 1.4.1103 does.

One can verify this by simply running ldd /path/to/rstudio.

### Describe the problem in detail

The Release Notes at:

https://rstudio.com/products/rstudio/release-notes/

mention that RStudio Server Pro now requires a Postgres database, but says nothing about RStudio Desktop (and lacks any explanation why the Desktop version would require a database).

### Describe the behavior you expected

I would expect database connectivity to remain in the odbc package, and not pushed into the basic desktop. I strongly object to requiring something not found in a typical desktop setup, and request that if this dependency remains, you provide the necessary libraries with the RStudio Desktop installation (as you do with the Qt libraries and icu - both of which most Linux desktop machines already have).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-02-19 15:03
@2011 Thank you for raising this! I'll mark it for review as part of our ongoing development of RStudio.

@kfeinauer Could this have something to do with introducing the internal database?

**Comment by kfeinauer** [comment] 2021-02-19 15:32
@ronblum Yes, this came about when adding database support. The dependency should not be necessary on the desktop, but due to how we deal with dependencies a shared component that depends on this library is pulled in by both server and desktop. This requirement could be removed in a future release.

**Comment by ronblum** [comment] 2021-02-19 18:46
@kgartland-rstudio Thanks! I'll switch this from a bug to an enhancement request.

**Comment by mcg1969** [comment] 2021-05-16 15:46
I'd like to suggest this is, in fact, something closer to a bug, and the previous label should be restored.

I understand why it was added—RStudio Server 1.4 uses a database in order to manage internal data. However, the documentation shows two options: SQLite and Postgres, with SQLite is the default. Requring a Postgres dependency _when it is not even being used_ poses a significant installation burden in many contexts.

**Comment by ccr-billing** [comment] 2021-12-16 21:31
I'm attempting to install rstudio-2021.09.1-372 and am using R 4.1.0.  Is there really no way to get around the postgres requirement?  We support a shared high performance computing environment and do not install databases.  Is there a way to install just the libraries necessary to get the rstudio install to complete?  Any advice is greatly appreciated!

**Comment by dsajdak** [comment] 2021-12-16 21:32
I'm attempting to install rstudio-2021.09.1-372 and am using R 4.1.0. Is there really no way to get around the postgres requirement? We support a shared high performance computing environment and do not install databases. Is there a way to install just the libraries necessary to get the rstudio install to complete? Any advice is greatly appreciated!

**Comment by mikebessuille** [comment] 2021-12-20 18:32
@dsajdak are you installing desktop, or server?  What platform?  I'm not understanding why this is a concern; you shouldn't have to install a database to get it to work.

**Comment by ronblum** [comment] 2021-12-20 18:55
Note: I believe we're requiring an installation of `libpq5`, but not all of PostgreSQL, when installing RStudio Desktop in a Linux environment.

**Comment by 2011** [comment] 2021-12-21 17:49
> Note: I believe we're requiring an installation of `libpq5`, but not all of PostgreSQL, when installing RStudio Desktop in a Linux environment.

WHY?  I have used RStudio desktop for years, and it never had this requirement before version 1.4.

1. RStudio desktop should not require theis libraries.
2. Database connectivity should remain in the odbc package.
3. Typical desktop installations don't have theis library (including mine - I would have to compile the entire PostgreSQL to upgrade to RStudio 1.4).
4. If you really feel that RStudio desktop absolutely **has** to have libpq, then why don't you provide it in the package? The installation package includes libraries for Qt and icu, which virtually every Linux desktop has. It makes absolutely no sense whatsoever to include those libraries with RStudio, yet demand users produce their own libpq library.

**Comment by ronblum** [comment] 2021-12-21 19:21
@2011 I was merely clarifying the issue.

**Comment by mcg1969** [comment] 2021-12-21 19:22
And thanks to both of you for that!

**Comment by ronblum** [comment] 2021-12-21 19:34
@mcg1969 Darn it, I thought I had switched this back to a bug back in May in response to your comment! Changing now.

**Comment by kfeinauer** [comment] 2021-12-21 19:38
The original thought in making `libpq` required is that it would be available to easily install via the system package manager when installing the RStudio `deb`/`rpm`. Clearly that is not always the case, and I apologize for the inconvenience this has caused you.

The `libpq` library has quite a few dependencies itself, so I think bundling them all and shipping them with RStudio is error-prone. 

I think we should allow for dynamic loading of the `libpq` library on Linux. SOCI (the database manager we are using) has some support for this (http://soci.sourceforge.net/doc/release/4.0/connections/). Otherwise we'd need to build `libpq` on all platforms and statically link to it, which could be tricky.

**Comment by dsajdak** [comment] 2021-12-21 19:59
@mikebessuille 
> @dsajdak are you installing desktop, or server? What platform? I'm not understanding why this is a concern; you shouldn't have to install a database to get it to work.

I'm attempting to install desktop version 2021.09.1+372, for CentOS 7, from source.  We install everything to a shared mounted filesystem and can not install using OS packages.  I spent 2 days getting all the dependencies installed in the shared filesystem only to have the rstudio 'cmake' fail with:
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/shared/directory/.../PQ_LIB
linked by target "rstudio-core-tests" in directory /shared/directory/.../rstudio-2021.09.1-372/src/cpp/core
    linked by target "rstudio-core" in directory/shared/directory/.../rstudio-2021.09.1-372/src/cpp/core
SOCI_POSTGRESQL_LIB
    linked by target "rstudio-core-tests" in directory/shared/directory/.../rstudio-2021.09.1-372/src/cpp/core
    linked by target "rstudio-core" in directory /shared/directory/.../rstudio-2021.09.1-372/src/cpp/core
`
I was hoping someone would have a suggestion as to how to get around this without a full Postgres install.

**Comment by kfeinauer** [comment] 2021-12-21 20:35
@dsajdak You need to have the `libpq` and `libsoci_*` files under your shared directory. Then you need to inform cmake where to look by specifying the `CMAKE_LIBRARY_PATH` environment variable. 

See https://cmake.org/cmake/help/latest/command/find_library.html and https://cmake.org/cmake/help/latest/variable/CMAKE_LIBRARY_PATH.html#variable:CMAKE_LIBRARY_PATH for more information on how this is found. 

We find this library here in the CMake file: https://github.com/rstudio/rstudio-pro/blob/3ae8a14e002eb8731367b204bb4e70e6bb93083d/src/cpp/CMakeLists.txt#L442-L456

You can use our `install-soci` script to build SOCI. It's designed to run at certain paths that we use for our builds, so it might not work out of the box for you. https://github.com/rstudio/rstudio-pro/blob/main/dependencies/common/install-soci. Particularly, you may need to specify the path to `libpq` to get it to build correctly. This can be done by adding it to the `CMAKE_LIBRARY_PATH` here https://github.com/rstudio/rstudio-pro/blob/3ae8a14e002eb8731367b204bb4e70e6bb93083d/dependencies/common/install-soci#L83.

**Comment by dsajdak** [comment] 2021-12-21 20:41
@kfeinauer Thank you!  I'm unable to get to the rstudio links you shared.  Perhaps they're in a private repo?  I am currently testing this with installing the postgres-devel and soci-postgresql-devel rpms on my build host.  If these libraries/packages are not required to run rstudio desktop, this should work.  If they are, then I'd rather your suggested method.

**Comment by kfeinauer** [comment] 2021-12-21 20:50
@dsajdak You'll need to build SOCI from source because we statically link it, so you need `.a` files instead of the `.so` that are shipped by the packages. As for `libpq`, you can get it from `postgres-devel` but you should also be able to get it from `libpq5-devel` (much smaller package).

Sorry about the visibility of the links. I have edited my comment to fix them.

**Comment by 2011** [comment] 2021-12-24 04:14
> The `libpq` library has quite a few dependencies itself, so I think bundling them all and shipping them with RStudio is error-prone.

Hard for me to believe that bundling those exceeds the complexity of bundling `libQt5WebEngineCore`. :)

**Comment by 2011** [comment] 2022-02-23 08:13
@MariaSemple I will protest against the changes you made on 0110. I filed the bug, and (for me) it has absolutely nothing to do with bulding RStudio from source. I can't run the packages you supply because of the (new) dependency on libpq. I do not view fixing this as an enhancement - it obviously represents a bug (something working before that no longer works).

**Comment by mcg1969** [comment] 2022-02-23 15:34
I agree, @2011

@MariaSemple , I understand that the RStudio maintainers may have simply concluded that they are going to be unable to address this issue to the satisfaction of its reporters. I have plenty of experience disappointing my users, too :-) it happens! 

But I think that preserving the historical record is important. This was never about the need to build from source. I think the proper course of action is to revert the title of this issue but to mark it as a "wontfix" if indeed the RStudio team has decided it is not feasible to solve

Thank you all!

**Comment by MariaSemple** [comment] 2022-02-23 21:28
I believe I misread some of the context of this issue, apologies for the confusion. I will change the title to "Remove libpq dependency in RStudio Desktop"; however, I will leave the tags as they currently are. While I understand that it is frustrating to not be able to use the newer version because you are unable to install the new dependency, the new dependency is not a bug as the addition of the dependency was intentional. To remove the dependency now would be considered an enhancement.

`libpq` was introduced as a dependency due to RStudio Server requiring it. RStudio Desktop and RStudio Server share much of the same code, and as a result the dependency was introduced on both sides. The dependency is not related to the Connection Pane feature or the ODBC Drivers that it uses. It is non-trivial to remove the dependency and introduces some regression risk. 

After discussing this with @kfeinauer I propose the following potential solution:
* Always explicitly link against SQLite libraries (which are used by all versions of the product).
* Never explicitly link against PostgreSQL libraries - instead use SOCI's feature that allows for dynamic loading of DB libraries through a call to `dlopen`.

If we choose to go this route, we will need to ensure that there is a very clear error message if `libpq` cannot be found, and that it occurs very early in start up of RStudio Server.

**Comment by 2011** [comment] 2022-02-23 22:30
Just to emphasize (and perhaps clarify) some things, I don't consider this a "documentation" issue at all. RStudio simply will not start without the missing library (with a message that it can't find libpq). I don't see any need for additional documentation on the matter.

I do want to quote @kfeinauer (20210219):

> The dependency should not be necessary on the desktop, but due to how we deal with dependencies a shared component that depends on this library is pulled in by both server and desktop. This requirement could be removed in a future release.

To repeat the points I made on 20211221, RStudio already comes bundled with more than 25 libraries (Qt and icu), most of them completely superfluous. Virtually every linux desktop has those libraries already, but RStudio supplies additional copies of them (I won't condemn that, because bundling versions known to work does add some value at the cost of disk space and memory use). But the one library many desktops do not have installed by default (libpq) gets left out. No offense to you (I doubt you personally made the associated decisions), but I would have have to place this in the top two software engineering idiocies that I have seen over the past five years.

If desktop users **have** to have libpq (and I imagine that the vast majority of them would find themselves content with SQLite), then bundle it (or bundle a stub library that allows RStudio to start, but then doesn't allow the choice of PostgreSQL as a database without libpq. I just don't understand the thinking on this (other than "we want to make things more difficult for our users").

**Comment by mikebessuille** [comment] 2022-02-25 14:57
Your perspective is much appreciated; please maintain a professional tone.

Coding decisions including dependency decisions are not made frivolously.  Sometimes, design choices are made to minimize development cost, maximize maintainability, reduce testing cost, or to have common code between the many versions of our product (server, desktop, pro, open source).  As such, this issue is not a bug.  Nor is it an "idiotic" design choice.  We will certainly consider improving it such that it doesn't affect the case you describe, keeping in mind that most of our users are unaffected by this, as they install the IDE from installers (which take care of the appropriate dependencies), rather than by building from source or by unpacking a tarball and manually installing.

**Comment by mcg1969** [comment] 2022-02-25 15:05
I appreciate the moderation. While I do agree they should be fixed, it is far from the worst thing I have encountered :-) in fact, I've done far worse myself!

**Closed** 2023-09-25 11:41 UTC
Labels: enhancement, internal database

**Comment by ronblum** [comment] 2023-10-20 20:26
This is resolved in [RStudio Desktop 2023.12.0-daily+212](https://dailies.rstudio.com/) for an upcoming release, covered in issue #13676. Please note that the dailies are meant for testing purposes only, not production.
