### ISSUE TITLE
Very sketchy error with access to repository without TLS >1.0 enabled

### ISSUE THREAD

**Issue by mirh** [rstudio/rstudio#8649] opened 2020-12-21 18:45 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      : Windows 7
    R Version       : 4.0.3

### Steps to reproduce the problem
0. Make sure you have a fresh RS profile (when cran_mirror gets set in `rstudio-prefs.json`, plain http is preferred)
1. Have TLS 1.1, 1.2 and 1.3 disabled in the [internet options](https://warwick.ac.uk/services/its/servicessupport/web/sign-on/help/tls1-eol/ie)
2. Try to install any package

[Another example](https://community.rstudio.com/t/install-packages-unable-to-access-index-for-repository-try-disabling-secure-download-method-for-http/16578), and this is at least one cause for #3726

### Describe the problem in detail
I originally thought connection to CRAN was failing because I was missing the [right root certificate](https://web.archive.org/web/20161119021416/https://hexatomium.github.io/2016/01/21/amazon-roots/) they are using (which I instead found on another functioning system), but while tinkering with windows updates to get it somehow added to the list of accepted Intermediate Certification Authority, I figured out IE 11 fixed it. 
But it didn't touch any chain of trust, just TLS as I hinted in the opening. 

### Describe the behavior you expected
[Check for it](https://johnpenford.wordpress.com/2015/03/16/configuring-internet-explorers-secure-protocols/) (or idk if the http error that is returned couldn't be further parsed), and either use the [built-in fallback](https://github.com/rstudio/rstudio/commit/bc7cdf78f9676f7acc1c56a8996925acb76ced87) you already have, or anyway at least give the user a more sensible warning. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-12-21 20:45
@mirh Thank you for raising this! We'll review the issue as we continue development of RStudio.

Also, please note that the upcoming version of RStudio Desktop, 1.4 Wax Begonia, will not be supported on Windows 7, since Microsoft dropped support for it in January 2020. That won't affect the existing 1.3 release, but any fixes won't be backported.

**Comment by mirh** [comment] 2020-12-21 21:22
Microsoft dropping support doesn't mean any of the existing toolsets will stop working for you?
If those are actually being a limitation, I guess like that's already another thing and legit, but this doesn't really sound good just stated this way. 
It's not a secret that that a lot of people in poorer countries cannot afford newer pcs, and you should at least weigh them (let alone those in richer ones with an IT department that can't be bothered to update the laboratory computers)

Then, with respect to this bug, it's kind of an edge case of the edge case (if I hadn't been using an unupdated throwaway VM to bisect another bug, I would never have caught it). 
Though it does happen, I vaguely guess it could also technically happen in linux, and you are already kind of handling a similar problem.

**Comment by ronblum** [comment] 2020-12-22 19:39
Hi @mirh—we work hard to test our products on many platforms including latest releases and older software.  However, it is not feasible for us to maintain our software on unsupported platforms. Microsoft ended support of Windows 7 on January 14, 2020, so we can no longer build our software on that platform. We must concentrate our efforts on the newer, supported versions of Windows to take advantage of improvements or critical bug fixes to the operating system and related dependencies. There really is no reasonable way for us to move forward while supporting very old platforms at the same time.

We value all our users and want them to be able to use our software on the platforms they have, so we do offer a way to download older versions of our software, including unsupported versions for old operating systems: https://rstudio.com/products/rstudio/older-versions/

**Comment by mirh** [comment] 2020-12-23 01:39
>  so we can no longer build our software on that platform

I'm not a professional developer, but that's not really how it works. Anyway, your circus, your monkeys I guess, better if I keep in-topic.

**Comment by mirh** [comment] 2021-06-21 15:29
Yes this is still a thing even in 1.4.1717

**Comment by mirh** [comment] 2021-12-28 15:25
Still the same in 2021.09.1 (build 372)
To reiterate again, this is also a W10+ problem if for whatever whimsical reason you have TLS settings changed.

**Comment by ronblum** [comment] 2021-12-30 15:13
@mirh Thanks! I'll mark these for re-review, to see if there's a reason TLS 1.0 is intentionally no longer supported, or if this is an unintended bug.

Note: Marking as a regression since it was a regression when first raised.

**Comment by mirh** [comment] 2022-01-01 15:18
TLS 1.0 not being supported anymore seems just normal practice, and it should very much be a [server](https://www.cdn77.com/tls-test/result?domain=https%3A%2F%2Fcran.rstudio.com%2F) thing. 
So it's not really a regression in R or Rstudio. 

I'm just saying that the "failing experience" could be better, if not any because you already implemented a "catching mechanism" that could/should address this, and oddly enough `use_internet2:false` doesn't seem to make a difference either.

**Comment by mikebessuille** [comment] 2022-01-03 18:12
This will only happen very rarely, and if the user has explicitly disabled newer TLS versions.  Yes the error message could be improved, but with so many urgent issues to work on, I don't see us getting to this in the near term.  As such, I'm closing this issue.

**Closed by mikebessuille** 2022-01-03 18:12 UTC
Labels: bug, reproducible, regression

**Comment by mirh** [comment] 2022-01-03 23:42
Then just have a low-priority label, duh?
Getting closed this way seems worse than stale issues.

**Comment by mikebessuille** [comment] 2022-01-04 13:30
@mirh I hear you.  Unfortunately, we have thousands of issues in our backlog and that becomes unwieldy to sort through and prioritize.  Consider that we might address a couple hundred backlog issues in a year; so only the very most urgent issues are getting addressed.  Something like this issue - which affects a tiny portion of our user base, and has a clear workaround, is simply not going to get addressed for probably years.  At that point, it's more effective to close it.  This is a standard industry practice; for example, https://github.com/microsoft/vscode/wiki/Issues-Triaging.  The information is still here in a closed ticket so in the future if similar issues arise, we'll see it in a search; it's not lost.  In any case, we greatly appreciate you taking the time to identify issues for us to consider.
