### ISSUE TITLE
Python plotting causes second RStudio session to open, causing a crash

### ISSUE THREAD

**Issue by chriscardillo** [rstudio/rstudio#7893] opened 2020-09-28 02:44 UTC
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.875
    OS Version      : Mac OS 10.15.2
    R Version       : 3.6.2 (also tried on 4.0.2)

### Steps to reproduce the problem

With reticulate and python packages installed...

```python
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

my_df = pd.DataFrame({"col1": [1, 2, 3], "col2": [4, 5, 6]})

sns.pointplot(x='col1', y='col2', data=my_df)
plt.show()
```

### Describe the problem in detail

I am running each line individually in a .py file, using Command + Enter. When I get to `sns.pointplot`, a second RStudio session opens up, and the icon remains bouncing until I run `plt.show()`, at which point a new window with the plot opens up. The second RStudio session shows up as 'Application Not Responding', and when I force quit this second session, it causes my initial session to crash.

### Describe the behavior you expected

I expected the plotting behavior that occurs in RStudio 1.3.1093, where the plot shows up in my plot pane.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by chriscardillo** [comment] 2020-10-01 00:08
Hi - I just wanted to add that I just downloaded [the preview release (v1.4.869-4)](https://rstudio.com/products/rstudio/download/preview/) and I am still encountering the same issue.

**Comment by ismayc** [comment] 2020-10-01 22:41
I am also seeing the same issue. Here's a Loom: https://www.loom.com/share/cadb26199d6345ba8af2887101220089

**Comment by kevinushey** [comment] 2020-10-06 23:37
This appears to be resolved in the latest [daily builds](https://dailies.rstudio.com) -- when I run the provided code, I see the plot displayed in the Plots pane.

<img width="956" alt="Screen Shot 2020-10-06 at 4 36 49 PM" src="https://user-images.githubusercontent.com/1976582/95271204-2342ea00-07f2-11eb-9114-87ef72d3388d.png">

If you aren't seeing this behavior in the latest dailies, please feel free to re-open this issue and please provide any other context that could be useful (e.g. the version of Python used; the Python modules in use; etc)

**Comment by ismayc** [comment] 2020-10-07 00:10
I'm still getting the same error. My `reticulate::py_config()` is below:

```
> py_config()
python:         /Users/chester/Library/r-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/chester/Library/r-miniconda/envs/r-reticulate/lib/libpython3.6m.dylib
pythonhome:     /Users/chester/Library/r-miniconda/envs/r-reticulate:/Users/chester/Library/r-miniconda/envs/r-reticulate
version:        3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:19:23)  [GCC Clang 10.0.1 ]
numpy:          /Users/chester/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.1
```

**Comment by chriscardillo** [comment] 2020-10-07 00:12
Also having trouble still:

```
> reticulate::py_config()
python:         /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
libpython:      /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/libpython3.6.dylib
pythonhome:     /Library/Frameworks/Python.framework/Versions/3.6:/Library/Frameworks/Python.framework/Versions/3.6
version:        3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
numpy:          /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy
numpy_version:  1.19.1
```

**Comment by kevinushey** [comment] 2020-10-07 05:22
Sorry! It looks like this fix requires the development version of `reticulate` -- can you install it with:

```
remotes::install_github("rstudio/reticulate")
```

and then give it another try?

**Comment by chriscardillo** [comment] 2020-10-07 12:01
Confirming plotting works as expected with the development version of `reticulate` and daily RStudio v1.4.909. This is great.

I notice one other small issue. Please let me know if I should put this in a separate ticket.

If you open up a fresh RStudio session, with a .py file in the source editor, and you run the first line of your .py file with CMD + Enter (in the example we've been using, `import pandas as pd`), that `pd` won't show up in the environment pane. `pandas` as `pd` is still available to use (and autocomplete on `pd` still works like a charm), but the variable itself does not show up in the environment pane under this specific condition.

**Comment by kevinushey** [comment] 2020-10-07 16:17
Glad to hear that fixed the issue! We'll be planning to submit a new version of `reticulate` to CRAN soon as well.

> If you open up a fresh RStudio session, with a .py file in the source editor, and you run the first line of your .py file with CMD + Enter (in the example we've been using, import pandas as pd), that pd won't show up in the environment pane. pandas as pd is still available to use (and autocomplete on pd still works like a charm), but the variable itself does not show up in the environment pane under this specific condition.

Please file a new issue -- thanks!

**Comment by kevinushey** [comment] 2020-10-14 20:34
This issue will ultimately be resolved when `reticulate` is updated, which is being tracked here: https://github.com/rstudio/rstudio/issues/7618

I'm going to close this as it's more-or-less a duplicate of that issue.

**Closed by kevinushey** 2020-10-14 20:34 UTC
Labels: backlog, bug, python

**Comment by melissa-barca** [comment] 2020-11-09 22:01
Verified this works with the dev version of `reticulate` and 1.4.1013.

**Comment by mbac** [comment] 2021-03-04 21:24
Hi,

I'm having the *exact* same issue, but running RStudio 1.4.1106 and `reticulate` 1.18 from CRAN. Please advise…

**Comment by RickyEsclapon** [comment] 2021-08-20 14:47
This is still happening on my end. I updated `reticulate` with the development version, and also upgraded RStudio to the last daily build, but it did not fix my issue. I'm on `reticulate` 1.20-9002, and RStudio version 2021-08.0 Build 324. I'm on the 2020 M1 Macbook Air (Big Sur version 11.2.3).

When making a Python chart it tries to opens a new RStudio window but it's not able to, and when I force quit the new window to close it shuts down my main RStudio session (R Session Aborted pop-up).

Python info:
```
> reticulate::py_config()
python:         /usr/local/bin/python3
libpython:      /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.dylib
pythonhome:     /Library/Frameworks/Python.framework/Versions/3.9:/Library/Frameworks/Python.framework/Versions/3.9
version:        3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52)  [Clang 6.0 (clang-600.0.57)]
numpy:          /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy
numpy_version:  1.21.2
```


More details on RStudio version:
```
RStudio 2021-08.0.324-0 "Ghost Orchid" Daily (cc1e34cfbcb83289eecbb724f74ca3f015776a5f, 2021-08-18) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
```
