### ISSUE TITLE
Copy + paste not available in RStudio terminal when using cat or vi open the file

### ISSUE THREAD

**Issue by analeighgui** [rstudio/rstudio#1960] opened 2018-01-12 17:24 UTC
I'm using the terminal in Rstudio Version 1.1.383. I use the below code (zcat and vi) to open a gz file and want to copy + paste with short cut Cmd + C & Cmd + V. I found out I got some random text instead.

`zcat <file> | less`
`vi <file>`

I also tried with mouse click and short cut shift+Cmd+C, but it didn't work. 
I tested in the mac terminal. I don't have the issue anymore.

**Comment by ronblum** [comment] 2018-01-12 21:00
@analeighgui I believe I can reproduce the problem. Can you check whether the text that's getting copied is from the terminal buffer, instead of what's in the open program? 

To reproduce:
1. Open new terminal
2. `ls -la`
3.  `vi <file>`
4. Select area
5. Copy using `Cmd-C`
6. Paste in another program using `Cmd-V`

The text you see in the paste is the equivalent region of the directory listing in the buffer. 

This is reproducible using terminal on MacOS Desktop 1.1.412 and RStudio Server Pro 1.1.412 on Ubuntu 16.04 using Chrome.

**Comment by analeighgui** [comment] 2018-01-13 11:42
@ronblum The text that's getting copied is in the open program showed the problem. Copying the buffer is fine.

This is produced on MacOS 10.13.2 and RStudio 1.1.383.

**Comment by warnes** [comment] 2019-05-24 15:54
The copied text is the contents of the selected lines terminal buffer history, rather than the currently visible text.

**Comment by gtritchie** [comment] 2019-09-04 17:13
To clarify, the scenario was:

- generate some output in normal terminal buffer (e.g. `ls -l`)
- run an ncurses (full-screen) terminal program such as `vim` or `less`, which switches the terminal to the alternate buffer
- select with mouse and copy
- the copied text was from the normal buffer (e.g. the output of `ls -l`), not the visible alternate buffer (`vim`)

**Comment by gtritchie** [comment] 2019-09-04 17:14
Fixed by xterm3 upgrade. Tested on build 1.3.421 on macOS.
https://github.com/rstudio/rstudio/pull/5282

**Closed by gtritchie** 2019-09-04 17:14 UTC
Labels: bug, reproducible, terminal

**Comment by lcolladotor** [comment] 2019-12-11 16:48
Hi,

I just noticed this same issue using RStudio Version 1.2.5019 (latest release from [here](https://rstudio.com/products/rstudio/download/#download)) on macOS Version 10.14.6 (18G95). This also happens with RStudio Version 1.2.5033 (latest preview from [here](https://rstudio.com/products/rstudio/download/preview/)).

Googling "RStudio 1.3" I found https://dailies.rstudio.com/rstudio/oss/mac/ version 1.3.659 (latest as of 2019-12-11 from https://www.github.com/rstudio/rstudio/commits/14f3dbf4568dd7595b95a278c3cdc5ec1052d090) where indeed the issue is resolved. Though I see the warning `Daily builds are intended for testing purposes, and are not recommended for general use.`. 

I'm just sharing this info in case you are also running into this issue with RStudio 1.2. 

Best,
Leo
