### ISSUE TITLE
Shiny app reload clears out running app and does not reload it

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4527] opened 2019-03-27 19:34 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1332-2 & 1.2.1330-2
    OS Version      : Red Hat 7.6 & Ubuntu 18.04
    R Version       : 3.5.1 & 3.5.3

### Steps to reproduce the problem

1. Create a new Shiny app: File -> New File -> Shiny Web App
2. Run the app in a window or the Viewer pane
3. Click on "Reload App"
    - The app goes away and doesn't get replaced by a new app (window closes or View pane clears out)
    - The button now says "Run App"
4. Click on "Run App" multiple times
    - `runApp()` commands get displayed in the console, even though listening is still going on (according to the console)
5. Stop the app by clicking on one of the stop signs
    - An error appears under each of the `runApp()` commands.

### Describe the problem in detail

The Shiny app goes away and doesn't reload. When the app is stopped, errors appear in the console, one for each click on the replacement "Run App" button in step (4).

```
> runApp('shiny_wont_reload')

Listening on http://127.0.0.1:6988


> runApp()
Error in shinyAppDir(x) : App dir must contain either app.R or server.R.
> runApp()
Error in shinyAppDir(x) : App dir must contain either app.R or server.R.
> runApp()
Error in shinyAppDir(x) : App dir must contain either app.R or server.R.
>
```

### Describe the behavior you expected

The app should reload.

Note: this isn't an issue on Desktop, both MacOS and Ubuntu.

**Comment by gtritchie** [comment] 2019-03-27 21:22
I repro'd on a clean Ubuntu 18.04 with 1.2.1330-2 (open source) installed.

**Comment by gtritchie** [comment] 2019-03-27 21:49
I was able to repro on a clean Bionic machine using 1.1.463, so this doesn't seem to be an IDE-side regression. Shiny side?

**Comment by jmcphers** [comment] 2019-03-27 21:52
This workflow requires us to do some cross-window coordination (and open/closing) with the browser, so a third possibility is that newer browsers have a stricter security policy.

**Comment by jmcphers** [comment] 2019-03-27 22:53
Moving this to patch since it's not a regression (but still deserves attention soon)

**Comment by jmcphers** [comment] 2019-04-01 17:16
Hmmm. I was not able to reproduce this with Shiny 1.2.0 on RStudio Server, both on MacOS and Ubuntu 16, and whether the app was run in the viewer pane or an external window. Some other variable must be in play.

**Comment by jmcphers** [comment] 2019-04-01 18:25
It seems that Firefox is the variable; I can reproduce reliably there.

The problem seems to be that, in Firefox, the Shiny application's `disconnected` postmessage is emitted when it is reloading. When we receive this message, the UI immediately acts as though the app has stopped. Unfortunately, the app isn't actually stopped, so we get into this state wherein the app is still running but we've disconnected from it in the UI. 

In Chrome, we don't get "disconnected" during a reload, so none of this happens.

**Closed** 2019-04-01 22:19 UTC
Labels: bug, high, server

**Comment by ronblum** [comment] 2019-06-04 15:43
Verified in RStudio Server 1.2.1528 on Red Hat 7.6 using Firefox on MacOS 10.14.6. Bonus: confirmed that it works in Google Chrome.
