### ISSUE TITLE
"Display math" LaTeX renders as plaintext in visual editor after restart of RStudio 

### ISSUE THREAD

**Issue by ArtificialTruth** [rstudio/rstudio#9401] opened 2021-05-24 17:16 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.1707 "Juliet Rose" (e10cd663, 2021-05-10) for Windows
    OS Version      : Windows 10 Pro
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open new untiled RMarkdown document in visual editor 

2. Add display math ($$ <some latex here $$) 
![image](https://user-images.githubusercontent.com/3297866/119383727-fdf0e680-bcc3-11eb-9311-50ab7dc2c098.png)

3. Save file, close R (don't save workspace)
4. LaTeX is no longer rendered, instead code as plaintext is shown:
![image](https://user-images.githubusercontent.com/3297866/119383823-1c56e200-bcc4-11eb-8b33-a964215455aa.png)

See before and after of the files here: 

[files.zip](https://github.com/rstudio/rstudio/files/6533954/files.zip)

### Describe the problem in detail
This happens on every restart of R studio.

### Describe the behavior you expected
That the LaTeX "display math region" does not break on restart.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-05-25 22:17
@ArtificialTruth Thank you for raising this! We'll review the issue as we continue development of RStudio. including the visual markdown editor. That said: What happens when you toggle between visual and source modes without restarting? I believe the same problem occurs.

- Problem reproduced in RStudio Desktop 1.4.1106 and 1.4.1717 on MacOS 11.3.
- Works correctly in RStudio Server 1.4.1717 on Ubuntu 20.04 via Chrome on MacOS 11.3.

**Comment by ArtificialTruth** [comment] 2021-05-27 16:15
Np. Yes the same issue occurs then.

Interestingly it does not occur with this more simple latex:
[test2.zip](https://github.com/rstudio/rstudio/files/6555397/test2.zip)

**Comment by jjallaire** [comment] 2021-09-13 13:05
It looks like this is a result of how pandoc parses `\begin{align}` see https://github.com/jgm/pandoc/issues/7566.

You can work around the issue for now by removing the blank lines.

**Comment by jjallaire** [comment] 2021-09-13 19:32
Confirmed that this behavior is because of the rules of pandoc markdown described here (https://pandoc.org/MANUAL.html#math) and discussed in this issue (https://github.com/jgm/pandoc/issues/7566)

> For display math, use $$ delimiters. (In this case, the delimiters may be separated from the formula by whitespace. However, there can be no blank lines betwen the opening and closing $$ delimiters.)

**Comment by jjallaire** [comment] 2021-09-13 20:13
I added visual editor code to remove blank lines from display math so that this can't occur: https://github.com/rstudio/rstudio/commit/f80299e97ceae297c775ab450461555ded1d39c4

**Comment by valerie-rstudio** [comment] 2021-09-28 17:28
### Verify Failed

    RStudio Edition : Desktop
    RStudio Version : 2021.12.0-daily+80
    OS Version      : mac OS 11.5.2
    R Version       : 3.6.3

### Failure Points
- The latex is still not rendered properly after switching back and forth between visual mode.

### Steps to Reproduce Problem
1. Download the example files 
[files.zip](https://github.com/rstudio/rstudio/files/7246198/files.zip)
2. Open the Original.rmd in RStudio
3. Switch to Visual Editor Mode, then back to Editor Mode
4. **Expected**: Latex properly rendered in both modes.
5. **Actual**: The `$$` symbols to indicate math now displayed as `\$\$`. Latex not properly rendered.

### Notes
- The IssueAfterCodeChange.rmd file is the result of the above repro steps.
- The IssueBeforeCodeChange.rmd file is the original issue before the PR.

**Comment by jjallaire** [comment] 2021-12-02 18:07
@valerie-rstudio I assigned this to `test` but perhaps I shouldn't have -- the resolution was that we are getting this behavior because of the rules of pandoc markdown (see comment here: https://github.com/rstudio/rstudio/issues/9401#issuecomment-918511086). So if you feed pandoc the following:

```markdown
$$
\begin{align*}

E[(X,Y)] = E(X),E(Y) &= \left(\int_{-\infty}^\infty xf(x,y)\ dx\ , \int_{-\infty}^\infty yf(x,y)\ dy \right) \\
 &= \left(\int_a^b x\cdot f(x,y)\ dx\ , \int_c^d y\cdot f(x,y)\ dy\right) \\
&= \left(\int_0^1 x \cdot 1\ dx\ , \int_1^2 y\cdot  1\ dy \right)\\
&= \left. \int_0^1 x \cdot 1\ dx = \frac{1}{2} x^2 \right]_0^1 \\
&= \left. \int_1^2 y \cdot 1\ dx = \frac{1}{2} y^2 \right]_1^2 \\
&= \left(\left. \frac{1}{2} x^2 \right]^1_0, \left. \frac{1}{2} y^2 \right]_1^2\right) \\
&= \left( \frac{1}{2} , \frac{1}{2} 4 - \frac{1}{2}\right) \\
&= \left(\frac{1}{2}, \frac{3}{2}\right)

\end{align*} 
$$
```

It will actually NOT parse this as math but rather inline tex (with the $$ excluded from the tex):

```bash
 pandoc --from markdown math.md --to native
```

```
[Para [Str "$$",SoftBreak,RawInline (Format "tex") "\\begin{align*}\n\nE[(X,Y)] = E(X),E(Y) &= \\left(\\int_{-\\infty}^\\infty xf(x,y)\\ dx\\ , \\int_{-\\infty}^\\infty yf(x,y)\\ dy \\right) \\\\\n &= \\left(\\int_a^b x\\cdot f(x,y)\\ dx\\ , \\int_c^d y\\cdot f(x,y)\\ dy\\right) \\\\\n&= \\left(\\int_0^1 x \\cdot 1\\ dx\\ , \\int_1^2 y\\cdot  1\\ dy \\right)\\\\\n&= \\left. \\int_0^1 x \\cdot 1\\ dx = \\frac{1}{2} x^2 \\right]_0^1 \\\\\n&= \\left. \\int_1^2 y \\cdot 1\\ dx = \\frac{1}{2} y^2 \\right]_1^2 \\\\\n&= \\left(\\left. \\frac{1}{2} x^2 \\right]^1_0, \\left. \\frac{1}{2} y^2 \\right]_1^2\\right) \\\\\n&= \\left( \\frac{1}{2} , \\frac{1}{2} 4 - \\frac{1}{2}\\right) \\\\\n&= \\left(\\frac{1}{2}, \\frac{3}{2}\\right)\n\n\\end{align*}",SoftBreak,Str "$$"]]
```

Whereas if you remove the blank lines you'll get DisplayMath:

```
[Para [Math DisplayMath "\n\\begin{align*}\nE[(X,Y)] = E(X),E(Y) &= \\left(\\int_{-\\infty}^\\infty xf(x,y)\\ dx\\ , \\int_{-\\infty}^\\infty yf(x,y)\\ dy \\right) \\\\\n &= \\left(\\int_a^b x\\cdot f(x,y)\\ dx\\ , \\int_c^d y\\cdot f(x,y)\\ dy\\right) \\\\\n&= \\left(\\int_0^1 x \\cdot 1\\ dx\\ , \\int_1^2 y\\cdot  1\\ dy \\right)\\\\\n&= \\left. \\int_0^1 x \\cdot 1\\ dx = \\frac{1}{2} x^2 \\right]_0^1 \\\\\n&= \\left. \\int_1^2 y \\cdot 1\\ dx = \\frac{1}{2} y^2 \\right]_1^2 \\\\\n&= \\left(\\left. \\frac{1}{2} x^2 \\right]^1_0, \\left. \\frac{1}{2} y^2 \\right]_1^2\\right) \\\\\n&= \\left( \\frac{1}{2} , \\frac{1}{2} 4 - \\frac{1}{2}\\right) \\\\\n&= \\left(\\frac{1}{2}, \\frac{3}{2}\\right)\n\\end{align*} \n"]]
```

So there isn't at the point anything more we can do as Pandoc is not parsing the input as an equation.

**Comment by jjallaire** [comment] 2021-12-02 20:16
Looking more closely at the fix, it should be addressing the example here. Let me take a closer look and see if I can tweak the fix to make it prevent this case.

**Comment by jjallaire** [comment] 2021-12-04 17:55
Looking yet more closely :-) I see that the code in `Original.Rmd` won't actually be parsed as DisplayMath by Pandoc (because of the embedded newlines). The fix we put in was to remove newlines that _entered in the visual editor_ however we can't do anything about newlines that are there before we read the document. So I think its correct for this issue to be closed b/c there isn't more we can do here.

**Comment by valerie-rstudio** [comment] 2021-12-06 15:54
### Not a Bug
Closing. See JJ's comments above.

**Closed by valerie-rstudio** 2021-12-06 15:54 UTC
Labels: bug, in progress, visual markdown
