### ISSUE TITLE
Entering tex symbols (\beta, etc) in Visual Markdown causes equations to not render

### ISSUE THREAD

**Issue by snjnz** [rstudio/rstudio#10327] opened 2022-01-09 20:59 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 Build 351  Also 2022.02.0-daily+361 from https://dailies.rstudio.com/rstudio/prairie-trillium/desktop/windows-xcopy/
    OS Version      : Windows 10 21H2
    R Version       : 4.1.1

### Steps to reproduce the problem

1. Enter Visual Markdown mode
2. Start an equation with the `$` sign, and include at least LaTeX Math Symbol that uses a backslash (i.e. `\beta`)
3. Close the `$` to end the equation and observe that the equation does not change type
4. Enter non-Visual mode and observe that most equation syntax has been backslashed out
5. Note that this doesn't occur by entering `$y$` and then editing the converted equation.

See example video: https://drive.google.com/file/d/1Duxf_tL3i18azRXPoSlst8hW-5xMRGfa/view?usp=sharing (recorded on 2021.09.0 Build 351)

### Describe the problem in detail

The visual markdown editor seems to change mode as soon as the first backslash for a LaTeX symbol is entered.  I've observed that when I type in:

`y = \`

As soon as I enter the `\` a `\tex` stand-in appears.  This doesn't appear when editing a pre-existing equation. My suspicion is that this prompt/standin is breaking the equation mode recognition.

### Describe the behavior you expected

Entering:

`$y = \beta_0 + \beta_1$`

character-by-character while in Visual Mode should work correctly.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2022-01-10 22:44
Thanks for the bug report -- I was able to reproduce this as well.

As you surmised, It looks like we suppress the auto-completion of `\tex` immediately after a `$`, but we don't do this within a currently-being-typed `$$` expression.

**Comment by jjallaire** [comment] 2022-05-07 17:01
Should be fixed here: https://github.com/rstudio/rstudio/commit/210d9b851044dee1361f4bc0ad95e9dc73ed092c

**Comment by snjnz** [comment] 2022-05-08 00:34
I just did a quick test with the latest daily (below) and it seems to be fixed/looks good to me.  Thank you!

```
RStudio 2022.06.0-daily+373 "Spotted Wakerobin" Daily (438f4c08d77b1424a9b3bb193d16060cdae06aaa, 2022-05-07) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

**Comment by jgutman** [comment] 2022-05-12 14:12
<img width="206" alt="image" src="https://user-images.githubusercontent.com/7817881/168095027-fa1ed465-a499-48c8-9a24-575727519534.png">

Verified in RStudio Desktop 2022.6.0.391, and additionally verified above by original issue reporter.

**Closed by jgutman** 2022-05-12 14:12 UTC
Labels: bug, visual markdown, test
