### ISSUE TITLE
Allow Background Jobs tab to be in panes other than Console

### ISSUE THREAD

**Issue by noamross** [rstudio/rstudio#14215] opened 2024-02-02 20:11 UTC
It would be very helpful for the Background Jobs tab to be able to be moved to one of the panes other than the console, so one could run background processes and keep an eye on them while keeping the console accessible.  This works great for the "Build" pane, so much I sometimes hack it by using a Makefile to run a background process just to get its output there.  Allowing this pane to move (and for that matter, the Terminal pane, too in case I'm running some other monitoring job), would be great.

**Comment by gtritchie** [comment] 2024-02-06 15:37
Marking this as a duplicate of the more general request: https://github.com/rstudio/rstudio/issues/2879

**Closed by gtritchie** 2024-02-06 15:37 UTC
Labels: enhancement, duplicate, new
