### ISSUE TITLE
RStudio code and options use terms 'blacklist' and 'whitelist'

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#9621] opened 2021-07-20 22:48 UTC
The RStudio codebase uses the terms "blacklist" and "whitelist" in many places. 

- The "Ignore GPU Blacklist" option (in Global Preferences / Graphics)
- The "whitelist" for process termination (in Global Preferences / Terminal)
- The `session-env-var-save-blacklist` option (in rsession.conf)
- The `directory-view-whitelist` option (in rsession.conf)

In addition, the terms are used extensively in the codebase to describe lists of specifically excluded (or allowed) items. We should replace these with more inclusive terms.

**Comment by ronblum** [comment] 2021-08-09 16:01
In the code, I found two references to `blacklist`:
- Is this one an option that ought to be renamed? https://github.com/rstudio/rstudio/blob/7ce19c54507e53de8859502605774a825cced146/src/cpp/desktop/DesktopMain.cpp#L433
- There's one in NEWS.md, but that appropriately describes a change

I found no references to `whitelist`

Now for the hard part: checking that the renamed options work.

**Comment by jmcphers** [comment] 2021-08-09 17:58
> Is this one an option that ought to be renamed?

That's the name of a Chromium option, so there's no way to change it.

**Comment by valerie-rstudio** [comment] 2021-08-12 21:32
@jmcphers 
Still see one reference to "whitelist" in the **rstudio** files:
- src/cpp/session/resources/pdfjs/build/pdf.worker.full.js

There are several "whitelist" used in the following **rstudio-pro** files:
- docs/server/r_sessions/directory_management.qmd
- docs/server/job_launcher/configuration.qmd
- src/cpp/activation/ActivationContextRemote.cpp
- src/cpp/server/ServerJobLauncherRpc.cpp

**Comment by R-Hannibal** [comment] 2021-09-13 17:55
@jmcphers - We've confirmed the rsession.conf settings `session-env-var-save-blacklist` and `directory-view-whitelist` have changed. 

Before closing though we'd like to verify the new setting names (`session-ephemeral-env-vars` and `directory-view-allow-list`) and their values are being respected properly. We've tried testing them but it currently appears they're getting ignored (could be due to the name change, or they may not have been working correctly in Juliet-Rose). 

What's a good test scenario for these settings so we can make sure we're testing them properly?

**Comment by ronblum** [comment] 2021-09-13 18:03
[Note: Or, I'm not using or understanding the properties properly.]

**Comment by jmcphers** [comment] 2021-09-13 23:20
ephemeral env vars:

> Specifies a list of environment variables that will not be saved when sessions suspend, separated by a colon character (:).

Add a var to the list, set it with Sys.setenv(), suspend the R session (from the homepage), and see if it comes back when you return the the session.

allow list:

> Specifies a list of directories exempt from directory view restrictions, separated by a colon character (:).

This one only takes effect if you're using `restrict-directory-view`. Was that turned on?

**Comment by ronblum** [comment] 2021-09-14 12:52
ephemeral env vars: Aha! I was treating this as "variables in the environment," that is any variable that would show up in the Environment Pane.

allow list: I set `restrict-directory-view` to 1, but I'll try again.

**Comment by ronblum** [comment] 2021-09-14 13:09
1. Ephemeral environment variables
`session-ephemeral-env-vars`: Verified in RStudio Workbench 2021.09.0-preview+340.pro1 on Red Hat 8.4.

2. Allowing directory view with restricted directory
Afer setting `restrict-directory-view=1`, I tried
```
> setwd("/var")
> getwd()
[1] "/var"
```
Then in the Files Pane, "Go to Working Directory" which showed me the contents of `/var`. Note: permission on `/var` is 755.

**Comment by jmcphers** [comment] 2021-09-14 16:44
That setting controls what files you can open in the IDE (i.e. in the editor pane), not which directories you can open in the Files pane.

https://docs.rstudio.com/ide/server-pro/latest/r_sessions/directory_management.html#restricted-directories

**Closed** 2021-09-14 17:00 UTC
Labels: test

**Comment by datakid** [comment] 2022-12-22 22:18
> > Is this one an option that ought to be renamed?
> 
> That's the name of a Chromium option, so there's no way to change it.


According to [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1101491#c11) we should be able to use `--ignore-gpu-blocklist`?

```
//gpu: rename switch to --ignore-gpu-blocklist

This switches is a relatively well known switch, so the old version is
kept around and produces a deprecation LOG(ERROR) when used.
```

I don't read the Chromium bug tracker that frequently so am unsure of the status of that bug or the fix's contributor, but I would appreciate if you could revisit this flag please.

**Comment by datakid** [comment] 2023-10-16 04:58
@ronblum @jmcphers can we please test if `--ignore-gpu-blocklist` works as we expect? This should be low-hanging fruit for an easy win? Thanks!
