### ISSUE TITLE
Hidden terminal history entries occasionally displayed

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#9833] opened 2021-09-10 18:57 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0-preview+341
    OS Version      : Ubuntu Focal
    R Version       : N/A
    Shell           : ZSH

### Steps to reproduce the problem

1. Run some commands in the terminal
2. Use terminal history after each command

### Describe the problem in detail

"Strange" entries appear as the most recent entry in the history occasionally. After running another command the "strange" entry disappears from the history altogether:

![image](https://user-images.githubusercontent.com/37987486/132903452-2c81b573-131f-409c-a875-bbbcc787f563.png)

(e.g. if I hit the up-arrow from `git status` it would go immediately to `git rebase --continue`.) Also note that the value of `$HISTCONTROL` is `ignoreboth` and this doesn't happen in a terminal outside of RStudio.

### Describe the behavior you expected

With `$HISTCONTROL` set to `ignoreboth`, no "strange" history entries should be shown.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by hadley** [comment] 2021-09-20 22:48
I see this frequently too.

**Comment by MariaSemple** [comment] 2021-09-20 23:12
@hadley What shell are you using?

**Comment by gtritchie** [comment] 2021-09-21 00:10
The shell is definitely a factor and zsh is more prone to this than bash was. I think there's another issue on this which I'll track down (might have gone stale).

Turning off "Save and restore environment variables" in terminal prefs will prevent this.

**Comment by gtritchie** [comment] 2021-09-21 00:38
For `zsh` to work with the "save and restore environment variables" setting, we don't use `$HISTCONTROL` because that's bash-specific and doesn't work with zsh.

The default IDE behavior with zsh is to lauch with `-g` to accomplish the same, but this can be overridden by other shell settings (HIST_IGNORE_SPACE).

Related:
https://github.com/rstudio/rstudio/pull/6186
https://github.com/rstudio/rstudio/issues/4699

**Comment by hadley** [comment] 2021-09-21 12:19
`echo $SHELL` suggests I'm using `/bin/zsh`.  I have very some history options set in `.profile` that I did so long ago that I don't remember why:

```
export HISTFILESIZE=100000
export HISTSIZE=10000
export HISTCONTROL=erasedups
export HISTIGNORE="&:ls:[bf]g:exit"
shopt -s histappend
```

**Comment by taiyodayo** [comment] 2022-10-18 04:15
I use zsh too and see the exact same symptom as @MariaSemple 
( ` echo 1BCBD8C1 && echo $HISTCONTROL && /usr/bin/env && echo B4DB905C` shows as the last command. )

Is there a workaround for this?

I could not find the setting for "unless they turn off Capture Environment Variables" as suggested by @gtritchie 
is it something I put in .zshrc, or a setting in RStudio?

**Comment by gtritchie** [comment] 2022-10-18 21:16
> I could not find the setting for "unless they turn off Capture Environment Variables" as suggested by @gtritchie is it something I put in .zshrc, or a setting in RStudio?

It's an RStudio setting. Tools / Options / Terminal / Closing : "Save and restore environment variables".

![screen shot of RStudio terminal settings with save and restore environment variables highlighted](https://user-images.githubusercontent.com/10569626/196546396-45222233-7473-4d53-a2fd-4f571ab12dd7.png)

**Comment by taiyodayo** [comment] 2022-10-19 06:38
Thank you very much!! How silly of me not noticing it. Problem is solved.

**Comment by russellsmithies** [comment] 2023-03-30 22:24
A bit late to the party with this comment but I've been searching for the solution for a while.
Is there a Global config setting to have this disabled by default?

**Comment by gtritchie** [comment] 2023-03-31 03:37
> Is there a Global config setting to have this disabled by default?

@russellsmithies Yes! You can set system-wide defaults for most user preferences. This works for both RStudio Server and RStudio Desktop.

To disable "save and restore environment variables" by default for all users on a system, create a file named `rstudio-prefs.json` containing

```json
{
    "terminal_track_environment": false
}
```

Linux and macOS, save the file at `/etc/rstudio/rstudio-prefs.json`

On Windows, the file goes at `%PROGRAMDATA%\RStudio\rstudio-prefs.json` (this particular preference isn't relevant on Windows, just mentioning it for completeness).

If you want to set any other preferences to a different default, you can figure out its name by changing it in the RStudio UI and then examining the user preferences file. That is normally in `~/.config/rstudio/rstudio-prefs.json` on Linux and Mac, and `%APPDATA%\RStudio\rstudio-prefs.json` on Windows.

You can also change where these files live using environment variables: see https://docs.posit.co/ide/desktop-pro/settings/settings.html for more details.

**Comment by gtritchie** [comment] 2023-03-31 03:42
You can also look up settings in the Workbench admin guide: https://docs.posit.co/ide/server-pro/reference/session_user_settings.html. Not all settings there will apply to open-source RStudio, but most will.

**Comment by krlmlr** [comment] 2024-03-02 05:27
Should a comment line like `# saving environment variables` , perhaps with a pointer to this issue, be added to the command line? A user seeing this in the history might act.

Adding this to aid users coming via search engine:

```
&& echo $HISTCONTROL && /usr/bin/env && echo
```

**Comment by gtritchie** [comment] 2024-03-02 16:40
> Should a comment line like `# saving environment variables` , perhaps with a pointer to this issue, be added to the command line? A user seeing this in the history might act.

That's a great idea, I'll look at doing that.

**Comment by gtritchie** [comment] 2024-03-11 21:37
For `zsh`, we rely on passing it the `-g` argument to ensure `HIST_IGNORE_SPACE` is enabled. We leverage that to hide the hidden command for saving environment variables from the command history. I've never understand exactly why it still shows up, sometimes, so I (finally) read the manual: 

> HIST_IGNORE_SPACE (-g)
>     Remove command lines from the history list when the first character on the line is a space, or when one of the
>    expanded aliases contains a leading space.  Only normal aliases (not global or suffix aliases) have this
>    behaviour.  Note that the command lingers in the internal history until the next command is entered before it
>    vanishes, allowing you to briefly reuse or edit the line.  If you want to make it vanish right away without
>    entering another command, type a space and press return.

That part about "the command lingers in the internal history until the next command is entered..." is what I previously missed. I swear it wasn't there five years ago, but I'm sure it was.

So I can trivially reproduce this issue by selected `zsh` as the terminal, starting a terminal, and typing a command (e.g. `ls -l`). Then WAIT a few seconds to allow the hidden command to run. Then hit up-arrow, and there it is.

So I believe fixing this case can be done by doing what it said: silently enter a command consisting only of a space after issuing the first "hidden" command to ensure it gets removed.

**Comment by ronblum** [comment] 2024-03-15 21:47
Verified in
- RStudio Desktop 2024.04.0-daily+581 on MacOS 14.4 using bash and zsh
- RStudio Desktop 2024.04.0-daily+593 on Ubuntu 22.04 using bash and zsh (had to install it)
- RStudio Server 2024.04.0-daily+593 on Ubuntu 22.04 using bash

Checked by
- creating multiple terminals and switching between them
- closing and restarting RStudio Desktop
- closing an RStudio Server session and opening a new one

Caveat: zsh on Ubuntu isn't maintaining history after exiting (works on MacOS), but that's a pre-existing issue which I'll file separately.

**Closed by ronblum** 2024-03-15 21:47 UTC
Labels: bug
