### ISSUE TITLE
RStudio-associated .R files in Mac OS X 10.14 not loaded into editor pane when double clicked in Finder

### ISSUE THREAD

**Issue by michael-mastroianni** [rstudio/rstudio#3728] opened 2018-10-23 20:40 UTC
### System details:
    RStudio Edition : Desktop
    RStudio Version : 1.2.1045 Build 1048 (01180140)
    OS Version      : Mac OS 10.14 (Mojave)
    R Version       :  3.5.1 (2018-07-02) -- "Feather Spray"

Double-clicked .R source file in Finder. 

Using the current preview release of RStudio. In order to fix this, I associated .R files with RStudio by right-clicking the source file in Finder, selecting Open With as RStudio.app, and choosing "Change All..." to associate all files with a .R extension with loading into RStudio by default.

Expected behavior is that file loads into RStudio editor pane, and getwd() returns directory that source file was opened from.

This has worked a few times, but seems to revert to RStudio launching without a source file loaded into the editor pane; not sure why. Executing getwd() at the console returns the current working directory, which is my home directory, when the file does *not* load. Note that I have just upgraded to OS 10.14 (Mojave) from 10.13 (High Sierra).

Thanks,

Mike M

**Comment by kevinushey** [comment] 2018-10-23 20:53
I can reproduce this. Strangely, at least in my case, it seems like RStudio only successfully opens the file half the time when I open RStudio this way. (In all cases, RStudio successfully opens but half the time it doesn't open the file on startup)

**Comment by michael-mastroianni** [comment] 2018-10-23 20:58
Sounds exactly as I am experiencing it as well, Kevin, thanks.

**Comment by kevinushey** [comment] 2018-10-23 21:42
The issue is in here: https://github.com/rstudio/rstudio/blob/308736b2cd02b53f225ce3ab3a581f15bd336e88/src/cpp/desktop/DesktopPosixApplication.cpp#L30

RStudio receives the file open request, but it actually comes _after_ the activation window has been initialized in some cases, and in those cases we interpret it as a request to open the file in an existing RStudio window. However, that window is not actually ready yet and so the request is just dropped on the floor.

**Comment by kevinushey** [comment] 2018-10-25 21:38
Looks like this still isn't fixed, unfortunately.

Note that one other side effect of this issue is that attempting to open a project from the Finder will sometimes lead to two instances of RStudio being opened, rather than just one.

**Comment by jmcphers** [comment] 2018-10-25 23:19
Should be fixed in #3747.

**Closed by jmcphers** 2018-10-25 23:19 UTC
Labels: bug, regression, reproducible

**Comment by kevinushey** [comment] 2018-10-26 15:46
@michael-mastroianni can you try once more with the latest [daily build](https://dailies.rstudio.com)? The situation should be improved now.

**Comment by michael-mastroianni** [comment] 2018-10-26 16:54
@kevinushey The daily build seems to have solved the problem. I tried 10 launches of various .R files with varying delays between each launch, all successfully loaded into the RStudio Desktop editor pane. Thanks very much!

Version/Environment:
```RStudio
Version 1.2.1074
© 2009-2018 RStudio, Inc.
Build 1082 (93a77229)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.11.1 Chrome/65.0.3325.230 Safari/537.36
```
