### ISSUE TITLE
Making an ODBC connection hangs in RStudio version 1.1.456 but is fine in 1.0.136

### ISSUE THREAD

**Issue by alexfun** [rstudio/rstudio#3701] opened 2018-10-18 01:18 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio-1.1.456
    OS Version      :  Windows 7 Pro 64 bit 
    R Version       :  3.3.2

### Steps to reproduce the problem

`DBI::dbConnect(odbc::odbc(), "DSN_NAME", pwd = 'password')` causes RStudio to be busy forever on version 1.1.456. It works fine in version 1.0.136 (The only change is updating to the new version of RStudio). 

### Describe the problem in detail

In RStudio version 1.1.456, if an incorrect `dsn` is supplied to `dbConnect`, we get an expected error message:

> Error: nanodbc/nanodbc.cpp:950: IM002: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified 

If an incorrect password is supplied then we get:

> Error: nanodbc/nanodbc.cpp:950: 28000: [Oracle][ODBC][Ora]ORA-01017: invalid username/password; logon denied

However, if both are correct, then it just hangs.

The issue seems to be tied to this version of RStudio, as running the commands in the RStudio terminal results in a successful connection.

### Describe the behavior you expected

I expect a connection object to be returned.

### Partial session info:

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] DBI_1.0.0         odbc_1.1.1        data.table_1.10.4 bindrcpp_0.2      forcats_0.3.0    
>  [6] stringr_1.3.0     dplyr_0.7.4       purrr_0.2.4       readr_1.1.1       tidyr_0.8.0      
> [11] tibble_1.4.2      ggplot2_2.2.1     tidyverse_1.2.1

**Comment by alexfun** [comment] 2018-10-18 01:19
This behaviour is also observed on a colleague's computer (Windows 10 64 bit).

**Comment by pascaloettli** [comment] 2018-10-18 02:12
Do you also reproduce with the [preview version](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by alexfun** [comment] 2018-10-18 03:59
No, not reproducible with Version 1.2.1060

**Comment by ronblum** [comment] 2019-01-14 17:11
@alexfun Thanks for letting us know about this, and that the issue is resolved in RStudio Desktop 1.2. [The latest preview, RStudio v1.2.1226-2](https://www.rstudio.com/products/rstudio/download/preview/), is available at [https://www.rstudio.com/products/rstudio/download/preview](https://www.rstudio.com/products/rstudio/download/preview).

**Closed** 2019-01-14 17:12 UTC
