### ISSUE TITLE
JavaScript error when knitting to Viewer Pane

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [rstudio/rstudio#12244] opened 2022-10-28 11:50 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0-daily+293 Elsbeth Geranium (desktop)
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

1. Create empty RMarkdown file
2. Make sure *Preview in Viewer Pane* is enabled
3. Click *Knit* button

### Describe the problem in detail

JavaScript error window appears

![image](https://user-images.githubusercontent.com/89191115/198580181-8205ee74-e044-48b1-9553-dd9f2f7c8ef7.png)

### Describe the behavior you expected

Trivial: JavaScript error window does not appear.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2022-10-28 15:25
Duplicate of #12220

**Closed by gtritchie** 2022-10-28 15:25 UTC
Labels: bug, duplicate, new
