### ISSUE TITLE
Intermittent error connecting to R on desktop build

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8270] opened 2020-11-02 22:52 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.998
    OS Version      : Unknown

### Steps to reproduce the problem

Unknown, but for affected users it happens intermittently when starting RStudio. 

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/470418/97927820-9882db80-1d1a-11eb-83e9-1b842780fd13.png)

Retrying usually addresses the problem as per @hadley.

### Describe the behavior you expected

RStudio should be able to connect to R. We do see intermittent failures from time to time, but this one warrants further investigation since:

- it has been reported by both @hadley and @mine-cetinkaya-rundel
- it started happening for both of them at nearly the same time
- we changed the code that shows this page very recently in PR https://github.com/rstudio/rstudio/pull/8148.

**Comment by kevinushey** [comment] 2020-11-04 22:14
Do we have a way to reliably reproduce this?

**Comment by MariaSemple** [comment] 2020-11-05 01:18
I have been trying to reproduce, but haven't been able to yet.

**Comment by kevinushey** [comment] 2020-11-05 16:51
I also haven't been able to reproduce. I think we'll have to audit the ways in which the error page can be triggered, and think about poking at the problem from ways that could manifest.

**Comment by kevinushey** [comment] 2020-11-06 19:49
Some thoughts on how we could approach this...

One hypothesis is that we're getting the wrong return value here:

https://github.com/rstudio/rstudio/blob/ece4e97f803ca4d616f1a49391ed3bfd2632373c/src/cpp/desktop/DesktopMainWindow.cpp#L664-L685

We could ignore the value of `ok` (perhaps it's incorrect some percentage of the time?) and instead check and see if we can evaluate a JavaScript callback on the window that would indicate if the load was successful.

Another hypothesis is that we're getting multiple `loadFinished()` signals -- https://bugreports.qt.io/browse/QTBUG-87089 suggests this is at least possible. If that's the case, then we could even delay the error check here (on a timer) just in case we're getting a premature `loadFinished()` response with the wrong result.

I'm not able to see how https://github.com/rstudio/rstudio/pull/8148 could affect this outcome, though...

**Comment by MariaSemple** [comment] 2020-11-06 19:59
Yes - the only thing I can't think is that the potential for this bug was there before #8148 but adding the mutex and additional boolean flag check somehow changed the timing so that the bug is getting triggered more often. We could also lock the mutex in the section of the code that decides whether the load was okay, so that it's not possible to both load the cannot connect page and have connected successfully.

**Comment by blairj09** [comment] 2020-11-09 15:59
I don't know if this could possibly have any impact, but I **always** open RStudio on a second monitor (my MacBook is always closed and I have it hooked to another monitor).

**Comment by kevinushey** [comment] 2020-11-12 18:39
I was able to reproduce locally, and it looks like `loadFinished()` is getting called multiple times. The first time it's called with `false`; then second time with `true`.

```
kevinushey@cdrv-2:~/rstudio-v14/src/build-cpp-Desktop_Qt_5_12_8_clang_64bit-RelWithDebInfo [master]
$ build && ./rstudio-dev
ninja: no work to do.
Loaded: false
Loaded: true
```

I don't know why this is the case, but I think the right resolution here is to use a timer and allow a small window where we wait to see if a "failed" window load is followed by a "successful" window load, and forego displaying the error message when that happens.

**Comment by blairj09** [comment] 2020-11-18 17:02
Noticed this doesn't manifest in daily 1.4.1038-2! Great work!

**Comment by kfeinauer** [comment] 2020-11-18 17:11
Verified by community, and I also have not seen it lately.

**Comment by mine-cetinkaya-rundel** [comment] 2020-11-18 23:42
I'm still getting this intermittent error

```
RStudio Edition : Desktop
RStudio Version : 1.4.1043
OS Version      : macOS Catalina 10.15.7
```

**Comment by kevinushey** [comment] 2020-11-30 18:11
@hadley also reports seeing this in 1.4.1066.

**Comment by kevinushey** [comment] 2020-11-30 18:34
@hadley mentions the issue is at least less frequent in 1.4; we _might_ be able to get away by bumping up the timer delay on the PR in https://github.com/rstudio/rstudio/pull/8382.

**Comment by blairj09** [comment] 2020-11-30 22:32
This had resolved for me, but it appeared again today on RDP 1.4.1063-1

**Comment by kfeinauer** [comment] 2020-12-01 16:15
@kevinushey Did you close this issue intentionally? I don't see any commits to bump up the timer.

**Comment by blairj09** [comment] 2020-12-01 17:03
Noticed again with 1.4.1066-4

**Comment by kevinushey** [comment] 2020-12-01 17:45
@kfeinauer thanks for catching that -- that was unintentional.

**Comment by kevinushey** [comment] 2020-12-02 18:28
Should (hopefully) be fixed by https://github.com/rstudio/rstudio/pull/8499. Please let us know if you're still seeing this issue in the latest builds!

(If the issue still re-occurs, I think we should re-open and target for a future milestone as anything more invasive will be out of scope for 1.4)

**Comment by kfeinauer** [comment] 2020-12-04 15:22
@mine-cetinkaya-rundel @blairj09 How is this looking on the latest daily? Improved, I hope?

**Comment by hadley** [comment] 2020-12-04 15:48
It's no better for me on 1.4.1073

**Comment by mine-cetinkaya-rundel** [comment] 2020-12-04 15:51
Just tried it with 1.4.1078 and it's not better for me either

**Comment by mine-cetinkaya-rundel** [comment] 2020-12-04 16:27
I don't know if this is helpful, but lately, I see the following first when I launch RStudio. This goes away after a few seconds and turns into the screen at the beginning of this issue.

<img width="1267" alt="Screenshot 2020-12-04 at 16 23 55" src="https://user-images.githubusercontent.com/5965649/101188267-63391880-364d-11eb-8a4c-64e5fddf2d3a.png">

**Comment by jmcphers** [comment] 2020-12-05 00:20
@mine-cetinkaya-rundel Thank you, this is extremely helpful. Does clicking Reload (during the several seconds in which this screen is displayed) fix the problem?

@kevinushey Maybe what's needed here is not waiting for a successful load to arrive (it seems like it never does in the most recent reports) but to do an automatic retry a limited number of times, perhaps separated by a short delay. What do you think?

**Comment by mine-cetinkaya-rundel** [comment] 2020-12-05 00:43
@jmcphers Yes, if I click reload it fixes the problem!

**Comment by mine-cetinkaya-rundel** [comment] 2020-12-11 13:45
With 1.4.1087, I'm seeing that intermittently upon launch RStudio gets stuck on the "This site can't be reached 127.0.0.1 refused to connect" screen, but this time with beach ball spinning so I can't click on Reload and it doesn't go away on its own. Force quitting and relaunching the project usually works.

**Comment by blairj09** [comment] 2020-12-11 15:19
I see new behavior with RStudio Desktop Pro 1.4.1087.5 running on macOS 11.0.1

1. Download the latest daily (in this case 1.4.1087.5)
2. Install the download by replacing the current version
3. Open RStudio
4. Accept the option to open it
5. I see the same screen @mine-cetinkaya-rundel mentions
6. I don't click Reload, I just wait
7. Now, instead of seeing the second screen (which was the previous behavior) RStudio just hangs and never opens. I had to force quit the app and then open it again. When opening it again, it opened and behaved as expected.

**Comment by kfeinauer** [comment] 2020-12-11 15:21
Not an ideal situation, but maybe @kevinushey could commandeer @blairj09's laptop for 20 minutes to debug what's going on so we can craft the correct fix.

**Comment by kevinushey** [comment] 2020-12-11 19:58
I've reverted https://github.com/rstudio/rstudio/commit/284c4b0159b3c2180869a8093b881dcc4056931a since it's evidently made the issue even worse. 😞 

I'm going to spend some time seeing if I can properly reproduce the issue locally since I haven't been successful with speculative fixes thus far.

**Closed** 2020-12-14 19:52 UTC
Labels: bug, desktop integration

**Comment by blairj09** [comment] 2020-12-15 18:20
The behavior is gone for me with 1.4.1090-1! 🙌  I did see a brief "Connecting to R" screen, but I think that is probably expected. Great work!

**Comment by kevinushey** [comment] 2020-12-15 21:43
Phew! Finally, that's fantastic news :)

**Comment by melissa-barca** [comment] 2020-12-16 18:38
I'm marking this as Verified based on @blairj09's feedback 😄

**Comment by blairj09** [comment] 2020-12-16 18:59
Further verified with 1.4.1093-1. It seems the problem is fully resolved 😁
