### ISSUE TITLE
addinslist package crashes rstudio on Mac

### ISSUE THREAD

**Issue by cmbarton** [rstudio/rstudio#1688] opened 2017-10-27 22:17 UTC
I've got RStudio Version 1.1.383 and R 3.4.1. All packages are up to dates. When I run addinslist, it crashes after opening a new window and attempting to update the list of adding. I reported this to the addinslist github issue tracker and the lead dev suggested I should also report it to rstudio. Here is the track link on the addinslist repo: 

https://github.com/daattali/addinslist/issues/74

I'm also attaching a screenshot of an example crash (sometimes it just takes the whole thing down). 

Michael Barton

<img width="2106" alt="addinlist_crash" src="https://user-images.githubusercontent.com/8967599/32127178-de8c1ff2-bb29-11e7-8145-d0b8b9e7e662.png">

**Comment by daattali** [comment] 2017-10-28 02:55
I told @cmbarton that I believe this should be reported as an RStudio bug because I don't think any code that I write in an addin should have the power to crash RStudio. I haven't looked into it at all because of that.

I'm also using rstudio 1.1.383 but on Windows and it doesn't crash for me

**Comment by dfalty** [comment] 2017-10-30 20:59
I'm unable to reproduce this as well on 1.1.383. Does it still crash after resetting RStudio's state?
https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

**Comment by kevinushey** [comment] 2017-10-31 16:27
@cmbarton: how many packages do you have installed? If you have a large number of packages installed, I wonder if that could be related?

**Comment by cmbarton** [comment] 2017-10-31 17:18
You don't say if you are using a Mac or not. What procedure are you referring to in "resetting Rstudio's state"?

Michael Barton

**Comment by cmbarton** [comment] 2017-10-31 17:19
I have 10's but not 100's of packages. What is a large number? Only a few are loaded at startup.


Michael Barton

**Comment by jmcphers** [comment] 2019-11-12 18:36
We've never been able to reproduce this, and are closing this since it's been a couple years without input. @cmbarton Feel free to reopen if you're still seeing the issue with recent builds.

**Closed by jmcphers** 2019-11-12 18:36 UTC
Labels: repro needed

**Comment by tmcduff** [comment] 2020-02-27 19:02
Was not able to repro with minimal effort. It appears legacy to older versions at this point. 

Verified: Version 1.3.842
