### ISSUE TITLE
Some Polish characters don't work in RStudio IDE console or script

### ISSUE THREAD

**Issue by gsmolinski** [rstudio/rstudio#6973] opened 2020-05-27 18:46 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      :  Windows 10 x64 (build 18363)
    R Version       :  4.0.0

### Steps to reproduce the problem
Use in the console or in the script right alt + a and you will see that nothing happened, but the polish letter "ą" should appear. Use  in the console or in the script right alt + z and you will see that polish letter "ż" appears as it should. My locale from sessionInfo:

[1] LC_COLLATE=Polish_Poland.1250 
[2] LC_CTYPE=Polish_Poland.1250   
[3] LC_MONETARY=Polish_Poland.1250
[4] LC_NUMERIC=C                  
[5] LC_TIME=Polish_Poland.1250    

This problem doesn't exist in the previous version of RStudio (RStudio-1.2.5042) and also doesn't exist in the R GUI 4.0.0.
### Describe the problem in detail
Some Polish character are working as expected, but not all of them. Perhaps, at least in part, it is connected with shortcuts used in RStudio, like right alt + l (when I use it, then I see "Please select the code to extract a function", but i should see the letter "ł" in console/script.) I would like to highlight that this problem appears not just in script, but also in the console, so I think that it is not connected with the script encoding.
### Describe the behavior you expected
When using Polish locale user should see Polish letters, when using appriopriate shortcuts (like for example right alt + a, which is "ą").

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-05-27 21:10
@gsmolinski Thank you for raising the issue! I can reproduce both the problem in RStudio Desktop 1.3.959 and the correct behavior in 1.2.5033. I'll mark it as a bug to review as we continue developing and updating RStudio.

**Comment by kevinushey** [comment] 2020-05-27 23:43
Looks like this is fixed in the v1.4 daily builds.

**Comment by mbojan** [comment] 2020-10-23 12:56
@ronblum @kevinushey This has become a nightmare for me. I started teaching intro R+RStudio class this semester and my Polish students need to be able to write in Polish in RStudio. The current stable build is broken in that respect. I have tried the daily build (1.4.959) but ran in to multitude of other problems, e.g. #8171, but also others  (I don't really have time to report everything at this moment). As I don't need most of the recent RStudio features for the course, but do critically need the students not to get confused/discouraged by buggy behavior I want to try to downgrade. Hence questions:

1. Where can I find RStudio 1.2.5033 Windows installer? The daily builds page lists only recent ones.
2. Is there a (simple) way to have multiple RStudio versions installed at the same time.

I need all this on Windows.

Please help.

**Comment by gsmolinski** [comment] 2020-10-23 13:50
@mbojan 
ad. 1:
https://rstudio.com/products/rstudio/older-versions/
It's 1.2.5042, but I'm using it and is fine

**Comment by mbojan** [comment] 2020-10-23 13:52
Thanks @gsmolinski ! Did you have to remove the conflicting keyboard shortcuts manually?

**Comment by gsmolinski** [comment] 2020-10-23 13:55
@mbojan but using 1.2.5042 I didn't encounter any conflicting keyboard shortcuts; perhaps there is some shortcuts which I'm not using, but I'm not aware of any conflicting keyboard shortcuts in version 1.2.5042

**Comment by mbojan** [comment] 2020-10-23 13:57
OK thanks. I think one had to in the earlier RStudio versions...

**Comment by kevinushey** [comment] 2020-10-23 19:09
@mbojan: I'm sorry to hear the latest release has caused you and your students so much grief. :-/

> The current stable build is broken in that respect. I have tried the daily build (1.4.959) but ran in to multitude of other problems, e.g. #8171, but also others (I don't really have time to report everything at this moment).

If you're able to, we would hugely appreciate it if you could share some of the issues you've encountered. We're currently in the process of preparing a 1.4 stable release, and if you're encountering any show-stopping issues we'd love to be able to fix those before we cut the final release!

Older RStudio releases are indeed available at https://rstudio.com/products/rstudio/older-versions/. If you'd like to install multiple copies of RStudio side-by-side on Windows, it's sufficient to just install those copies of RStudio into different paths.

**Comment by mbojan** [comment] 2020-10-30 12:01
Thanks @kevinushey . I ordered the students to downgrade. The true test will be on the coming Wednesday. Meanwhile, installed a daily build side-by-side with 1.2, I'll try to revisit and report the problems I encountered.

**Closed** 2021-10-13 15:27 UTC
Labels: bug, windows, regression
