### ISSUE TITLE
Rmd document not rendering to HTML in preview release

### ISSUE THREAD

**Issue by philstraforelli** [rstudio/rstudio#3965] opened 2018-11-28 18:59 UTC
I've attached an Rmd doc for some exercises I'm working on. The code is fully self-contained, you just need an online connection to grab some data, and the following packages available on CRAN: `MASS`, `tidyverse`, `tidybayes`, `GGally`, `scales` and `brms`. 

This refuses to render to HTML when using the latest preview release (1.2.1153-1) but works just fine with the last official release (1.1.463).

[Rmd_doc.zip](https://github.com/rstudio/rstudio/files/2626211/Rmd_doc.zip)

Here are the system details, please let me know if you need any further information.

    RStudio Edition : Desktop
    RStudio Version : 1.2.1153-1
    OS Version      : Win10
    R Version       : 3.5.1

**Comment by philstraforelli** [comment] 2018-11-28 20:41
Sorry for being so unclear. RStudio just seems to get stuck after the creation of the .md file. Here's what it looks like:
![capture](https://user-images.githubusercontent.com/22040238/49180868-c3807b80-f30a-11e8-8818-57419c6f6e13.PNG)

It will sit like this for hours, until I hit the stop button. With version 1.1.463, the time elapsed from the creation of the .md document to the HTML document is maybe a second.

**Comment by kevinushey** [comment] 2018-11-28 21:52
Thanks; I can reproduce. This looks like yet another Pandoc issue 😞 

See also: https://github.com/rstudio/rstudio/issues/3661

**Comment by kevinushey** [comment] 2018-11-28 22:10
Pandoc 2.5 was just released; I suppose we could see if updating Pandoc fixes this issue.

**Comment by kevinushey** [comment] 2018-11-29 18:16
Looks like this is indeed fixed with Pandoc 2.5.

@jmcphers, how do you feel about us pulling another Pandoc update? (I can do the legwork)

**Comment by Schn3** [comment] 2018-11-30 13:03
Hi, I have exactly the same problem, can you tell me whats the simplest way to update pandoc?
I downloaded the file from pandoc but how do I integrade it in RStudio?

**Closed** 2018-11-30 20:43 UTC

**Comment by jmcphers** [comment] 2018-12-11 04:59
> Then, how can I set the pandoc parameter in RStudio?

Use the `pandoc_args` parameter in your YAML header. See an example here:

https://rmarkdown.rstudio.com/html_fragment_format.html#pandoc_arguments

**Comment by gaospecial** [comment] 2018-12-18 03:45
> I am still seeing this issue on RStudio 1.2.1186, with the builtin Pandoc 2.5. Knitting a fairly short RMarkdown file to HTML will often hang indefinitely - but frustratingly, not in a way I can reproduce, as a file that was consistently failing just started working while I was trying to put together this report.
> 
> Alternative HTML formats like `prettydoc::html_pretty` don't seem to have the same issues from what I've seen.
> 
> Allowing more memory for the pandoc process with `pandoc_args: ["+RTS", "-M1024M", "-RTS"]` also seemed to help, but not consistently.
> 
> **Update:** I've just done a bit more investigation and what seems to work most consistently is copying the command that RMarkdown is trying to run, and running it myself in Powershell. This seems to work regardless of whether I change the amount of memory available to pandoc - so there may be some issue introduced by the way RMarkdown is trying to call pandoc?

I replaced the pandoc executable with the latest 64-bit version (download from pandoc.org), and it can run smoothly without further modifying the pandoc args. 

So, it is a pandoc AND RStudio issues.

**Comment by kevinushey** [comment] 2018-12-18 03:54
That doesn't make sense to me. RStudio already uses the latest Pandoc release (2.5 64bit) in the current preview.

**Comment by onesandzeroes** [comment] 2018-12-18 04:36
I ended up trying the same solution as gaospecial, dropping the latest pandoc executable into the RStudio folder, and it seems to resolve all the issues, no need to modify pandoc args or anything. It did seem odd that they were both ostensibly Pandoc 2.5, although I'm pretty sure there was a difference in file sizes between the bundled version and the version I downloaded directly from the Pandoc github, suggesting they were not the same executable.

**Comment by kevinushey** [comment] 2018-12-18 05:18
That's bizarre! I'm seeing the exact same thing. I'll make sure RStudio gets the updated version of Pandoc 2.5.

**Comment by GegznaV** [comment] 2018-12-20 23:36
Pandoc 2.5 has an issue related to markdown documents conversion to other formats (jgm/pandoc#5166) and I quite often faced this inconvenience after RStudio updated Pandoc to 2.5. Thus I had to downgrade to 2.4 on my PC to get all my documents knitted. 

I think Pandoc 2.5 is not a good choice until the issue is not fixed.

**Comment by ande4148** [comment] 2020-09-11 14:50
> I ended up trying the same solution as gaospecial, dropping the latest pandoc executable into the RStudio folder, and it seems to resolve all the issues, no need to modify pandoc args or anything. It did seem odd that they were both ostensibly Pandoc 2.5, although I'm pretty sure there was a difference in file sizes between the bundled version and the version I downloaded directly from the Pandoc github, suggesting they were not the same executable.

This worked for me.  I downloaded the pandoc zip from https://github.com/jgm/pandoc/releases/tag/2.10.1
Then deleted the pandoc files in C:\Program Files\RStudio\bin\pandoc
Then replaced the two deleted files with the same files from the zip.
