### ISSUE TITLE
report crypto errors that occur when reading private keys

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9181] opened 2021-04-02 19:21 UTC
In `rsaSign()`, we report errors from `PEM_read_bio_RSAPrivateKey()` here:

https://github.com/rstudio/rstudio/blob/b2f3bc9748a1eb13de0506657a9f262314736d3f/src/cpp/core/system/Crypto.cpp#L147-L150

However, the use of `boost::system::errc::not_enough_memory` is most likely misleading: this may have failed for other reasons; e.g. because the key itself was invalid or could not be read.

(related to Pro ticket 59235)

**Comment by mikebessuille** [comment] 2021-04-12 17:36
This is a duplicate of https://github.com/rstudio/rstudio-pro/issues/2459.  Closing this.

**Closed by mikebessuille** 2021-04-12 17:36 UTC
Labels: backlog, bug, support
