### ISSUE TITLE
"Find in files" silently fails to work on folders with unusual names

### ISSUE THREAD

**Issue by lotard** [rstudio/rstudio#6595] opened 2020-04-05 00:17 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5033
    OS Version      :  10.15.4 MacOS
    R Version       :  3.6.3

### Steps to reproduce the problem
mkdir "\!folder"
echo "foobar" > \!folder/file.R
Rstudio -> Edit -> Find in Files -> type "foobar", point to the !folder (or folder above) -> Find
(won't see any hits)

### Describe the problem in detail
Can't find anything in files within folders starting with "!" (and probably other signs).

### Describe the behavior you expected
Be able to search folders like that.

- [X ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-04-06 14:28
@lotard Thank you for raising the issue. I can reproduce this on MacOS 10.15.4 using RStudio 1.3.935. I'll mark this as an issue to review as we continue development of RStudio.

That said, what shell are you using? I had to add a slash to recognize the exclamation mark in the folder name: `\!folder` This is both in in zsh and bash:

```
mkdir "\!folder"
echo "foobar" > \!folder/file.R
```

**Comment by lotard** [comment] 2020-04-06 14:41
Yes, I've noticed slash is essential, but clearly forgot to add it to the example. Thanks for flagging that.

**Comment by kevinushey** [comment] 2020-04-06 17:25
This is likely fixed in the v1.4 builds, as per https://github.com/rstudio/rstudio/pull/6572.

**Comment by Katzmann1983** [comment] 2020-04-08 12:22
> This is likely fixed in the v1.4 builds, as per #6572.

Can confirm, that the issue is fixed in the current build.

**Closed** 2020-09-06 00:25 UTC
Labels: bug, find in files, reproducible

**Comment by R-Hannibal** [comment] 2020-09-08 16:14
Adding the 'verified' label based off of user feedback (thanks for confirming @Katzmann1983!).
