### ISSUE TITLE
Show S4 methods in the outline

### ISSUE THREAD

**Issue by llrs** [rstudio/rstudio#13562] opened 2023-08-27 07:46 UTC
When writing S4 classes and methods the generics and methods do not appear in the outline.
I have a package with many S4 methods (and several S3 methods) with multiple definitions in the same file, from just two (A, A<-) to several related (A_to_B, B_to_A, A_to_C, C_to_C, ...). 

Not having the definition available in the outline makes it harder to navigate the files and find the right place to go (I don't know from memory the line where the definition starts).
It would be nice if they could be detected automatically and shown in the document outline.

As a workaround I am currently using titles `# $<- ###` to find them.
Another workaround I tried is using the key shortcut CTRL+arrows (Up and down) to move between function definitions.
But once a S4 definition is met the cursor doesn't move to the next S4 definition (`setMethod("B", signature = "A", definition = function(x, y, ...){})`, only the view moves.

I'm using RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-07) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

**Comment by kevinushey** [comment] 2023-08-28 18:24
Duplicate of https://github.com/rstudio/rstudio/issues/13133.

**Closed by kevinushey** 2023-08-28 18:24 UTC
Labels: enhancement, new
