### ISSUE TITLE
Constant errors when editing a file synced to Google Drive 

### ISSUE THREAD

**Issue by arencambre** [rstudio/rstudio#7131] opened 2020-06-15 00:05 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Windows 10
    R Version       : 4.0.1

### Steps to reproduce the problem
Edit a file that is saved in a folder that the Google Backup and Sync app is syncing to Google Drive.

### Describe the problem in detail
Repeatedly, you will get an error that says **The process cannot access the file because it is being used by another process**:
![image](https://user-images.githubusercontent.com/411495/84607271-fdc05800-ae71-11ea-9bde-5417182a1a5f.png)

Less commonly, you'll get an error that says **The file [filename] has changed on disk. Do you want to reload the file from disk and discard your unsaved changes?**:
![image](https://user-images.githubusercontent.com/411495/84610619-cb6a2700-ae80-11ea-808a-ef6d1a4d91f9.png)

#3837 's wording or comments suggests a belief that it would fix more than just Dropbox. It does not fix this problem with Google Drive.

This is the only software I use that has so many problems with Google Drive. It is highly desirable for RStudio to be compatible with Google Drive as it provides a recovery option for data loss in cases where version control cannot help, including between check-ins/pushes or if the user does not use version control.

### Describe the behavior you expected
Editing a file in a folder synced by Google Drive creates no errors.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-06-15 18:35
Internal note: this likely occurs because RStudio's autosave (which saves files to the project `.Rproj.user` folder) is attempting to access files currently read and locked by Google Drive.

We could also try alleviating this by allowing for a retry timeout when we're attempting to open a file handle.

**Comment by ronblum** [comment] 2020-06-15 19:53
2nd internal note: @kevinushey would this solution affect files outside of a project as well? I haven't been able to consistently reproduce this with just autosave, but I can consistently been able to do so by repeatedly typing and saving fast enough till Google Sync and I have been in conflict (not a realistic scenario, but it forces the issue).

**Comment by kevinushey** [comment] 2020-06-15 21:12
@ronblum: I believe this would affect files opened both inside and outside a project, as in each case files within the project's `.Rproj.user` will need to be updated.

**Comment by kevinushey** [comment] 2020-06-22 18:30
These errors are likely coming from here:

https://github.com/rstudio/rstudio/blob/18cbf55262fde15825aafa0d3764b2e82aba5467/src/cpp/shared_core/FilePath.cpp#L1387-L1403

We could potentially resolve this in a couple ways. If we see this particular error, we could:

1. Wait a small amount of time, and then try again to re-open the file;
2. Try also opening the file using `GENERIC_READ | GENERIC WRITE` (although this is more dangerous, since we could then end up attempting to read a file at the same time a process is trying to write to it)

**Comment by matthewberryman** [comment] 2020-09-04 04:44
It's not autosave—turning it off just simply stops it being a frequent issue. We are seeing this issue intermittently with Dropbox on manual save and with all autosave off, at ~ same frequency as reported [here](https://github.com/rstudio/rstudio/issues/3837#issuecomment-583811554).

Dropbox version 104.4.75, Windows 10 x64 (build 17763), R Studio 1.3.1073 and R 4.0.2.

Some sort of exponential back-off process variation on 1 would seem to me to be the best solution.

**Comment by kevinushey** [comment] 2020-10-16 20:48
Verified fixed in 1.4.945 -- I no longer see errors when attempting to save / modify files stored within a folder backed up by Google Backup and Sync.

In the case where RStudio and Google appear to be contending for file access, I notice that the save action does indeed pause and wait for a short period of time (<1s) before successfully saving the file.

**Comment by Thralni** [comment] 2020-11-18 16:51
Hello,
I'm reading here that this issue is 'verified fixed' but have no idea how I can get the Rstudio version that fixes it? I downloaded the newest one currently available and keep getting this constant error. Any help would be appreciated.
Best,
Benjamin

**Comment by kfeinauer** [comment] 2020-11-18 16:55
@Thralni You can get the latest 1.4 daily from https://dailies.rstudio.com/

**Comment by Thralni** [comment] 2020-11-18 17:11
Thanks!!

**Comment by bbjonz** [comment] 2022-02-15 16:51
Happening quite frequently with R 4.1.2 and Rstudio 2022.02.0 Build 442.  M1 Mac mini, Monterey and Google Drive.

**Comment by bbjonz** [comment] 2022-02-21 18:21
Thanks for looking into this.  Let me know if I can send/post output or logs.

**Comment by cchen22** [comment] 2023-06-12 07:32
Can anyone let me know the best solution for this problem with Google Drive by 2023? Thanks!

**Comment by thk686** [comment] 2023-12-01 19:01
The problem is that the directory .Rproj.user is required to exist within the project source tree. The .Rproj.user is not compatible with network drives. My guess is that RStudio uses git or something similar within this directory. Git is not compatible with network drives as it relies on specific checksumming behavior. There is a trivial fix that has been suggested but complete ignored by Posit/RStudio folks. If we had the option to place this directory outside of the project tree, these problems would disappear. This directory is only there to cache information. You can delete it and it will be recreated in the next session. Therefore, it does not need to be in the project tree. It could, for example, exist in our home directories or in scratch space somewhere. I cannot understand why this is not an option.

**Comment by gdickens** [comment] 2024-05-15 23:17
This still seems to be an issue. My solution is to close Google Drive before I start working on an R Project. I'll then start google drive again to sync everything once I'm finished working on the project. 

Obviously this isn't ideal.

**Comment by gtritchie** [comment] 2024-06-25 19:53
> This should be fixed in one the latest daily builds of the release in progress, [Cranberry Hibiscus 2024.07.0]

Note that the fix requires configuring the project to store `.Rproj.user` somewhere other than the cloud drive, see https://github.com/rstudio/rstudio/pull/14875.

**Comment by ronblum** [comment] 2024-07-09 12:34
Closing as fixed. If anyone still runs into this issue, please let us know!

**Closed by ronblum** 2024-07-09 12:34 UTC
Labels: bug, remote storage, need help verifying
