### ISSUE TITLE
Multiline indentation incorrect with vectors of highlighted colors

### ISSUE THREAD

**Issue by ahl27** [rstudio/rstudio#12734] opened 2023-02-21 17:58 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353 
    OS Version      : OSX 12.6.1
    R Version       :  4.2.1

### Steps to reproduce the problem
Create a vector of colors (ex. `c('black','red')`), then split it into multiple lines. The indentation of successive lines is larger than expected. 
### Describe the problem in detail

When creating vectors, breaking them into multiple lines typically restarts indentation to the first parenthesis of the first line. For example, when using enter to separate a vector of numerics, RStudio indents to the following:

```
x <- c(100,
       99,
       98)
```

This behavior is consistent across all vectors, except when using vectors that incorporate the new color highlighting syntax. Instead, these vectors indent to the end of the first element in the first line:
```
x <- c('red', 
            'black',
            'green')
```

### Describe the behavior you expected

Expected behavior should be consistent with other vector types:
```
x <- c('red', 
       'black',
       'green')
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-02-21 20:21
@ahl27 Thank you for raising this! The bug is covered by issue #12489 and will be fixed in the upcoming Cherry Blossom release, 2022.03.0.

**Closed by ronblum** 2023-02-21 20:21 UTC
Labels: bug, new

**Comment by ahl27** [comment] 2023-02-21 20:36
oops, I guess I missed that issue--thank you for the quick response!

**Comment by ronblum** [comment] 2023-02-21 20:40
@ahl27 No problem! I've done the same plenty of times. The best was when I've filed a bug that was a duplicate of an issue that I filed only a few days earlier. 😄
