### ISSUE TITLE
Rstudio freezes and then stops working when the butoon load workspace is pushed

### ISSUE THREAD

**Issue by alex2760** [rstudio/rstudio#4644] opened 2019-04-13 17:01 UTC
### System details

    RStudio Edition :  desktop
    RStudio Version : 1.2.1335
    OS Version      : Winodws 7
    R Version       : 64bit 3.4.4

### Steps to reproduce the problem
Rstudio starts normally
It downloads the workspace .Rdata from my working directory
When the button Load Workspace is pushed it freezes and then the pop up window 
Rstudio has stopped working appears "close program"
### Describe the behavior you expected
To proceed with downloading the workspace 

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3076477/diagnostics-report.txt)
[Uploading diagnostics-report.txt…]()

**Comment by ronblum** [comment] 2019-06-10 17:40
@alex2760 Thank you for raising the issue. I'm unable to reproduce it, though, on Windows 7 and several versions of R (3.4.4, 3.5.3, and 3.6.0). 
1) By "button," do you mean using the menu bar? Session -> Load Workspace
2) What happens when you try to do the same thing in the standalone R GUI?
3) Would you be willing to try [the current preview release](https://www.rstudio.com/products/rstudio/download/preview/) and see what happens?

**Comment by gadepallivs** [comment] 2019-10-19 20:16
I work with Rstudio on windows where data/code is on the shared drive. I noticed this after my recent update. When I copy code from web to Rstudio or after few launches app.r , r studio freezes.

**Comment by ronblum** [comment] 2020-01-03 17:54
@gadepallivs If I understand correctly, it looks like the freeze is occurring under different conditions. So, please open a new ticket with info for the issue you're running into. If the problem with Load Workspace, please update this ticket.

In the meantime, closing the ticket since there hasn't been any recent activity about the original issue.

**Closed by ronblum** 2020-01-03 17:54 UTC
Labels: repro needed
