### ISSUE TITLE
RStudio just shows a white screen, menu not working

### ISSUE THREAD

**Issue by slhck** [rstudio/rstudio#7353] opened 2020-07-15 07:02 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.3.959
    OS Version      :  Ubuntu 20.04
    R Version       :  3.6.3

### Steps to reproduce the problem

I have freshly installed the latest RStudio under Ubuntu:

```
sudo apt remote --purge rstudio
rm -rf ~/.rstudio ~/.rstudio-desktop ~/.config/rstudio
sudo dpkg -i rstudio-1.3.959-amd64.deb
```

Then I open RStudio.

### Describe the problem in detail

I only get a white screen, not showing any contents. The menu is visible, but clicking any menu item results in nothing.

![image](https://user-images.githubusercontent.com/582444/87513469-12625c80-c679-11ea-9e77-e6742c9fa959.png)

The diagnostics report is here: https://gist.githubusercontent.com/slhck/4e7755d1f80a9166271392e8623c487e/raw/986e18ca7c15dbbb09b77cee464a3840d207eed0/diagnostics.txt

When I run it via CLI, I get:

```
➜ rstudio                                               
../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
```

### Describe the behavior you expected

I expected the normal layout to be shown.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dmkaplan2000** [comment] 2020-07-15 13:49
I am getting lots of similar behavior. Not always, sometimes Rstudio works fine for a long time, but sometimes, particularly as I am moving through an Rmarkdown document, it will just hang showing the grey screen as Werner reports.

**Comment by slhck** [comment] 2020-07-15 13:51
In the meantime I got it to work, but that was just randomly. Then I closed RStudio and opened it again, same issue appeared.

**Comment by dmkaplan2000** [comment] 2020-07-15 14:08
This is similar to my experience. It seems to happen fairly randomly without a clear trigger. But for me, it happens often enough that it is becoming rather frustrating. If the rstudio powers that be have suggestions for more helpful debugging, I would be happy to carry that out. 

Note that I am running the same setup as Werner except that I am using R 4.0.

**Comment by gtritchie** [comment] 2020-07-15 15:37
This is a known issue on Ubuntu 20. Fixed in upcoming bugfix release https://rstudio.com/products/rstudio/download/preview/

**Comment by gtritchie** [comment] 2020-07-15 15:39
Duplicate of #6379

**Closed by gtritchie** 2020-07-15 15:39 UTC
Labels: duplicate
