### ISSUE TITLE
Popos/Ubuntu 22.04 - RStudio Daily: Copy+Paste not working

### ISSUE THREAD

**Issue by universal** [rstudio/rstudio#11329] opened 2022-06-01 12:19 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 461
    OS Version      :  Pop!Os (Ubuntu) 22.04
    R Version       : 4.2

### Steps to reproduce the problem
Open any file, enter some text, and try to copy and paste something using the context menu or keyboard shortcuts

### Describe the problem in detail

* Highlighting some text enables and right-clicking enables the Cut/Copy/Paste context-menu entries. Clicking on Cut or Copy and then clicking elsewhere in the document the context-menu entries are disabled.
* Copying some text using Ctrl+C and trying to paste it using Ctrl+V does not work either.
* Copying some text from outside of RStudio and pasting it, does not work either.

### Describe the behavior you expected
Copy + Paste works.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by universal** [comment] 2022-06-01 12:20
Happy to supply any missing details :-)

**Comment by ronblum** [comment] 2022-06-01 14:55
@universal Thank you for raising this! Checking the older build is on its own already helpful, so I appreciate it. I can't reproduce the issue though, using Ubuntu 22.04 with R 4.2.0 and GNOME. What desktop environment are you using?

@jgutman Do you have any suggestions of other information that @universal can provide?

**Comment by ronblum** [comment] 2022-06-02 15:24
@universal That's good to hear, and thank you for letting us know! I was reluctant to suggest reverting to build 452, so I'm glad to hear that build 467 works.

**Comment by universal** [comment] 2022-06-03 08:12
back to square one: after booting my machine today... again no copy/paste... no other process open...

marking some text -> ctrl+c -> ctrl+v leads to no visible changes, but marks the file as changed... so at least something is happening...


detailed version information, as I was curious about the electron version, but that seems to inhibit the same problem:
```
RStudio 2022.06.0-daily+467 "Spotted Wakerobin" Daily (bf3030ac3d4667619d7bc7367d780e372ad873c1, 2022-06-01) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2022.06.0-daily+467 Chrome/102.0.5005.61 Electron/19.0.1 Safari/537.36
```

gonna try with todays build(s), and see if it works after just uninstalling and reinstalling and see if a reboot "breaks" it...

**Comment by universal** [comment] 2022-06-03 08:35
after a reboot, still broken. Happy to supply any more details, do some debugging, ... Just clueless as to what to check now... Copy+Paste works in other applications :-)

**Comment by ronblum** [comment] 2022-06-03 16:21
[See also #11329]

**Comment by universal** [comment] 2022-06-08 07:06
daily build 491 (not the electron variant!) appears to be working again. even survived a reboot... will monitor the situation.

**Comment by mikebessuille** [comment] 2022-06-08 14:17
Notice that in #11111, per https://github.com/rstudio/rstudio/issues/11111#issuecomment-1147926965, the QT builds seem to now be fixed but Matheus is still reproducing this in Electron.  I think we should close 11329 and continue working on this in 11111 as an electron-specific issue.

**Comment by matheustavaresdev** [comment] 2022-06-08 14:23
Just tested it on https://dailies.rstudio.com/version/2022.06.0-daily+461/ and this behavior only occurs on the `Electron` build. Regular build works as expected. Closing this issue so this can be tracked on #11111

**Closed by matheustavaresdev** 2022-06-08 14:23 UTC
Labels: bug
