### ISSUE TITLE
text encoding issue in console with 1.2 preview, windows 10, cp1252 locale

### ISSUE THREAD

**Issue by dpprdan** [rstudio/rstudio#3658] opened 2018-10-12 07:58 UTC
I have a weird text encoding issue with with RStudio v1.2 desktop preview on windows 10 with the cp1252 locale. When I open a project created with RStudio pre-v1.2 and type a non-ASCII string into the console, it is printed as escapes. After I either open Tools > Project Options and close them without changing anything, or I run `sessioninfo::session_info()` (but not after `sessionInfo()`), the strings are printed with the correct glyphs. See my screen recordings below. 

![rstudio_encoding](https://user-images.githubusercontent.com/1423562/46855489-27ef8600-ce04-11e8-8ebb-06b09f5b774c.gif)
![rstudio_encoding2](https://user-images.githubusercontent.com/1423562/46855553-579e8e00-ce04-11e8-817d-90bfa79cca69.gif)

I would expect RStudio to print the glyphs right away. 

The problem does not seem to occur with project files that were created with v1.2, when opening the default RStudio window (i.e. not in a project), or in RGui.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1047
    OS Version      : Windows 10 (build 1803)
    R Version       : 3.5.1

**Comment by kevinushey** [comment] 2018-10-12 17:34
Try as I might, I can no longer get the problem to reproduce. Any chance you can provide some steps I could try running in order to reproduce the issue locally?

**Comment by dpprdan** [comment] 2018-10-12 18:00
I can reliably reproduce it when I open an old, i.e. pre-1.2 project. After I run session_info(), I can not get back to the faulty state (I think) without closing and opening RStudio again, though. 

Deleting the hidden .RStudio folder within the project directory (is that what it's called? Not at my work notebook right now) also solves the problem, but that is probably expected?

**Comment by dpprdan** [comment] 2018-10-12 18:06
What makes it even weirder, is that the € -> \u0080 mapping should not even be there, since that was fixed in R 3.5, as you are probably aware. The correct mapping would be \u20AC.

**Comment by kevinushey** [comment] 2018-10-12 18:31
Aha! I think I have a reproducible example.

1. Create an R script,
2. Insert some unicode text, e.g. '鬼',
3. Save that file,
4. Try running your snippet of code `c('ä', '€')` in the console.

You should see the erroneous output:

```R
> c('ä', '€')
[1] "\xe4"   "\u0080"
```

I'll see if we can learn more. Let me know if this is a solid repro for you as well.

**Comment by kevinushey** [comment] 2018-10-12 18:55
It looks like something is getting out-of-sync in the locale, as I'm seeing the following:

```R
> c('ä', '€')
[1] "\xe4"   "\u0080"
> Sys.getlocale()
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> c('ä', '€')
[1] "\xe4"   "\u0080"
> Sys.setlocale(locale = "English")
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> c('ä', '€')
[1] "ä" "€"
```

**Comment by kevinushey** [comment] 2018-10-13 01:42
I hunted this down and it's somehow caused by this PR: https://github.com/rstudio/rstudio/commit/30d15bffc5c10023380f5e6329e5031f1f379a30

I'll try to figure out what's going on!

**Comment by kevinushey** [comment] 2018-10-13 01:48
Looks like the underlying cause is actually a bug in R. One can reproduce in e.g. RGui with the following:

```R
Sys.setlocale(locale = "English")
print('ä') # okay
code <- "鬼"
parse(text = code, encoding = "UTF-8") . # parse error
print('ä') # error!
```

When I run this, I get:

```R
> Sys.setlocale(locale = "English")
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> print('ä')
[1] "ä"
> code <- "鬼"
> parse(text = code, encoding = "UTF-8")
Error in parse(text = code, encoding = "UTF-8") : 
  <text>:1:1: unexpected '<'
1: <
    ^
> print('ä')
[1] "\xe4"
```

It seems like the encoding set during `parse()` effectively leaks out and affects any future parse attempts when an error occurs. I'll file a bug for the R team and see if we can work around the issue locally.

**Comment by kevinushey** [comment] 2018-10-13 01:55
Filed a bug report: https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17484

**Comment by kevinushey** [comment] 2018-10-13 17:29
There should be a workaround for this issue coming to the next daily builds of RStudio.

The issue occurs whenever a parse error occurs if the encoding is supplied to `parse()`, e.g.

```R
Sys.setlocale()
print('ä')
parse(text = "!", encoding = "UTF-8")
print('ä')
```

which gives me, in RStudio and RGui:

```R
> Sys.setlocale()
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> print('ä')
[1] "ä"
> parse(text = "!", encoding = "UTF-8")
Error in parse(text = "!", encoding = "UTF-8") : 
  <text>:2:0: unexpected end of input
1: !
   ^
> print('ä')
[1] "\xe4"
```

**Comment by kevinushey** [comment] 2018-10-15 20:39
I believe this issue should be fixed in the latest daily builds. @dpprdan, if you're still seeing issues please feel free to re-open.

**Closed by kevinushey** 2018-10-15 20:39 UTC
Labels: bug, encoding

**Comment by dpprdan** [comment] 2018-10-16 10:31
Thanks @kevinushey! Sorry for falling silent, I was away for the weekend and did not have time to look at this again yet, but will do so ASAP.
