### ISSUE TITLE
Long lines not wrapped on project open

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#1759] opened 2017-11-16 12:55 UTC
<img width="926" alt="screen shot 2017-11-16 at 6 54 21 am" src="https://user-images.githubusercontent.com/4196/32892190-00e67eaa-ca9b-11e7-93e0-528d3db7b25e.png">

The lines are wrapped as soon as I adjust the window size or the position of the divider

**Comment by dfalty** [comment] 2017-11-16 16:03
I can't actually reproduce this on 1.1.383 or 1.2.176 (Mac). What version are you running?

**Comment by hadley** [comment] 2017-11-16 16:17
1.1.383, but it's existed for a long time.

Hmmm, but reproducing it might be more complicated than I thought. It might be more like this:

1. Open two rmarkdown documents; ensure both are wrapping.
1. Resize the editor to be much smaller.
1. Close and re-open RStudio.
1. Switch to the other RMarkdown document

I'm not sure if that's exactly the behaviour, but it definitely involves resizing the editor, re-opening RStudio, and a document that isn't opened by default.

**Comment by dfalty** [comment] 2017-11-16 16:49
Thanks for the additional input! I was able to get a 100% repro with the following steps on 1.1.383.

1. Open two rmarkdown documents; ensure both are wrapping.
2. Open rmd #2 and open the document outline.
3. Switch to rmd #1 and resize the editor to be smaller.
4. Close and re-open RStudio.
5. Switch to rmd #2. Observe the text being hidden by the document outline until a resize.

The kicker is I can't reproduce this on 1.2.176. Are you able to update and see if you can reproduce?

**Comment by hadley** [comment] 2017-11-16 21:33
I've upgraded and I'll let you know if I see it again.

**Comment by jmcphers** [comment] 2019-11-19 18:55
I'm guessing @hadley did not see it again, and since @darby was also not able to repro on 1.2, we can probably close this safely.

**Closed by jmcphers** 2019-11-19 18:55 UTC
Labels: repro needed
