### ISSUE TITLE
Source pane displays non-empty R script as empty

### ISSUE THREAD

**Issue by maciejkasinski** [rstudio/rstudio#1623] opened 2017-10-18 09:50 UTC
After opening an existing project in RStudio, one of my scripts "how_to_use-Ex.R" is displayed in source pane as though it was empty. You can see it isn't (size of 1.8 KB).
![image](https://user-images.githubusercontent.com/11080604/31711199-b0a523ce-b3f7-11e7-83c8-6ea5ea8e4918.png)
Fortunately, the script has not been erased. Reopening the script in RStudio solves empty display problem.

OS X 10.11.6 (15G31)
RStudio 1.1.383

**Comment by kevinushey** [comment] 2017-10-18 16:10
Does this always occur when you restart the IDE with that file open, or was this a one-time issue you noticed?

**Comment by etienne-s** [comment] 2017-10-19 12:38
It happened to me as well today. Closing the project and restarting RStudio did not solve anything, but reopening the script did.

@kevinushey For me it was a one-time issue.

Windows 7 x64
RStudio 1.1.383

**Comment by maciejkasinski** [comment] 2017-10-19 13:30
It happened two or three times. Maximum of 3 scripts were empty at once.

**Comment by tinu-schneider** [comment] 2017-10-21 08:34
Same here. 
If I open the (emptied) script in a new window ("Show in new window"), close this new window and open the file again from the files menu, the content shows up as expected. 

@kevinushey It happens from time to time, up to now in Shiny projects only.

@jmcphers A repro is hard to build - it happens randomly (up to now I dont see any pattern)

```r
Session info ---------------------------------------------------------                  
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, mingw32             
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  German_Switzerland.1252     
 tz       Europe/Berlin               
 date     2017-10-21    
```

**Comment by kevinushey** [comment] 2017-10-23 16:35
Can you share the output of a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report)? If the document is long, you might want to upload it as e.g. a [GitHub gist](https://gist.github.com) and share a link to that.

**Comment by tinu-schneider** [comment] 2017-11-05 20:20
The issue did not happen again - so I can't upload any diagnostics report.

**Comment by etienne-s** [comment] 2017-12-04 13:44
It happened to me again today. Here is a diagnostics report: [diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1527226/diagnostics-report.txt)

Note that I removed old log lines and that I anonymized a few elements. I kept the latest log lines but they were generated before I opened that project.

Also note that this morning I updated R from 3.4.2 to 3.4.3 (from Rgui, using `installr::updateR()`), just saying this in case it would be related.

**Comment by jmcphers** [comment] 2017-12-04 17:35
@kevinushey I pulled some state from someone experiencing this issue (ping me offline if you'd like the full data). What's happening in at least some cases is that the source database migration from 1.0 to 1.1 is failing for some files; the file gets moved, but its contents aren't transferred. In example I have, there isn't an obvious culprit -- some files are migrated successfully, but others (most) are not.

**Comment by kevinushey** [comment] 2018-01-02 23:48
I was able to reproduce this issue in the following way.

1. Create an RStudio project,
2. Open that project with RStudio v1.0,
3. Open a few files in that project,
4. Shut down the IDE,
5. Open the project with RStudio v1.1,
6. Try editing one of the open files,
7. Close and re-open RStudio v1.1,
8. Notice that the open document is empty.

I think this is because we don't fully migrate to the new format on the first transfer of files. On the first open of RStudio v1.1, the sources folder looks like this:

```
$ tree
.
├── per
│   ├── t
│   └── u
├── prop
│   ├── 2646FB5C
│   ├── 28A9DEA3
│   ├── DC6A99FB
│   └── INDEX
└── s-F955001D
    ├── 244D0217
    ├── 88798333
    ├── FAE2342D
    └── lock_file
```

After a close + re-opening of the IDE, it looks like this:

```
$ tree
.
├── per
│   ├── t
│   └── u
├── prop
│   ├── 2646FB5C
│   ├── 28A9DEA3
│   ├── DC6A99FB
│   └── INDEX
└── s-1794F329
    ├── 244D0217
    ├── 244D0217-contents
    ├── 88798333
    ├── 88798333-contents
    ├── FAE2342D
    ├── FAE2342D-contents
    └── lock_file
```

Because those `-contents` files aren't populated on the first run, we end up with property files written out with no contents after an autosave. To mitigate this, we should extract the contents out of each properties file during migration and write the associated `-contents` file.

**Comment by jmcphers** [comment] 2018-01-03 04:04
Backported fix to 1.1 in 906409e635ec22960400d08f0e512374a8030e65.

**Comment by ronblum** [comment] 2018-01-08 18:10
We have a preview release for an upcoming 1.1 patch at
   https://www.rstudio.com/products/rstudio/download/preview/
It addresses this bug. If any of you are still seeing this issue, you can try out the preview and see if it resolves the problem for you.

**Comment by gimeno09** [comment] 2019-12-05 16:26
Hi I still have this issue in my system- windows 10 and RStudio version Version 1.1.456 – © 2009-2018 RStudio, Inc.. I am seeing all data when i open the file with notepad but while opening in R, its blank file.

**Comment by johnDowee** [comment] 2020-01-11 08:40
Hi, the issue still persists. I did numerous re-installation but no way out. I am doing it with Anaconda3-2019.10-Windows and RStudio 1.1.456. The notepad shows the script intact but Studio editor is blank and knit produces output document correctly. It's funny and irritating...

Please share if there is a solution.

**Comment by johnDowee** [comment] 2020-01-11 13:59
> 
> 
> Hi, the issue still persists. I did numerous re-installation but no way out. I am doing it with Anaconda3-2019.10-Windows and RStudio 1.1.456. The notepad shows the script intact but Studio editor is blank and knit produces output document correctly. It's funny and irritating...
> 
> Please share if there is a solution.

I partially bypassed the issue by installing a higher version of RStudio outside Anaconda after reading this ![Update RStudio in Anaconda](https://community.rstudio.com/t/how-do-i-update-the-version-of-rstudio-in-anaconda/39799/3). Almost sure the issue is with RStudio 1.1.456.

**Comment by mmahmoudian** [comment] 2020-03-17 07:03
I am facing this issue on version 1.2.5033 of Rstudio server on hosted on my Ubuntu 16.04 desktop. The symptoms (file tree) are very similar to [what @kevinushey mentioned](https://github.com/rstudio/rstudio/issues/1623#issuecomment-354906042). I usually open the code in detached mode (detached from the panes by clicking "show in new window") to work on it on another vertical monitor. This probably the reason that every time I open the Rstudio I get another window open having two tabs, both are the same exact file and of course empty and not saved! every time I press the x on the top right corner of the tabs and select "Don't save", the next time I open the Rstudio it re-appears again!

![image](https://user-images.githubusercontent.com/390889/76830527-134fc280-682e-11ea-9f0b-4ce7ff52ca49.png)

**Comment by Stalwart-GS** [comment] 2020-04-01 11:27
I came across this issue while I was facing the same problem, but after various hit and trials and understanding what can be the causes of this problem, 
In my humble opinion, I think this problem is arising with the R Studio that come along with anaconda distributor because after various updations and looking up on the internet. 
This showing of empty files even I just updated it a second ago, is now solved when I installed the R studios from the origin site of R Studios with the latest version installed.
and then uninstalled that the version I got with anaconda distribution.
Personally, my issue is solved, So you can give this method a try in case if you have not already.

**Comment by Stalwart-GS** [comment] 2020-04-01 11:28
> 
> 
> Hi, the issue still persists. I did numerous re-installation but no way out. I am doing it with Anaconda3-2019.10-Windows and RStudio 1.1.456. The notepad shows the script intact but Studio editor is blank and knit produces output document correctly. It's funny and irritating...
> 
> Please share if there is a solution.

You can try what I just tried and it solved the issue for me.

**Comment by mmahmoudian** [comment] 2020-04-01 11:32
> I think this problem is arising with the R Studio that come along with anaconda distributor
@Stalwart-GS I personally hate anaconda and what it does to my system. it's been years that I'm avoiding it, and I've always (since day 1) have installed Rstudio from their official .deb file, and yet I have this issue, hence your hypothesis, unfortunately, does not stand.

**Comment by robbwh** [comment] 2020-04-02 21:55
@mmahmoudian There could be an issue with your workspace. I fixed my friend's Rstudio by pressing control-shift-F10 to clear the workspace, closing out of Rstudio, and opening it back up.

**Comment by mmahmoudian** [comment] 2020-04-03 09:34
@robbwh just checked it, nope, it does **not** fix the issue. This is clearly a bug in the way Rstudio is storing the open files

**Comment by ronblum** [comment] 2020-04-03 14:24
@mmahmoudian What version of R are you using and what browser are you using to connect to RStudio Server? And does the issue only occur when you have a file in a separate window?

**Comment by villalbac** [comment] 2020-04-05 01:18
> I am facing this issue on version 1.2.5033 of Rstudio server on hosted on my Ubuntu 16.04 desktop. The symptoms (file tree) are very similar to [what @kevinushey mentioned](https://github.com/rstudio/rstudio/issues/1623#issuecomment-354906042). I usually open the code in detached mode (detached from the panes by clicking "show in new window") to work on it on another vertical monitor. This probably the reason that every time I open the Rstudio I get another window open having two tabs, both are the same exact file and of course empty and not saved! every time I press the x on the top right corner of the tabs and select "Don't save", the next time I open the Rstudio it re-appears again!
> 
> ![image](https://user-images.githubusercontent.com/390889/76830527-134fc280-682e-11ea-9f0b-4ce7ff52ca49.png)

I had the issue with the Anaconda and RStudio 1.1.4.56. I opened the file in a new window or new project and now is working fine. No re-installation and no complicated fixes. It might be something on the configuration and the rendering. Forgot to mention that I'm on Windows 10 in case it has anything to do. Thank you!

**Comment by villalbac** [comment] 2020-04-05 01:26
> I was able to reproduce this issue in the following way.
> 
> 1. Create an RStudio project,
> 2. Open that project with RStudio v1.0,
> 3. Open a few files in that project,
> 4. Shut down the IDE,
> 5. Open the project with RStudio v1.1,
> 6. Try editing one of the open files,
> 7. Close and re-open RStudio v1.1,
> 8. Notice that the open document is empty.
> 
> I think this is because we don't fully migrate to the new format on the first transfer of files. On the first open of RStudio v1.1, the sources folder looks like this:
> 
> ```
> $ tree
> .
> ├── per
> │   ├── t
> │   └── u
> ├── prop
> │   ├── 2646FB5C
> │   ├── 28A9DEA3
> │   ├── DC6A99FB
> │   └── INDEX
> └── s-F955001D
>     ├── 244D0217
>     ├── 88798333
>     ├── FAE2342D
>     └── lock_file
> ```
> 
> After a close + re-opening of the IDE, it looks like this:
> 
> ```
> $ tree
> .
> ├── per
> │   ├── t
> │   └── u
> ├── prop
> │   ├── 2646FB5C
> │   ├── 28A9DEA3
> │   ├── DC6A99FB
> │   └── INDEX
> └── s-1794F329
>     ├── 244D0217
>     ├── 244D0217-contents
>     ├── 88798333
>     ├── 88798333-contents
>     ├── FAE2342D
>     ├── FAE2342D-contents
>     └── lock_file
> ```
> 
> Because those `-contents` files aren't populated on the first run, we end up with property files written out with no contents after an autosave. To mitigate this, we should extract the contents out of each properties file during migration and write the associated `-contents` file.

Thanks works for Anaconda on Windows 10 installations

**Comment by mmahmoudian** [comment] 2020-04-06 14:15
@ronblum
> @mmahmoudian What version of R are you using and what browser are you using to connect to RStudio Server? And does the issue only occur when you have a file in a separate window?

As far as I understand, it should not matter what browser i use, but for the sake of the argument:
On the server side (`sessionInfo()`):

> R version 3.6.0 (2019-04-26)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.6 LTS

On the client side (Firefox About, `lsb_release -a`):
> Firefox 74.0.1 (64-bit)
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.4 LTS
> Release:	18.04
> Codename:	bionic

-------
@villalbac 
> I had the issue with the Anaconda and RStudio 1.1.4.56. I opened the file in a new window or new project and now is working fine. No re-installation and no complicated fixes. It might be something on the configuration and the rendering. Forgot to mention that I'm on Windows 10 in case it has anything to do. Thank you!

You are right that the new project have fixed that. It will "fix" it since it ignores the issues with the existing project and moves on. The bug still exists and it's a matter of time and [yet to be found] right circumstances that you face it again.

**Comment by margar37** [comment] 2020-04-11 20:39
I have the same problem. I am using R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
Is there any solution available?

**Comment by kevinushey** [comment] 2020-04-11 21:30
FWIW, the latest release of the RStudio v1.1 series is v1.1.463, available at https://rstudio.com/products/rstudio/older-versions/. That version should presumedly have the fix.

Alternatively, you should consider upgrading to the latest release (currently v1.2; soon to be v1.3).

**Comment by Azures729** [comment] 2020-11-10 20:39
I was able to fix by going to

**File** > **Reopen with Encoding...** > Select **UTF-8**

I also chose **Set as default encoding for source files**

**Comment by bmk316** [comment] 2021-01-15 03:48
Thanks so much Azures729!

**Comment by bmk316** [comment] 2021-01-15 03:48
> I was able to fix by going to
> 
> **File** > **Reopen with Encoding...** > Select **UTF-8**
> 
> I also chose **Set as default encoding for source files**

Thanks so much!!!

**Comment by Eribakova** [comment] 2021-02-10 21:45
thank you! worked for me too.

**Comment by ml1230** [comment] 2021-02-13 05:58
> I was able to fix by going to
> 
> **File** > **Reopen with Encoding...** > Select **UTF-8**
> 
> I also chose **Set as default encoding for source files**

Thank you so much

**Comment by hansobro000** [comment] 2021-03-07 04:09
This happened to me as well. As mentioned earlier, my issue had to do with the Anaconda version. I fixed it by installing Rstudio and then re-downloading the latest version from their official website.

**Comment by samzipper** [comment] 2022-05-04 15:04
Had this issue after updating to R 4.2.0/RStudio 2022.02.2 Build 485 and @Azures729 solution worked as well.

**Comment by Futats** [comment] 2022-05-12 17:55
Same as @samzipper : I just uninstalled RStudio and installed from RStudio.com and I still encounter this issue in build 485. Reopen in UTF-8 does make things visible, but all .r files I have tried open apparently blank when opened with my system default ISO-8859-1.

**Release:** RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19)

**Comment by ronblum** [comment] 2022-05-12 18:55
@samzipper and @Futats what operating systems are you using? 

Triage: Possible regression.

**Comment by samzipper** [comment] 2022-05-12 19:02
@ronblum Thanks for investigating - to provide some more detail, re-opening with encoding works, but I have to re-do it with each source file. Setting UTF-8 as default it doesn't seem to carry over from file to file, either within the same RStudio session or across multiple sessions.

**RStudio**: "Prairie Trillium" Release (8acbd38b, 2022-04-19) for Windows
**R**: R version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics"

**Windows**:
Edition	Windows 10 Pro
Version	21H2
Installed on	‎8/‎4/‎2021
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by Futats** [comment] 2022-05-12 19:26
For me, setting UTF-8 as the default worked for all .r files I tried and persisted across RStudio reboots, but the issue comes back for every file if I return to my system default ISO-8859-1.

**RStudio:** "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for Windows
**R:** R version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics"

**Windows:**
Windows 10 Enterprise
Version 1809
OS build 17763.2746
Experience Windows Feature Experience Pack 120.2212.4170.0

**Comment by AlexSiormpas** [comment] 2022-05-13 08:59
> I was able to fix by going to
> 
> **File** > **Reopen with Encoding...** > Select **UTF-8**
> 
> I also chose **Set as default encoding for source files**

God bless you! The solution worked for me too!

**Comment by jgutman** [comment] 2022-05-13 12:14
FYI @kevinushey penny for your thoughts

**Comment by kevinushey** [comment] 2022-05-13 16:42
This appears pretty serious to me. It's likely related to the changes in R 4.2.0 on Windows to use UTF-8 as the default locale.

I can also reproduce whenever I try to re-save a "large" document (larger than 1kb on disk) with a non-UTF-8 encoding. When I do this, the file saved on disk is now size 0. As far as I can see, there is no error logged or anything else; we're just silently losing the file contents.

My guess is that the code here is silently failing for some reason:

https://github.com/rstudio/rstudio/blob/925ba91c701782b4a3b375fba7852df50b5652eb/src/cpp/session/modules/SessionSource.cpp#L446-L468

If that's the case, stepping through this code may be fruitful:

https://github.com/rstudio/rstudio/blob/925ba91c701782b4a3b375fba7852df50b5652eb/src/cpp/r/RUtil.cpp#L145-L200

**Comment by kevinushey** [comment] 2022-05-13 17:30
I've filed https://github.com/rstudio/rstudio/issues/11206 to track this particular iteration of the issue. Note that the issue should only effect RStudio on Windows with R 4.2.0. Please direct any other follow-up there.

**Closed by kevinushey** 2022-05-13 17:30 UTC
Labels: bug, windows, encoding, source editor, current
