### ISSUE TITLE
Function argument on new line is indented by 4 spaces

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudio#10752] opened 2022-03-08 19:04 UTC
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.6.0.189
    OS Version      : OS X  12.2.1
    R Version       : R version 3.6.3 (2020-02-29)

### Steps to reproduce the problem

Ensure that `use_spaces_for_tab` is enabled and `num_spaces_for_tab` is 2.

```r
rstudioapi::writeRStudioPreference("use_spaces_for_tab", TRUE)
rstudioapi::writeRStudioPreference("num_spaces_for_tab", 2L)
```

Type out the following function definition.

```r
demo <- function(
  first_arg = TRUE,
  second_arg = FALSE
) {
  # body
}
```

The editor will place `first_arg` at column 4, rather than at column 2, regardless of the `use_spaces_for_tab` or `num_spaces_for_tab` settings:

```r
demo <- function(
    first_arg = TRUE,
  second_arg = FALSE
) {
  # body
}
```

Select all of the text for the function definition and run "Reindent Selection" (Cmd/Ctrl + I). The indentation of the first argument is not changed.

Remove the two spaces before the first argument and select the function definition again. Run "Reindent Selection". The extra indentation is added back to the first argument.

### Describe the problem in detail

https://user-images.githubusercontent.com/5420529/157307197-dd7ece9d-cf10-444d-978c-1b2221c27c83.mp4

### Describe the behavior you expected

1. I expected that all arguments would have consistent indentation.
2. I expected that Reindent Selection would restore consistent indentation.

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2022-03-09 19:29
The attempt to double-indent parameters here is intentional -- see https://style.tidyverse.org/functions.html#long-lines-1.

I'm not able to reproduce the mismatched indentation, though -- I consistently see an indent of 4 spaces for the function parameters. Can you think of anything else that might be affecting that behavior?

**Comment by gadenbuie** [comment] 2022-03-09 21:24
I also have `auto_detect_indentation = TRUE` (default is `FALSE`)?

Here are my current user-level prefs (minus few irrelevant preferences).

```json
{
  "auto_detect_indentation": true,
  "check_arguments_to_r_function_calls": true,
  "check_unexpected_assignment_in_function_call": true,
  "console_double_click_select": true,
  "continue_comments_on_newline": true,
  "doc_outline_show": "sections_and_chunks",
  "editor_keybindings": "vim",
  "font_size_points": 12,
  "highlight_r_function_calls": true,
  "highlight_selected_line": true,
  "jobs_tab_visibility": "shown",
  "latex_preview_on_cursor_idle": "inline_only",
  "load_workspace": false,
  "posix_terminal_shell": "zsh",
  "rainbow_parentheses": true,
  "remove_history_duplicates": true,
  "reuse_sessions_for_project_links": true,
  "rmd_chunk_output_inline": false,
  "rmd_viewer_type": "pane",
  "save_files_before_build": true,
  "save_workspace": "never",
  "scroll_past_end_of_document": true,
  "shiny_background_jobs": true,
  "shiny_viewer_type": "pane",
  "show_hidden_files": true,
  "show_indent_guides": true,
  "syntax_color_console": true,
  "terminal_track_environment": false,
  "wrap_tab_navigation": false
}
```

Project prefs include

```json
{
  "auto_append_newline": true,
  "default_encoding": "UTF-8",
  "default_latex_program": "pdfLaTeX",
  "default_sweave_engine": "Sweave",
  "num_spaces_for_tab": 2,
  "root_document": "",
  "strip_trailing_whitespace": true,
  "use_roxygen": true,
  "use_spaces_for_tab": true,
  "visual_markdown_editing_wrap": "sentence"
}
```

**Comment by gadenbuie** [comment] 2022-03-09 21:28
> The attempt to double-indent parameters here is intentional -- see [style.tidyverse.org/functions.html#long-lines-1](https://style.tidyverse.org/functions.html#long-lines-1).

Is there any chance of adding a preference to control this? I strongly prefer 2 space indents everywhere and I suspect many other people will have strong opinions and feelings around this as well.

**Comment by gadenbuie** [comment] 2022-03-09 22:13
It's weird. I can't reproduce this now on my work machine. It happened for me in the first session after installing yesterday's 2022.06 daily, but I've since closed down all IDEs and re-opened them (which I also did to install the daily).

On my personal machine, where I'm currently using `2022.02.0+443` I still see the same unexpected behavior: only the first line is double-indented but subsequent lines are single-indented.

**Comment by kevinushey** [comment] 2022-03-09 23:00
> Is there any chance of adding a preference to control this? I strongly prefer 2 space indents everywhere and I suspect many other people will have strong opinions and feelings around this as well.

We can do that; I could definitely see users wanting to control this.

I'll also play around and see if I can find a way to reproduce this locally as well.

**Comment by gadenbuie** [comment] 2022-03-10 02:09
I figured out the missing preference: `vertically_align_arguments_indent`. When disabled, I get the behavior above and toggling it back on puts all arguments in the same column (double indent). 

```r
# function argument indentation mismatch
rstudioapi::writeRStudioPreference("use_spaces_for_tab", TRUE)
rstudioapi::writeRStudioPreference("num_spaces_for_tab", 2L)
rstudioapi::writeRStudioPreference("vertically_align_arguments_indent", FALSE)

# function arguments all double-indented
rstudioapi::writeRStudioPreference("vertically_align_arguments_indent", TRUE)
```

Personally, I'd be happy if `vertically_align_arguments_indent = FALSE` was the way to disable the tidyverse double-indent style.

**Comment by ronblum** [comment] 2022-05-13 18:50
I think this is a duplicate of #11101. (Please correct me if I'm wrong!) I'll close this one, since the other one was given a target release, but I'll copy over the last comment.

**Closed by ronblum** 2022-05-13 18:50 UTC
