### ISSUE TITLE
[Windows] shell with clobbered HOME environment variable

### ISSUE THREAD

**Issue by mbojan** [rstudio/rstudio#6801] opened 2020-05-04 13:44 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Windows 10
    R Version       :  4.0.0

### Steps to reproduce the problem

1. Open RStudio, no project active
2. Open Tools/Shell... and close it
3. Open Tools/Shell... for the second time, inspect $HOME

### Describe the problem in detail

Opening the shell for the first time in RStudio session works OK resulting with:

![shell1](https://user-images.githubusercontent.com/636574/80971935-bfb92880-8e1d-11ea-8d62-e83d0e3ca1ef.PNG)

Closing it and opening for the second time results with

![shell2](https://user-images.githubusercontent.com/636574/80971958-ca73bd80-8e1d-11ea-8217-607e76263c3f.PNG)

Clearly the `HOME` variable is wrong. This persists even if, say, I open a project and re-open the Shell again. I need to restart RStudio.

### Describe the behavior you expected

Clearly opening the Shell should work properly and identically every time.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mbojan** [comment] 2020-05-04 21:32
I also checked if it is so with the Tools/Terminal. The `HOME` variable points to `/c/Users/mbojanowski`, but there is the following error message at the very top before initial prompt:

```
/usr/bin/cut: you must specify a list of bytes, characters, or fields           Try '/usr/bin/cut --help' for more
information.
```

I tried reinstalling RStudio with no avail. I am wondering if any other settings might interfere here. I'll be happy to help to debug this further because it is really annoying.

**Comment by gtritchie** [comment] 2020-05-04 21:49
I'm going to take a look. Notice you are using R 4.0, we are working through some issues with it and RStudio; do you happen to know if this was working correctly before you upgraded to R 4.0?

**Comment by gtritchie** [comment] 2020-05-04 22:22
I was able to reproduce with R 3.6.3, RStudio 1.2.5042, and Git For Windows v2.26.2.

**Comment by kevinushey** [comment] 2020-05-04 22:36
I believe this is a dupe -- let me find the old issue...

**Comment by gtritchie** [comment] 2020-05-04 22:40
Yes, also repros on 1.1, so been around a while.

**Comment by gtritchie** [comment] 2020-05-04 22:57
Not _really_ same thing as the terminal, but I lump Tools / Shell under terminal label for tracking purposes.

**Comment by gtritchie** [comment] 2020-05-04 23:03
This is fixed in RStudio 1.3; you can download the latest preview release of 1.3 at:

https://rstudio.com/products/rstudio/download/preview/

**Closed by gtritchie** 2020-05-04 23:03 UTC
Labels: desktop, terminal, windows

**Comment by mbojan** [comment] 2020-05-05 00:06
Great! Thanks!

**Comment by gtritchie** [comment] 2020-05-06 01:04
Tracked down the original issue and fix. #3663
