### ISSUE TITLE
C++ diagnostics give false errors

### ISSUE THREAD

**Issue by helske** [rstudio/rstudio#8901] opened 2021-02-05 10:55 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  Daily build 1.4.1548, same issue was also present in older versions
    OS Version      :  Windows 10
    R Version       :  4.0.2

### Steps to reproduce the problem

1. Run `Rcpp::Rcpp.package.skeleton("foo")`
2. Create an R project using the folder created above

### Describe the problem in detail

Opening the `rcpp_hello_world.cpp`, I see diagnostic errors:
```
'Rcpp::CharacterVector' (aka 'int') is not a class, namespace, or enumeration
'Rcpp::NumericVector' (aka 'int') is not a class, namespace, or enumeration
'Rcpp::List' (aka 'int') is not a class, namespace, or enumeration
```

More details:
```
> .rs.setClangDiagnostics(2)
Attemping to load libclang for x86_64-w64-mingw32 
C:/Program Files/RStudio/bin/rsclang/x86_64/libclang.dll
   LOADED: 5.0.2

Restarting R session...

CLANG INDEXING: C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp
# RESTORING PACKAGE COMPILATION CONFIG ----
C:/MyTemp/repos/foo/.Rproj.user/58796C0E/cpp-compilation-config
{
    "args": [
        "-IC:/Program Files/RStudio/resources/libclang/builtin-headers/5.0.2",
        "-IC:/Program Files/RStudio/resources/libclang/builtin-headers/libc++/5.0.2",
        "-IC:/MyTemp/Rlibs/Rcpp/include",
        "-std=gnu++11",
        "-IC:/Devel/R/include",
        "-DNDEBUG"
    ],
    "pch": "Rcpp",
    "is_cpp": true,
    "hash": "15989048671612521884",
    "compiler": "14695981039346656037"
}
# GENERATING PRECOMPILED HEADERS ----
[
    "-IC:/Program Files/RStudio/resources/libclang/builtin-headers/5.0.2",
    "-IC:/Program Files/RStudio/resources/libclang/builtin-headers/libc++/5.0.2",
    "-IC:/MyTemp/Rlibs/Rcpp/include",
    "-IC:/Devel/R/include",
    "-DNDEBUG",
    "-IC:/MyTemp/Rlibs/Rcpp/include",
    "-std=gnu++11"
]

C:/Program Files/RStudio/resources/libclang/builtin-headers/libc++/5.0.2\math.h:301:15: fatal error: 'math.h' file not found
# COMPILATION ARGUMENTS ----
[
    "-IC:/Program Files/RStudio/resources/libclang/builtin-headers/5.0.2",
    "-IC:/Program Files/RStudio/resources/libclang/builtin-headers/libc++/5.0.2",
    "-IC:/MyTemp/Rlibs/Rcpp/include",
    "-std=gnu++11",
    "-IC:/Devel/R/include",
    "-DNDEBUG",
    "-include-pch",
    "C:/Users/jovetale/AppData/Local/Temp/Rtmpi0UMSb/rstudio/libclang/precompiled/Rcpp/0152D82B/1.0.6-x86_64-w64-mingw32-78730-5.0.2/Rcpp-std=gnu++11.pch",
    "-v"
]
  (Creating new index)
clang version 5.0.2 (tags/RELEASE_502/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: 
ignoring nonexistent directory "lib\clang\5.0.2\include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 10.0/VC/include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 9.0/VC/include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 9.0/VC/PlatformSDK/Include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 8/VC/include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 8/VC/PlatformSDK/Include"
#include "..." search starts here:
#include <...> search starts here:
 C:/Program Files/RStudio/resources/libclang/builtin-headers/5.0.2
 C:/Program Files/RStudio/resources/libclang/builtin-headers/libc++/5.0.2
 C:/MyTemp/Rlibs/Rcpp/include
 C:/Devel/R/include
End of search list.
C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp:8:25: error: 'Rcpp::CharacterVector' (aka 'int') is not a class, namespace, or enumeration
C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp:9:25: error: 'Rcpp::NumericVector' (aka 'int') is not a class, namespace, or enumeration
C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp:10:25: error: 'Rcpp::List' (aka 'int') is not a class, namespace, or enumeration
TOTAL MEMORY: 22 mb (rcpp_hello_world.cpp)
PERFORMANCE 2106 ms (rcpp_hello_world.cpp)
CLANG INDEXING: C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp
CLANG REMOVE INDEX: C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp
# COMPILATION ARGUMENTS ----
[
    "-IC:/Program Files/RStudio/resources/libclang/builtin-headers/5.0.2",
    "-IC:/Program Files/RStudio/resources/libclang/builtin-headers/libc++/5.0.2",
    "-IC:/MyTemp/Rlibs/Rcpp/include",
    "-std=gnu++11",
    "-IC:/Devel/R/include",
    "-DNDEBUG",
    "-include-pch",
    "C:/Users/jovetale/AppData/Local/Temp/Rtmpi0UMSb/rstudio/libclang/precompiled/Rcpp/0152D82B/1.0.6-x86_64-w64-mingw32-78730-5.0.2/Rcpp-std=gnu++11.pch",
    "-v"
]
  (Creating new index)
clang version 5.0.2 (tags/RELEASE_502/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: 
ignoring nonexistent directory "lib\clang\5.0.2\include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 10.0/VC/include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 9.0/VC/include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 9.0/VC/PlatformSDK/Include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 8/VC/include"
ignoring nonexistent directory "C:/Program Files/Microsoft Visual Studio 8/VC/PlatformSDK/Include"
#include "..." search starts here:
#include <...> search starts here:
 C:/Program Files/RStudio/resources/libclang/builtin-headers/5.0.2
 C:/Program Files/RStudio/resources/libclang/builtin-headers/libc++/5.0.2
 C:/MyTemp/Rlibs/Rcpp/include
 C:/Devel/R/include
End of search list.
C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp:8:25: error: 'Rcpp::CharacterVector' (aka 'int') is not a class, namespace, or enumeration
C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp:9:25: error: 'Rcpp::NumericVector' (aka 'int') is not a class, namespace, or enumeration
C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp:10:25: error: 'Rcpp::List' (aka 'int') is not a class, namespace, or enumeration
TOTAL MEMORY: 22 mb (rcpp_hello_world.cpp)
PERFORMANCE 497 ms (rcpp_hello_world.cpp)
C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp:8:25: error: 'Rcpp::CharacterVector' (aka 'int') is not a class, namespace, or enumeration
C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp:9:25: error: 'Rcpp::NumericVector' (aka 'int') is not a class, namespace, or enumeration
C:/MyTemp/repos/foo/src/rcpp_hello_world.cpp:10:25: error: 'Rcpp::List' (aka 'int') is not a class, namespace, or enumeration
```

### Describe the behavior you expected

No errors/warnings.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2021-02-08 18:20
@kevinushey Is this a regression in Juliet Rose? (Also, does this R code correspond to some user gesture like creating a new Rcpp project from the UI?)

**Comment by kevinushey** [comment] 2021-02-08 19:27
This appears to be a regression.

> Also, does this R code correspond to some user gesture like creating a new Rcpp project from the UI?)

Yes: https://github.com/rstudio/rstudio/blob/eb4205ce735cb5aaf59c4f9472ae563bf53a8011/src/cpp/session/modules/SessionProjectTemplate.cpp#L581

**Comment by kevinushey** [comment] 2021-03-29 22:54
Appears to be working for me with the latest daily build (1.4.1654):

<img width="239" alt="Screen Shot 2021-03-29 at 3 53 49 PM" src="https://user-images.githubusercontent.com/1976582/112909808-fab3f280-90a6-11eb-86d9-60facb45aead.png">

If you'd like, you can download and test the latest version at https://dailies.rstudio.com/.

**Comment by kevinushey** [comment] 2021-04-21 16:10
Duplicate of https://github.com/rstudio/rstudio/issues/4685.

**Closed by kevinushey** 2021-04-21 16:10 UTC
Labels: bug, c++
