### ISSUE TITLE
GitHub requires ECDSA instead of RSA for new keys

### ISSUE THREAD

**Issue by jeroen** [rstudio/rstudio#10807] opened 2022-03-19 14:26 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      :  Mac
    R Version       : 4.1

The IDE lets uses generate an RSA keypair (under global options -> git/svn), however as of recently [github restricts use of newly generated rsa keys](https://github.blog/2021-09-01-improving-git-protocol-security-github/). This is particularly a problem because R packages gert and libgit2 (and perhaps others) don't support the newly required RSA SHA-2 signatures yet, as described in the [post](https://github.blog/2021-09-01-improving-git-protocol-security-github/):

> __libgit2 and other Git clients__
> If you’re using libgit2 or another piece of code using libssh2, we recommend you use libssh2 1.9.0 or newer and an ECDSA key, since it does not yet support RSA with SHA-2. 

Here is an actual bug reported by a user that used the rstudio generated rsa key: https://github.com/r-lib/gert/issues/172

So the recommendation from the blog post is to switch to ecdsa instead of rsa for newly generated keys. I think that makes sense, ecdsa has been supported in openssl and openssh for a very long time now, it's available in every os.

**Comment by jennybc** [comment] 2022-03-19 15:42
I think this is a duplicate of #8255.

**Comment by ronblum** [comment] 2022-03-21 12:20
Closing as a duplicate of #8255, but I added the information above to it.

**Closed by ronblum** 2022-03-21 12:20 UTC
Labels: duplicate
