### ISSUE TITLE
List of "recent files" is empty when new window is open

### ISSUE THREAD

**Issue by jaySf** [rstudio/rstudio#4990] opened 2019-06-21 07:34 UTC
When I notch a script into a new window ("show in new window"), the list of "recent files" seems to get deleted somehow. 

### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1511
    OS Version      : Win 7 pro
    R Version       : R version 3.6.0 (2019-04-26)

### Steps to reproduce the problem
open two scripts and notch one of them into a new window, then try to open list of recent files (see image)

### Describe the problem in detail
![recemp](https://user-images.githubusercontent.com/32597794/59905573-e25d7100-9406-11e9-977e-b7000563ec0a.png)

### Describe the behavior you expected
accessing the list of recent files

**Comment by pascaloettli** [comment] 2019-06-21 08:54
I think this issue was [already mentioned](https://github.com/rstudio/rstudio/issues/3968#issuecomment-472133277). Exists in `1.2.1522` and `1.3.264`.

**Comment by ronblum** [comment] 2019-06-21 13:51
Agreed, this is a duplicate of #3968. Thanks!

**Closed by ronblum** 2019-06-21 13:51 UTC

**Comment by jaySf** [comment] 2019-06-23 11:35
Thanks guys, sorry for the dupe, still annoying though. :)
