### ISSUE TITLE
Reliable aborts even if the R session doesn't respond to interrupts

### ISSUE THREAD

**Issue by krlmlr** [rstudio/rstudio#8865] opened 2021-02-01 18:08 UTC
Currently, if the R session is busy in non-interruptible code (e.g. in C/C++ code), clicking the "Stop" button doesn't terminate the R session. Is it possible to implement forceful shutdown of the R session, so that at least the open files and the active project are not lost?

The following example shows where this occurs in practice: an SQL query that can be made arbitrarily complex.

``` r
library(RSQLite)

make_query <- function(range) {
  paste0(
    "SELECT MAX(",
    paste0("a", range, " * ", 2^range, collapse = " + "),
    ")\n",
    "FROM ",
    paste0("(SELECT 0 AS a", range, " UNION SELECT 1) t", range, collapse = " CROSS JOIN ")
  )
}

writeLines(make_query(0:2))
#> SELECT MAX(a0 * 1 + a1 * 2 + a2 * 4)
#> FROM (SELECT 0 AS a0 UNION SELECT 1) t0 CROSS JOIN (SELECT 0 AS a1 UNION SELECT 1) t1 CROSS JOIN (SELECT 0 AS a2 UNION SELECT 1) t2

con <- dbConnect(SQLite())

dbGetQuery(con, make_query(0:3))
#>   MAX(a0 * 1 + a1 * 2 + a2 * 4 + a3 * 8)
#> 1                                     15

system.time(dbGetQuery(con, make_query(0:10)))
#>    user  system elapsed 
#>   0.002   0.000   0.002
system.time(dbGetQuery(con, make_query(0:20)))
#>    user  system elapsed 
#>   0.873   0.000   0.873
system.time(dbGetQuery(con, make_query(0:21)))
#>    user  system elapsed 
#>   1.848   0.000   1.848

# Long timeout
# dbGetQuery(con, make_query(0:31))
```

<sup>Created on 2021-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

CC @hadley.

**Comment by kevinushey** [comment] 2021-02-01 19:59
Normally, after a set of failed interrupts, you should see something like:

<img width="287" alt="Screen Shot 2021-02-01 at 11 59 02 AM" src="https://user-images.githubusercontent.com/1976582/106511317-ea0b4580-6484-11eb-922a-dc8946ee0ca2.png">

and clicking Yes should forcefully terminate the process. However, at least in my case, that didn't seem to work ...

**Comment by kevinushey** [comment] 2021-02-01 20:00
And FWIW here's a simple way to get the `rsession` stuck in this state:

`````
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
void hang(NumericVector x) {
  while (x.size() < 16) {}
}

/*** R
hang(1:8)
*/
`````

**Comment by hadley** [comment] 2021-02-01 20:34
FWIW that terminate button has never reliably worked for me, and now I alway just force quit RStudio.

**Comment by jmcphers** [comment] 2021-02-16 19:56
This is another facet of the core problem discussed in https://github.com/rstudio/rstudio/issues/2038, which is that a lot of RStudio code and R code runs in the same process, so (in this instance) we can't hear the request to terminate R since R is busy (HOW IRONIC)

**Comment by kevinushey** [comment] 2021-02-16 20:30
The part that surprises me here is that we should be using our special `abort` RPC, which gets handled up-front on the listener thread:

https://github.com/rstudio/rstudio/blob/78065d206958c4c7f69b58007bc81a96fac8745c/src/cpp/session/http/SessionHttpConnectionListenerImpl.hpp#L301-L311

But we still never see the abort.

**Comment by jeffvroom** [comment] 2021-06-09 02:34
I think this is improved with the async-rpc. I can reliably terminate the R session from the menu when running Kevin's hang(1:8) test (above), even after clicking on the stop button enough times to use up all of the browser connections.

The curious thing is that I'm not seeing the dialog after clicking on the stop button a number of times and waiting. I do recall seeing that before.... can anyone confirm that it's supposed to do that?  Under what conditions?

**Comment by kevinushey** [comment] 2021-06-09 21:18
For reference, the code that handles this lives here:

https://github.com/rstudio/rstudio/blob/0d279a2bf77c910ce1eb8f583d92416ad7036d6e/src/gwt/src/org/rstudio/studio/client/application/ApplicationInterrupt.java#L76-L121

From reading the code, I believe the intention was for that dialog to display if the user attempted to interrupt 3 or more times, and none of those interrupt requests ever received a response.

Because interrupts are serviced offline, I suspect that interrupt responses are always being received (even if the interrupt request didn't actually force R to interrupt execution) so I believe it's possible, in some cases, for the console to remain "busy" but the repeated interrupt attempts still won't show that dialog.

**Comment by jeffvroom** [comment] 2021-07-07 02:07
Fixed in PR https://github.com/rstudio/rstudio/pull/9568  Thanks Kevin for the help!

**Comment by ronblum** [comment] 2021-08-02 13:20
I've been using this every so often in multiple RStudio versions and environments, and it's been working as expected. For the first and final verification, I used the C++ code that @kevinushey provided above, in
- RStudio Desktop 2021-07.0.270 on MacOS 12 beta
- RStudio Server 2021.7.0.271.1 on Red Hat 8.4 via Chrome on MacOS 12 beta
- RStudio Server 2021.7.0.271.1 on SLES 15 SP3 via Safari on MacOS 12 beta

Confirmed!

**Closed by ronblum** 2021-08-02 13:20 UTC
Labels: bug, test
