### ISSUE TITLE
RStudio no longer marks .Rproj.user project directory as hidden

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#15514] opened 2024-12-13 05:31 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.09.1
    OS Version      : Windows
    R Version       : Any

### Steps to reproduce the problem

Create an RStudio project.

### Describe the problem in detail

The `.Rproj.user` directory is not marked as hidden.

### Describe the behavior you expected

It should be marked as hidden.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-12-13 15:12
@kevinushey I can't reproduce this on Windows 11, going as far back as 2023.12.1: The directory is only shown when "Show hidden files" is set. Or is the directory supposed to be hidden even then?

**Comment by ronblum** [comment] 2024-12-13 15:18
Never mind--this is for a folder hidden by Windows, not the file pane.

**Comment by ronblum** [comment] 2024-12-23 17:42
Verified fixed in RStudio Desktop 2024.12.1+522. Checked that
1) In the File Explorer, the icon is slightly translucent, indicating that the file is hidden.
2) In the files properties, <kbd>Attributes -> Hidden</kbd> is checked.

**Closed by ronblum** 2024-12-23 17:42 UTC
Labels: bug, windows, projects
