### ISSUE TITLE
R banner is duplicated sometimes on launch

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3439] opened 2018-09-06 23:33 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.961
    OS Version      : Windows 10 x64
    R Version       : 3.5.1

### Steps to reproduce the problem

Launch RStudio.

### Describe the problem in detail

Observer that, sometimes (~50%) the banner is duplicated.

![screen shot 2018-09-06 at 4 32 35 pm](https://user-images.githubusercontent.com/1976582/45190371-7e104e80-b1f2-11e8-941f-2aa9c4e0597d.png)

### Describe the behavior you expected

The banner should only pop up once.

**Comment by kevinushey** [comment] 2019-01-08 19:50
What type of project were you opening when you reproduced the issue?

**Comment by ronblum** [comment] 2019-01-09 15:58
I'm not sure, sorry. It was probably something simple, with some simple R and R Markdown file in it, rather than a bookdown or new package. But I haven't been able to reproduce it.

@BartJanvanRossum Do you have any insight into the type of project you opened?

**Comment by BartJanvanRossum** [comment] 2019-01-09 16:05
For me it happens for every project I open. I just updated RStudio to the latest daily build to be sure. 
I tested some packages, shiny projects and a project just containing a .pdf.
Every time I got a double banner. The first banner appears (almost) immediately. Than it seems to be loading and then the second banner appears.
If I just start an RStudio without a project open I get a single banner just as expected.

**Comment by kevinushey** [comment] 2019-01-09 16:08
In one of the projects where this occurs, could you try pressing <kbd>Ctrl + `</kbd> and taking a screenshot of the request log that shows up?

**Comment by BartJanvanRossum** [comment] 2019-01-09 16:12
![image](https://user-images.githubusercontent.com/28725410/50912141-b8545b80-1431-11e9-9e0b-5f6d66654998.png)

**Comment by jmcphers** [comment] 2019-01-31 21:49
I'm going to move this out of 1.2 since I don't think any safe fix is possible there. If there's a change to the watchdog timer you have in mind, this a good time to make it on v1.3 so it has plenty of bake time.

**Comment by jmcphers** [comment] 2019-12-02 22:32
We haven't had any other reports of this (and certainly no reproducible examples) in about a year. Closing unless we get more data.

**Closed by jmcphers** 2019-12-02 22:32 UTC
Labels: bug, verified, windows

**Comment by BartJanvanRossum** [comment] 2019-12-03 08:52
I do understand that you are closing this. However I'd like to mention that I still have this 'problem'. Just tried the latest daily build and it is also present there. 
It only happens on startup. If I do Help - Diagnostics - Reload UI I only get one banner.
