### ISSUE TITLE
Presentation pane warning message will not clear

### ISSUE THREAD

**Issue by jhuntergit** [rstudio/rstudio#4767] opened 2019-05-07 12:57 UTC
RStudio Edition : Preview
    RStudio Version : 1.2.1335
    OS Version      : Windows 7 Pro
    R Version       : 3.5.3

Everytime I start up R Studio I'm greeted with this message in my Presentation pane:

    C:/Users/user/Dropbox/R-dir/project38/file38.md not found

I deleted that file a while ago, yet the warning persists. Is this expected behavior? `file38.md` is a standalone file, and is not referenced anywhere else in my R code, scripts, etc. I want to resolve this persistent warning message by getting rid of the issue causing it.

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

other attached packages:
[1] forcats_0.4.0   stringr_1.4.0  
[3] dplyr_0.8.0.1   purrr_0.3.2    
[5] readr_1.3.1     tidyr_0.8.3    
[7] tibble_2.1.1    ggplot2_3.1.1  
[9] tidyverse_1.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       cellranger_1.1.0
 [3] pillar_1.3.1     compiler_3.5.3  
 [5] plyr_1.8.4       tools_3.5.3     
 [7] packrat_0.5.0    jsonlite_1.6    
 [9] lubridate_1.7.4  gtable_0.3.0    
[11] nlme_3.1-137     lattice_0.20-38 
[13] pkgconfig_2.0.2  rlang_0.3.4     
[15] cli_1.1.0        rstudioapi_0.10 
[17] haven_2.1.0      withr_2.1.2     
[19] xml2_1.2.0       httr_1.4.0      
[21] generics_0.0.2   hms_0.4.2       
[23] grid_3.5.3       tidyselect_0.2.5
[25] glue_1.3.1       R6_2.4.0        
[27] readxl_1.3.1     modelr_0.1.4    
[29] magrittr_1.5     backports_1.1.4 
[31] scales_1.0.0     rvest_0.3.3     
[33] assertthat_0.2.1 colorspace_1.4-1
[35] stringi_1.4.3    lazyeval_0.2.2  
[37] munsell_0.5.0    broom_0.5.2     
[39] crayon_1.3.4   
```

**Comment by ronblum** [comment] 2019-05-14 15:22
@jhuntergit Thank you for raising the issue. I'm unable to reproduce it, though. However, there have been known issues with Dropbox in the past. Do you recall the steps you used to create the file before deleting it? And does this happen with any other file you delete?

Also, I wonder if recreating the file and then deleting it again would resolve the issue? This is the sort of absurd thing I would try out myself:
1. Recreate C:/Users/user/Dropbox/R-dir/project38/file38.md
2. Open the file in RStudio
3. Close RStudio (without closing the file)
4. Delete the file
5. Open RStudio
    - RStudio should give you a "File Deleted" message
6. Click "Yes" to close the file
7. Close RStudio
8. Open RStudio
    - Does the error go away?

**Comment by jhuntergit** [comment] 2019-05-14 20:42
This issue is only isolated to this one `file38.md`. I performed the steps above, unfortunately it didn't resolve the issue. You're right and this is almost certainly a Dropbox issue, because at the same time the problem started, I started getting this error popping up in R Studio every few seconds:

`The process cannot access the file because it's being used by another process`

[This article](https://support.rstudio.com/hc/en-us/articles/200534477-Using-Dropbox-with-RStudio-Projects) explains that utilizing Dropbox's selective sync often fixes this issue. The firewall I'm on won't allow access to this Dropbox feature so I'm out of luck... until R Studio 1.3.X comes out. I read somewhere this version will have a toggle to disable this warning. It can't come soon enough. Thank you and I'm looking forward to 1.3.X.

**Comment by ronblum** [comment] 2019-06-10 16:36
@jhuntergit What happens if you close the Presentation tab?

**Comment by jhuntergit** [comment] 2019-06-10 20:53
I closed the Presentation tab with `x` and the error doesn't pop up anymore when I start R Studio. It appears to have solved the issue. Thanks.

**Comment by ronblum** [comment] 2019-06-10 20:58
@jhuntergit Good to hear!

**Closed** 2019-06-10 20:59 UTC
Labels: verified
