### ISSUE TITLE
Strange behaviour with copy/paste from console pane to source pane

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#3421] opened 2018-09-03 10:09 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.951
    OS Version      : Ubuntu 18.04
    R Version       : 3.5.1

### Steps to reproduce the problem
Not sure it is really an issue, but I couldn't recall I already faced this behavior in version `1.1`.

First of all, make a backup of the `.Rhistory` file located in the home directory. Then open `rstudio` and type any command in the `Console` pane. For example:

    plot(1,1)

Press `Enter` to run the plot.

Now, in the `Console` pane, highlight `plot(1,1)` (without the prompt mark), Crtl+C (copy), then in `Source` pane, Ctrl+V (paste). `plot(1,1)` is successfully copied from the former and pasted into the latter.

Enter a new command in the `Console` pane, for example

    A <- matrix(1:10, nrow = 2)

Then `Enter`. The matrix `A` is created. Once again, copy/paste the newly ran command from the `Console` to the `Source`, it works.

With the arrow keys `Up`, recall the `plot` command **without** running it. Try to copy/paste this command with Ctrl+C/Ctrl+V, it won't work (`A <- matrix(1:10, nrow = 2)` will be pasted). But using the middle-button of the mouse, it will be successful. 

### Describe the problem in detail

I sometimes need to copy a command I don't want to run again, while writing a script. What is the "status" of the command recalled by arrow keys? I noticed you only can highlight the prompt mark or the command you just recalled, not both at the same time.

### Describe the behavior you expected

I expect the command to be copied in the clipboard when using Ctrl-C. Of course, the use of the middle-button is a workaround, but some unexpected behaviors also have been previously reported.

**Comment by david-cortes** [comment] 2018-09-03 18:39
Cannot reproduce, using RStudio 1.2.792, R 3.5.1, running on debian with KDE (linux).

**Comment by kevinushey** [comment] 2018-09-04 20:45
Thanks for the bug report! This is indeed a regression in the latest dailies and should be fixed with the upcoming builds.

**Closed** 2018-09-04 20:46 UTC

**Comment by ronblum** [comment] 2018-09-05 16:52
Verified in RStudio Desktop 1.2.956-1 on Ubuntu 18.04.
