### ISSUE TITLE
`chromote::ChromoteSession()` can not be started within Workbench

### ISSUE THREAD

**Issue by schloerke** [rstudio/rstudio#12960] opened 2023-04-05 14:07 UTC
### System details

    RStudio Edition : Posit Workbench
    RStudio Version : Unknown
    OS Version      : Unknown
    R Version       : Unknown

### Steps to reproduce the problem

`{chromote}` has received a couple issues that Chrome can not be launched or viewed within `Posit Workbench`.

There are a few errors going on. The script below should surface all of them. 

```r
install.packages("chromote")
b <- chromote::ChromoteSession$new()
b$Page$navigate("https://www.google.com")
b$screenshot()
b$view()
```

### Describe the problem in detail

The issues below are done within Posit Workbench

Issues:
* Viewing a Chromote Session causes an error
	* On `colorado.posit.co`, Running the code above works up until `b$view()`. 
	* `b$view()` has error:
	```
    [323:323:0405/130442.186660:ERROR:ozone_platform_x11.cc(238)] Missing X server or $DISPLAY
    [323:323:0405/130442.186712:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
    [323:375:0405/130442.187485:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    ```
	* Run on R v4.2.0
* `Error: Invalid Chrome Path`: https://github.com/rstudio/chromote/issues/103
	* When running a `{shinytest2}` test, `{chromote}` can not find the Chrome Path. 
	* This bug should be surfaced in `chromote::ChromoteSession$new()`
* `webshot2::webshot() - Can not find port`: (Slack message)
	* So the user can install the packages, can run `{chromote}` like regular within an R terminal, but within Posit Workbench, `{chromote}` can not be launched.
	* Code works in a linux terminal, but not within Workbench

<details><summary> Copy of message from Slack</summary>

We first received the following output for the R console in the Workbench UI:

```
> chromote::find_chrome()
 google-chrome
"/usr/bin/google-chrome"
> webshot2::webshot("https://cran.rstudio.com/")
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. Error:
Run `rlang::last_trace()` to see where the error occurred.
> remotes::install_github("rstudio/chromote")
Skipping install of 'chromote' from a github remote, the SHA1 (c4cad74f) has not changed since last install.
 Use `force = TRUE` to force installation
```

And then they output from an R session run from a Linux terminal:

```
> chromote::find_chrome()
 google-chrome
"/usr/bin/google-chrome"
> remotes::install_github("rstudio/chromote")
Skipping install of 'chromote' from a github remote, the SHA1 (c4cad74f) has not changed since last install.
 Use `force = TRUE` to force installation
> webshot2::webshot("https://cran.rstudio.com/")
https://cran.rstudio.com/ screenshot completed
```

I then followed up by asking for the trace that the error message above mentions, and they sent us the following output:

```
> webshot2::webshot("https://cran.rstudio.com/")
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. Error:
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/error_no_available_port>
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. Error:
---
Backtrace:
 ▆
 1. └─webshot2::webshot("https://cran.rstudio.com/")
 2. └─chromote::default_chromote_object()
 3. ├─chromote::set_default_chromote_object(Chromote$new())
 4. └─Chromote$new()
 5. └─chromote (local) initialize(...)
 6. └─Chrome$new()
 7. └─chromote (local) initialize(...)
 8. └─chromote:::launch_chrome(path, args)
 9. └─chromote:::with_random_port(launch_chrome_impl, path = path, args = args)
Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.
> rlang::last_trace(drop = FALSE)
<error/error_no_available_port>
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. Error:
---
Backtrace:
 ▆
 1. └─webshot2::webshot("https://cran.rstudio.com/")
 2. └─chromote::default_chromote_object()
 3. ├─chromote::set_default_chromote_object(Chromote$new())
 4. └─Chromote$new()
 5. └─chromote (local) initialize(...)
 6. └─Chrome$new()
 7. └─chromote (local) initialize(...)
 8. └─chromote:::launch_chrome(path, args)
 9. └─chromote:::with_random_port(launch_chrome_impl, path = path, args = args)
 10. └─rlang::abort(...)
```
	

</details>

### Describe the behavior you expected

I expect `{chromote}` to be able to create a new `ChromoteSession`, take a screenshot, and be able to be viewed by the user all within Posit Workbench.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by shahreyar-abeer** [comment] 2023-05-18 09:26
Any updates with this issue?
I'm getting the `Error: Invalid Chrome Path` issue in Posit Workbench

**Comment by datakid** [comment] 2023-06-20 23:00
Also seen in support ticket #91292

**Comment by jorgesinval** [comment] 2023-11-14 09:11
Any solution to this issue? Thanks.

**Comment by kevinushey** [comment] 2024-01-18 19:40
I'm not able to reproduce on a local Workbench installation; everything appears to be fine to me now.

On Colorado, this fails because of:

```
> b <- chromote::ChromoteSession$new()
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. Error: 
Command '/usr/bin/chromium-browser' requires the chromium snap to be installed.
Please install it with:

snap install chromium
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by ronblum** [comment] 2024-01-18 19:54
@kevinushey I have an environment that reproduces the first two errors in the issue, using Posit Workbench 2023.12.1+385.pro7 on Ubuntu 22 (I haven't tried open source) and Google Chrome 120.0.6099.224.

```
> b$view()
[46537:46537:0118/195148.900464:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[46537:46537:0118/195148.900502:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
```

**Comment by kevinushey** [comment] 2024-01-18 21:12
One problem I noticed: when starting `chromote`, it tries to write stuff into `/tmp` owned by the current user account; e.g. `/tmp/Crashpad`. If multiple users are trying to use `chromote` on the same machine, they'll run into conflicts.

The issue reported by @ronblum likely occurs because there is no X server running on that machine; e.g. from a terminal:

```
(base) kevin:~$ xset q
xset:  unable to open display ":0"
```

As far as I can see, `chromote` works fine as long as the system pre-requisites are available.

**Comment by jthomasmock** [comment] 2024-01-19 17:16
@schloerke - it seems like this does work as long as an x-server and a version of chrome/chromote is available on the server. I think this could be handled by a more descriptive error message in `chromote` - does that make sense?

As part of our research - Kevin also found:

> One problem I noticed: when starting chromote, it tries to write stuff into /tmp owned by the current user account; e.g. /tmp/Crashpad. If multiple users are trying to use chromote on the same machine, they'll run into conflicts.

**Comment by n1b0r63** [comment] 2024-01-19 18:02
> @schloerke - it seems like this does work as long as an x-server and a version of chrome/chromote is available on the server

I work on a Posit workbench server installed on a CentOS server, with other members of my DS team. I'm not sure if my sysadmin will agree to install a X-server on a server like that...

**Comment by kevinushey** [comment] 2024-01-19 20:56
> I work on a Posit workbench server installed on a CentOS server, with other members of my DS team. I'm not sure if my sysadmin will agree to install a X-server on a server like that...

The `chromote` package could probably be modified to use a virtual frame buffer for display / output. This is described in a couple places, e.g. https://robinding.medium.com/how-to-run-headless-chrome-with-extensions-in-ubuntu-16-04-using-xvfb-in-nodejs-2bed7b361efc, but as far as I can tell this is outside of RStudio's purview and would need to be implemented in `chromote`.

In other words, if you want `chromote` to work as currently implemented, you need a running X server.

**Comment by kevinushey** [comment] 2024-01-19 21:08
Hmm, but https://developer.chrome.com/blog/headless-chrome does say...

> **So I still need Xvfb?**
> 
> No. Headless Chrome doesn't use a window so a display server like Xvfb is no longer needed. You can happily run your automated tests without it.
> 
> What is Xvfb? Xvfb is an in-memory display server for Unix-like systems that enables you to run graphical applications (like Chrome) without an attached physical display. Many people use Xvfb to run earlier versions of Chrome to do "headless" testing.
> 

Perhaps that's only true in newer versions of Chrome / Chromium?

**Comment by skyeturriff** [comment] 2024-03-18 15:48
A support customer in ticket# 102034 is seeing `webshot2` working in their dev environment, but failing in their stage and prod envs
```
> library(chromote)
> packageVersion("chromote")
[1] ‘0.1.2’
> chromote::find_chrome()
[1] "/usr/lib64/chromium-browser/chromium-browser"
> b <- ChromoteSession$new()
Error in `with_random_port()`:
! Cannot find an available port. Please try again.
Caused by error in `startup()`:
! Failed to start chrome. Error:
Run `rlang::last_trace()` to see where the error occurred.
```

They're using the same Docker image across all envs. They did mention noticing a difference in open ports on their dev and stage envs, but correcting it to match the dev host had no effect. They also mentioned testing port availability through `randomPort()` function from `httpuv` package, and did not notice any issue.

Using an earlier version of `webshot` does work.

**Comment by skyeturriff** [comment] 2024-03-18 18:26
Thank you @kevinushey !

**Comment by gadenbuie** [comment] 2024-03-18 19:48
> Also worth saying that the issue here is unlikely to be related to ports, but is more likely related to the chromote package being unable to launch Chrome / Chromium.

@skyeturriff I agree with @kevinushey's assessment here. However it's unlikely to be something wrong with the chromote package specifically, and more likely to be related to a system- or environment-specific failure to start Chrome/Chromium.

One trick I've used in the past is to inspect left-over log files after the process fails to start. You can ask the user to run `dir(tempdir(), pattern = "chrome-", full.names = TRUE)` to list chrome-related log files in the session's temp directory (after a failed attempt to start a chromote session). Sometimes there are clues hidden in those log files.

**Comment by skyeturriff** [comment] 2024-03-18 20:45
Thank you @gadenbuie ! I've passed that along to Support

**Comment by kevinushey** [comment] 2024-03-18 20:45
I also wonder if the `chromote` package should either (1) automatically include those logs as part of the error output, or (2) inform the user that they can read those log files to get more error details. Right now the error is unfortunately rather opaque.

**Comment by rloche** [comment] 2024-04-05 13:10
Thanks for everyone feedback. To add more information, here is what happen in my case:

- Posit workbench server pro 2023.12.1
- Centos 7
- R 4.0.5
- chromote 0.1.2
- Chromium installed on the server: 123.0.6312.58
- No X server / GUI

When I do this:
```
library(chromote)
trace(chromote:::launch_chrome_impl, quote(print(utils::ls.str())))
b <- ChromoteSession$new()
```

I get this: 
```
Tracing startup(port = port, ...) on entry 
args :  chr [1:4] "--disable-gpu" "--force-color-profile=srgb" "--disable-extensions" "--mute-audio"
path :  Named chr "/usr/bin/chromium-browser"
port :  int 22330
Error: Chromote: timed out waiting for response to command Runtime.evaluate
```

And in the temp files created, retrieved with `dir(tempdir(), pattern = "chrome-", full.names = TRUE)`, stdout is empty and stderr contains this:
```
[0405/145235.867038:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0405/145235.867091:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0405/145235.871089:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.

DevTools listening on ws://127.0.0.1:22330/devtools/browser/291d195f-e833-4a1d-906c-29b52f18b865
[0405/145235.875017:ERROR:angle_platform_impl.cc(44)] DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
[0405/145235.875146:ERROR:angle_platform_impl.cc(44)] Display.cpp:1070 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1070 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[0405/145235.875240:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Not initialized.
[0405/145235.875317:ERROR:gl_display.cc(786)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[0405/145235.875387:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[0405/145235.875446:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[0405/145235.877809:ERROR:angle_platform_impl.cc(44)] DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
[0405/145235.877918:ERROR:angle_platform_impl.cc(44)] Display.cpp:1070 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1070 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[0405/145235.877983:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Not initialized.
[0405/145235.878049:ERROR:gl_display.cc(786)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[0405/145235.878105:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[0405/145235.878173:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[0405/145235.879525:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[0405/145236.351842:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[0405/145236.355192:ERROR:v8_initializer.cc(812)] V8 process OOM (Failed to reserve the virtual address space for the V8 sandbox).
```

I'm not sure where the error really is.
Originally, We're looking for a solution to automatize the tests for our shiny and shinytest2 rely on chromote, and it's pretty much the only solution, so we're stuck...

**Comment by rloche** [comment] 2024-04-05 15:01
> Could this be an issue with `max-memory-mb` being set too low? Seeing the error `V8 process OOM (Failed to reserve the virtual address space for the V8 sandbox).` made me think of [this issue](https://github.com/rstudio/rstudio-pro/issues/5019)

I'm not sure what you mean because your link is broken, but on the server we have set in the `/etc/rstudio/rsession.conf` file ` max-memory-mb = 50000`, I think that should be enough ?

**Comment by kevinushey** [comment] 2024-04-05 17:00
I think the error here is caused by the amount of memory available to the Chrome / Chromium process, as opposed to what's made available for the R session.

You might be able to pass a flag like `--max_old_space_size=8192` to the Chrome process to ask it to retain more memory, via something like:

```
args <- chromote::get_chrome_args()
args <- c("--js-flags=\"--max_old_space_size=8192\"", args)
chromote::set_chrome_args(args)
```

Or perhaps:

```
Sys.setenv(NODE_OPTIONS = "--max-old-space-size=8192")
```

Unfortunately, I can't find any official documentation on what the right way to communicate this to Chrome / Chromium is; there's just a scattering of different recommendations online.

**Comment by rloche** [comment] 2024-04-08 07:49
Thanks for your answer.

Unfortunately, it does not work. It does seems the parameter is correctly passed with your first option. I tried different variations, and added quotes to looks like what I've seen on other forums, but the error stay the same.

What makes me think the parameter is passed correctly is that the chromium process that is launched looks like that:

`/usr/bin/chromium-browser --enable-plugins --enable-extensions --enable-user-scripts --enable-printing --enable-gpu-rasterization --enable-sync --auto-ssl-client-auth --headless --remote-debugging-port=27451 --remote-allow-origins=http://127.0.0.1:27451 --js-flags="--max_old_space_size=8192" --disable-gpu --force-color-profile=srgb --disable-extensions --mute-audio`

This is the last version that I tried, where I add the quotes, but like I said I tried several variations around it.
The errors I got in the files are still exactly the same.

**Comment by fh-mthomson** [comment] 2024-07-03 00:15
I ran into two challenges while trying to set up `chromote` in Workbench; sharing solutions I found back here in case its helpful (also open to feedback on my approach!):

**Challenge 1**: Installing relevant deps to the Docker image pulled by Workbench:  
* Reprex: 
``` r
b <- chromote::ChromoteSession$new()
#> `google-chrome` and `chromium-browser` were not found. Try setting the `CHROMOTE_CHROME` environment variable to the executable of a Chromium-based browser, such as Google Chrome, Chromium or Brave or adding one of these executables to your PATH.
#> Error in initialize(...): Invalid path to Chrome
chromote::find_chrome()
#> `google-chrome` and `chromium-browser` were not found. Try setting the `CHROMOTE_CHROME` environment variable to the executable of a Chromium-based browser, such as Google Chrome, Chromium or Brave or adding one of these executables to your PATH.
#> NULL
packageVersion("chromote")
#> [1] '0.2.0'
```
nit: it'd be super helpful if the error could re-direct to docs that outline how to do install into applicable systems (e.g., Docker for Workbench)

* Solution (illustrative):
```
FROM --platform=linux/amd64 docker.prod.flatiron.io/rstudio/r-session-complete:ubuntu2204-2024.04.2--59ebe4d

# Install google-chrome 
RUN curl -L https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | tee /usr/share/keyrings/google-chrome-keyring.gpg >/dev/null
RUN gpg --no-default-keyring --keyring /usr/share/keyrings/google-chrome-keyring.gpg --fingerprint
RUN echo "deb [signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
RUN apt-get -y update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
    google-chrome-stable \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*
```

References:  
* [system requirements of `webshot2`, Posit PM](https://packagemanager.posit.co/client/#/repos/cran/packages/overview?search=webshot2) 
* [medium article](https://robinding.medium.com/how-to-run-headless-chrome-with-extensions-in-ubuntu-16-04-using-xvfb-in-nodejs-2bed7b361efc)
* https://github.com/ashbythorpe/selenider/issues/22#issue-2353802993

**Challenge 2**:  Permissions issue related to `--no-sandbox`:
* Reprex: 
``` r
chromote::set_chrome_args(chromote:::default_chrome_args())

b <- chromote::ChromoteSession$new()
#> Error in `with_random_port()`:
#> ! Cannot find an available port. Please try again.
#> Caused by error in `startup()`:
#> ! Failed to start chrome. Error: Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
#> [0703/000005.639233:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : No space left on device (28)
#> [0703/000005.649603:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
#> [0703/000005.649699:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
#> [0100/000000.668105:ERROR:zygote_linux.cc(673)] write: Broken pipe (32)
chromote:::default_chrome_args()
#> [1] "--force-color-profile=srgb" "--disable-extensions"      
#> [3] "--mute-audio"
```

* Solution (interim): specify `--no-sandbox` (not a default arg, likely intentionally given security considerations)
``` r
chromote::set_chrome_args(c(chromote:::default_chrome_args(), "--no-sandbox"))
b <- chromote::ChromoteSession$new()
```

**Question:** are there alternatives y'all can recommend that would avoid needing to set `--no-sandbox`?

<details><summary>More detail</summary>
<p>

`--no-sandbox` is seemingly bypassed, since each of the cases are FALSE on Workbench ([reference](https://github.com/rstudio/chromote/blob/a900c469f699121c342fe2f82b0ddf56159e4a88/R/chromote.R#L666C27-L666C50))

``` r
chromote:::is_inside_ci()
#> [1] FALSE
chromote:::is_inside_docker()
#> [1] FALSE
chromote:::is_missing_linux_user()
#> [1] FALSE
```

While there's a comment in the function [here](https://github.com/rstudio/chromote/blob/a900c469f699121c342fe2f82b0ddf56159e4a88/R/chromote.R#L666C27-L666C50)

```
# > Note: --no-sandbox is not needed if you properly setup a user in the container.
# https://developers.google.com/web/updates/2017/04/headless-chrome
```

It's unclear whether there is additional Docker-level setup to create user profile in Workbench. Of note, there is almost surely always an `id` available in user sessions, as referenced by `is_missing_linux_user()`. Illustrative (redacted):
```
> system("id")
uid=12345678(user.name) gid=123450001(user.name) groups=....
```

</p>
</details>

**Comment by kevinushey** [comment] 2024-08-28 21:51
It seems to me like the issues reported here are all external to RStudio / Workbench itself, and are primarily related to the environment wherein RStudio is running (since extra system dependencies are required in order for `chromote` to function).

IMHO, the `chromote` package should be responsible for detecting if the necessary system pre-requisites are available, and notify the user if they are not (e.g. a running X server seems to be necessary? even though some available documentation seems to say otherwise?)

I'm going to close this for now, but I'm happy to re-open if we can say more conclusively that there is an issue in RStudio proper.

**Closed by kevinushey** 2024-08-28 21:51 UTC
Labels: bug, support, pm, evaluate effort 🕐🗳🔎

**Comment by fh-mthomson** [comment] 2024-09-19 00:46
I agree the issues are separate from the RStudio IDE (this repo) but still highlights that `chromote`  (needed for `webshot2` / `shinytest2`) can still be _very_ challenging to get working in Workbench (it took me several days).

I've proposed more narrowly scoped issues in the `chromote` repo accordingly:
* https://github.com/rstudio/chromote/issues/179
* https://github.com/rstudio/chromote/issues/178

Feel free to transfer / modify as you see fit. Thanks for the consideration :)
