### ISSUE TITLE
stdout does not appear in Rstudio when using `parallel::makeForkCluster(..., outfile="")`

### ISSUE THREAD

**Issue by tshmak** [rstudio/rstudio#3135] opened 2018-07-10 03:41 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.419
    OS Version      :  Ubuntu 16.04.4 LTS
    R Version       :  Microsoft R Open 3.4.2

### Steps to reproduce the problem
```
library(parallel)
cl <- makeForkCluster(2, outfile="")
parLapply(cl, 1:2, function(i) {print("abc"); return(i)})
```
### Describe the problem in detail
It is supposed to print "abc" in the child processes. While this works in the terminal, it doesn't work in Rstudio. 

### Describe the behavior you expected
stdout in the Rstudio console window. 

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /opt/microsoft/ropen/3.4.2/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.4.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_HK.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_HK.UTF-8        LC_COLLATE=en_HK.UTF-8    
 [5] LC_MONETARY=en_HK.UTF-8    LC_MESSAGES=en_HK.UTF-8   
 [7] LC_PAPER=en_HK.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_HK.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     grDevices datasets  graphics  utils     methods  
[8] base     

other attached packages:
[1] RevoUtils_10.0.6     General_0.1          roxygen2_6.0.1      
[4] devtools_1.13.3      RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13   digest_0.6.12  withr_2.0.0    commonmark_1.4 R6_2.2.0      
 [6] magrittr_1.5   stringi_1.1.5  xml2_1.1.1     tools_3.4.2    stringr_1.2.0 
[11] compiler_3.4.2 memoise_1.1.0 
```

<!-- Depending on the problem, the following may also be helpful

1. The output of sessionInfo() 
```
2. The R code in question
3. A diagnostics report; see https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report

Thank you for taking the time to file an issue!  -->

**Comment by kfeinauer** [comment] 2018-07-10 14:19
Does this reproduce for you in the daily build? You can grab the latest daily from here: https://dailies.rstudio.com/

**Comment by tshmak** [comment] 2018-07-13 06:35
Yes, I'm now using Rstudio 1.2.823

**Comment by tshmak** [comment] 2018-10-10 09:16
Hi, are there anything else I can do to help?

**Comment by kevinushey** [comment] 2018-10-11 02:15
This issue is likely common to most R front-ends (I can reproduce in R.app). Not yet sure what it would take to support this; would need a way of capturing and forwarding stdout / stderr back to the parent R process explicitly.

**Comment by jmcphers** [comment] 2019-11-19 21:28
Closing since this bug isn't specific to RStudio.

**Closed by jmcphers** 2019-11-19 21:28 UTC
Labels: repro needed
