### ISSUE TITLE
Use tinytex to compile LaTeX documents

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#2788] opened 2018-05-15 15:10 UTC
I think the **tinytex** package is mature enough now (it has been on CRAN for about half a year), so we may consider using it to compile LaTeX documents (including Rnw documents https://github.com/yihui/tinytex/issues/10). Note that the **rmarkdown** package has already used it to compile the intermediate `.tex` files to PDF in `rmarkdown::render()`. Some tips on how the IDE options should be passed to **tinytex**:

![image](https://user-images.githubusercontent.com/163582/40065076-7cb8cba0-5826-11e8-9d6c-e49fd01653dd.png)

1. The main function to call is `tinytex::latexmk()`.

1. The LaTeX engine (`pdflatex`, `xelatex`, `lualatex`) is passed to the `engine` argument of `latexmk()`.

1. The `Clean auxiliary output` option is passed to the `clean` argument of `latexmk()`.

1. The `Enable shell escape` option is passed to `latexmk(engine_args = '-shell-escape')`.

The main advantages of using **tinytex** is that it will process bibliographies and resolve other cross-references correctly (compile the .tex for a correct number of times). If the user has installed [TinyTeX](https://yihui.name/tinytex/) (`tinytex::install_tinytex()`), missing LaTeX packages can also be installed automatically.

Let me know if you need any other information.

**Comment by kevinushey** [comment] 2018-05-15 16:12
@jmcphers this would be nice to get in for RStudio v1.2; do you think we have the time to squeeze it in?

**Comment by jmcphers** [comment] 2018-05-15 16:28
It'd certainly be nice! I've added it optimistically to the backlog for 1.2 but we should prioritize some of the longer-standing bugs/regressions over this.

**Comment by njtierney** [comment] 2019-07-24 06:41
Just wanted to chime in here that using tinytex to compile PDF would be really nice!

**Comment by kevinushey** [comment] 2019-09-11 16:40
I believe this has become somewhat higher priority for v1.3. Newer versions of MiKTeX hide the "full" installer somewhat, and only provide the basic installer; at least based on what I see from https://miktex.org/download.

This implies that attempts to compile PDFs will fail by default, even with MiKTeX installed. Normally, MiKTeX will try to prompt you to install missing packages, but we've seen that fail (and of course that will fail if you lack internet connectivity)

```
2019-09-10 09:28:28,485-0700 INFO  pdflatex - starting with command line: C:\Users\rich\AppData\Local\Programs\MIKTEX~1.9\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode cda.tex
2019-09-10 09:28:28,540-0700 INFO  pdflatex - allowing known shell commands
2019-09-10 09:28:28,541-0700 INFO  pdflatex - enabling input (output) from (to) processes
2019-09-10 09:28:28,762-0700 FATAL pdflatex - GUI framework cannot be initialized.
2019-09-10 09:28:28,762-0700 FATAL pdflatex - Info:
2019-09-10 09:28:28,762-0700 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2019-09-10 09:28:28,762-0700 FATAL pdflatex - Line: 77
2019-09-10 09:28:28,762-0700 INFO  pdflatex - finishing with exit code 1
```

It's possible to request a "full" installation if you use the "net" installer (which is not the most prominently visible installer), and then request a "full" install in that wizard. But that's definitely not the path most users will take.

**Comment by yihui** [comment] 2019-10-11 02:38
#5490 provided a way to install TinyTeX, which is great! What I requested in this issue was actually to use `tinytex::latexmk()` to compile .tex files.

**Comment by retodomax** [comment] 2019-11-27 20:35
It would be great if the "Compile PDF" button somehow calls `tinytex::pdflatex('filename.tex')` if tinytex is installed. Otherwise, if just pdflatex is executed, missing LaTeX packages are not installed automatically (in RStudio 1.2.5). Or am I doing something wrong?

Thank you!

![RStudio_LaTeX](https://user-images.githubusercontent.com/36004669/69757630-bdabb900-115d-11ea-8ca2-da1a5a15f679.png)

**Comment by kevinushey** [comment] 2019-11-27 21:00
This is currently only available in the [daily builds](https://dailies.rstudio.com/) of RStudio.

**Comment by retodomax** [comment] 2019-11-27 21:08
I see... Thank you!

**Comment by yihui** [comment] 2020-04-04 18:48
I just realized that #5608 only made it possible to compile .tex files via `tinytex::latexmk()`, but not `.Rnw` documents. And I was hoping the intermediate `.tex` from `.Rnw` could be compiled through **tinytex** as well (yihui/tinytex#10). I'm not familiar with `rnw_weave::runWeave` below, but it sounds like it does the two steps together ("weave" + "compile to pdf"):

https://github.com/rstudio/rstudio/blob/a675c8564ce74baf06dcc702300a21ac6484dd23/src/cpp/session/modules/tex/SessionCompilePdf.cpp#L614-L632

So somewhere inside `rnw_weave::runWeave`, we need to call `tinytex::latexmk()` if the preference `use_tinytex` is true.

I was just about to tell the user who asked the question https://stackoverflow.com/q/61029677/559676 to try the daily build, but after I tested it, I realized `.Rnw` was not compiled through **tinytex**, so it won't work for this user (references won't be correctly resolved).

**Comment by kevinushey** [comment] 2020-09-09 22:31
It looks like we normally run R as a sub-process when weaving `.Rnw` files, basically invoking the following:

```
$ ps -p `pgrep -nx R`
  PID TTY           TIME CMD
36278 ttys006    0:00.21 /Library/Frameworks/R.framework/Resources/bin/exec/R --slave --no-save --no-restore -e grDevices::pdf.options(useDingbats~+~=~+~FALSE);~+~utils::Sweave('test.Rnw',~+~encoding='UTF-8')
```

And this is where that all happens:

https://github.com/rstudio/rstudio/blob/d24a955b8194a21cbad034ba138cbeb281623f83/src/cpp/session/modules/tex/SessionRnwWeave.cpp#L509-L572

@yihui, can you share what the right way to invoke `tinytex::latexmk()` here would be -- would we invoke it instead of `utils::Sweave()` here? Or in tandem in some way?

**Comment by kevinushey** [comment] 2020-12-08 23:00
@yihui sorry for taking so long to respond. You are correct that I was using Sweave; sorry for missing that part. This is where we're building the command to invoke `knit()`:

https://github.com/rstudio/rstudio/blob/fafd617518d01be973e138c306f8bb253de58676/src/cpp/session/modules/tex/SessionRnwWeave.cpp#L265-L281

And this is where we run the latex compiler after a successful weave (or knit):

https://github.com/rstudio/rstudio/blob/fafd617518d01be973e138c306f8bb253de58676/src/cpp/session/modules/tex/SessionCompilePdf.cpp#L730-L804

So I think we need to use `tinytex()` when rendering there as well.

**Comment by kevinushey** [comment] 2020-12-09 23:43
Fixed via https://github.com/rstudio/rstudio/pull/8570 -- this should ensure that the `.tex` files weaved via Sweave / knitr are now also rendered by `tinytex`.

**Comment by yihui** [comment] 2020-12-13 02:43
Awesome! Thanks @kevinushey!

**Comment by yihui** [comment] 2021-01-16 03:50
Here is an `.Rnw` document that I use to test the "Compile PDF" button in the IDE:

```tex
\documentclass{article}

\begin{document}

<<>>=
# tinytex should automatically reinstall this package later
tinytex::tlmgr_remove('framed')

# test bibliography
knitr::write_bib('base', 'test.bib')
@

\cite{R-base}

\bibliography{test.bib}
\bibliographystyle{unsrt}
\end{document}
```

If this feature is implemented correctly and you have TinyTeX installed (`tinytex::install_tinytex()`), you should see that 1) the LaTeX package `framed` should be automatically reinstalled; 2) the bibliography should be generated (`\cite{R-base}` generates `[1]` instead of `??`).

**Comment by ronblum** [comment] 2021-01-27 15:14
Verified in
- RStudio Desktop 1.4.1507 on MacOS 11.1
- RStudio Server 1.4.1512 on Red Hat 8.3 with Chrome on MacOS 11.1

Tested using sample code from http://mally.stanford.edu/~sr/computing/latex-example.html and https://www.overleaf.com/latex/examples/dodecahedron-desk-calendar/mrjbknbbrjhy

**Closed by ronblum** 2021-01-27 15:14 UTC
Labels: enhancement, test

**Comment by kevinushey** [comment] 2021-02-04 00:07
Can also confirm the example in https://github.com/rstudio/rstudio/issues/2788#issuecomment-761333127 works as expected.
