### ISSUE TITLE
Fix $ autocompletion of underscores followed by number or letter

### ISSUE THREAD

**Issue by t-gummer** [rstudio/rstudio#11689] opened 2022-08-02 12:49 UTC
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
    OS Version      :  Windows
    R Version       : R version 4.1.3 (2022-03-10) -- "One Push-Up"

### Steps to reproduce the problem

In $ autocompletion, if I was to create the following list, say:
```r
x <- list("_0" = NA)
```
and then attempt to autocomplete (ctrl+space or tab in the console) with `x$`, I obtain this:
```
x$_0
#> Error: unexpected input in "x$_"
```

when I should be getting:
```
x$`_0`
#> [1] NA
```

### Describe the problem in detail

The backticks around names that start with "_+[0-9]" (underscores followed by a number are not being quoted as they should according to R syntax).

### Describe the behavior you expected

As I state above, I expect it to put backticks around `_0` etc. in the example above.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

----

### The solution?

I have put through a pull request with my attempt to fix it here: https://github.com/rstudio/rstudio/pull/11688

**Comment by ronblum** [comment] 2022-08-02 14:56
@t-gummer Thank you for raising the issue and submitting a fix! This is a duplicate of issue #4094, but I'll close that one as a duplicate since you provided a PR for this.

Here is [the guide for submitting code changes to RStudio](https://github.com/rstudio/rstudio/wiki/A-Beginner's-Guide-to-Writing-RStudio-IDE-Features). Next step is to assign this to a reviewer; I'll go ahead and add one.

**Comment by t-gummer** [comment] 2022-08-02 23:19
Thanks for getting back to me 😃. Apologies for the duplicate issues, I had a look to see if I could find the same issue, I did not come across that one (it is quite old) be but it is also slightly different to mine as it pertains to backticks inside names (an issue which is probably more difficult to fix and is less common to encounter) instead of names starting with underscores followed by numbers.

**Comment by ronblum** [comment] 2022-08-03 12:40
@t-gummer Thank you for pointing out my mistake! And no apologies necessary—as you point out, they're not the same, just a similar issue regarding backticks. But at least now they're both connected.

**Comment by t-gummer** [comment] 2022-08-05 01:26
As it turns out names with an underscore followed by a letter also don't work so I'll  put through an additional pull request to fix that.

**Comment by jgutman** [comment] 2022-08-10 18:33
@t-gummer I'll add the change to handle underscores followed by letters, thanks for raising! Just wanted to double check, have you signed the [individual](https://www.rstudio.com/wp-content/uploads/2014/06/rstudioindividualcontributoragreement.pdf) contributor agreement? You can send the signed copy to [contribute@rstudio.com](mailto:contribute@rstudio.com).

**Comment by t-gummer** [comment] 2022-08-11 04:46
> @t-gummer I'll add the change to handle underscores followed by letters, thanks for raising! Just wanted to double check, have you signed the [individual](https://www.rstudio.com/wp-content/uploads/2014/06/rstudioindividualcontributoragreement.pdf) contributor agreement? You can send the signed copy to [contribute@rstudio.com](mailto:contribute@rstudio.com).

Yes I have signed it already 🙂.

**Comment by ronblum** [comment] 2022-08-11 11:20
Verified that ticks now appear with autocompletion of `x$` in this example, to `` x$`_0` ``

**Comment by ronblum** [comment] 2022-08-11 12:28
Reverting to "in progress" because now, all autocompletions are getting backticks, which are unnecessary

```
> y <- list("a" = NA)
> y$`a` # with autocompletion
[1] NA
> y$a # without autocompletion
[1] NA
> 
```

I don't believe is correct, as `y$a` would be correct. Similar example: `cli::` with autocompletion results in `` cli::`ansi_align`() `` but it should end up as `` cli::ansi_align() ``.

**Comment by jonvanausdeln** [comment] 2022-08-12 20:08
Verified on 2022.11.0-101
Windows 11, Ubuntu 22.04, MacOS 12.4

Tested all above scenarios and various uses of underscores.

**Closed by jonvanausdeln** 2022-08-12 20:08 UTC
Labels: bug, autocompletion
