### ISSUE TITLE
RStudio won't launch

### ISSUE THREAD

**Issue by laurenfitch** [rstudio/rstudio#2063] opened 2018-01-26 01:14 UTC
RStudio crashed with a fatal error. No other error message was provided. Googling suggested uninstalling and reinstalling R and RStudio. I uninstalled and reinstalled, and now RStudio won't start.

"This application failed to start because it could not find or load the Qt platform plugin "windows". Reinstalling the application may fix this problem.

I have tried reinstalling several times to no avail.

### System details

    OS Version      : Windows 7
    RStudio Version : 1.1.419 (also tried 1.1.383)
    R Version       : 3.4.3

### Steps to reproduce the problem
Launch RStudio

### Describe the problem in detail
Application doesn't launch

### Describe the behavior you expected
RStudio should launch
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1666247/diagnostics-report.txt)

**Comment by laurenfitch** [comment] 2018-01-26 01:37
I was able to reinstall and open/run RStudio 1.0.153. Nothing newer.

**Comment by ronblum** [comment] 2018-01-26 17:48
@laurenfitch Can you try resetting the RStudio Desktop state? Instructions are available at
[https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State](https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State)

**Comment by dfalty** [comment] 2018-01-26 17:53
I can't reproduce this on Win 7 1.1.419 or 1.1.383. Let us know if resetting the desktop state works.

**Comment by gtritchie** [comment] 2019-04-30 23:36
Closing; please reactivate if this is still a problem.

**Closed by gtritchie** 2019-04-30 23:36 UTC
