### ISSUE TITLE
Chunk option variable is not found

### ISSUE THREAD

**Issue by oscardelama** [rstudio/rstudio#8060] opened 2020-10-14 16:27 UTC
Hi friends,

When I run a notebook using variables to setup the chunk options, those variables are not recognized. In the console I get the error:
Error in eval(ele) : object 'Xxxx' not found
The reprex is the following:

****
    ---
    title: "R Notebook"
    output: html_notebook
    ---

    # Setup

    ```{r}
    dont_run_it <- TRUE
    ```

    # Test this

    ```{r eval=!dont_run_it}
    print("Do not eval this")
    ```
    ## [1] "Do not eval this"
*******
After running (Run All or Run all chunks below) the example I get in the console:

    > dont_run_it <- TRUE
    Error in eval(ele) : object 'dont_run_it' not found
    > print("Do not eval this")
    [1] "Do not eval this"

If I select "!dont_run_it" and run it (Ctrl + Enter) I get in the console:

    Error in eval(ele) : object 'dont_run_it' not found
    > !dont_run_it
    [1] FALSE

### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.4.904
    OS Version      :  Linux Mint Ulyana (Ubuntu 20.04 focal)
    R Version       :  4.0.3 (2020-10-10) 

### Steps to reproduce the problem
Run All the notebook 

### Describe the problem in detail
Variables used to setup chunk options are not recognized

### Describe the behavior you expected
The variable should be recognized

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-10-15 13:58
@oscardelama Thank you for raising the issue! I can reproduce it in RStudio Desktop from 1.2.5042 through 1.4.926 on MacOS 11 beta 9 using R 4.0.3. We'll review it as we continue to develop RStudio.

A few notes:
1) This is not a regression, as it goes back at least as 1.2

2) It seems to happen whenever evaluation needs to be done (not proper technical wording) on a variable. So for example, 
````
```{r eval=dont_run_it}
````
works, but 
````
```{r eval=(dont_run_it)}
````
fails.

3) This example from https://bookdown.org/yihui/rmarkdown-cookbook/chunk-variable.html fails as a result of no. 2:
````
```{r}
fig_small <- FALSE  # change to TRUE for larger figures
width_small <- 4
width_large <- 8
```

```{r, fig.width=if (fig_small) width_small else width_large}
plot(cars)
```
````

```
> fig_small <- FALSE  # change to TRUE for larger figures
> width_small <- 4
> width_large <- 8
Error in eval(ele) : object 'fig_small' not found
> plot(cars)
```

**Comment by oscardelama** [comment] 2020-10-15 18:09
Hi @ronblum,

Please be aware, that contrary to what you say, this doesn't work:

    ```{r eval=dont_run_it}

If in a previous chunk you set `dont_run_it <- FALSE`, RStudio runs the chunk anyway.

Thank you for your help.

**Comment by alexlifshitz** [comment] 2021-01-20 18:45
As of Version 1.4.1103, this still does not work. Very annoying. 
Is there a workaround?

**Comment by cderv** [comment] 2021-01-20 19:02
@ronblum I think this is related to https://github.com/rstudio/rstudio/issues/6675 and https://github.com/rstudio/rstudio/issues/7622 

It seems the IDE feature of running code chunk is not taking into account the environment to evaluate the chunk option. All these issues are related to this I think.

**Comment by R-Hannibal** [comment] 2021-02-12 20:11
Closing as duplicate of https://github.com/rstudio/rstudio/issues/6675.

**Closed** 2021-02-12 20:11 UTC
Labels: bug, notebooks, triage
