### ISSUE TITLE
spell check with German

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rstudio#6999] opened 2020-05-29 12:20 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      :  MacOS 10.14.6
    R Version       :  4.0.0

### Describe the problem in detail

Real time spell checking with German dictionary seems to mark all words containing umlauts or sharp s "ß" as misspelt.

**Comment by ronblum** [comment] 2020-06-02 16:10
@neuwirthe Thank you for raising this! I can reproduce this with both realtime and on-demand spellchecking, with the German dictionary. We'll review this as we continue development of RStudio.

QA note: to reproduce,
1. Tools -> Global Options -> Spelling -> Main dictionary language -> Install More Languages
2. After the additional languages are loaded, change the language to German.
3. Make sure "Use real time spellchecking" is checked.
4. Open a new R file.
5. In the file, enter
```
# er wußte
# er wusste
# er wußtße"
# er wusstsse
```
6. Save the file.

The error is that the first one, `wußte`, is getting marked as misspelled. It should not be—the spelling is correct.

<img width="85" alt="Eszett" src="https://user-images.githubusercontent.com/31009952/83542850-8978d280-a4c9-11ea-8edb-fcdcdd2d1e9e.png">

**Comment by ronblum** [comment] 2020-06-02 16:17
Actually, the reason for what looks like my reproducing the issue is that `wußte` isn't in the `de_DE.dic` dictionary file; only `wusste` is present. The reverse happens with `zustößt` because only it's present in the dictionary, while `zustösst` is not.

@neuwirthe Can you provide a few words for which you see the issue? I want to make sure it's not just because of the words I picked.

**Comment by neuwirthe** [comment] 2020-06-02 21:35
Ok. an issue I was not careful about is that the German New dictionary does not work with realtile spellchecking.
Since I write according to the new rules.
The rules have changed quite a bit regarding ß.
Where are the dictionaries located (I am on a Mac)

<img width="795" alt="2020-06-02_23-30-17" src="https://user-images.githubusercontent.com/157619/83572057-320a4f00-a529-11ea-97c7-add6cf58ddae.png">

**Comment by neuwirthe** [comment] 2020-06-03 10:10
Here are some other works marked as possible errors:
täglich
Fälle
Todesfälle

These word are correct in both the old and the new German rules.

**Comment by adamconroy** [comment] 2020-06-08 21:26
Hi @neuwirthe, did you happen to upgrade from an older version of RStudio to 1.3? Unfortunately the old dictionaries weren't properly UTF-8 encoded so non-ASCII characters could fail to spell check.

Can you try going to Global Options -> Spelling and scroll to the bottom of the dictionary drop-down and select Update Dictionaries? This should redownload them and give you the correctly encoded versions. It may require an RStudio restart.

If this doesn't work for you we can dig into it further. I have confirmed on my version of 1.3 with the latest dictionaries that the words you listed work correctly.

**Comment by neuwirthe** [comment] 2020-06-10 10:18
Thank you, updating the dictionaries solved the problem.
Any change to also being able to use the German New dictionary for real time checkin any tome soon now?

**Comment by ronblum** [comment] 2020-08-14 20:02
@adamconroy Should the request for real time spellchecking for the German New dictionary be a new request? Or is it tied to #7218 or another issue?

**Comment by adamconroy** [comment] 2020-08-15 03:04
That will be done as part of #7218 yeah. Hopefully I can find good Typo.js compatible dictionaries for all of the languages. Sadly I believe the rule algorithm in the library has some flaws that are causing these issues and it might require a more thorough examination of it to make this all right.

**Closed** 2020-09-17 21:46 UTC
Labels: bug, spellcheck

**Comment by kevinushey** [comment] 2020-10-22 22:58
Verified with RStudio 1.4.963; real-time spellchecking appears to work well with the `German (New)` dictionary.

It seems some words are still marked as incorrect; e.g.

<img width="270" alt="Screen Shot 2020-10-22 at 3 57 09 PM" src="https://user-images.githubusercontent.com/1976582/96938440-3fe05280-147f-11eb-841d-81ad166e4e14.png">

but those errors are presumedly a property of the dictionary being used, and ultimately fixing this would require finding a better dictionary. However, given that users can add words themselves to an existing dictionary, I think it's okay to treat this as fixed / verified.

(If required, we could track updating the dictionary as a separate work item?)

**Comment by florianhartig** [comment] 2021-11-12 14:32
I have the same problem with RStudio Desktop 1.4.1717

**Comment by dernst** [comment] 2023-11-14 15:05
We're having this problem with rstudio pro 2023.09.0. I believe this is an encoding error in the dictionaries that are being downloaded by rstudio as part of "Install more dictionaries". More specifically, the file `~/.config/rstudio/dictionaries/languages-system/de_DE_neu.aff` is wrong. This file is encoded in UTF-8 however in line 13 it says `SET ISO8859-1`. Changing this line to `SET UTF-8` seems to have solved this problem for me.

Unfortunately this gets overridden if you use the "Update dictionaries" option in the rstudio config UI.

**Comment by thilop** [comment] 2023-12-06 16:51
I had the same problem and can confirm that changing the value is a solution.

> We're having this problem with rstudio pro 2023.09.0. I believe this is an encoding error in the dictionaries that are being downloaded by rstudio as part of "Install more dictionaries". More specifically, the file `~/.config/rstudio/dictionaries/languages-system/de_DE_neu.aff` is wrong. This file is encoded in UTF-8 however in line 13 it says `SET ISO8859-1`. Changing this line to `SET UTF-8` seems to have solved this problem for me.
> 
> Unfortunately this gets overridden if you use the "Update dictionaries" option in the rstudio config UI.
> 
> There's already an issue on it: #8147

**Comment by Schleicher-Thomas** [comment] 2024-01-24 20:46
> The error is that the first one, `wußte`, is getting marked as misspelled. It should not be—the spelling is correct.

But "wußte" is actually spelt incorrect. 
https://www.duden.de/suchen/dudenonline/wu%C3%9Fte

**Comment by neuwirthe** [comment] 2024-01-25 09:54
“wußte” is correct according to the old roles (dictionary German)
but not according to the new rules (dictionary German new)
