### ISSUE TITLE
Indentation settings ignored in package vignette

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9211] opened 2021-04-09 20:09 UTC
**Steps to reproduce:**
* Create an R package.
* Configure both the global options and the project options to use more than 2 spaces per tab, and to use spaces.
* Add an Rmd vignette through `usethis`.
* Add an R code chunk in the vignette.
* Use tab for indentation inside the code chunk.

**Expected behavior:** should use the configured indentation for the project or from the global options.

**Actual behavior:** uses tabs, with a width of 2 spaces.

**Setup:** RStudio 1.4.1547.

**Comment by ronblum** [comment] 2021-04-22 19:53
Thanks @david-cortes ! I can reproduce this in
- RStudio Desktop 1.4.1681 on MacOS 11.3
- RStudio Server 1.4.1681 on Ubuntu 20.04 via Chrome on MacOS 11.3

However, it works fine in
- RStudio Server 1.4.1106 on Red Hat 8.3 via Chrome on MacOS 11.3

So this appears to be a regression.

**Comment by jmcphers** [comment] 2021-04-22 20:11
Candidate for JR since it is a regression from the stable version.

**Comment by kevinushey** [comment] 2021-04-22 20:16
I suspect this is because of the Auto-detect code indentation preference:

<img width="609" alt="Screen Shot 2021-04-22 at 1 15 27 PM" src="https://user-images.githubusercontent.com/1976582/115779407-cf05ee80-a36c-11eb-9fb9-71feb3bf58f3.png">

`usethis::use_vignette()` creates vignettes from a template that uses two-space indentation; e.g.

`````
---
title: "hello"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hello}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(pkg)
```
`````

And because that file is already created to use 2-space indentation, RStudio detects and chooses to respect that.

**Comment by kevinushey** [comment] 2021-05-18 20:34
To be honest, I think the "right" solution here is to just turn off auto-detect code indentation by default. While it can be useful, the behavior is confusing and fairly non-apparent for users.

**Comment by kevinushey** [comment] 2021-07-09 20:48
Main thing to test is that the "Auto-detect code indentation" preference is off by default in brand new RStudio sessions.

<img width="601" alt="Screen Shot 2021-07-09 at 1 47 46 PM" src="https://user-images.githubusercontent.com/1976582/125134453-3f92f080-e0bc-11eb-9c8b-d8f7699e2e0e.png">

**Comment by ronblum** [comment] 2021-07-22 19:21
Using the above example, confirmed that
1) The autodetect option is unchecked by default.
2) Th indentation used by the set tab width is used if autodetect is turned off, and only two spaces are used when turned on.

Verified in
- RStudio Desktop 1.5.232 on MacOS 12 beta
- RStudio Server 1.5.233 on Ubuntu 20.04.2 via Safari on MacOS 12 beta

**Comment by ronblum** [comment] 2021-07-22 19:22
Marking for possible automated testing—not specific to vignettes, but to autodetecting indentation in general.

**Comment by ronblum** [comment] 2021-08-12 13:14
Following discussion with @astayleraz , the automated test focus will be on making checking the core change, that the option is unchecked by default. Testing indentation itself here and elsewhere will be handled separately.

**Comment by astayleraz** [comment] 2021-08-13 19:32
I added an automation check for the default setting for the auto-indent setting. Closing issue.

**Closed by astayleraz** 2021-08-13 19:32 UTC
Labels: bug, regression, packaging, test, autotest
