### ISSUE TITLE
Lists in the File view don't display all contents at bottom

### ISSUE THREAD

**Issue by TheBrightlyProject** [rstudio/rstudio#4662] opened 2019-04-18 08:34 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  v1.2.1502-1
    OS Version      : macOS Mojave 10.14.4
    R Version       : Latest

### Steps to reproduce the problem
1. Navigate to a directory that has a longer list of files than can fit in the Files view without scrolling
2. Scroll, or drag the scroll bar to the bottom
3. See that there are still files but cut off in the viewport

### Describe the problem in detail
Can't see the last file in a directory if the list of files is bigger than the view window.
I have attached a picture of this, where I have scrolled and moved the scroll bar to the bottom, yet I can't see the last file in the directory.

<img width="599" alt="Screenshot 2019-04-18 at 4 29 23 PM" src="https://user-images.githubusercontent.com/22562573/56347799-a257f300-61f7-11e9-8647-a46b01f8d96c.png">

### Describe the behavior you expected
That once the scroll bar is at the bottom, that the bottom of the list is visible.

**Comment by pascaloettli** [comment] 2019-04-18 10:18
I can reproduce in version `1.2.1502-1`. This doesn't happen in version `1.2.1335`. Looks like a regression. 

    RStudio Edition : Desktop
    RStudio Version : 1.2.1502-1
    OS Version      : macOS Mojave 10.14.4
    R Version       : 3.5.3

(not reproducible in Ubuntu)

**Comment by kevinushey** [comment] 2019-04-18 16:05
Likely related to https://github.com/rstudio/rstudio/pull/4580.

**Comment by kevinushey** [comment] 2019-04-18 17:16
Interestingly, I cannot reproduce when using my MBP's builtin display, but can when using an external display (+ scrolling with mouse) ...

**Comment by kevinushey** [comment] 2019-04-18 17:24
@pascaloettli were you able to reproduce using your laptop's own display, or were you using an external monitor?

**Comment by jmcphers** [comment] 2019-04-18 23:12
Fixed in #4665.

**Comment by ronblum** [comment] 2019-06-04 14:13
@TheBrightlyProject and @pascaloettli I don't see the problem in 1.2.1522; however, I can't reproduce it in 1.2.1502. Can you confirm whether or not the problem is resolved in the latest preview build?

**Comment by pascaloettli** [comment] 2019-06-05 01:35
@kevinushey Sorry, I didn't see your message. It was on both.
@ronblum Problem solved since `1.2.1511`

**Comment by ronblum** [comment] 2019-06-05 15:02
@pascaloettli Thanks for checking!

**Comment by TheBrightlyProject** [comment] 2019-06-06 01:25
Sorry for also chiming in late. No issues here with: 1.2.1522

**Comment by ronblum** [comment] 2019-06-06 13:03
Thank you @TheBrightlyProject for checking as well!

**Comment by kevinushey** [comment] 2019-06-19 17:21
I'm seeing this again in v1.2.1541.

**Comment by kevinushey** [comment] 2019-06-21 19:26
Looks like a regression from https://github.com/rstudio/rstudio/commit/3c61cd27e855f82a434a8e872774b69a63a0cc2c#diff-d8c9d190556b0a17a26366934efb62c0.

Looks like the right solution needs to somehow balance:

1. Ensuring superfluous horizontal scrollbars don't show up in e.g. the Environment pane;
2. Ensuring one can still scroll to the bottom of a regular DataGrid.

**Closed** 2019-06-25 22:42 UTC
Labels: bug, repro needed, verified
