### ISSUE TITLE
Console prompt cursor character problem and crash at startup in RStudio daily

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rstudio#3641] opened 2018-10-10 09:31 UTC
At startup a `?`instead of `>` is shown and if commands are sent to console the session crashes.
I think it's something related to access to the .RData. Because when the session crashes and restart the workspace is empty and if I save the new empty workspace the bug doesn't trigger at the next startup. Also, even if I manually restart after the crash the workspace is empty!

Another suspicion is related to the fact that my RStudio projects are inside a google drive folder (which is in turn inside a dropbox folder); google drive showed me notification of files which got restored in the folders of the projects which showed the problem.

Unfortunately the bug is not consistent, so sometimes its triggered, sometimes is not and I'm not able to reproduce it.

My workaround is to restart the session before sending any commands and manually reload the .RData afterward. After restarting the session I still see `?`instead of `>`, but I just need to hit Return a couple of time to restore the proper prompt cursor.

### System details

RStudio Edition : Desktop
RStudio Version : 1.2.1031 (daily)
OS Version      : MacOs 14.0
R Version       : 3.5.1

**Comment by kevinushey** [comment] 2018-10-11 02:17
Any chance you can share the workspace causing this issue?

Often, this is caused by an unintentional call to `base::parse()` with no arguments, but it's not yet clear why this might be occurring.

**Comment by bakaburg1** [comment] 2018-10-11 08:45
I wish I could, but again it's totally not predictable! I know I'm not of much help but I hoped that being detailed in the problem would trigger some intuition in people who know RStudio code base.

**Comment by jmcphers** [comment] 2019-11-12 22:07
Sorry, we're not sure we know what's going on here, and haven't had any other reports in over a year, so closing for now. Let us know if you're still seeing it with more recent RStudio builds.

**Closed by jmcphers** 2019-11-12 22:07 UTC
Labels: bug, repro needed
