### ISSUE TITLE
RStudio hanging while installing "BH" package on Windows 7 using RStudio and packrat

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#1864] opened 2017-12-17 19:15 UTC
Not sure where this issue belongs so I'm cross posting from https://github.com/rstudio/packrat/issues/433

I have a fresh install of R 3.4.3, RStudio Preview 1.1.399, the development version of packrat, Windows 7, Dropbox is turned off.

I created a new project using packrat using RStudio ran ``install.packages("BH")``, and it has been hanging ever since. 

I have also run this using R in Powershell and it installs in a normal amount of time.

**Comment by kendonB** [comment] 2017-12-17 19:20
```r
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252    LC_MONETARY=English_New Zealand.1252
[4] LC_NUMERIC=C                         LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3   tools_3.4.3      packrat_0.4.8-53
```

**Comment by kevinushey** [comment] 2017-12-17 20:24
Thanks for the bug report. I can reproduce this; it appears that the issue is indeed only triggered when using both RStudio + Packrat together (the issue doesn't occur when installing BH within e.g. RGui + Packrat, nor when installing BH when not within a Packrat project)

**Comment by kendonB** [comment] 2018-01-22 09:42
I've found this problem of packrat hanging while installing a number of different packages from RStudio. I've also had reports of similar issues from a colleague who uses Mac.

**Comment by oguzhanogreden** [comment] 2018-04-14 08:53
I'm having the same issue with BH package, using packrat within RStudio on Windows 10.

**Comment by jmcphers** [comment] 2018-06-22 19:09
Should be fixed with https://github.com/rstudio/rstudio/commit/307c6e70d029735d76ffd1afb3133c871d1ccf22.

**Comment by ronblum** [comment] 2018-08-23 14:47
Verified in 1.2.914-1.

**Comment by bjce** [comment] 2018-09-04 18:50
I have Windows 10, with R 3.5.1 and Rstudio 1.1.456 and I can't install BH both on RStudio or R alone

**Comment by adamrobinson361** [comment] 2018-10-02 13:28
Is this fix now available in the latest windows r studio release? This would solve a lot of our Windows installation problems I think whilst using rstudio

**Comment by kevinushey** [comment] 2018-10-02 17:06
It's not fixed in the latest release, but the fix is available in the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) if you're willing to give it a try.

**Comment by lisovyk** [comment] 2018-10-16 08:44
Is there a workaround for those who can't use preview release?

**Comment by gdutz** [comment] 2018-11-22 16:20
With Windows 10, R 3.5.1, packrat 0.5.0 and the latest RStudio Preview 1.2.39 I still have an issue: Installation of "BH" seems to be successful, but CPU usage of the RStudio R Session stays unusually high and the console is not responsive. Installing BH without packrat works fine.

**Comment by tchakravarty** [comment] 2019-04-20 04:19
@kevinushey 

I downloaded the latest preview release: 

![image](https://user-images.githubusercontent.com/2289192/56452652-54570280-6351-11e9-8384-a7dc258a4d33.png)

and am trying to install {{tidyverse}} with a {{packrat}}-enabled RStudio project, but it has been stuck trying to unpack for the last 10 minutes: 

![image](https://user-images.githubusercontent.com/2289192/56452679-823c4700-6351-11e9-98e0-cab546e55a84.png)

What might the issue be? I am not sure how to provide a reproducible example in this context, so please let me know if you need any additional information. 

Thanks.

**Comment by ronblum** [comment] 2019-05-02 14:43
I'm able to reproduce this on Windows 7, both with 1.2.1335 and 1.1.463, so this is not a regression. It's not an issue on MacOS 10.14.

**Comment by aheggie** [comment] 2019-05-14 23:50
Just installed latest versions of R and Rstudio on a Windows 10 machine that's never had any R installed on it - Rstudio hangs installing BH on a packrat-tracked project, not on other untracked projects

furthermore after trying to add BH several times packrat::status() and packrat::snapshot() now give these new errors/warnings

```
> packrat::status()

The following packages are referenced in your code, but are not present
in your library nor in packrat:

    readr

You will need to install these packages manually, then use
packrat::snapshot() to record these packages in packrat.
Error in if (pkg$name == pkgName) return(pkg) : 
  argument is of length zero
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  No DESCRIPTION file for installed package 'file1f7826cf60a3'
2: In FUN(X[[i]], ...) :
  No DESCRIPTION file for installed package 'file32bc2aa56f5f'
3: In FUN(X[[i]], ...) :
  No DESCRIPTION file for installed package 'filebd43b51217'
4: In FUN(X[[i]], ...) :
  Package 'readr' not available in repository or locally
> packrat::snapshot()
Error: Unable to retrieve package records for the following packages:
- "file1f7826cf60a3", "file32bc2aa56f5f", "filebd43b51217"
```

I think those files are somehow related to the three attempted installs of BH, as those warnings are new and I havent done anything besides trying to install BH

**Comment by aheggie** [comment] 2019-05-14 23:55
Ok not to spam responses but just to say I tried one more time (without running any other commands) and there is now a fourth file so it seems related:

`> packrat::snapshot()
Error: Unable to retrieve package records for the following packages:
- "file1ca02e621280", "file1f7826cf60a3", "file32bc2aa56f5f", "filebd43b51217"`

**Comment by randrescastaneda** [comment] 2019-05-21 16:07
Just to report that I have the same problem. `Installing BH (1.69.0-1) ...` hangs with no resolution. 
Thanks.

**Comment by g-tregonning** [comment] 2019-05-24 15:58
Also have the same problem!

**Comment by kevinushey** [comment] 2019-05-24 22:34
It still looks like the underlying problem here relates to the RStudio file monitor. While the R session attempts to unpack the archive, the file monitor thread is simultaneously trying to collect information about the files. It seems like there's contention between the two threads that causes the process to hang.

I'm also seeing something really weird -- if you try to remove an installation of BH using e.g. `remove.packages("BH")`, then R seems to hang as well.

**Comment by kevinushey** [comment] 2019-05-24 23:27
One other issue: RStudio is still running its behind-the-scenes library / lockfile hashing, and this is quite slow as we recursively search _all_ files in the library for DESCRIPTION files -- this can be slow when large packages (e.g. BH) are installed. This is unnecessary since we just need to look for DESCRIPTION files at the root package paths. See: https://github.com/rstudio/rstudio/blob/b6d30146e9f3e798dd73c3325d096ea2b36d9d07/src/cpp/session/modules/SessionPackrat.cpp#L243-L247

@jmcphers, is it expected that this behind-the-scenes Packrat code is still running?

**Comment by g-tregonning** [comment] 2019-05-26 08:48
I tried installing an older version of BH using the http source from Bristol Uni archives and it worked. SO this may be a good workaround if you aren't bothered about having the most recent version of BH.

`packageurl <- "https://cran.r-project.org/src/contrib/Archive/plogr/plogr_0.1-1.tar.gz"
> install.packages(packageurl, repos=NULL, type="source")`

**Comment by jmcphers** [comment] 2019-05-28 17:03
@kevinushey Yes, this still runs so that we can get the packrat state (even though we don't auto snapshot any more).

**Comment by kevinushey** [comment] 2019-06-04 19:04
Brain-dumping some notes. It looks like we get a giant cascade of file change events when BH is installed (or removed, even). Note that there are 11387 files in the BH directory reported after install; we get a file event for each file.

It looks like, for _every_ file change, we attempt to re-process the Packrat project state:

![Screen Shot 2019-06-04 at 11 40 28 AM](https://user-images.githubusercontent.com/1976582/58906332-8da8bf00-86c0-11e9-94df-78f2cb1fe872.png)

This means (recursively!) listing files in the Packrat directory thousands of times.

I also saw one case where R seemed to actually be stuck _recursively_ calling `.rs.listPackagesPackrat()` for some reason, but I have no idea how this could occur ...

**Closed** 2019-06-10 17:55 UTC
Labels: bug, reproducible, verified
