### ISSUE TITLE
/usr/lib/rstudio/bin/rsession: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MavropaliasG** [rstudio/rstudio#7955] opened 2020-10-04 03:09 UTC
I want to report a problem I had and a solution I got, in the hopes that others find it useful.

    RStudio Edition : Desktop
    RStudio Version : 1.4.869
    OS Version      :  Manjaro LInux on LInux 5.8.11
    R Version       :  R version 4.0.2 (2020-06-22)

After upgrading to 1.4.869  (through this https://aur.archlinux.org/packages/rstudio-desktop-preview-bin) Rstudio failed to open with the following message

```
The R session process exited with code 127.

/usr/lib/rstudio/bin/rsession: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
```

A user helped me and told me to install extra/postgresql-libs, which fixed my problem. They said "If you don't have it installed and aren't using PostgreSQL it's probably an upstream RStudio issue - they may be looking to connect to PostgreSQL by default."

**Comment by znmeb** [comment] 2020-10-04 04:24
I tried to reproduce this on Ubuntu 18.04 LTS "Bionic Beaver" and it works there. It turns out the RStudio package downloaded from https://rstudio.com/products/rstudio/download/preview/ is installing `libpq5` as a dependency, so it works. The Arch User Repository PKGBUILD needs to add the Arch client library as a dependency. RStudio folks - you can close this as "Unable to reproduce". I'll go update the AUR page.

**Closed** 2020-10-04 17:37 UTC
