### ISSUE TITLE
Support YAML autocompletion in R Markdown + Quarto documents (inline YAML)

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#9895] opened 2021-09-28 08:11 UTC
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2021.12.0.82
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : R version 4.1.1 (2021-08-10)

### Steps to reproduce the problem

1. Open RMarkdown document.
2. Insert empty R chunk.
3. Try writing `page` (at least 3 characters of chunk option name) and expect an auto-completion pop-up to appear. But nothing happens.

![RS-add-autocompletion--paged_print](https://user-images.githubusercontent.com/12725868/135047775-73917a7c-1c1f-4d27-a117-502f8e17127a.gif)

### Describe the problem in detail

Chunk option `paged.print` has no auto-completion activated.

### Describe the behavior you expected

I expect the chunk option `paged.print` and its values (TRUE/FALSE) to have auto-completion possibilities in RStudio as most of the other chunk options have this feature.

Could this be implemented in the next release of RStudio?

**Comment by ronblum** [comment] 2021-09-28 16:19
@GegznaV Thank you for raising this! I can reproduce this at least as far back as RStudio Desktop 1.2.5042 on MacOS 12 beta.

**Comment by GegznaV** [comment] 2022-03-28 12:56
Still reporducible in 

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.2.0.443
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.1.3 (2022-03-10)


Are there any plans for solving this in the near future?

**Comment by GegznaV** [comment] 2022-09-28 12:28
Still an issue in:


    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.7.1.554
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

**Comment by romainfrancois** [comment] 2022-12-05 13:09
We could add missing options in `.rs.knitrChunkOptions()`, or even add them directly to `knitr:::opts_chunk_attr`, but that'd make these knitr options also available outside of rmarkdown.

**Comment by GegznaV** [comment] 2023-11-16 20:34
It seems that the original issue for R Markdown style options is fixed:
![image](https://github.com/rstudio/rstudio/assets/12725868/ff791816-037c-40f0-8454-4a61bc36ad7a).
But there are no auto-completion/suggestion options for the value (`TRUE`/`FALSE`):
![image](https://github.com/rstudio/rstudio/assets/12725868/02695a31-62ed-4cd0-bb09-dde64a33e7be)

There is no auto-completion for the Quarto style option too:
![image](https://github.com/rstudio/rstudio/assets/12725868/34f7d6c3-7467-498d-b237-326e951069a2)

Should this issue be closed and new issues opened? Or it's better to keep it open?

**Comment by kevinushey** [comment] 2023-11-17 18:25
Let's keep this issue and use it to track adding autocompletion support for YAML chunk options.

**Comment by kevinushey** [comment] 2024-01-26 21:05
> But there are no auto-completion/suggestion options for the value (TRUE/FALSE):

This happens because `knitr` declared `paged.print` to be a numeric option, e.g.

```
> knitr:::opts_chunk_attr$paged.print
[1] "numeric"
```

From https://github.com/yihui/knitr/blob/a14074c58e46fb51f61b219c8a195a8ef4914971/R/defaults.R#L152-L155.

**Comment by kevinushey** [comment] 2024-02-08 21:18
This may be related to this Quarto issue: https://github.com/quarto-dev/quarto-cli/issues/8652

In particular, Quarto's bundled YAML autocompletion helper fails if the chunk contains inline options in the chunk header.

**Comment by ronblum** [comment] 2024-02-22 15:27
Verified in
- RStudio Desktop 2024.4.0+475 on MacOS 14.3.
- RStudio Server 2024.4.0+469.pro5 on Ubuntu 22 via Chrome on MacOS 14.3.

Checked in
- R Markdown and Quarto documents
- Source and visual modes
- With and without the commas (for the heck of it)

**Closed by ronblum** 2024-02-22 15:27 UTC
Labels: bug, autocompletion, r markdown, quarto, pm
