### ISSUE TITLE
"Special" characters from Windows pop-up tool are not inserted

### ISSUE THREAD

**Issue by francisbarton** [rstudio/rstudio#7954] opened 2020-10-03 12:44 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.869 (also tested in 1.3.1073)
    OS Version      : Windows 10
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Close all RStudio instances
1. Start a new session of RStudio
1. Create a fresh RMarkdown document
1. Press the key combination <kbd>Win</kbd> + <kbd>.</kbd>
     (<kbd>Win</kbd> + <kbd>;</kbd> is an alternative combination to achieve the same thing)
2. Select the `Ω` tab to select from a range of characters (this is navigable with keyboard or mouse)
3. Select the desired character, and click - or press <kbd>Enter</kbd> - to insert
4. The character appears to be inserted momentarily but then immediately disappears

Possibly a duplicate of, or connected to, #4584

### Describe the problem in detail
The Windows "special" character [pop-up tool](https://www.zdnet.com/article/windows-10-tip-get-easy-access-to-symbols-emojis-and-other-special-characters/) is a convenient way to insert emoji and a wide range of characters not usually found on the hardware keyboard. This pop-up tool is available in recent updates to Windows.
The pop-up tool is working fine for me in other apps such as Word, and within this browser text entry field I am currently using.
If I use the tool to insert a character into Word, then cut and paste it into RStudio, it pastes in fine.

When I try to use it in RStudio, it fails to insert a character, as described above.
This also applies to inserting emoji, though I feel that is less important than more common characters such as `é`
This has been tried within an RMarkdown document and within a text entry field, namely the "Find and Replace" feature (<kbd>Ctrl</kbd> + <kbd>F</kbd>)

However, the Windows "Character Map" program _does_ succeed in inserting a character.
The [technique](https://support.microsoft.com/en-gb/office/insert-ascii-or-unicode-latin-based-symbols-and-characters-d13f58d3-7bcb-44a7-a4d5-972ee12e50e0) of using <kbd>Alt</kbd> + numeric keypad codes also succeeds fine in RStudio.
The error seems particular to the pop-up tool.

### Describe the behavior you expected

The selected character is successfully inserted into the document or field.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-10-05 15:58
Thanks -- I was able to reproduce. This did not reproduce using Ace kitchen sink + Chrome, so it may either be due to the older version of Ace we're using, or the version of Qt WebEngine.

**Comment by kevinushey** [comment] 2020-10-14 20:46
Note: worth checking if this is automagically fixed via the Qt 5.15.1 update.

**Comment by francisbarton** [comment] 2021-08-20 21:01
Weirdly, and by complete chance, I have found one emoji that successfully inserted from the pop-up tool into an R script in the Source pane: this one 😊 (`U+1F60A`). It is also copy-and-pasteable around the document.
I haven't tried *all* the others, but every other one I have tried has failed to insert.

**Comment by gtritchie** [comment] 2022-03-29 17:45
I can reproduce the problem on Windows-10 (21H1) with RStudio 2022.02.1-461 (latest official Qt-based desktop release).

With the same Electron-based build, the issue goes away.

So it appears this problem is fixed by Windows-11 for all versions of RStudio Desktop, and fixed on Windows-10 by the Electron build of RStudio.

**Comment by gtritchie** [comment] 2022-03-29 17:54
Confirmed this is fixed by Electron on Windows-10. On Windows-11, the problem goes away for both Qt and Electron-based RStudio.

**Closed by gtritchie** 2022-03-29 17:54 UTC
Labels: bug, ace, qtwebengine, backlog
