### ISSUE TITLE
Error message appears when creating Quarto Projects with capital letters in the project name

### ISSUE THREAD

**Issue by kelli-rstudio** [rstudio/rstudio#14907] opened 2024-07-01 21:16 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 2024.07.0-daily+250 
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem
1. Use new project wizard to create a Quarto Project with a new directory
2. Name the project something with a capital letter like: "quartoProj17198657262318404"
3. Create the project and see the following error message and that the quarto file fails to open automatically

![image](https://github.com/rstudio/rstudio/assets/114421526/6eaabf07-8de0-4625-ab3c-19466e48647c)

### Describe the problem in detail
Creating a Quarto project using a name that contains capital letters results in a "No such file or directory" error. However, the error does not appear when using a name with all lowercase letters and numbers like "quartoproj123456789012345". 

### Describe the behavior you expected
Quarto projects with names that contain capital letters should open without an error message and the generated quarto file should open automatically

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2024-07-01 21:40
This is the same as https://github.com/rstudio/rstudio/issues/14894, which _should_ have been fixed by the update to Quarto 1.5.49 via https://github.com/rstudio/rstudio/pull/14895.

**Comment by gtritchie** [comment] 2024-07-01 21:44
Build 2024.07.0-daily+250  is from before that fix was made. Try using build 257 or newer. Assuming it works (the fix was already verified and closed), you can close this issue as a duplicate of #14984.

**Closed** 2024-07-01 21:45 UTC
Labels: bug, new
