### ISSUE TITLE
Missing shared objects at v1.2.243

### ISSUE THREAD

**Issue by pslacerda** [rstudio/rstudio#4277] opened 2019-02-08 18:04 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.243
    OS Version      : Ubuntu 18.04.1 LTS
    R Version       : 3.4.4

### Steps to reproduce the problem

Install the daily build 1.2.243.

### Describe the problem in detail
When attempting to run the `bin/rstudio` program, some libraries are missing. They are not installable in current Ubuntu.

### Describe the behavior you expected
Open the RStudio Desktop.

I simply downloaded the missing libraries from From Ubuntu trusty (14.04LTS), copied all `.so` files to the `bin/` directory.

* libgstreamer-plugins-base0.10-0_0.10.36-1.1ubuntu2.1_amd64.deb
* libgstreamer0.10-0_0.10.36-1.2ubuntu3_amd64.deb

**Comment by jmcphers** [comment] 2019-02-08 18:25
Is 1.2.243 really your build? That's very old, and we don't use gstreamer any more. Does the issue reproduce with the preview release?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by pslacerda** [comment] 2019-02-08 18:41
1.2.243 is really the latest build I found.

https://dailies.rstudio.com/rstudio/oss/ubuntu/x86_64/xcopy/
![image](https://user-images.githubusercontent.com/149358/52498242-0090a600-2bb7-11e9-8cca-f4791e9520e5.png)

Yes, first I tried with the preview. The R session aborts when running any Python chunk on a Rmd file, so I skiped the current preview (1.2.1270, at least on that link) towards 1.2.243.

Even earlier I tried the 1.1 for use the reticulate Python engine, but it wasn't obvious for me that it was a preview feature for 1.2.

**Comment by jmcphers** [comment] 2019-02-08 19:32
It looks like the problem might just be that the dailies page weren't picking up the new builds! Just pushed a fix, want to try with a newer build?

https://dailies.rstudio.com/rstudio/oss/ubuntu/x86_64/xcopy/

**Comment by pslacerda** [comment] 2019-02-08 21:36
I'm downloading this preview release, and will give a try.

**Comment by pslacerda** [comment] 2019-02-09 05:10
I not really downloaded, but noticed that I had already tested it.

It installs alright.

Run a Python chunk aborts the R session, as I said before. Should open another issue?

**Comment by jmcphers** [comment] 2019-02-09 05:32
Yes, please, especially if you can get a callstack (try attaching to `rsession` with gdb)

**Comment by jmcphers** [comment] 2019-02-11 17:47
Closing this one (we'll track the crash separately!)

**Closed by jmcphers** 2019-02-11 17:47 UTC

**Comment by pslacerda** [comment] 2019-02-11 18:05
Cool!
