### ISSUE TITLE
Switching between Source <-> Visual Modes for a Quarto Document Breaks Code Cell Play Button with Escaped Chunk

### ISSUE THREAD

**Issue by coatless** [rstudio/rstudio#14805] opened 2024-06-07 17:20 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.1 Build 748
    OS Version      :  macOS 14.5 (23F79)
    R Version       :  4.4.0

### Steps to reproduce the problem

1. Open a blank Quarto document.  Using **Source** mode, paste the following code into the Quarto document:

`````md
---
title: "Play button interactive with md escape"
format: html
editor: visual
---

```{r}
1 + 1
```

```` md
```{{bash}}
echo $USER
```
````

Gives:

```{bash}
echo $USER
```

`````

2. Switch into the **Visual** Mode from **Source** Mode. Notice the play buttons in the later portion of the document. 

3. Switch back into the **Source** mode from the **Visual** Mode. 

Notice that the play buttons are no longer present after the `md` escape code cell due to a new space being added next to `md`, e.g.

The switch from **Visual** back to **Source** causes: 

`````md
````md
```{{bash}}
echo $USER
```
````
`````

To go to: 

`````md
```` md
```{{bash}}
echo $USER
```
````
`````

This removes the play button for the later code cell. Deleting the space between `md` and the cell definition yield the right results.

### Describe the problem in detail

We wrote the document in source mode where each interactive cell has a play button

<img width="800" alt="A screenshot showing the initial Quarto document state in the source mode with play buttons appearing next to each interactive code cell" src="https://github.com/rstudio/rstudio/assets/833642/45b4736c-c6be-44a2-8b9e-c7d4139de29b">

Pressing **Visual** transforms it to a WYSIWYG editor with play buttons still present

<img width="801" alt="A screenshot showing the Quarto document after switching from the **Source** to **Visual** mode with the play buttons  to execute code still appearing next to each interactive code cell" src="https://github.com/rstudio/rstudio/assets/833642/bf4afd87-afde-46b4-b1ab-1dcc78679a15">

Switching back to **Source** causes the play buttons to disappear from cells later in the document. 

<img width="803" alt="A screenshot showing the Quarto document after switching for the last time from **Visual** to **Source** mode with the play buttons in the later document now being missing from the code cells" src="https://github.com/rstudio/rstudio/assets/833642/67a26a0b-97f1-4728-b9b3-9177230a6b37">

### Describe the behavior you expected

There shouldn't be a space inserted after the `md` and the play buttons should not randomly disappear from the later code cells after switching from Source -> Visual -> Source.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-06-10 13:03
@coatless Thank you for raising this! I'm not sure that I'm entirely reproducing the issue, but I am seeing at least as far back as RStudio Desktop 2022.07.2+576 that the run buttons don't appear in source mode, only in visual mode.

**Comment by ronblum** [comment] 2024-06-17 16:47
@coatless BTW, is this new behavior in the 2024.04.1 release, or did you see it earlier, similar to what I found above?

**Comment by coatless** [comment] 2024-06-17 18:48
@ronblum great question; not entirely sure. I'm more in the VS Code realm at the moment. I've been jumping back into RStudio when I'm teaching. So, it would have to be somewhere between now and about 1 year back?

**Comment by kevinushey** [comment] 2024-10-30 17:35
It looks like this has since been fixed in the daily builds:

<img width="531" alt="Screenshot 2024-10-30 at 10 34 43 AM" src="https://github.com/user-attachments/assets/50c6acc0-aaa3-4c2e-b65e-a8b2bdb6e885">

Any chance you could try and test? These builds are available at https://dailies.rstudio.com/.

**Comment by gtritchie** [comment] 2024-10-31 16:30
I was able to repro in Cranberry Hibiscus patch 1, but confirmed it no longer repros in 2024.11.0-daily+341.

**Closed by gtritchie** 2024-10-31 16:30 UTC
Labels: bug, visual markdown
