### ISSUE TITLE
RStudio doesn't start/connect to R

### ISSUE THREAD

**Issue by stgries** [rstudio/rstudio#11069] opened 2022-04-26 19:20 UTC
I just upgraded my OS to POP OS 22.04. As a result, starting RStudio (2022.02.1 Build 461) doesn't start R anymore. I did some digging online and it seems the situation is comparable to what's described [here](https://github.com/rstudio/rstudio/issues/10149) or [here](https://community.rstudio.com/t/rstudio-issue-in-linux/134716).

Right now the situation is this:

- if I start RStudio by double-clicking on an .Rmd file, it seems to start an rsession, but doesn't connect and nothing gets shown in the RStudio window;
- If I start RStudio with <code>rstudio --no-sandbox</code> at a terminal prompt, it works fine;
- If I start RStudio with <code>sudo rstudio</code> at a terminal prompt, it works but I get this output:

TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/root/.local/share/rstudio/log/rdesktop.log'.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[But the file '/root/.local/share/rstudio/log/rdesktop.log' does not exist.]

- if I start RStudio with <code>rstudio</code> at a terminal prompt, I get this:

<code>$ rstudio
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/xdg/xdg-pop:/etc/xdg/rstudio/logging.conf'. Logging to '/home/USER/.local/share/rstudio/log/rdesktop.log'.
The X11 connection broke (error 1). Did the X11 server die?</code>

The file desktop.log contains the following:

2022-04-26T15:35:09.126055Z [rdesktop] ERROR Unable to find libR.so in expected locations within R Home directory You are in </home/USER> and these are your available functions; LOGGED FROM: bool rstudio::core::r_util::{anonymous}::detectRLocationsUsingR(const string&, rstudio::core::FilePath*, rstudio::core::FilePath*, rstudio::core::config_utils::Variables*, std::__cxx11::string*, const string&, const string&, const rstudio::core::FilePath&) src/cpp/core/r_util/REnvironmentPosix.cpp:592

Here is my sessionInfo():

```
$ sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 22.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.3
```

I have completely uninstalled RStudio multiple times, but it's not helping -- any ideas on what I might have to do? Thanks a lot!

**Comment by dat-linux** [comment] 2022-04-26 21:06
ubuntu 22.04. I have latest R, the latest rstudio amd64 binary as zip, downloaded. It opens, then freezes (needs xkill to kill the window frame, as close button does not respond) without loading the body of the application. Same for the .deb install. I have libssl1.1 and libssl3 installed.  The .deb install doesn't complain, but just fails to launch as described. I cannot find any logs to see what errors are being logged.

22.04 is a LTS release and has been keenly awaited for months. For rstudio to just break like this is very frustrating.

**Comment by stgries** [comment] 2022-04-26 21:13
> ubuntu 22.04. I have latest R, the latest rstudio amd64 binary as zip,
> downloaded. It opens, then freezes (needs xkill to kill the window frame,
> as close button does not respond) without loading the body of the
> application.
>
Yes, same here, only xkill or the system monitor can shut it down.

**Comment by kevinushey** [comment] 2022-04-26 21:41
Duplicate of https://github.com/rstudio/rstudio/issues/10902.

**Closed by kevinushey** 2022-04-26 21:41 UTC

**Comment by stgries** [comment] 2022-04-26 21:49
I'm not sure whether that is the same bug. Like I described, I could
clearly install it, it works well if run as a superuser or with the
--no-sandbox option, so not being able to install it is not the issue --
clearly, it is installed, just not running when started as a normal user or
with double click on a code or rmarkdown file.

**Comment by abalter** [comment] 2023-05-31 20:55
This is still a problem. #13184
