### ISSUE TITLE
Object explorer expand button disappears when modifying one or more list items in-place as char

### ISSUE THREAD

**Issue by slin30** [rstudio/rstudio#4969] opened 2019-06-18 13:28 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Windows 10 Enterprise
    R Version       : 3.6.0

### Description
When modifying a `list` (or `data.frame`), where _modifying_ includes:

* in-place
* appending, but referencing an existing element

...where the source column is not already `character`, and the action is to coerce to `character` via `as.character()`, the environment pane object's expansion arrow disappears. Thus far, this seems to only occur with `as.character` and not e.g. `paste`. 

### Repex (all-in-one; see per-command screens below)
```
ll <- list(a = 1, b = "1")
# this is ok
ll[[3]] <- paste(ll$a)
# this is also OK (calling as.character on a chr)
ll[[4]] <- as.character(ll$b)
# but this is not-- expansion icon disappears
ll[[5]] <- as.character(ll$a)
```

### Screens
`ll <- list(a = 1, b = "1")`
![s1](https://user-images.githubusercontent.com/13291275/59687512-d8d7cd00-91aa-11e9-9c5f-2917d4f32f13.png)

`ll[[3]] <- paste(ll$a)`
![s2](https://user-images.githubusercontent.com/13291275/59687514-d8d7cd00-91aa-11e9-8907-f1d86a4645d0.png)

`ll[[4]] <- as.character(ll$b)`
![s3](https://user-images.githubusercontent.com/13291275/59687518-d9706380-91aa-11e9-89fe-f63f5744538d.png)

`ll[[5]] <- as.character(ll$a)`
![s4](https://user-images.githubusercontent.com/13291275/59687522-d9706380-91aa-11e9-9849-430179e1e11a.png)

### Sessioninfo
```
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0   
```

**Comment by ronblum** [comment] 2019-06-18 16:49
@slin30 Thank you for filing this issue. I believe it's a reproducible duplicate of #4758, which should be fixed in a future release of RStudio:

```
> ll_char <- list(a = as.character("1"))
> .rs.hasAltrep(ll_char)
[1] FALSE
> ll_num <- list(a = as.character(1))
> .rs.hasAltrep(ll_num)
[1] TRUE
```

**Closed by ronblum** 2019-06-18 16:49 UTC

**Comment by slin30** [comment] 2019-06-18 17:06
Thanks @ronblum; I did my best to look through open issues, but did not check closed; appreciate the follow-up and insight re: Altrep.
