### ISSUE TITLE
spellcheck popup does not display

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#11306] opened 2022-05-26 20:56 UTC
### System details

    RStudio Edition : 2022.6.0.439
    RStudio Version : Desktop [Open Source]
    OS Version      : macOS Monterey 12.4
    R Version       : R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem

Create an R document containing some spelling errors, and then try to hover your mouse over the error.

### Describe the problem in detail

A small tiny box is displayed at the bottom-right of the spellchecked word.

<img width="168" alt="Screen Shot 2022-05-26 at 1 54 58 PM" src="https://user-images.githubusercontent.com/1976582/170578630-ac06a05a-f7fb-43e5-9ae7-e051c212e96c.png">

### Describe the behavior you expected

Either we should display nothing, or we should display something a bit more relevant; perhaps something like:

```
Misspelled word 'xyz'.
Right click to open spell-check menu.
```

For reference, the previous display (which was not great)

<img width="204" alt="Screen Shot 2022-05-26 at 1 55 29 PM" src="https://user-images.githubusercontent.com/1976582/170578715-aad2333e-1a9f-4f63-92d5-69004ee5e51f.png">

---

<details>

<summary>Session Info</summary>

``` r
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0   
```

</details>

**Comment by mikebessuille** [comment] 2022-05-31 18:16
i think we should remove the box.

**Comment by gtritchie** [comment] 2022-05-31 20:03
Duplicate of #5348?

**Comment by kevinushey** [comment] 2022-05-31 20:23
Sort of -- previously, we displayed a tooltip showing only "Spellcheck"; now, you just see a small rectangle.

**Comment by romainfrancois** [comment] 2022-10-04 16:12
Do we have code to guess alternatives ? Otherwise, as @mikebessuille said, we can just remove the box.

**Comment by kevinushey** [comment] 2022-10-04 18:29
I think we can either:

1. Remove the box, or
2. Provide a message like "Misspelled word (right click for suggestions)"

Do we think it's "obvious" that a user can right-click on a misspelled word to get the popup suggestion list?

**Comment by romainfrancois** [comment] 2022-10-14 07:21
We might reconsider removing the tooltip later, but for now we've brough back the "Spellcheck" text.

**Comment by romainfrancois** [comment] 2022-10-14 13:13
Another thing to consider is that we can get into this situation: 

<img width="253" alt="image" src="https://user-images.githubusercontent.com/2625526/195855591-8ed4d1e7-f5e1-488d-bde4-d846dec7535b.png">

**Comment by kevinushey** [comment] 2022-10-14 17:07
> We might reconsider removing the tooltip later, but for now we've brough back the "Spellcheck" text.

Given that buglet I think we should just remove the Spellcheck tooltip and consider bringing it back later if we want to give it some proper descriptive text (+ fix other UI issues). What do you think?

**Comment by romainfrancois** [comment] 2022-10-14 18:05
Yeah, I'll revert and then try to figure out how to remove the empty tooltip.

**Closed** 2022-12-05 16:33 UTC
Labels: bug, spellcheck
