### ISSUE TITLE
Probleme with choropleth  for the France

### ISSUE THREAD

**Issue by guillaumeFAGOT** [rstudio/rstudio#5175] opened 2019-08-02 07:58 UTC
Hi,
There is a problem to get a map of the France with GADM on Rstudio.
I'dont have the problem with R.
I use **RStudio
Version 1.1.463 – © 2009-2018 RStudio, Inc.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko)**
I don't have the problem with the map of Belgium or the USA with Rstudio.
( to change of country I change 
`Fr<-gadm_sf_loadCountries("BEL",level=2)`
or
`Fr<-gadm_sf_loadCountries("USA",level=2)`
Below the code :
```
library(GADMTools)
Vinter2 <- data.frame(NomDept=c("Loire-Atlantique","Bouches-du-Rhône",
                                "Hauts-de-Seine","Yvelines",
                                "Val-de-Marne","Essonne"),
                      NumDept=c(44,13,92,78,94,91),
                      NbreVoyage=c(532,354,350,332,315,293),
                      stringsAsFactors=FALSE)
Fr<-gadm_sf_loadCountries("FRA",level=2)
choropleth(Fr, 
           data =     Vinter2,
           value =    "NbreVoyage", 
           adm.join = "NomDept",
           breaks =   "pretty", 
           palette =  "Oranges",
           legend =   "test",
           title =    "test2")
```
This is the error send by the system on Rstudio (whith the France as I said)
> Error in UseMethod("choropleth", x) : 
>   pas de méthode pour 'choropleth' applicable pour un objet de classe "NULL"
>

**Comment by pascaloettli** [comment] 2019-08-02 08:15
Did you try with the [current version](https://download1.rstudio.org/desktop/macos/RStudio-1.2.1335.dmg)? I cannot reproduce neither on Linux nor on MacOS.

**Comment by guillaumeFAGOT** [comment] 2019-08-02 12:21
I think that I can't use a more updated package cause I'm on a **32** bits macs.
Version 1.1.463 – © 2009-2018 RStudio, Inc.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko)
The .dmg current version file that I've put on my computer can't be installled.
Is it possible to find a fix ?

**Comment by ronblum** [comment] 2019-08-02 18:35
@guillaumeFAGOT RStudio Desktop 1.2.1335 is not supported for Mac OS X 10.11 (El Capitan), unfortunately. 

What version of R are you using? I've tried reproducing on a few environments, using 1.1.463 and 1.2.1335. What I've found is that on RStudio Desktop
- for France, sometimes the command completes but no plot is rendered.
- it hangs for USA (macOS 10.15 Catalina, RStudio Desktop 1.2.1335, R 3.6.1). In standalone R, it takes a while, but eventually completes (it takes a few minutes).

But! After working for a while, I suddenly got a similar null error, but when running in standalone R with Belgium:
> Error in UseMethod("depth") : 
  no applicable method for 'depth' applied to an object of class "NULL"

and I can't get out of that state. I'm not sure what's causing it, other than trying it out many times. So the "NULL" issue might be an issue with R.

That said, the France plot not always displaying is enough to mark this as a bug.

**Comment by ronblum** [comment] 2019-08-02 18:54
@guillaumeFAGOT For Belgium in R, I was able to get out of that state by removing the .RData file. Can you try closing RStudio, backing up the ~/.RData file, then removing it? Or if you're in a project, the file would be in the project directory. Then restart RStudio and try again.

**Comment by guillaumeFAGOT** [comment] 2019-08-06 07:39
Thanks, I will look at this, as soon as possible.

**Closed** 2019-10-17 18:33 UTC
Labels: bug
