### ISSUE TITLE
RStudio Server Pro calling `View()` returns Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by jonkeane-socure** [rstudio/rstudio#7199] opened 2020-06-23 15:48 UTC
### System details

    RStudio Edition : RStudio Server Pro
    RStudio Version : 1.3.1031-1
    OS Version      : Ubuntu 18.04.4 LTS
    R Version       : 4.0.1 and 3.6.2

### Steps to reproduce the problem
1. open a new session
2. run `View(mtcars)`

### Describe the problem in detail
I notice that with any data frame I've tried, when I call `View()` (e.g. `View(mtcars)`) I get the error:

```
Show Data Frame
Exception caught: (TypeError) : Cannot read property 'substr' of null
```

After this happens the data displays just fine, though other aspects of the files/other objects open in the source pane are in a bad state (e.g. command-return won't execute lines selected or not). Re-opening a .R file will make it work again sometimes. Typically I will have to quit the session from the main RStudio page before it will be fully working again.

### Describe the behavior you expected
Being able to use `View()` dataframes without the error + the UI oddities that follow

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kfeinauer** [comment] 2020-06-23 16:18
Duplicate of #7163. Update to the latest daily and the issue should go away.

**Closed by kfeinauer** 2020-06-23 16:18 UTC

**Comment by jmcphers** [comment] 2020-06-23 16:40
You can get a new preview here:

https://www.rstudio.com/products/rstudio/download/preview/
