### ISSUE TITLE
Make R Markdown setup chunks work the same for chunk output inline & in console

### ISSUE THREAD

**Issue by apreshill** [rstudio/rstudio#7863] opened 2020-09-23 14:12 UTC
The current behavior in the IDE is that `setup` chunks in an R Markdown document are automatically run when working in ["notebook mode"](https://r4ds.had.co.nz/r-markdown.html#chunk-name) (i.e., chunk output is shown inline when working in the IDE). But, this doesn't work if you send your chunk output to the console instead. This is often confusing for R Markdown users; for example, see:

+ <https://community.rstudio.com/t/what-defines-the-setup-chunk/27595>
+ <https://community.rstudio.com/t/automatic-execution-of-setup-chunk-in-rmd/71483>
+ <https://twitter.com/PhilippBayer/status/1272774062733791233?s=20>

I think it is a great feature for working interactively in R Markdown, and would like to see those of us who prefer to send chunk output to the console to get the same experience! Is it possible to have `setup` chunks work the same, regardless of this setting in the IDE? 

Here is a reprex courtesy of community member @francisbarton: <https://gist.github.com/francisbarton/fa84117627271ae20bcf68d55cd7c274>

Thank you for considering!
Alison

**Comment by mikebessuille** [comment] 2021-01-13 14:00
Requested by RMarkdown team

**Comment by francisbarton** [comment] 2021-08-22 13:20
This appears to be working fine now! My reprex works, anyway.

**Comment by jgutman** [comment] 2022-06-10 16:08
This is actually linked to several bugs reported by @hadley (at least 3 or 4 I think), and I think we need to prioritize this earlier than 2024 @mikebessuille

**Comment by jgutman** [comment] 2022-06-10 16:27
Actually this is a duplicate of #10677

**Closed by jgutman** 2022-06-10 16:27 UTC
Labels: enhancement, notebooks, backlog, notebook mode

**Comment by francisbarton** [comment] 2022-06-11 16:32
Probably more accurate to say that 10677 (newer) is a duplicate of this, but whatever gets the work done I guess.
