### ISSUE TITLE
Malformed list output in Notebooks

### ISSUE THREAD

**Issue by ewenharrison** [rstudio/rstudio#4783] opened 2019-05-10 15:01 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1335 Build 1379 (f1ac3452)
    OS Version      : Windows 10: Platform: x86_64-w64-mingw32/x64 (64-bit)
    R Version       : R version 3.6.0 (2019-04-26)

### Steps to reproduce the problem

![Capture](https://user-images.githubusercontent.com/3391394/57536168-88638900-733b-11e9-9990-6a8ec5fcf3e6.PNG)

### Describe the problem in detail

Same/similar to : #3163

Has not been fixed by workaround now written into distribution: https://github.com/rstudio/rstudio/commit/9e545543166b4d6139dd6ed4e3cc185db9415c47

We have replicated this problem over 3 windows computers fully up-to-date today. 

### Describe the behavior you expected
Output without ÿþ

**Comment by ronblum** [comment] 2019-05-13 13:45
@ewenharrison Thank you for reporting this and providing information, including the screenshot. I'm going to mark this as a duplicate of #3163 and reopen that issue.

**Closed by ronblum** 2019-05-13 13:45 UTC
