### ISSUE TITLE
Repeated "*** recursive gc invocation" warnings, followed by RStudio crash

### ISSUE THREAD

**Issue by eipi10** [rstudio/rstudio#10565] opened 2022-02-10 17:42 UTC
I work on a virtual Windows server that I remote into. For the last few weeks many of my RStudio sessions have been crashing within a few minutes to a few hours. The crash almost always happens in the middle of some operation on a relatively large data frame (a few million rows), often a `dplyr` pipe of several operations or creating a ggplot, where the following is written to the console (the number of repeats varies). 

> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation
> *** recursive gc invocation

Then, usually within about 10 to 30 seconds, RStudio crashes. When I reopen the project, whatever code edits I hadn't saved are generally gone. Also, even after RStudio crashes, I can see in the Task Manager that R and RStudio processes related to  the crashed session are still running, and any RAM the session was using is often still tied up and not available for other processes.

I've also had some other warnings I haven't seen before. These don't seem to be associated (at least not immediately) with crashes, but I'm including an example in case it's relevant. These warnings seem to occur in the middle of `dplyr` pipe operations.:

> Warning: stack imbalance in '.Call', 78 then 76
> Warning: stack imbalance in '{', 74 then 72
> Warning: stack imbalance in '.Call', 76 then 75
> Warning: stack imbalance in '{', 72 then 71

I don't have a reproducible example, because this seems to happen randomly and doesn't seem to depend on the specific code I've been running. My local computer is a Macbook Pro and I've never had this happen on it (though I'm running the same R and RStudio versions as on the Windows virtual machine). I'd also never seen the "recursive gc invocation" warning until a few weeks ago. I'm not sure if it coincided with any particular changes in the system or the R setup. 

I asked a [question about this problem](https://community.rstudio.com/t/how-to-fix-recursive-gc-invocation-followed-by-rstudio-crash/127607/2) on RStudio Community. No one had an answer, but two people commented about similar problems they've been having.

Below are the details for the remote virtual computer.  Please let me know if additional information would be helpful. 

> Operating system: Windows Server 2016 Standard, Version 1607, Build 14393.4886
> R  version 4.1.2
> RStudio version: 2021.09.2+382 "Ghost Orchid" Release (fc9e217980ee9320126e33cdf334d4f4e105dc4f, 2022-01-04) for Windows, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
> 
> Session info varies, but below is a typical one. I also load several internal packages that I haven't included below.
> 
> R version 4.1.2 (2021-11-01)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows Server x64 (build 14393)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] tools     stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] ggdist_3.0.1                  naniar_0.6.1                  vroom_1.5.7                  
>  [4] patchwork_1.1.1               forcats_0.5.1                 stringr_1.4.0                
>  [7] dplyr_1.0.7                   purrr_0.3.4                   readr_2.1.1                  
> [10] tidyr_1.1.4                   tibble_3.1.6                  ggplot2_3.3.5                
> [13] tidyverse_1.3.1               lubridate_1.8.0               readxl_1.3.1                 
> [16] scales_1.1.1                  fst_0.9.4                     openxlsx_4.2.5               
> [19] rlang_0.4.12                  knitr_1.37                   
> [34] reprex_2.0.1                  testthat_3.1.1                devtools_2.4.3               
> [37] usethis_2.1.5                
> 
> loaded via a namespace (and not attached):
>  [1] fs_1.5.2             bit64_4.0.5          httr_1.4.2           rprojroot_2.0.2      backports_1.4.1     
>  [6] utf8_1.2.2           R6_2.5.1             DBI_1.1.2            colorspace_2.0-2     withr_2.4.3         
> [11] tidyselect_1.1.1     prettyunits_1.1.1    processx_3.5.2       bit_4.0.4            compiler_4.1.2      
> [16] cli_3.1.0            rvest_1.0.2          xml2_1.3.3           desc_1.4.0           odbc_1.3.3          
> [21] callr_3.7.0          digest_0.6.29        rmarkdown_2.11       pkgconfig_2.0.3      htmltools_0.5.2     
> [26] sessioninfo_1.2.2    dbplyr_2.1.1         fastmap_1.1.0        keyring_1.3.0        rstudioapi_0.13     
> [31] farver_2.1.0         generics_0.1.1       jsonlite_1.7.2       distributional_0.3.0 zip_2.2.0           
> [36] magrittr_2.0.1       Rcpp_1.0.7           munsell_0.5.0        fansi_0.5.0          visdat_0.5.3        
> [41] lifecycle_1.0.1      stringi_1.7.6        yaml_2.2.1           pkgbuild_1.3.1       blob_1.2.2          
> [46] grid_4.1.2           parallel_4.1.2       crayon_1.4.2         haven_2.4.3          hms_1.1.1           
> [51] ps_1.6.0             pillar_1.6.4         pkgload_1.2.4        glue_1.6.0           evaluate_0.14       
> [56] remotes_2.4.2        modelr_0.1.8         vctrs_0.3.8          tzdb_0.2.0           cellranger_1.1.0    
> [61] gtable_0.3.0         assertthat_0.2.1     cachem_1.0.6         xfun_0.29            broom_0.7.11        
> [66] memoise_2.0.1        ellipsis_0.3.2

**Comment by jeffvroom** [comment] 2022-02-10 21:06
Yes, that does sound like an issue in ghost-orchid that we fixed. Another workaround is to add:

--- /etc/rstudio/rsession.conf:
session-handle-offline-enabled=0

This will prevent you from being able to save/open files when R is busy, but avoids the problematic code path that cause that recursive gc warning and potential crash.

**Comment by eipi10** [comment] 2022-02-10 21:20
> Would you be able and willing to test whether this issue is resolved with the preview release of RStudio? https://www.rstudio.com/products/rstudio/download/preview/

@kevinushey Yes, happy to test. Do you have specific code I should run that you think is likely to reproduce the problem, or should I just do my regular workflow and see if the problem occurs?

**Comment by jeffvroom** [comment] 2022-02-10 22:49
This is the issue that we just fixed: https://github.com/rstudio/rstudio/issues/10424 

It happens when you try to save a file or do another file based operation when R is busy, and it runs a gc at the same time. It's pretty hard to reproduce reliably so I'd say go about your regular workflow.

**Comment by Westat-Transportation** [comment] 2022-02-10 22:49
We are having similar issues on an environment where RStudio is invoked over an RDP app session.    In our case the recursive gc() invocation error messages come up when running `librtary(haven)`.  

Our case sounds a lot like the issues found by @eipi10.

**Comment by eipi10** [comment] 2022-02-10 22:56
@Westat-Transportation I also use RDP for my remote sessions.

**Comment by Westat-Transportation** [comment] 2022-02-10 22:57
The server admin is going to try installing the preview version to see if it fixes the issue.

**Comment by eipi10** [comment] 2022-02-10 23:05
After a few minutes running code in an rmarkdown document I've been working on, I can confirm that the code is running *much* faster and peak RAM usage is about 20% lower. Before updating RStudio to the preview version, R was often using up all or nearly all of the 32GB of RAM available. I will report back later on whether I get any crashes after working on the document for a while.

**Comment by Westat-Transportation** [comment] 2022-02-10 23:12
We can also confirm that installing the preview version fixes the crashes related to using haven with the recursive gc() error messages.

**Comment by kevinushey** [comment] 2022-02-15 17:17
Great news -- thanks for taking the time to test and report back! I'm going to close this issue, but please let us know if you run into any other issues.

**Closed by kevinushey** 2022-02-15 17:17 UTC
Labels: bug, repro needed

**Comment by bbneo** [comment] 2024-04-02 13:22
I have encountered this error running RStudio-server in WSL... usually during a process which involves gregexpr() operations on large textstreams using mclapply() to apply multiple patterns simultaneously across 10-15 processes.

My RStudio version is:

RStudio 2021.09.2+382 "Ghost Orchid" Release (fc9e217980ee9320126e33cdf334d4f4e105dc4f, 2022-01-04) for Ubuntu Bionic
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

/ScannerHG_Production$ R --version
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by kevinushey** [comment] 2024-04-02 16:42
@bbneo -- any chance you can share a standalone reproducible example?

**Comment by bbneo** [comment] 2024-05-01 11:26
This seems to happen after my program intermittently saves a moderate size intermediate RData Results file (1 Mb... WSL environment across a Google Drive mount point) and then starts into a new stage of parallel processing (library(parallel), mclapply())  for the next file.

Most recently... the parallel process started, but seems to be hung, and one processor is running at 100% for several hours (overnight).  

Any intuition?  Might it help me to run a gc() ( "garbage collection") either before or after each file is processed or whenever the intermediate file is written?

**Comment by kevinushey** [comment] 2024-05-01 20:34
It could, if the issue were caused by the R garbage collector running at an inopportune time, or if memory exhaustion was somehow causing issues... but that's still just speculation; there's still no obvious apparent cause to me :-/
