### ISSUE TITLE
Output not consistently displayed for Python scripts called by Rmd R chunks

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3271] opened 2018-08-06 20:26 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.873-2
    OS Version      : Ubuntu 16.04.2/4
    R Version       : 3.4.4 and 3.5.1
    Python Version  : 2.7.12 and 3.5.2
    Reticulate Vers : 1.1.0

### Steps to reproduce the problem

All of these steps need to be performed twice: once with Python 2 and a second time with Python 3.
1. Create a Python file called `oneline.py` that contains the following code:
```
print("One line")
```

2. In the console, run the following code:
```
library(reticulate)
use_python("/usr/bin/python")
py_run_file("oneline.py")
```

3. Create an R Markdown file that contains the following code:
````
---
title: "One Line Python"
output: html_notebook
---
  
```{r setup}
library(reticulate)
use_python("/usr/bin/python")
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
py_run_file("oneline.py")
```
````

Or, for more detail and comparing to code that works:

````
---
title: "One Line Python"
output: html_notebook
---

**Begin with setup:**
```{r setup}
library(reticulate)
use_python("/usr/bin/python")
knitr::opts_chunk$set(echo = TRUE)
```

**Let's start by checking which version of Python is being used.**
First with Python:
```{python}
import sys
print(sys.version)
```

And second with R:
```{r}
py_config()
```

**Now let's run an R chunk that calls a one-line Python script.**
```{r}
py_run_file("oneline.py")
```

**Next, let's use a Python chunk that calls the same Python script.**
```{python}
exec(open("oneline.py").read())
```

**Finally, let's run the same code in a Python chunk.**
```{python}
print("One line")
```

**And we're done.**
````

4. Preview the Rmd file.
5. Knit the Rmd file.

Note: The R session needs to be restarted when changing Python versions.

### Describe the problem in detail

When using `py_run_file()` to execute an external Python file that displays output (using `print()`), the results aren’t always displayed.
1. In the console: works with Python 2.7 but not Python 3.5.
2. Previewing an R chunk of an Rmd file: works with Python 2.7 but not Python 3.5
3. Knitting to HTML an R chunk of an Rmd file: doesn’t work with either Python 2.7 or 3.5.

This is true for both R 3.4.4 and 3.5.1. 

### Describe the behavior you expected

The output from the external file should always get displayed, regardless of the version of Python, and even when the file is knitted.

Note:
- Running in R outside of RStudio works fine for both versions of Python. 
- Calling the external file from a Python chunk using `exec()` works fine for both, as well.

Even though this is an issue when using Python and reticulate, I’m filing it here because it works fine when running R in the terminal and only happens within RStudio.

**Comment by kevinushey** [comment] 2018-08-10 00:08
IIUC this is an issue in the `reticulate` package itself.

Note that if you're using Python 3.x, you need to explicitly flush stdout / stderr with `sys.stdout.flush()` and `sys.stderr.flush()` for output to be emitted -- for example:

`````
---
title: "Reticulate"
output: md_document
---
  
```{r}
reticulate::use_python("/usr/local/bin/python3", required = TRUE)
reticulate::py_run_string("
import sys
print('hello')
sys.stdout.flush()
")
```
`````

although perhaps `reticulate` should flush these for the user automatically after a `py_run_file()` and `py_run_string()`.

**Comment by ronblum** [comment] 2018-08-10 13:49
When I run this code, though, the only thing that shows up in the knitted output is the code, not the line `hello`. This is true for both Python 2.7.12 and Python 3.5.2 with reticulate 1.10.0 and 1.1.0.9000 (the dev version).

**Comment by kevinushey** [comment] 2018-08-10 16:16
Sorry, you're right. In essence, there are two bugs here (and both need to be fixed on the `reticulate` side).

**Comment by jjallaire** [comment] 2018-09-19 14:09
Could we address this by flushing after `py_run_file()` and `py_run_string()`? (I'm hesitant to remap the streams unconditionally b/c I'm not sure what other defects or anomalies that might trigger).

**Comment by jjallaire** [comment] 2018-09-19 14:19
Experimenting, I see that just flushing doesn't address the issue b/c knitr doesn't pick up the writes to stdout. Note that this isn't just a reticulate issue, calling the `system()` function exhibits the same problem:

    ```{r}
    system("echo 'foo'")
    ```

**Comment by kevinushey** [comment] 2018-09-19 18:19
Indeed. I guess my question is whether we should consider taking any action or just document this behavior (and perhaps nudge people towards using Python chunks explicitly if they want to see Python output)

**Comment by kevinushey** [comment] 2018-09-26 18:44
I'm going to close this. We can re-open if any users report similar confusion.

**Closed by kevinushey** 2018-09-26 18:44 UTC
Labels: bug, python

**Comment by deliciouslytyped** [comment] 2019-06-16 01:39
@ronblum @kevinushey I'm pretty sure I had this working a few days ago so I'm not sure what changed, but if I run
```
> library(reticulate)
> py_run_string("print('please work')")
``` 
in rstudio, I don't get any output.
I'm on `[Package reticulate version 1.12.0-9001 Index]` according to the docs (I just ran ` devtools::install_github("rstudio/reticulate")`).

Adding `sys.stdout.flush()` works. The reason I'm confused is I didn't have to do this earlier.

**Comment by kevinushey** [comment] 2019-06-17 16:27
Thanks, I can reproduce this too. I'll see if I can figure out what's going on. Interestingly it reproduces in RStudio but not in the regular R terminal...

**Comment by deliciouslytyped** [comment] 2019-06-17 18:20
Ah...sounds fun. Thanks for looking into it.

**Comment by kevinushey** [comment] 2019-06-17 23:21
Should be fixed now with the latest development version of `reticulate`.
