### ISSUE TITLE
Reindent & Reformat Lines stopped working in Quarto Callout Blocks

### ISSUE THREAD

**Issue by cy-james-lee** [rstudio/rstudio#14640] opened 2024-05-02 15:35 UTC
Verify fixed in:
- [x] Patch: 2024.04.2
- [ ] Release: 2024.07.0

---

### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0 Build 735
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : 4.4.0 (2024-04-24 ucrt)

### Steps to reproduce the problem
1. Open/create a quarto document.
2. Create a [Callout Block](https://quarto.org/docs/authoring/callouts.html)
3. Create a code block inside the callout block and write any multi-line code (that should have indentations).
4. Select all lines in the code block and perform Reindent Lines (Ctrl + I).

### Describe the problem in detail
All lines are moved to the left end, without any indentation.

````
::: {.callout-note collapse="true"}
```{r}
library(dplyr)
mtcars |> 
mutate(
mpg = seq_len(
n()
)
)
```
:::
````

### Describe the behavior you expected
Normal Reindent Lines (Ctrl + I) behavior is this:

````
```{r}
library(dplyr)
mtcars |> 
  mutate(
    mpg = seq_len(
      n()
    )
  )
```
````

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-05-02 15:55
@cy-james-lee Thank you for raising the issue! I can reproduce this in RStudio Desktop 2024.04.1+735 on Windows 11. 

Note: This is source mode only--it works in visual mode. Also, this works correctly in version 2023.12.1+402.

**Comment by petzi53** [comment] 2024-05-03 11:40
I experienced the same problem in source mode on macOS. In my case, it didn't work inside _and_ outside Quarto blocks. 

RStudio Edition : Desktop
RStudio Version : 2024.04.0+735
OS Version      : MacOS Sonoma 14.4.1
R Version       : 4.4.0 (2024-04-24) -- "Puppy Cup"
Quarto Version:  1.4.554

Indentation works with the previous RStudio Version 2023.12.1+402, but only with 2 spaces. The older version didn't respect changes in the global and project configuration. (I didn't notice this before).

In visual mode, everything works in the older and the latest RStudio version.

**Comment by cy-james-lee** [comment] 2024-05-03 16:47
I also noticed that collapsing code section doesn't work inside of callout blocks. 

I always add session info at the end of Quarto inside of a collapsed callout like so:
````
::: {.callout-note collapse="true"}
## Session Info
```{r}
sessionInfo()
```
:::
````

I don't have the collapse button next to ## Session Info:
![image](https://github.com/rstudio/rstudio/assets/13931593/736e79c5-1f82-49ab-950f-905e8ac75547)

If I comment out the callout block enclosure, I get the collapse button back.
![image](https://github.com/rstudio/rstudio/assets/13931593/ad995df1-eb8f-4e73-8a5f-b6a5d0d9dae0)

**Comment by ronblum** [comment] 2024-05-03 19:37
@petzi53 Can you provide a brief example of code in which you're seeing the issue?

@cy-james-lee I believe that what you're seeing is discussing in issue #14642.

**Comment by ronblum** [comment] 2024-05-08 19:19
Also @d-morrison found that this happens with reformatting (<kbd>cmd-shift-A</kbd> or <kbd>Menu Bar > Code > Reformat Code</kbd>).

**Comment by gtritchie** [comment] 2024-05-09 17:50
Regression caused by https://github.com/rstudio/rstudio/pull/14558.

**Comment by LeenSonneveld** [comment] 2024-05-10 08:26
This seems to occcur (in source editor) not only after callout block, but any ::: (eg. ::: column, ::: panel-tabset

**Comment by ronblum** [comment] 2024-05-29 19:32
Initial example verified fixed in RStudio Desktop 2024.07.0-daily+174, but need to test a little further.

**Comment by ronblum** [comment] 2024-05-30 13:04
Verified in RStudio Desktop 2024.04.2+762.pro1:
- The indentation works.
- Indentation respects the number of space of tab width.
- The collapse arrow is present.

**Comment by ronblum** [comment] 2024-05-30 13:32
Verified in 2024.07.0-daily+178.pro1 on Windows 11, as well.

**Closed by ronblum** 2024-05-30 13:32 UTC
Labels: bug, regression, source editor
