### ISSUE TITLE
Loading some dictionaries freezes RStudio even after RStudio is restarted

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6041] opened 2020-01-16 22:16 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.743 & 1.3.730
    OS Version      : MacOS 10.15.3
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Back up `~/.config/rstudio-prefs.json`
2. Tools -> Global Options -> Spelling
3. Change the main dictionary to Lithuanian
4. Apply
    - RStudio becomes unresponsive, possibly with a "Save" message that doesn't go away.
5. Force quit RStudio
5. Reopen RStudio
    - RStudio will open and display the IDE, but it is unusable—no typing or clickable menus.
6. Force quit RStudio
7. To return to the previous working state, copy the backup file from above to `~/.config/rstudio-prefs.json`
    - The backup file was necessary because the `rstudio-prefs.json` file has been updated with the newly-chosen dictionary, so RStudio becomes unusable.

### Describe the problem in detail

RStudio becomes unusable when certain dictionaries are chosen.

### Describe the behavior you expected

All dictionaries should be loaded properly and RStudio continue to run.

These dictionaries work:
- Danish
- Dutch
- English (all of them)
- German 
- Portuguese (Portugal)

But these dictionaries fail:
- Czech
- German (New)
- Lithuanian
- Portuguese (Brazil)

These are just some examples. I'm not sure what the differences and commonalities are. It's not the size of the file: at 2 MB, the Dutch dictionary is twice the size of Lithuanian and German (New). 

This works in RStudio Server 1.3.730 on Red Hat 7.8. Also, this is a regression, as it works fine in RStudio Desktop 1.2.5033.

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2020-01-22 21:22
Discussed with @adamconroy and we don't think there's a viable solution to this without using an entirely differently library which is out of scope for 1.3. We will blacklist the the languages that are problematic and forcibly disable real time spellchecking for those languages (with a warning)

**Comment by adamconroy** [comment] 2020-01-22 22:39
A little extra information for when I revisit this:

The core issue we're running into is that Typo.js runs out of memory when processing all of the rules for more complex languages. There are quite a few approaches we can take here but the crux of it is that certain languages just have nearly unbounded complexity. Loading some of these dictionaries even in non-typo.js libraries just takes a TON of memory (seen 6 gigs for Lithuanian). 

There are a few different approaches we can take for "solving" this but it's not a simple problem sadly. I think the above solution is the best we can do at the moment though now I'm wondering if the CPP handles this dictionary well.

- Loading these dictionaries "works" (until it runs out of memory anyway) https://github.com/titoBouzout/Dictionaries

**Comment by adamconroy** [comment] 2020-01-29 21:54
This is "fixed" now due to PR #6109. However, this was only done by turning off real time spellchecking for known incompatible dictionaries. A more permanent solution will take a lot of work due to the above problems. I'll file a separate issue as we no longer freeze, at least.

**Closed by adamconroy** 2020-01-29 21:54 UTC
Labels: bug, desktop, regression, spellcheck

**Comment by rich-rstudio** [comment] 2020-03-11 15:00
@adamconroy I verified that the blacklisted dictionaries do show the unavailable message, but if the user still hits Apply and then OK  on a blacklisted dictionary, then reopens the global options, the language is changed to English (Australia) but the unavailable message still is displayed.

**Comment by adamconroy** [comment] 2020-03-11 21:10
@rich-rstudio I am not able to reproduce this weirdness that you're seeing at all. Not sure what the cause is! I'm guessing if you restart the app though you'll see the correct dictionary. I tried on Linux, MacOS, and Windows all with the latest daily (1.3.906-8) and can't make it happen. hoping it's just a fluke.

**Comment by rich-rstudio** [comment] 2020-03-12 16:48
@adamconroy I checked on a newer build (Version 1.3.908) and the problem doesn't come up anymore. Thanks!
