### ISSUE TITLE
RStudio crashes when using dplyr filter with old R versions

### ISSUE THREAD

**Issue by noahprime** [rstudio/rstudio#13728] opened 2023-10-02 16:00 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version :  RStudio-2023.09.0-463
    OS Version      :  MacOS Ventura 13.5.2 
    R Version       :  3.6.3

### Steps to reproduce the problem
Using `ggplot2`, try and create a plot and view using the RStudio plots viewer.

### Describe the problem in detail
RStudio crashes and prompts you to restart.

This started happening when using the new RStudio version. I've since reverted back to RStudio-2023.06.2-561 and the problem is gone. 

There's also no problem when using the latest R version, but unfortunately the project I'm working on is still using a very old version. 

### Describe the behavior you expected
Plot to be produced in the plot viewer.

**I can return to this and edit the issue when I have time to run a diagnostic report. Sorry for now.**

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2023-10-02 19:17
Thanks for the bug report! Unfortunately, I wasn't able to reproduce locally. I tried running this code:

```
library(ggplot2)
ggplot(mtcars, aes(x = mpg, y = cyl)) + geom_point()
```

and had the plot generated as expected. For reference:

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X Snow Leopard 13.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.4.3

loaded via a namespace (and not attached):
 [1] fansi_1.0.4      withr_2.5.1      utf8_1.2.3       grid_3.6.3       R6_2.5.1         lifecycle_1.0.3  gtable_0.3.4     magrittr_2.0.3   scales_1.2.1    
[10] pillar_1.9.0     rlang_1.1.1      cli_3.6.1        farver_2.1.1     vctrs_0.6.3      labeling_0.4.3   tools_3.6.3      glue_1.6.2       munsell_0.5.0   
[19] compiler_3.6.3   pkgconfig_2.0.3  colorspace_2.1-0 tibble_3.2.1    
```

although note that I am running on an M1 macOS machine, running Ventura 13.6. Packages were all installed from sources.

**Comment by ronblum** [comment] 2023-10-04 10:21
Same—I don't run into a problem using the example above, using MacOS 14 on an Intel MacBook Pro with R 3.6.3.

@noahprime What happens if you use @kevinushey's sample code? If it works, can you provide sample code that breaks? And what happens if you plot without `ggplot2`, e.g. `plot(cars)`?

**Comment by kevinushey** [comment] 2023-10-04 16:19
Sorry, but I am still not able to reproduce. Does the same crash occur for you in a regular R session, outside of RStudio?

You might need to reinstall `dplyr` and all of its dependencies from sources.

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X Snow Leopard 13.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] ggplot2_3.4.3 dplyr_1.1.3  

loaded via a namespace (and not attached):
 [1] fansi_1.0.4      withr_2.5.1      utf8_1.2.3       grid_3.6.3      
 [5] R6_2.5.1         gtable_0.3.4     lifecycle_1.0.3  magrittr_2.0.3  
 [9] scales_1.2.1     pillar_1.9.0     rlang_1.1.1      cli_3.6.1       
[13] vctrs_0.6.3      generics_0.1.3   tools_3.6.3      glue_1.6.2      
[17] munsell_0.5.0    compiler_3.6.3   colorspace_2.1-0 pkgconfig_2.0.3 
[21] tidyselect_1.2.0 tibble_3.2.1  
```

**Comment by noahprime** [comment] 2023-10-04 17:07
@kevinushey Hmm strange. Works perfectly fine in a regular R session. I'm generally working on a project that uses `renv` for reproducibility, so not super flexible in the package versions I'm using. For now I'm fine using the previous RStudio version.

**Comment by kevinushey** [comment] 2023-10-06 17:24
Thanks -- I'm going to close this as not reproducible, but if you can share more details or if others encounter this issue we can re-investigate.

**Closed by kevinushey** 2023-10-06 17:24 UTC
Labels: bug, plots
