### ISSUE TITLE
Code chunks within HTML comments break the document when switched to visual editor

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#9060] opened 2021-03-04 20:04 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1589
    OS Version      : macOS 11.2.2
    R Version       : 4.0.4

### Steps to reproduce the problem

- Create an R Markdown document, and place the following text using the source editor> Note that there is a space within the backticks that define the code chunk (so that text shows properly here), you'll need to remove that when reproducing.

```
---
output: html_document
---

This text is not commented out

<!--

This is commented out text

` ``{r}
# this is a code chunk within the commented out area
1+1
` ``

--->

This text is also not commented out
```

- Knit the document, and as expected you get the following output.

![image](https://user-images.githubusercontent.com/5965649/110021484-affebf00-7d22-11eb-9ead-b5c29be83917.png)

- Switch to the visual editor, and in the editor, things appear to be ok.

![image](https://user-images.githubusercontent.com/5965649/110022400-c8230e00-7d23-11eb-95e8-a12fdc9bdc57.png)

- Knit the document again, and the second line of text is no longer there.

![image](https://user-images.githubusercontent.com/5965649/110022466-dd983800-7d23-11eb-9dfe-83ff994d496c.png)

### Describe the problem in detail

If you switch the editor back to source, the background coloring suggests the backticks that are supposed to be closing off the code chunk might now be closing the HTML block. But that still doesn't explain why the second line of text is not visible in the output.

![image](https://user-images.githubusercontent.com/5965649/110022824-54353580-7d24-11eb-9421-87c09bcafdaf.png)

Note that this becomes a pain point not just when switching between editor types but also when two collaborators are working on a project, one using the visual and the other using the source editor, and "Write canonical visual mode markdown in source mode" is set to true.

### Describe the behavior you expected

Since the visual editor also has a notion of "comments" I would expect this commented our block of text (including the code chunk) to be converted to such a comment.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment] 2021-07-21 11:19
I can repro this with just pandoc round-tripping the markdown as follows:

```bash
pandoc switch.Rmd --from markdown --to json | pandoc --from json --to markdown | pandoc --from markdown --to html 
```

So the issue isn't any visual editor specific manipulations but rather pandoc not "seeing" the backticks inside the HTML comment and consequently not including an extra backtick in the enclosing raw block.

**Comment by jjallaire** [comment] 2021-07-21 11:39
Should be fixed here: https://github.com/rstudio/rstudio/commit/8a25fe3e6d1371e5edf2363b62a9eadf1762414a

**Comment by astayleraz** [comment] 2021-08-02 20:29
I verified in Daily Version 2021-07.0.285-2 and following the steps I am not seeing the second line disappear after knitting. Closing issue.

**Closed by astayleraz** 2021-08-02 20:29 UTC
Labels: bug, test, visual markdown editing
