### ISSUE TITLE
RStudio ligature suport for superassignment

### ISSUE THREAD

**Issue by konradedgar** [rstudio/rstudio#1547] opened 2017-10-04 08:12 UTC
The ligature **`->>`** does not seem to be correctly represented in RStudio for superassignmemt.

<img width="352" alt="screen shot 2017-10-03 at 21 45 57" src="https://user-images.githubusercontent.com/7386756/31148379-725983e0-a884-11e7-9892-420abc2e255c.png">

It should be
```r
w ->> w
```

which I reckon should match:

<img width="55" alt="screen shot 2017-10-03 at 21 52 48" src="https://user-images.githubusercontent.com/7386756/31148644-3eddf6f8-a885-11e7-9acb-55d251980475.png">

---

- RStudio v1.1.379
- macOS High Sierra
- *Font:* [Fira Code Retina](https://github.com/tonsky/FiraCode)

**Comment by dfalty** [comment] 2017-10-04 16:48
It looks like this is specific to Fira Code font. I'm able to reproduce this.

Thanks for the report!

**Comment by jmcphers** [comment] 2017-10-04 17:29
@dfalty Does this also happen in the [Ace kitchen sink](https://ace.c9.io/build/kitchen-sink.html)?

**Comment by dfalty** [comment] 2017-10-04 18:19
What it looks like on Mac Safari.
![image](https://user-images.githubusercontent.com/15237845/31192348-9df928ca-a906-11e7-9a4f-df026da9df1d.png)

**Comment by dfalty** [comment] 2017-10-04 18:19
And Chrome.
![image](https://user-images.githubusercontent.com/15237845/31192390-b78dab1c-a906-11e7-97d2-6f69bb1e67b8.png)

**Comment by kevinushey** [comment] 2017-10-04 19:00
Hopefully this is something that may be fixed when we next update Ace?

**Comment by jmcphers** [comment] 2017-10-04 19:20
That's possible, but Ace isn't the only variable. It could also be that we need some CSS or similar to enable 3-character ligatures.

**Comment by konradedgar** [comment] 2017-10-04 19:37
Thanks for showing the interest, applying *Reformat Code* breaks the **`->>`** into **`->`** which breaks the code (as shown below).

![ligature](https://user-images.githubusercontent.com/7386756/31195874-9497724a-a943-11e7-846d-3031396cc66a.gif)

**Comment by kevinushey** [comment] 2017-10-04 20:50
Thanks for reporting -- this should be fixed with https://github.com/rstudio/rstudio/commit/2f61e0197d53f8db70bc0fd1f52d2595bae31e11.

**Closed** 2017-10-04 21:59 UTC
Labels: low, reproducible

**Comment by dfalty** [comment] 2017-11-03 15:14
Verified fixed 1.2.150
