### ISSUE TITLE
Orphaned windows after exiting shiny app (shinytest) when RStudio is fullscreen

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#2839] opened 2018-05-23 19:36 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.656
    OS Version      : Mac 10.12.6
    R Version       : 3.5.0

### Steps to reproduce the problem
1. Open RStudio in full-screen mode
2. Create the default shiny application
3. Record Test
4. Take at least one snapshot
5. Save script and exit test event recorder
6. Observe you now have an orphaned black window and you will get more if you do this over and over

### Describe the problem in detail
Orphaned windows after exiting shiny app (shinytest) when RStudio is fullscreen. 
![image](https://user-images.githubusercontent.com/15237845/40446610-644d3a7c-5e95-11e8-9aaa-7fcf77bfcb0d.png)

**Comment by MariaSemple** [comment] 2018-05-24 01:11
This issue seems like the same issue as #2663.

**Comment by javierluraschi** [comment] 2018-06-11 12:53
Duplicate of https://github.com/rstudio/rstudio/issues/2663

**Closed by javierluraschi** 2018-06-11 12:53 UTC
Labels: bug, duplicate, low, reproducible
