### ISSUE TITLE
IDE window goes black during package installation

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#2060] opened 2018-01-25 22:29 UTC
This is in v1.2 with qtwebengine. I did `devtools::install_github("rstudio/cloudml")` and after a few packages were successfully installed this occurred in the IDE:

<img width="1590" alt="screen shot 2018-01-25 at 5 26 43 pm" src="https://user-images.githubusercontent.com/104391/35415892-2fa3dff8-01f5-11e8-901f-e9b174a5bce0.png">

I noticed that a file download progress dialogs had shown up right before this happened so maybe that's related? (on windows we do some window arranging when the download dialog pops up b/c it used to show up behind the IDE, perhaps that code isn't working properly w/ qtwebengine?)

**Comment by kevinushey** [comment] 2018-01-29 21:15
I wasn't able to reproduce this. Are you able to consistently reproduce this?

It looks like you're running Windows in a VM -- FWIW, I've seen some similar rendering issues with other applications when run in this kind of configuration. Do you see the same thing on a native Windows machine?

**Comment by jjallaire** [comment] 2018-01-29 22:32
I am not able to reproduce it.

However I can also say I've never seen it happen prior to the QtWebEngine update (with RStudio or any other Windows application in this VM).

Probably nothing to do here other than see if it happens again to anyone.

**Comment by javierluraschi** [comment] 2018-03-02 05:26
I hit this all the time... but not during package, in my case, I hit this whenever my VM is idle, switching windows in OS X and then coming back to the VM. I'm using VM Fusion.

**Comment by ronblum** [comment] 2018-03-05 18:01
Closing #2302 as a duplicate. Information from there:

From @ronblum:
*OS Version      : Windows 10 Home (real), Windows 10 Enterprise & Pro (VM)*

*Steps to reproduce the problem*
1. Launch RStudio Windows Desktop
2. Put Windows to sleep (including closing laptop)
3. Wake up Windows (including opening laptop)

*Describe the problem in detail*
1. In some cases, RStudio freezes—can't type, switch tabs, etc. The only thing that seems to work is the top menu bar, but clicking on items doesn't actually do anything.
2. In other cases, RStudio is entirely black.
Exiting RStudio requires terminating it using the Task Manager. Right-clicking on the icon in the Taskbar and choosing "Close Window", or clicking on the X in the upper-right, don't work.

From @kevinushey:

Some other things worth testing:

- Does this reproduce in other QtWebEngine applications? (We can try running some of the sample applications provided with Qt)

- If so, is it by any chance fixed in Qt 5.10.1? Or does the issue exist in Qt 5.9.x as well?

**Comment by gtritchie** [comment] 2018-03-05 18:04
FYI, working on getting build updated to 5.10.1. https://github.com/rstudio/rstudio/pull/2321

**Comment by javierluraschi** [comment] 2018-03-12 22:03
A few more bits of information... I was able to remove this problem in my VM by turning off DirectX... These settings make this problem go away for me:

<img width="635" alt="screen shot 2018-03-12 at 2 58 44 pm" src="https://user-images.githubusercontent.com/3478847/37311854-21a303d6-2606-11e8-9efb-0ef8b4bbe8da.png">

However, enabling `Accelerated 3D Graphics` brings this problem back.

**Comment by tungmilan** [comment] 2018-05-24 15:47
This problem got worse if I had 2 RStudio sessions opened. My Win 10 laptop became extremely slow to the point it was almost frozen after waking up from sleep mode. The mouse pointer moved in slow motion mode. Things only returned to normal after I forced close RStudio from the Task Manager.

Relevant log from `diagnostics-report.txt` file

````
[1] "1.1.453"

$R
[1] "C:\\PROGRA~1\\R\\R-35~1.0\\bin\\x64\\R.exe"

$pdflatex
[1] "C:\\MiKTeX\\miktex\\bin\\x64\\pdflatex.exe"

$bibtex
[1] "C:\\MiKTeX\\miktex\\bin\\x64\\bibtex.exe"

$gcc
[1] "c:\\Rtools\\mingw_64\\bin\\gcc.exe"

$git
[1] "C:\\PROGRA~1\\Git\\cmd\\git.exe"

$svn
[1] ""

R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    yaml_2.1.19    fortunes_1.5-4

SysInfo:
       sysname        release        version       nodename        machine 
     "Windows"     ">= 8 x64"   "build 9200"    "user007X360"       "x86-64" 
         login           user effective_user 
       "user007"        "user007"        "user007" 

R Version:
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.0                         
year           2018                        
month          04                          
day            23                          
svn rev        74626                       
language       R                           
version.string R version 3.5.0 (2018-04-23)
nickname       Joy in Playing   

22 May 2018 06:41:27 [rsession-user007] ERROR system error 109 (The pipe has been ended); OCCURRED AT: virtual void rstudio::session::NamedPipeHttpConnection::close() C:\Users\Administrator\rstudio\src\cpp\session\http\SessionNamedPipeHttpConnectionListener.hpp:198; LOGGED FROM: virtual void rstudio::session::NamedPipeHttpConnection::close() C:\Users\Administrator\rstudio\src\cpp\session\http\SessionNamedPipeHttpConnectionListener.hpp:198
23 May 2018 17:42:49 [rsession-user007] CLIENT EXCEPTION (rsession-user007): (TypeError) : undefined is not an object (evaluating 'this.a.a.r.row');|||com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Exceptions.java#28::wrap|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#244::apply|||com/google/gwt/core/client/impl/Impl.java#283::entry0|||#-1::anonymous|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Windows NT 6.2  WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1
23 May 2018 17:42:50 [rsession-user007] CLIENT EXCEPTION (rsession-user007): (TypeError) : undefined is not an object (evaluating 'this.a.a.r.row');|||com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Exceptions.java#28::wrap|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#244::apply|||com/google/gwt/core/client/impl/Impl.java#283::entry0|||#-1::anonymous|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Windows NT 6.2  WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1
23 May 2018 19:58:00 [rsession-user007] CLIENT EXCEPTION (rsession-user007): (TypeError) : undefined is not an object (evaluating 'this.a.a.r.row');|||com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Exceptions.java#28::wrap|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#244::apply|||com/google/gwt/core/client/impl/Impl.java#283::entry0|||#-1::anonymous|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Windows NT 6.2  WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1
23 May 2018 19:58:00 [rsession-user007] CLIENT EXCEPTION (rsession-user007): (TypeError) : undefined is not an object (evaluating 'this.a.a.r.row');|||com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Exceptions.java#28::wrap|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#244::apply|||com/google/gwt/core/client/impl/Impl.java#283::entry0|||#-1::anonymous|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Windows NT 6.2  WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1
23 May 2018 19:58:00 [rsession-user007] CLIENT EXCEPTION (rsession-user007): (TypeError) : undefined is not an object (evaluating 'this.a.a.r.row');|||com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Exceptions.java#28::wrap|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#244::apply|||com/google/gwt/core/client/impl/Impl.java#283::entry0|||#-1::anonymous|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Windows NT 6.2  WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1
23 May 2018 21:28:06 [rsession-user007] ERROR system error 0 (The operation completed successfully); OCCURRED AT:  :0; LOGGED FROM: rstudio::core::Error rstudio::r::session::graphics::handler::shadow::writeToPNG(const rstudio::core::FilePath&, rstudio::r::session::graphics::handler::DeviceContext*) C:\Users\Administrator\rstudio\src\cpp\r\session\graphics\RShadowPngGraphicsHandler.cpp:297
23 May 2018 21:28:20 [rsession-user007] CLIENT EXCEPTION (rsession-user007): (TypeError) : undefined is not an object (evaluating 'this.a.a.r.row');|||com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Exceptions.java#28::wrap|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#244::apply|||com/google/gwt/core/client/impl/Impl.java#283::entry0|||#-1::anonymous|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Windows NT 6.2  WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1
23 May 2018 21:28:21 [rsession-user007] CLIENT EXCEPTION (rsession-user007): (TypeError) : undefined is not an object (evaluating 'this.a.a.r.row');|||com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Exceptions.java#28::wrap|||com/google/gwt/core/client/impl/SchedulerImpl.java#167::runScheduledTasks|||com/google/gwt/core/client/impl/SchedulerImpl.java#338::flushPostEventPumpCommands|||com/google/gwt/core/client/impl/SchedulerImpl.java#76::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#244::apply|||com/google/gwt/core/client/impl/Impl.java#283::entry0|||#-1::anonymous|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Windows NT 6.2  WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1
````

**Comment by gtritchie** [comment] 2018-07-11 22:30
I still see issues even with Qt 5.11.1, at least on VMWare Fusion. Using 1.2.815, launched, then put the Windows-10 VM to sleep. On restore, the RStudio window ghosted when I tried to interact with it and ultimately had to be killed with task manager. I also had Chrome and notepad running, they were fine after the restore.

**Comment by gtritchie** [comment] 2018-07-12 00:35
I have not been able to reproduce yet on a Windows-10 laptop using 1.2.818. Able to put to sleep, and wake up, etc., and RStudio remains responsive. Now we just need to try it on every other Windows laptop in the world.

**Comment by kevinushey** [comment] 2018-07-16 17:55
I just had the RStudio front-end freeze _while using the IDE_. I was attempting to debug some internal `.rs.` R machinery.

**Comment by gtritchie** [comment] 2018-07-16 18:15
@kevinushey which platform? Not that it's good on any platform.

**Comment by kevinushey** [comment] 2018-07-16 18:22
This was on my Windows 10 VM (VMware Fusion), with hardware acceleration enabled.  Host machine is a Late 2013 MBP.

**Comment by gtritchie** [comment] 2018-07-16 18:39
I have seen hangs and rendering glitches on VMWare Fusion (10.1.2), on both my late 2015 iMac with hardware acceleration enabled (AMD Radeon R9 M390 2048 MB), and my MBP (mid 2014) with Intel Iris Pro 1536 MB / NVIDIA GeForce GT 750M. Windows-10 in all cases.

**Comment by kevinushey** [comment] 2018-07-24 23:49
FWIW I was playing with RStudio on an in-house Windows 10 laptop (Yoga Pro 2) and didn't have any trouble with RStudio freezing. Same story with my (somewhat sparsely) used home Windows desktop + RStudio v1.2.

Given that we haven't had any bug reports from daily / preview users thus far either, I think we can take this is as evidence that only VMs are affected. If that is indeed the case, then I think this issue won't need to block v1.2 release, but let's keep it live just in case any other users report trouble.

**Comment by mingwandroid** [comment] 2018-07-25 01:12
You could bundle the software gl drivers as provided by the qt project? Performance may be poor though!

**Comment by kevinushey** [comment] 2018-08-08 22:58
Confirmed that this hang goes away when we switch to software rendering, and this can now be toggled within the Advanced tab of the general preferences pane.

It is indeed an issue specific to the VMware Fusion drivers; thus far we haven't heard any reports of this specific issue from other users (although we have had reports of other various rendering issues)

**Closed by kevinushey** 2018-08-08 22:58 UTC
Labels: bug, qtwebengine, reproducible
