### ISSUE TITLE
RStudio incorrectly detects failed install of png package

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#8721] opened 2021-01-11 22:40 UTC
### System details

    RStudio Edition : Server
    RStudio Version : v1.4.1103-1 and 1.3.1093-1
    OS Version      : Ubuntu16
    R Version       : 3.3.3

### Steps to reproduce the problem
On an instance of Rstudio that does not have the dependencies to run python and libpng-dev try and install what is needed in RStudio to run the python code. 

**Note**: I saw this with an instance of ubuntu16 created via fuzzbucket.

### Describe the problem in detail
The console out put says the package 'png' successfully installed even though it did not and shows the following:
```Installing 'png' for Python/Reticulate...
Installing package into ‘/home/at/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/png_0.1-7.tar.gz'
Content type 'application/x-gzip' length 24990 bytes (24 KB)
==================================================
downloaded 24 KB

gcc -I/opt/R/3.3.3/lib/R/include -DNDEBUG  -I/usr/local/include    `libpng-config --cflags` -fpic  -g -O2  -c read.c -o read.o
* installing *source* package ‘png’ ...
** package ‘png’ successfully unpacked and MD5 sums checked
** libs
/bin/bash: libpng-config: command not found
/opt/R/3.3.3/lib/R/etc/Makeconf:132: recipe for target 'read.o' failed
read.c:3:17: fatal error: png.h: No such file or directory
compilation terminated.
make: *** [read.o] Error 1
ERROR: compilation failed for package ‘png’
* removing ‘/home/at/R/x86_64-pc-linux-gnu-library/3.3/png’

The downloaded source packages are in
	‘/tmp/RtmpPp4MAs/downloaded_packages’


✔ Package 'png' successfully installed.
Warning message:
In utils::install.packages("png", repos = "https://cran.rstudio.com/") :
  installation of package ‘png’ had non-zero exit status
```

### Describe the behavior you expected
I would expect RStudio not to tell me it was successfully installed and would be helpful if it let me know I needed libpng-dev installed on the system before I can install the things I needed from the app.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MariaSemple** [comment] 2021-01-11 23:18
This is output directly from R, I believe. Can you check if you get the same output from running `install.packages("png")` from an R console launched from the terminal?

**Comment by astayleraz** [comment] 2021-01-12 16:56
I did not see "Package 'png' successfully installed." when I ran install.packages("png") from an R console.

**Comment by MariaSemple** [comment] 2021-01-12 19:46
I reproduced this (by accident) with the `r2d3` package (which attempted to be installed when I tried to create an `r2d3` file). The background job shows as succeeded despite the package installation failing. It does not appear to be specific to the `png` lib.

**Comment by valerie-rstudio** [comment] 2021-01-13 18:10
Also experiencing this issue on:
RStudio Edition : Server
RStudio Version : 1.4.1103-1
OS Version      :  RHEL 7.8
R Version       :  4.0.2

**Comment by kevinushey** [comment] 2021-01-13 19:09
Note that the resolution for this issue is to install the `libpng` package; e.g. on a Debian system:

```
sudo apt install libpng-dev
```

and this would normally have been installed for you via:

```
sudo apt install r-base-dev
```

I suspect the QA images are being provisioned in a way that leaves them without many of the requisite system libraries used by R packages.

**Comment by jmcphers** [comment] 2021-01-13 20:03
> the requisite system libraries used by R packages.

FYI for QA, there's a database of these here: https://github.com/r-hub/sysreqsdb

**Comment by ronblum** [comment] 2021-01-13 21:49
The problem isn't the failure to install; it's that the log states that the installation was successful even when it fails.

This is a duplicate of #7259.

**Closed by ronblum** 2021-01-13 21:49 UTC
Labels: bug, jobs, r packages
