### ISSUE TITLE
RStudio v1.2 makes classic multiple window loops on Windows

### ISSUE THREAD

**Issue by Nelson-Gon** [rstudio/rstudio#4738] opened 2019-05-01 20:27 UTC
Just upgraded to version 1.2 on Windows but it has a couple of problems:
1. I can't change the theme as the window forms a loop.
2. RStudio occupies the entire screen making it hard to find many options e.g the apply button isn't visible to enable modification of settings.
3. Maybe it's the new design but the logo on the toolbar is now light blue instead of the darker(and nicer) dark blue.

Image:
<img width="802" alt="rstudio pic" src="https://user-images.githubusercontent.com/42792514/57040733-e5ec3b80-6c92-11e9-8fa1-8c312ca54ab3.PNG">

Full screen view:
<img width="956" alt="full screen" src="https://user-images.githubusercontent.com/42792514/57040794-16cc7080-6c93-11e9-8909-321e56ad53da.PNG">

**Comment by ronblum** [comment] 2019-05-13 15:00
@Nelson-Gon I'm unable to reproduce the problem on Windows 10. Can you provide the environment information, including which version of Windows you're using? Thanks!

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by Nelson-Gon** [comment] 2019-05-14 05:04
Sorry for not including details. I reverted to an earlier RStudio Version but downloaded 1.2.1335 and the looping issues seems to have gone. However, the scaling issue is still relevant as I cannot change the theme since I cannot access the apply button. Below are my system details:

```
 R.Version: [1] "R version 3.5.3 RC (2019-03-04 r76216)"  [1] "Great Truth"

RStudio. Version:  [1] ‘1.2.1335

RStudio Edition: Desktop

OS Version: Windows 10 1803

```

What I'm currently seeing:

<img width="959" alt="rstudio scaling" src="https://user-images.githubusercontent.com/42792514/57671973-9f122480-7648-11e9-9d67-1902546d59ec.PNG">

**Comment by ronblum** [comment] 2019-05-14 14:08
@Nelson-Gon Good to hear that the looping Windows is gone—though still concerning that it appeared in the first place; were you using the preview version (1.2.1511), or did you redownload/reinstall 1.2.1335?

Regarding the hidden buttons: I can reproduce the issue if I increase the zoom level of the application. A few things:
1) Even though you can't see the OK button, pressing <kbd>Return</kbd> should update RStudio with your changes and make the window go away.
2) Do you have the application zoomed in? In two ways
    - In the Global Options window, choose Appearance. What does Zoom say, and what happens if you decrease it?
    - Also, is the application zoomed in? What happens if you change it with <kbd>Ctrl</kbd><kbd>-</kbd>, <kbd>Ctrl</kbd><kbd>0</kbd>, and <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>+</kbd>?

I recognize that you might intentionally be increasing the zoom level—I do that for most applications on my Windows laptop, such as to read Gmail or visit most websites.

Regarding the icon: Yes, the flat, light blue circle is our new icon, replacing the darker blue, marble-like image.

**Comment by ronblum** [comment] 2019-05-14 14:37
Not certain, but this might be a duplicate of #1605.

**Comment by Nelson-Gon** [comment] 2019-05-15 01:26
Thank You, I naively thought the default would be a display that "automatically" scales as per the system defaults. As for the previous looping issue, I had simply downloaded and reinstalled RStudio 1.2.3335 in both cases. Hopefully I'll get used to the new icon soon, loved the darker colour. Will close this now.

**Closed** 2019-05-15 01:30 UTC
Labels: bug, repro needed
