### ISSUE TITLE
Certain structure of Rmd file blocks chunk widgets 

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#8495] opened 2020-11-30 21:53 UTC
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.1066
    OS Version      : Windows 10
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Create a new empty Rmd document.
2. Paste the code that you find below (without leading spaces). Required conditions:
    a. Create header as in row 2.
    b. The header should be above the chunk.
    c. The first line in the code chunk should be "R" comment, which defines a section (i.e., ends in `------`)  as in row 5.
3. Try to run the code in the chunk by clicking on the arrow widget as shonw in the gif.

![rs-bug--rmd-do-not-run-chunk](https://user-images.githubusercontent.com/12725868/100668889-45c23100-3365-11eb-8aa6-6dd6e265c397.gif)

The code:

```
    # Section 1
    
    ```{r}
    # Comment ----------
    print("The code was evaluated")
    ```
```


### Describe the problem in detail

The widget to run the code does not work if these conditions are present.

### Describe the behavior you expected

I expect code to run as usual when the arrow is clicked:
![rs-bug--rmd-do-not-run-chunk-OK](https://user-images.githubusercontent.com/12725868/100670813-19f47a80-3368-11eb-84ee-992bb9b1841b.gif)


- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by GegznaV** [comment] 2020-11-30 22:02
One more interesting combination:
![rs-bug--rmd-do-not-run-chunk-2](https://user-images.githubusercontent.com/12725868/100670897-385a7600-3368-11eb-8746-3ceb4c6aa4a3.gif)

The output loads but newer gets fully loaded: I waited for 5 minutes and the rprocess did not finish.

**Comment by ronblum** [comment] 2020-12-01 16:30
Thanks @GegznaV for the bug report! I can reproduce the problem in RStudio Desktop 1.4.1063 on both Windows 10 and MacOS 11.1 , and in RStudio Server 1.4.1032 on Red Hat 8.3. We'll review this as part of our ongoing development of RStudio. 

Note: This is a regression, as it works in RStudio Desktop 1.3.1093.

**Comment by kevinushey** [comment] 2020-12-01 18:41
Looks like this is likely fallout from https://github.com/rstudio/rstudio/commit/f67dfaf70ec3acaa182435d9bc8345766f673992. The R section chunk is unexpectedly closing the scope of the R Markdown chunk early, which is causing us to mis-compute the chunk boundaries.

I will take a look!

**Closed** 2020-12-01 19:19 UTC
Labels: bug, r markdown, regression

**Comment by GegznaV** [comment] 2020-12-01 23:18
I can confirm, that in RStudio 1.4.1071 the issue was solved.

**Comment by kevinushey** [comment] 2020-12-01 23:58
Awesome, I'm glad to hear it! Thanks for taking the time to report the issue and also test + report back.

**Comment by kfeinauer** [comment] 2020-12-02 15:47
Community verified.
