### ISSUE TITLE
When I close a project, its objects stay in the global environment

### ISSUE THREAD

**Issue by arencambre** [rstudio/rstudio#8683] opened 2021-01-05 18:25 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1100
    OS Version      : Windows 10 20H2
    R Version       : R 4.0.3

### Steps to reproduce the problem
1. Open a project.
2. Run an R script that creates objects in the global environment.
3. Close the project.

https://user-images.githubusercontent.com/411495/103684370-12b92180-4f51-11eb-956b-7c0abda1b7d5.mp4

### Describe the problem in detail
The objects created in the global environment when the project was loaded stay loaded after you close the project.

### Describe the behavior you expected
All global-environment objects created when a project is open are no longer present when the project is closed.

Also, related: if you watch the example video, RStudio was open but not with a project loaded. It had objects in the global environment in that state. After I opened the project, ran an Rmd, then closed that project, the original objects were gone, obliterated by the leftovers from the project.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2021-01-05 18:31
I believe this occurs because, even after the project is closed, the same working directory for that project is used for the newly-launched R session.

**Comment by arencambre** [comment] 2021-01-05 18:33
That appears correct, just now verified with `getwd()`. Is that the expected behavior? Seems like the working directory should revert to the prior one in this case?

**Comment by kevinushey** [comment] 2021-01-05 18:35
I think you're right. What do you see in Tools -> Global Options? There should be a setting for the default working directory:

<img width="601" alt="Screen Shot 2021-01-05 at 10 34 22 AM" src="https://user-images.githubusercontent.com/1976582/103685155-9539e500-4f41-11eb-9773-b6702a7496f8.png">

In my case, it was set to a recently-used project folder; I suspect something similar happened to you with your project as well. (I never explicitly set it to use this project folder so that feels something like a bug / regression)

**Comment by arencambre** [comment] 2021-01-05 18:38
Aha, it is pointing to the folder of that project I opened.

Somehow it may be getting changed without my consent. While it's hard to prove a negative, I have no memory of changing that setting, plus can't think of why I would have ever had a need to.

**Comment by arencambre** [comment] 2021-01-05 18:39
Confirming that setting the default working directory to `~` resolved this. Still, do not know how that changed.

**Comment by jmcphers** [comment] 2021-01-14 20:20
I think the bug here is probably that the the "default working dir" in the preferences dialog isn't getting the right initial value. 

https://github.com/rstudio/rstudio/blob/ddcd7191ec89c4da00e77afae7e9f27e61e87c36/src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java#L129-L139

**Comment by jmcphers** [comment] 2021-01-19 22:44
> Somehow it may be getting changed without my consent. While it's hard to prove a negative, I have no memory of changing that setting, plus can't think of why I would have ever had a need to.

I think I figured out what's going on. This appears to be fallout from https://github.com/rstudio/rstudio/commit/4cc863704bd5ebd6d2394726b1785c841f30820b. Here's a simpler repro:

1. Close all running instances of RStudio
2. Remove your `initial_working_directory` preference (or delete your whole prefs file)
3. Start RStudio and open a project
4. Open Global Options. Note that the "default working directory" setting reflects your project path.
5. Do not make any prefs changes, and click OK.
6. Close the project and open a different one.
7. Open Global Options again. Note that the "default working directory" setting is still set to the first project's path.

The pref value gets stuck to whatever the current session directory is the first time you edit your RStudio options.

**Comment by jmcphers** [comment] 2021-01-29 22:39
@kevinushey I think we should consider fixing this for Tiger Daylily since it's a regression and a number of other users have noticed the incorrect behavior as well.

See: https://github.com/rstudio/rstudio/issues/6979#issuecomment-756648638

**Comment by kevinushey** [comment] 2021-01-30 00:04
More specifically, this is fallout from https://github.com/rstudio/rstudio/commit/d199e1666102f49f21a56cefedff1a8848f85e76#diff-9672b7e11cf70103e8175c75d6d45e8874d67393bf2bf922e6debbfbb6bbbcd0R419.

**Comment by R-Hannibal** [comment] 2021-02-12 21:08
Verified Fixed on: RStudio Version - 1.4.1106-4, R Version - 3.6.3, Windows 10 - Desktop 

Tested that opening a project with no `rstudio-prefs.json` file present no longer sets Global Options > General > Basic > Default working directory to the location of the project (this was occurring in 1.4.1103, which caused Default working directory to be a set to that first project, even when opening subsequent projects). 

The Default working directory now defaults to '~' and remains that until the user changes the setting.

**Closed by R-Hannibal** 2021-02-12 21:08 UTC
Labels: bug, regression, test
