### ISSUE TITLE
Clicking on console doesn't focus it when "Limit visible console output" is on

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8740] opened 2021-01-14 19:25 UTC
### System details

    RStudio Edition : Either
    RStudio Version : 1.4-juliet-rose

### Steps to reproduce the problem

1. Ensure that the *Limit visible console output* setting is on.
2. Run `sessionInfo()` a few times to fill the console with output.
3. Click in the Source pane.
4. Click on the text in the Console pane (not on the line containing the prompt)

### Describe the problem in detail

Nothing happens. 

### Describe the behavior you expected

Clicking on the Console should cause the console to gain focus, so that you can start typing in at the prompt. This is the behavior when *Limit visible console output* is turned off.

**Comment by adamconroy** [comment] 2021-01-14 19:31
Interesting. Is this on Desktop? I recently turned off the code that forced focus when you clicked on the console (with the option turned on) and the functionality still felt correct...in server. I'm guessing this is a Qt limitation.

**Comment by jmcphers** [comment] 2021-01-14 19:59
No. It repros on Server.

**Comment by R-Hannibal** [comment] 2021-02-04 22:35
@adamconroy - Do we know if this issue is a regression from 1.4 Wax Begonia functionality? I'm assuming it is as I am unable to reproduce the reported behavior on 1.4.1103 builds (the other answer would be I am missing a key part of the reproduction...definitely possible).

I'm gonna go ahead and close this issue based on what I'm seeing, but please let me know if this issue WAS present in Wax Begonia as that will mean I need to re-test and figure out what I'm doing wrong on the repro 👍.

**Comment by R-Hannibal** [comment] 2021-02-04 22:45
Verified Fixed on: RStudio Version - 1.4.1547, R Version - 3.6.3, Windows 10 - Desktop 

Clicking into the console pane (text, latest button, prompt) with "Limit visible console output enabled" returns focus to the console and allows the user to immediately start typing into the prompt line.

Did some additional testing around Clear console (Ctrl + L) but was unable to detect any negative impacts caused by this change.

**Closed by R-Hannibal** 2021-02-04 22:45 UTC
Labels: bug, console, test
