### ISSUE TITLE
Save / Save As greyed out

### ISSUE THREAD

**Issue by HanOostdijk** [rstudio/rstudio#6475] opened 2020-03-15 17:20 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.904
    OS Version      : Windows 10 x64 (build 18363)
    R Version       : 3.6.0 (2019-04-26)

Problem could be the same as [5722](https://github.com/rstudio/rstudio/issues/5722).
The status of that is [repro needed]. This could mean (??) that you need another person to reproduce it. Then here it is.

### Steps to reproduce the problem
In my case it is enough to show a data.frame in a separate window. See detail description.

### Describe the problem in detail

- Start RStudio
- No edit panel is open and therefore open an edit panel via menu: `File|New File|R Script`
- Enter the line `df = tibble::tibble(x=1:5,y=1:5)`
- Execute the line with the `source` button.
- I see `source('~/.active-rstudio-document')` in the console panel and `df` is created and visible in the `data` section of the `Environment panel`
- display `df` via the button in the `data` section.
- if I set focus on the edit panel and click on the `File` menu I see the following options
![image](https://user-images.githubusercontent.com/13506389/76706431-afbb7d00-66e7-11ea-8ace-ae5c5e821495.png)
- in other words: no problems with save and saveas
- when I set focus on the panel where `df` is played and click the `show in new window` button, the data.frame is show in a separate panel as expected
- if I set focus again on the edit panel and click on the `File` menu I see the following options
![image](https://user-images.githubusercontent.com/13506389/76706542-7b948c00-66e8-11ea-95d3-1a3d0912f20a.png)
- in other words: the save options are no longer available
- closing the separate panel makes no difference: the save options are still not available
  
### Describe the behavior you expected
Also in the case of the existence of a separate window to view a data.frame I expect that I can 'saveas' code in an edit window when that window has focus.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
** daily build version **
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-03-16 19:03
Thanks for the reproducible example! I can reproduce this now on Windows and Linux with RStudio Desktop.

**Comment by adamconroy** [comment] 2020-03-26 20:33
@melissa-barca Dug into this a bit and it appears to be directly related to the mechanics of `popoutDoc` and not due to `Source.java`'s handling of the commands . I'm wondering if the work that you're doing now will totally rework all of this functionality and that this issue will be fully obviated as a consequence of that, in which case it wouldn't be worth going much deeper here.

**Comment by melissa-barca** [comment] 2020-03-27 00:39
Hi @adamconroy I'm still working on the design, but I should be able to give you an answer in a week or so.

**Comment by adamconroy** [comment] 2020-03-27 02:00
Sounds good, no rush :) Just don't want to put work into something that might be totally removed anyway.

**Comment by melissa-barca** [comment] 2020-05-15 20:16
Hi @adamconroy I believe I am going to be reworking this functionality so you can go ahead and assign this one to me to confirm. Thanks.

**Comment by melissa-barca** [comment] 2020-07-23 22:51
To clarify my understanding, the issue being described here is that when you have a source editor in a satellite window without any editors in the main window, Save and Save As are disabled in the main window?

**Comment by HanOostdijk** [comment] 2020-07-24 12:03
Melissa,

I can't describe it more clearly than done in the first entry. 

I **do have** a file with an editor in the main window: otherwise I would not complain about not being able to "save" (?).
With editor I mean the standard editing facility in RStudio for an R source file :  no external editor.
But probably I misunderstand your question.

By the way currently I use RStudio 1.4.489 Desktop .
And another by the way: 'sometimes' the `Return to main window` button does not work.

**Comment by gtritchie** [comment] 2020-10-16 18:53
Works fine on Mac build 1.4.944 and Server build 1.4.933-1, but I can still repro 100% of the time on Windows build 1.4.945.

**Comment by kevinushey** [comment] 2020-10-21 17:31
Looks like this may not be totally fixed. After following the reproduction steps, I see that Save is active, but Save As... is not:

<img width="319" alt="Screen Shot 2020-10-21 at 10 29 22 AM" src="https://user-images.githubusercontent.com/1976582/96756091-6a031900-1388-11eb-9fd1-d5862e6e6777.png">

Compare with a regular R script which has some changes which can be saved:

<img width="330" alt="Screen Shot 2020-10-21 at 10 30 36 AM" src="https://user-images.githubusercontent.com/1976582/96756146-8010d980-1388-11eb-9c33-7c6955709419.png">

Note that:

- 'Save As...' is not greyed out;
- The 'Rename' command is enabled + visible;
- The 'Save with Encoding...' command is enabled + visible.

**Comment by kevinushey** [comment] 2020-10-30 19:12
I'm going to take a look and see if I can learn more.

**Comment by kevinushey** [comment] 2020-10-30 19:57
Short summary of primary issue:

1. Create a new, empty R document,
2. Execute `View(mtcars)`,
3. Pop out the data viewer to a separate window,
4. Return focus to the main window.

Once focus has returned to the original R source document, the Save commands will remain grayed out.

**Closed** 2020-10-30 21:57 UTC
Labels: backlog, bug, reproducible

**Comment by rich-rstudio** [comment] 2020-11-02 18:10
verified on Win 10 Desktop and MacOS desktop 1.4.997
