### ISSUE TITLE
Chunks can't be queued if they don't have output from a previous run

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4238] opened 2019-01-29 17:18 UTC
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.1256
    OS Version      : Cross-platform
    R Version       : 3.5.2

### Steps to reproduce the problem

1. Create an R Notebook or R Markdown file with multiple chunks:
````
```{r first_chunk}
print(1)
Sys.sleep(5)
```

```{r second_chunk}
print(2)
Sys.sleep(5)
```
````
2. Make sure all output is cleared.
3. Click on the green arrow to run first_chunk.
4. While first_chunk is running, click on the green arrow for second_chunk.
    - Nothing happens with second_chunk.
5. After first_chunk is done running, run second_chunk.
    - second_chunk now runs and output appears.
6. Rerun first_chunk.
7. While first_chunk is running, click on the green arrow for second_chunk.
    - The green arrow should turn into the "queued" clock icon.
    - After first_chunk completes, second_chunk should run and produce output.
8. Clear the output for second_chunk.
9. Rerun first_chunk.
10. While first_chunk is running, click on the green arrow for second_chunk.
    - Nothing happens with second_chunk.

### Describe the problem in detail

Chunks can only be queued if they've already been run and the output is still available. If a chunk has not run, or it has run but the output was cleared, it cannot be queued.

### Describe the behavior you expected

Chunks should be queueable even if they haven't already run.

Note: this is nota regression, as 1.1.463 has the same behavior.

**Comment by MaxKman** [comment] 2019-07-03 13:45
Has this bug been addressed in the meantime? I still encounter the same problem in Version 1.2.1335 on MacOS.

Thanks
Max

**Comment by ronblum** [comment] 2019-07-03 14:35
@MaxKman No, unfortunately it hasn't been addressed yet—it didn't make the cut for the upcoming release, [currently in preview](https://www.rstudio.com/products/rstudio/download/preview/). However, as part of reviewing bugs, we not only take into account severity and effort, but also impact, which we measure in part by the number of people who express interest with thumbs ups on the initial request (not this comment). So I recommend doing that, which will give it a leg up!

**Comment by MaxKman** [comment] 2019-07-03 15:03
Done. Thanks for pointing this out. Hope this gets fixed soon since the scheduling is super useful when it works properly!

**Comment by Nico-Rojas** [comment] 2019-09-04 19:30
This has not been fixed right? Same issue here. Thank @ronblum for posting this.

**Comment by ronblum** [comment] 2019-09-05 15:08
@Nico-Rojas No, not yet. But we'll keep it for reviewing as a bug to fix—but I can't provide a timeline for it, unfortunately. However, the thumbs up—like the one you clicked on—help us determine which bugs are the highest priority.

**Comment by Nico-Rojas** [comment] 2019-09-05 15:52
@ronblum , that makes sense. I always feel grateful for having access to rstudio. Good luck working in all the bugs. Thank you for the answer.

**Comment by jmcphers** [comment] 2021-02-02 18:30
I'm moving this to Juliet Rose since I know what the problem is, this is widely reported, and there are internal reports of this issue causing confusion in the new visual editor.

**Comment by valerie-rstudio** [comment] 2021-02-04 21:20
### Verified Fixed

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1546 & 1.4.1546-1
    OS Version      : mac OS 11.1 & centos8
    R Version       : 4.0.3

Verified that chunks can be queued even if they have never before been run. Tested in both R Notebook and R Markdown on source and visual mode.

**Closed by valerie-rstudio** 2021-02-04 21:20 UTC
Labels: bug, notebooks, test
