### ISSUE TITLE
Undo not working in Markdown editor

### ISSUE THREAD

**Issue by arnyeinstein** [rstudio/rstudio#7960] opened 2020-10-05 09:31 UTC
### System details

    RStudio Edition: Desktip 
    RStudio Version : 1.4.869
    OS Version      : Windows 10
    R Version       : 4.0.0

### Steps to reproduce the problem
RMarkdown file in Markdown editor: try to undo stuff does not work
### Describe the problem in detail
Ctr-Z is not working to undo stuff in the Markdown editor
### Describe the behavior you expected
Undo

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Cheers
Renger

**Comment by jmcphers** [comment] 2020-10-05 16:59
I'm not able to reproduce this in RStudio's daily build -- do you see the problem there?

https://dailies.rstudio.com/

**Comment by cderv** [comment] 2020-10-05 18:09
I am also on Windows 10 with 1.4.900 and I can't use CTRL+Z either. However, Undo menu button works. 

This has been the case since some dailies now. First reported there (see comments): https://github.com/rstudio/rstudio/issues/7588

**Comment by kevinushey** [comment] 2020-10-05 22:42
Is it possible that this issue depends on the keyboard layout being used, or something similar?

**Comment by arnyeinstein** [comment] 2020-10-09 08:23
I tried to assign a different key combination, but that did not solve the problem. I have a Swissgerman keyboard. I noticed also that if I want to try to change the key combination to e.g. Ctrl+$, in RStudio it shows Ctr+\ (which is probably the English keyboard). I don't know if this is another issue.

**Comment by cderv** [comment] 2020-10-09 08:52
Still happening with 1.4.916

On my side I have a French keyboard (AZERTY)

Assigning a new shortcut to Undo works in the source editor but does not work either in the visual editor.

**Comment by kevinushey** [comment] 2020-10-09 16:33
I can reproduce as well if I activate an AZERTY keyboard layout.

**Comment by kevinushey** [comment] 2020-10-09 16:44
Also worth noting that Undo works fine within Ace editor instances; it's in Markdown / other prosemirror contexts where it does not.

I can also reproduce the issue using one of the Qt example browsers with the demo instance at https://prosemirror.net/, which hints that this is most likely a Webengine issue. 😞

**Comment by kevinushey** [comment] 2020-10-09 16:53
Logging `keydown` events...

## Chrome

<img width="939" alt="Screen Shot 2020-10-09 at 9 48 12 AM" src="https://user-images.githubusercontent.com/1976582/95610044-8ca24300-0a14-11eb-8c4e-065426824512.png">

## WebEngine

<img width="939" alt="Screen Shot 2020-10-09 at 9 49 28 AM" src="https://user-images.githubusercontent.com/1976582/95610176-ba878780-0a14-11eb-9cdd-7ab1ae22da8a.png">

Note that the `key` property is corrupt with QtWebEngine -- possibly related? Although I wonder why other <kbd>Ctrl</kbd>-prefixed commands (e.g. <kbd>Ctrl + B</kbd> for bold) work, while this particular command does not.

**Comment by R-Hannibal** [comment] 2020-10-09 19:36
I'm also able to repro this when I switch over to my French AZERTY keyboard (RDP, RStudio version: 1.4.904-1). Undo `Ctrl + z` works fine in a regular markdown document, switching over to visual mode it ceases to function.

**Comment by jmcphers** [comment] 2020-10-09 19:40
Note that we are probably going to be updating QtWebEngine in order to address https://github.com/rstudio/rstudio/issues/7897 (@gtritchie  is working on building experimental packages). As @kevinushey has discovered this appears to be another WebEngine issue, so we might hold this for a couple of days in hopes it's addressed with the new engine.

**Comment by kevinushey** [comment] 2020-11-05 17:16
Re-opening as @cderv reported that Ctrl + Y is busted as well. 😭

**Comment by cderv** [comment] 2020-11-05 17:53
I know what it has not bugged me more. I got used to it not working because CTRL+Y for Redo does not work in RStudio 1.3 either for me. It was not new to 1.4 as Undo with CTRL+Z, which I used much more often. (I just tried it in 1.3)

But... looking at https://github.com/rstudio/rstudio/issues/5595 it seems CTRL+SHIFT+Z is the keybinding for Redo, and not CTRL+Y. Tried it just now and work in 1.3 and 1.4. 

Is it just a matter of label as https://github.com/rstudio/rstudio/issues/5595 is showing (Edit menu indeed show CTRL+Y)

I checked in Keyboard shortcut menu and oddly I got two... That would explain CTRL+Y not working.
![image](https://user-images.githubusercontent.com/6791940/98277729-f6702700-1f97-11eb-86ce-2273dd1ab291.png)
it seem it is used for another thing... 
![image](https://user-images.githubusercontent.com/6791940/98277679-eb1cfb80-1f97-11eb-8a67-b8a39f07561f.png)

So CTRL+Y is working after all but not as we are used to on windows with undo / redo. 

So real follow up issue is https://github.com/rstudio/rstudio/issues/5595 - you can close @kevinushey

**Comment by kevinushey** [comment] 2020-11-05 18:22
Roger that. Thanks!

**Closed by kevinushey** 2020-11-05 18:22 UTC
Labels: bug, keyboard shortcuts, qtwebengine, visual markdown editing

**Comment by adamconroy** [comment] 2020-11-17 18:42
verified in 1.4.1038 (that it's not a thing, the labels in the shortcut window are definitely confusing though)
