### ISSUE TITLE
Console output folds across rows making output illegible

### ISSUE THREAD

**Issue by mvuorre** [rstudio/rstudio#8696] opened 2021-01-07 11:19 UTC
### System details

    RStudio Edition : RStudio Server
    RStudio Version : 1.4.1103
    OS Version      : Ubuntu 20.04 (through Windows Subsystem for Linux)
    R Version       : 4.0.3

### Steps to reproduce the problem

In a fresh RStudio server session (using it through Firefox, but same happens on Chrome; server is hosted on WSL2 Ubuntu, and I am accessing it on the same machine on Windows 10):

<img width="399" alt="Screenshot 2021-01-07 110837" src="https://user-images.githubusercontent.com/7349270/103886000-c0a30800-50d8-11eb-994d-9a0700cdb338.png">

### Describe the problem in detail

Output in the console folds across rows in a way that garbles the output, making it difficult to read. I also described this on the community forum: <https://community.rstudio.com/t/rstudio-server-console-width-problem/89733>. I've tried several different fonts, but this happens on every font I've tried so far. I've also adjusted the width of the entire window and the console, and sometimes the problem disappears for a while but comes back quickly. I haven't found a pattern to that.

### Describe the behavior you expected

I would expect the console output to not fold across lines in any situation.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-01-07 14:42
Copying sample code from Community thread:

```
library(tidyverse)
tibble(bind_cols(mtcars, mtcars))
```

**Comment by rickyking** [comment] 2021-01-07 15:25
I am getting the same issue. I like the function of choosing a new font. Especially with Firas Code, I am able to do the ligature. 

When I switch the font back to `default` problem disappeared.

**Comment by jmcphers** [comment] 2021-01-07 18:32
RStudio is supposed to tell R how many characters wide the console is so that it formats its output correctly. This calculation is probably not happening correctly. This is one of the client metrics and is ultimately forwarded to the `width` option. 

https://github.com/rstudio/rstudio/blob/ddcd7191ec89c4da00e77afae7e9f27e61e87c36/src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java#L249

https://github.com/rstudio/rstudio/blob/ddcd7191ec89c4da00e77afae7e9f27e61e87c36/src/cpp/r/session/RClientMetrics.cpp#L58-L59

**Comment by jmcphers** [comment] 2021-01-07 18:35
@mvuorre  @rickyking What does this return for you?

    Sys.getenv("RSTUDIO_CONSOLE_WIDTH")

And, does reducing the width help? For example...

    options(width = 60)

**Comment by rickyking** [comment] 2021-01-07 18:51
@jmcphers 

Hi,

```
Sys.getenv("RSTUDIO_CONSOLE_WIDTH")
```

This gets 148 for me. But I think it changes according to the size of the console. 

Yes reducing width helps but after resize the console, it's has been overwritten.

**Comment by mvuorre** [comment] 2021-01-08 09:31
Hi @jmcphers ,

```
> Sys.getenv("RSTUDIO_CONSOLE_WIDTH")
[1] "85"
```

But that of course changes when I resize the window/panel.

I have the same behavior as @rickyking, that is I can make the problem go away by manually adjusting e.g. `options(width = 70)`, but if I resize the window or console panel, the problem reappears. When I query for `options()$width`, it looks like RStudio is setting it a bit too wide after resizing window/panel.

**Comment by jmcphers** [comment] 2021-01-08 17:42
> it looks like RStudio is setting it a bit too wide after resizing window/panel.

Yes, I believe you've hit the crux of the problem!

As RStudio queries the browser to calculate the width, it's possible this is browser specific. Which browser are you using to access RStudio Server? Does using a different browser change the behavior?

**Comment by kevinushey** [comment] 2021-01-08 18:22
I've seen similar issues with testthat output: the rendered text overflows because the width of each rendered character is actually a bit larger than the "typical" width of a regular monospace character.

I'm not positive the same thing is happening here (especially because as far as I can tell there are no special ligatures / multibyte characters) but if changing the font resolves the issue then it well could be.

**Comment by jmcphers** [comment] 2021-01-08 18:25
> I've seen similar issues with testthat output

That makes since since the Build pane uses exactly the same mechanism to set its width:

https://github.com/rstudio/rstudio/blob/ddcd7191ec89c4da00e77afae7e9f27e61e87c36/src/cpp/r/session/RClientMetrics.cpp#L60-L61

**Comment by mvuorre** [comment] 2021-01-09 15:49
> As RStudio queries the browser to calculate the width, it's possible this is browser specific. Which browser are you using to access RStudio Server? Does using a different browser change the behavior?

This happens on both Firefox and Chrome.

**Comment by rickyking** [comment] 2021-01-09 15:53
Y'a both chrome Firefox and safari

**Comment by rickyking** [comment] 2021-01-25 01:13
Is this issue fixed on the new release?

**Comment by kevinushey** [comment] 2021-01-25 18:30
No, it is not.

**Comment by mvuorre** [comment] 2021-01-26 15:50
Just adding that I am also encountering this on the desktop R Studio (Version 1.4.1103; Mac OS big sur 11.1). I have tried Fira Code and Monaco fonts, and it happens on both.

**Comment by ronblum** [comment] 2021-07-28 12:20
Unstaling and tagging for review as this affects multiple users.

**Comment by kevinushey** [comment] 2021-07-28 19:21
I can reproduce on Windows using Chrome to connect to a local development server as well. This is where we compute the character width:

https://github.com/rstudio/rstudio/blob/a4b25170ae0fee3f6a40a730d6d7c3b1383f4c08/src/gwt/src/org/rstudio/core/client/dom/DomUtils.java#L1114-L1150

I wonder if the issue is that we're not applying the active desktop font to the label generated for measuring the font width? The default font (Consolas?) is a bit narrow compared to other common monospace fonts.

FWIW, I don't see the issue when using the default editor font (Consolas) but do see it with a variety of others (Courier New,  Droid Sans Mono)

**Comment by kevinushey** [comment] 2021-07-28 20:09
Here's how Windows fonts get applied here:

<img width="334" alt="Screen Shot 2021-07-28 at 1 02 19 PM" src="https://user-images.githubusercontent.com/1976582/127388243-df49ca8c-57d5-4d24-ba03-e98af5194195.png">

But here's the font + style set on the Label element we're creating + testing:

<img width="333" alt="Screen Shot 2021-07-28 at 1 03 31 PM" src="https://user-images.githubusercontent.com/1976582/127388275-31d3caf2-cc18-4f0a-bd04-93dc661f46cd.png">

The problem, I think, is that the element we're creating is a plain div and not pre. Note that we only style fonts for pre-formatted text here:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/resources/themes/css/fonts.css

**Comment by valerie-rstudio** [comment] 2021-08-13 17:00
### Verified Fixed

    RStudio Edition : Server
    RStudio Version : 2021-08.0 Build 305-3
    OS Version      : ubuntu18 (server); windows10 (client)
    R Version       : 4.0.3

Verified that the default width of the console window is wide enough to display entire tibble without word wrap. If the console window is resized by the user to be too small for the tibble, word wrap still occurs.

### Notes
- Entered the following commands to test this issue:
```
install.packages("tidyverse")
library(tidyverse)
tibble(bind_cols(mtcars, mtcars))
```

**Closed by valerie-rstudio** 2021-08-13 17:00 UTC
Labels: bug, console, test
