### ISSUE TITLE
unable to create new RScript file in RStudio

### ISSUE THREAD

**Issue by rishabh-kim** [rstudio/rstudio#5133] opened 2019-07-21 16:53 UTC
I have RStudio-1.2.1335(64-bit) and R-3.6.1 installed into my laptop
When I launch RStudio, application launches and it shows menu bar on top which has options 
like File, Edit, Code, View, etc and the rest of the body of the page is blank white.
I am unable to create or open a project or a file in RStudio.
I click on File, it gives dropdown with options like New File, New Project, Open File and other options. 
When I click on New File > RScript, it does not open the page where I would get the console, environment 
or any other tab and I end up having the blank white page with the menu bar on top. 
Also same thing happens when I try to open a new project following the similar method. 
Please suggest the steps required to fix this.

**Comment by MariaSemple** [comment] 2019-07-21 19:31
Hi @rishabh-kim, thanks for reporting this issue. What operating system are you using when this occurs?

**Comment by rishabh-kim** [comment] 2019-07-21 20:09
Hi,

I use windows 7

Regards,
Rishabh

**Comment by ronblum** [comment] 2019-07-22 16:19
@rishabh-kim and @MariaSemple I tried out the same profile–RStudio Desktop 1.2.1335 on Windows 7, but I wasn't able to reproduce the issue—I was able to successfully create an R script and new project.

**Comment by rishabh-kim** [comment] 2019-07-22 19:34
@RonBlum and @MariaSemple Is there any configuration that needs to be done
other than choosing the default options while installing and setting up
rstudio/r or if any specific directory/folder path is to be used while
setting up or post setup?

**Comment by ronblum** [comment] 2019-09-16 14:39
@rishabh-kim Is this still an issue with [the latest RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/)? (Note that preview builds are intended for testing purposes only.)

**Comment by rishabh-kim** [comment] 2019-09-16 20:10
Hi Ron,

I bought a new laptop and I am able to run rstudio, 64-bit version in this
one which I was not able to use in my previous laptop giving me issues
which I have described in previous messages. The issue could have been with
my laptop and not the software. Earlier I had a Dell Inspiron laptop
which had an i3 processor. Now I have Lenovo Legion which has an i5
processor.

Regards,
Rishabh

**Comment by ronblum** [comment] 2019-09-16 20:14
@rishabh-kim Thank you for the update, and I'm glad it's working! Hopefully the issue was with the previous laptop, and not RStudio, per se. I'll close the issue, but if you or anyone else runs into it, it'll still show up in searches and can be reopened.

**Closed by ronblum** 2019-09-16 20:14 UTC
Labels: bug, repro needed

**Comment by rishabh-kim** [comment] 2019-09-16 20:37
okay thank you Ron.
