### ISSUE TITLE
Global options not in expected location on macOS

### ISSUE THREAD

**Issue by cbrnr** [rstudio/rstudio#14120] opened 2024-01-12 06:57 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0+369 
    OS Version      : macOS Sonoma 14.2.1
    R Version       : 4.3.2

### Steps to reproduce the problem

Applications on macOS make their options (settings/preferences) available in their application menu (which is named after the application). This means that people will go looking for the settings in the RStudio menu, but this menu does not contain an options entry:

![Screenshot 2024-01-12 at 07 53 26](https://github.com/rstudio/rstudio/assets/4377312/f19f8492-7742-4de5-a03f-9a96916abfb9)

Instead, the "Global options" entry is located in the "Tools" menu, which is inconsistent with macOS guidelines.

### Describe the behavior you expected

I would expect the "Global options" entry to be available in the "RStudio" menu (and only in that menu, because duplicated menu entries are also confusing, which BTW is the case for the "About" dialog available in both the "RStudio" and "Help" menus).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-01-16 17:46
@cbrnr Thank you for raising this! I'm marking this as a duplicate of issue #13692, though please make a note if you think that this is incorrect.

**Closed by ronblum** 2024-01-16 17:46 UTC
Labels: bug, new
