### ISSUE TITLE
File properties aren't respected by global find and replace

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#6048] opened 2020-01-17 19:21 UTC
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.3.743 & 1.3.730
    OS Version      : MacOS 10.15.3 & Red Hat 7.8
    R Version       : 3.6.1 & 3.6.0

### Steps to reproduce the problem

1. Create a file called `mischief.R` containing just one line, `Loki`.
2. On the command line: change the file permissions to read-only and a different (real) owner and group, e.g.
```
chmod 444 mishchief.R
chown another_user mishchief.R
chgrp another_group mishchief.R
```
3. Make sure that the permissions, owner, and group have been updated correctly, e.g.
```
# ls -l mischief.R 
-r--r--r--. 1 another_user another_group 5 Jan 17 18:58 mischief.R
```
3. In the IDE: Edit -> Find in Files
4. Under "Find" type `Loki`
5. Under "Search In" choose the directory containing the file `mischief.R`
6. Click on "Find"
    - The search should display the file name and location above, with _Loki_ highlighted in the matching lines
7. Next to "Replace With" type `Trickster`
8. Replace All -> Yes
    - The search should display the file name and location above, with _Trickster_ highlighted in the matching lines
9. On the command line, check the permissions, etc., on the file
    - Write permissions have been added to the file, and the owner and group have reverted to the user and group associated with the RStudio account
```
# ls -l mischief.R 
-rw-rw-r--. 1 rstudio rstudio 5 Jan 17 18:58 mischief.R
```
10. Check the contents of the file: _Loki_ is replaced with _Trickster_
```
[root@ip-10-0-0-42 global]# cat mischief.R 
Trickster
```

### Describe the problem in detail

The file has been updated, and its permissions, owner, and group have been changed.

### Describe the behavior you expected

The existing file properties should be respected:
1. File permissions, owner, and group should not be changed.
2. The file should not be changed, as it's not supposed to be writable.

----------

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-03-06 14:59
This is still occurring on Ubuntu 18.04, but works on MacOS 10.15.4.

**Comment by melissa-barca** [comment] 2020-03-07 00:48
Hi @ronblum I did more research after our call and discovered that the discrepancies were coming from me testing using rstudio server and you testing using rstudio desktop. I discovered that when using rstudio server, the replace is being performed by the user logged in from the browser and when using rstudio desktop it's performed by root because that is the user using the app. Even though root doesn't have permission to modify the file, it still has the capability to do so because it's root.
Since this situation is unique to root, I think this is the expected behavior we'd want to see and that we can close this issue.

**Comment by jmcphers** [comment] 2020-03-09 16:50
> when using rstudio desktop it's performed by root because that is the user using the app. 

I don't think that's typical. You *can* run RStudio Desktop as root, but most of the time it's run by an ordinary unprivileged user. If that doesn't work, we need to fix it. Do you see the problem if you run RStudio Desktop using an unprivileged account?

@ronblum does this align with your experience?

**Comment by melissa-barca** [comment] 2020-03-09 16:57
Hi @jmcphers to add context, Ron and I had been testing how we were seeing discrepancies between the behavior of attempting a replace when running desktop vs server as root. On our call on Friday, we did confirm unprivileged users were not able to perform the replace in desktop and server. I will also let @ronblum confirm this.

**Comment by jmcphers** [comment] 2020-03-09 22:10
Does this explain what @robinlovelace was seeing? 

When you say "not able to perform the replace" -- is any error shown? What does it look like to the user?

**Comment by melissa-barca** [comment] 2020-03-09 22:16
@jmcphers  Yes we are displaying the system error we received from trying to open an input stream. It displays in red rather than succesful results in green. Unfortunately, I don't think this is related to @Robinlovelace's problem.

**Comment by ronblum** [comment] 2020-03-10 17:42
I rechecked using the latest build, 1.3.900. If the file isn't supposed to be writeable by the current user, it doesn't get updated. But if it's writable, then the text gets replaced as expected, but the owner, group, and permissions are updated unexpectedly.

First, using the original reprex:
1) This is no longer an issue with file permissions set to 444, which doesn't allow anyone to write to it.
2) However, if we start off with file permissions of 666 (r/w for all), then we end up back in an unexpected state: the file is correctly edited, but owner and group are changed, and the permissions are set to 664.

Second: Here are the results when running with a series of files with different owners (`vmware` and `pulse`) and permissions. This is using RStudio Desktop running with the user `vmware`. The search is for `replace_me` which is then replaced with `replaced_you`.
```
vmware@vmware-virtual-machine:~/repl_rs_desktop$ # Testing global replace with RStudio Desktop
vmware@vmware-virtual-machine:~/repl_rs_desktop$ ls -l
total 80
---------- 1 vmware vmware 40 Mar 10 09:13 file_000.txt
---x--x--x 1 vmware vmware 40 Mar 10 09:13 file_111.txt
--w--w--w- 1 vmware vmware 40 Mar 10 09:13 file_222.txt
--wx-wx-wx 1 vmware vmware 40 Mar 10 09:13 file_333.txt
-r--r--r-- 1 vmware vmware 40 Mar 10 09:13 file_444.txt
-r-xr-xr-x 1 vmware vmware 40 Mar 10 09:13 file_555.txt
-rw-r--r-- 1 vmware vmware 40 Mar 10 09:13 file_644.txt
-rw-rw-r-- 1 vmware vmware 40 Mar 10 09:13 file_664.txt
-rw-rw-rw- 1 vmware vmware 40 Mar 10 09:13 file_666.txt
-rwxrwxrwx 1 vmware vmware 40 Mar 10 09:13 file_777.txt
---------- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_000.txt
---x--x--x 1 pulse  pulse  40 Mar 10 11:58 file_pulse_111.txt
--w--w--w- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_222.txt
--wx-wx-wx 1 pulse  pulse  40 Mar 10 11:58 file_pulse_333.txt
-r--r--r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_444.txt
-r-xr-xr-x 1 pulse  pulse  40 Mar 10 11:58 file_pulse_555.txt
-rw-r--r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_644.txt
-rw-rw-r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_664.txt
-rw-rw-rw- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_666.txt
-rwxrwxrwx 1 pulse  pulse  40 Mar 10 11:58 file_pulse_777.txt
vmware@vmware-virtual-machine:~/repl_rs_desktop$ sudo grep replace *
file_000.txt:replace_me
file_111.txt:replace_me
file_222.txt:replace_me
file_333.txt:replace_me
file_444.txt:replace_me
file_555.txt:replace_me
file_644.txt:replace_me
file_664.txt:replace_me
file_666.txt:replace_me
file_777.txt:replace_me
file_pulse_000.txt:replace_me
file_pulse_111.txt:replace_me
file_pulse_222.txt:replace_me
file_pulse_333.txt:replace_me
file_pulse_444.txt:replace_me
file_pulse_555.txt:replace_me
file_pulse_644.txt:replace_me
file_pulse_664.txt:replace_me
file_pulse_666.txt:replace_me
file_pulse_777.txt:replace_me
vmware@vmware-virtual-machine:~/repl_rs_desktop$ 
vmware@vmware-virtual-machine:~/repl_rs_desktop$ # Replaced 'replace_me' with 'replaced_you'
vmware@vmware-virtual-machine:~/repl_rs_desktop$ 
vmware@vmware-virtual-machine:~/repl_rs_desktop$ ls -l
total 80
---------- 1 vmware vmware 40 Mar 10 09:13 file_000.txt
---x--x--x 1 vmware vmware 40 Mar 10 09:13 file_111.txt
--w--w--w- 1 vmware vmware 40 Mar 10 09:13 file_222.txt
--wx-wx-wx 1 vmware vmware 40 Mar 10 09:13 file_333.txt
-r--r--r-- 1 vmware vmware 40 Mar 10 09:13 file_444.txt
-r-xr-xr-x 1 vmware vmware 40 Mar 10 09:13 file_555.txt
-rw-rw-r-- 1 vmware vmware 42 Mar 10 12:12 file_644.txt
-rw-rw-r-- 1 vmware vmware 42 Mar 10 12:12 file_664.txt
-rw-rw-r-- 1 vmware vmware 42 Mar 10 12:12 file_666.txt
-rw-rw-r-- 1 vmware vmware 42 Mar 10 12:12 file_777.txt
---------- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_000.txt
---x--x--x 1 pulse  pulse  40 Mar 10 11:58 file_pulse_111.txt
--w--w--w- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_222.txt
--wx-wx-wx 1 pulse  pulse  40 Mar 10 11:58 file_pulse_333.txt
-r--r--r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_444.txt
-r-xr-xr-x 1 pulse  pulse  40 Mar 10 11:58 file_pulse_555.txt
-rw-r--r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_644.txt
-rw-rw-r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_664.txt
-rw-rw-r-- 1 vmware vmware 42 Mar 10 12:12 file_pulse_666.txt
-rw-rw-r-- 1 vmware vmware 42 Mar 10 12:12 file_pulse_777.txt
vmware@vmware-virtual-machine:~/repl_rs_desktop$ sudo grep replace *
file_000.txt:replace_me
file_111.txt:replace_me
file_222.txt:replace_me
file_333.txt:replace_me
file_444.txt:replace_me
file_555.txt:replace_me
file_644.txt:replaced_you
file_664.txt:replaced_you
file_666.txt:replaced_you
file_777.txt:replaced_you
file_pulse_000.txt:replace_me
file_pulse_111.txt:replace_me
file_pulse_222.txt:replace_me
file_pulse_333.txt:replace_me
file_pulse_444.txt:replace_me
file_pulse_555.txt:replace_me
file_pulse_644.txt:replace_me
file_pulse_664.txt:replace_me
file_pulse_666.txt:replaced_you
file_pulse_777.txt:replaced_you
vmware@vmware-virtual-machine:~/repl_rs_desktop$ 
```
Only files for which `vmware` had write access were updated. However, for all of the updated files
    - the permissions changed to 664, `-rw-rw-r--`
    - the ownership of the `pulse/pulse` files changed to to `vmware/vmware`
For example:
`-rwxrwxrwx 1 pulse  pulse  40 Mar 10 11:58 file_pulse_777.txt`
became
`-rw-rw-r-- 1 vmware vmware 42 Mar 10 12:12 file_pulse_777.txt`


- In comparison, `sed` behaves a little bit differently: it replaces the text and changes ownership for all readable files—including those without write permission—but it doesn't modify the permissions. For example, running as the user `vmware` on the file
`-r--r--r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_444.txt`
replaces the text and changes the file to 
`-r--r--r-- 1 vmware vmware 42 Mar 10 12:22 file_pulse_444.txt`
```
vmware@vmware-virtual-machine:~/repl_sed$ # Testing global replace with 'sed'
vmware@vmware-virtual-machine:~/repl_sed$ ls -l *
---------- 1 vmware vmware 40 Mar 10 09:13 file_000.txt
---x--x--x 1 vmware vmware 40 Mar 10 09:13 file_111.txt
--w--w--w- 1 vmware vmware 40 Mar 10 09:13 file_222.txt
--wx-wx-wx 1 vmware vmware 40 Mar 10 09:13 file_333.txt
-r--r--r-- 1 vmware vmware 40 Mar 10 09:13 file_444.txt
-r-xr-xr-x 1 vmware vmware 40 Mar 10 09:13 file_555.txt
-rw-r--r-- 1 vmware vmware 40 Mar 10 09:13 file_644.txt
-rw-rw-r-- 1 vmware vmware 40 Mar 10 09:13 file_664.txt
-rw-rw-rw- 1 vmware vmware 40 Mar 10 09:13 file_666.txt
-rwxrwxrwx 1 vmware vmware 40 Mar 10 09:13 file_777.txt
---------- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_000.txt
---x--x--x 1 pulse  pulse  40 Mar 10 11:58 file_pulse_111.txt
--w--w--w- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_222.txt
--wx-wx-wx 1 pulse  pulse  40 Mar 10 11:58 file_pulse_333.txt
-r--r--r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_444.txt
-r-xr-xr-x 1 pulse  pulse  40 Mar 10 11:58 file_pulse_555.txt
-rw-r--r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_644.txt
-rw-rw-r-- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_664.txt
-rw-rw-rw- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_666.txt
-rwxrwxrwx 1 pulse  pulse  40 Mar 10 11:58 file_pulse_777.txt
vmware@vmware-virtual-machine:~/repl_sed$ sudo grep replace *
file_000.txt:replace_me
file_111.txt:replace_me
file_222.txt:replace_me
file_333.txt:replace_me
file_444.txt:replace_me
file_555.txt:replace_me
file_644.txt:replace_me
file_664.txt:replace_me
file_666.txt:replace_me
file_777.txt:replace_me
file_pulse_000.txt:replace_me
file_pulse_111.txt:replace_me
file_pulse_222.txt:replace_me
file_pulse_333.txt:replace_me
file_pulse_444.txt:replace_me
file_pulse_555.txt:replace_me
file_pulse_644.txt:replace_me
file_pulse_664.txt:replace_me
file_pulse_666.txt:replace_me
file_pulse_777.txt:replace_me
vmware@vmware-virtual-machine:~/repl_sed$ sed -i 's/replace_me/replaced_you/g' *
sed: can't read file_000.txt: Permission denied
sed: can't read file_111.txt: Permission denied
sed: can't read file_222.txt: Permission denied
sed: can't read file_333.txt: Permission denied
sed: can't read file_pulse_000.txt: Permission denied
sed: can't read file_pulse_111.txt: Permission denied
sed: can't read file_pulse_222.txt: Permission denied
sed: can't read file_pulse_333.txt: Permission denied
vmware@vmware-virtual-machine:~/repl_sed$ ls -l *
---------- 1 vmware vmware 40 Mar 10 09:13 file_000.txt
---x--x--x 1 vmware vmware 40 Mar 10 09:13 file_111.txt
--w--w--w- 1 vmware vmware 40 Mar 10 09:13 file_222.txt
--wx-wx-wx 1 vmware vmware 40 Mar 10 09:13 file_333.txt
-r--r--r-- 1 vmware vmware 42 Mar 10 12:22 file_444.txt
-r-xr-xr-x 1 vmware vmware 42 Mar 10 12:22 file_555.txt
-rw-r--r-- 1 vmware vmware 42 Mar 10 12:22 file_644.txt
-rw-rw-r-- 1 vmware vmware 42 Mar 10 12:22 file_664.txt
-rw-rw-rw- 1 vmware vmware 42 Mar 10 12:22 file_666.txt
-rwxrwxrwx 1 vmware vmware 42 Mar 10 12:22 file_777.txt
---------- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_000.txt
---x--x--x 1 pulse  pulse  40 Mar 10 11:58 file_pulse_111.txt
--w--w--w- 1 pulse  pulse  40 Mar 10 11:58 file_pulse_222.txt
--wx-wx-wx 1 pulse  pulse  40 Mar 10 11:58 file_pulse_333.txt
-r--r--r-- 1 vmware vmware 42 Mar 10 12:22 file_pulse_444.txt
-r-xr-xr-x 1 vmware vmware 42 Mar 10 12:22 file_pulse_555.txt
-rw-r--r-- 1 vmware vmware 42 Mar 10 12:22 file_pulse_644.txt
-rw-rw-r-- 1 vmware vmware 42 Mar 10 12:22 file_pulse_664.txt
-rw-rw-rw- 1 vmware vmware 42 Mar 10 12:22 file_pulse_666.txt
-rwxrwxrwx 1 vmware vmware 42 Mar 10 12:22 file_pulse_777.txt
vmware@vmware-virtual-machine:~/repl_sed$ sudo grep replace *
file_000.txt:replace_me
file_111.txt:replace_me
file_222.txt:replace_me
file_333.txt:replace_me
file_444.txt:replaced_you
file_555.txt:replaced_you
file_644.txt:replaced_you
file_664.txt:replaced_you
file_666.txt:replaced_you
file_777.txt:replaced_you
file_pulse_000.txt:replace_me
file_pulse_111.txt:replace_me
file_pulse_222.txt:replace_me
file_pulse_333.txt:replace_me
file_pulse_444.txt:replaced_you
file_pulse_555.txt:replaced_you
file_pulse_644.txt:replaced_you
file_pulse_664.txt:replaced_you
file_pulse_666.txt:replaced_you
file_pulse_777.txt:replaced_you
vmware@vmware-virtual-machine:~/repl_sed$
```

- Using `vim`: only files that the user is allowed to write to get updated, and their ownership/group settings and permissions don't change. At least, when doing so file-by-file; I started testing with `:argdo ... | update`, but I wound up saving file-by-file anyway, with no `!` overrides.

These are the results using RStudio Desktop running as an individual user. If you'd like the results from  Desktop running as `root` or  in RStudio Server, let me know.

**Comment by Robinlovelace** [comment] 2020-03-10 18:00
In case it's of use and interest, permission issues seem to affect my favourite find/replace CLI tool: https://github.com/chmln/sd/issues/14. From the commit that fixed that issue it seems as if they used a function called `set_permissions()` to ensure the new file had the correct permissions when replacing the file, which is I imagine what is happening here (the whole file gets overwritten).

Rust implementation may be of limited use here but thought it worth flagging, to say great work on diagnosis and flagging the issues on Linux, in case it's of use/inspiration: others have had and solved similar issues for sure :rocket:

**Comment by jmcphers** [comment] 2020-03-10 22:07
The change in ownership is inevitable unless we are willing to modify the file in place. On most Unix/Linux systems it is impossible to change ownership on files unless you are root -- even if you are the current owner of the file. So we shouldn't worry about that one too much.

The change in permissions should not be inevitable. On Unix/Linux systems we should be able to read the permissions mask on the old file (using `::stat`) and reapply it to the new one (using `::chmod`) right before we do the replace.

https://github.com/rstudio/rstudio/blob/8437450d58fb5b99731d71b1e6ef4eefd4f02848/src/cpp/session/modules/SessionFind.cpp#L551

**Closed** 2020-03-11 23:13 UTC
Labels: bug, find in files

**Comment by ronblum** [comment] 2020-03-24 20:11
Verified on Red Hat 7.8 (Server) and MacOS 10.15.4 (Desktop).
