### ISSUE TITLE
Rmd, Visual Mode, very first code chunk does not have chunk options visible

### ISSUE THREAD

**Issue by HannesOberreiter** [rstudio/rstudio#8963] opened 2021-02-12 14:30 UTC
### System details

  RStudio Edition : Desktop
  RStudio Version : 1.4.1103
  OS Version      :  darwin19.6.0
  R Version       : 4.0.3

### Steps to reproduce the problem

Create an empty .Rmd file. Insert a code junk at the very top, eg:

````
```
{r}
summary(cars)
```
````

Save the file and open it again in visual mode. Code Chunk has no clickable options in visual mode. 

### Describe the problem in detail

Example image of first code chunk without clickable options and followed by code chunk with options. If a text is before the code chunk it also works fine. If you edit the code junk the buttons are again visible.

![sample image](https://user-images.githubusercontent.com/16878981/107780507-0d68a700-6d47-11eb-8fcb-364654476a76.png)

### Describe the behavior you expected

Buttons should be visible for every code chunk.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-02-19 15:46
@HannesOberreiter Thank you for raising the issue! I can't reproduce it on MacOS 11.3 Big Sur(Darwin 20.4.0). We'll check on MacOS 10.5 Catalina (I think that's what you're on, since it's Darwin 19.x).

**Comment by HannesOberreiter** [comment] 2021-02-19 16:05
@ronblum I did update my OS a few days ago, I can still reproduce the mentioned bug. I attached a Video.

https://user-images.githubusercontent.com/16878981/108529270-97c78280-72d4-11eb-9e37-c3f2913e64b2.mp4

**Comment by ronblum** [comment] 2021-02-19 18:00
@HannesOberreiter Thank you for the video! We couldn't reproduce this on 10.15 Catalina, either, but the video is useful to show the issue in action. I'll mark it for review.

**Comment by ronblum** [comment] 2021-02-19 18:03
...and now I can reproduce it in RStudio Desktop 1.4.1572 on MacOS 11.3, after all. I'm not sure if there's a specific reprex, since it appears intermittent.

**Comment by jjallaire** [comment] 2021-07-21 02:01
I'm not reproing this either (on Mac OS 10.15). If the issue is Mac OS system dependent then it's almost for sure some issue in the webkit rendering engine (which is more or less beyond our control).

**Comment by jjallaire** [comment] 2021-07-21 18:44
I'm suggesting that we close this due to it's only reproing on older OS's

**Comment by HannesOberreiter** [comment] 2021-07-21 19:22
@jjallaire thanks for looking into it and I personally (if that counts) don't mind if it gets closed.

fyi: I can still reproduce the visual bug on Mac Big Sur 11.4

![image](https://user-images.githubusercontent.com/16878981/126546886-41463fa1-a4f9-45cf-9e12-38f9a041412b.png)

**Comment by astayleraz** [comment] 2021-07-28 00:15
I was unable to reproduce this issue as well. Closing the issue for now as it is hard or inconsistent to reproduce and seems to be limited to older OS's.

**Closed by astayleraz** 2021-07-28 00:15 UTC
Labels: bug, macos, test, visual markdown editing
