### ISSUE TITLE
Non-text files (PDF, Word doc, etc.) aren't getting opened externally

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2156] opened 2018-02-08 00:54 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.331
    OS Version      : MacOS 10.12.6
    R Version       : 3.4.3

### Steps to reproduce the problem

1. File -> Open (or shortcut, e.g. Cmd-O)
2. Choose a non-text file, e.g. as PDF, Word doc, or an Apple disk image file (.dmg)

### Describe the problem in detail

When an attempt is made to open a file that should be opened externally—e.g. .pdf, .docx, even .dmg—the file isn't opened. This is silent—there is no message indicating that the file was not opened.

### Describe the behavior you expected

The file should be opened externally, e.g. .pdf by Preview or Acrobat, .docx by Word, and .dmg extracted. That was the behavior previously, in 1.1.423.

**Comment by dleutnant** [comment] 2018-03-10 12:01
Bug reproducible with RStudio 1.2.405.  (also note that filetypes mentioned are not being opened through clicking in "Files" Pane)

**Comment by yihui** [comment] 2018-04-24 19:18
I'm not sure if it is the same issue, but the PDF won't be opened (no-op) if an R Markdown document is knitted to PDF, and the `System Viewer` is chosen to be the PDF viewer in Options:

![image](https://user-images.githubusercontent.com/163582/39208930-de84b410-47c9-11e8-9c9c-e178c0ec81ce.png)

BTW, I cannot reproduce @ronblum's issue with today's daily build.

**Comment by kevinushey** [comment] 2018-09-13 17:46
It looks like this issue has been fixed in the latest daily builds.

**Comment by yihui** [comment] 2018-09-13 20:17
Just tried the daily build. The issue I reported does not seem to be fixed (still no-op after knitting if the viewer is the system PDF viewer).

**Comment by kevinushey** [comment] 2018-09-13 22:06
Sorry, this should now really for-real be fixed. :-)

**Comment by yihui** [comment] 2018-09-14 03:59
Confirmed! Thanks!

**Closed** 2019-11-27 18:42 UTC
Labels: bug, regression
