### ISSUE TITLE
When using an electron version of Rstudio Desktop, the font of Japanese characters in Source pane does not reflect the font setting

### ISSUE THREAD

**Issue by k1-ito** [rstudio/rstudio#13062] opened 2023-04-28 07:29 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : any electron versions 
    OS Version      : Windows 10/11 Pro 22H2
    R Version       : 4.2.3 and later

### Steps to reproduce the problem
1. use an electron version of RStudio Desktop.
2. choose an editor font in Tools -> Global Option -> Appearance -> Editor font. (I use `Noto Mono` as an example.)

### Describe the problem in detail

The font of Japanese characters does not reflect the font setting.
 
For example:
the Qt version of RStudio-2022.07.2+576 
![2023-04-28 (1)](https://user-images.githubusercontent.com/121043466/235075332-d7380985-d2e1-4ea6-849c-7134887db806.png)
Both Latin and Japanese fonts are `Noto Mono`.

RStudio-2023.03.0+386
![2023-04-28 (3)](https://user-images.githubusercontent.com/121043466/235075281-d5b6679c-979d-45b5-be85-5955103deb4e.png)
In the electron version of RStudio Desktop, the Japanese font is not `Noto Mono` but looks `MS Gothic`,
while `Tokyo` is still shown with `Noto Mono`.

### Describe the behavior you expected

In any electron version of RStudio Desktop, the font setting is also applied to Japanese characters.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-04-28 15:36
@k1-ito Thank you for raising the problem! Can you provide some sample text to try out? This'll make it easier to reproduce the same thing that you're seeing.

**Comment by k1-ito** [comment] 2023-04-29 01:54
@ronblum Thank you very much for your prompt reply.

the Qt version of RStudio-2022.07.2+576
![Qt](https://user-images.githubusercontent.com/121043466/235278112-0d0801a4-864f-45a1-bc4b-44c24e84ade8.jpg)

RStudio-2023.03.0+386
![electron](https://user-images.githubusercontent.com/121043466/235278114-2286e08f-5bec-4fab-8496-81e90ad2a42c.jpg)

Are they sufficient? If not, please let me know.

**Comment by k1-ito** [comment] 2023-04-29 11:43
Sorry, I'm afraid I misunderstood the situation.
I investigated into this issue further and have found this is a difference of fallback Japanese fonts.
The Qt versions use `Meiryo` and the Electron use `MS Gothic` (sans-serif).
So this is more of an enhancement than a bug. (At least for me, `Meiryo` looks nicer than `MS Gothic`.)

**Comment by kevinushey** [comment] 2023-05-01 16:45
It looks like Electron BrowseWindow supports a 'defaultFontFamily' object, so perhaps we can change this to Meiryo? https://www.electronjs.org/docs/latest/api/browser-window

**Comment by kevinushey** [comment] 2023-05-01 16:46
Ah, I see you opened a separate issue at https://github.com/rstudio/rstudio/issues/13070 (thanks!) so I'll close this one.

**Closed by kevinushey** 2023-05-01 16:46 UTC
Labels: bug, info needed, source editor, locale
