### ISSUE TITLE
Data viewer cell width not constrained; list cells don't render

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3940] opened 2018-11-21 18:21 UTC
It appears that https://github.com/rstudio/rstudio/issues/3858 has regressed again; in build 1146, large cells don't get clamped.

![image](https://user-images.githubusercontent.com/470418/48860814-d2998380-ed76-11e8-88a7-d33824c25790.png)

We're also not showing list columns (see [the 1.2 preview blog post](https://blog.rstudio.com/2018/11/19/rstudio-1-2-preview-the-little-things/) for an example of what this should look like). Simple repro:

    library(dplyr)
    z <- data.frame(a = "a") %>% mutate(b = list(list(1,2,3)))
    View(z)

Results in:

![image](https://user-images.githubusercontent.com/470418/48860930-20ae8700-ed77-11e8-9e8d-2b5aa37fc18d.png)

It should have an object exploration icon. 

This is also a regression (from https://github.com/rstudio/rstudio/issues/2881). 

Related: https://github.com/rstudio/rstudio/issues/3919.

**Comment by jmcphers** [comment] 2018-11-21 18:45
@kevinushey do you want to take a look at this? It looks like these long cells aren't getting the `large` class that was intended in https://github.com/rstudio/rstudio/pull/3887.

**Comment by kevinushey** [comment] 2018-11-22 03:36
It looks like this specifically effects list columns -- the original example of

``` r
View(data.frame(a = "Truth", b = "A falsehood which has the sound of truth, and is expressed with vehemence and passion, but is not true in any meaningful way."))
```

does still clamp the width. I'll look into what's going on for list columns.

**Comment by kevinushey** [comment] 2018-11-27 16:59
https://community.rstudio.com/t/rstudio-1-2-na-show-up-as-0-in-dataframe-viewing-tab/18841 may also be related (`NA` cells not rendering as `0` instead of `NA`)

![screen shot 2018-11-27 at 8 59 27 am](https://user-images.githubusercontent.com/1976582/49098003-c3a54c00-f222-11e8-86aa-2b5c0e9053bf.png)

**Comment by adamconroy** [comment] 2018-11-27 18:46
Interesting.  I'll look into this and diff it against the previous performance to confirm it is a regression.

**Comment by adamconroy** [comment] 2018-12-03 16:23
Unfortunately my previous bug fix was very naive (and I didn't know that we actually used the styling functions for anything) so it was doing a very poor job of running the column defs. I took some time through the weekend into today to really understand how the column defs were being run and implemented a solution that solves all of the above problems. 

Fix is in commit https://github.com/rstudio/rstudio/commit/1c34712a40d1d4823db5f019b77ef61be46001b7

**Closed by adamconroy** 2018-12-03 16:23 UTC
Labels: data viewer, regression

**Comment by ronblum** [comment] 2019-02-26 18:59
Verified, but see #4361.
