### ISSUE TITLE
Quoted fields with quotes leads to mismatched parentheses/unexpected tokens

### ISSUE THREAD

**Issue by wgrundlingh** [rstudio/rstudio#9573] opened 2021-07-07 23:44 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Windows
    R Version       : 4.1.0

### Steps to reproduce the problem

The following short piece of code, when saved (unsaved code isn't parsed it seems), shows a parser error:

```
x <- tibble(
  `A \`B C\`` = 1:10
)
```

In principle, a quoted field with quotes needs escaping to preserve the quotes, and that confuses the parser, resulting in a mismatched parenthesis and/or unexpected tokens.

### Describe the problem in detail

![image](https://user-images.githubusercontent.com/1776164/124841542-57466980-df42-11eb-97f2-146c6a4048ab.png)

![image](https://user-images.githubusercontent.com/1776164/124841564-63cac200-df42-11eb-9ae2-3c24b152e679.png)

### Describe the behavior you expected

The statement is valid, so there should be no parser error.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-07-08 14:01
@wgrundlingh Thank you for pointing this out! We'll review this as we continue to develop RStudio.

Note: Reproducible in RStudio Desktop 1.5.168 and RStudio Server on Ubuntu 1.5.168.

**Comment by ronblum** [comment] 2021-07-22 18:25
Verified in
- RStudio Desktop 1.5.232 on MacOS 12 beta
- RStudio Server 1.5.232 on Ubuntu 20.04.2 via Chrome on MacOS 12 beta

Marking for possible automated test.

**Comment by astayleraz** [comment] 2021-08-09 23:38
Looks like unit test coverage was added for this already so I am not going to add a UI test. Closing issue.

**Closed by astayleraz** 2021-08-09 23:38 UTC
Labels: bug, diagnostics, test, autotest
