### ISSUE TITLE
Alt + - shortcut freezes after updating to daily builds (2023.05.0-daily+254≦ )

### ISSUE THREAD

**Issue by aaayato** [rstudio/rstudio#13029] opened 2023-04-21 08:15 UTC
### Issue Summary

After updating to the daily build (2023.05.0-daily+275) to fix the issue "RStudio not able to load selected R version on Windows" (#12452 ), the shortcut key "Alt + -" is no longer functional and causes freezing when entered. Other shortcuts, such as "Alt + Ctrl + I", work properly.

### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.05.0-daily+275
    OS Version      : Windows 10 x64 (build 22621)
    R Version       : 4.2.3

### Steps to reproduce the problem

1. Open RStudio window
2. Open any type of file
3. Type "Alt + -" on the keyboard

### Describe the problem in detail

When I enter the shortcut key "Alt + -", RStudio freezes and becomes unresponsive. This issue only occurred after updating to the daily build (2023.05.0-daily+275) to address issue #12452 . The issue persists even after restarting RStudio.

### Describe the behavior you expected

RStudio should respond to "Alt + -" and perform the appropriate action.

### Already Tried

- Restarting RStudio
- Restarting the computer
- Disabling all other applications and programs running in the background
- Other shortcuts, such as "Alt + Ctrl + I", work properly
- Tried another daily build, but it occurs

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-04-21 14:44
@aaayato Thank you for raising this! What keyboard layout are you using, e.g. US QERTY, Arabic AZERTY, etc.? Also, does this occur in the Console, the Editor in visual or source mode, etc.?

**Comment by aaayato** [comment] 2023-04-23 01:12
Thanks all for the lighting fast response!

I use JIS 108. I am not familiar with the names of the modes...It occurs in the area framed in red. (Source mode and Console?)
<img width="1298" alt="スクリーンショット 2023-04-23 10 02 57" src="https://user-images.githubusercontent.com/45648405/233813947-7bac9ef6-6ac0-403d-9ee4-115b855c9247.png">

**Comment by ronblum** [comment] 2023-04-24 13:56
@aaayato Did this work in previous versions of RStudio Desktop 2023.05?

Ref: #12457 in which <kbd>Alt + -</kbd> doesn't work on non-QWERTY keyboards. In this case, though, it's a QWERTY keyboard (I looked up JIS 108). I can't reproduce the issue, though.

**Comment by aaayato** [comment] 2023-04-25 02:27
I tried using version 2023.05.0-daily+251, but I encountered the same issue. In version 2023.03.0+386, I was able to insert the " <- " character using the "Alt + -" shortcut without any problem. However, in this version, issue #12452 occurs and I need to select Rterm.exe instead of R.exe every time I start the application.

Thank you for your help.

**Comment by ronblum** [comment] 2023-04-25 13:29
@aaayato Thank you for the added info!

Triage: This is a regression in Mountain Hydrangea, although I wasn't able to reproduce it.

**Comment by aaayato** [comment] 2023-04-26 06:29
Hi!
I have installed version 2022.07.2+576 and now the "Alt + -" shortcut is working properly. Also, I am not experiencing issue #12452 with this version, so I will be using it for the time being.
I hope this solution can help others who may be facing similar issues.

Thank you again for your help.

**Comment by timtmok** [comment] 2023-05-01 14:38
@aaayato were you affected by #12452 with 2023.03.0? If so, how did you eventually start RStudio to find that Alt+- does not cause this freezing issue?

**Comment by aaayato** [comment] 2023-05-01 16:44
@timtmok Wtih 2023.030? I got #12452. In this case, I need select Rterm.exe instead of R.exe every time I start the application. For more information. At the select R dialogue, browse to: C:\Program Files\R\R-4.2.2\bin\x64 and select Rterm.exe. Then R Studio launches.

**Comment by timtmok** [comment] 2023-05-01 17:11
@aaayato Thank you for the clarification. I'll see if that fix can get in for the 2023.03.1 patch release.

**Comment by timtmok** [comment] 2023-05-05 14:50
This may be related to #12983. A fix for that other issue has merged and will be available in the next daily (May 6 or greater). So it may be fixed by that change.

@aaayato The startup issue in 2023.03.0 has a fix backported in the 2023.03.1 patch. If you were experiencing issues with an error at startup, that may address the problem.

**Comment by jonvanausdeln** [comment] 2023-05-08 16:38
I checked Desktop build 2023.05.0-daily+331, on Windows 11.  I don't see the issue and it works as expected. Given @aaayato also  is seeing it working, I will close this out.

**Closed by jonvanausdeln** 2023-05-08 16:38 UTC
Labels: bug, key bindings

**Comment by aaayato** [comment] 2023-05-09 00:55
With 2023.05.0-daily+331 I don't see any problems (this problem and #12452).

Thank you for your answers.

**Comment by ronblum** [comment] 2023-05-11 10:15
Thanks for verifying, @aaayato !
