### ISSUE TITLE
data.frame preview with multiple AsIs fails

### ISSUE THREAD

**Issue by khliland** [rstudio/rstudio#13215] opened 2023-06-08 15:36 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.1 Build 446
    OS Version      : macOS Ventura 13.4
    R Version       : 4.3.0

### Steps to reproduce the problem
Run the following line in the console
`df <- data.frame(X = I(matrix(c(1,0,0,1),2)), W = I(matrix(c(1,-1,-1,1),2)))`

### Describe the problem in detail
The `data.frame` viewer fails for `data.frame`s containing two or more **AsIs** objects. This means that the above `data.frame` will lead to an error dialog in the autocompletition preview in the Console, it cannot be opened with the `View()` function and it gives an error when being constructed in the Console.

### Describe the behavior you expected
The desired behavior would be to not get errors for these objects and ideally seeing at least one column of each AsIs object in the preview.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/11690258/diagnostics-report.txt)

**Comment by sharon-wang** [comment] 2023-06-09 18:53
I was able to reproduce this in `2023.06.0+421` on Mac 13.1 using the following steps:

1. Run `df <- data.frame(X = I(matrix(c(1,0,0,1),2)), W = I(matrix(c(1,-1,-1,1),2)))` in console
2. Type `df` in console, then hit tab key to trigger autocomplete
3. Get error
    ```
    Error in .subset2(x, i, exact = exact) : subscript out of bounds
    Error in if (maxRows != -1 && nrow(data) > maxRows) data <- head(data,  : 
        missing value where TRUE/FALSE needed
    ```

**Comment by ronblum** [comment] 2023-06-09 19:13
Looks like this issue has been around for a while, first introduced in Prairie Trillium: I can reproduce it in RStudio Desktop 2022.02.2+485 on MacOS 13.4.

**Comment by kevinushey** [comment] 2023-08-15 18:53
Everything looks good on my side:

<img width="581" alt="Screenshot 2023-08-15 at 11 49 03 AM" src="https://github.com/rstudio/rstudio/assets/1976582/6f077ba8-0cd1-490c-9a4f-1d801ae4ecfa">

**Comment by khliland** [comment] 2023-08-16 07:34
I still get errors on my Mac with the newest RStudio release (and R 4.3.1):
> df <- data.frame(X = I(matrix(c(1,0,0,1),2)), W = I(matrix(c(1,-1,-1,1),2)))
Error in .subset2(x, i, exact = exact) : subscript out of bounds
> View(df)
Error in View : subscript out of bounds

About RStudio:
"Mountain Hydrangea" Release (547dcf86, 2023-07-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

**Comment by sharon-wang** [comment] 2023-08-16 14:55
@khliland, this fix is still undergoing testing and hasn't made it into an official release yet. At the moment, the fix is available in [the daily builds](https://dailies.rstudio.com/), starting with version `2023.09.0-daily+310`.

Please note that the **daily builds are for testing purposes** and are not intended for production use. If you'd like to check the daily builds, we'd be glad to hear if the error is now resolved for you 🙂

**Comment by ronblum** [comment] 2023-08-22 14:46
Verified fixed in RStudio Desktop (MacOS 14) and Server (Ubuntu 20.04.5) 2023.09.0-daily+348 using the above reprex.

**Closed by ronblum** 2023-08-22 14:46 UTC
Labels: bug, data viewer
