### ISSUE TITLE
Issue: Unable to establish connection with R session

### ISSUE THREAD

**Issue by cassiorampinelli** [rstudio/rstudio#8497] opened 2020-12-01 17:13 UTC
Hi,
I have been using R Studio/R for a while, and it was working fine. However, after I recently updated it, it started popping up a window with the message “Unable to establish connection with R session”. 

I know that there are similar topics like that (for instance, https://community.rstudio.com/t/rstudio-error-unable-to-establish-connection-with-r-session/58759), but I couldn’t solve my case with any suggestions. Does someone have any idea about how can I fix it? 

Thank you
 

_______________________________________________________________________________________________________________________
Following is my Session Info

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.3  bookdown_0.20   htmltools_0.5.0 tools_4.0.3     yaml_2.2.1      tinytex_0.24    rmarkdown_2.3  
 [8] knitr_1.29      digest_0.6.25   xfun_0.15       rlang_0.4.6     evaluate_0.14  

PS:

**Comment by antoniodagnino** [comment] 2020-12-21 03:55
I have the same problem and is driving me crazy! 'Unable to stablish connection with R session'

There are several ways to recreate the error:
1. I can just leave the Rstudio idle for around 5 seconds, and then I just hit enter in console and the error will show up. After that, if I continue pressing enter the error dissapears and console starts executing my code. However, the error comes back again.
2. If I click on history tab, most of the times I get the error showing again. Then, I insist couple of times until history shows up
3. If I go to Tools-->global options I get the error as well
4. This is a good one, if I go to Tools --> Global options --> Code -->Saving and then I edit Auto-Save option 'When editor is idle': set to 'backup unsaved changes'. That would make the error to show up every 5-10 seconds. It would not let me write code without interrupting me. I had to disable that option to partially work on my Rstudio.

I believe this is is a problem of link between R and RStudio. Since it's intermittent, but pretty consistent I have the chance to evaluate it's behavior.

My action items were all mentioned in https://community.rstudio.com/t/rstudio-error-unable-to-establish-connection-with-r-session/58759 and no luck

Also, I shut down my firewall to see if it was a problem but no luck.

I hope you might have an idea of what this could be and help out!

Regards,

Antonio

**Comment by jmcphers** [comment] 2021-02-16 19:09
We're closing this since we need more information to reproduce the problem. If you're still seeing it with the latest version of RStudio, please reopen and fill out the bug reporting template completely.

**Closed by jmcphers** 2021-02-16 19:09 UTC
Labels: bug, triage, windows
