### ISSUE TITLE
Console command history does not automatically highlight last command

### ISSUE THREAD

**Issue by uqrmaie1** [rstudio/rstudio#7682] opened 2020-08-30 17:52 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      : macOS Catalina 
    R Version       : 3.5.2

### Steps to reproduce the problem

When pressing Command + up to cycle through the command history, the highlighted command is not the latest command.

### Describe the problem in detail

The list of previous commands shows the earliest matching ones. To get to the latest commands, it's necessary to scroll down the list. This is different from earlier version of RStudio, where the latest matching command was the one highlighted.

### Describe the behavior you expected

I would expect the last command to be the first to come up.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-10-13 18:19
@uqrmaie1 I'm unable to reproduce it in 1.3. However, would you be willing to try out the RStudio 1.4 Wax Begonia preview at https://rstudio.com/products/rstudio/download/preview/ to see if this is still an issue in it? There was another bug related to history that was resolved, and I wonder if this is affected, as well. (Note: previews are meant for testing and evaluation only.

**Comment by kevinushey** [comment] 2020-10-15 22:00
I'm also unable to reproduce. Given that, I'm going to close the issue; @uqrmaie1, please feel free to re-open if you can provide more context.

**Comment by uqrmaie1** [comment] 2020-10-20 02:33
Thanks for looking into this!
I have tested this in RStudio 1.4, and the behavior hasn't changed.

The problem only occurs after searching the history for partial matches: After re-starting RStudio, Command+Up will highlight the last command. Typing the beginning of another command followed by Command+Up will still highlight last command. But after that, Command+Up will highlight seemingly random commands (regardless of whether or not it's a partial search or a full search).

I have removed my history_database and .Rhistory files, but I get the same behavior even with a fresh command history.

I don't think I can re-open the issue, but I could make a new one or provide more information.

**Comment by kevinushey** [comment] 2020-10-20 16:40
Thanks! I'll re-open and I'll see if we can reproduce given your feedback.

**Comment by kevinushey** [comment] 2020-10-20 19:42
I'm still not able to reproduce. I think we'll need to see a screencast or something similar so we can understand exactly what behavior you're seeing.

**Comment by uqrmaie1** [comment] 2020-10-20 19:57
This shows what I get by searching the command history with Command+Up. In the first two instances the last (bottom) command is highlighted. In the third instance, it's a random command in the middle of the command history.

![Screen Recording 2020-10-20 at 3 51 00 PM2](https://user-images.githubusercontent.com/8817129/96637439-ada84500-12ec-11eb-9d16-c9a2182090a5.gif)

**Comment by mikebessuille** [comment] 2020-10-22 19:52
This is great feedback; thank you for the recording and detail.  At this point in the 1.4 release, we're only taking critical fixes, so we'll have to look at this early in the next release.  Moving to 1.5.

**Comment by kevinushey** [comment] 2020-12-01 19:48
Moving to 1.4 as this has become a sufficiently annoying issue for a number of users.

The underlying issue, if I understand correctly, is that the index of the last selected item is restored when the command history is presented, even if the search query has changed. For example, this reproduces the issue for me:

1. Press <kbd>Cmd + Up</kbd> to show command history,
2. Select the item 2nd from the top (press the Down button twice to select it),
3. Press enter to insert that item from the history,
4. Clear the entered item in the console by e.g. using backspace,
5. Type `x`, and then press <kbd>Cmd + Up</kbd> to initiate a new search with `x` as the query.

The 2nd item in the list is selected, even though a brand new query has been initiated.

![console-history](https://user-images.githubusercontent.com/1976582/100788870-8acc7e80-33ca-11eb-9f24-42c57dca9429.gif)

The problem is that we compare the search query string with the selected text too late -- note how we update `lastSearch_ = text` here:

https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HistoryCompletionManager.java#L235

but then test it again afterwards here:

https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HistoryCompletionManager.java#L238-L241

**Closed** 2020-12-02 00:35 UTC
Labels: backlog, bug, console

**Comment by kfeinauer** [comment] 2020-12-02 15:41
Verified fixed 1.4.1073
