### ISSUE TITLE
R studio crashes constantly when disconnecting from external displays

### ISSUE THREAD

**Issue by nergiszaim** [rstudio/rstudio#5781] opened 2019-11-22 19:48 UTC
OS Version: Catalina
RStudio Version:  1.2.5019
Edition: "Elderflower" (fba733f0, 2019-10-24)

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by jmcphers** [comment] 2019-11-23 00:41
Sorry, you haven't included any reproducible steps, a crash report, or any other information that would help us here. Please fill out the issue template completely. 

RStudio 1.3 includes automated crash reporting, so if you're willing to try a daily that may either (a) resolve your problem, or (b) get enough information to us to fix it.

https://dailies.rstudio.com/

**Comment by jmcphers** [comment] 2019-11-23 00:42
Possibly also a dupe of https://github.com/rstudio/rstudio/issues/5749

**Closed by jmcphers** 2019-11-23 00:41 UTC
