### ISSUE TITLE
HTML <input> with type='checkbox'/'radio' doesn't render correctly in viewer

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rstudio#9730] opened 2021-08-12 22:20 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : "Ghost Orchid" Daily (129b6e5b, 2021-08-12) for macOS
    OS Version      : MacOs 11.5.1 (Big Sur)
    R Version       : 4.1.0

### Steps to reproduce the problem

```r
library(htmltools)

browsable(
  tags$label(
    tags$input(id="foo", type="checkbox"),
    tags$span("foo")
  )
)
```

![input-check](https://user-images.githubusercontent.com/1365941/129277132-8f667825-4e93-4566-981c-d3f626fc59a0.gif)

### Describe the behavior you expected

When the checkbox is selected, a checkbox should render (similar to how it does in other browsers)

**Comment by ronblum** [comment] 2021-08-19 18:17
@cpsievert Thanks! I can't reproduce it, though I'm using MacOS 12 Monterey.

@astayleraz Would you mind trying this in MacOS 10.15.x Big Sur? Thanks!

**Comment by ronblum** [comment] 2021-08-24 20:47
See https://github.com/rstudio/shiny/issues/3484.

**Comment by nwstephens** [comment] 2021-10-04 23:33
Interestingly, this is not an issue in RStudio Workbench.

https://vimeo.com/622897255

**Comment by gtritchie** [comment] 2021-10-05 04:24
> Interestingly, this is not an issue in RStudio Workbench.

This suggests an issue with Qt (QtWebEngine). Not the first (by far), especially on Mac. For example see the discussion here: https://github.com/rstudio/rstudio/issues/3190#issuecomment-406440054

I ran a test on our (pre-alpha) Electron desktop, and this problem goes away on Mac, so I'll add this to our "Fixed By Electron" epic.

**Comment by jmcphers** [comment] 2021-10-05 15:41
The "fix" for this is to add some CSS that adds just a dash of zoom to the radios.

**Comment by gtritchie** [comment] 2021-11-19 17:58
I can't repro on Monterey (12.0.1) with 2021.09.1+372 "Ghost Orchid".

**Comment by R-Hannibal** [comment] 2022-01-11 18:14
So far this appears to only occur on MacOS 11 (multiple reports of the issue being non-reproducible on MacOS 12), and has not been seen to occur on early pre-alpha Electron builds.

Removing the `qa repro` label, this issue should be re-tested on an Electron build when they're available on MacOS 11 to see if the issue is fixed simply by the switchover to Electron with no other code change required.

**Comment by kevinushey** [comment] 2022-03-02 23:29
Appears to be fixed in Electron.

https://user-images.githubusercontent.com/1976582/156467108-aac36129-1780-4d63-8973-445fc85acc41.mov

**Closed by kevinushey** 2022-03-02 23:29 UTC
Labels: bug, qtwebengine, backlog, electron, good first issue
