### ISSUE TITLE
Error viewing function.  Incorrect number of arguments for 'rs_jumpToFunction'

### ISSUE THREAD

**Issue by M3IT** [rstudio/rstudio#8170] opened 2020-10-23 10:29 UTC
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.953
    OS Version      : Win 10 v2004
    R Version       : 4.0.3

### Steps to reproduce the problem
1. Source an R file containing functions
2. Note list of functions appearing in the environment pane
3. Click on a function to view it. 
4. Console shows: View(function_name)
5. Console shows: **Error in View : Incorrect number of arguments (3), expecting 4 for 'rs_jumpToFunction'**

Note that if the R script is opened in RStudio and manually run, rather than the file being sourced, the functions will display correctly.

### Describe the problem in detail
_Error in View : Incorrect number of arguments (3), expecting 4 for 'rs_jumpToFunction'_ when attempting to open a function previously sourced.

### Describe the behavior you expected
Function code to display in new source code window.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-10-23 18:23
@M3IT Thank you for the bug report! I can't reproduce it on either Windows 10 or MacOS 11. Can you provide an example so that I can try to reproduce this? Thanks!

**Comment by bohm0072** [comment] 2020-10-24 03:01
I had the same error independently occur for me on MacOS 10.15 w/ R 4.0.3 and RStudio 1.4.953.

Error was resolved for me once I reverted to the stable version of the release for RStudio (1.3.1093).

**Comment by M3IT** [comment] 2020-10-24 03:45
[Repo](https://github.com/M3IT/RStudio_function_open_issue). 
Run test.R

Includes [short gif](https://github.com/M3IT/RStudio_function_open_issue/blob/main/example.gif) of the error occurring. 

Per @bohm0072, I tried reverting to RStudio-1.3.959 and the problem no longer occurs.

**Comment by kevinushey** [comment] 2020-10-24 05:30
Thanks! I was able to reproduce and this will be fixed up in the next daily builds + the next iteration of the 1.4 preview.

For reproducing, note that you need to source a saved R file -- merely running the code with e.g. <kbd>Cmd + Enter</kbd> is not sufficient.

**Closed** 2020-10-24 05:29 UTC
Labels: bug, environment pane, repro needed

**Comment by kfeinauer** [comment] 2020-11-16 21:59
Verified fixed 1.4.1035
