### ISSUE TITLE
RStudio issues "Fatal error: 'R_TempDir" contain space" error and doesn't start up

### ISSUE THREAD

**Issue by pikpa** [rstudio/rstudio#13112] opened 2023-05-11 18:37 UTC
### System details

    RStudio Edition : 
    RStudio Version :
    OS Version      : Windows 11
    R Version       : 4.3.0

### Describe the problem in detail

I downloaded R 4.3.0 download with Windows 11, it gives this error when starting "Fatal error: 'R_TempDir" contain space" , Rstudio also does not work

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-05-12 07:24
@pikpa Thank you for raising the issue! This is a known problem, so I'm closing this as a duplicate of issue #13012, where you can follow the progress and provide any additional information you might have.

**Closed by ronblum** 2023-05-12 07:24 UTC
Labels: bug, windows, startup
