### ISSUE TITLE
Code chunk of shell commands  are not displayed correctly in “html_notebook” output of R notebook

### ISSUE THREAD

**Issue by mt1022** [rstudio/rstudio#1700] opened 2017-11-01 04:43 UTC
I have a R notebook named "test.Rmd" with the following content:

    ---
    title: "R Notebook"
    output: html_notebook
    ---
    ```{sh}
    faToTwoBit dmel-all-chromosome-r6.04.fasta dmel-all-chromosome-r6.04.2bit
    ```

Then rstudio will create "test.nb.html" automatically. However, the code chunks are wrongly displayed in the html:

[![enter image description here][1]][1]

It only displayed `bit`, instead of the entire line (`faToTwoBit dmel-all-chromosome-r6.04.fasta dmel-all-chromosome-r6.04.2bit`).

I have asked [this question on SO](https://stackoverflow.com/questions/47000407/why-does-r-notebook-display-truncated-lines-in-html-notebook-output) and also reported it [here](https://github.com/yihui/knitr/issues/1451). It seems to be a rstudio bug. I am using the latest release of RStudio 1.1.383 - Ubuntu 16.04+/Debian 9+ (64-bit) 2017-10-09 downloaded from [here](https://www.rstudio.com/products/rstudio/download/).

  [1]: https://i.stack.imgur.com/wVfRb.png

**Comment by kohlkopf** [comment] 2017-11-01 07:31
I'll add my 2¢–it looks like this is only an issue when you have a {sh} chunk and there is a number preceding by a period as part of a continuous set of characters. Removing this part of the shell command from the file name resulted in expected output.

**Comment by mt1022** [comment] 2017-11-01 11:09
@kohlkopf That seems to be the cause of the error. If I change the line to `faToTwoBit dmel-all-chromosome-r6.x04.fasta dmel-all-chromosome-r6.x04.x2bit` by  inserting a `x` between every neighboring `.` and digits , it will be displayed correctly.

**Comment by kevinushey** [comment] 2017-11-01 16:04
Here's an MRE (attempt to preview this notebook without executing any chunks)

````
---
title: "R Notebook"
output: html_notebook
---

```{bash}
a.1
```
````

**Comment by kevinushey** [comment] 2017-11-01 16:14
The content is correctly written out in the resulting Notebook file; e.g. we have:

    <pre class="bash"><code>a.1</code></pre>

I suspect this might actually be an issue with `highlight.js`. @yihui, I think I saw you were working on an update to highlight.js because of similar issues seen in R documents -- do you know if this is an incantation of the same issue?

**Comment by yihui** [comment] 2017-11-01 16:21
@kevinushey The issue with your MRE definitely seems like the highlight.js issue https://github.com/rstudio/rmarkdown/issues/988. I'm not sure about the issue with `faToTwoBit`. It might be the same. It is easy to verify, though. @mt1022 Could you try the patch https://github.com/rstudio/rmarkdown/pull/1178?

```r
devtools::install_github("rstudio/rmarkdown#1178")
```

If the problem is gone, it is an issue with highlight.js and we need to upgrade it in the rmarkdown package.

**Comment by kevinushey** [comment] 2017-11-01 16:27
@yihui: Thanks! Just want to confirm that your patch does indeed resolve the issue in the MRE I put together.

**Comment by kevinushey** [comment] 2017-11-01 18:46
I'm going to close this as a duplicate of https://github.com/rstudio/rmarkdown/issues/988, since this needs to be resolved in `rmarkdown`.

**Closed by kevinushey** 2017-11-01 18:46 UTC
Labels: bug, low, reproducible

**Comment by mt1022** [comment] 2017-11-02 01:44
@yihui I tried that patch and and the shell commands get displayed correctly. I think that fixed the problem.

**Comment by yihui** [comment] 2017-11-02 02:05
@mt1022 Good to know. I'll continue working on https://github.com/rstudio/rmarkdown/pull/1178 and hopefully it will be merged soon. Thanks for testing it!
