### ISSUE TITLE
US international layout with dead keys not working ok in terminal

### ISSUE THREAD

**Issue by pachamaltese** [rstudio/rstudio#2587] opened 2018-04-04 18:55 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1
    OS Version      : Ubuntu 16.04.4 LTS
    R Version       :  3.4.3

### Steps to reproduce the problem

Open the terminal from RStudio and try to type `git commit -m "some message", the quotes won't be caught by the program

### Describe the behavior you expected

To be able to type ", á, é , etc

### The output of sessionInfo() 

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=es_CL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=es_CL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=es_CL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=es_CL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4    yaml_2.1.18  
```

**Comment by gtritchie** [comment] 2020-03-26 17:02
I am not able to reproduce this on Ubuntu 16.04.6 LTS using RStudio 1.1.463, 1.2.5033, or 1.3.929.

I'm using "English (International AltGr dead keys)" and able to type double-quotes normally.

**Comment by pachamaltese** [comment] 2020-04-02 00:10
@gtritchie Hi. I created a video that shows the problem with Ubuntu 18.04 https://drive.google.com/open?id=1tYAVl1HLTmt0K8lPEGidaFqr0NXeWyGB

**Comment by gtritchie** [comment] 2020-04-03 22:41
Note to self, see also: https://github.com/rstudio/rstudio/pull/6517

**Comment by gtritchie** [comment] 2020-04-03 22:43
@pachamaltese Thanks, what version of RStudio are you trying? If you can, please try the latest 1.3 preview and see if that makes any difference. https://rstudio.com/products/rstudio/download/preview/

**Comment by pachamaltese** [comment] 2020-04-03 22:44
sure, I'll update Version 1.2.5033

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by ronblum** [comment] 2020-04-16 15:08
@pachamaltese Have you had any luck with the upgrade to 1.2?

**Comment by pachamaltese** [comment] 2020-04-16 15:17
No luck. Any idea how to upload a video here?

**Comment by pachamaltese** [comment] 2020-04-17 17:19
here's a video
[rstudio.zip](https://github.com/rstudio/rstudio/files/4494345/rstudio.zip)

**Comment by andodet** [comment] 2020-10-02 10:52
Glad I've found this issue, dead keys on intl keyboards don't work with `1.4.874`. To be honest I have no idea whatsoever on how to go debugging this.

<details>
<summary><tt>sessionInfo()</tt> output</summary>
<p>

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] fansi_0.4.1       withr_2.3.0       digest_0.6.25     crayon_1.3.4      assertthat_0.2.1  evaluate_0.14    
 [7] rlang_0.4.7       cli_2.0.2         rstudioapi_0.11   rmarkdown_2.3     tools_4.0.2       glue_1.4.2       
[13] tinytex_0.25      xfun_0.16         yaml_2.2.1        compiler_4.0.2    sessioninfo_1.1.1 htmltools_0.5.0  
[19] knitr_1.29
```
</details>

**Comment by R-Hannibal** [comment] 2021-04-23 20:48
Not able to reproduce this on JR builds testing on Ubuntu20, closing as not reproducible.

@andodet - let us know if you're still experiencing this issue in our [latest release](https://dailies.rstudio.com/) along with the keyboard you're using and we'll take another look.

**Closed by R-Hannibal** 2021-04-23 20:48 UTC
Labels: encoding, linux, qa repro, terminal
