### ISSUE TITLE
Realtime Spellcheck: Rip out Typo.js, just use the CPP Hunspell

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#9145] opened 2021-03-24 18:50 UTC
Not quite a bug, not really a feature but:

Typo.js is flawed. It's been a thorn in our side since it first couldn't handle the larger dictionaries and further quirks have been identified as time goes on (issues with encodings, thinks every Korean misspelling is correct). Also it appears that the dictionary isn't really being maintained anymore. I've had this idea in the back of my head for a while and I think it's just time to do it.

Much of the work for realtime spellchecking is still valid (linting, only checking on scroll, etc) but we should just shunt the words down to the backend spellchecker instead of querying Typo.js. This will dramatically simplify the system complexity as well as give us [me] more confidence in the strength of our spellchecker. I was overly ambitious putting this feature together and didn't know 
 how to fully vet all the use cases for this library before using it.

I actually don't anticipate this taking particularly long at all (I've poked at this idea multiple times in the past year) and I'd love to cut out the performance losses that Typo.js added.

**Comment by adamconroy** [comment] 2021-03-24 19:00
Also I REALLY want to remove this "feature": https://github.com/rstudio/rstudio/blob/bb77b1f8a561594616c6f48ed88388a4f9b70200/src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java#L520

There are a couple open PRs against Typo.js to address this in different ways but there hasn't been any movement on them in years.

**Comment by valerie-rstudio** [comment] 2021-04-20 18:12
Ran through preliminary testing of feature/bug before Pull Request was merged using custom release file. [Test doc can be viewed here.](https://docs.google.com/spreadsheets/d/1E1_S0TOEbr65a2jY_WPE1WslFEaenQ_dMmURa__htnU/edit?usp=sharing) 

Two bugs were discovered during testing (although they were not regressions caused by this change:
- https://github.com/rstudio/rstudio/issues/9245
- https://github.com/rstudio/rstudio/issues/9244

**Comment by adamconroy** [comment] 2021-04-22 17:24
This is done.

**Comment by valerie-rstudio** [comment] 2021-04-26 16:09
### Verified Fixed

    RStudio Edition : Server
    RStudio Version : 1.4.1687-1
    OS Version      : ubuntu20
    R Version       : 4.0.2

Verified that spellchecking works as expected. See above comment for full test doc completed on test build before merge. Quick cursory check performed again after merge.

**Closed by valerie-rstudio** 2021-04-26 16:09 UTC
Labels: bug, spellcheck, test
