### ISSUE TITLE
`debugonce()` "loses focus" on file after printing out local variable

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#10664] opened 2022-02-23 19:53 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Daily 2022.02.0 Build 427
    OS Version      : Mac
    R Version       : 4.1.1

### Steps to reproduce the problem

Run the following and then step through the debugger like I do in the video

```r
library(slider)

debugonce(slider:::slide_impl)

slide_dbl(1:5, identity)
```

### Describe the problem in detail

After using `debugonce()`, you are generally taken to a file where you can step through the code. It seems that if you:

- Begin stepping
- Print out a local variable
- Continue stepping

then the IDE will lose focus of that file.

The video below shows this by first stepping through the function without printing anything out (which works), and then shows the buggy situation where focus on the file is lost.

https://user-images.githubusercontent.com/19150088/155397295-41b98219-9824-4c27-8c6b-9643db866573.mov

**Comment by DavisVaughan** [comment] 2022-04-27 19:56
It is worth noting that this doesn't occur for packages that you have used `devtools::load_all()` on.

i.e. if I do `devtools::load_all()` to load slider, then do `debugonce(slide_int)`, then it works fine.

But as seen above if I do `library(slider)` then `debugonce(slide_int)`, then it breaks

**Comment by kevinushey** [comment] 2022-04-27 20:21
This bug effectively makes the debugger unusable (it's a bad regression and affects debugging for any function) so it needs to be fixed in SW.

**Comment by mikebessuille** [comment] 2022-05-02 17:49
Consider for backporting to next PT patch as well

**Comment by DavisVaughan** [comment] 2022-05-10 17:43
I've also noticed that if I install the package locally with RStudio's `Install` button then it works fine. i.e. if I were to install slider locally, then close the slider Rproj and jump into a different project, then I would still be able to debug the original example properly.

I think this implies that it has something to do with `--with-keep.source`, as RStudio's install button keeps source by default, and I think `load_all()` does too

**Comment by kevinushey** [comment] 2022-05-10 18:16
https://github.com/rstudio/rstudio/pull/9922 may be related; it fixed a similar issue IIRC. (Or at least, it should help give a place to start looking.)

**Comment by jgutman** [comment] 2022-05-10 20:16
Thanks for pointing me @kevinushey ! Reverting confirmed that the regression was indeed introduced in that commit so now I have a very good idea where to look 😸

**Comment by jgutman** [comment] 2022-05-10 22:33
@mikebessuille This bug was introduced in 2022.02.0, and so definitely needs to be in the next PT patch

**Comment by romainfrancois** [comment] 2022-05-11 07:32
Verified in RStudio 2022.06.0-daily+385 and RStudio 2022.02.3+490 "Prairie Trillium" 

spotted wake robin; 

<img width="767" alt="image" src="https://user-images.githubusercontent.com/2625526/167793287-4ffbf198-2725-4de4-ba75-d17183887ef5.png">

prairie trillium: 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/2625526/167793895-97fefd5b-960f-4e42-8495-474cbcce3e87.png">

**Comment by DavisVaughan** [comment] 2022-05-11 11:49
I can also confirm that this is fixed with the latest daily (2022.06.0-daily+385). Thank you all! I am very happy this is fixed

**Comment by kevinushey** [comment] 2024-03-02 04:44
I'm seeing this issue again with R 4.3.2, but not sure if this is a regression in RStudio or a change in the latest R release that's causing trouble. Either way, I believe https://github.com/rstudio/rstudio/pull/14360 will resolve this issue.

**Comment by ronblum** [comment] 2024-03-13 15:36
@DavisVaughan Would you be able to check this in the latest dailies? It's working for me in RStudio Desktop 2024.04.0-daily+573, but I can't reproduce the problem in the first place.

**Comment by jgutman** [comment] 2024-03-13 16:05
FYI Davis is OOO until March 21

**Comment by DavisVaughan** [comment] 2024-03-21 19:31
It's working for me in 2024.04.0-daily+635

**Comment by kevinushey** [comment] 2024-03-21 20:51
thanks @DavisVaughan!

**Closed** 2024-03-21 20:51 UTC
Labels: bug, regression, debugging, need help verifying
