### ISSUE TITLE
RStudio incorrectly opens rendered Quarto book at the root URL

### ISSUE THREAD

**Issue by dpastoor** [rstudio/rstudio#11883] opened 2022-08-31 17:25 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : "Elsbeth Geranium" Daily (f2c427e6, 2022-08-30) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+157 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36
    OS Version      : 12.3.1 Monterey
    R Version       : 4.2.1

### Steps to reproduce the problem

Render a book through the Render button

### Describe the problem in detail

When render is clicked, RStudio opens the book at the root URL, instead of the URL with the correct path. In this case, instead of `http://localhost:6067` it should open `http://localhost:6067/example.html`.

https://user-images.githubusercontent.com/3196313/187740984-dc114a04-3435-4d3f-a136-2401607b2474.mov

### Describe the behavior you expected

RStudio should open the correct URL.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MariaSemple** [comment] 2022-09-06 18:11
Could this be caused by the book in this example not having a homepage such as `index.qmd`?

**Comment by jthomasmock** [comment] 2022-09-06 18:12
What version of Quarto is this?

**Comment by dpastoor** [comment] 2022-09-06 23:42
@jthomasmock  1.1.168 - @MariaSemple indeed if I have an index.qmd and setup as a entire book is rendered it opens properly, the confusing piece is it's properly messaging which URL path to open in the terminal but then opens only to the root instead (check around 10 seconds into the recording)

**Comment by mikebessuille** [comment] 2022-09-13 14:50
Per Tom, this is expected behaviour.  Closing this; @dpastoor if you think this should change, please comment.

**Closed** 2022-09-13 14:50 UTC
Labels: bug, quarto
