### ISSUE TITLE
Freeze when copy-pasting within a QMD file

### ISSUE THREAD

**Issue by VNNikolaidis** [rstudio/rstudio#12934] opened 2023-03-30 11:40 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  2023.03.0+386
    OS Version      :  Windows 10
    R Version       :  4.2.3

### Steps to reproduce the problem

1. Rename test2.qmd.txt to test2.qmd

2. Open it in RStudio
 
3. Copy the last two lines (from < to >) in that file and paste it below. RStudio IDE freezes.

### Describe the problem in detail

RStudio sometimes freezes when copy-pasting in qmd file. 

### Describe the behavior you expected

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/11110936/diagnostics-report.txt)
[test2.qmd.txt](https://github.com/rstudio/rstudio/files/11110940/test2.qmd.txt)

**Comment by VNNikolaidis** [comment] 2023-03-30 14:07
Thank you for your reply, indeed it probably the same as issue #12879  (which I have missed noticing). In my case I only noticed it happening when editing QMD files. I cannot help on whether it existed in previous versions (although I might install one and check).

**Comment by mikebessuille** [comment] 2023-03-30 17:38
Closing this as a duplicate of https://github.com/rstudio/rstudio/issues/12879. I think it's a duplicate; if it turns out to be a separate issue we will reopen.  We intend to urgently fix this problem; thank you for raising it!

**Closed by mikebessuille** 2023-03-30 17:38 UTC
Labels: bug, triage, visual markdown
