### ISSUE TITLE
Various preferences are not saved in .config/rstudio/rstudio-pref.json

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#5147] opened 2019-07-26 11:48 UTC
After #5069 has been merged, I cannot apply various settings in the IDE:

- Pane layout
- "code" settings
- "general" settings

When changed, they are not applied and not written to `.config/rstudio/rstudio-pref.json`. 

In addition, when clicking "OK" to close the "Global Options" menu nothing happens. Only "cancel" works.

**Comment by jmcphers** [comment] 2019-07-26 16:57
I couldn't reproduce any of these except the pane layout bit (I think that may have been blocking the others). It looks like some strings were missed there. I've just pushed a fix; should have a new build later today. Thanks for reporting!

**Closed** 2019-07-26 16:56 UTC

**Comment by pat-s** [comment] 2019-07-26 18:12
Everything fine now again, thanks! Finally a VCS usuable config file :rocket:
