### ISSUE TITLE
No arguments list or autocomplete for 'new' of R6 classes

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8423] opened 2020-11-18 15:08 UTC
**Steps to reproduce:**
* Load some library defining an R6 class.
* Try to create an instance with `the_class$new()`
* Try to get autocomplete on the arguments for `new`.

**Expected behavior:** should show arguments and autocomplete options for the `new` call for R6 classes.

**Actual behavior:** shows only the generic `new(...)`, which is not helpful.

**Setup:** RStudio 1.4.1032, R 4.0.3, R6 2.5.0.

**Comment by kevinushey** [comment] 2020-11-18 18:02
Marking as 1.4 because this is a regression from 1.3 and because the fix is safe.

**Closed** 2020-11-19 00:01 UTC
Labels: autocompletion, bug

**Comment by kfeinauer** [comment] 2020-11-20 15:08
@david-cortes Would you be able to check the latest daily version to see if this is fixed for you?

**Comment by david-cortes** [comment] 2020-11-20 21:47
@kfeinauer : it's working, but with a caveat. If I try `some_class$new()` and press tab inside the parentheses, it will autocomplete them correctly, but when I type `some_class$new()` and it shows me a pop-up with the arguments,  the pop-up will only say `new(Class, ...)`.

**Comment by kfeinauer** [comment] 2020-11-20 21:48
@kevinushey Is the behavior reported by David also a regression?

**Comment by kevinushey** [comment] 2020-11-20 22:09
That's not a regression; that's a relatively long-standing issue.
