### ISSUE TITLE
>> When I want to choose a file from a list - nothing happens

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [rstudio/rstudio#7279] opened 2020-07-06 13:39 UTC
Hi,
When I press this button >> (many tabs are open):

![obraz](https://user-images.githubusercontent.com/28902421/86598805-f6d2c400-bf9d-11ea-952a-9a243637aee5.png)

and I have chosen a file to bring it back in r script pane - nothing happens. 
It doesn't bring it back on a screen.

![obraz](https://user-images.githubusercontent.com/28902421/86599100-752f6600-bf9e-11ea-9658-f48041d7f19a.png)

Please fix it. 

My Rstudio version is 1.4.539, Windows 10 x64, R 4.0.0.
When I installed preview version 1.3.1054 of RStudio everything is OK.

**Comment by gtritchie** [comment] 2020-07-06 15:27
Duplicate of #7274

**Closed by gtritchie** 2020-07-06 15:27 UTC
Labels: duplicate
