### ISSUE TITLE
getActiveDocumentContext() does not treat console as "active document" in RStudio 1.3.944

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#6805] opened 2020-04-20 20:43 UTC
In RStudio **1.2**.5042, `getActiveDocumentContext()` returns the contents of the editor the focus is on: either from R console or from source editor (**the expected behavior**).
This line was run in console:
```r
rstudioapi::getActiveDocumentContext()
## Document Context: 
## - id:        '#console'
## - path:      ''
## - contents:  <1 rows>
## Document Selection:
## - [1, 1] -- [1, 1]: ''
```

Unfortunately, in RStudio v**1.3**.944, it seems that `getActiveDocumentContext()` does not treat R console as "active document" and always return the same result as `getSourceEditorContext()` does (**the undesired behavior**).
These lines were run in console:

```r
rstudioapi::getActiveDocumentContext()
## Document Context: 
## - id:        'C7E93921'
## - path:      '~/R/file.R'
## - contents:  <16 rows>
## Document Selection:
## - [11, 1] -- [11, 1]: ''
```

To make sure that the other two functions work as expected:

```r
rstudioapi::getConsoleEditorContext()
Document Context: 
## - id:        '#console'
## - path:      ''
## - contents:  <1 rows>
## Document Selection:
## - [1, 1] -- [1, 1]: ''
```

```r
rstudioapi::getSourceEditorContext()
## Document Context: 
## - id:        'C7E93921'
## - path:      '~/R/file.R'
## - contents:  <16 rows>
## Document Selection:
## - [11, 1] -- [11, 1]: ''
```

I expect `rstudioapi::getActiveDocumentContext()` to return the contens of the editor that has focus.

I use RStudio v1.3.944-1 Preview on Windows 10 with R 3.6.3 and **rstudioapi** 0.11.

**Comment by kevinushey** [comment] 2020-05-04 17:41
Transferring this to the RStudio repository as the work required to fix it will likely lie on the RStudio side.

**Comment by kevinushey** [comment] 2020-05-04 17:42
Marking as v1.3-patch since (IIUC) this will imply that RStudio Addins which rely on correctly inferring the active editor (Source pane vs. Console) will not function correctly.

**Comment by kevinushey** [comment] 2020-05-04 17:51
This is likely caused by a change in the IDs used for elements in the IDE. We check if the last focused editor had the `"rstudio_console_input"` ID here:

https://github.com/rstudio/rstudio/blob/1575b60af00590f79694da0036cb5e6f43cde5bd/src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java#L699-L703

It looks like the ID for the console input editor instance has inadvertently changed:

<img width="565" alt="Screen Shot 2020-05-04 at 10 50 05 AM" src="https://user-images.githubusercontent.com/1976582/80996693-1cecb400-8df5-11ea-9923-6025116282a2.png">

We should make this check more robust.

**Comment by gtritchie** [comment] 2020-05-04 21:00
Fixed in 1.4 via a5dcc971, and in 1.3-patch via d6bb993b.

**Closed by gtritchie** 2020-05-04 21:00 UTC
Labels: console, regression

**Comment by R-Hannibal** [comment] 2020-06-03 15:36
Hey @GegznaV, thanks again for finding and reporting this issue. We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).

If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by GegznaV** [comment] 2020-06-08 19:07
The issue is solved. Thank you.

**Comment by milesalanmoore** [comment] 2022-03-25 01:25
An old issue-- but I am experiencing this now as well. I am calling the function to be able to set the working directory to the documents directory. The console outputs the exact same:

`> rstudioapi::getActiveDocumentContext()
Document Context: 
- id:        '#console'
- path:      ''
- contents:  <1 rows>
Document Selection:
- [1, 1] -- [1, 1]: ''`

For what it's worth to future users searching for this issue, `rstudioapi::getSourceEditorContext()` returns the correct path.
