### ISSUE TITLE
Feature Request: CMD to set working directory in terminal

### ISSUE THREAD

**Issue by slopp** [rstudio/rstudio#3721] opened 2018-10-21 17:49 UTC
Ideally, there would be an easy way to set the terminal working directory to R's working directory, similar to the options available for the Files Pane.

**Comment by gtritchie** [comment] 2018-10-22 04:16
Duplicate of #2363.

**Closed by gtritchie** 2018-10-22 04:16 UTC

**Comment by gtritchie** [comment] 2018-10-22 04:17
Duplicate of #2363
