### ISSUE TITLE
Rstudio desktop crashes upon startup after upgrading to Kubuntu 21.10 beta

### ISSUE THREAD

**Issue by bshor** [rstudio/rstudio#9882] opened 2021-09-24 04:48 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1717
    OS Version      : Kubuntu 21.10 beta
    R Version       : 4.1.1

### Steps to reproduce the problem

Upgraded Kubuntu 21.04 to 21.10 beta. 

### Describe the problem in detail

Hello, I just upgraded to Kubuntu 21.10 (impish) beta, which seems like it went fine. But RStudio desktop (running latest version) no longer works. The window comes up and it's just blank. There are no panes visible.

![image](https://user-images.githubusercontent.com/468070/134619685-739d4817-19f4-4a44-8ea0-953cdc2c7c88.png)

### Describe the behavior you expected

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report]([diagnostics-report.txt](https://github.com/rstudio/rstudio/files/7222920/diagnostics-report.txt)).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by fthx** [comment] 2021-09-24 07:51
I think it's a duplicate of:
https://github.com/rstudio/rstudio/issues/9854

**Comment by ronblum** [comment] 2021-09-24 13:33
Agreed, closing as a duplicate.

@bshor check out @fthx's workaround at https://github.com/rstudio/rstudio/issues/9854#issuecomment-926445284 which hopefully resolves this for now.

**Closed by ronblum** 2021-09-24 13:33 UTC
