### ISSUE TITLE
Assignment operator shortcut only inputs "=" symbol but not the "<-" symbol what can I do to change it?

### ISSUE THREAD

**Issue by ElmarEinars** [rstudio/rstudio#11879] opened 2022-08-31 12:19 UTC
Im on a MacBook and every time I'm trying to input the assignment operator it only inputs "=" symbol but not the "<-", how can I change that?

**Comment by ronblum** [comment] 2022-08-31 20:02
@ElmarEinars How are you trying to input the assignment operator, is it with the keyboard shortcut <kbd>Option -</kbd> or <kbd>Alt -</kbd>? Is this happening in the body of an R Markdown document, or is it in R Markdown code chunks or an R script?

**Comment by ronblum** [comment] 2022-08-31 20:06
This might be a duplicate of #11753. @ElmarEinars What keyboard layout are you using, and can you provide the following information?

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by ronblum** [comment] 2022-09-16 14:47
Closing this as a duplicate. Issue #11753 is happening with an Estonian keyboard layout, so if you're using another keyboard layout, please let us know!

**Closed by ronblum** 2022-09-16 14:47 UTC
