### ISSUE TITLE
RStudio crashes on Kubuntu 20.04

### ISSUE THREAD

**Issue by alaimos** [rstudio/rstudio#6727] opened 2020-04-24 15:00 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : Kubuntu 20.04
    R Version       : R 3.6.3

### Steps to reproduce the problem

The GUI is not working properly after an upgrade to Kubuntu 20.04. It get stuck on a blank screen when maximizing or resizing the window. As soon as the application get stuck, it can be closed only by killing it.

The same behavior happens with the latest Rstudio Preview and Daily build.

From the terminal I get the followind DUMP:

> ../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
> Received signal 11 SEGV_MAPERR 0000000000e6
> #0 0x7f7686217a4f <unknown>
> #1 0x7f7686217e4b <unknown>
> #2 0x7f76862184ce <unknown>
> #3 0x7f768b3d43c0 <unknown>
> #4 0x7f768727b863 <unknown>
> #5 0x7f7687283e4a <unknown>
> #6 0x7f768b3d43c0 <unknown>
> #7 0x7f7682459361 clock_nanosleep
> #8 0x7f768245eeb7 nanosleep
> #9 0x7f768622470b <unknown>
> #10 0x7f7686dfb3cb <unknown>
> #11 0x7f7686df6bb7 <unknown>
> #12 0x7f7686df6d38 <unknown>
> #13 0x7f7686e2f018 <unknown>
> #14 0x7f768876b222 <unknown>
> #15 0x7f768876b3ca <unknown>
> #16 0x7f768876b40b <unknown>
> #17 0x7f76861f14d3 <unknown>
> #18 0x7f7686224a10 <unknown>
> #19 0x7f768b3c8609 start_thread
> #20 0x7f768249b103 clone
>   r8: 00007f765bffe110  r9: 00007f765bffe0f0 r10: 00007f765bffe0d0 r11: 00007f765bffe0b0
>  r12: 00007f765bffe1c0 r13: 00007f765bffe170 r14: 0000000001738210 r15: 00007f765bffe1c0
>   di: 0000000000000001  si: 00007f765bffdfc0  bp: 00007f765bffe1a0  bx: 00000000000000e6
>   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000012  sp: 00007f765bffe170
>   ip: 00007f768727b863 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
>  trp: 000000000000000e msk: 0000000000000000 cr2: 00000000000000e6
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.

The diagnostic report from my setup:
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4529698/diagnostics-report.txt)

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-04-24 18:50
@alaimos Thank you for filing the issue! I'm unable to reproduce this on Kubuntu 20.04 LTS with R 3.6.3, both in RStudio Desktop 1.2.5042 and 1.3.947. However, thanks for including the diagnostics reports, etc. We'll review the issue as part of our continuing development of RStudio.

**Comment by gtritchie** [comment] 2020-04-26 21:44
The `failure in syscall 0230` strongly suggests this is related to issues with newer glibc, as mentioned here: #6379 

See similar conversation for Ubuntu 20.04 (#6723).

This fix for this is planned to be in the first 1.3-patch release, and is already the most current daily builds (1.4). In short, we took a new Qt release (5.12.8), specifically to address that issue, but deemed it too risky to take for the first 1.3 release.

**Comment by gtritchie** [comment] 2020-05-12 19:16
This is now fixed starting with daily build 1.4.325. The fix will also be in the first bug-fix release for 1.3 (known as 1.3-patch) but no builds available for that yet.

We will are not currently planning to fix this for RStudio 1.2 (any version).

**Closed by gtritchie** 2020-05-12 19:16 UTC
Labels: bug, desktop, linux
