### ISSUE TITLE
Legibility of auto-completion data preview in dark mode

### ISSUE THREAD

**Issue by quantixed** [rstudio/rstudio#12943] opened 2023-03-31 07:09 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386
    OS Version      : macOS 13.3
    R Version       :  R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"

### Steps to reproduce the problem

Problem occurs on clean install of RStudio using _Solarized Dark_ theme. Other settings: Modern theme, zoom 100%, Monaco, default Text rendering,  Editor font size 10.

### Describe the problem in detail

A completion feature was introduced recently to preview the column of data in a data frame while typing (love this feature!). I am using a "dark" theme. With this theme, each data point is previewed in a very light grey colour on a white rectangle ([example](https://fosstodon.org/@quantixed/110099691925192326)) which makes it very difficult to read.

### Describe the behavior you expected

A darker grey would help legibility and accessibility to those using dark themes.

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-03-31 07:27
@quantixed Thank you for bringing this over [from Masstodon](https://aus.social/@Dan/110076526017202403)! I was able to reproduce the issue. I'll mark it for review as we continue development of RStudio.

**Comment by ronblum** [comment] 2023-04-03 15:49
Marking as a duplicate of #12881. Sorry, @quantixed—I forgot that this had already been filed...!

**Closed by ronblum** 2023-04-03 15:49 UTC
Labels: bug, autocompletion
