### ISSUE TITLE
Double closing backtick is automatically inserted

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4532] opened 2019-03-28 09:39 UTC
**Steps to reproduce:**
* Enable autocompletions and closing quotes/parentheses/etc.
* Write two words (whether in the editor or the console) separated by a space.
* Add a backtick (`) at the beginning of the second word, and another backtick at the end.

**Expected behavior:** should insert one backtick at the end.

**Actual behavior:** inserts two backticks at the end, but not at the beginning. The problem is not present with other symbols such as quotes.

**Setup:** RStudio 1.2.1330, R 3.5.1, running on windows 10.

**Example:**
```r
first_word `second_word<try to put backtick here>
```

Turns into:
```r
first_word `second_word``
```

**Comment by pascaloettli** [comment] 2019-03-28 11:14
Similar issue opens [here](https://github.com/rstudio/rstudio/issues/2513)

**Comment by kevinushey** [comment] 2019-03-28 15:38
Closing as dupe of https://github.com/rstudio/rstudio/issues/2513.

**Closed by kevinushey** 2019-03-28 15:38 UTC
