### ISSUE TITLE
Close all files not working unless changes are made first in a file

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#8103] opened 2020-10-19 14:51 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.949
    OS Version      : ubuntu 18
    R Version       : 4.0.2

### Steps to reproduce the problem
1. open a new R script file but leave it empty
2. go to File -> Close All
### Describe the problem in detail
nothing happens
### Describe the behavior you expected
the file should be closed regardless if the user made changes

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment] 2020-10-19 17:33
This problem seems to be unique to linux - I could reproduce there but not on my mac (haven't tried windows).

**Comment by melissa-barca** [comment] 2020-10-19 22:22
Closed in #8109

**Closed by melissa-barca** 2020-10-19 22:22 UTC
Labels: backlog, bug

**Comment by kfeinauer** [comment] 2020-10-21 15:35
Verified fixed RStudio 1.4.954
