### ISSUE TITLE
2022.12.0 on Ubuntu: "crtl+ pageDown" doesn't work anymore to "Open Next Tab"

### ISSUE THREAD

**Issue by MatthieuStigler** [rstudio/rstudio#12488] opened 2022-12-22 09:49 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0
    OS Version      :  Ubuntu 20.04
    R Version       :  4.2.2

### Steps to reproduce the problem

Using `crtl+ pageDown` to switch tab doesn't work anymore on 2022.12.0, while it was working pretty much forever before. 

### Describe the problem in detail

Before Rstudio 2022.12.0, I could always use `crtl+ pageDown` to switch to right tab (or pagedown for left), even without altering the default shortcut of `ctrl+Tab` for "Open Next Tab". 

I realize that it was maybe an oddity that `crtl+ pageDown` was working on top of the default shortcut `ctrl+Tab`, but I am wondering whether that change in behavior was intended and whether it is necessary? I cannot see it mentioned in the version change News?

### Describe the behavior you expected

No silent deprecation of the shortcut `crtl+ pageDown` since it was accepted for many years. 

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-12-22 21:51
@MatthieuStigler Thank you for raising this! I can reproduce the problem in RStudio Desktop 2022.12.0+353, along with the original behavior in 2022.07.+576. This is true for both <kbd>Ctrl+PageUp</kbd> and <kbd>Ctrl+PageDown</kbd>. It's possible that the change is due to the switch to the Electron framework. We'll review this as we continue to develop RStudio.

Note: The previous behavior mimics the same behavior as with multiple tabs in other applications, such as Firefox and Terminal. The new behavior is the same as if <kbd>Ctrl</kbd> isn't being used—that is, the same as <kbd>PageUp</kbd> and <kbd>PageDown</kbd>.

**Comment by davidruegamer** [comment] 2023-02-11 22:56
Any updates or workarounds for this? It's quite an impediment to work efficiency for me...

**Comment by timtmok** [comment] 2023-07-05 20:18
https://github.com/rstudio/rstudio/blob/4c4a64f92cef7c9f30ad5530665dd2a0470e975b/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L773-L782

It appears to never have been bound to Ctrl+PgDown/PgUp. It might have been a keybinding conflict that was resolved when switching to Electron. I can confirm by building with Qt and Electron locally. Both show the keybinding as Ctrl+Tab and Ctrl+Shift+Tab for Next Tab and Previous Tab. However, Qt allows the mapped keybinding as well as Ctrl+Tab for Next Tab action. I'll close this since the keybinding is intended.

@davidruegamer You can re-map the keybinding for these actions in Tools -> Modify keyboard shortcuts.

**Closed by timtmok** 2023-07-05 20:18 UTC
Labels: bug, regression, source editor, key bindings
