### ISSUE TITLE
RStudio Freezes on Windows 10

### ISSUE THREAD

**Issue by csnardi** [rstudio/rstudio#5902] opened 2019-12-18 07:17 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5019
    OS Version      : Windows 10
    R Version       : 3.6.1

### Steps to reproduce the problem
I can't really tell how to reproduce this bug. It seems to happen spuriously; loading several libraries in might have something to do with it but I can't narrow it down to a certain set.

### Describe the problem in detail
After a while, RStudio will hang. There will be no way to interact with the terminal; the menu buttons on the toolbar still work however. The only way to get the terminal to work again is by terminating the R session or by restarting RStudio.

### Describe the behavior you expected
RStudio shouldn't randomly hang, requiring a restart of the program.

The diagnostic report I generated after a freeze is [in this gist](https://gist.github.com/csnardi/21954671e1d0a2edba2866c1c7a18b82). I tried switching to software rendering as suggested in another bug report, but the issue persists.

**Comment by ronblum** [comment] 2019-12-18 14:16
@csnardi Thank you for filing the issue! I haven't run into this it yet on Windows, but I'll keep an eye out for it. If you find reproducible steps, let us know so that we can try it, as well. In the meantime, I'll mark it for review, to see if the diagnostic report provides any insight.

**Comment by chasemc** [comment] 2019-12-18 15:44
I've been experiencing this as well. Spurious is definitely the right description but can definitively become annoying at times.  Seems to occur on my laptop most often when copying and pasting from outside RStudio into RStudio. Also, for me, usually it's the "Qt Qtwebengineprocess" that freezes.

**Comment by ronblum** [comment] 2019-12-18 15:59
@chasemc What versions of RStudio, Windows, and R are you using?

**Comment by csnardi** [comment] 2019-12-19 07:24
I do wonder if the clipboard is related; I've noticed some correlation there like @chasemc mentions but I tried e.g. copying a file which eventually resulted in a hang in once case but I couldn't reproduce with the same steps a second time.

**Comment by kevinushey** [comment] 2019-12-19 23:16
Switching rendering engines may help: https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors

**Comment by chasemc** [comment] 2020-01-07 22:15
@ronblum Looks like I'm running an old daily release of RStudio 1.3.251 so I'm not the best to follow up with probably . I'm in the middle of a bunch of work right now, but would be happy to downgrade to the latest stable release or upgrade to the latest daily and see if it continues.  Let me know which of those two would help more.

**Comment by csnardi** [comment] 2020-01-23 18:20
If there's any other reports I can run to help track down the cause of this, just let me know!

**Comment by jmcphers** [comment] 2020-04-27 23:25
Unfortunately we don't really have anything to go on here so I'm closing this. If it crops up again it'd be helpful to know (in a new issue):

1. Is this a busy hang (a process pegging a CPU core at 100% or near it)? If so, which process is pegging the CPU?
2. If it is not a busy hang, what does Process Explorer show for the stacks of the active threads? (see: https://superuser.com/questions/462989/how-can-i-view-the-call-stack-of-a-running-process-thread)?

**Closed by jmcphers** 2020-04-27 23:25 UTC
Labels: bug, triage, windows

**Comment by chasemc** [comment] 2020-04-27 23:29
Thanks @jmcphers, I've moved completely to Linux for other reasons so can't follow up

**Comment by csnardi** [comment] 2020-04-28 00:19
I've been using the 1.3 preview, and the hangs seem to have gone away.
