### ISSUE TITLE
IDE Terminal Unable to Use after Installing RTools

### ISSUE THREAD

**Issue by dipterix** [rstudio/rstudio#7197] opened 2020-06-23 07:07 UTC
# System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Windows10
    R Version       :  R-4.0.2

### Steps to reproduce the problem

1. Install Git bash [https://gitforwindows.org/](https://gitforwindows.org/)
2. Follow [https://cloud.r-project.org/bin/windows/Rtools/](https://cloud.r-project.org/bin/windows/Rtools/) to install `rtools`
3. Add `rtools40` to PATH environment variable, save to `~/.Renviron` (IMPORTANT)
4. Open RStudio `Terminal` tab
5. Type `ls`

### Describe the problem in detail

Because rtools40 was added to ~/.Renviron, terminal will first search its path for commands. However, those commands are incompatible with Git Bash, resulting in error.

This should be no problem if I set terminal option and let Windows Prompt to be my default tools, or manually set `PATH` and remove rtools40. However, RStudio's default is Git Bash, and `PATH` is contaminated for normal users after installing rtools following CRAN guidelines.

### Describe the behavior you expected

You should be able to see the following error in `Terminal`

```
$ ls
      1 [main] ls (11688) C:\rtools40\usr\bin\ls.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x180316408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2020-06-23 16:10
This is a duplicate of #6828.

Fixed in latest preview release: https://rstudio.com/products/rstudio/download/preview/

**Closed by gtritchie** 2020-06-23 16:10 UTC
Labels: duplicate, terminal
