### ISSUE TITLE
The "x" signs to close the tabs can be dragged into source code panes

### ISSUE THREAD

**Issue by datafj** [rstudio/rstudio#10269] opened 2021-12-20 20:58 UTC
### System details

    RStudio Edition : Server 
    RStudio Version : 2021.09.1 Build 372
    OS Version      :  Ubuntu 20
    R Version       :  4.1.2

### Steps to reproduce the problem

1. Move mouse over the "x" sign to any tab of source code
2. Press down the left button and hold it
3. Move the mouse to the text area of any source code pane
4. Release the mouse button

### Describe the problem in detail

The base64 code of the image of the "x" sign will show up in the source code pane:

<code>
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAWElEQVR42mNgGPTAxsZmJsVqQApgmGw1yApwKcQiT7phRBuCzzCSDSHGMKINIeDNmWQlA2IigKJwIssQkHdINgxfmBBtGDEBS3KCxBc7pMQgMYE5c/AXPwAwSX4lV3pTWwAAAABJRU5ErkJggg==
</code>

### Describe the behavior you expected

The "x" sign should not be draggable.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-12-21 14:31
@datafj Thank you for raising the issue! What browser are you using to connect to RStudio Server, and is it also on Ubuntu 20.04?

**Comment by datafj** [comment] 2021-12-21 14:35
@ronblum I use Brave on Windows 10. RStudio sever is running on a separate machine in the same local network. Thanks!

**Comment by ronblum** [comment] 2021-12-21 14:59
Interesting. Do you have any other browsers installed—Edge, Safari, or Chrome—that you'd be willing to try it on? Thanks!

**Comment by datafj** [comment] 2021-12-21 15:47
@ronblum I just tested on Edge, Chrome, and Firefox, and the same behavior can be reproduced on all of them.

**Comment by ronblum** [comment] 2021-12-21 19:23
@datafj Thank you for checking them all! I'll try to reproduce with them, since I don't have Brave. Much appreciated!

**Comment by ronblum** [comment] 2021-12-22 14:07
Reproduced in R markdown in visual mode:
- RStudio Desktop 2022.02.0-daily+290 on Windows 10
- RStudio Server 2022.02.0-daily+335 on Ubuntu 20.04 via Chrome on Windows 10
- RStudio Desktop 2022.02.0-daily+335 on MacOS 12.1
- RStudio Server 2022.02.0-daily+335 on Ubuntu 20.04 via Chrome on MacOS 12.1

**Comment by mikebessuille** [comment] 2022-01-03 18:27
That's really strange behaviour!  Thank you for logging this issue.  As the result is benign, easy for the user to undo, and given that we have a large backlog of urgent issues, I'm going to close this.  If worse symptoms arise from this, please comment on the issue and we can reconsider.

**Closed by mikebessuille** 2022-01-03 18:27 UTC
Labels: bug, reproducible, source editor
