### ISSUE TITLE
Function signatures in help pane are hard to read with dark themes

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#11172] opened 2022-05-10 20:33 UTC
This is hard to read and coloring the equals signs differently makes it harder:
![function_signatures](https://user-images.githubusercontent.com/11860098/167716858-6c46f697-95e8-4462-8484-c73af4838d45.png)

(This is on linux with Sky theme)

**Comment by kevinushey** [comment] 2022-05-10 20:45
Thanks for reporting -- this is a duplicate of https://github.com/rstudio/rstudio/issues/10839 and should already be fixed in the latest daily builds.

**Closed by kevinushey** 2022-05-10 20:45 UTC
