### ISSUE TITLE
rmarkdown files: option to Run All Previous Chunks while respecting 'eval' options

### ISSUE THREAD

**Issue by aljabadi** [rstudio/rstudio#7622] opened 2020-08-20 03:44 UTC
Thanks for the amazing project.

When running Run All Previous Chunks, by definition it runs all previous chunks, but I was hoping that there would be a way/option to do so while respecting the `eval` chunk option as it makes it so much easier to tweak the code down the line without having to comment out all chunks which are required, say, in other environments.  For instance, consider the following case where I want to tweak the plots in the last chunk:

<pre>
---
title: "Run All Prevoious Chunks to respect 'eval' options"
output: html_document
---

```{r setup}
library(knitr)
## we want to avoid re-running if the output is already saved
## it is obviously an example and certainly not a warranted approach
load_intensive_function_outputs <- file.exists('cars.rds')
run_intensive_function <- !load_intensive_function_outputs
```

# Data

```{r run, echo=TRUE, eval=run_intensive_function}
## I want my report to show this chunk at all times
intensive_function <- function() {
  cat('intensive run in progress!\n')
  for (i in 5:1) {
    cat('hang on', i, ' seconds ...\n')
    Sys.sleep(1)
  }
  cars
}
carz <- intensive_function()
## save output of intensive_function on local machine:
saveRDS(carz, file='cars.rds')
```

```{r load, echo=FALSE, eval=load_intensive_function_outputs}
## I never want this chunk echoed in the report, but I want it it to run
## when desired 
carz <- readRDS('cars.rds')
```

[lengthy sections with a lot of parametric eval options]

# Results

Here's where I want to press 'Run All Chunks Above' and hope to load data on my machine, 
as opposed to run from scratch so I can just get to the visulisation part:

```{r}
plot(carz)
```

```{r}
## cleanup
unlink('cars.rds')
```

</pre>

With Run All Previous Chunks, the consuming function will run. It would be great if there was a less manual way to reproduce the 'knit' environment up to the plot chunk without lots of manual runs.

I understand that the following is a workaround:
```r
if (load_intensive_function_outputs) {
  load
}
```

```r
if (run_intensive_function) {
  run
}
```

But it defeats the purpose of a nice report.

Thanks in advance.

**Comment by ronblum** [comment] 2020-08-20 20:40
@ajabadi Thank you for filing the issue and the code sample! I'll mark it as an enhancement, for review as we continue development of RStudio.

**Comment by cderv** [comment] 2020-08-21 08:38
FWIW I think this is also related to https://github.com/rstudio/rstudio/issues/6675

It would be a nice improvement taht this works for better experience with conditional Rmd files.

**Comment by R-Hannibal** [comment] 2021-02-12 20:08
Closing this as a duplicate of https://github.com/rstudio/rstudio/issues/6675.

**Closed by R-Hannibal** 2021-02-12 20:08 UTC
Labels: enhancement, r markdown, triage
