### ISSUE TITLE
Support R4.2.0: adapt to Windows memory limit changes

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9792] opened 2021-08-30 18:20 UTC
https://github.com/wch/r-source/commit/a984cc29b9b8d8821f8eb2a1081d9e0d1d4df56e

Need to assess if this effects how RStudio works on Windows with R 4.2.0 (currently in development), and adapt if need be.

**Comment by gtritchie** [comment] 2021-09-27 23:54
Also R 4.2 is planning to drop support for 32-bit Windows. We'll need to ensure we don't present 32-bit sessions as an option for R 4.2 on Windows.

**Comment by kevinushey** [comment] 2021-11-23 21:34
For testing, it should suffice to validate that RStudio can launch and use the latest development builds of R without issue. Those can be downloaded here:

https://r-devel.github.io/

**Comment by R-Hannibal** [comment] 2021-11-30 18:29
@kevinushey - when it comes to using the latest development builds of R 'without issue.', seems like I'm having some issues. Not sure if this is expected with a new development build of R or not:

While RStudio is starting up fine and I can switch to the new R-devel version (`R Under development (unstable) (2021-11-30 r81263) -- "Unsuffered Consequences"`), I don't appear to be able to update or install certain packages (like `shiny` for example) while using this new r version. Including below the errors I'm getting in the console when attempting to install the shiny package, not sure if this is expected with an in development r version or if these are issues that need to be resolved before this issue can be considered verified -

**Comment by kevinushey** [comment] 2021-11-30 19:49
I wasn't able to reproduce this locally; the `withr` package installs without issue. That said, I think you caught a couple things we need to take care of. Here's my version of the build output:

```
installing the source package 'withr'

trying URL 'https://cran.rstudio.com/src/contrib/withr_2.4.3.tar.gz'
Content length 96600 bytes (94 KB)
downloaded 94 KB

* installing *source* package 'withr' ...
** package 'withr' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'withr'
    finding HTML links ... done
    defer                                   html  
    devices                                 html  
    makevars_user                           html  
    set_makevars                            html  
    with_                                   html  
    with_collate                            html  
    with_connection                         html  
    with_db_connection                      html  
    with_dir                                html  
    with_envvar                             html  
    with_file                               html  
    with_gctorture2                         html  
    with_language                           html  
    with_libpaths                           html  
    with_locale                             html  
    with_makevars                           html  
    with_options                            html  
    with_package                            html  
    with_par                                html  
    with_path                               html  
    with_rng_version                        html  
    with_seed                               html  
    with_sink                               html  
    with_temp_libpaths                      html  
    with_tempfile                           html  
    with_timezone                           html  
    withr                                   html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (withr)

The downloaded source packages are in
	'C:\Users\kevin\AppData\Local\Temp\RtmpGgPJfJ\downloaded_packages'
```

Your output has:

```
Warning in install.packages :
  the 'wininet' method is deprecated for http:// and https:// URLs
```

And indeed, we try to force the use of wininet on Windows in some contexts; e.g.

```
> .rs.secureDownloadMethod()
[1] "wininet"
```

I believe we'll need to update that to use `libcurl` with newer versions of R.

```
*** arch - i386
Error in `::`(base, quote) : could not find function "::"
Calls: <Anonymous>
Execution halted
```

The development versions of R do not come with 32-bit builds; did you install R-devel over a previously-existing copy of R-devel? It's surprising to me that R is trying to build a 32-bit copy of the package here.

**Comment by kevinushey** [comment] 2021-11-30 19:49
Filed https://github.com/rstudio/rstudio/issues/10163 to track the change for "wininet".

**Comment by R-Hannibal** [comment] 2021-11-30 22:27
Yup, I installed over an old version of R-devel that I had on the system that included 32 bit. 

Not sure if it's related to that but I also noticed the very odd behavior of: If I don't have R-devel selected as my current R version, I only see one listing of R-devel in Tools > Global Options > General > R version:

![r_devel_1](https://user-images.githubusercontent.com/62304541/144138056-7b7252a6-eada-4f34-90e7-2f2e50f3926d.PNG)

But once I select R-devel as my R version, I now get a 2nd R-devel listing in the dropdown menu:

![r_devel_2](https://user-images.githubusercontent.com/62304541/144138148-a48256f3-07cc-44ec-ab3a-46dcbd04e34d.PNG)

**Comment by kevinushey** [comment] 2021-12-01 01:48
That seems relatively minor, but it could be worth filing a separate issue for? That should ultimately be unrelated to the associated PR, though.

**Comment by R-Hannibal** [comment] 2021-12-01 21:28
Sorry @kevinushey, more questions before I feel confident closing this.

Trying to check more general functionality and I ran into what seems like another R 4.2.0 specific issue - Plots won't display in the plots pane using R 4.2.0. Entering a plot command in the console results in the following message and the plot displaying in an external window:

```
> plot(cars)
Warning message:
R graphics engine version 15 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed.
```

Not having this issue with any other R version that I've checked. Should I close this issue because RStudio will in fact launch on windows with 4.2.0 and for the most part work (then file the plots issue and any others I've noticed as separate tickets)?

**Comment by jmcphers** [comment] 2021-12-01 22:26
@R-Hannibal The plot issue is known, and tracked here: https://github.com/rstudio/rstudio/issues/10058

**Comment by R-Hannibal** [comment] 2021-12-02 20:00
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 2022.01.0-daily+259
    OS Version      : Windows 10
    R Version       : 4.2.0

### Summary
Verified that RStudio will launch with R 4.2.0 and basic IDE functionality is intact. Also confirmed that we do not present 32 bit R 4.2.0 as an option in the R version selector as this is no longer supported in R 4.2.0.

### Automation
- No automation tests created. Our current framework does not support running E2E automated tests against desktop, though we have a ticket open to explore adding this capability - https://github.com/rstudio/rstudio-ide-automation/issues/147

### Notes
-Ran into a couple issue while testing this ticket, but they are being tracked separately: [Plots pane not working with R 4.2.0](https://github.com/rstudio/rstudio/issues/10058), and issues installing certain packages due to R 4.2.0's [deprecation of the wininet download method](https://github.com/rstudio/rstudio/issues/10163).

**Closed by R-Hannibal** 2021-12-02 20:00 UTC
Labels: developer, r versions, test

**Comment by ronblum** [comment] 2022-01-13 17:45
Note: Verified the backport in Ghost 2021.09.2+382.
