### ISSUE TITLE
R session failed to start with `r-devel` UCRT

### ISSUE THREAD

**Issue by pcdi** [rstudio/rstudio#10065] opened 2021-11-10 11:21 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-08) for Windows
    OS Version      : x86_64-w64-mingw32/x64 (64-bit) Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    R Version       : R Under development (unstable) (2021-11-09 r81170 ucrt) -- "Unsuffered Consequences"

### Steps to reproduce the problem
- Install the Windows UTF-8 (UCRT) development Version of R from [here](https://www.r-project.org/nosvn/winutf8/ucrt3/) (see also the [installation info blog post](https://developer.r-project.org/Blog/public/2021/03/12/windows/utf-8-toolchain-and-cran-package-checks/index.html))
- Set RStudio to use the `r-devel` version (hold down <kbd>Ctrl</kbd>, double-click `rstudio.exe`, select `r-devel`)
- RStudio starts with a blank screen
- The next time RStudio is opened (without manually selecting the R version via <kbd>Ctrl</kbd> clicking), it will show an actual error message: 

### RStudio Version

RStudio 2021.09.1+372, "Ghost Orchid" (8b9ced18, 2021-11-08) for Windows

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Error message

[No error available]

### Process Output

The R session exited with code -1073740791. 

Error output:

```
[No errors emitted]
```

Standard output:

```
[No output emitted]
```

### Describe the behavior you expected

RStudio should be able to start with an R development version, specifically with the UTF-8 UCRT build.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2021-11-10 17:09
See also: https://github.com/rstudio/rstudio/issues/9824

**Comment by mikebessuille** [comment] 2021-11-15 20:12
Duplicate of #9824

**Closed by mikebessuille** 2021-11-15 20:12 UTC
Labels: bug, duplicate, r versions
