### ISSUE TITLE
resolve intermittent failure to launch with development electron builds on Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10694] opened 2022-02-28 18:09 UTC
I see this about 10% of the time when trying to run RStudio on Windows via `npm start`:

<img width="568" alt="Screen Shot 2022-02-28 at 10 02 03 AM" src="https://user-images.githubusercontent.com/1976582/156034587-c7bc7835-87dc-49f8-acbf-ee95817a64bb.png">

Logging for posterity in case I see it again (or anyone else sees it).

**Comment by kevinushey** [comment] 2022-02-28 19:09
It seems to be occurring in the following JS:

```
/***/ "./src/native/desktop.node":
/*!*********************************!*\
  !*** ./src/native/desktop.node ***!
  \*********************************/
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {

module.exports = require(__webpack_require__.ab + "desktop.node")
```

implying that `__webpack__require__.ab` is `undefined`, for some reason.

On macOS, I see:

```
kevin@MBP-P2MQ:~/rstudio/src/node/desktop/.webpack [main]
$ rg -F "__webpack_require__.ab"
renderer/error_window/index.js
978:/******/    if (typeof __webpack_require__ !== 'undefined') __webpack_require__.ab = "/Users/kevin/rstudio/src/node/desktop/.webpack/renderer" + "/native_modules/";

renderer/main_window/index.js
796:/******/    if (typeof __webpack_require__ !== 'undefined') __webpack_require__.ab = "/Users/kevin/rstudio/src/node/desktop/.webpack/renderer" + "/native_modules/";

renderer/choose_r/index.js
1088:/******/   if (typeof __webpack_require__ !== 'undefined') __webpack_require__.ab = "/Users/kevin/rstudio/src/node/desktop/.webpack/renderer" + "/native_modules/";

renderer/loading_window/index.js
978:/******/    if (typeof __webpack_require__ !== 'undefined') __webpack_require__.ab = "/Users/kevin/rstudio/src/node/desktop/.webpack/renderer" + "/native_modules/";

renderer/connect_window/index.js
978:/******/    if (typeof __webpack_require__ !== 'undefined') __webpack_require__.ab = "/Users/kevin/rstudio/src/node/desktop/.webpack/renderer" + "/native_modules/";

main/index.js
44074:module.exports = require(__webpack_require__.ab + "desktop.node")
49570:/******/  if (typeof __webpack_require__ !== 'undefined') __webpack_require__.ab = __dirname + "/native_modules/";
```

Next time this pops up, I'll see if the generated webpack code seems incorrect somehow.

**Comment by gtritchie** [comment] 2022-05-26 15:12
Do we need an issue tracking this? It won't impact users and it's an IDE dev workflow thing (and by design, for all intents and purposes).

**Comment by mikebessuille** [comment] 2022-05-26 15:37
Ahhhh!  I didn't gather initiallly that this is a developer workflow thing.  In that case... either it should be in tech debt, or... closed?

**Comment by mikebessuille** [comment] 2022-10-21 18:07
I don't think we're going to spend the time to fix this, and it only affects developers.  Tim suggests closing it.

**Closed by mikebessuille** 2022-10-21 18:07 UTC
Labels: tech debt, electron
