### ISSUE TITLE
ggrepel text labels disappear in Rmd chunk "Show in New Window"

### ISSUE THREAD

**Issue by slowkow** [rstudio/rstudio#4330] opened 2019-02-19 18:26 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.463 
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Open the attached Rmd file in RStudio.
2. Run the chunk to display the plot.
3. Click the **Show in New Window** button.

### Describe the problem in detail

When I click the **Show in New Window** button in my Rmd file, the text labels disappear in the plot shown in the new window.

<img width="153" alt="Show in New Window" src="https://user-images.githubusercontent.com/209714/53038012-ac54b400-3449-11e9-838b-d03a82829ffe.png">

Here is a video demonstrating the problem: https://vimeo.com/318265708#t=52s

Here is the Rmd file, so you can try it on your own computer:

````rmd
---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r ggrepel-issue-121}
library(ggplot2)
library(ggrepel)
library(dplyr)

ggdata <- diamonds %>% 
  group_by(cut) %>% 
  summarise_at(vars(depth, table), mean)

ggdata %>% 
  ggplot() +
  geom_point(aes(x = depth, y = table)) +
  geom_text_repel(aes(x = depth, y = table, label = cut))
```
````

This issue was originally reported here:

https://github.com/slowkow/ggrepel/issues/121

### Describe the behavior you expected

The labels do appear as expected in every other case I've tested.

For example, if you plot to the Viewer Pane, it works. Then, if you click **Zoom** on the Viewer Pane to get a new window, it also works as expected.

Only the **Show in New Window** button does not work.

<details>
<summary>sessionInfo()</summary>
<pre>
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.0   ggrepel_0.8.0 ggplot2_3.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       rstudioapi_0.9.0 knitr_1.21       magrittr_1.5    
 [5] tidyselect_0.2.5 munsell_0.5.0    colorspace_1.4-1 R6_2.3.0        
 [9] rlang_0.3.1.9000 plyr_1.8.4       tools_3.5.1      grid_3.5.1      
[13] gtable_0.2.0     xfun_0.4         withr_2.1.2      yaml_2.2.0      
[17] lazyeval_0.2.1   assertthat_0.2.0 tibble_2.0.1     crayon_1.3.4    
[21] purrr_0.3.0      glue_1.3.0       labeling_0.3     compiler_3.5.1  
[25] pillar_1.3.1     scales_1.0.0     pkgconfig_2.0.2 
</pre>
</details>

**Comment by kevinushey** [comment] 2019-02-19 19:03
Did you try the [preview release](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by slowkow** [comment] 2019-02-19 19:09
Yes, I get the same behavior with RStudio 1.2.1280

**Comment by kevinushey** [comment] 2019-02-19 19:28
Thanks! You can see the same issue if you resize the IDE surface as well (which forces a re-rendering of the underlying graphic).

![repel](https://user-images.githubusercontent.com/1976582/53041656-5ed04b00-3439-11e9-8d45-818474b34cca.gif)

@jmcphers can you think of anything off-hand which might be causing this? IIRC we're just saving / loading the state of the graphics device when the chunk has finished executing, so I wonder why text in this case is being missed. (Note that things work fine for such plots in the Plots pane; it's specifically for chunk output where this text is lost after a resize).

**Comment by kevinushey** [comment] 2019-02-19 21:29
I think I figured out what's going on. You can reproduce the behavior with the following. First, in one R session, save the plot:

```r
library(ggplot2)
library(ggrepel)
library(dplyr)

ggdata <- diamonds %>% 
   group_by(cut) %>% 
   summarise_at(vars(depth, table), mean)

plot <- ggdata %>% 
   ggplot() +
   geom_point(aes(x = depth, y = table)) +
   geom_text_repel(aes(x = depth, y = table, label = cut))

recorded <- grDevices:::recordPlot()
saveRDS(recorded, file = "~/scratch/plot.rds")
```

Then, in a separate R session, load and replay the plot:

```r
loaded <- readRDS("~/scratch/plot.rds")
print(loaded)
```

The problem is, when the saved plot is replayed, `ggrepel` is not loaded and so the text is (silently?) no longer plotted. Note that RStudio does the moral equivalent of this behind the scenes when replaying chunk plots.

**Comment by kevinushey** [comment] 2019-02-19 21:35
Note that `recordPlot()` also takes a list of loaded + attached packages to be used as dependencies for a particular plot object, and `replayPlot()` also accepts a `reloadPkgs` argument to specify if the package dependencies should be loaded + attached, so perhaps there is some extra orchestration that needs to happen here.

**Comment by paullevchuk** [comment] 2020-01-31 13:36
Any updates about this bug?

**Comment by coffee-and-genomics** [comment] 2020-03-24 20:45
Still having this issue on:

- macOS v10.15.3
- RStudio v1.2.5033
- ggrepel v0.8.2

**Comment by dsolito** [comment] 2020-12-13 15:28
I got the same problem.

**Comment by LukasWallrich** [comment] 2021-01-20 13:09
Just to highlight that this is the case across platforms: I face the same issue in RStudio Server based on the rocker image.

**Comment by AlbertRapp** [comment] 2021-05-13 09:47
This is still an issue.

**Comment by davidyanglee** [comment] 2021-05-27 18:56
Anyone found a solution to this bug?

**Comment by denvercal1234GitHub** [comment] 2021-05-30 15:18
My friend told me about the workaround for this issue. 

Just take the code and run it in the Console to get the plots in the Plots panel of RStudio.

**Comment by alankjackson** [comment] 2021-07-19 22:44
Yeah, still a problem.

**Comment by Jacqland** [comment] 2021-09-28 20:53
This is still an issue for me, both with ggrepel and ggdist packages. For the latter, dots created by stat_dots also disappear in plots if you resize the window or click "show in new window"

**Comment by alankjackson** [comment] 2022-05-26 03:03
Still seems to be an issue, RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for Ubuntu Bionic
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by massisnascimento** [comment] 2022-08-12 23:04
This is still an issue 3.5 years later :/

**Comment by ozgunozankilic** [comment] 2023-03-10 23:10
Still a problem.

**Comment by alankjackson** [comment] 2023-06-07 21:39
This is the never-ending issue.

**Comment by kevinushey** [comment] 2023-06-07 23:04
The hard part here is figuring out what packages are required to re-generate a plot based only on the object returned by `recordPlot()`, since we try to restore these plots in an R sub-process. `?recordPlot` even has:

>     Replay of a recorded plot may not produce the correct result (or
>      may just fail) if the display list contains a call to
>      'recordGraphics' which in turn contains an expression that calls
>      code from a non-base package other than 'graphics' or 'grid'.  The
>      most well-known example of this is a plot drawn with the package
>      'ggplot2'.  One solution is to load the relevant package(s) before
>      replaying the recorded plot.  The 'load' and 'attach' arguments to
>      'recordPlot' can be used to automate this - any packages named in
>      'load' will be reloaded, via 'loadNamespace', and any packages
>      named in 'attach' will be reattached, via 'library', as long as
>      'reloadPkgs' is 'TRUE' in the call to 'replayPlot'.  This is only
>      relevant when attempting to replay in one R session a plot that
>      was recorded in a different R session.

I'm not sure if packages have some way of recording a plot's dependencies directly into the plot itself; I suspect not, though.

**Comment by kevinushey** [comment] 2023-07-31 17:07
@teunbrand: thank you; this is incredibly helpful to know!

I've filed a feature request on R Core's side to see if there's anything that could be done in the `grid` package, to help ensure that the packages required to generate a plot are recorded as part of the plot metadata. https://bugs.r-project.org/show_bug.cgi?id=18573

**Comment by ronblum** [comment] 2023-08-07 11:53
Verified fixed in RStudio Desktop 2023.09.0-daily+301 on MacOS 13.5. Checked with both:
1. Opening a new window
2. Resizing the Editor Pane

**Closed by ronblum** 2023-08-07 11:53 UTC
Labels: bug

**Comment by mjskay** [comment] 2023-08-07 21:39
This fix does not seem to work for {ggdist} (as reported upthread) since only {ggforce} and {ggrepel} are hardcoded here:

**Comment by kevinushey** [comment] 2023-08-07 22:08
@mjskay, I've put together a more general fix in https://github.com/rstudio/rstudio/pull/13466.

**Comment by mjskay** [comment] 2023-08-07 22:38
Awesome, thanks so much! :)
