### ISSUE TITLE
Resizing or even clicking console border moves focus to the end

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8544] opened 2020-12-05 13:00 UTC
**Steps to reproduce:**
* Print enough output in the console so as to make it scrollable.
* Scroll to the middle of the console output.
* Hover the mouse around the border of the console pane from which it's possible to resize it by dragging a left click.
* Click the border, but don't even move the mouse (so as not to resize anything).

**Expected behavior:** should do nothing, and resizing should ideally maintain the focus.

**Actual behavior:** focus moves to the end.

**Setup:** RStudio 1.4.1078.

**Comment by ronblum** [comment] 2020-12-08 15:38
@david-cortes I can reproduce this using RStudio 1.4.1078 on MacOS 11.1. I believe you use Debian and Windows? Which would mean the issue occurs in RStudio Desktop on multiple operating systems.

Note: This is not an issue in RStudio Server, using Safari, Chrome, and Firefox on MacOS 11.1.

**Comment by mikebessuille** [comment] 2020-12-08 16:24
Until this past weekend, the console had "Limit console display to a subset of total content" enabled by default.  As of this weekend it is disabled by default.  Can you verify which setting you had when you encountered this issue?

**Comment by adamconroy** [comment] 2020-12-08 21:38
@ronblum im moving to juliet rose on the basis that it's like due to the Limit feature that we have turned off, can you confirm?

**Comment by ronblum** [comment] 2020-12-08 23:13
Confirmed! Turning off the option makes the problem go away. The problem returns when when it's turned back on.

**Comment by valerie-rstudio** [comment] 2021-01-28 17:10
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1527
    OS Version      :  mac OS 11.1
    R Version       :  4.0.2

Verified that when user attempts to resize console, the console maintains users scroll position with the Limit Console Output option either on or off.

**Closed by valerie-rstudio** 2021-01-28 17:10 UTC
Labels: bug, console, regression, test
