### ISSUE TITLE
RStudio opens unexpected nested data from "View" when filtered from search bar with magnifying glass

### ISSUE THREAD

**Issue by raykrajci** [rstudio/rstudio#15041] opened 2024-08-06 20:19 UTC
### System details

RStudio Edition: Both
RStudio Version: 

- Desktop: RStudio 2024.04.2+764 "Chocolate Cosmos" Release (e4392fc9ddc21961fd1d0efd47484b43f07a4177, 2024-06-05) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.2+764 Chrome/120.0.6099.291 Electron/28.3.1 Safari/537.36, Quarto 1.4.554 (C:/Users/Ray/AppData/Local/Programs/Quarto/bin/quarto.exe)
- Server: RStudio 2024.04.999-dev+999 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-04-10) for Linux
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

OS Version:

- Desktop: x86_64-w64-mingw32/x64
- Server: x86_64-pc-linux-gnu

R Version: R version 4.4.0 (2024-04-24) -- "Puppy Cup"

### Steps to reproduce the problem

1. `library(tidyverse)`
2. Create data with `data <- tibble::tribble(~id, ~data, "A", "A1", "A", "A2", "B", "B1", "B", "B2")`: 
![image](https://github.com/user-attachments/assets/4461aaba-4f80-4f2f-8e08-a562fc306f52)
4. Nest data with `nested_data <- data %>% tidyr::nest(data = data)`
5. View nested data in RStudio with `View(nested_data)` in the console or by clicking the table icon in the "Environment" pane: 
![image](https://github.com/user-attachments/assets/16ff6fa6-aac4-47f5-a5ba-7591b9311de8)
6. In the "View" pane which opens to show the data, put the letter 'B' into the search bar with the magnifying glass. This should filter out the row with "A" in `id` from the view: ![image](https://github.com/user-attachments/assets/4c82eba7-e5c8-4ac6-b321-1002db5c095e)
7. Hover over the table icon in the "View" pane in the `data` column for the row with "B" in `id`. This will show the expected contents of the cell: `list(data = c("B1", "B2"))`: 
![image](https://github.com/user-attachments/assets/502df1cb-e91b-4d47-ae48-ef802e591bd4)
8.  Click on the the table icon in the "View" pane in the `data` column for the row with "B" in `id`. This will run `View(nested_data[[2]][[1]])` in the Console pane and open the "View" pane: 
![image](https://github.com/user-attachments/assets/3579242e-ba20-445c-bbd5-2cf853ee4037)

### Describe the problem in detail

All indications from the GUI are that clicking on the table icon for the nested data in the "View" pane will show me the "B" nested data - that is, I have filtered the "A" row out of the view using the search bar and when I hover over the icon, the popup shows the nested "B" data.

However, when you do click on the table icon Rstudio runs the command `View(nested_data[[2]][[1]])` which opens the "A" data, when it should have run `View(nested_data[[2]][[2]])` to open the "B" data based on what I saw.

I speculate that RStudio does not take into account what is shown when the search bar with the magnifying glass is used to filter out rows.

### Describe the behavior you expected

I expected that when I clicked on the table icon for the nested data, I would open the "B" data that I see in the filtered view.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists. ((NOTE: Only for desktop, I am not admin of our server instance))
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-08-20 15:13
@raykrajci Thank you for raising the issue! I can reproduce this in multiple versions of RStudio, going at least as far back as RStudio Desktop 2022.07.2+576.  I think that this is a duplicate of a previous issue, #9960. Would you agree?

**Comment by raykrajci** [comment] 2024-08-20 15:19
@ronblum yep, that seems to be the same. Sorry for the duplicate!

**Comment by ronblum** [comment] 2024-08-20 15:22
@raykrajci No problem at all! It took me a bit of searching to find it, and even that only because it rang a bell. I'll close this one as a duplicate and re-raise the bug for consideration.

**Closed by ronblum** 2024-08-20 15:22 UTC
Labels: bug, data viewer

**Comment by ronblum** [comment] 2024-08-20 15:23
Also, thank you for the very precise step-by-step example--it made it easy to see the problem without even have to think. 🙂

**Comment by ronblum** [comment] 2024-08-28 16:39
Verified in RStudio Desktop 2024.10.0-daily+106 (see #9960).

**Comment by rweberc** [comment] 2024-08-28 19:53
Appreciate all the attention this issue is getting, especially since, outside of test data frames where it's easier to identify that an unexpected row's data is being displayed, it really can lead to arriving at incorrect conclusions about data being inspected.

As mentioned above, I created an issue for this issue in 2020 (#7546) and have seen it go through a number of iterations of feedback since then, going stale, being closed, and being re-flagged again several times.  As the internal note might indicate above, it may not be a trivial matter to resolve.  For that reason, I wonder (if it turns out resolving it in the short-term is not likely) that it would make sense to disable the detail view when filters are applied.  Obviously, much more useful to be able to filter to the correct row and dig into the details, but if that becomes very difficult, at least the interim disabling would prevent users from misinterpreting their data sets.

Thanks again for all the work on this and related issues.

**Comment by ronblum** [comment] 2024-08-28 20:05
@rweberc I think that this is fixed. I checked your original post in #7546, and this is what I see. Can you confirm that it's correct?
![image](https://github.com/user-attachments/assets/166452f0-0d70-47d1-a28b-3f74f3b1a4e5)
