### ISSUE TITLE
Ligature font doesn't render in Microsoft Edge

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#8519] opened 2020-12-02 18:33 UTC
Hi everyone,

I have a problem with ligature font. While I try to set a default font for the source code is JetBrains Mono, it worked well to render a book and preview in Rstudio. However, when I open it in Microsoft Edge, the ligature font doesn't display. Could you please help me fix this problem

Here is in R previewer:
![image](https://user-images.githubusercontent.com/63569637/100915903-4d084c80-34d5-11eb-87e7-15dd99887844.png)

But when I open it in Microsoft Edge, it fail to display ligature font here:

![image](https://user-images.githubusercontent.com/63569637/100915924-585b7800-34d5-11eb-86ac-20ae27362e4e.png)

**Comment by cderv** [comment] 2020-12-02 18:38
For reference this is has also been posted here https://github.com/rstudio/bookdown/issues/1037 as a duplicate

**Comment by ntluong95** [comment] 2020-12-02 18:42
@cderv Sorry about that. Do you know about the issues?

**Comment by jmcphers** [comment] 2020-12-02 20:22
This is not a bug in the IDE so closing it here.

**Closed by jmcphers** 2020-12-02 20:22 UTC
