### ISSUE TITLE
[Windows] Non-local file paths (UNC) generated through RStudio autocomplete are not valid for R (should use forward slashes)

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#5096] opened 2019-07-12 12:36 UTC
This is perhaps the root cause behind other issue -> https://github.com/rstudio/rstudio/issues/5089

**Steps to reproduce:**
* Have RStudio autocomplete a path in a non-local user folder.
* Pass that path that RStudio produced to some R function.

**Expected behavior:** autocompleted path should be valid for R.

**Actual behavior:** path format is not understood by R.
![autocomplete_file](https://user-images.githubusercontent.com/11860098/61128432-7ed0db80-a4ba-11e9-9aa1-b9f1aa144116.png)

![autocomplete_file_doesnt_exist](https://user-images.githubusercontent.com/11860098/61128420-79739100-a4ba-11e9-8d54-1f8095a1e6b4.png)

**Comment by ronblum** [comment] 2019-07-12 13:37
@david-cortes Thanks as alway for reporting these issues. In this case, do you see this occuring for local paths as well, or only networked drives?

**Comment by david-cortes** [comment] 2019-07-12 13:45
> @david-cortes Thanks as alway for reporting these issues. In this case, do you see this occuring for local paths as well, or only networked drives?

Only networked drives.

**Comment by david-cortes** [comment] 2019-07-15 08:04
@ronblum  : did a bit more testing and it's enough with changing the backslashes to forward slashes to fix it.
![network_path](https://user-images.githubusercontent.com/11860098/61202483-49adce80-a6f0-11e9-8ccc-de23de7bacab.png)
FYI @kevinushey

**Comment by ronblum** [comment] 2019-07-15 14:13
Ah. Looks like this is an issue with UNC paths. There are several known issues with UNC paths—searchable with `is:issue UNC`, so we can add this one to the list.

**Comment by kevinushey** [comment] 2019-07-15 15:54
It's probably worth saying that UNC paths are usually formatted as e.g.

```
\\servername\path
```

In other words, there need to be _two_ leading slashes, and since R requires backslashes to be escaped in strings the path should start with e.g. `"\\\\server\\path\\to\\file"`. (or, just use forward slashes and R will translate them as appropriate)

**Comment by david-cortes** [comment] 2019-07-15 16:26
> It's probably worth saying that UNC paths are usually formatted as e.g.
> 
> ```
> \\servername\path
> ```
> 
> In other words, there need to be _two_ leading slashes, and since R requires backslashes to be escaped in strings the path should start with e.g. `"\\\\server\\path\\to\\file"`. (or, just use forward slashes and R will translate them as appropriate)

But if I put 4 backslashes, R still says that the file doesn't exist.

**Comment by kevinushey** [comment] 2019-07-15 16:36
Then that seems like a bug in R's handling of UNC paths. If you were able to find a reproducible example (something that reproduces in R outside of RStudio) it could be worth filing as a bug report with R Core.

**Comment by kevinushey** [comment] 2019-07-15 16:37
That said, there are two separate issues here:

1. How R itself handles UNC paths;
2. How the compiler, when invoked by R, handles UNC paths.

It's possible that there are some disparities in this behavior (e.g. one works and one doesn't)

**Comment by david-cortes** [comment] 2019-07-16 09:37
@kevinushey : did some more testing:
* R actually accepts the 4 backshales and double forward slashes (that is, raw string in the standard windows format as `\\obj_name\some\path`.
* Mingw32 (not sure about the one Rtools uses) will only accept them in the standard windows format when passed to `-I` (`\\obj_name\some\path`) with or without the quotes, and with the all-forward slashes but in quotes (`-I"//some/nonlocal/path"`), so RStudio needs to pass them like that instead (currently passes the first ones as backslashes and the next ones as forward slashes).

**Comment by kevinushey** [comment] 2019-07-16 17:07
Got it, I think that makes sense.

Can you copy + paste the whole compiler command that you're seeing? The include paths are usually coming from e.g. `CXXFLAGS`, which are normally in R's own `etc/Makeconf` and are occasionally amended by package-specific Makevars or Makefiles (or a user's own `~/.R/Makevars`). It's possible that the R Makeconf needs to be tweaked, but it could also be something locally.

**Comment by david-cortes** [comment] 2019-07-16 17:10
> Got it, I think that makes sense.
> 
> Can you copy + paste the whole compiler command that you're seeing? The include paths are usually coming from e.g. `CXXFLAGS`, which are normally in R's own `etc/Makeconf` and are occasionally amended by package-specific Makevars or Makefiles (or a user's own `~/.R/Makevars`). It's possible that the R Makeconf needs to be tweaked, but it could also be something locally.

Sure, I had put it here: https://github.com/rstudio/rstudio/issues/5089

But copy-pastying:
```
==> Rcpp::compileAttributes()

* Updated R/RcppExports.R

==> Rcmd.exe INSTALL --no-multiarch --with-keep.source apkg

* installing to library '\\fs1.networked.drive/users/me/Documents/R/win-library/3.5'
* installing *source* package 'apkg' ...
** libs
C:/Rtools/mingw_64/bin/g++ -m64 -I"C:/PROGRA~1/MIE74D~1/ROPEN~1/R-35~1.3/include" -DNDEBUG  -I"\\fs1.networked.drive/users/me/Documents/R/win-library/3.5/Rcpp/include"   -I"C:/a/w/1/s/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c Num.cpp -o Num.o
Num.cpp:22:18: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
                  ^
compilation terminated.
make: *** [C:/PROGRA~1/MIE74D~1/ROPEN~1/R-35~1.3/etc/x64/Makeconf:215: Num.o] Error 1
ERROR: compilation failed for package 'apkg'
* removing '\\fs1.networked.drive/users/me/Documents/R/win-library/3.5/apkg'
In R CMD INSTALL

Exited with status 1.
```

**Comment by kevinushey** [comment] 2019-07-16 20:32
I believe the issue here needs to be resolved in R. This is where R sets up include paths for LinkingTo packages:

https://github.com/wch/r-source/blob/e1f8bd60dac460211bfdb522137cbea13d2ac0fb/src/library/tools/R/install.R#L1097-L1099

I believe that the path needs to be normalized here to use Windows slashes. You could file a bug report with R at https://bugs.r-project.org/bugzilla/.

It's worth noting that `normalizePath()` forces the two leading slashes to be backslashes; e.g.

```
> libpath <- "//Mac/Home/windows"
> normalizePath(libpath, winslash = "/")
[1] "\\\\Mac/Home/windows"
```

All that said -- the simplest workaround for your own case would likely be to map the network drive as a local drive, and use that local drive letter instead.

**Closed by kevinushey** 2019-07-16 20:32 UTC
Labels: bug, windows

**Comment by david-cortes** [comment] 2019-07-17 11:21
@kevinushey : I did a bit more digging. The include paths are taken from function `find.package`, which returns a valid path with 4 backslashes at the beginning and forward slashes following. `file.exists` accepts it in that format (says it exists), but not with 2 backslashes only, despite RStudio autocompleting it like that too. The compiler however doesn't take either if the slashes are mixed.

Also the default argument for `normalizePath`'s `winslash` is `"\\"`. If I pass it with all-forward slashes, it produces the standard windows path. And if I pass it with mixed slashes starting with 4 backslashes (like it was passed to the compiler), it produces a valid path too, only starting from C drive. With 2 backslashes it says the path is invalid.

So, since `find.package` is outputting a valid path (for R), is the issue really within R core?

Also wouldn't the solution be as simple as applying `normalizePath` before passing it to the compiler? That is, changing this line:
```r
paths <- find.package(lpkgs, quiet = TRUE)
```

to:
```r
paths <- normalizePath(find.package(lpkgs, quiet = TRUE))
```
