### ISSUE TITLE
Can not launch RStudio

### ISSUE THREAD

**Issue by WanderHow** [rstudio/rstudio#12917] opened 2023-03-28 07:29 UTC
### System details

    RStudio Edition :Desktop
    RStudio Version : 2023.03.0+386
    OS Version      : Windows 11 
    R Version       : R-4.2.3

### Describe the problem in detail
I can't launch RStudio. I have tried to remove %appdata%/RStudio and reinstal R and RStudio, but there is still no reaction after selecting R version. 

rdesktop.log:
2023-03-28T06:58:11.603Z ERROR Error querying the Windows registry: Error: Command failed: %SystemRoot%\System32\reg.exe query HKEY_LOCAL_MACHINE\SOFTWARE\R-Core\R /s /v InstallPath /reg:32

rsession-DELL.log:
2023-03-28T06:58:16.819799Z [rsession-DELL] ERROR Unable to retrieve user home path. HRESULT:  0x80070003; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::core::system::userSettingsPath(const class rstudio::core::FilePath &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,bool) src/cpp/core/system/Win32System.cpp:341

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2023-03-28 15:53
Duplicate of https://github.com/rstudio/rstudio/issues/12452. Please see https://github.com/rstudio/rstudio/issues/12452#issuecomment-1483905450 if you'd like to help us diagnose.

**Closed by kevinushey** 2023-03-28 15:53 UTC
Labels: bug, new

**Comment by WanderHow** [comment] 2023-03-29 01:34
I have did as you said, and gein this error.
&nbsp;
rdesktop.log has nothing new, but rsession-username.log shows the following error
2023-03-29T01:25:36.482744Z [rsession-DELL] ERROR Unable to retrieve user home path. HRESULT:&nbsp; 0x80070003; LOGGED FROM: class rstudio::core::FilePath __cdecl rstudio::core::system::userSettingsPath(const class rstudio::core::FilePath &amp;,const class std::basic_string<char,struct std::char_traits<char&gt;,class std::allocator<char&gt; &gt; &amp;,bool) src/cpp/core/system/Win32System.cpp:341





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "rstudio/rstudio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rstudio/rstudio] Can not launch RStudio (Issue #12917)





 
Duplicate of #12452. Please see #12452 (comment) if you'd like to help us diagnose.

**Comment by ronblum** [comment] 2023-04-04 05:58
@WanderHow I copied over your comment above in order to continue the discussion in #12452.
