### ISSUE TITLE
ANSI hyperlinks of rstudio:run do not appear in the build tab (Ubuntu 20)

### ISSUE THREAD

**Issue by maelle** [rstudio/rstudio#11241] opened 2022-05-19 06:05 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : "Spotted Wakerobin" Daily (5799183b, 2022-05-18) for Ubuntu Bionic
    OS Version      : Ubuntu 20
    R Version       : 4.2.0

### Steps to reproduce the problem

First 3 steps = https://github.com/maelle/ansilinks

1. Create a package with a simple function.
1. Create a testthat snapshot test.
1. Modify the code used in the test so the snapshot test fails.
1. Run the test in the console (`testthat::test_active_file()`). The expected clickable links to run code appear

![image](https://user-images.githubusercontent.com/8360597/169221309-ec2a94bc-0967-4977-8a91-c22a84830d11.png)

1. Delete the new snapshot `tests/testthat/_snaps/blop.new.md`, re-run the test in the build tab via clicking on the "Run Tests" button at the top of the test file. There is a clickable link to the test file but not to run code

![image](https://user-images.githubusercontent.com/8360597/169221379-55c26813-2f1f-44fa-903d-e3b4bc2115f6.png)

### Describe the problem in detail

No more details to add. 

### Describe the behavior you expected

I expected the clickable links to run code to be present in the build tab too.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by maelle** [comment] 2022-05-19 06:12
testthat session info

<details>

```r
> sessioninfo::session_info("testthat")
─ Session info ────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22)
 os       Ubuntu 20.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  fr_FR.UTF-8
 ctype    fr_FR.UTF-8
 tz       Europe/Paris
 date     2022-05-19
 rstudio  2022.06.0-daily+420 Spotted Wakerobin (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────
 package    * version    date (UTC) lib source
 brio         1.1.3      2021-11-30 [1] RSPM (R 4.2.0)
 callr        3.7.0      2021-04-20 [1] RSPM (R 4.2.0)
 cli          3.3.0.9000 2022-05-16 [1] Github (r-lib/cli@072ed21)
 crayon       1.5.1      2022-03-26 [1] RSPM (R 4.2.0)
 desc         1.4.1      2022-03-06 [1] RSPM (R 4.2.0)
 diffobj      0.3.5      2021-10-05 [1] RSPM (R 4.2.0)
 digest       0.6.29     2021-12-01 [1] RSPM (R 4.2.0)
 ellipsis     0.3.2      2021-04-29 [1] RSPM (R 4.2.0)
 evaluate     0.15       2022-02-18 [1] RSPM (R 4.2.0)
 fansi        1.0.3      2022-03-24 [1] RSPM (R 4.2.0)
 glue         1.6.2      2022-02-24 [1] RSPM (R 4.2.0)
 jsonlite     1.8.0      2022-02-22 [1] RSPM (R 4.2.0)
 lifecycle    1.0.1      2021-09-24 [1] RSPM (R 4.2.0)
 magrittr     2.0.3      2022-03-30 [1] RSPM (R 4.2.0)
 pillar       1.7.0      2022-02-01 [1] RSPM (R 4.2.0)
 pkgconfig    2.0.3      2019-09-22 [1] RSPM (R 4.2.0)
 pkgload      1.2.4      2021-11-30 [1] RSPM (R 4.2.0)
 praise       1.0.0      2015-08-11 [1] RSPM (R 4.2.0)
 processx     3.5.3      2022-03-25 [1] RSPM (R 4.2.0)
 ps           1.7.0      2022-04-23 [1] RSPM (R 4.2.0)
 R6           2.5.1      2021-08-19 [1] RSPM (R 4.2.0)
 rematch2     2.1.2      2020-05-01 [1] RSPM (R 4.2.0)
 rlang        1.0.2      2022-03-04 [1] RSPM (R 4.2.0)
 rprojroot    2.0.3      2022-04-02 [1] RSPM (R 4.2.0)
 rstudioapi   0.13       2020-11-12 [1] RSPM (R 4.2.0)
 testthat   * 3.1.4      2022-04-26 [1] RSPM (R 4.2.0)
 tibble       3.1.7      2022-05-03 [1] RSPM (R 4.2.0)
 utf8         1.2.2      2021-07-24 [1] RSPM (R 4.2.0)
 vctrs        0.4.1      2022-04-13 [1] RSPM (R 4.2.0)
 waldo        0.4.0      2022-03-16 [1] RSPM (R 4.2.0)
 withr        2.5.0      2022-03-03 [1] RSPM (R 4.2.0)

 [1] /home/maelle/R/x86_64-pc-linux-gnu-library/4.2
 [2] /opt/R/4.2.0/lib/R/library

───────────────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by ronblum** [comment] 2022-05-20 17:37
@maelle Thank you for raising this! I see the same behavior on MacOS 12.4. I'll mark this for review.

Note: The "Test" button in the Build Pane, which calls `devtools::test()`, has the links and formatting.

**Comment by romainfrancois** [comment] 2022-05-24 13:24
`cli::ansi_has_hyperlink_support()` returns `FALSE` because of the `cli.num_colors` option: 

```r
    opt <- as.integer(getOption("cli.num_colors", NULL))[1]
    if (!is.na(opt) && opt == 1) 
        return(FALSE)
```

The build pane does recognize the ansi code, otherwise the `test-blop` link would not appear. What happens is that the `snapshot_*` links are not emitted so can't be picked up, so I'm not sure this is an ide issue.

**Comment by romainfrancois** [comment] 2022-05-24 13:32
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/2625526/170047108-6232022d-b127-415d-8348-4acc180c3192.png">

Should `RSTUDIO_CLI_HYPERLINKS` sooner ? cc @gaborcsardi

**Comment by gaborcsardi** [comment] 2022-05-24 13:52
That's expected I believe, the testthat tests run in a reproducible context, so no ANSI colors, or hyperlinks.

**Comment by romainfrancois** [comment] 2022-05-26 11:32
It looks like the difference is in the `local_reporter_output()` call in `snapshot_accept_hint()`. 

With "Run Tests" it has `crayon = FALSE` which sets `cli.num_colors` to 1, which disables the hyperlinks. More investigation needed.

**Comment by romainfrancois** [comment] 2022-05-30 10:02
At the end of the day, https://github.com/r-lib/cli/issues/465 should fix it. 

However, `testthat` seems to still use `crayon` detection: https://github.com/r-lib/testthat/blob/2f48ca6c86fe205cd9283cd6cc8eb0e2a07031b5/R/reporter.R#L60

So I'd say it's up to `testthat` to fix this, or `crayon:::num_ansi_colors` could use the new `cli`  rstudio detection ?

A workaround could be to add `options(cli.num_colors = 256);` to https://github.com/rstudio/rstudio/blob/bb265d0dbedece7ced0325526ba14cb13684cb2d/src/cpp/session/modules/build/SessionBuild.cpp#L1213 or setting the `R_CLI_NUM_COLORS` env var. 

But it's probably better to fix in a package so that older rstudio versions can also benefit.

**Comment by romainfrancois** [comment] 2022-05-30 10:26
Maybe the `R_CLI_NUM_COLORS` env var should be set when `RSTUDIO_CONSOLE_COLOR` is: 

https://github.com/rstudio/rstudio/blob/5427386efdc8352b84c28d07067b5a534bae8a5a/src/cpp/session/modules/SessionConsole.cpp#L187

**Comment by romainfrancois** [comment] 2022-05-30 11:04
Should be fixed by: https://github.com/r-lib/testthat/pull/1633 without changing the ide code.

**Comment by gaborcsardi** [comment] 2022-05-30 11:16
It also needs dev cli I believe.

**Comment by romainfrancois** [comment] 2022-05-30 11:58
I think it does: 

cran cli: 

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/2625526/170987392-80a87ad5-6ac6-438d-8342-3377122a445d.png">

dev cli: 

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/2625526/170987665-f5c0580b-cff8-4ce4-97b6-500e0372a025.png">

**Closed** 2022-06-27 08:51 UTC
Labels: bug
