### ISSUE TITLE
Cursor jumps to the right when I type in Emacs from a terminal window

### ISSUE THREAD

**Issue by wlandau** [rstudio/rstudio#4349] opened 2019-02-22 19:53 UTC
![53259587-6db73780-369d-11e9-9dcc-7ee627fd590b](https://user-images.githubusercontent.com/1580860/53267316-0c995f00-36b1-11e9-9f7e-16e0439fe048.gif)

Specs:
- RHEL 7.6
- RStudio Server 1.1.453
- bash 4.2.46(2)-release
- Emacs 24.3.1

**Comment by DesiQuintans** [comment] 2019-03-01 04:47
In case it helps narrow down the bug, I couldn't replicate it on my own machine.

- Windows 7 64-bit
- RStudio Desktop 1.2.1303
- GNU Emacs 26.1 build 1 (I ran it with `emacs -nw`)

**Comment by jmcphers** [comment] 2020-03-13 23:40
We haven't been able to reproduce this and haven't had any reports in over a year, so closing. You might want to try with a recent build of RStudio; a preview of 1.3 is out now:

https://www.rstudio.com/products/rstudio/download/preview/

**Closed by jmcphers** 2020-03-13 23:40 UTC
Labels: bug

**Comment by wlandau-lilly** [comment] 2020-03-14 01:45
I am actually still having this issue, both on the original RHEL server (where I do not have admin privileges) and Mac OS 10.14.6. And I cannot install 1.2.5033 or 1.3.911 on the Mac due to #5507.

Could it be a font issue? The font in RStudio's terminal looks bold compared to the font in my regular Terminal.

**Comment by wlandau** [comment] 2020-12-27 21:48
Update: this problem went away on its own for me, possibly when I switched from Bash to Zsh.
