### ISSUE TITLE
Export options with the Viewer

### ISSUE THREAD

**Issue by nskoch** [rstudio/rstudio#5427] opened 2019-09-18 15:58 UTC
Export of the Viewer allows:
- Save as an Image
- Copy to clipboard
- Save as a web page.
After creating a table in an HTML format, the Viewer exhibit it nicely.
However, the "Save" and the "Copy" option gave the same truncated capture of the table.  The "Save as a web page" option is correct.
Best regards
![Rplot](https://user-images.githubusercontent.com/42101624/65164721-bd948c00-da3d-11e9-8e8f-9a05b986a648.jpeg)

**Comment by ronblum** [comment] 2019-09-18 16:22
@nskoch Thank you for reporting the issue. What environment are you working with? Specifically, the following:

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by nskoch** [comment] 2019-09-18 16:40
> RStudio Edition : 
> RStudio Version : 1.1.383
> OS Version      : mingw32
> R Version       : 3.6.1
Windows 10 Pro
Version 1903

HP EliteBook

**Comment by ronblum** [comment] 2019-09-18 19:43
@nskoch Thank you for the info. I'm unable to reproduce the issue. A few things:

1) The [current version of RStudio](https://www.rstudio.com/products/rstudio/download/) is 1.2.1578. Is this still an issue there?
2) Grabbing and moving the lower righthand corner will resize the image that will get copied to the clipboard. Does that take care of the issue?
<img width="190" alt="clipboard_corner" src="https://user-images.githubusercontent.com/31009952/65180424-d47db300-da2a-11e9-8802-6cc831107bbd.png">

3) If neither of these resolves the issue, can you please provide example code for which you see the issue? This will help in trying to reproduce it. Thanks!

**Comment by nskoch** [comment] 2019-09-19 06:52
Thanks for your reply.

I have downloaded the last version.

Now with the same code, nothing appears in the Viewer but only on the Console. Which did not allow a copy/past but only « Show in New Window ».

My code is the following 
table1(~Gender+age+ht+ibw | study, data=dba)

From the package table1.

Furthermore windows such as « About RStudio » did not fit entirely on the screen and are not sizeable.

Best regards
Nicolas

**Comment by jmcphers** [comment] 2020-05-05 15:55
This is a very old version of RStudio! The newer rendering engine in RStudio 1.2 should address this; feel free to reopen if it isn't resolved in the latest builds. 

https://www.rstudio.com/products/rstudio/download/preview/

**Closed by jmcphers** 2020-05-05 15:55 UTC
Labels: repro needed

**Comment by Batsi-2015** [comment] 2020-06-19 15:58
is there a way to automatically save the table from viewer. I have tried the html tools and saveWigdet but get these errors: saveWidget ----> error ---> "Error in .getNamespace(pkg) : 
  invalid type/length (symbol/0) in vector allocation" and htmltools::save_html -----> error --> "Error in writeImpl(text) : 
  Text to be written must be a length-one character vector". I can save the table okay when I click Export by would be great to just save with the command line options
