### ISSUE TITLE
dir hook path separator on Windows incompatible with Roxygen

### ISSUE THREAD

**Issue by brry** [rstudio/rstudio#10591] opened 2022-02-14 10:24 UTC
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 2022.02.0 Build 431 "Prairie Trillium" Release (1b11f0e8, 2022-02-09) for Windows 
    OS Version      : Windows 10 x64 (build 19041), x86_64, mingw32
    R Version       : 4.1.2 (2021-11-01)

### Steps to reproduce the problem

`dir("C:\\path", full=TRUE)`
returns paths with 'proper' slashes, e.g. `"C:/path/file"` due to `dir` being overwritten with

    "RStudio hook: restore original with `.rs.files.restoreBindings()`"
    .Call("rs_listFiles", path, pattern, all.files, full.names, 
        recursive, ignore.case, include.dirs, no.., PACKAGE = "(embedding)")

Roxygen needs the paths with Windows path separators (double backslash). With the Rstudio 'dir' hook, all Rd files are deleted after creation. See the issue there: <https://github.com/r-lib/roxygen2/issues/1287>

I don't mind whether Roxygen or Rstudio behaviour is changed but it would be good if both are compatible.  
I raised this issue link both.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2022-02-14 18:33
Duplicate of https://github.com/rstudio/rstudio/issues/10573; we'll continue following up there.

**Closed by kevinushey** 2022-02-14 18:33 UTC
Labels: bug, windows, regression

**Comment by brry** [comment] 2022-02-15 08:27
Thanks so much!   
Sorry I had missed the other issue. I only searched for roxygen, not devtools::document

**Comment by kevinushey** [comment] 2022-02-15 17:09
No worries! We appreciate your filing of the bug report, especially with the extra investigation to confirm it was an issue on the RStudio side.
