### ISSUE TITLE
R graphics engine version 13 is not supported (upcoming R version)

### ISSUE THREAD

**Issue by RLumSK** [rstudio/rstudio#7277] opened 2020-07-06 08:08 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1054
    OS Version      :  macOS 10.15.5
    R Version       :  "R Under development (unstable) (2020-07-01 r78761)"

### Steps to reproduce the problem

For example, the call

```r
plot(1:10)
```

leads to 

```
Warning message:
R graphics engine version 13 is not supported by this version of RStudio. 
The Plots tab will be disabled until a newer version of RStudio is installed. 
```

### Describe the problem in detail

["The graphics engine version, R_GE_version, has been bumped to 13 ...](https://cloud.r-project.org/doc/manuals/r-devel/NEWS.html), thus plots appear only outside of RStudio and not anymore in RStudio itself. This might
be related to https://github.com/rstudio/rstudio/issues/7253.

### Describe the behavior you expected

The plots are shown in RStudio and no warning is shown.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2020-07-06 17:33
Duplicate of https://github.com/rstudio/rstudio/issues/7253.

**Closed by jmcphers** 2020-07-06 17:33 UTC
Labels: plots

**Comment by R-Hannibal** [comment] 2020-07-18 00:34
Adding the verified label here to indicate this is a verified duplicate of https://github.com/rstudio/rstudio/issues/7253. That issue is not looking fixed at the moment, but the work will be tracked there.
