### ISSUE TITLE
"Usage" Section in Help File is Not Rendered Correctly When a Dark Editor Theme is Used

### ISSUE THREAD

**Issue by MarcelHWachter** [rstudio/rstudio#11051] opened 2022-04-24 07:45 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.1 Build 461
    OS Version      : Windows 10 21H2 
    R Version       : 4.2.0

### Steps to reproduce the problem
Choose dark editor theme and open the help file of a function.
### Describe the problem in detail
If a dark theme is active (e.g. Dracula) and you open the help file of a function, the "Usage" section is blurry and not rendered correctly. Prior to the installation of R 4.2.0 this problem didn't occur.
![image](https://user-images.githubusercontent.com/69349874/164965694-ae4320d1-86f3-42d4-88e9-a7e4e2ac07bd.png)
### Describe the behavior you expected
Correct Rendering of the Usage section in the help file.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by netique** [comment] 2022-04-24 12:53
This was already fixed, please check with daily build.

**Comment by MarcelHWachter** [comment] 2022-04-24 16:57
Oh sorry, didn't seet that. Should I close the issue?

**Comment by kevinushey** [comment] 2022-04-25 18:52
Thanks for reporting -- this is a duplicate of https://github.com/rstudio/rstudio/issues/10839.

**Closed by kevinushey** 2022-04-25 18:52 UTC
