### ISSUE TITLE
R Studio abruptly closed while ggplot()

### ISSUE THREAD

**Issue by Naveera-Latif** [rstudio/rstudio#10042] opened 2021-11-03 15:38 UTC
### System details

    RStudio Edition : 
    RStudio Version :  1.4.1106
    OS Version      : Ubuntu 20.04.3 LTS
    R Version       :   4.1.1 

### Steps to reproduce the problem
install.packages("ggplot2)
library(ggplot2)
x <-iris
ggplot(data=x, aes(x=x$Species , y=x$Sepal.Length))+ geom_boxplot()

### Describe the problem in detail
everytime I run this command, session was aborted in studio.

### Describe the behavior you expected

> library(ggplot2)
> x <-iris
> ggplot(data=x, aes(x=x$Species , y=x$Sepal.Length))+ geom_boxplot()
[10009:10010:20211103,203813.408901:ERROR file_io_posix.cc:148] open /home/naveera/.r/crashpad_database/pending/8c6304d5-f812-476f-848e-3adb627ac3a8.lock: File exists (17)
[10009:10009:20211103,203813.411228:ERROR process_memory_range.cc:86] read out of range
[10009:10009:20211103,203813.411237:ERROR elf_image_reader.cc:558] missing nul-terminator
[10009:10009:20211103,203813.411357:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.414726:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.414784:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.414831:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.414879:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.414930:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.414983:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.415397:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.415447:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.415850:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.415998:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.416042:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.416088:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.416131:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.416175:ERROR elf_dynamic_array_reader.h:61] tag not found
[10009:10009:20211103,203813.416219:ERROR elf_dynamic_array_reader.h:61] tag not found
[1

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by achubaty** [comment] 2022-01-21 17:44
isn't this the same error caused by the updated R 4.1 graphics engine not being supported in earlier rstudio releases? I can't find the dupe bug here, but this was fixed in a subsequent version of rstudio shortly after R 4.1 release.

**Comment by kevinushey** [comment] 2022-01-21 18:44
Yes, I believe that's correct. Given that @Naveera-Latif is using an older release of RStudio, I would recommend updating.

**Comment by mikebessuille** [comment] 2022-05-06 20:00
I'm closing this as resolved, per comments above

**Closed by mikebessuille** 2022-05-06 20:00 UTC
Labels: bug, repro needed, plots
