### ISSUE TITLE
Source pane syntax highlighting breaks for new knitr syntax (e.g., verbatim code chunks containing an r code chunk)

### ISSUE THREAD

**Issue by remlapmot** [rstudio/rstudio#10703] opened 2022-03-01 11:11 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 157
    OS Version      : Windows 11
    R Version       : 4.1.2

### Steps to reproduce the problem

Open an R Markdown (or I guess qmd) file in the Source pane which has a code chunks defined by more than 3 backticks which includes 3 backticks.

### Describe the problem in detail

Knitr v1.37 introduced verbatim code chunks, I noticed that when I include an r code chunk within one then the syntax highlighting after the verbatim chunk is then incorrect. i.e,

````` rmarkdown
````{verbatim}
```{r}
1 + 1
```
````
`````  

Screenshot

<img width="658" alt="2022-03-01 11_03_06-RStudio" src="https://user-images.githubusercontent.com/3777473/156157788-2a1b5c24-b497-43a5-a183-b66291772cbc.png">

I think the bug is that the highlighting is unreliable for chunks defined by more than 3 backticks which then contain 3 backticks.

This then causes 2 further problems

* the bottom collapse/expand arrow on the left handside of the Source pane then points to an incorrectly matched code fence. You can see in my screenshot the bottom arrow is incorrectly pointing downwards instead of upwards to the top of the verbatim chunk.

* the Outline pane then incorrectly detects lines beginning with `#` as headings that aren't in the R Markdown code.

My test Rmd file is as follows

````` rmarkdown
---
title: "Test RStudio R Markdown styling after a verbatim chunk"
---

Some text.

```
# Some code
```

Some text.

````{verbatim}
```{r}
1 + 1
```
````

Text incorrectly highlighted.

```{r}
# Not a heading!
```

Text incorrectly highlighted.

`````

### Describe the behavior you expected

Correct syntax highlighting.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-03-01 14:51
@remlapmot Thank you for raising the issue! I can reproduce this is in RStudio Desktop 2022.06.0-daily+151 2021.09.2+382, on both Windows 11 and MacOS 12.1. 

Also, could you check visual mode? I believe it's working in there, and the problem is only in source mode.

**Comment by ronblum** [comment] 2022-03-01 14:55
Note for triage: It's not a new issue, but I marked it as a candidate for Spotted Wakerobin in part because of the difference between source and visual modes.

**Comment by ronblum** [comment] 2022-03-01 16:50
@remlapmot Thank you! I can reproduce this issue as well. I'm marking this as visual editor as well.

**Comment by cderv** [comment] 2022-03-01 16:54
@ronblum I think this is the same as https://github.com/rstudio/rstudio/issues/10079 that I opened following the addition of the feature in **knitr**

**Comment by mikebessuille** [comment] 2022-03-07 18:08
Seems related to https://github.com/rstudio/rstudio/issues/10263.

**Comment by jennybc** [comment] 2022-11-10 18:02
I just bumped into this as well, when revising the R Packages book.

I'm using a four-backticked verbatim chunk to guard a literal three-backticked code chunk:

![Screen Shot 2022-11-10 at 9 41 36 AM](https://user-images.githubusercontent.com/599454/201171929-031fea1f-0637-429f-b927-d8a849b99f6c.png)

and am also seeing:

* loss of syntax highlighting from that point on
* broken outline from that point on (no header detection)
* switching to Visual mode restores the outline (yay!)

**Comment by ronblum** [comment] 2023-07-19 14:49
This issue keeps popping up. I'm consolidating them all in issue #10079.

**Closed by ronblum** 2023-07-19 14:49 UTC
Labels: bug, r markdown, source editor
