### ISSUE TITLE
Shortcut in visual mode (windows)

### ISSUE THREAD

**Issue by PabloSerrati** [rstudio/rstudio#7556] opened 2020-08-09 22:36 UTC
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.4.691
    OS Version      : Windows 10 x64 (build 18362)
    R Version       : R version 4.0.2 (2020-06-22)

### Steps to reproduce the problem
There is not steps
### Describe the problem in detail
When I am in "Visual Mode" (RStudio 1.4.691), I can't use the most of keyboard shortcuts. Example, if I want to **bold** my text, ctr + b doesn't work. Even for undo actions this doesn't work (this works correctly outside from "visual mode").  It is interesting that "change mode" shortcut works in visual and traditional mode.

Aditionally I am having some problems in visual mode with "Markdown shortcuts" (it understands them as special characters instead of format commands). This works correctly in tradicional mode.

### Describe the behavior you expected
see bellow.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment] 2020-08-12 10:15
Thanks for reporting this! The keyboard shortcut issue was due to some corruption of Ctrl+ keys by qtwebengine and is fixed here: https://github.com/rstudio/rstudio/commit/f07a6bb54ff2882d9eba84a44613aba2e8f9a06a (available in daily build v1.4.703).

In terms of the markdown shortcuts, I wasn't able to reproduce any unexpected behavior there. Could you provide more specifics?

**Comment by jjallaire** [comment] 2020-08-13 10:57
Closing for now. If there continue to be issues w/ markdown shortcuts feel free to re-open along w/ additional details on specifically what's not working.

**Closed by jjallaire** 2020-08-13 10:57 UTC
Labels: visual markdown editing
