### ISSUE TITLE
Facing issue in installing R studio for 64 bit PC. I am getting below error message. I have added "C:\Windows\System32" to system variable but still getting same error message.

### ISSUE THREAD

**Issue by Surabhi2107** [rstudio/rstudio#12909] opened 2023-03-25 16:23 UTC
![R studio error](https://user-images.githubusercontent.com/128921494/227729401-1179f6b1-670f-4149-b169-46b04411b12b.png)

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

### Describe the behavior you expected

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by Surabhi2107** [comment] 2023-03-25 16:25
I am getting above error message(64bit)I have added "C:\Windows\System32" in system varible. But issue persists

**Comment by kevinushey** [comment] 2023-03-25 19:55
Duplicate of https://github.com/rstudio/rstudio/issues/12452. See https://github.com/rstudio/rstudio/issues/12452#issuecomment-1483905450 if you'd like to test and provide us with more diagnostic information.

**Closed by kevinushey** 2023-03-25 19:55 UTC
Labels: bug, new
