### ISSUE TITLE
When folding code, line width is not adjusted

### ISSUE THREAD

**Issue by EmilBode** [rstudio/rstudio#2146] opened 2018-02-06 17:04 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : OSX 10.13.3 (High Sierra)
    R Version       : 3.4.2 (Short Summer)

### Steps to reproduce the problem
Open a new R-script, type code like this:

```R
if(SomeVar=='A long string of text. Or alternatively, a compound of conditionals, that together make a long line, so that it doesn't comfortably fit on your screen width') {
NewVar <- 'NewValue'
NewVar2 <- 'SomeMoreCode'
}
```

- Collapse/fold your statement (click left)

### Describe the problem in detail
If I scroll to the right, I can only scroll up to the opening "{", I can't see the "foldedSymbol", or my closing "}".

### Describe the behavior you expected
Extra space for scrolling, so that I can scroll to the right and see my entire {...}

### Note
Interestingly, if I add extra padding (e.g. a comment) right of my "{" the line width is seen as that of the original line. 
I.e., if I type something like:

```R
if(Var='Value') { # Some very long comment
Code
}
```

and then collapse, I can scroll way farther to the right, even too much

**Comment by ronblum** [comment] 2018-02-06 18:07
@EmilBode, thank you for raising the issue. I was able to reproduce this in 1.1.419. 

Just to clarify regarding the steps to: it is only the code between the brackets that is collapsed.

**Comment by EmilBode** [comment] 2018-02-07 08:11
That's right, the collapsing itself is working as expected, it's only the scrolling sideways that's not working as expected.
I guess RStudio simply calculates the width of each individual line, without taking into account that lines can grown by collapsing some code.
I also tried this code:

```R
if(SomeVar=='SomeVal') {
  print('SomeCode')
  NewVar2 <- 'SomeMoreCode'
} # And to close this block, I'd like to add some comment, e.g. to specify conditions that are now fulfilled. If uncollapsed, the line is readable, but no longer if I collapse it.
```

and it gets about the same result: I can right-scroll to character position 25 (if you have a very narrow sourcepane). Which is the maximum amount of characters in line 1 (the line number visible on the left), but not the amount of characters that is actually displayed.

**Comment by kevinushey** [comment] 2018-02-07 16:14
Thanks for the bug report! I've also reported this issue upstream, at https://github.com/ajaxorg/ace/issues/3553. (This appears to be a minor issue in the Ace editor, which RStudio uses to power its editor instances)

**Comment by jmcphers** [comment] 2019-11-27 18:36
Closing since there's no work for us to do here -- we'll have to wait for the problem to be resolved upstream (and it still hasn't been...)

**Closed by jmcphers** 2019-11-27 18:36 UTC
Labels: bug, external, reproducible
