### ISSUE TITLE
Clicking on multi-line console text selects random lines and moves to top

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#6553] opened 2020-03-30 13:48 UTC
**Steps to reproduce:**
* Paste some multi-line text in the console that would be long-enough to make it scrollable, but don't execute it.
* Scroll to the end of the pasted text.
* Click anywhere in the text.

**Expected behavior:** should move the writing position to where it was clicked, and leave the focus as it was.

**Actual behavior:** at the first click, selects several lines of text and shifts the focus to the beginning of the text that is in the console. At the second click, puts the writing position at the point that was clicked, but again shifts to the top. Using the keyboard to move the writing position also causes it to scroll to the top.

**Setup:** RStudio 1.3.929, running on debian linux.

I recall this was not a problem in the earlier 1.2 versions, but I might be wrong about it.

![unfocused_console](https://user-images.githubusercontent.com/11860098/77919640-1b841500-72a6-11ea-9175-54fb65d247bb.gif)

**Comment by kevinushey** [comment] 2020-03-30 16:52
I can reproduce this on macOS as well, with v1.3.929.  To reproduce, the length of the pasted multi-line input needs to be longer than the height of the Console pane.

It looks like we're forcing the first line of the console input to be in view on click.

**Comment by kevinushey** [comment] 2020-03-30 17:07
This reproduces in old RStudio v1.3 builds (tested back to 1.3.100) so I suspect this might be related to the Ace update.

**Comment by kevinushey** [comment] 2020-03-30 17:47
It seems like it's caused by this code:

https://github.com/rstudio/rstudio/blob/4dff639cf455cf90c1a2eae3981b68fef5f10a74/src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java#L115-L122

This code path tries to use the Ace cursor element to figure out the right cursor location and scroll it into view, but that no longer works as expected.

**Comment by jmcphers** [comment] 2020-03-30 21:17
Fixed in #6556.

**Comment by kevinushey** [comment] 2020-03-31 16:46
Re-opening as prior fix was insufficient.

**Comment by jmcphers** [comment] 2020-04-01 18:30
Fixed in #6562

**Closed by jmcphers** 2020-04-01 18:30 UTC
Labels: bug, console

**Comment by rich-rstudio** [comment] 2020-04-08 17:40
verified on 1.3.938-2 Preview
