### ISSUE TITLE
Display within console of vectors of complex numbers with labels erroneously repeats 1st row's values if it can't fit in 1 line.

### ISSUE THREAD

**Issue by wmkaminsky** [rstudio/rstudio#8657] opened 2020-12-23 03:26 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.3.1093
    OS Version      :  Windows 10 Home (Version 1909, Installed 11/21/2020, Version 18363.1256)
    R Version       :   4.0.3 (2020-10-10 "Bunnie-Wunnies Freak Out")

## First, note that the following complex-valued vector does indeed display correctly for me.
a <- 1:52         # Nothing special about 52. 
                        # I just chose it for convenience for naming later by `letters` and `LETTERS`,
                        # and because 52 is of sufficient length to keep values from fitting on 1 line.
z <- a + a*1i
z

## Now, just adding *labels* will elicit the error for me.  Namely, the second and higher rows formed by wrapped text printing will erroneously repeat the first row in regard to the *values* (though not the *names*; the names still display correctly for me).
names(z) <- c(letters, LETTERS)
z

## It does seem there's something critical about the values being complex.  I note that the erroneous repeats disappear for both
Re(z)
Im(z)

## As my final point, I also note that if I reset the names to NULL, the complex values display correctly again.
names(z) <- NULL
z

### Describe the problem in detail

Again, it seems to me there's a error displaying vectors when:
    -- the vectors *complex-valued*, AND
    -- moreover, the values have *names* accompanying them, AND
    -- the values and names don't all fit on 1 line.

Namely, the *values* of the first row will erroneously be repeated in the second and higher rows necessitated by the displayed text being wrapped.   On the other hand, the *names* remain correctly displayed in all rows.   

### Describe the behavior you expected

Both the correct values and names appearing regardless of whether the values have names.

- [ Y ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ Y ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ Y ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ Y ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-12-23 15:17
@wmkaminsky Thank you for filing the issue, and for pinning down the conditions in which this occurs! I can reproduce this, in my case in RStudio Desktop 1.4.1096 on MacOS 11.1 and RStudio Server 1.4.1096 on Red Hat 8.3. However—I can also reproduce this in standalone R, outside of RStudio, so the IDE is repeating the information being provided by R. So, I'm closing this as an external issue. If you'd like to file an R bug with (I assume it's a bug? It looks like a bug), information about how to do so is at https://www.r-project.org/bugs.html . Thanks!

**Closed by ronblum** 2020-12-23 15:17 UTC
