### ISSUE TITLE
Reopen project after session crash, if possible

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3220] opened 2018-07-25 17:37 UTC
Today, if your R session crashes, the next session you start will be in the empty project.

We do this so that you don't get stuck in a crash loop; if for some reason you have a project/state which crashes R on startup or shortly thereafter, you couldn't escape if we kept reloading the same state. 

This can be inconvenient, however, as it takes you out of context. It'd be nice if we could stay inside the project. To do this while still avoiding a crash loop, we could consider some kind of delayed launch success flag that's set after the session has successfully been alive for a healthy period (say, a full minute); if it lives that long, it's presumed that it doesn't have a startup crash. A session that does not live for the healthy period before crashing would result in the behavior we have today (project closure).

(via @hadley, @MariaSemple, @kevinushey)

**Comment by kfeinauer** [comment] 2018-10-19 16:54
If we are unable to restore the project as described above, we should set restore the default non-project working directory. See #3358 and #3709.

**Comment by tareefk** [comment] 2019-01-24 21:39
Could we prompt people to select what they would prefer the IDE do?

**Comment by jmcphers** [comment] 2019-01-24 23:33
Yes, that could be part of the workflow in cases where we can't determine the right course of action implicitly.

**Comment by david-cortes** [comment] 2019-02-19 18:58
Perhaps a stupid question, but why would _opening_ a project crash R?

**Comment by jmcphers** [comment] 2019-02-19 19:09
Not stupid at all! R can be crashed by code in .Rprofile, or by loading code from .Rdata on startup. It's also possible for RStudio itself to crash during boot because of bad project state as it loads your active documents, builds your environment pane, etc.

**Comment by david-cortes** [comment] 2019-02-19 19:15
> Not stupid at all! R can be crashed by code in .Rprofile, or by loading code from .Rdata on startup. It's also possible for RStudio itself to crash during boot because of bad project state as it loads your active documents, builds your environment pane, etc.

Had no idea the `.Rprofile` file was loaded from the project directory instead of the regular home. But in that case, is it any better than just loading the default session, which also loads its own `.Rprofile` and `.Rdata`?

How about asking the user in the crash dialog instead? (at least when the crash is produced by a segfault in code).

**Comment by jmcphers** [comment] 2019-02-19 19:17
> How about asking the user in the crash dialog instead?

A good idea, and one of the proposals in #4331!

**Comment by MichaelChirico** [comment] 2019-09-17 08:24
I think a prompt is the best way

![Screenshot 2019-09-17 at 4 13 17 PM](https://user-images.githubusercontent.com/7606389/65023753-15f85a80-d966-11e9-9d28-7d5af52531d0.png)

Plenty of real estate here to have a "Re-start project" button besides "Start New Session" -- then there's just the design concern of how to communicate the difference between the two options.

The concern about an R crash loop is I think a bit underdeveloped.

Suppose a user's project directory has become corrupted in a way that would produce such a crash loop. What is the expected behavior on their part to fix this? Wouldn't it be better if RStudio offered some guidance here on common errors?

What about the following:

 1. Automatically re-start the crashed project.
 2. If the project crashes again before user does anything, start again with `R --vanilla` to isolate the issue. If this succeeds, inform the user that they likely have some corrupting code in their `.Rprofile` (etc).

As of now, 99% of the time that I'm crashing RStudio it's because I'm working on the C/C++ code of a package and making mistakes. The current behavior is rather inconvenient, to the point where actually when I'm testing some new code I'm more likely to start R in the terminal since the normal segfault behavior there is much more graceful and I don't completely lose my project state. My 2 cents.

**Comment by dfalty** [comment] 2019-11-15 01:48
This issue also impacts RStudio Server sessions that are killed from the command line `rstudio-server kill-session/kill-all` or from the session timeout kill feature `session-timeout-kill-hours` when RSP is set up to not have multiple sessions `server-multiple-sessions=0`. The session is then treated like a crashed session that will not reopen the project when recreating the session. 

Because rstudio.cloud is set up this way, it means users can get in a situation where the cloud project can be killed and when the session is recreated, it looks like all session data especially unsaved data is lost because the project is not reopened. 

Steps:
1. Have RStudio Server Pro setup with `server-multiple-sessions=0`
2. Create a session and project
3. Create a new file, save, and add additional unsaved changes
4. Log out
5. From the command line `rstudio-server kill-all` (can be reproduced by causing `session-timeout-kill-hours` to be triggered on the session
6. Log back in
7. Observe new session is created and the project isn't opened so it seems like all unsaved changes are lost
Note: unsaved changes will be located in the `.Rproj.user` directory and can be recovered by opening the project

rstudio.cloud steps to reproduce:
1. Create a project
2. Create a file and have unsaved changes
3. Keep the session busy for longer than 4 hours but don't interact with the browser tab or close it out. Example: `for (i in 1:15400) {Sys.sleep(1)}` This is because `session-timeout-kill-hours` is set to 4 currently
4. Go back to cloud project
5. Observe session is created and it looks like unsaved changes are lost because project isn't open

**Comment by jmcphers** [comment] 2019-12-05 19:43
I think the session timeout kill hour problem is distinct. I have opened https://github.com/rstudio/rstudio-pro/issues/1349 to track it.

**Comment by jmcphers** [comment] 2020-03-20 16:12
Very strongly related to https://github.com/rstudio/rstudio-pro/issues/1424.

**Closed** 2020-04-06 22:45 UTC
Labels: enhancement, rstudio.cloud

**Comment by dfalty** [comment] 2020-06-04 19:52
Verified functionality on 1.3.1007-2 and 1.3.1008.
