### ISSUE TITLE
Quarto hangs RStudio

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12836] opened 2023-03-14 13:16 UTC
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.3.0.386
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.2.2 (2022-10-31 ucrt)

### Steps to reproduce the problem

1) Create a new default Quarto document and save it.
2) Make rendered document appear in the Viewer pane.
![image](https://user-images.githubusercontent.com/12725868/225011440-94f975dd-4bba-456c-af7a-30716ec1484a.png)

3) Render the document.
4) Try to restart the current R session and this hangs RStudio. The similar behavior happens if you try to exit RStudio.
![image](https://user-images.githubusercontent.com/12725868/225012128-ccbd1938-094d-4cc4-a5e3-069912cbea81.png)

### Describe the problem in detail

Most of the functionalities in RStudio do not work. If you quit RStudio the hard way (nothing else works), the session state (e.g., open tabs) is lost.

### Describe the behavior you expected

RStudio restarts as usual. Nothing is lost. If something (as the preview of the current Quarto document), should be stopped, the functionality for this exists.

**Comment by GegznaV** [comment] 2023-03-14 13:26
Will this issue be fixed before the next release of RStudio?

**Comment by GegznaV** [comment] 2023-03-14 15:50
Can it be that the real issue is that not finished background jobs (Quarto preview is one of them) hang RStudio?

**Comment by daranzolin** [comment] 2023-03-14 18:35
Came here to file the same issue. It's been a nightmare introducing both RStudio and Quarto to my team.

**Comment by jonvanausdeln** [comment] 2023-03-14 18:47
@GegznaV, Thank you for reporting this.

I can reproduce on windows 11 with 2023.03.0+386.

This could be related to https://github.com/rstudio/rstudio/issues/10823.

**Comment by jonvanausdeln** [comment] 2023-03-14 19:11
I have found another work around.

You need to stop the background job for serving the quarto document.  It will then let you restart the session.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/6433789/225112074-858d6bb2-fbdf-4f09-824b-046104a71326.png">

**Comment by jonvanausdeln** [comment] 2023-03-14 19:21
[#12655](https://github.com/rstudio/rstudio/issues/12655), might also be related

**Comment by mikebessuille** [comment] 2023-03-14 19:54
Does the quarto background job persist while the preview is being displayed, or does it finish after some time?

**Comment by jonvanausdeln** [comment] 2023-03-14 20:03
The job persists, and appears to only stop when manually stopped. Closed the viewer and it the job persisted.

I was just also able to reproduce in Elsbeth.. so it's been in there for awhile.

**Comment by jonvanausdeln** [comment] 2023-03-14 20:46
@mikebessuille , I agree. It should be high priority for next release (or patch), but I don't think it should hold up Cherry Blossom as we are so close.

**Comment by GegznaV** [comment] 2023-03-16 11:05
>How often would a user want to restart the R session when a quarto document is being previewed?

Every time a user tries to close RStudio while Quarto is being previewed, he or she may even not notice that RStudio is chased as clicking the close button twice forces RStudio to close. After clicking the Close button once RStudio gets frozen, you may not save any files (and some users may find this stressful).  After clicking the second time, RStudio closes. But luckily, in this situation, no open tabs are lost after RStudio is restarted.

Trying to restart the R session makes it even worse: all open tabs will be lost. It's not a big deal if the changes in the tabs are saved. (Just new users like my students will start panicking, but experienced ones will know how to deal with this). But if there are **unsaved changes, they may be lost**. And this is a big deal. As in the frozen state, the files do not save. There is a workaround to copy everything to some other program, but you have to know about it.

>  I think this is not urgent enough to prevent Cherry Blossom from releasing. 

I think that the in current released version this issue is present so releasing a new one will not make things worse (you should release it). But the issue must be fixed ASAP.

**Comment by ronblum** [comment] 2023-03-22 15:45
This also stops a project from closing.

*From @oswaldoforey in issue #12873:*

### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0 Build 386
    OS Version      : Windows 10 Professionnal
    R Version       : 4.2.2 (2022-10-31 ucrt)

### Steps to reproduce the problem

Open a new project from the top right Project drop down menu in RStudio, then New Directory and Quarto Website. Render the provided example website using the "Render website" option under the Build tab, then hit the "Close Project" option from the same drop down menu. The Closing project window pops up with the "running circle" (sorry don't know what to call it) indicating that it is closing, but it never does. 

### Describe the problem in detail

I discovered that opening the PC task manager, unfolding the RStudio option and ending the "Deno: a secure runtime for JavaScript and TypeScript" process closes the project ok in RStudio.

### Describe the behavior you expected

I expected the project to close without having to stop Deno through the task manager

**Comment by schw4b** [comment] 2023-04-27 08:25
I have the same issues
1) Cannot close a project while Quarto Project is running. Needs first to manually stop the background job.
2) Same for restarting R
3) I observed a similar problem for a Quarto interactive document (server: shiny): After running the Document, I cannot stop the Render process. 
Steps to reproduce 3). 
 1. File -> New File -> Quarto Document, select interactive, press create
 2. Save the newly created document under any filename
 3. Run Document
 4. Change the document, hit save
 5. Now you cannot show your changes: stop button under the Render tab does not work. Hit Run Document again does not work. Now, further changes to the Document cannot be saved anymore. Only option is to close RStudio. Changes will be lost.

I have this issue under Windows 10 but not on my Mac installation.

**Comment by jonvanausdeln** [comment] 2023-05-25 15:28
Verified on Desktop 2023.06.0-daily+401
Windows 11

Able to successfully restart R, close project, and start new project.  Quarto process ends correctly in all cases.

**Closed by jonvanausdeln** 2023-05-25 15:28 UTC
Labels: bug, quarto

**Comment by schw4b** [comment] 2023-06-06 11:57
Wonderful, thank you!

**Comment by MohammadAliAmir** [comment] 2024-02-20 09:36
Is there also a fix for UNIX-like operating systems? I have a similar issue that rstudio server seems to be hanging when I start a new R project. This is running on a centos7 container and what I see is that quarto is swallowing up all the resources given to that container. After a long wait, it finally becomes responsive and the popup of the R project creation appears.

Also I don't see any backgrounds jobs running in the background jobs tab but I do see the process of quarto in a seperate shell.

Maybe less related to this issue, but is there a way to disable quarto/deno instead as I don't use it? I only noticed this behaviour when I upgrade from 2022.02.3-492 to 2023.12.0-369 ? Should I perhaps create a seperate issue for this?

rstudio info: RStudio 2023.12.0+369 "Ocean Storm" Release (33206f75bd14d07d84753f965eaa24756eda97b7, 2023-12-17) for CentOS 7
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

**Comment by jonvanausdeln** [comment] 2024-02-20 16:43
@MohammadAliAmir this issue was about rendering a quarto document and not allowing R to restart.  Sounds like your issue is slightly different.  I recommend opening a new issue for your specific scenario.
