### ISSUE TITLE
Setup chunks are no longer automatically run

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#10592] opened 2022-02-14 14:15 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.01.0 Build 234
    OS Version      : 
    R Version       : 

### Steps to reproduce the problem

Create a new `.Rmd` containing:

````
```{r setup}
print("Hi")
```

```{r}
print("Bye")
```
````

### Describe the problem in detail

Run the second chunk 

### Describe the behavior you expected

I expect the setup chunk to be automatically run once before any other chunks. I'm sure this used to happen.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment] 2022-02-14 17:49
I can reproduce this sporadically, but not consistently. If I open RStudio Desktop, and run the second chunk, the setup chunk runs. If I restart the R session, with Cmd Shift 0, and run the second chunk, generally the setup chunk runs as well but sometimes it seems to not run. I'm seeing this behavior in 2022.02.0+434.

I think the setup chunk only doesn't run if I press the button to run chunk immediately after session restart, before the session has finished fully restarting. It seems like if I wait at least a couple of seconds, the setup chunk always runs.

@hadley do you see the same?

<img width="354" alt="image" src="https://user-images.githubusercontent.com/7817881/153918387-81a2fb51-9263-4871-8d07-33b09cf1df60.png">

**Comment by hadley** [comment] 2022-02-14 22:03
Hmmm, I can't ever it to run.  I tried waiting ~10 seconds, and I tried clicking the button instead of using cmd + shift + enter, but it still reliably fails for me.

**Comment by ronblum** [comment] 2022-02-18 15:39
I can consistently reproduce the problem in RStudio Desktop 2022.02.0+443 on MacOS 12.1. I only get `Bye`, never `Hi`.

**Comment by hadley** [comment] 2022-02-22 20:25
@ronblum you're describing the expected behaviour, right? I'm not seeing that behaviour.

**Comment by ronblum** [comment] 2022-02-23 15:08
@hadley Oh no, I'm describing what I'm seeing. I'll get a proper video capture of it.

**Comment by jgutman** [comment] 2022-02-23 15:26
Just to check, @hadley can you confirm a couple things, since it seems like we're having a little trouble reproducing the same behavior (setup chunk never runs) that you're seeing:

1. Open the Command Palette with Shift + Cmd + P and search for "Automatically run Setup chunk when needed". Is it on?
2. If yes, would you mind updating to the RStudio release from last week -- 2022.02.0+443 and confirm you still see the behavior?

**Comment by hadley** [comment] 2022-02-24 16:53
Oooh, "show chunk output inline" is off. It's surprising to me that this affects this behaviour, so that's probably the root cause.

**Comment by jgutman** [comment] 2022-02-24 16:59
I'll be honest and say, I have no idea why it affects the behavior, but I found the answer in this old [RStudio Community post](https://community.rstudio.com/t/automatic-execution-of-setup-chunk-in-rmd/71483/4)

I'll check whether that's the intended behavior

**Comment by jgutman** [comment] 2022-02-24 17:46
For clarity, I'm going to close this issue, but open a new one to reflect that `Show chunk output inline in all documents` setting should be better named, and it also SHOULDN'T control whether setup chunks are automatically executed.

**Closed by jgutman** 2022-02-24 17:46 UTC
Labels: repro needed

**Comment by hadley** [comment] 2022-02-25 13:17
Thanks @jgutman!
