### ISSUE TITLE
Column completions show incorrect data

### ISSUE THREAD

**Issue by uhkeller** [rstudio/rstudio#12880] opened 2023-03-22 09:46 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386
    OS Version      : macOS 13.2.1
    R Version       : 4.2.3

### Steps to reproduce the problem

Start a new session. Run the following two lines in the console:

```R
df1 <- data.frame(a = 1:3)
df2 <- data.frame(a = 11:13)
```
Now type `df1$` in the console. The column completion will show the data for `df1$a` correctly:

![image](https://user-images.githubusercontent.com/2323704/226863054-72788dfd-f73b-4697-9124-410bfcd102da.png)

Delete the line and type `df2`. The data frame completion shows the correct data:

![image](https://user-images.githubusercontent.com/2323704/226863622-685cceaf-66cc-4a0a-8827-90457d745073.png)

Now type `$`. The column completion will show the *incorrect* data from `df1$a` instead of `df2$a`:

![image](https://user-images.githubusercontent.com/2323704/226864462-efb1f773-7b74-4038-9d7d-b26f5aab9007.png)

### Describe the problem in detail

Column completions sometimes show data from a different data frame, though data frame completions are correct.

### Describe the behavior you expected

I expected the completion to show the correct data…

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by cathblatter** [comment] 2023-03-25 19:17
my question here might be related https://community.rstudio.com/t/rstudio-dataframe-preview-after-piping-shows-old-variables/162835

**Comment by ronblum** [comment] 2023-04-04 06:05
@uhkeller Thank you for raising this issue, and also @cathblatter for pointing out the Community post! I can also reproduce this in RStudio Desktop 2023.05.0-daily+164 on MacOS 13.3.

@romainfrancois Do you have any thoughts about this problem?

**Comment by mikebessuille** [comment] 2023-04-10 14:19
@romainfrancois would you be able to look at this?  Looks like a regression resulting perhaps from your changes in Cherry Blossom?

**Comment by romainfrancois** [comment] 2023-05-12 08:13
I believe this is a browser caching issue when loading `gridviewer.html` related to 

https://github.com/rstudio/rstudio/blob/afdee25b92abb127646fc345f5be6481ea777a0f/src/cpp/session/modules/SessionHelp.R#L559-L560

**Comment by sharon-wang** [comment] 2023-07-24 20:08
We've recently added various fixes in the data viewer to address data caching issues 🎉 

I've verified that this issue is fixed in the latest release `2023.06.1` which you can download here: https://posit.co/download/rstudio-desktop/!

**Closed by sharon-wang** 2023-07-24 20:08 UTC
Labels: bug, autocompletion
