### ISSUE TITLE
Stage chunk and stage line exclude last line of file

### ISSUE THREAD

**Issue by dapperjapper** [rstudio/rstudio#2460] opened 2018-03-20 22:47 UTC
### System details

I was able to reproduce this bug on both systems that I had access to.

    RStudio Edition : Server and Deskop
    RStudio Version : 1.1.383 (Server) and 0.98.1103 (Desktop)
    OS Version      : 
    R Version       : R version 3.4.2 (Both)

### Steps to reproduce the problem

1. Create a file in a git-tracked repo in RStudio. Add a line of text and a newline at the end and commit.
2. Add at least two lines of text to the file--keeping the newline at the end--and save.
3. Highlight the last two or three lines of the file in the RStudio git diff viewer, and click "Stage lines."
4. The lines above the last line will be staged, but the last line of the file is mysteriously unstaged.

### Describe the problem in detail

The "Stage line" and "Stage chunk" buttons in the diff viewer window don't apply any operations to the last line of a file when editing a file that has a newline at the end. The "Stage" button (that applies to the whole file) functions correctly, just not the partial staging buttons in the lower pane.

I'm guessing there's an off-by-one bug somewhere in the code that connects to the git backend.

### Describe the behavior you expected

Any lines that are highlighted when "Stage lines" is clicked should be staged.

**Comment by kevinushey** [comment] 2018-03-21 20:19
Thanks for the bug report! We've bumped into this numerous times in the past as well and it's definitely a vexing bug -- unfortunately, we haven't been able to get to the bottom of it yet, but we'll continue investigating.

**Comment by colearendt** [comment] 2018-06-13 03:34
Not sure how much this is related.  I was thinking about opening a separate bug, but maybe this is the same bug masquerading in different ways.  

Maybe related to #2877 ?  Which I have observed on occasion on Mac or Linux (RStudio Server Pro).  Props to the terminal, which is an awesome fall-back when Git functionality doesn't work.

In RStudio Desktop 1.2.648-1, I have reproduced the following:

- create a classic `app.R`
- modify a line in the middle of the file (stage line / stage selection works fine)
- add a line and a character to the bottom of the file (above the ending new-line)
- now stage chunk / stage line on the bottom of the file doesn't work (as predicted).  Stage chunk still works on our earlier change, but stage line / stage selection _do not_.
- ok, revert the change at the bottom of the file (will have to do this manually, since discard chunk does not work either)
- add a character to the top line of the file
- stage / discard chunk works for this line, but stage line / stage selection do not.  Similarly, stage line / stage selection do not work on our middle-of-the-page change either.

Wacky behavior!  Hope it helps peg the issue.

**Comment by colearendt** [comment] 2018-07-03 16:37
Another note, I am seeing the following error when trying to stage lines that are rejected for this reason.  Note that line 34 is neither the line I am trying to stage, nor the last line of the file.
```
03 Jul 2018 16:32:25 [rsession-rstudio] error: corrupt patch at line 34
```

Line 34 and context (`tags$h1(title)` is line 34)
```
html_report <- function(
                        results_variable,
                        filename = "dplyr_test_results.html",
                        title = "dplyr SQL translation tests",
                        show_when_complete = TRUE) {
  html_result <- list(
    tags$h1(title),
    1:nrow(results_variable) %>%
      map(function(x) {
        print_result(results_variable[x, ], x)
      })
  )

  save_html(html_result, filename)

  if (show_when_complete) utils::browseURL(filename)
}
```

This is the commit I was trying to stage in chunks: https://github.com/colearendt/dbtest/commit/f654f2f5f8d73745e7ddac1b08504bb2a201da1b

**Comment by kevinushey** [comment] 2018-07-03 17:11
What we had seen in the past was attempts to stage whitespace-only chunks occurring at the end of the file would fail. It sounds like this is failing in an entirely separate context?

**Comment by colearendt** [comment] 2018-07-03 19:02
Yeah, I have had it fail in all sorts of different contexts.  The stage / unstage line / selection have seemed pretty fickle to me - I try to use that functionality a lot 😄

**Comment by colearendt** [comment] 2021-02-06 14:51
Please keep

**Comment by salim-b** [comment] 2021-02-08 18:14
This issue still persists in latest stable RStudio v1.4.1103 and is really annoying. 😐

**Comment by salim-b** [comment] 2022-03-04 08:28
This is still an issue with RStudio Desktop 2022.02.0+443.

Besides, I suspect this might be related to https://github.com/rstudio/rstudio/issues/5476.

**Comment by mortonne** [comment] 2022-09-30 06:11
This is still an issue with RStudio 2022.07.1 Build 554. When I attempt to stage a function added to the end of the file, the link with the closing brace (}) is excluded, which of course would make that commit contain invalid code. It makes the git interface much harder to use effectively.

**Closed** 2024-02-29 16:00 UTC
Labels: bug, vcs
