### ISSUE TITLE
Dark themes don't report themselves as dark

### ISSUE THREAD

**Issue by hezibu** [rstudio/rstudio#4850] opened 2019-05-26 17:25 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1335
    OS Version      : Windows 10
    R Version       :  3.6.0

### Steps to reproduce the problem
Fresh install of RStudio. Change to a dark theme. IDE theme remains light Modern instead of dark modern.

```
> rstudioapi::getThemeInfo()
$editor
[1] "Clouds Midnight"

$global
[1] "Modern"

$dark
[1] FALSE

$foreground
[1] "rgb(146, 146, 146)"

$background
[1] "rgb(25, 25, 25)"

> .Call("rs_readUiPref", "rstheme")
$isDark
[1] FALSE

$name
[1] "Clouds Midnight"

$url
[1] "theme/default/clouds_midnight.rstheme"

> .rs.readUiPref("rstheme")
$isDark
[1] FALSE

$name
[1] "Clouds Midnight"

$url
[1] "theme/default/clouds_midnight.rstheme"

```

![image](https://user-images.githubusercontent.com/44232295/58385157-ae07b800-7ff4-11e9-8c1a-92c6b1d0c454.png)

1. The output of sessionInfo() 
```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0  tools_3.6.0     rstudioapi_0.10

```

**Comment by pascaloettli** [comment] 2019-05-27 01:06
There is a problem somewhere. This is how it looks like on my computer:

![Screenshot from 2019-05-27 10-04-14](https://user-images.githubusercontent.com/6613954/58389614-07a8ca80-8067-11e9-91e9-5093a7b814f1.png)


     RStudio Edition : Desktop
     RStudio Version : 1.2.1335
     OS Version      : Ubuntu 18.04.2
     R Version       :  3.6.0

> R> rstudioapi::getThemeInfo()
> $editor
> [1] "Clouds Midnight"
> 
> $global
> [1] "Modern"
> 
> $dark
> [1] TRUE
> 
> $foreground
> [1] "rgb(146, 146, 146)"
> 
> $background
> [1] "rgb(25, 25, 25)"
> 
> R> .Call("rs_readUiPref", "rstheme")
> $isDark
> [1] TRUE
> 
> $name
> [1] "Clouds Midnight"
> 
> $url
> [1] "theme/default/clouds_midnight.rstheme"
> 
> R> .rs.readUiPref("rstheme")
> $isDark
> [1] TRUE
> 
> $name
> [1] "Clouds Midnight"
> 
> $url
> [1] "theme/default/clouds_midnight.rstheme"

**Comment by hezibu** [comment] 2019-05-27 08:41
what could it be?

**Comment by pascaloettli** [comment] 2019-05-27 09:21
What's strange is that the [Clouds Midnight theme](https://github.com/rstudio/rstudio/blob/master/src/cpp/session/resources/themes/clouds_midnight.rstheme) is clearly a dark theme (`rs-theme-is-dark: TRUE`)

**Comment by MariaSemple** [comment] 2019-05-27 19:10
@hezibu Are you able to see any errors in the Javascript Console? You can open this by right clicking anywhere in RStudio and selecting "Inspect Element" from the context menu. The console should be the second tab, labelled "Console".

**Comment by hezibu** [comment] 2019-05-27 20:12
> 
> 
> @hezibu Are you able to see any errors in the Javascript Console? You can open this by right clicking anywhere in RStudio and selecting "Inspect Element" from the context menu. The console should be the second tab, labelled "Console".

This could be it:

``
Uncaught TypeError: Cannot read property 'nTh' of undefined
    at O (jquery.dataTables.min.js:1)
    at jquery.dataTables.min.js:1
    at k (jquery.dataTables.min.js:1)
    at HTMLTableElement.<anonymous> (jquery.dataTables.min.js:1)
    at Function.each (jquery.js:2)
    at n.fn.init.each (jquery.js:2)
    at n.fn.init.F [as dataTable] (jquery.dataTables.min.js:1)
    at initDataTable (dtviewer.js:1133)
    at dtviewer.js:1388
    at dtviewer.js:385
``

**Comment by MariaSemple** [comment] 2019-05-27 22:52
I don't think that's related since the theme should have loaded before the data table. Could you try the following:

1. Change the theme to something other than Clouds Midnight.
2. Open the Javascript Console again, and switch to the Network tab instead.
3. Change the theme back to Clouds Midnight.
4. Look for "clouds_midnight.rstheme" in the list of names on the left-hand side of the network pane.  If you click it, you should see a preview of file in the pane to the right. 
5. The first to lines should look like
```
/* rs-theme-name: Clouds Midnight */
/* rs-theme-is-dark: TRUE */

```
Could you confirm that's what you see as well?

Also, I'm not sure that this is related, but could you try updating the locale to something else? As an example try running `Sys.setlocale(locale = "English_US")`. Note that this change won't be preserved between R sessions.

**Comment by hezibu** [comment] 2019-05-31 08:48
Hi Maria,

Setting sys.locale didn't help.

I see the two lines mentioned and `rs-theme-is-dark`` is in fact ``TRUE``.
However, switching to idle fingers for example, i get this line in the network tab:

``idle_fingers.rstheme?dark = 0``

Another strange behavior I experience now is mismatch between preview and actual colors:

![image](https://user-images.githubusercontent.com/44232295/58693177-d6970580-8398-11e9-96fb-105f1c28eced.png)

**Comment by hezibu** [comment] 2019-06-02 17:48
I don't know what happened, but it seems to work now...

**Comment by MariaSemple** [comment] 2019-06-02 20:22
Well that's good news! I'm going to close this issue for now, but feel free to reopen it if the problem recurs.

**Comment by ronblum** [comment] 2019-06-07 13:40
This issue resurfaced. Copying over from #4914 (CC @joniok):

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335 (build 1379)
    OS Version      : Windows 10 x64 (build 17763)
    R Version       : 3.6.0

```
> rstudioapi::getThemeInfo()
$editor
[1] "Dracula"

$global
[1] "Modern"

$dark
[1] FALSE

$foreground
[1] "rgb(248, 248, 242)"

$background
[1] "rgb(40, 42, 54)"

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_Finland.65001    LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_Finland.65001   LC_NUMERIC=C                       
[5] LC_TIME=English_Finland.65001      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0  tools_3.6.0     rstudioapi_0.10
```

### Steps to reproduce the problem
I have a fresh install of RStudio 1.2  and I tried changing to a dark theme after installation. IDE theme remains light Modern instead of dark Modern for every theme.

### Describe the problem in detail

I have the exact problem as [4850](https://github.com/rstudio/rstudio/issues/4850). It seems that every theme has `isDark` value set as `FALSE`. I have checked this from the output of `rstudioapi::getThemes()`. Unfortunately I don't know how to reproduce the problem since this is the first time I have had problems with themes in RStudio 1.2.

I have tried reinstalling RStudio and also reinstalling after deleting RStudio caching files from AppData and AppData/Local folders of Windows.

**Comment by ronblum** [comment] 2019-07-01 13:46
@joniok Are you still running into this issue?

**Comment by joniok** [comment] 2019-07-02 04:43
> 
> 
> @joniok Are you still running into this issue?

Yes, the issue is still present and has not 'fixed itself' as with some users.

**Comment by MariaSemple** [comment] 2019-07-02 04:56
Can you share the output of running `rstudioapi::getThemes()` from the console?

**Comment by joniok** [comment] 2019-07-02 06:31
> 
> 
> Can you share the output of running `rstudioapi::getThemes()` from the console?

Here's the requested output:

```
> rstudioapi::getThemes()
$ambiance
$ambiance$name
[1] "Ambiance"

$ambiance$isDark
[1] FALSE


$chaos
$chaos$name
[1] "Chaos"

$chaos$isDark
[1] FALSE


$chrome
$chrome$name
[1] "Chrome"

$chrome$isDark
[1] FALSE


$clouds
$clouds$name
[1] "Clouds"

$clouds$isDark
[1] FALSE


$`clouds midnight`
$`clouds midnight`$name
[1] "Clouds Midnight"

$`clouds midnight`$isDark
[1] FALSE


$cobalt
$cobalt$name
[1] "Cobalt"

$cobalt$isDark
[1] FALSE


$`crimson editor`
$`crimson editor`$name
[1] "Crimson Editor"

$`crimson editor`$isDark
[1] FALSE


$dawn
$dawn$name
[1] "Dawn"

$dawn$isDark
[1] FALSE


$dracula
$dracula$name
[1] "Dracula"

$dracula$isDark
[1] FALSE


$dreamweaver
$dreamweaver$name
[1] "Dreamweaver"

$dreamweaver$isDark
[1] FALSE


$eclipse
$eclipse$name
[1] "Eclipse"

$eclipse$isDark
[1] FALSE


$`idle fingers`
$`idle fingers`$name
[1] "Idle Fingers"

$`idle fingers`$isDark
[1] FALSE


$katzenmilch
$katzenmilch$name
[1] "Katzenmilch"

$katzenmilch$isDark
[1] FALSE


$`kr theme`
$`kr theme`$name
[1] "Kr Theme"

$`kr theme`$isDark
[1] FALSE


$material
$material$name
[1] "Material"

$material$isDark
[1] FALSE


$merbivore
$merbivore$name
[1] "Merbivore"

$merbivore$isDark
[1] FALSE


$`merbivore soft`
$`merbivore soft`$name
[1] "Merbivore Soft"

$`merbivore soft`$isDark
[1] FALSE


$`mono industrial`
$`mono industrial`$name
[1] "Mono Industrial"

$`mono industrial`$isDark
[1] FALSE


$monokai
$monokai$name
[1] "Monokai"

$monokai$isDark
[1] FALSE


$`night owl`
$`night owl`$name
[1] "Night Owl"

$`night owl`$isDark
[1] FALSE


$`pastel on dark`
$`pastel on dark`$name
[1] "Pastel On Dark"

$`pastel on dark`$isDark
[1] FALSE


$`solarized dark`
$`solarized dark`$name
[1] "Solarized Dark"

$`solarized dark`$isDark
[1] FALSE


$`solarized light`
$`solarized light`$name
[1] "Solarized Light"

$`solarized light`$isDark
[1] FALSE


$`textmate (default)`
$`textmate (default)`$name
[1] "Textmate (default)"

$`textmate (default)`$isDark
[1] FALSE


$tomorrow
$tomorrow$name
[1] "Tomorrow"

$tomorrow$isDark
[1] FALSE


$`tomorrow night`
$`tomorrow night`$name
[1] "Tomorrow Night"

$`tomorrow night`$isDark
[1] FALSE


$`tomorrow night 80s`
$`tomorrow night 80s`$name
[1] "Tomorrow Night 80s"

$`tomorrow night 80s`$isDark
[1] FALSE


$`tomorrow night blue`
$`tomorrow night blue`$name
[1] "Tomorrow Night Blue"

$`tomorrow night blue`$isDark
[1] FALSE


$`tomorrow night bright`
$`tomorrow night bright`$name
[1] "Tomorrow Night Bright"

$`tomorrow night bright`$isDark
[1] FALSE


$twilight
$twilight$name
[1] "Twilight"

$twilight$isDark
[1] FALSE


$`vibrant ink`
$`vibrant ink`$name
[1] "Vibrant Ink"

$`vibrant ink`$isDark
[1] FALSE


$xcode
$xcode$name
[1] "Xcode"

$xcode$isDark
[1] FALSE
`````

**Comment by joniok** [comment] 2019-08-11 11:49
Hi, my work laptop was recently formatted and Windows 10 was reinstalled for other reasons, but this problem did not occuranymore when installing a fresh version of RStudio 1.2. This means that from my part this problem is taken care of, since I cannot replicate the probelm or provide more information anymore. But thank you for your assistance! Hope this probelm doesn't reoccure.

**Comment by jmcphers** [comment] 2019-08-23 23:52
Closed since we don't have a repro; glad it is working for you now! Let us know if you see it again.

**Closed** 2019-08-23 23:52 UTC
Labels: bug, repro needed, themes

**Comment by EdGreen21** [comment] 2019-11-25 22:48
In case this helps diagnose the problem: this happened to me too on a new Windows10 machine. It turns out it was due to a mismatch between location settings (I live in Germany but have a UK laptop with international keyboard). When RStudio opened I got the following error:

During Startup - Warning message:
Setting LC_CTYPE = failed

Once I'd set all the locale settings to match up in Windows, this problem went away.

See also: https://community.rstudio.com/t/during-startup-warning-message-setting-lc-ctype-failed-on-windows/21451

Hope this helps

**Comment by gwd999** [comment] 2020-01-11 21:52
Updating RStudio to 1.2.5033 has brought up this issue/bug (dark themes show THEME$$isDark == FALSE) again. 
On my other laptop with RStudio 1.2.5001 DARK themes show correctly and so the fonts are readable in the dark themes. I have the same ~/.Renviron file in place on both laptops, which set the LC_ variables equal to "C", in order to cope with the 'Failed to set LC_' warnings/messages. I am running WINDOWS 10 Pro 64-bit on both machines, so the LOCALES do not seem to fix this issue, at least for me.

**Comment by WFB2** [comment] 2020-11-26 16:55
I have the same issue as the contributers above me.. It's also a new Windows10 machine. I do not get any errors.
My output of `rstudioapi::getThemes() ` looks similar to @joniok . Has there been any update on the issue?
Thanks in advance!

**Comment by matteodefelice** [comment] 2021-01-07 09:23
I also have this issue on my new Windows 10 machine, I solved the Locale issue. The output of  `rstudioapi::getThemes()` says that the dark themes have `isDark` to `FALSE`. Any solution to this? I have RStudio 1.3.1093
