### ISSUE TITLE
Behavior of devtools::document() in RStudio is differerent to command line

### ISSUE THREAD

**Issue by pat-s** [rstudio/rstudio#3880] opened 2018-11-13 10:41 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1114
    OS Version      : Arch Linux
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Clone a R pkg (e.g. https://github.com/mlr-org/mlr)
2. Open RStudio
3. Run `devtools::document()`
4. Experience strange behavior (see details)
5. Open an R vanilla session (R --vanilla)
6. Run `devtools::document()` 
7. See correct behavior of `devtools::document()`

### Describe the problem in detail

Somehow `devtools::document()` behaves differently when running it in Rstudio compared to running it in a terminal session.

1. A lot of warning messages about a missing "title field" (false positive?)
2. Affected .Rd files get deleted aferwards

![selection_017](https://user-images.githubusercontent.com/8430564/48408111-cab75f00-e738-11e8-944a-167193661ad1.png)

**Comment by ronblum** [comment] 2018-11-15 15:51
@pat-s Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.

**Comment by kevinushey** [comment] 2018-11-30 18:09
Likely a duplicate of https://github.com/rstudio/rstudio/issues/3464.

**Closed by kevinushey** 2018-11-30 18:09 UTC
Labels: bug

**Comment by ronblum** [comment] 2018-12-18 20:09
This appears to be fixed, using the example `mlr` package.
