### ISSUE TITLE
Figure-related YAML chunk options are ignored for the inline preview

### ISSUE THREAD

**Issue by netique** [rstudio/rstudio#12305] opened 2022-11-07 18:01 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.12.0-preview+314 "Elsbeth Geranium" Preview (f3eb68a11735d56130ea51cc72f96fb6d2bb7852, 2022-11-05) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0-preview+314 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
    OS Version.     : macOS Ventura 13.0
    R Version.      : 4.2.2 

### Steps to reproduce the problem

1. create a `.qmd` document in any format
2. use YAML-style chunk option to change any figure setting like `#| fig-asp: 1.5`
3. run all chunks and "knit" the document
4. observe that the plot in the editor completely ignores any figure-related settings, whereas the rendered document is fine

<img width="1508" alt="Snímek obrazovky 2022-11-07 v 18 59 56" src="https://user-images.githubusercontent.com/34926852/200381842-45a762fe-be3c-45ba-85fa-e563e8f0c7c3.png">

### Describe the problem in detail

The plot (no matter if in Source or Visual mode) in-line preview ignores any YAML-style figure-related chunk option.

### Describe the behavior you expected

The plot in-line preview should reflect the chunk option.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-11-18 14:35
@netique Thank you for raising the issue! I can reproduce it in:
- RStudio Desktop 1.4.1743 on MacOS 13
- RStudio Desktop 2022.12.0-preview+330 on MacOS3
- RStudio Server 2022.12.0-preview+330 on Ubuntu 20.04.5 via Chrome on MacOS 13

I believe this is the same bug as #4521, so I'm closing this one as duplicate and nothing it in there.

**Comment by ronblum** [comment] 2022-11-18 15:38
Ugh, thank you for putting me on the right path! I'll reopen this issue.

**Comment by cderv** [comment] 2023-03-16 11:38
Just for reference, a bunch of issues regarding plot should be dealt with and this seems related : https://github.com/rstudio/rstudio/issues/12740

**Comment by vancleve** [comment] 2023-07-13 19:10
Same as this issue? https://github.com/rstudio/rstudio/issues/11708

**Comment by jgutman** [comment] 2023-10-16 21:48
@vancleve @netique @andrewheiss I believe this is a duplicate of #11708 which we just closed in the recent RStudio daily builds, if you'd like to test that out and confirm if the issue is resolved

**Closed** 2023-10-16 22:23 UTC
Labels: bug, duplicate, plots, source editor
