### ISSUE TITLE
rstudio links against system qt library ignoring the rstudio-bundled qt version

### ISSUE THREAD

**Issue by datamole** [rstudio/rstudio#3128] opened 2018-07-07 16:49 UTC
I am compliling the latest version of rstudio from the github sources.

Rstudio doesn't compile against the system qt version 5.11. 
So I am installing the bundled qt version (5.10.1) via the dependency scripts. The cmake script subsequently confirms that it found and will be using the bundled qt version.

Compilation runs without errors, but when I execute the rstudio binary I get the following error message:

path/rstudio/bin/rstudio: relocation error: path/rstudio/bin/rstudio: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev version Qt_5 not defined in file libQt5Positioning.so.5 with link time reference

The output of running  "ldd rstudio" suggests that the binary links against the system qt library in /usr/lib64/ instead of the bundled one that the qmake script found. 

I tried both without the -DQT_QMAKE_EXECUTABLE option as well as specifying the path to the bundled qmake explicitly for the cmake command. It makes no difference.

I guess cmake doesn't configure for linking against the bundled qt-version correctly so the program crashes at runtime linking against another qt version?

**Comment by gtritchie** [comment] 2018-07-11 20:35
What Linux flavor are you building on?

**Comment by gtritchie** [comment] 2018-07-11 20:44
Also, see discussion in #3061. The primary mechanism for building RStudio from source is via the make-package script. The INSTALL docs at the root of the repo don't reflect this and need to be updated.

**Comment by gtritchie** [comment] 2018-07-12 17:42
I'm going to make this a duplicate of #3061 and track the issue there. Most likely we'll just update the INSTALL document to reflect using make-package script instead of `make install`, but would be nice if `make install` did the right thing, too.

**Closed by gtritchie** 2018-07-12 17:42 UTC
Labels: developer, duplicate
