### ISSUE TITLE
Switching to visual mode rewrites one-line latex blocks and breaks the markdown document

### ISSUE THREAD

**Issue by LDSamson** [rstudio/rstudio#9216] opened 2021-04-11 10:42 UTC
### System details

    RStudio Edition : 
    RStudio Version :  1.4.1106
    OS Version      :  Windows 10
    R Version       :  4.0.3

### Steps to reproduce the problem

With the following RMarkdown document, switch back and forth to visual editor a few times. (the specific latex command does not matter)

````markdown
---
output: pdf_document
---

# Any document titel

```{=tex}
\begin{alatexcommand}
```

some text here

```{r }
hist(iris$Sepal.Length)
```

`\end{alatexcommand}`{=tex}



````

### Describe the problem in detail

If the RMarkdown document mentioned above is switched to visual mode, the latex code chunks are removed and the latex command is placed outside the code chunks (just like `\begin{customlatexcommand}`) . For me, within a bookdown project, this behavior already breaks my code. If switched back and forth from visual editor again, the code becomes worse and eventually one cannot switch to visual mode anymore (error: unable to activate visual mode (error passing code chunks out of document)). This is the rewritten document:

````markdown
---
output: pdf_document
---

# Any document titel

```{=tex}
\begin{alatexcommand}

some text here

```{r }
hist(iris$Sepal.Length)
```

\end{alatexcommand}
```
````

### Describe the behavior you expected

I expect visual Markdown editor to not change any latex code chunks in the first place; they should be left alone ideally.
(If there is a workaround tip how I can switch off this behavior until this is fixed and still use the visual editor, I would be glad to hear it)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-04-14 16:42
@LDSamson Thank you for raising this! I can reproduce this in RStudio Server 1.4.1106 on Ubuntu 20.04 via Chrome on MacOS 11.3. I'll mark this for review as we continue development of RStudio.

Note: This occurs after two back-and-forth switches. After only one switch, the code becomes:

````
---
output: pdf_document
---

# Any document titel

\begin{alatexcommand}

some text here

```{r }
hist(iris$Sepal.Length)
```

\end{alatexcommand}
````

**Comment by jjallaire** [comment] 2021-07-21 19:17
The issue here seems to be that pandoc treats `\begin` and `\end` specially (which is I'm imagining why you have the markdown written as you do). I wasn't aware of this. It should be straightforward to also treat them specially in the editor (and always put them in tex blocks). Should have a fix for this very soon.

**Comment by jjallaire** [comment] 2021-07-23 12:15
With this commit we now do special handling for `\begin` and `\end`, ensuring that if they exist by themselves within a block that they become a proper LaTeX raw block (and thus evade pandoc's special handling of them, which attempts to vacuum up everything in between as a raw tex block): https://github.com/rstudio/rstudio/commit/ea3f25ea466d5215cf2cd759251d76feb7390fa8

Here's what the visual editor now transforms the test document into:

<img width="619" alt="Screen Shot 2021-07-23 at 8 06 53 AM" src="https://user-images.githubusercontent.com/104391/126780205-ff1b4155-1bbc-47bf-8059-5ace36099155.png">

**Comment by astayleraz** [comment] 2021-08-02 20:40
I verified in Daily Version 2021-07.0.285-2 that I am seeing the same consistent output as jjallaire after toggling many times and it is not changing any latex code chunks. Closing issue.

**Closed by astayleraz** 2021-08-02 20:41 UTC
Labels: bug, test, visual markdown editing
