### ISSUE TITLE
Postback scripts no longer work on macOS Electron builds

### ISSUE THREAD

**Issue by jcheng5** [rstudio/rstudio#11964] opened 2022-09-16 17:52 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 2022.11.0-daily+186 (2022.11.0-daily+186)
    OS Version      : macOS Monterey 12.5.1 (21G83)
    R Version       : 4.1.2 aarch64

### Steps to reproduce the problem

Press the Git Pull button on a repo that you cloned via SSH, using an SSH key that has a passphrase. (Maybe this also happens for https-cloned repos where the password isn't saved? I don't know, I always use SSH)

### Describe the problem in detail

You get this error:
```
ssh_askpass: exec(rpostback-askpass): No such file or directory
```

### Describe the behavior you expected

A popup should appear, prompting you to type in your passphrase.

There are a couple of things that appear to be behind this:

1. In the electron build, the postback scripts (like rpostback-askpass) have been moved to `RStudio.app/Contents/Resources/app/bin/postback`, but this is not added to the `$PATH` (however, `RStudio.app/Contents/Resources/app/bin/` is on the `$PATH`).
2. The `$RS_RPOSTBACK_PATH` is not set to the correct value; its current value is `/Applications/RStudio.app/Contents/Resources/app/rpostback` but it should be `/Applications/RStudio.app/Contents/Resources/app/bin/rpostback`. See [here](https://github.com/rstudio/rstudio/blob/4f7063b13bb0bae8377639a36d3ff4b7626de6e3/src/cpp/session/SessionMain.cpp#L2160-L2165)

If I type the following into the R console, everything works:
```
Sys.setenv(RS_RPOSTBACK_PATH="/Applications/RStudio.app/Contents/Resources/app/bin/rpostback")
Sys.setenv(PATH=paste0(Sys.getenv("PATH"), ":/Applications/RStudio.app/Contents/Resources/app/bin/postback"))
```

---

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jgutman** [comment] 2022-09-20 15:17
I'm working on fixing this! But this is a duplicate of #11693 so I'm going to close this

**Closed by jgutman** 2022-09-20 15:17 UTC
Labels: bug, vcs
