### ISSUE TITLE
Trying to save a .rmd file while installing/updating R packages makes R/RStudio crash

### ISSUE THREAD

**Issue by clayzermk1** [rstudio/rstudio#8494] opened 2020-11-30 20:55 UTC
### System details
    RStudio Edition : Desktop (preview)
    RStudio Version : Version 1.4.1048
    OS Version      : macOS 10.15.7 (19H15)
    R Version       : 4.0.2 (2020-06-22)

### Steps to reproduce the problem
1. Begin updating or installing packages, either from the `install.packages()` function, or using the IDE's package update tool.
1. Make a change to a .rmd file.
1. Attempt to save the file.
1. Observe that the package installation freezes, and that the file is not saved.
1. Wait a couple minutes to receive a "Terminate R" modal with the text:
```
R is not responding to your request to interrupt processing so to stop the current operation you may need to terminate R entirely.

Terminating R will cause your R session to immediately abort. Active computations will be interrupted and unsaved source file changes and workspace objects will be discarded.

Do you want to terminate R now?

[No] [Yes]
```

Selecting "Yes" will result in a R fatal error dialog. See screenshot below.
![image](https://user-images.githubusercontent.com/1075015/100662856-50031180-330a-11eb-917c-b743a784b34b.png)

### Describe the problem in detail
While attempting to save a file I was working on during package updates, the R process unexpectedly experienced a fatal error. I am able to reproduce this consistently.

The diagnostics report is attached.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5618655/diagnostics-report.txt)

### Describe the behavior you expected
I expected that I could save files in the IDE without crashing the R process.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-11-30 23:20
This is a somewhat long-standing issue caused by the fact that:

1. The installation of R packages is done in a separate R child process launched via `system()`;
2. When `system()` is running, RStudio doesn't receive any "events" from R and so doesn't get a chance to process RPCs (e.g. requests for save).

A similar way to reproduce is via:

```
system("sleep 20")
```

and note that files cannot be saved while that command is running.

**Comment by clayzermk1** [comment] 2020-12-01 17:45
This stood out to me as a VS Code user since I can save files at any point regardless of whether a process is running in the editor such as an internal script execution.

What about crashing the IDE's R process though? I get that a save may not execute while the child process is running, but attempting to save seems to crash the parent process entirely. It halts the child process and it never completes.

**Comment by jeffvroom** [comment] 2021-06-09 02:44
This should be fixed or at least greatly improved now with the handle-offline and async-rpc features in the fix for https://github.com/rstudio/rstudio/issues/2038

We no longer tie-up browser connections for RPC requests and certain operations that don't depend on the R runtime will run in a separate thread, even when R is busy.  Currently these operations include new file, save file, and access to the terminal.

If you find an operation that (frustratingly) blocks when running an R command like:

> system("sleep 30") 

let me know and I can see if it's possible to add it to the "offlineable" requests.

**Comment by ronblum** [comment] 2021-06-28 19:01
@jeffvroom Saving works. Only some file types open up, though. For example, R script, R Notebook, and SQL files open up. R Markdown doesn't at all, and for Shiny the initial pop up window appears but not the file itself—though in both cases, the request is queued up so that the next steps occur after the Console is no longer busy.

**Comment by mikebessuille** [comment] 2021-07-19 19:58
Is the behaviour Ron describes by design?  Sounds like this might be fully fixed?

**Comment by jeffvroom** [comment] 2021-07-28 22:26
To create an RMarkdown file or Shiny app requires use of the unsatisified_dependencies API that can't run offline as it makes calls to check on the existence of the set of packages provided by the client. The response is used by the IDE to determine if you need to install packages first. I created a separate issue for these two file types:

https://github.com/rstudio/rstudio/issues/9672

**Comment by ronblum** [comment] 2021-08-02 13:04
This is working as expected, then, when running `system("sleep 20")` in
- RStudio Desktop 2021-07.0.270 on MacOS 12 beta
- RStudio Server 2021-07.0.271 on SLES 15 SP3 via Chrome on MacOS 12 beta

I am happily closing this issue as verified.  :)

**Closed by ronblum** 2021-08-02 13:04 UTC
Labels: bug, test
