### ISSUE TITLE
Shiny numeric inputs increment twice on arrow click

### ISSUE THREAD

**Issue by schloerke** [rstudio/rstudio#6953] opened 2020-05-26 14:27 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959, 1.4.388
    OS Version      : macOS
    R Version       : 4.0.0

### Steps to reproduce the problem

Run any shiny app with a numeric input in pane or window.  Click the up or down arrow buttons in the numeric input box. 

```r
# install.packages("shiny")

library(shiny)
ui <- fluidPage(
  numericInput("hadley", "n", value = 5, step = 3)
)
shinyApp(ui, function(input, output) {
  observe({str(input$hadley)})
})
```

(The step value is not required to produce the bug. I gave it a value that wasn't `1` to help determine the numeric change is being submitted twice.)

### Describe the problem in detail

Observe the number is incremented twice.  Ex: Click "up arrow" and the value will jump from `5` to `11` (`5 + 3 + 3`).

### Describe the behavior you expected

I would expect that clicking an arrow would only increment the value once. Ex: Click the "up arrow" and the original value is `5` would produce a final value of `8` (`5 + 3`).

This behavior works as expected in a browser even if the Shiny app is run by the IDE.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

cc @hadley

**Comment by schloerke** [comment] 2020-05-26 14:41
In my local testing, I have removed all JS Event Listeners and the value still increments twice.  

The value is not reported to the server as that event listener was removed, but I don't know what would still cause the input value to increment twice.

**Comment by kevinushey** [comment] 2020-05-26 18:00
For me, tapping with a trackpad, the number increments as many as 6 times!

**Comment by schloerke** [comment] 2020-05-26 18:02
It's going from `5` to `35`?!?

**Comment by gtritchie** [comment] 2020-05-26 18:14
Doesn't repro for me on Windows (but does on Mac).

**Comment by gtritchie** [comment] 2020-05-26 18:18
Also repros in other spin controls in the IDE, such as the tab width setting. Using arrow keys correctly increments / decrements by 1, but clicking has the issue.

<img width="592" alt="screenshot of global options showing a spin control" src="https://user-images.githubusercontent.com/10569626/82935821-8c604a00-9f42-11ea-8a02-0145632e40ba.png">

**Comment by kevinushey** [comment] 2020-05-26 18:23
For me, using arrow keys still increments the value by more than 1 (e.g. right now it increments / decrements by 3).

**Comment by schloerke** [comment] 2020-05-26 18:25
@kevinushey  

The example shiny app above has a step size of 3. The app should be inc/decrementing by 3's. 

When clicking the arrows, for me it was jumping by 6's.

**Comment by kevinushey** [comment] 2020-05-26 18:29
Thanks -- I missed that.

**Comment by gtritchie** [comment] 2020-05-26 18:44
As a datapoint, I did a build with Qt 5.14.2 and the issue went away, suggesting it's going to be a Mac-specific QtWebEngine thing.

**Comment by jmcphers** [comment] 2020-06-10 22:46
We are not going to update to QtWebEngine in Water Lily, so unless there's another way around this, we are not going to fix it in Water Lily. (We could create our own number control but the problem doesn't warrant the effort, esp. since it's already fixed upstream.)

**Comment by NickPyll** [comment] 2020-06-17 13:00
Yeah this is an annoying issue...I fixed mine by setting `step` at half the desired value. So, I wanted it to step 1 at a time and I set `step = .5`. Fo you, you might try 1.5. Hacky, but it works...

**Comment by jmcphers** [comment] 2020-07-13 22:39
Moving to 1.5 as we're not likely to do a major Qt update in 1.4, either.

**Comment by gtritchie** [comment] 2021-02-18 01:03
Confirmed this is fixed by switching to Electron (tested in prototype, keeping open until we have production code).

**Comment by gtritchie** [comment] 2021-11-25 20:31
Confirmed again with latest code (and that it still repros in Ghost Orchid, and latest daily build).

**Comment by gtritchie** [comment] 2022-03-30 17:01
(Re) confirmed this is working as expected on Electron using 2022.06.0-daily+244 on macOS 12.3.

**Closed by gtritchie** 2022-03-30 17:01 UTC
Labels: bug, macos, qtwebengine, shiny, electron, test
