### ISSUE TITLE
Blurry fonts and icons in MacOS

### ISSUE THREAD

**Issue by jclopeztavera** [rstudio/rstudio#4953] opened 2019-06-14 02:00 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.242 
    OS Version      : MacOS Mojave 10.14.5 (18F132)
    R Version       : 3.5.3

### Steps to reproduce the problem
1. Open RStudio on MacOS. 
2. Maximize window.
3. Open any other application or go back to another Desktop.
4. Wait some (undefined) time.
5. The fonts and icons are blurry. 

### Describe the problem in detail
In MacOS, The fonts and icons of all interfaces (Console, Scripts, Menus) get blurry after spending some time in another application while RStudio is maximized in its own desktop.

I had been experiencing this issue for some time. I re-installed RStudio 1.2. I looked at a similar, closed, issue that happened on Windows [Blurry font in Windows #2784](https://github.com/rstudio/rstudio/issues/2784) and I installed the latest RStudio build, which is referenced in this Issue. 

My laptop characteristics are: 
MacBook Pro (Retina, 13-inch, Early 2015)
OS Version: MacOS Mojave Version 10.14.5 (18F132)
Processor: 2.7 GHz Intel Core i5
Memory: 8 GB 1867 MHz DDR3
Startup disk: MacOS
Graphics: Intel Iris Graphics 6100 1536 MB

### Describe the behavior you expected
Not blurry fonts and icons. 

1. The output of sessionInfo() 
```
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.3  tools_3.5.3     packrat_0.5.0-6
```
2. The R code in question
NA
3. A diagnostics report
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3288695/diagnostics-report.txt)

**Comment by kevinushey** [comment] 2019-06-14 05:19
Can you also provide some information on your monitor configuration? Are you just using your laptop's built-in display, or an external display as well? Are you changing the display configuration while RStudio is open?

**Comment by jclopeztavera** [comment] 2019-06-14 15:44
Can you also provide some information on your monitor configuration? 
**Built-in display**
**13.3-inch (2560 x 1600)**
**Intel Iris Graphics 6100 1536 MB graphics**
** Resolution: Default for display**
**Nighshift: Off**

Color LCD Profile (*.icc format not supported by GitHub, needs to be changed backto color.icc) [color.txt](https://github.com/rstudio/rstudio/files/3291288/color.txt)



Are you just using your laptop's built-in display, or an external display as well? 
**Just the built-in display**

Are you changing the display configuration while RStudio is open?
**No**

**Comment by ronblum** [comment] 2020-01-03 18:39
@jclopeztavera have you continued to try the 1.3 downloads, and if so, is the problem still occurring?

**Comment by jclopeztavera** [comment] 2020-01-14 20:11
Thanks for the follow up. I have just downloaded a new RStudio 1.3, although I also had 1.3 when I opened this issue. Now I have:

```
RStudio Edition : Desktop
RStudio Version : Version 1.3.740
OS Version      : MacOS Catalina 10.15.2 (19C57)
R Version       : 3.6.1
```
The  problem seems to have been fixed. However, I am not sure if this is due to a change of laptop to: 

MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
2.3 GHz Quad-Core Intel Core i5
Memory 16 GB 2133 MHz LPDDR3
Graphics Intel Iris Plus Graphics 655 1536 MB

Please let me know how can I help.

**Comment by ronblum** [comment] 2020-01-15 21:48
@jclopeztavera Thank you for the update! There are a number of possible reasons for the fix: the new hardware, the update to Catalina, or the 1.3 build, and maybe more. Since the problem is resolved—for whatever reason—I'm going to close the issue. If anyone runs into a similar issue on, esp. on a Mac, this ticket can be updated, and we'll revisit then. In the meantime, thank you for the offer to help!

**Closed by ronblum** 2020-01-15 21:48 UTC
Labels: macos, repro needed

**Comment by dill** [comment] 2020-08-04 09:37
In case it's useful to anyone else, I had the same issue with a MacBook Air (Retina, 13-inch, 2020), 1.1 GHz Quad-Core Intel Core i5 running Catalina 10.15.5.

Upgrading from RStudio 1.3.959 to 1.3.1056 solved the issue for me (I didn't change anything else).

**Comment by dill** [comment] 2020-08-10 11:35
Sorry, following-up on this again. The issue I've now found is that moving from external to laptop monitor leads to fuzzy fonts (had not realised this was the path that lead me to the above). This is solved by closing and re-opening RStudio. 

@ronblum would you prefer I open a new issue with this in as it's somewhat different to the above?

**Comment by ronblum** [comment] 2020-08-10 15:33
@dill No problem! Does changing the rendering help? https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors  If not, then yes, please open a new issue, since the external monitor is involved, too. Thanks!

**Comment by dill** [comment] 2020-08-19 07:55
Thanks @ronblum, switching to software rendering seems to fix this 👍. One minor issue when switching between screens is that you initially have RStudio windows that look like those below. This is fixed by resizing the window. I don't find this to be a major problem but thought I'd report here anyway.

laptop -> external
![Screenshot 2020-08-19 at 08 51 08](https://user-images.githubusercontent.com/1953/90607753-9324f300-e1f9-11ea-8740-48631de04ced.png)


external -> laptop
<img width="1200" alt="Screenshot 2020-08-19 at 08 51 52" src="https://user-images.githubusercontent.com/1953/90607762-961fe380-e1f9-11ea-8a43-4ec486508c9e.png">

**Comment by ronblum** [comment] 2020-08-19 14:14
@dill I'm glad switching rendering engines worked. As for the second issue, just to make sure, do  you mean that the Environment Pane is getting zoomed or expanded? If so, would you mind opening a new issue for that? This way we can treat the two issues separately. Thanks!

**Comment by dill** [comment] 2020-08-19 14:18
@ronblum I don't think it's the environment pane specifically, I think it's what ever is in the top left corner gets zoomed or the whole window gets shrunk to the top corner, because of the retina scaling? (Though I am no expert on how the retina graphics actually work, I should stress!) Happy to open an issue if the above makes sense to you!

**Comment by ronblum** [comment] 2020-08-19 16:45
@dill Yes, that makes sense, and thank you!
