### ISSUE TITLE
rstudio over x2go: X11 connection broke

### ISSUE THREAD

**Issue by benzipperer** [rstudio/rstudio#3382] opened 2018-08-28 15:04 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Ubuntu 16.04
    R Version       : 3.4.4
    x2go server version: 4.1.0.3

### Steps to reproduce the problem

Log into an XFCE desktop using x2go and run rstudio.

### Describe the problem in detail
The rstudio GUI does not load successfully:

```
$ rstudio
The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":50"
      after 404 requests (404 known processed) with 0 events remaining.
```

### Describe the behavior you expected
rstudio should open successfully as it does using other remote desktop solutions (e.g., ssh -X, nomachine).

### Additional materials
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/2328478/diagnostics-report.txt)

**Comment by kevinushey** [comment] 2018-08-28 16:14
Do you have any better luck with the [preview release](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by benzipperer** [comment] 2018-08-28 16:40
Thanks for the suggestion! I didn't know about the preview release. Unfortunately after installation I can't seem to open preview release at all:

Using x2go the preview results in 
```
$ rstudio
Could not initialize GLX
Aborted (core dumped)
```

Over ssh -X, the preview results in 
```
$ rstudio
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Received signal 6
#0 0x7fce977830a5 <unknown>
#1 0x7fce964c4141 <unknown>
#2 0x7fce9778343d <unknown>
#3 0x7fce936c6390 <unknown>
#4 0x7fce91ba8428 gsignal
#5 0x7fce91baa02a abort
#6 0x7fce9396905e QMessageLogger::fatal()
#7 0x7fce9105f9e6 <unknown>
#8 0x7fce9105fd22 <unknown>
#9 0x7fce91061ed6 QQuickWidget::resizeEvent()
#10 0x7fce9c9db7ad <unknown>
#11 0x7fce94a2e7b2 QWidget::event()
#12 0x7fce9106284b QQuickWidget::event()
#13 0x7fce9c9db9f6 <unknown>
#14 0x7fce949f163c QApplicationPrivate::notify_helper()
#15 0x7fce949f8987 QApplication::notify()
#16 0x7fce93b51028 QCoreApplication::notifyInternal2()
#17 0x7fce94a26f22 QWidgetPrivate::sendPendingMoveAndResizeEvents()
#18 0x7fce94a2aa13 QWidgetPrivate::show_helper()
#19 0x7fce94a2a9b7 QWidgetPrivate::showChildren()
#20 0x7fce94a2aa2f QWidgetPrivate::show_helper()
#21 0x7fce94a2db65 QWidget::setVisible()
#22 0x7fce94a2a9c8 QWidgetPrivate::showChildren()
#23 0x7fce94a2aa2f QWidgetPrivate::show_helper()
#24 0x7fce94a2db65 QWidget::setVisible()
#25 0x559ad8584d29 <unknown>
#26 0x559ad8585d6b <unknown>
#27 0x7fce93b7d181 QObject::event()
#28 0x7fce949f163c QApplicationPrivate::notify_helper()
#29 0x7fce949f8987 QApplication::notify()
#30 0x7fce93b51028 QCoreApplication::notifyInternal2()
#31 0x7fce93b53abb QCoreApplicationPrivate::sendPostedEvents()
#32 0x7fce93ba5b63 <unknown>
#33 0x7fce8ab78197 g_main_context_dispatch
#34 0x7fce8ab783f0 <unknown>
#35 0x7fce8ab7849c g_main_context_iteration
#36 0x7fce93ba51af QEventDispatcherGlib::processEvents()
#37 0x7fce8681fb81 <unknown>
#38 0x7fce93b4f89a QEventLoop::exec()
#39 0x7fce93b58424 QCoreApplication::exec()
#40 0x559ad85555a3 <unknown>
#41 0x7fce91b93830 __libc_start_main
#42 0x559ad8558e8b <unknown>
  r8: 0000000000000049  r9: 00007fce9cd43940 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffe3d139360 r13: 0000559adaafa710 r14: 0000559ada8e07d0 r15: 00007ffe3d1398e0
  di: 00000000000035a6  si: 00000000000035a6  bp: 0000559adaafa710  bx: 00007fce93c398a0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007fce91ba8428  sp: 00007ffe3d139148
  ip: 00007fce91ba8428 efl: 0000000000000206 cgf: cccc000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[13845:13845:0100/000000.899764:ERROR:broker_posix.cc(43)] Invalid node channel message
```

And using nomachine the preview results in 
```
$ rstudio
QOpenGLShader::compile(Vertex): failed
QOpenGLShader::compile(Fragment): failed
Could not link shader program:
 ""
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7f6623b6d0a5 <unknown>
#1 0x7f66228ae141 <unknown>
#2 0x7f6623b6d43d <unknown>
#3 0x7f661fab0390 <unknown>
#4 0x7f661d15d8b3 <unknown>
  r8: 0000000000000049  r9: 0000000000000000 r10: 00007f662912e250 r11: 00007f6615ddd2b0
 r12: 0000000000000000 r13: 00007fff0b922870 r14: 0000000000000001 r15: 0000562e8c888fa8
  di: 0000000000000000  si: 0000562e8cdadec8  bp: 0000000000000001  bx: 0000000000000000
  dx: 0000562e8cdadeb8  ax: 0000562e8c888fa8  cx: 0000562e8c888fa8  sp: 00007fff0b9226e0
  ip: 00007f661d15d8b3 efl: 0000000000010246 cgf: 0000000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[18715:18715:0100/000000.357128:ERROR:broker_posix.cc(43)] Invalid node channel message
```

**Comment by kevinushey** [comment] 2018-08-28 16:50
You might need to enforce software rendering. Does the following help at all?

```
QMLSCENE_DEVICE=softwarecontext rstudio
```

**Comment by benzipperer** [comment] 2018-08-28 17:50
Thanks!

Enforcing software rendering seems to work for remote connections using ssh -X and nomachine, but under x2go it still produces an error:
```
$ QMLSCENE_DEVICE=softwarecontext rstudio
Could not initialize GLX
Aborted (core dumped)
```
Is there some additional output that I can send that would be useful?

**Comment by kevinushey** [comment] 2018-08-28 17:52
You could also try installing the requisite OpenGL drivers -- e.g. with Debian repositories something of the form

```
sudo apt-get install libgl1-mesa-dri
```

should help.

**Comment by benzipperer** [comment] 2018-08-28 20:13
Hm, these are already installed along with libgl1-mesa-glx. I also installed libgl1-mesa-dev, libgl1-mesa-dri-lts-xenial, libgl1-mesa-dev-lts-xenial, libgl1-mesa-glx-lts-xenial, but no luck. After installation and restarting the x2goserver service I still get the same error

```
$ QMLSCENE_DEVICE=softwarecontext rstudio
Could not initialize GLX
Aborted (core dumped)
```

maybe this means there is some underlying problem with opengl and x2go

**Comment by benzipperer** [comment] 2018-08-31 02:59
Thank you so much! This does work for me with X2Go and RStudio 1.1.456.

Unfortunately this modification also prevents Atom from being run. 

I guess I need to move these queries over to x2go.

**Comment by narendramukherjee** [comment] 2018-08-31 03:42
Just pointing out that this suggestion works for me as well, on Ubuntu 18.04 running RStudio on a MATE desktop through X2Go. thanks for the help :)

**Comment by kevinushey** [comment] 2018-08-31 15:53
If you can reproduce these issues with some of the example Qt applications, you might consider filing a bug report at https://bugreports.qt.io/. I'm not sure if Qt explicitly attempts to support desktop applications with X11 forwarding, though.

**Comment by jmcphers** [comment] 2018-09-04 21:58
I'm closing this here since ultimately it's out of our control and will probably need to be worked around by getting GLX/OpenGL support configured properly in x2go.  This might help:

https://www.hoffman2.idre.ucla.edu/access/x11_forwarding/

> . Starting in Xorg 1.17 (running on CentOS 6.9 and 7.x; Ubuntu version 15.04 and up and other linux distributions) indirect GLX was disabled by default, to enable indirect GLX and to allow remote visualization on the cluster of applications that use OpenGL (such as Abaqus, matlab, etc.) on your linux box you will have to locate the executable file Xorg (which is located in /usr/bin in CentOS), make a copy and create a wrapper to it in which Xorg is invoked with the +iglx flag.

**Closed by jmcphers** 2018-09-04 21:58 UTC
