### ISSUE TITLE
When filtering tibble inside DataViewer and clicking into a nested list item for details, results show non-filtered tibble’s list value at this position instead of currently filtered/selected row's list value

### ISSUE THREAD

**Issue by rweberc** [rstudio/rstudio#7546] opened 2020-08-07 21:14 UTC
### Where is the bug?

Data Viewer in RStudio

### Describe the problem in detail

When using the "magnifying glass" tool in DataViewer to look at a nested list in a tibble that has been filtered within the DataViewer, the value that is shown corresponds to the non-filtered row at the position selected, rather than the currently selected row's value.

### Steps to reproduce the problem

1. Run the following:

```
df <- dplyr::tribble(
  ~ id, ~ val,
  "1", list(1, 2, 3),
  "2", list(4, 5, 6),
  "3", list(7, 8, 9)
) 

View(df)
```

2. In Data Viewer, filter to `id` equals `3`:

![image](https://user-images.githubusercontent.com/6138269/89686165-d44d0700-d8cb-11ea-9d1c-fc0780166a3f.png)

3. Click the magnifying glass in the 'val' cell (next to `list(7, 8, 9)`).

4. Values displayed for `df[[2]][[1]]` of the unfiltered data frame (`list(1, 2, 3)`) rather than `list(7, 8, 9)` as expected from the specific cell clicked on:

![image](https://user-images.githubusercontent.com/6138269/89686361-41609c80-d8cc-11ea-8ad2-807fd84c3a3e.png)

### Environment
```
R Version: 3.6.1
Dplyr: 1.0.1
RStudio Desktop (Version: 1.3.1056)
Windows 10

R Version: 3.6.1
Dplyr: 0.8.5
RStudio Desktop (Version: 1.2.5019)
Windows 10 Version 1803
```

**Comment by ronblum** [comment] 2020-08-10 16:43
@rweberc Thank you for filing this. I can reproduce this in RStudio Desktop 1.4.673, as well. We'll review the bug as we continue developing RStudio.

**Comment by noahatchison** [comment] 2021-08-19 15:42
This issue still exists in the following environment: 
```
R Version: 4.1.0
dplyr: 1.0.7
RStudio Desktop: 1.4.1717
Windows 10: 19043
```

**Comment by ronblum** [comment] 2021-08-19 16:18
Reproduced in 
- RStudio Desktop 2021-08.0.317 on MacOS 12 beta
- RStudio Server 2021-08.0.317 via Safari on MacOS 12 beta

**Comment by jgutman** [comment] 2022-01-13 16:27
This is a duplicate of #9960 -- will address the issue there.

**Closed by jgutman** 2022-01-13 16:27 UTC
Labels: bug, reproducible, data viewer, backlog
