### ISSUE TITLE
Unexpected "Find in Files" > "Replace" behaviour when finding a regular expression

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudio#9344] opened 2021-05-13 18:22 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1707 (“Juliet Rose” (e10cd663, 2021-05-10) for macOS)
    OS Version      : 10.15.7
    R Version       : 4.0.2 (2020-06-22)

### Steps to reproduce the problem

I'm in an RStudio project (a package). I use "Find in Files" to search for `otherpkg::fun\b` (note the `\b` word boundary) and check "Regular expression". The expected instances are found. But when I try to do wholesale replacement with `fun`, the replacement text is just the found text, i.e. it's a no-op.

### Describe the problem in detail

This behaviour makes it hard to use RStudio to accelerate the process once you've decided to import `fun` from `otherpkg` into your own namespace.

### Describe the behavior you expected

I expected instances of `otherpkg::fun\b` to replaced with `fun` (or whatever I asked for).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

https://user-images.githubusercontent.com/599454/118169145-75c63380-b3dd-11eb-9777-359a3ddadbbb.mp4

**Comment by ronblum** [comment] 2021-05-13 19:55
Reproduced in RStudio Desktop 1.3.1093 on MacOS 11.3.

**Comment by mikebessuille** [comment] 2021-05-17 17:21
Need to determine how badly regular expressions are broken; is it just certain tags?

**Comment by melissa-barca** [comment] 2021-05-18 15:28
Interestingly, when "Whole word" is checked the replace works as expected. Behind the scenes, all "Whole word" does is add `\b`.

**Comment by ronblum** [comment] 2021-05-18 21:56
Replace works correctly with regular expressions when using `^` and `*` in them.

Note: a regex with `+` doesn't find any matching files, which is a separate issue.

**Comment by melissa-barca** [comment] 2021-05-18 22:58
This issue with regular expressions here only occurs when trying to perform a replace because of the difference in how we search for a word when performing a replace vs in a find. When doing a find, we use `grep -f` to pass the search pattern via a file so we don't have to worry about escaping, but when we do the replace we use `boost::regex_replace` with the `boost::format_sed` pattern which must be interpreting the pattern as if it were entered at the command line (expecting escapes).

For example, if you have files `search` and `pattern`:
```
$ cat pattern
purr::map\b
$ cat search
purr::map(dots, as_dribble)
```
and pass them to grep, you're able to get the desired result:
```
$ grep -f ./pattern search
purr::map(dots, as_dribble)
```
whereas if you pass the pattern directly with `$ grep purr::map\b`, there are no results. In this case, `\b` needs to be escaped so `$ grep purr::map\\b` will give the desired results. To fix this, we need to tweak the way we are performing the replace to account for this difference. 


@ronblum `+` won't work because `grep` uses [Basic Regular Expressions](https://www.gnu.org/software/sed/manual/html_node/BRE-vs-ERE.html), but escaping plus `\+` should work.

**Comment by ronblum** [comment] 2021-05-19 13:36
@melissa-barca I didn't realize that the pattern is reversed in ERE—and thank you, `\+` works.

**Comment by mikebessuille** [comment] 2021-06-01 17:42
regex not completely broken, just word boundaries.  Therefore not critical for 1.5.

**Comment by jgutman** [comment] 2022-01-13 16:46
This is closely related to #9813

**Comment by jgutman** [comment] 2022-01-14 22:57
Need to address together with #3572

**Comment by jgutman** [comment] 2022-01-25 17:38
> @melissa-barca I didn't realize that the pattern is reversed in ERE—and thank you, `\+` works.

As part of resolving this issue, we've actually changed Find in Files to use ERE, not BRE as previously. We'll have more info on this closer to release, but essentially, you now no longer escape `\+` to use it as a quantifier -- `\+` matches a literal plus sign, and `+` with no escaping matches 1 or more instances of the preceding expression. More detail in the comments and QA notes of the linked PR (#10362) .

**Comment by jmcphers** [comment] 2022-01-25 17:44
>  but essentially, you now no longer escape \+ to use it as a quantifier -- \+ matches a literal plus sign

We should definitely document this behavioral change (BRE -> ERE) in `NEWS` if we haven't already.

**Comment by jgutman** [comment] 2022-01-25 17:46
> > but essentially, you now no longer escape + to use it as a quantifier -- + matches a literal plus sign
> 
> We should definitely document this behavioral change (BRE -> ERE) in `NEWS` if we haven't already.

Absolutely! this is for Spotted Wakerobin, so it's in the NEWS file for that branch. Since that's rather abbreviated though, we might want to include a more _extended_ version of the differences in a blog post or something similar

**Comment by jgutman** [comment] 2022-01-25 17:51
Some examples to test:

In `~/test_find_in_files.R`:
```
# this should get replaced 
purrr::map(1:5, print)

# this should not get replaced
"mapping"

# this should also get replaced
"Map this!"

"making a comment (in parentheses)"
```
Search term 1.
![image](https://user-images.githubusercontent.com/7817881/151030116-9578f9d4-7da3-4118-8418-847fb42b83be.png)
Replacement 1. 
![image](https://user-images.githubusercontent.com/7817881/151030354-42a1e0ad-c58e-41f1-a575-ad88e5bbd988.png)

Search term 2.
![image](https://user-images.githubusercontent.com/7817881/151031190-55a14c4f-8e22-4b44-8e1b-ce41d8f05106.png)
Replacement 2.
![image](https://user-images.githubusercontent.com/7817881/151031370-6d745fff-d774-4b04-a65b-fcf51f52a671.png)

Final state of `~/test_find_in_files.R`:
```
# this should get replaced 
purrr::walk(1:5, print)

# this should not get replaced
"mapping"

# this should also get replaced
"walk this!"

"making a comment {in parentheses}"
```

**Comment by kevinushey** [comment] 2022-01-25 21:27
For NEWS, we can highlight that the Find in Files regular expression engine now more closely matches the default engine used by R, as well.

**Comment by timtmok** [comment] 2022-01-27 14:42
Works on Mac and Windows

**Closed** 2022-01-27 14:43 UTC
Labels: bug, find in files
