### ISSUE TITLE
Rstudio 1.4 - Visual editor - option to close code chunks

### ISSUE THREAD

**Issue by WattsMatthew** [rstudio/rstudio#8672] opened 2020-12-31 13:51 UTC
It would be really useful to have an option in the visual editor to close code chunks, so you only get the output only i.e. a table or figure. This feature is available in the usual R-markdown view. For example, I'm currently writing a paper using in visual editor mode, i'm done with all the code and don't need to see it anymore - so the code chunks get in the way.

**Comment by ronblum** [comment] 2021-01-04 16:17
@WattsMatthew Thank you for the suggestion! We'll review it as we continue development of RStudio.

**Comment by ronblum** [comment] 2021-07-06 15:03
Pinging this to unstale it—I think we should still consider this. I'll mark it as "Later," though.

**Comment by jjallaire** [comment] 2021-09-13 18:15
Closing as duplicate of https://github.com/rstudio/rstudio/issues/8613

**Closed by jjallaire** 2021-09-13 18:15 UTC
Labels: enhancement, visual markdown editing, backlog
