### ISSUE TITLE
Input/output error when using textbox in Open file menu

### ISSUE THREAD

**Issue by dfalty** [rstudio/rstudio#4059] opened 2018-12-18 23:11 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.456 & 1.2.1194-1
    OS Version      : RHEL 7.3

### Steps to reproduce the problem
1. Select File -> Open File
2. Try typing out the file to open (same results using full path as relative)
3. Select Open
4. Observe empty source pane open and error popup

### Describe the problem in detail
![image](https://user-images.githubusercontent.com/15237845/50188663-f30e1c80-02e7-11e9-9183-bbf30f51971e.png)

**Comment by GWarsow** [comment] 2019-05-07 11:21
Is there some estimate, when this bug will be fixed?

**Comment by fthommen** [comment] 2021-03-25 11:56
This problems is still there in the newest RStudio version and it has been confirmed by RStudio as a bug in Decemebr 2018.  Can we expect it to be solved soon?

**Comment by R-Hannibal** [comment] 2021-03-26 15:27
Verified Fixed on: RStudio Version - 1.4.1652-1, R Version - 4.0.4, RHEL8 - Server 

Files are now successfully opening via File > Open File... > typing in partial or full file name and hitting Enter to open the file.

Comparison tested with `1.4.1647-1` where the issue was still reproducible. Tested on RDP as well and was not able to reproduce the issue there.

**Closed by R-Hannibal** 2021-03-26 15:27 UTC
Labels: bug, test

**Comment by fthommen** [comment] 2021-03-26 17:54
When will version `1.4.1652-1` be available for download?  We currently only find `1.4.1106-5` in the download area.

**Comment by R-Hannibal** [comment] 2021-03-26 18:00
@fthommen - You can currently access the 1.4.1652-1 build (that's the pro build, but open source builds are also available) on our [daily builds](https://dailies.rstudio.com/) page. 

Warning, these are early builds of our next release so they may be slightly less stable than `1.4.1106-5`.

**Comment by fthommen** [comment] 2021-03-26 18:23
@R-Hannibal We have a pro license.  I'll check the daily builds page.  thanks a lot for the speedy answer.
