### ISSUE TITLE
I am getting this "Unable to establish connection with R session" .Tried reinstalling,updating the packages but to no use.

### ISSUE THREAD

**Issue by virtualdogg** [rstudio/rstudio#5858] opened 2019-12-08 07:25 UTC
The issue tracker is not for questions. If you have a question, please feel free to ask it on our community site, at https://community.rstudio.com/c/rstudio-ide.

**Comment by ronblum** [comment] 2019-12-09 17:59
@virtualdogg Thank you for filing the issue. Can you please provide your environment information so that we can try to reproduce? Also, was the link above meant for a specific Community post? As is, it's pointing at the `rstudio-ide` channel, not to a post. Thanks!

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by ronblum** [comment] 2019-12-09 18:28
@virtualdogg Another question: is there something—updating packages, running an R script, some specific code—in particular that triggers the error? And is it in the console, a pop up window, etc.?

Since we don't have enough information to address the issue, I'm closing it. However, if you are able to provide the information above, please open a new ticket. Thanks!

**Closed by ronblum** 2019-12-09 18:28 UTC
Labels: bug, repro needed

**Comment by florianWickler** [comment] 2020-01-17 11:15
@ronblum Since approx. 2 weeks I have the same problem as described above. 

After some minutes of inactivity, I can't use Rstudio anymore. On R Console I get an 'Error: Unable to establish connection with R session' everytime I trie to use it. When I then try to save Files, RStudio will prompt a 'Unable to establish connection with R session'.

Unfortunately I'm not able to reproduce this bug apaart from waiting.

Updating R and RStudio had no effect.

System Details:
```
RStudio Edition : Desktop
RStudio Version :  1.2.5033
OS Version      :  Windows 10 
R Version       : 3.6.2
```

**Comment by Mckay-R** [comment] 2020-01-17 21:56
I am facing the same problem. What can I do to fix this? I have updated R and Rstudio countless times, but this is not helping.

**Comment by florianWickler** [comment] 2020-02-04 09:02
I solved all problems by deactivating/deinstalling the antivirus software (Avast)

**Comment by Robinlovelace** [comment] 2020-07-16 13:36
In case it's of use/interest to others I'm having the same issue on this set-up:

```
RStudio Server Pro
Version 1.3.895-2
© 2009-2020 RStudio, PBC
"Middlemist Red" (6b8393d3, 2020-03-07) for Ubuntu Bionic
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
```

It seems to be intermittent. @florianWickler did your solution work work on the host or client side?

**Comment by eduard-martinez** [comment] 2020-09-05 00:26
You do not need deactivating/uninstalling AVS. AVS has problems with the latest version of Rstudio but if you try an older version of it, this will be solved. 

You can get an older version of Rstudio here: https://rstudio.com/products/rstudio/older-versions/ 
The version 1.0.153 can help you.
