### ISSUE TITLE
Can't enable visual R markdown editor: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DarwinAwardWinner** [rstudio/rstudio#8138] opened 2020-10-21 14:30 UTC
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.904
    OS Version      : macOS Catalina 10.15.7
    R Version       : R version 4.0.3 (2020-10-10)

### Steps to reproduce the problem

1. Open the attached Rmd file (`big_Rmd.txt`; rename to `big.Rmd`) in RStudio 1.4.904
2. Attempt to enable visual R markdown mode

### Describe the problem in detail

A dialog box pops up saying `RangeError: Maximum call stack size exceeded`, and visual mode is not enabled. 

### Describe the behavior you expected

I expected visual mode to be enabled.

[big_Rmd.txt](https://github.com/rstudio/rstudio/files/5416593/big_Rmd.txt)

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5416582/diagnostics-report.txt)

**Comment by kevinushey** [comment] 2020-10-21 16:43
Likely a duplicate of https://github.com/rstudio/rstudio/issues/8116: should be fixed in the next daily builds. Thanks for reporting!

If you still see this in the next daily builds (1.4.957+) please feel free to re-open.

**Closed by kevinushey** 2020-10-21 16:43 UTC
