### ISSUE TITLE
Elsbeth build has extremely fast within-file scroll speed

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#11578] opened 2022-07-08 14:48 UTC
It seems like the Elsbeth builds have a much faster within-file scroll speed.

This is kind of hard to make a reprex for, but I swear it is much faster. I find myself blowing by the code block im expecting to scroll to, and im really not scrolling very fast with my mouse.

I've been told that this might be due to Electron vs not Electron (i.e. the non Electron Spotted Wakerobin daily didn't have this issue)

https://user-images.githubusercontent.com/19150088/178015581-d18e0e4b-0233-4944-9161-dce9a5615bdc.mov

RStudio 2022.10.0-daily+55 "Elsbeth Geranium" Daily (f895778c3e83e20672af1434f040a31b8f2cf906, 2022-07-07) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.10.0-daily+55 Chrome/102.0.5005.115 Electron/19.0.6 Safari/537.36

**Comment by netique** [comment] 2022-07-19 09:54
Note that in a dataframe preview, the scrolling speed matches that of Qt, i.e. works great. The issue seems to be concerning the editor only.

**Comment by netique** [comment] 2022-07-26 13:18
I've stumbled upon this "fiddle" which behaves the same as the Electron build ACE editor scroll-speed-wise https://codepen.io/zymawy/pen/XwbxoJ.
There is indeed such option `scrollSpeed` in RStudio source, but I don't understand how it affects only the Electron build.

https://github.com/rstudio/rstudio/blob/8b617539f302a5b278fbc51fe39aba906ceff0e1/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java#L658

**Comment by kevinushey** [comment] 2022-07-27 13:04
@netique Nice catch -- indeed, we do some work to adjust the scroll speed on Windows (this was necessary for Qt desktop at least). We may need to consider similar tweaks for Electron.

**Comment by netique** [comment] 2022-07-27 13:23
One more info - this issue **seems to be macOS related only**. At least on Windows, I cannot see any problem at all (using 2022.11.0-daily+80 Electron build).

**Comment by netique** [comment] 2022-08-07 09:24
Possibly related issue: https://github.com/microsoft/vscode/issues/146403. But vscode probably doesn't use ACE. The message is Electron could be messing something up on macOS.

**Comment by netique** [comment] 2022-08-07 20:36
I have just build RStudio Server on my M1 Mac (`./ant devmode`) and it seems to me that the scroll speed is as fast as with the Electron build. Even current rstudio.cloud (2022.02.2 Build 485.pro2) is similar (I really don't know how to measure it properly, but I always compare it with visual-mode Quarto or Markdown document, which is rendered in the same pane and doesn't utilize ACE).

**Comment by netique** [comment] 2022-08-07 21:17
OK, allowing the "pixel ratio fix" mentioned above to other OS than Windows seems to solve the issue for me. Should I PR it? https://github.com/netique/rstudio/commit/7f98b458128795547dabab30e187b7e8d787376f

**Comment by netique** [comment] 2022-08-13 13:49
Digging deeper, Qt builds, which behaves normally, uses rather old Chrome version 69.0.3497.128 as opposed to Electron, which uses up-to-date 102.0.5005.167. Indeed, when I try ACE using the old Chromium, the scroll speed is much slower. So this could be a bug/change of Chrome which ACE doesn't reflect. On top of that, the current RStudio ACE version is 1.4.5, but the current release is 1.9.5. I think there are no scroll-related changes between these, but it may be worth updating.

**Comment by timtmok** [comment] 2022-09-21 14:30
I haven't been able to reproduce the odd scrolling except for Linux, which seems to scroll 3 lines at a time. It seems like the best solution that will work for different users with their own scrolling preference is to add a sensitivity preference. Ron and I discussed an option that can be set from 0-100 (or maybe 1-100) to adjust the sensitivity.

**Comment by netique** [comment] 2022-09-21 15:10
@timtmok That is weird. Have you tried _Electron_ build on macOS? On Windows, there is no problem at all, maybe because it is fixed with these lines: https://github.com/netique/rstudio/commit/7f98b458128795547dabab30e187b7e8d787376f. The diff is me removing the condition on Windows, so the tweak is applied on macOS and Linux. After that, it works for me like a charm.

Adding scroll sensitivity as an options is nice, but it should default to a value in a manner that the resulting scrollspeed matches exactly sroll behavior in, e.g., packages pane, visual editor and so on. The goal is to have the same speed as it was in Qt times.

**Comment by timtmok** [comment] 2022-09-21 15:41
@netique I have tried across Mac, Linux, and Windows. Only Linux appeared to scroll a minimum of 3 lines at a time. While a default setting that works for all would be nice, everyone has different configurations and will experience scrolling differently. I can enable the code that was meant for Windows desktop but that may not actually work for everyone. For that, a preference would allow users to adjust scrolling to their preference.

I've attached my screen recording on Mac. I can scroll slow or fast with granularity down to partial lines scrolled. I've also tried on a different monitor with scaling. The scrolling sensitivity code uses the device pixel ratio as reported by the browser. It was all handled to provide a proper ratio for the sensitivity. So my guess is it has something to do with pixel density with different displays and it not updating properly.

https://user-images.githubusercontent.com/9591545/191547140-7c940619-c386-4031-9f9a-c422c2ea64d5.mov

**Comment by timtmok** [comment] 2022-09-22 17:40
I've got a change up for review that will hopefully help with the scroll sensitivity. I'm unable to reproduce the issue but I think this change will allow users to adjust the sensitivity to their liking. The default value will use what was the Windows scroll adjustment that is based on the pixel device ratio.

100 is default that is the same as the Windows scrolling adjustment. Higher results in faster scrolling.

**Comment by netique** [comment] 2022-09-22 19:16
Thanks a lot, @timtmok ! What truly amazes me is that this is not replicable (a lot of subjectivity comes into play, of course).  Maybe different mouse settings can somehow affect it, but why would it only show up in Ace editor?

>  I can scroll slow or fast with granularity down to partial lines scrolled

I can achieve that as well, but there is so much "acceleration" it is close to unusable (that is why I am so into solving this 😄).

**Comment by timtmok** [comment] 2022-09-22 19:26
@netique My guess is it is based on different display pixel ratios. The default pixel ratio was 1.0 and was only adjusted for Windows. That sets the scroll speed to 2.0. Chromium might have changed how scrolling works (maybe inertial scrolling tweaks?) and coupled with the right display pixel ratio causes this issue. Maybe low res display or turning up the scaling on a high res display 🤷

**Comment by DavisVaughan** [comment] 2022-09-23 12:51
@timtmok if you want to create a manual build of the IDE (@romainfrancois has done this for me) then I'd be happy to test it out for you, you can ping me on slack with the link

**Comment by timtmok** [comment] 2022-09-23 17:34
@DavisVaughan PR has been merged and is currently building. The Mac build should finish in about an hour. There's only one Mac build agent so might as well build everything.

**Comment by netique** [comment] 2022-09-24 14:28
Good job, @timtmok ! I had to set 85 for me to be perceptually identical with the Qt version, but it works great. Chromium did actually change the scroll API many times according to the dev changelogs, but I guess it is on ACE to accommodate that. ACE version used by RStudio is a bit stale, but I think they didn't change anything regarding scrolling through the up-to-date version. Many thanks!

**Comment by jonvanausdeln** [comment] 2022-09-27 22:03
Verified on 2022.11.0-daily+219
Windows 11, MacOS 12.4, Ubuntu 22.04

Tested several settings from 10-200, all seemed to perform as I'd expect. Also tried with different screens and mouse settings.

**Closed by jonvanausdeln** 2022-09-27 22:03 UTC
Labels: bug, electron

**Comment by netique** [comment] 2023-01-05 13:53
Just a follow-up: it's pretty clear now that the issue is caused by Chromium itself which introduced some changes dealing with framerate to match the Safari behavior on pro-motion displays on macOS in version 98. It affects how `mousewheel` events are handled and it seems that the `deltaY` is essentially doubled. See the bug filed at https://bugs.chromium.org/p/chromium/issues/detail?id=1404833. I am writing this for future reference because the `mousewheel` event handling may change in the upcoming Chromium versions. But the user can now adapt to the possible change using the newly introduced setting.

**Comment by netique** [comment] 2023-08-31 15:08
Note that the underlying issue in Chromium has been fixed just now: https://bugs.chromium.org/p/chromium/issues/detail?id=1207308#c7

This will likely cause some decrement in scroll speed for users that customized it in preferences. However, that the setting may render useless as the scroll speeds will match that of the system, just as it did before Chromium introduced the issue.

**Comment by timtmok** [comment] 2023-09-05 09:12
The Chromium fix will likely be picked up in the next Electron update. Once RStudio updates Electron to a version with this fix, the behaviour will change. This Chromium fix won't be available in time for Desert Sunflower.

**Comment by netique** [comment] 2024-04-03 17:06
Well I have just tried 2024.04.0-daily+675 with Electron 28.2.6 and now it seems slow so I have to bump the sensitivity level all the way up to 200 to be comparable to other panes (Help, Files, etc.). Platform: aarch64-apple-darwin20 (64-bit), running under: macOS Sonoma 14.4.1.

**Comment by netique** [comment] 2024-04-03 17:06
Well I have just tried 2024.04.0-daily+675 with Electron 28.2.6 and now it seems slow, so I have to bump the sensitivity level all the way up to 200 to be comparable to other panes (Help, Files, etc.). Platform: aarch64-apple-darwin20 (64-bit), running under: macOS Sonoma 14.4.1.

**Comment by netique** [comment] 2024-04-03 17:06
Well I have just tried 2024.04.0-daily+675 with Electron 28.2.6 and now it seems slow so I have to bump the sensitivity level all the way up to 200 to be comparable to other panes (Help, Files, etc.). Platform: aarch64-apple-darwin20 (64-bit), running under: macOS Sonoma 14.4.1.
