### ISSUE TITLE
Rstudio freezing together with builtin browser when .tabset is in combination with GoogleCharts

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11895] opened 2022-09-02 14:29 UTC
### System details
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem
- Create an Rmarkdown file
- Define a tabset'd section
- Include code for google.visualization.Calendar
- knit
- Builtin browser will freeze together with Rstudio

### Describe the problem in detail

While learning a bit about [GoogleCharts](https://developers.google.com/chart/interactive/docs/quick_start)
I experienced consistent freezing in some parts of a copied code when knitting to html and on the builtin browser.
After enabling&dissabling parts of the code, I reduced it to the some incompatibility with the Calendar chart of google.
But this is only raised when inside of a tabset section.
It freezes when the resulting page is opened by the builtin browser, but the whole Rstudio freezes together.

### Describe the behavior you expected
Not freeze Rstudio

[rstudio_hangs_with_google_charts.zip](https://github.com/rstudio/rstudio/files/9478643/rstudio_hangs_with_google_charts.zip)

**Comment by ronblum** [comment] 2022-09-02 17:37
@DiegoJArg Thank you for raising this! I can also reproduce this in RStudio Desktop 2022.11.0-daily+160. This is a bug both when viewing in the Viewer Pane and an external window. We'll review it was we continue development of RStudio.

Triage: Candidate for Elsbeth Geranium?

**Comment by kevinushey** [comment] 2022-09-02 23:41
The bundled HTML also hangs if you open it within a regular browser (e.g. Chrome) so I don't think this is an RStudio-specific issue.

**Comment by MariaSemple** [comment] 2022-09-06 18:04
Closing since this reproduces outside of RStudio

**Closed by MariaSemple** 2022-09-06 18:04 UTC
Labels: bug, r markdown, triage
