### ISSUE TITLE
Publish button shows unsaved document error  message for saved/knitted doc

### ISSUE THREAD

**Issue by rich-rstudio** [rstudio/rstudio#6711] opened 2020-04-22 17:09 UTC
### System details

    RStudio Edition : Desktop/Server
    RStudio Version : Version 1.3.945
    OS Version      : Ubuntu
    R Version       : 3.3.3

### Steps to reproduce the problem
1. create a R markdown document
2. save and knit the document 
4. click on the publish button in the editor pane (not the viewer pane)
### Describe the problem in detail
Error message "unsaved documents cannot be published. Save the document before publishing it"
### Describe the behavior you expected
Publish modal is displayed since the user already saved and knitted the doc. (viewer pane publish button works correctly)

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-04-22 20:47
I've marked this issue as a blocker for v1.3, since it inhibits publishing of documents.

@gtritchie since this falls under the umbrella of publishing, I've assigned you -- let me know if you're able to take a look.

**Comment by gtritchie** [comment] 2020-04-25 17:55
Reproduced with 1.3.947 (Mac Desktop) but not with 1.2.5042, marking as regression.

**Comment by gtritchie** [comment] 2020-04-25 23:03
This problem was introduced with this PR: "Reduce disruptions caused by autosave" #6442

Specifically, these added lines (remove these and the problem goes away):

https://github.com/rstudio/rstudio/blob/6fde984999965d679da15b5ace4d948e60a684ca/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L2958-L2960

Assigning to @jmcphers

**Closed** 2020-04-27 17:19 UTC
Labels: bug, publishing, regression

**Comment by R-Hannibal** [comment] 2020-04-29 15:45
Verified Fixed on: Windows Desktop, RStudio version: 1.3.952-1, R version 3.6.3.

Saved docs are now publishing successfully from the Source pane, no error dialogue about the document being Unsaved is returned (*unless the document is actually in an unsaved state).
