### ISSUE TITLE
Table made from kable in R Markdown interferes with scrolling using mouse or trackpad

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2202] opened 2018-02-15 14:26 UTC
### System details

    RStudio Edition : Server and Desktop
    RStudio Version : 1.1.383, 1.1.423, 1.2.342
    OS Version      : MacOS Desktop and Ubuntu
    R Version       : 3.4.3

### Steps to reproduce the problem
1. Create an R Markdown document that contains the sample code below. The full Rmd file is here (rename from .txt to .Rmd): [kable_scolling.txt](https://github.com/rstudio/rstudio/files/1727946/kable_scolling.txt)
``kable(matrix(1:100), col.names = "Long")``
``kable(matrix(1:1), col.names = "Short")``

2. Run —> Run All
3. Click inside the “kable_long” chunk
4. Scroll down past the output using the trackpad (two fingers) or mouse (third button/wheel).
5. Try to scroll up or down.
6. Click inside  the “kable_short” chunk
7. Scroll down past the output using the trackpad or mouse.
8. Try to scroll up or down

![kable_scrolling](https://user-images.githubusercontent.com/31009952/36261331-00653fdc-1232-11e8-9090-03d37cefa887.gif)

### Describe the problem in detail

Outputted R Markdown chunks containing kable() tables interfere with scrolling using the Mac trackpad’s two-finger scroll gesture or mouse wheel/third button. If the cursor starts off in code, and then you try to scroll up or down past an output with a table generated using kable(), then the cursor automatically jumps into the output and the screen stops scrolling. Then one of two things happen:
1. If there are more rows in the table than can be displayed at once, the mouse now scrolls up and down within it. This is normal behavior, if one had clicked on the output, but not in this case, because we tried to scroll past the output.
2. If the output layout is large enough that all the records are displayed, the screen simply pauses. It’s as if the mouse jumped into the output table, but there’s nothing to scroll through, so it just sits there.

The behavior is consistent on Server. On Desktop, it's a bit inconsistent. Sometimes, when (1) occurs, if you scroll all the way down to the final row or up to the first row, the mouse jumps back out and the screen continues to scroll. Also, (2) doesn’t always happen.

### Describe the behavior you expected

The scrolling will continue past the outputs. Scrolling within the outputted table will only happen in case (1)—more rows than can be displayed at once—with a mouse click on it. In case (2)—all rows are displayed—not only should the scrolling continue past the output, there should be no equivalent to clicking within the output; scrolling should continue past it.

**Comment by jrvianna** [comment] 2018-11-11 16:14
I am having a similar issue. When any kable is created in the Rmd a big output area is created, even if the table is small, and with the mouse over this big area it does not scroll the Rmd file, so have to try to get in corners or scroll quickly to be able to see the Rmd file after the kable. Can reproduce this error with the example kable in https://rmarkdown.rstudio.com/demos/6-tables.Rmd. Using macOS 10.14, RStudio 1.2.1045, knitr 1.2.0, rmarkdown 1.1.0.

I would argue that this is quite a troubling bug and would increase the priority from low.

**Comment by balthasars** [comment] 2019-04-19 19:32
I have the same issue and can confirm that this is not conducive to being productive.

**Comment by stuartsoorholtz** [comment] 2019-11-20 19:17
I have the same issue on macOS 11.15, R 3.6.1, RStudio 1.2.5001, knitr 1.26, rmarkdown 1.17.

**Comment by callanhoskins** [comment] 2020-01-28 06:46
I have the same issue on Ubuntu 18.04. This prevents me from using `kable()` at all, and should be a high priority imo!

**Comment by KeelyDulmage** [comment] 2020-03-11 18:42
I have the same issue on Windows 10 v1903, R 3.6.0, Rstudio 1.2.5033, knitr 1.23, rmarkdown 1.14

**Comment by careyhuh** [comment] 2020-04-24 06:18
I had the same issue. I switched to using kableExtra.
library(kableExtra)
dataframe %>%
  kable() %>%
  kable_styling()
This made the scrolling problem go away.

**Comment by serivas** [comment] 2020-05-11 19:01
Same issue here, but in my case even when I have a tiny table, the r markdown direct output covers pretty much all visible space so it's very hard to scroll

**Comment by IsabelFE** [comment] 2020-08-27 17:32
This is a really annoying bug. Is this being addressed?

**Comment by sofisinozich** [comment] 2021-03-18 17:10
Sorry to necro, but can this be reopened? #8056 explicitly does not solve this issue per the PR.
Anecdotally, I'm on RStudio 1.4.1106 and I can still reproduce the blocked scrolling and extra whitespace (Windows 10, knitr 1.31, RMarkdown 2.7, R 4.0.3)

**Comment by ronblum** [comment] 2021-03-18 19:00
@sofisinozich Thank you for pointing this out! I can confirm that it's still an issue in RStudio Desktop 1.4.1627 on MacOS 11.3. Reopening.

**Comment by isaactpetersen** [comment] 2021-03-23 03:12
I have this issue on RStudio Desktop 1.4.1103 on Windows 10.

**Comment by adamconroy** [comment] 2021-03-23 04:41
I propose we look at this after the Electron changes. There is a chance that this will change it (though I'm only 30% hopeful).

**Comment by gtritchie** [comment] 2021-03-23 18:10
@adamconroy I haven't read the whole thread, but is this desktop specific (in which case it might be fixed by Electron), or does it also happen on Server in latest Chrome (in which case it won't).

If is truly desktop only and thus possibly fixed by Electron, plz add to the "Fixed by Electron" EPIC, put in 1.5 milestone, and put on the backlog.

Thanks!

**Comment by adamconroy** [comment] 2021-03-23 18:35
I thought I had remembered this being desktop only but reading back on it, it appears that it's actually worse/more consistent on server. A lot of this has to do with how we have tables inside tables and how different browsers deal with it, this is why I thought it might be affected by Electron. The behavior will likely still change but this is a larger issue.

**Comment by ronblum** [comment] 2021-03-23 20:36
Confirmation that it's also a problem in RStudio Server 1.4.1639 using Safari on MacOS 11.3.

**Comment by geonj97** [comment] 2021-04-28 03:41
Still not fixed...

**Comment by adamconroy** [comment] 2021-04-29 05:12
I am dedicated to actively squashing this bug. Hold on tight. 🙏

**Comment by mikebessuille** [comment] 2021-05-31 17:58
Pretty sure Adam had a PR that he was going to submit to this.. @jmcphers  did you see it?

**Comment by jmcphers** [comment] 2021-06-01 16:16
No, I didn't.

**Comment by maximilianpress** [comment] 2021-07-28 19:53
I am also seeing this on desktop rstudio 1.4.1106 and OSX 10.15.7.

**Comment by Varix** [comment] 2021-07-29 01:21
Issue on Ubuntu in RStudio also

**Comment by saskia-c** [comment] 2021-07-31 13:38
I am having the same issue using desktop rstudio 1.4.1717 and OS Big Sur 11.4.

**Comment by GCRev** [comment] 2021-10-20 00:48
This looks like default scrolling behavior for browsers: when the mouse is hovered over a scrollable item (even when unfocused), it will intercept the wheel events and prevent them from propagating to the parent. We could try working around this by making it so that the user must focus the scrollable sub-item before they can scroll it, and otherwise it would be blocked from scrolling.

If that's too much of a disruption, then we'd have to do some more complex logic to determine user intent to scroll a sub-element.

**Comment by astayleraz** [comment] 2021-11-16 21:58
I verified the following on mac os with version 2022.01.0-daily-205 and ubuntu:

Verify that you can scroll from the top of the document to the bottom without encountering a pause, provided you keep the mouse pointer perfectly still.
Verify that moving the mouse over sub-content allows you to scroll its content
Verify that removing the mouse from the sub-content area disables the sub-content again, and scroll behavior on the main document is restored.

Closing issue as fixed.

**Closed by astayleraz** 2021-11-16 21:58 UTC
Labels: bug, r markdown, test

**Comment by ronblum** [comment] 2021-11-16 22:45
@GCRev and @astayleraz Thank you for fixing this!
