### ISSUE TITLE
Tabbing changes UI focus in visual mode instead of inserting tabs

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8474] opened 2020-11-24 20:48 UTC
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.1056
    OS Version      : MacOS 11.1, Red Hat 8.2, and Windows 10
    R Version       : 4.0.3

### Steps to reproduce the problem

In visual mode, version 1:
1. Click anywhere in the content.
2. Press <kbd>Tab</kbd>.
    - The focus shifts to buttons and other parts of the UI.

In visual mode, version 2:
1. Create a bulleted or numbered list.
2. Place the cursor in one of the items, except the first one.
3. Press <kbd>Tab</kbd>.
    - MacOS and Red Hat: The item sinks.
    - Windows: The focus shifts to buttons and other parts of the UI.
4. Press <kbd>Tab</kbd> a few more times.
    - The focus shifts to buttons and other parts of the UI.

In visual mode, version 3: 
1. Click in a code chunk.
2. Press <kbd>Tab</kbd>.
    - A tab is inserted and the cursor shifts right, using the set width of the tab width, as expected.

The same for the above is true for <kbd>Shift-Tab</kbd> (in version 2, step 3, the items are lifted).

### Describe the problem in detail

<kbd>Tab</kbd> and <kbd>Shift-Tab</kbd> change focus, as if the “Tab key always moves focus” Accessibility option is checked. On Windows, this is always the case. On Mac and Linux, if inside a list, the list item will sink or lift as far as possible, then tabbing will switch focus.

### Describe the behavior you expected

When <kbd>Tab</kbd> and <kbd>Shift-Tab</kbd> are pressed outside of a list, tabs should be added or removed. Inside a list item, tabbing should sink and lift the items.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment] 2020-11-25 15:56
This is a serious issue we need to fix for 1.4

**Comment by mikebessuille** [comment] 2020-11-25 16:02
If you keep hitting tab it moves through various UI elements, but once it gets to the console, it starts adding tabs again.  Very strange.  (Mac OS Big Sur, with 1.4.1066)

**Comment by ronblum** [comment] 2020-11-25 17:49
Note: this works fine within code chunks, code blocks, YAML, and tables, and possibly other areas. For example:
1. <kbd>Alt-Ctrl-I</kbd>
    - Creates R chunk
2. <kbd>Tab</kbd> three times
    - Inserts three tabs
3. <kbd>Shift-Tab</kbd> once
    - Removes one tab
4. Type `# I've been tabbed`
     - Places the text to the right of the last tab

The end result, if tabs are set to 10 spaces:
```
{r}
                    # I've been tabbed
```

**Comment by kevinushey** [comment] 2020-11-25 19:35
This all makes sense given that the default behavior of Tab in a browser is to move focus between elements. The only surprise then is that Tab isn't handled in the visual editor (except in the case where a code chunk has focus).

**Comment by gtritchie** [comment] 2020-11-25 20:02
Right, this is all behaving correctly except for default behavior in editing surfaces should be to indent (or whatever) versus moving focus, unless the Tab Key Always Moves Focus accessibility setting is on. I know JJ wrote some specific code related to this earlier on (seen during code reviews). Have asked if he'd like me to take this, more likely he'll fix it in the time it takes me to ask.

**Comment by jjallaire** [comment] 2020-11-25 21:18
Yes, there is no such thing as a "tab" in markdown (or really even in HTML or LaTeX). Tabs do exist in code blocks and they also exist as a gesture within lists, but they don't exist (or at least exist in any meaningful or useful way) in content.

So while this probably will seem unintuitive to some (esp. if they are attempting to do something like indent the beginning of a paragraph) it is acting as intended. Note that even if we wanted to make tab work to indent the beginning of a paragraph there is no way to express this in markdown (rather, this is expressed in a CSS stylesheet).

We *could* make tab insert a configurable number of non-breaking spaces. While this would conform to user's expectations visa via MS Word, it isn't really what you are supposed to be doing to achieve indentation (again, this is the province of stylesheets).

**Comment by mikebessuille** [comment] 2020-11-26 12:51
In regular (non-visual-mode) editing, tab inserts a set of spaces.  I think users will expect the same behaviour for consistency.  I also think it will be expected that tabs insert something (spaces, indent, whatever) because people using visual mode will expect it to be much more like Word.

**Comment by jjallaire** [comment] 2020-12-02 14:49
I see why this is confusing for users so we should definitely do something. Inserting tabs or sequences of non-breaking spaces is definitely a holdover from non-semantic authoring whereas markdown is really trying quite hard to be semantic (e.g. if you want your paragraphs to start with an indent you use CSS or LaTeX or your MS Word styles for that). We could just concede this non-semantic pattern and let users make their own non-semantic bed but we haven't done that in other places.

Another option would be to just ignore tab (i.e. don't lose focus). This would elicit the reaction "I guess tab doesn't work" rather than "why can't I type anymore" which is definitely an improvement. i.e. at least you get feedback that tab is not a thing in markdown.

My instinct would be to ignore tab for now and then see how much feedback we get about it.

**Comment by mikebessuille** [comment] 2020-12-02 15:05
I struggle with trying to force people into a way of working that we deem correct, versus making it work the way most users would expect.  I am not sure the correct answer here because they _are_ editing in markdown after all, even if it is a visual representation of it.  I wonder if we should optionally be authoring a CSS file under the hood along with the markdown file, and applying the CSS to the output.  Longer term of course.  For now..  My gut is that we should insert spaces.  But I'm okay with ignoring the tabs as well, as there is value in gaining feedback.  At least that will keep them in the window so they can continue typing.

**Comment by jjallaire** [comment] 2020-12-02 15:09
We're not really trying to force them, we are trying to help them learn a new model. Documents that are authored in too literal a fashion are not usable e.g. on the web (how many good word -> html for use on a website tools are there? probably none) or in sophisticated print publications (again, how many good word -> latex tools are there?) . When you are editing in the WordPress visual editor the same constraints apply (don't know what they do with tab) but you certainly can't e.g. set a bunch of fonts and indent in arbitrary ways.

I agree that we may end up inserting spaces, but I'd rather start more conservatively. I'll prepare a PR.

**Comment by jjallaire** [comment] 2020-12-02 15:12
e.g. web editors (wordpress, tinymce) generally do not recognize the tab key: https://github.com/WordPress/gutenberg/issues/1621

**Comment by jjallaire** [comment] 2020-12-02 15:15
If our behavior is aligned with other web content editors in not recognizing tab, then if I disable it we are effectively reducing accessibility (b/c now tab will require the special accessibility setting to always have tab advance). So its user confusion vs. appropriate gestures for the medium vs. accessibility.

**Comment by jjallaire** [comment] 2020-12-02 15:35
One minimal change we should definitely make is that in cases where tab doesn't work in a list (e.g. first item, attempting to indent 2 levels, etc.) we should do nothing rather than change focus.

**Comment by mikebessuille** [comment] 2020-12-02 15:56
Given that in regular markdown editing, that tabs insert spaces (and don't navigate for accessibility) I think tabs should not navigate away from the editor when in visual mode.

**Comment by jjallaire** [comment] 2020-12-02 16:54
Okay, I'll make the change to have tab not navigate (unless the special accessibility option is enabled)

**Comment by jjallaire** [comment] 2020-12-02 17:25
PR here: https://github.com/rstudio/rstudio/pull/8517

**Comment by jmcphers** [comment] 2020-12-02 23:25
PR is merged; I think we can consider this issue settled for the 1.4 release.

**Closed by jmcphers** 2020-12-02 23:25 UTC
Labels: backlog, bug, keyboard shortcuts, visual markdown editing

**Comment by kfeinauer** [comment] 2020-12-03 17:25
Verified tab key no longer changes focus when tabbing within regular content in Visual Mode. 1.4.1075.

**Comment by Krixpiny** [comment] 2022-03-29 18:36
Try to disable this option.
![imagen](https://user-images.githubusercontent.com/51924204/160681283-fb152e2c-1883-4bfc-b8b9-57f3384e59a2.png)
