### ISSUE TITLE
Rstudio Ubuntu 22.04

### ISSUE THREAD

**Issue by Dumbo-programmer** [rstudio/rstudio#10938] opened 2022-04-08 17:28 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.02.1+461
    OS Version      : ubuntu 22.04
    R Version       : 4.1.2

### Steps to reproduce the problem
Ubuntu Recent LTS DE.Branch
### Describe the problem in detail
complete white.
Logs:
```
2022-04-07T03:12:09.939811Z [rsession-tawhidk] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1443
2022-04-07T03:12:09.939811Z [rsession-tawhidk] ERROR Parent terminated; LOGGED FROM: void {anonymous}::detectParentTermination() src/cpp/session/SessionMain.cpp:1443
```
After some research I found out that it is not supported yet.
Could that be a problem?
### Describe the behavior you expected
I expected it to run lik ubuntu 20.04

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2022-04-11 16:53
Duplicate of https://github.com/rstudio/rstudio/issues/10902.

**Closed by kevinushey** 2022-04-11 16:53 UTC
