### ISSUE TITLE
New RMarkdown document - yaml header not populated

### ISSUE THREAD

**Issue by andypicke** [rstudio/rstudio#3482] opened 2018-09-14 16:15 UTC
When I create a new RMarkdown document from RStudio, none of the yaml fields at the top of the template are populated. It used to populate the title: and output: fields.

### System details

    RStudio Edition : Desktop 
    RStudio Version : Version 1.1.456
    OS Version      : Windows Server 16 Standard
    R Version       : 3.5.0

### Steps to reproduce the problem
Click on new file button at upper left, then RMarkdown. Then click ok on window that opens.

### Describe the problem in detail

None of yaml at top of document is populated.

### Describe the behavior you expected

I expected the yaml at top of document to be populated with title and output variables.

Thank you for taking the time to file an issue!  -->

**Comment by jmcphers** [comment] 2018-09-17 19:42
We couldn't reproduce this. :-/ Have you tried updating to the latest versions of the `rmarkdown` and `yaml` packages?

**Comment by jmcphers** [comment] 2018-11-12 20:36
Since neither of us can reproduce at this point I'm going to close the issue; let us know if you see it again!

**Closed by jmcphers** 2018-11-12 20:36 UTC
Labels: repro needed
