### ISSUE TITLE
[ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#6694] opened 2020-04-19 18:41 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5042
    OS Version      : FreeBSD 12.1
    R Version       : 3.6.3

### Steps to reproduce the problem
Build.

### Describe the problem in detail
```
[ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')
### Describe the behavior you expected
```

See the build log: https://people.freebsd.org/~yuri/RStudio-1.2.5033.log

I observed this problem while trying to update the FreeBSD port.

**Comment by jmcphers** [comment] 2020-04-21 16:55
```
--MAKE_ENV--
HOME=/wrkdirs/usr/ports/devel/RStudio/work  JAVA_HOME=/usr/local/openjdk11  
```

I think this `JAVA_HOME` is the problem. GWT 2.8 doesn't support Java 11. https://github.com/gwtproject/gwt/issues/9626

**Comment by jmcphers** [comment] 2020-04-21 16:58
Duplicate of https://github.com/rstudio/rstudio/issues/6088.

**Closed by jmcphers** 2020-04-21 16:58 UTC
Labels: builds, freebsd

**Comment by yurivict** [comment] 2020-04-21 17:22
What Java version should RStudio be built with then?

**Comment by jmcphers** [comment] 2020-04-21 17:25
Java 8. e.g,

https://github.com/rstudio/rstudio/blob/5a0745193b39bfb98a0575a970be614c2083bc6b/docker/jenkins/Dockerfile.bionic-amd64#L49

**Comment by kevinushey** [comment] 2020-04-21 22:03
FWIW, my understanding is that GWT 2.8.2 (used by RStudio v1.3+) does support Java > 8; it's just GWT 2.8.1 that doesn't support it.

We're hoping to release RStudio v1.3 soon so I think it'd be simpler to wait for our release and bump the OpenBSD build scripts then.
