### ISSUE TITLE
[Windows] Cannot knit on path with special characters

### ISSUE THREAD

**Issue by lgaborini** [rstudio/rstudio#4254] opened 2019-02-01 14:57 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1206
    OS Version      : Windows 10 x64 (build 17763)
    R Version       : version 3.5.2 (2018-12-20)    
    Platform        : x86_64-w64-mingw32/x64 (64-bit)

### Steps to reproduce the problem

1. Create a R or Rmd file in a path containing a special character (e.g. "é")
2. Open that file, write something, save
3. Run "Compile Report" 

### Describe the problem in detail

I created the file `C:/Users/Lorenzo/spéciale/test.R` (notice the "é" ):
```
print('Ok')
```

It can be sourced correctly from Rstudio, producing and running the line: 
```
source('C:/Users/Lorenzo/spéciale/test.R')
```
Rstudio API also returns the correct document path:
```
> rstudioapi::getSourceEditorContext()$path
[1] "C:/Users/Lorenzo/spéciale/test.R"
```

As I run the Compile Report command, the special characters are substituted with a `?`, and the command fails:
```
Error in tools::file_path_as_absolute(input) : 
  file 'C:/Users/Lorenzo/sp?ciale/test.R' does not exist
Calls: <Anonymous> -> setwd -> dirname -> <Anonymous>
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/Lorenzo/sp?ciale/test.R": La sintassi del nome del file, della directory o del volume non è corretta
Execution halted
```

### Request log

The `render_rmd` method is called with the good path:
```
"{""method"":""render_rmd"", ""params"":[""C:/Users/Lorenzo/spéciale/test.R"",1,""html_document"",""UTF-8"","""",false,0,"""","""",""""], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}"
```

### sessionInfo

```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                  
[5] LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] usethis_1.4.0.9000

loaded via a namespace (and not attached):
 [1] compiler_3.5.2  htmltools_0.3.6 tools_3.5.2     fs_1.2.6        glue_1.3.0      yaml_2.2.0      Rcpp_1.0.0      rmarkdown_1.11 
 [9] highr_0.7       knitr_1.21      xfun_0.4        digest_0.6.18   packrat_0.5.0   evaluate_0.12  
```

**Comment by jmcphers** [comment] 2019-02-01 16:11
I think this is the same as issue https://github.com/rstudio/rstudio/issues/4075, which is fixed in a newer version of RStudio than what you're using. Can you confirm that the issue is resolved in our preview release?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by lgaborini** [comment] 2019-02-01 16:41
Updated to 1.2.1256, it acts weirdly: sometimes it escapes the chars correctly, sometimes not.   

* With `é` or `ö`, it does not work.
* If I substitute the `é` with `œ` (U+0153), it renders the HTML.
* If I substitute with a `ѩ` (U+0469) or a `ｅ` (U+FF45), it spins, then breaks:

```
processing file: test.spin.Rmd
  |......................                                           |  33%
  ordinary text without R code

  |...........................................                      |  67%
label: unnamed-chunk-1
  |.................................................................| 100%
  ordinary text without R code


output file: test.knit.md

Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="test.utf8.md": La sintassi del nome del file, della directory o del volume non è corretta
Calls: <Anonymous> ... pandoc_convert -> base_dir -> vapply -> FUN -> normalizePath
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]=".": La sintassi del nome del file, della directory o del volume non è corretta
Execution halted
```

**Comment by ronblum** [comment] 2019-02-06 16:00
I'm able to reproduce this in 1.2.1268. It works correctly in 1.1.463, though.

**Comment by jmcphers** [comment] 2019-02-08 00:19
Agree that this is a regression we need to fix for 1.2. It looks like this was partially fixed in https://github.com/rstudio/rstudio/commit/a1f4c9f116ff1dd2206625b08296eda1bf20f130, but that `utf8ToConsole()` is not handling these characters correctly.

**Comment by jmcphers** [comment] 2019-02-08 18:46
@lgaborini The "spins then breaks"  errors are coming from rmarkdown rather than RStudio. I've opened an issue over there:

https://github.com/rstudio/rmarkdown/issues/1529

**Closed** 2019-02-08 22:57 UTC
Labels: bug, encoding, regression, windows

**Comment by kamz8** [comment] 2020-11-13 09:16
Today I has classes at the University and we have big problem with polish chars in windows path. Girl have user name with polish char and we didn't can install package. 

She have a newest version of R studio. Please! Let you fix it, because we can't work on classes normally

**Comment by ronblum** [comment] 2020-11-13 17:48
@kamz8 1) Can you give me an example of a path name, or at least the portion with the Polish characters? 
2) Which version of RStudio is this—1.3.1093?
3) Is the problem only when installing packages, or are there are other issues?
4) What happens when running in R, outside of RStudio
Thanks! This will help to try to reproduce the problem.
