### ISSUE TITLE
RStudio doesn't ask to save workspace

### ISSUE THREAD

**Issue by jmm34** [rstudio/rstudio#14258] opened 2024-02-13 07:49 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.1 Build 402
    OS Version      : macOS 14.2.1
    R Version       : 4.3.2

### Steps to reproduce the problem

I installed the latest version of Rstudio, rebooted my machine several times...

### Describe the problem in detail

Rstudio does not offer to save the workspace on exit, even though this should be requested as the correct choice in the global options.

### Describe the behavior you expected

Rstudio should offer to save the workspace.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2024-02-13 14:45
@jmm34 Thank you for raising the issue! I'm unable to reproduce it, though, and can trigger the dialog on closing RStudio Desktop after just `x <- 1` in the Console Pane. Can you confirm that the option is set to "Ask" and not "Always?"  
<img width="250" alt="workspace" src="https://github.com/rstudio/rstudio/assets/31009952/bf438966-4d99-4ca6-b303-fc73a8989e9c">

**Comment by jmm34** [comment] 2024-02-15 08:34
Dear Ron,
Thank you for your help.
Yes the option is set to Ask.
Cheers,
Jean-Michel

**Comment by jmm34** [comment] 2024-02-15 08:55
Dear Ron,
I've just discovered that the problem occurs exclusively when I use the command q(). This issue isn't related to RStudio but to R itself, specifically because the default setting for the save argument of the quit function is no longer set to "ask". I apologize for my earlier request.
Best regards,
Jean-Michel

**Comment by jmm34** [comment] 2024-03-21 20:02
Any update?

**Comment by kevinushey** [comment] 2024-03-21 20:54
I can reproduce as well. More specifically, if I run:

```
x <- 42
quit()
```

then RStudio quits without prompting the user to save, even though I had previously set "Save workspace to .RData on exit" to "Ask". However, if I go into the Global Options dialog, set it to Ask, and then click OK to save those preferences, _then_ I am prompted to save on exit.

It looks like we're somehow not respecting a saved version of that preference on quit; I think this is worth fixing.

**Comment by jmm34** [comment] 2024-03-21 21:24
@kevinushey, thank you  very much for your update. On my side, I have to 
1) select another option, 
2) save,
3) select "Ask"
4) save again 
and then it's work; but, as you, just for the current session.
I think it’s good if someone can fix that.

**Comment by ronblum** [comment] 2024-03-25 11:13
Verified in RStudio Desktop 2024.04.0-daily+641 on Windows 11.

But the problem occurs still occurs RStudio Desktop 2024.04.0-daily+652 on MacOS, even after changing the preferences away from and back to "Ask."

**Comment by kevinushey** [comment] 2024-03-25 18:56
@ronblum it seems to work for me. Can you confirm what settings you have for both the Global Options and Project Options, and whether it depends on if you have a project currently open or not?

<img width="643" alt="Screenshot 2024-03-25 at 11 56 10 AM" src="https://github.com/rstudio/rstudio/assets/1976582/8a6af191-6024-4999-8a92-907e0698cb40">

<img width="571" alt="Screenshot 2024-03-25 at 11 56 25 AM" src="https://github.com/rstudio/rstudio/assets/1976582/8679348a-16bf-4d93-81ca-1f928ed519be">

**Comment by ronblum** [comment] 2024-03-26 14:04
All set! Verified in RStudio Desktop 2024.04.0-daily+657 on MacOS 14.4.

But: If you cancel in the dialog and then try to close again, you won't get prompted even if more changes are made. I'll file a separate issue for that.

**Closed by ronblum** 2024-03-26 14:04 UTC
Labels: bug
