### ISSUE TITLE
Problem with identify() in RStudio, works fine in RGui

### ISSUE THREAD

**Issue by Ghotitox** [rstudio/rstudio#3162] opened 2018-07-16 17:05 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.1.453 (but not a new issue, happening since I first tried this in April 2018)
    OS Version      :  Windows 10
    R Version       :  3.5.1 (but not a new issue, happening since I first tried this in April 2018)

### Steps to reproduce the problem
install.packages("titanic")
library(titanic)
data1<-titanic_train
plot(data1$Age~data1$Fare, pch=16,col=data1$Pclass,xlim=c(-150,550))
identify(data1$Age,data1$Fare,labels=data1$Name,tolerance=1)
Try clicking on any points with a fare over 125.  Clicking points on the far left of the plot seems to work, but would like to label the points on the far right. 

### Describe the problem in detail
Error: "warning: no point within 0.25 inches"
To try to find a workaround, I have tried changing the xlim, changing the label value, point type, and changing the tolerance. Labels work perfectly fine in standard RGui. 
***Update: Sorry about this- this example has problems in RGui as well. I thought that it was working fine in RGui, but I must not have been as observant as I had remembered.***

I have seen similar issues reported before, but those particular examples seem to work fine now- this one seems to be new.

### Describe the behavior you expected
I expect it to label the points with the Passenger Name (or anything else one might choose).

**Comment by pascaloettli** [comment] 2018-07-17 06:56
I just tried the code provided by the OP. I can confirm I get a (different) warning for any point for a fare above 200 (it works up to 150) : 
> warning: no point within 1.00 inches

Interestingly, the same warning appears in R running directly in console.

    RStudio Edition : Desktop
    RStudio Version : 1.2.822
    OS Version      : Ubuntu 18.04
    R Version       : 3.5.1

**Comment by ronblum** [comment] 2018-07-17 13:46
Reproduced with RStudio Desktop 1.1.453 and 1.2.830 using R 3.5.1 on MacOS 10.12.6 (Sierra), Windows 10, and Red Hat 7.5.

@pascaloettli Thanks for reporting this. We'll check it out as we work on future development of RStudio.

**Comment by OverLordGoldDragon** [comment] 2021-12-06 22:41
Reproduced in latest RStudio, Windows 10, no problem in RGui. Any progress?

**Comment by paulito-bandito** [comment] 2022-02-20 22:03
Can confirm this behavior is also happening with Windows in 10 RStudio ("R version 4.1.2 (2021-11-01)").

**Comment by ronblum** [comment] 2022-02-22 15:45
Thanks for updating us that it's still occurring! We just released a new version of RStudio Desktop, 2022.02.0+443 Prairie Trillium. Would you be willing to check if it still occurs in it? Thanks! https://www.rstudio.com/products/rstudio/download/#download

**Comment by paulito-bandito** [comment] 2022-02-22 19:31
No prob! Trying....

**Comment by paulito-bandito** [comment] 2022-02-22 19:40
Still an issue: So it can't identify when I click directly on the points, BUT curiously it's finding some of the points when I click outside the plot at the very bottom of the panel. 

![image](https://user-images.githubusercontent.com/5655808/155206339-7b359791-5100-4a68-aa09-4288dd8c703e.png)

**Comment by paulito-bandito** [comment] 2022-02-22 19:43
@ronblum If it helps, I'm using a Bootcamp version of Windows Home 10. Perhaps it's a driver I don't have installed?

**Comment by Ghotitox** [comment] 2022-02-22 20:19
I have recently tried it on both Windows 11 and on RStudio.Cloud, and it still doesn't work. Here is part of a video I made, where I show the behavior in RStudio.Cloud.  Same behavior you described.

**Comment by MORI-Yukito** [comment] 2022-02-24 15:55
You can call win.graph() before plot.
It is not cool, but works fine :)

**Comment by paulito-bandito** [comment] 2022-02-24 20:38
@MORI-Yukito Great interim solution! Thanks so much for posting this. This work-around is working for me too!

**Comment by Ghotitox** [comment] 2022-02-24 21:56
Thanks! Is there an equivalent solution for RStuio.Cloud?

**Comment by MORI-Yukito** [comment] 2022-02-25 04:53
@Ghotitox 
It seems there is no solution for RStudio.Cloud... 
We have to wait for an update.

**Comment by ronblum** [comment] 2022-02-25 13:18
This is reproducible in the R GUI and console, both in Windows 11 and MacOS 12.1. This repository is meant specifically for bugs and enhancements for RStudio. For problems with R,[ instructions for filing bugs reports](https://www.r-project.org/bugs.html) are at https://www.r-project.org/bugs.html

Since this is a problem in R outside of RStudio, I'm closing this ticket. I apologize for any confusion—I should have closed this earlier.

**Closed** 2022-02-25 13:19 UTC
Labels: bug, reproducible, external

**Comment by Ghotitox** [comment] 2022-02-25 16:17
OK, sorry- identify has **always** worked for me in R GUI, and **never** worked in RStudio or RStudio.Cloud.  I guess it is just me.

**Comment by ronblum** [comment] 2022-02-25 16:38
@Ghotitox No problem at all! It sounds like the problem with the R GUI or console isn't consistent. Also, I suspect that the reason I didn't close this initially is that I only checked RStudio and not standalone R, which I should've done. So, sorry about that, and thank you for raising this in the first place!

**Comment by barnabasharris** [comment] 2022-09-08 09:03
I'm getting this issue on RStudio Server running on Ubuntu.

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C 
```
Any work around?

**Comment by AdrianHordyk** [comment] 2022-12-14 19:34
I'm having this issue with RStudio 2022.07.2 Build 576. Works fine in RGui - only a problem in RStudio.

@MORI-Yukito's workaround works for me

**Comment by bweidel** [comment] 2023-07-17 14:59
I had this very frustrating issue for a couple of years and finely found the solution in a discussion issue about 'locator'.
https://stackoverflow.com/questions/73256552/problem-with-point-location-with-locator-function-in-r

My windows display zoom level and Rstudio zoom level were not the same, once I made them the same (100%), identify worked just as it did before.

**Comment by SocProf** [comment] 2023-09-19 00:46
This issue still happens in posit.cloud though.

I get this in the console:
`warning: no point within 0.25 inches
integer(0)`
