### ISSUE TITLE
Invalid Quarto preview path for default project if `_quarto.yml` and `.rproj` file are in different directories

### ISSUE THREAD

**Issue by dragonstyle** [rstudio/rstudio#14027] opened 2023-12-06 20:01 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  Version 2023.09.0+463 (2023.09.0+463)
    OS Version      :  MacOS Ventura
    R Version       :  4.3.0 (2023-04-21) -- "Already Tomorrow"

### Steps to reproduce the problem

[quarto-test.zip](https://github.com/rstudio/rstudio/files/13591041/quarto-test.zip)

- Unzip attached zip file
- Open RStudio project using RStudio
- Open `testing/quarto-test.qmd`
- Press the render button

### Describe the problem in detail

The render succeeds, but the URL used to open the preview will be:

`http://localhost:6768/testing/quarto-test.html`

but because the path to the file should be relative to the `_quarto.yml` file, the path should instead be:

`http://localhost:6768/quarto-test.html`

### Describe the behavior you expected

Successful preview using `http://localhost:6768/quarto-test.html`

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2024-01-09 00:00
I don't think this can work with the way RStudio's integration with Quarto is architected. There's a pretty strong assumption made throughout the code base that:

1. Each RStudio project has a single `_quarto.yml`,
2. That `_quarto.yml` file lives within the project root directory,
3. This file provides all relevant project-specific configuration (that is, there is no expectation of Quarto sub-projects, or `_quarto.yml` files within sub-directories that might affect files rendered in those directories).

This is where we try to infer the global Quarto configuration for a project:

https://github.com/rstudio/rstudio/blob/826d4f2da0fc4b85da265d91929cdfea3f1c4115/src/cpp/session/modules/quarto/SessionQuarto.cpp#L852-L857

Is this expected to be a common pattern? If so, I expect it will take some work to unravel how to support this consistently.

**Comment by kevinushey** [comment] 2024-01-09 00:22
It looks like we have some code that tries to parse URLs out of the Quarto output when figuring out where to browse, e.g.

https://github.com/rstudio/rstudio/blob/826d4f2da0fc4b85da265d91929cdfea3f1c4115/src/cpp/session/modules/quarto/SessionQuartoJob.cpp#L109-L124

But I'm not sure why the path is limited to only `web/viewer.html`. Should we be inferring the path to the file regardless of the rendered name?

**Comment by gtritchie** [comment] 2024-02-13 17:06
1. Reproduced the problem with 2023.12.1+402 "Ocean Storm".
2. With 2024.04.0-daily+440 "Chocolate Cosmos" the preview opens successfully.
3. As a sanity check, confirmed that a quarto project with _quarto.yml and the .Rproj file in the same folder still works as expected

Closing as verified.

**Closed by gtritchie** 2024-02-13 17:06 UTC
Labels: bug
