### ISSUE TITLE
Diagnostic warning: "X is defined but not used" when X is used within a glue expression

### ISSUE THREAD

**Issue by daattali** [rstudio/rstudio#3821] opened 2018-11-05 18:51 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      :  Windows
    R Version       : 3.4.3

### Steps to reproduce the problem

When I have `name <- "dean"; greeting <- glue("hello {name}")`; in my code, RStudio gives a warning that the variable `name` is not used. I definitely understand the technical difficulty in recognizing it within a glue expression, and it's entirely possible that you'll decide to close this as not-going-to-fix, but I just wanted to point it out in case someone over there has a clever simple solution :)

I can't show a small reproducible example because when I only have a few lines in an R script trying to make a minimal example, I can't get the diagnostics warnings to show up. I guess there might be some logic in the IDE that determines when diagnostics should start kicking in?

**Comment by ronblum** [comment] 2018-11-09 20:30
@daattali Do you have diagnostics set to show on save? That should force the message to appear on saving a small example:
    Tools -> Global Options -> Code -> Diagnostics -> Show diagnostics whenever source files are saved

<img width="331" alt="diagnostics_on_save" src="https://user-images.githubusercontent.com/31009952/48286616-3d23f880-e434-11e8-9000-a06463f5934a.png">

**Comment by daattali** [comment] 2018-11-09 21:42
Ah, thanks, I didn't realize it only shows diagnostics on save!

So I just went ahead and tried replicating this in a new file. But it seems like I'm seeing another diagnostic fail? :)

![image](https://user-images.githubusercontent.com/952340/48289699-62b5ff80-e43e-11e8-9311-261805839427.png)

That's a separate issue though

**Comment by almeidaxan** [comment] 2019-09-16 20:43
This warning message also keeps bugging me from time to time.

Here's a small MWE that gives the warning:

`library(glue)
greeting <- function() {
   name <- "xan"
   msg <- glue("hello {name}")
   msg
}
greeting()`

Just paste the MWE on a script, save it, and make sure to enable the option as suggested by @ronblum.

![image](https://user-images.githubusercontent.com/4544059/64991714-c1db7080-d8a8-11e9-8b3d-a65dd862f377.png)

**Comment by ronblum** [comment] 2019-09-17 13:37
Duplicate of #5270. Closing this one and copying over the reproducible example.

**Closed by ronblum** 2019-09-17 13:37 UTC
Labels: repro needed
