### ISSUE TITLE
Darkmode not implemented in Open File Pop up

### ISSUE THREAD

**Issue by mdeea** [rstudio/rstudio#14187] opened 2024-01-29 22:45 UTC
Thank you for your great work on Rstudio!

### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0 Build 369
    OS Version      : Ubuntu 22.04
    R Version       : 4.3.2 

### Steps to reproduce the problem
File > Open File  
from menu

### Describe the problem in detail
The background is not consistent with Dark mode

### Describe the behavior you expected
Shouldn't it be black like the main window?

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2024-02-01 16:56
You can make the Open File / Save File dialogs be in dark mode for RStudio Desktop on Linux, but it requires a couple steps.

First, you have to have Linux itself set to dark mode; this is independent of RStudio's dark themes. On Ubuntu 22, this is in Settings / Appearance. It would be nice to have RStudio automatically use a dark theme when the OS is using a dark theme but this isn't implemented (see second item in list of issues below).

Next you have to tell RStudio Desktop to use the operating system's File dialogs instead of RStudio's built-in dialogs (which are always light themed, see first item in list of issues below). Turn this on in RStudio under Tools / Global Options / General / Advanced: "Use native file and message dialog boxes".

Now you should see the operation system's standard File Open dialog, which will follow the operating system's light/dark mode setting.

Be aware that there is an issue in Electron (on which RStudio Desktop is built) which can cause these dialogs to sometimes appear under the RStudio main window (third item in list of issues below). This bug is why RStudio, on Linux, uses its own built-in dialogs by default instead of the operating system dialogs.

Lots of words, hope that helps!

### Related Issues (for reference)

- [Modal windows theme does not follow the general theme of the application #10296](https://github.com/rstudio/rstudio/issues/10296)
- [choose theme depending on os-level dark mode #5813](https://github.com/rstudio/rstudio/issues/5813)
- [Electron: showOpenDialog / showSaveDialog opens _behind_ the app after the second call onward #32857](https://github.com/electron/electron/issues/32857)

**Comment by gtritchie** [comment] 2024-02-02 18:03
I'm closing this as a duplicate of https://github.com/rstudio/rstudio/issues/10296; that's _essentially_ what you are encountering.

**Closed by gtritchie** 2024-02-02 18:03 UTC
Labels: bug, duplicate
