### ISSUE TITLE
R studio fatal error when loading data Ubuntu 18.04

### ISSUE THREAD

**Issue by monstaaa** [rstudio/rstudio#5080] opened 2019-07-09 11:57 UTC
rStudio will crash while loading data online via package quantmod. The error saying rStudio has encountered a fatal error and need to restart.

I tried both desktop version and server version, and having the same problem.

### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.2.1555
    OS Version      : Ubuntu 18.04
    R Version       : Microsoft R Open 3.5.3
    GPU: NVIDIA 1080 TI
    GPU Driver: Nvidia 418

### Steps to reproduce the problem

    install.package("quantmod")
    library("quantmod")
    getSymbols("SBUX") // any symbol will give the error

### Describe the problem in detail

    Once getSytmbols is executed, rStudio will either stuck for a while or immediately report fatal error. Then the session restart.

### Describe the behavior you expected

    load a data frame via online source

#### Crash report metadata
![image](https://user-images.githubusercontent.com/10230048/60886149-32b63a80-a21f-11e9-9d06-d4878d3bdb4f.png)

#### journal error
![Screenshot from 2019-07-09 07-36-15](https://user-images.githubusercontent.com/10230048/60885105-be7a9780-a21c-11e9-9584-a626a1db5531.png)
#### SegvAnalysis
![image](https://user-images.githubusercontent.com/10230048/60885417-87f14c80-a21d-11e9-9354-06f7c7baa359.png)

**Comment by david-cortes** [comment] 2019-07-09 15:14
Cannot reproduce. RStudio 1.2.1555, R 3.5.3 (also from MS), Windows 10.

**Comment by kevinushey** [comment] 2019-07-09 16:35
I'm not able to reproduce with R from the Debian repositories on my Ubuntu 18.04 VM.

The crash appears to be in the crypto libraries (`ssl3_cleanup_key_block()`) so I suspect this is either an issue with the version of OpenSSL on your system or with something with Microsoft R Open.

**Comment by ronblum** [comment] 2019-07-09 18:08
@monstaaa What happens when you run this in standalone R?

**Comment by monstaaa** [comment] 2019-07-10 02:42
Hello @david-cortes @kevinushey @ronblum ,

Thank you all for the information.

So after some testing, I can conclude that rStudio **is not** responsible for this crash. It is Microsoft-r(3.5.3 for Ubuntu 18). Maybe it is due to OpenSSL as @kevinushey said, but it is irrelevant here.

### Below is what I did for testing
OS: Ubuntu 18.04
rStudio: 1.2.1555
GPU driver: 390 // default by Ubuntu
#### steps
1.  fresh install Ubuntu 18.04
2.  install r-base 3.6 from apt // to isolate any effect that Microsoft-r may produce
3.  install rStudio 1.2.1555
4.  install package quantmod
5.  execute getSymbols <---- running without any error
6.  uninstall r-base via apt
7.  install Microsoft-r  
8. install package quantmod
9. execute getSymbols <----- same error as this morning

**Comment by jmcphers** [comment] 2019-07-20 00:39
Closing since you discovered it's not RStudio crashing; appreciate the detective work!

**Closed by jmcphers** 2019-07-20 00:39 UTC
Labels: repro needed
