### ISSUE TITLE
Environment list dropdown can fail to populate in some cases

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7215] opened 2020-06-24 21:21 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.3.1045
    OS Version      : macOS 10.15.5
    R Version       : 4.0.2

### Steps to reproduce the problem

In the Environment Pane, click the Global Environment button to view the R environments on the search path. While that popup is showing, press `Ctrl + 2` to focus the console.

### Describe the problem in detail

The dropdown list is cleared and a small empty box is shown; it cannot be re-populated on subsequent attempts to click the Global Environment button.

<img width="175" alt="Screen Shot 2020-06-24 at 2 20 03 PM" src="https://user-images.githubusercontent.com/1976582/85628919-cd24af00-b625-11ea-9163-7b803dc4b5dd.png">

### Describe the behavior you expected

Shortcuts that move focus should (probably) close any open menus, rather than clear the shown menu items.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-06-24 21:44
Looks like this is the culprit:

https://github.com/rstudio/rstudio/commit/f7e0c601b3c2ee6b0913aa227b58893c4d0f71ef#diff-a4493365058cdaad7ff9ccd51e286508R374-R382

@gtritchie, do you know if there's a more appropriate solution here? I wonder if we should instead be closing the menu explicitly rather than toggling its visibility?

**Comment by kevinushey** [comment] 2020-06-24 21:58
Seems like calling `hide()` there instead might be an appropriate fix?

**Comment by gtritchie** [comment] 2020-06-25 18:25
Fixed in 1.3 water-lily via ea9f21f

**Closed** 2020-06-25 18:25 UTC
Labels: environment pane, regression

**Comment by gtritchie** [comment] 2020-06-25 18:27
Fixed in master (1.4) via d1fadda

**Comment by R-Hannibal** [comment] 2020-07-06 15:00
Verified Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows 10 - Desktop 

Comparison testing between 1.3.1045 and 1.3.1054 (Current Preview), on the old build shifting focus using keyboards shortcuts caused the dropdown menu which was open to become corrupted/not display properly (issue persisted until the IDE was closed and then re-opened). The issue is fixed on the latest preview, did some additional testing around dropdown menus post-fix, opening/closing/closing using keyboard shortcuts/making sure they still function. No regression in functionality detected.
