### ISSUE TITLE
The "|>" ligature doens't work on editor but works on console

### ISSUE THREAD

**Issue by brunocarlin** [rstudio/rstudio#8550] opened 2020-12-07 17:13 UTC
### System details

    RStudio Edition : 
    RStudio Version : 1.4.1081
    OS Version      :  Windows 10 1809
    R Version       : R Under development (unstable) (2020-12-06 r79580)

### Steps to reproduce the problem

Just try this code

`2  |> mean()`

### Describe the problem in detail

I would expect this to print the same across console and editor

![image](https://user-images.githubusercontent.com/1176377/101382015-37f53a00-3896-11eb-8a91-eab2ac84e854.png)

### Describe the behavior you expected

I would like this:

![image](https://user-images.githubusercontent.com/1176377/101382038-40e60b80-3896-11eb-95a5-9bc52d28f4c3.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2021-02-13 00:15
![image](https://user-images.githubusercontent.com/470418/107835222-92ef5580-6d4d-11eb-92c3-f9f83a605fae.png)

**Comment by jmcphers** [comment] 2021-02-13 00:16
Looks like it's working in Juliet Rose. @ronblum can you confirm?

**Comment by brunocarlin** [comment] 2021-02-13 02:48
I know I am not supposed to be the one to test this but now it works for me on rstudio 1.4.1569!

**Comment by ronblum** [comment] 2021-02-16 14:38
@brunocarlin We have no objection to you or any other user checking if something works, so I appreciate your doing so and letting us know!

**Comment by ronblum** [comment] 2021-02-17 19:51
Confirmed that it works everywhere in the console and source editor in
- RStudio Desktop 1.4.1572 on MacOS 11.3
- RStudio Server 1.4.1571 on Ubuntu 20.04.2 using Chrome and Firefox on MacOS 11.3
using Fira Code.

However, it isn't fully working with the visual editor:
![new_pipe.png](https://codetreeusercontent.s3.amazonaws.com/uploads/797e37f6-287f-42dc-81b8-e281cb785b29/new_pipe.png)

@jmcphers Let me know if I should close this and open a separate issue for the visual markdown editor.

Note: code used for checking (wording represents current state of visual markdown editor).
````
---
title: "Works in a YAML |> block"
output: html_document
---

```{r}
Works in R |> chunk
```

```{bash}
Works in a bash |> chunk
```

Doesn't work with `inline |> code`

Doesn't work with |> text
````

**Comment by jmcphers** [comment] 2021-02-17 23:02
The triangle ligature is a feature of the font, not a feature of RStudio. It will not work in visual editor prose because that is rendered in a proportional font that doesn't have the ligature (nor should it as it's not code). 

I do think it should work in inline R code. If it doesn't, feel free to open another issue, although it is not likely to get attention for Juliet Rose as almost all code using lambdas is going to be multi-line.

**Comment by ronblum** [comment] 2021-02-18 16:42
Done! See #8989.

So, verified fixed.

**Closed** 2021-02-18 16:42 UTC
Labels: bug, source editor, test
