### ISSUE TITLE
Cannot set a custom keyboard shortcut that includes the Ctrl key and a letter

### ISSUE THREAD

**Issue by pjdon** [rstudio/rstudio#7244] opened 2020-06-27 19:39 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Windows 10
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Open **Keyboard Shortcuts** dialog by clicking **Toolbar** -> **Tools** -> **Modify Keyboard Shortcuts**
2. Set a custom shortcut for an action (e.g. **Clear All Plots**) that includes the **Ctrl** key and a letter key (e.g. **Ctrl** + **N**)
3. Press the shortcut keys to trigger the action

### Describe the behavior you expected

* In the **Shortcut** column, the shortcut should be `Ctrl + N` but instead says `Ctrl + □`
* The action should be triggered when the shortcut is pressed but does not

### Describe the problem in detail

* Entering `Ctrl + Shift` causes the same issue, but `Ctrl + Alt` does not
* Also affects the `\|` key
* Not all letters result in a `□` character. Some outliers:
`Ctrl + I` becomes `Ctrl + Tab`
`Ctrl + H` becomes `Ctrl + Backspace`
`Ctrl + J` becomes `Ctrl + `
`Ctrl + M` becomes `Ctrl + Enter`
* The shortcut that appears in the cell can be used to trigger the action. E.g. when you enter `Ctrl + I` for an action, you would then use `Ctrl + Tab` to trigger the action.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2020-06-27 23:38
This issue should be resolved in our preview release. Can you check 1.3.1054 and confirm that it's resolved for you there?

https://rstudio.com/products/rstudio/download/preview/

**Comment by gtritchie** [comment] 2020-06-28 17:58
Duplicate of #7142, which should be fixed in latest preview build as written above. Let us know if this is not the case.

**Closed** 2020-06-28 17:59 UTC
Labels: duplicate, keyboard shortcuts
