### ISSUE TITLE
In deployment dropdown menu, Clear List doesn't work

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#3998] opened 2018-12-05 18:59 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1165
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

* Deploy an application.
* Click on the publish dropdown arrow to show the menu, then select Clear List.
* The deployed application will still be shown in the dropdown menu.

I noticed that it doesn't delete the entry in the rsconnect/ subdirectory. For example, in this test app, after running Clear List, the file rsconnect/shinyapps.io/winston/test-slash.dcf still exists.

![shiny-deploy-clear-list 2018-12-05 12_57_51](https://user-images.githubusercontent.com/86978/49537056-888fc200-f88d-11e8-83d0-1e4d7e3e8ea4.gif)

**Comment by kevinushey** [comment] 2018-12-06 20:15
Should be fixed in the latest dailies -- thanks for reporting!

**Closed by kevinushey** 2018-12-06 20:15 UTC
Labels: bug

**Comment by ronblum** [comment] 2018-12-21 14:49
@wch Can you check if this works now? I'm unable to reproduce the problem.
