### ISSUE TITLE
Cursor position not synchronized with text after "fi"

### ISSUE THREAD

**Issue by juliangrimm225** [rstudio/rstudio#5061] opened 2019-07-03 09:13 UTC
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux
RStudio version 1.2.1335

Hello, my cursor space does not sync with the text in RStudio. If "fi" (for example in file) is written in the code, the font changes for this two characters. They become a little bit smaller (again, only these two characters). As far as I can tell, the cursors stays on the position where it should be. In the attached image is an example with two "fi" and the cursor on the last position possible on this line (no spaces or tabs at the end)

![Screenshot from 2019-07-03 11-13-50](https://user-images.githubusercontent.com/39006056/60579580-abcb1300-9d83-11e9-80c2-af70a203bc53.png)

Changing the fonts did not help. Any more ideas?

**Comment by ronblum** [comment] 2019-07-03 12:30
@juliangrimm225 Thank you for reporting this! Do you see this in multiple fonts or just one font, or multiple fonts? And what font/fonts are you using?

**Comment by juliangrimm225** [comment] 2019-07-03 14:26
I see this in Courier, LucidaTypewriter, MathJax_Vector, MathJax_Vector-Bold, Nimbus Mono PS, Noto Color Emoji and VT323. I do not see it in Source Code Pro and Source Code Variable. These are all the fonts I can choose. I will change my font to one of those then.

Also: I set the preferences to automatic line breaks. If a new line starts then, the cursor gets resetted.

**Comment by ronblum** [comment] 2019-07-03 14:38
@juliangrimm225 Thank you for providing this information! It will be when reviewing the bug as part of ongoing development of RStudio.

**Comment by kevinushey** [comment] 2019-07-03 16:41
I wonder if the issue is caused by ligatures? It looks like the `fi` in `file` is being collapsed into a single character; that may be messing up the cursor positioning.

**Comment by kevinushey** [comment] 2019-07-03 16:42
Thanks -- I think the issue is indeed caused by the ligatures here, since our editor expects all characters to be of the same length. When `fi` is collapsed into a single-width character, that likely confuses the computation of the cursor position.

**Comment by juliangrimm225** [comment] 2019-07-03 18:52
Just to clarify: the fi still stays two characters, in the right Position
you can delete both letters in their own. If you use the arrow keys and go
letter by letter through the line, you can delete them this way.

**Comment by mine-cetinkaya-rundel** [comment] 2019-09-18 15:09
I'm seeing a similar issue when using bolded text in multiple spots in a line. It is possible this is due to my font choice and ligatures. I'm using Fira font, on RStudio Version 1.2.1578.

**Comment by kevinushey** [comment] 2019-09-19 15:00
@mine-cetinkaya-rundel to double-check, are you using Fira or FiraCode? I would recommend FiraCode as it ensures ligatures are properly monospaced (ie: I can't reproduce this issue when using FiraCode)

**Comment by mine-cetinkaya-rundel** [comment] 2019-09-19 21:28
@kevinushey I confirmed that I am using 

- Fira Code, with 
- Modern RStudio theme
- 11 Font size
- Solarized Light editor theme

I couldn't get a good quality GIF of the screen capture, but you can view the video [here](https://youtu.be/ucrKvHtBF8g). Adding text in parentheses seemed to make matters worse.

**Comment by mine-cetinkaya-rundel** [comment] 2019-09-19 22:08
Follow up: I was able to resolve the issue by updating my FiraCode install with https://github.com/tonsky/FiraCode/. The issue was potentially due to having an old version of FiraCode, and not due to an issue with the RStudio IDE.

**Comment by jmcphers** [comment] 2019-12-09 21:25
Closing since we haven't had reports in months and it's likely due to an old FiraCode version with incorrect geometry for ligatures (thanks @mine-cetinkaya-rundel !)

**Closed by jmcphers** 2019-12-09 21:25 UTC
Labels: bug

**Comment by djvanness** [comment] 2020-06-03 19:09
This topic is showing closed, but I can confirm that I am having this problem with R 4.0.0 and Rstudio 1.3 on a RHEL system. Seems to happen on all fonts I have tried.

**Comment by kevinushey** [comment] 2020-06-08 22:00
Can you share a screenshot so we know exactly what you're seeing?

**Comment by djvanness** [comment] 2020-06-08 22:18
When typing, the text is inserted one position behind (to the left) of where the cursor is located after entering any text with 'fi' in it. I have confirmed it also does the same thing with 'fl'. 
In the screenshot, you can see in two places where 'fi' is joined into a single character ligature (fitted.model and file =). 
![image](https://user-images.githubusercontent.com/28707305/84085695-2220be00-a9b4-11ea-8423-e3aa4ff32408.png)

**Comment by kevinushey** [comment] 2020-06-09 05:06
Thanks! I believe the ligatures are indeed the issue. Because the line has two characters rendered as a single-width character, the cursor position is incorrectly computed.

Are you able to disable those ligatures, or select a font without ligatures?

**Comment by sethmund** [comment] 2023-02-06 02:56
Just ran across this issue using x11, I had to create a local fonts folder and set the XDG path so they could exchange to the node.
