### ISSUE TITLE
Rstudio resets window location / size

### ISSUE THREAD

**Issue by brry** [rstudio/rstudio#12463] opened 2022-12-19 20:34 UTC
### System details

RStudio Desktop 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
Windows10 Pro, Version 10.0.19044 Build 19044

### Steps to reproduce the problem

Open Rstudio, maximize screen, close and reopen.  The previous window location and size is not kept (as in the previous latest Rstudio version). Instead, the window is centered on screen at around half the screen area.

If I resize the window manually, the setting is kept. Except if I expand to near the screen border, it also resets.  
Size is not the issue, but location (if a stable shape is dragged closer to the screen edge, the next time it is resetted).

**Comment by ronblum** [comment] 2022-12-20 20:17
@brry Thank you for raising this issue! I can reproduce it partially in RStudio Desktop 2022.12.0+353 on Windows 11 and MacOS 13.2. In my case, the height is maintained, but the horizontal is only about 3/4 of the width. This is a regression from RStudio Desktop 2022.07.2+576. We'll review this as we continue development of RStudio.

**Comment by jmlietaer** [comment] 2023-01-07 11:31
**Same here - some additional info**

**When R-related file opened from File Explorer:**
Screen opens with top menu bar almost completely hidden. Resizing manually makes the top of the screen visible.
(cfr. screenshot in fine)

**When opened from RStudio shortcut (with property set to Run: Maximize):**
Screen opens in full screen mode (in default directory), as expected.

![rstudio](https://user-images.githubusercontent.com/12417447/211147839-124a1be8-b684-4903-9d03-7e66a74a2321.png)

**Comment by brry** [comment] 2023-01-09 08:36
This issue also props up with a script sent to a different window (left third of the screen) with the main Rstudio window in the right two thirds.  
When sending code from said script, the main window recenters, with the output in the console partly hidden behind the script window.  
It also seems to be mosty a position close to the top or bottom of the screen that triggers the reset, not so much proximity to the right of the screen.

**Comment by litotes18** [comment] 2023-01-11 06:29
Same issue with me, Win 10, 
RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

RStudio starts not maximized and I am not able to keep the window size maximized.

**Comment by psychbruce** [comment] 2023-03-22 16:42
Same issue (Win 11) still exists for RStudio-2023.03.0-386 (2023-03-16).
Keeping the window size maximized is necessary and important for many users.
I am wondering if this issue can be fixed in the next release?

**Comment by brry** [comment] 2023-03-24 06:38
Thanks, @jmlietaer - this works fine for me with the .bat file in "~".  
Note for others: the symbol in the file browser then is no longer the Rstudio logo.  
Here's a quick way the create the file from within R:
`cat("start /max rstudio.exe %1\nexit", file="~/RstudioMax.bat")`

**Comment by ebuhle** [comment] 2023-03-24 23:49
I have not tried the .bat file approach yet (while I very much appreciate the ingenuity, it seems fiddly and I'm really hoping this bug will get fixed soon) but I will note that this does not work in my case:

> **When opened from RStudio shortcut (with property set to Run: Maximize):**
> Screen opens in full screen mode (in default directory), as expected.

I normally launch RStudio from the Windows Start menu with Run set to Maximized, and I've been experiencing this issue with 2022.12.0+353.

**Comment by jmlietaer** [comment] 2023-03-25 08:41
@ebuhle - Sure, it is fiddly, but it works as a **temporary solution** to open R related files directly in RStudio in a maximized view.
I also hope the bug will be fixed soon, but even the latest RStudio version (4.2.3 - 2023-03-15) still has the bug.
As for the **Start menu**, you can of course put a shortcut to "rstudiomax.exe" in the Start menu, which will open simply open RStudio maximized.

**Comment by ebuhle** [comment] 2023-03-25 14:29
Sure, understood. I just mentioned the observation that Run: Maximized doesn't necessarily work as one more data point in case it might help the RStudio folks track down the bug.

**Comment by gtritchie** [comment] 2023-03-28 15:20
I am fixing this. There are two problems:

* the code that saves and restores main window location pays no attention to maximized state; this got missed when RStudio was ported to Electron
* the check if a window's saved location is still valid (e.g. due to changes in display layouts, different monitors, etc.) is way too aggressive; if even one pixel of a window falls outside a display it will treat that as offscreen and reset to a default location; I'll change this to be more like it was in the Qt version where as long as a reasonable amount of the window is visible it will consider it valid

Should have fixes for these in today (this will be for the next release, e.g. 2023.05 Mountain Hydrangea).

**Comment by ronblum** [comment] 2023-04-13 19:05
This is now working correctly in RStudio Desktop 2022.05.0-daily+212 on Windows 10.

On MacOS 13.2, this is mostly working. However, after restarting RStudio and un-maximizing the window, the IDE is positioned with the left edge or the right edge aligned with the center of the screen, depending on whether it was previously positioned more towards right or left side of the screen.

**Comment by ronblum** [comment] 2023-04-13 20:14
Closing this issue as Windows-specific, which is all set. I'll open a new issue for MacOS.

**Closed by ronblum** 2023-04-13 20:14 UTC
Labels: bug, regression, electron

**Comment by brry** [comment] 2023-04-13 20:57
Thank you so much! I'm looking forward to testing it soon ;)

**Comment by brry** [comment] 2023-05-22 08:15
I'm sorry to report that the issue persists.
I removed all Rstudio components (incl in AppData/Roaming) and installed RStudio 2023.03.1+446 "Cherry Blossom" Release (6e31ffc3ef2a1f81d377eeccab71ddc11cfbd29e, 2023-05-09) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.1+446 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
Rstudio doesn't launch in full window, regardless of the previous settings.

**Comment by gtritchie** [comment] 2023-05-22 14:30
This fix is in the next release of RStudio (2003.05) not in 2003.03.

**Comment by stewartli** [comment] 2023-07-16 00:47
yes, this issue is fixed after installed the newest version of rstudio. however, there is another one. when i start a new session, TWO rsdutio IDE come out. thanks for the help.

**Comment by ronblum** [comment] 2023-07-17 12:21
@stewartli Since this is a different problem, can you open a new issue for it? Thanks!

**Comment by cleitonmoya** [comment] 2024-08-29 14:37
When sourcing without echo (Ctrol+Shift+S) a script that is opened in another window, the main window of RStudio exits its maximized state. With Ctrl+Shit+Enter, this problem does not occur.
I'm using RStudio 2024.04.2 Buld 764 on Windows 10.
