### ISSUE TITLE
Destructive changes when switching to visual rmarkdown editor

### ISSUE THREAD

**Issue by gorkang** [rstudio/rstudio#8030] opened 2020-10-10 10:29 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.869
    OS Version      :  Ubuntu 18.04
    R Version       :  4.0.2

### Steps to reproduce the problem

Create a Rmarkdown document:

(1) Include a line that start with `[]:`. For example: `[TODO]: Do a thing`
(2) Include a line that that start with `[]`. For example: `[] Text`

In the attached file, switching to visual rmarkdown editor causes the problems described here: [rmarkdown.zip](https://github.com/rstudio/rstudio/files/5358801/rmarkdown.zip)

### Describe the problem in detail

- Lines (1) will disappear
- In lines (2), the `[]` will disappear

### Describe the behavior you expected

Content should not disappear when switching to the visual editor

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment] 2020-10-11 12:52
Believe it or not that is actually the standard behavior for Pandoc when it sees a [reference link](https://pandoc.org/MANUAL.html#reference-links) that doesn't resolve to a link label elsewhere in the document. Here you can see what happens when we include these links and then ask pandoc to convert to it's internal AST (note that the document as represented by `blocks` is empty):

```bash
$ echo '[TODO]: Do a thing' | pandoc --to json | jq .
```
```
{
  "blocks": [],
  "pandoc-api-version": [
    1,
    21
  ],
  "meta": {}
}
```

```bash
$ echo '[]: text' | pandoc --to json | jq .
```

```
{
  "blocks": [],
  "pandoc-api-version": [
    1,
    21
  ],
  "meta": {}
}
```

If you try converting to html using the command line you'll similarly get an empty document:

```bash
echo '[TODO]: Do a thing' | pandoc --to html
```

So while those reference links are being removed by the visual editor (b/c we use pandoc to read the markdown) they will also be removed by pandoc when you render the document.

If however there is a valid target for the reference link within the document then it's preserved by pandoc. For example, compare rendering this markdown (which yields an empty document):

```markdown
[google]: https://www.google.com
```

With rendering this markdown:

```markdown
[google]: https://www.google.com

[google][]
```
Which yields a link to google.

Similarly, if you include a target for your reference link within the document then visual editor will preserve it (however the "preservation" is effectively turning it into a normal link, as this is what pandoc does when converting reference links to it's internal AST representation). Translation: because we read markdown with pandoc and pandoc "erases" reference links one way or another, they aren't supported by visual mode.

**Comment by kevinushey** [comment] 2020-10-13 16:55
@jjallaire, do you think it would be worth detecting or warning in cases like these, where content in a source document might be lost when activating visual mode? (Is this the only case, or are there other examples where this could occur?)

**Comment by jjallaire** [comment] 2020-10-15 12:01
We actually won't know that this happened unless we pre-inspect the source document (e.g with regexes) to find possible instances of it. We could do this but it would be pretty expensive so not something we can do for v1.4.

**Comment by adamconroy** [comment] 2020-11-17 18:49
moving to 1.5 milestone (but seems like it might be closed as "by design") as it has been specified above that this will not be done in 1.4

**Comment by bakaburg1** [comment] 2021-08-31 13:50
Hello, wouldn't be simple to leave to original source untouched?

**Comment by ronblum** [comment] 2021-08-31 14:02
@bakaburg1 The visual editor by default updates the source to conform to standard Pandoc format.  It's possible to set the document to canonical mode so that the source code is unaffected. See https://rstudio.github.io/visual-markdown-editing/markdown.html#canonical-mode for details.

Also reopening so that we can reconsider the above https://github.com/rstudio/rstudio/issues/8030#issuecomment-709244147.

**Comment by jjallaire** [comment] 2021-09-13 16:42
@bakaburg1 We can't leave the source untouched as it has to parsed into the Pandoc AST, edited as an AST, then re-written to markdown (i.e. the visual editor is not editing raw text it's editing the logical structure of the document, and since parsing Pandoc markdown is quite complex we need to rely on Pandoc to do this). We also rely on Pandoc to write markdown, which does impose some limitations (all summarized here: https://rstudio.github.io/visual-markdown-editing/markdown.html#markdown-output). 

So I think we do need to close this as by design. In the future Pandoc may move to a new parser that preserves more source context (how much is hard to say though) and at that point improved source preservation will be possible.

**Closed by jjallaire** 2021-09-13 16:42 UTC
Labels: enhancement, visual markdown editing
