### ISSUE TITLE
data.table results do not show and RStudio freezes after a few enters with R4.3 on Mac

### ISSUE THREAD

**Issue by Fred-Wu** [rstudio/rstudio#13084] opened 2023-05-03 01:01 UTC
RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386 
    OS Version      MacOS 13.3.1: 
    R Version      4.3 : 

I am testing the new experimental feature `_` in R4.3 on my Macbook using `data.table` package
However, the following codes do not return anything in the RStudio Console. 

```
library(data.table)
dat <- data.table(a = c(1,2,3,4), b = c("a", "a", "b", "b"))
dat |> _[, .(sumA = sum(a)), by = b]
```

Also, after I sent the codes for a few times to the console, RStudio just froze as in the pic below. 

<img width="683" alt="image" src="https://user-images.githubusercontent.com/4111978/235815216-e0416d5a-e3d6-4e1d-a6c3-cf2891c4ed7e.png">

It worked after I forced it to quit and re-launched, but not the first time. 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/4111978/235815518-f1906fce-bff5-4dd8-93f5-ec4da6f0f3f7.png">

**Comment by kevinushey** [comment] 2023-05-03 04:43
Sorry, but I wasn't able to reproduce locally. Can you provide any other details? Have you configured data.table to use OpenMP?

The output of `data.table::getDTthreads()` might also be helpful.

**Comment by Fred-Wu** [comment] 2023-05-03 11:02
It was compiled from the source with OpenMP support. But the initial package loading did not show this above. 

I restarted RStudio, now the multi-thread information appeared. But `getDTthreads()` also did not return anything. 

<img width="678" alt="image" src="https://user-images.githubusercontent.com/4111978/235897762-8e415ad9-f7f3-4c86-8cc1-b37a974eaeea.png">

There is no issue when running the codes in `vscode-R`.

**Comment by kevinushey** [comment] 2023-05-04 19:49
The "officially" supported way is to follow the directions at https://mac.r-project.org/openmp/.

Alternatively, if you're using Homebrew, you can use:

```
brew install libomp
```

And then edit (or create) a file at `~/.R/Makevars` to have the contents:

```
CPPFLAGS = -Xclang -fopenmp -I/opt/homebrew/opt/libomp/include
PKG_LIBS = -L/opt/homebrew/opt/libomp/lib -lomp
```

**Comment by kevinushey** [comment] 2023-05-07 21:38
Perhaps a duplicate of https://github.com/rstudio/rstudio/issues/13091, if the issue arises from having both diagnostics enabled + usages of the pipe-bind operator?

**Comment by ronblum** [comment] 2023-05-08 11:14
@Fred-Wu If you're interested in checking the fix in the upcoming Mountain Hydrangea release, [daily builds for it](https://dailies.rstudio.com/) are available at https://dailies.rstudio.com/. Please note that the dailies are for testing purposes only, not production.

**Comment by Fred-Wu** [comment] 2023-05-11 00:47
> @Fred-Wu Would you be willing to check the fix in the upcoming Mountain Hydrangea release, [daily builds for it](https://dailies.rstudio.com/) are available at https://dailies.rstudio.com/. Please note that the dailies are for testing purposes only, not production.

I have tested the latest daily builds 334 for MacOS. The issue seems to have been resolved. Thanks.

**Closed** 2023-05-11 07:32 UTC
Labels: bug, info needed
