### ISSUE TITLE
Open project in new R session button is not working anymore

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#11600] opened 2022-07-12 09:29 UTC
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.10.0.59
    OS Version      : Windows 10 x64 (build 22000)
    R Version       : R version 4.2.0 (2022-04-22 ucrt)

### Steps to reproduce the problem

* Open RStudio IDE in no project (or in a project)
* Try to change project from the menu with new R session button 
![image](https://user-images.githubusercontent.com/6791940/178458088-bc606c8c-a41b-46bb-b30d-197b93d4b0b2.png)

following @ronblum suggestion, this also happens when doing Session > New Session... for menu bar.
![image](https://user-images.githubusercontent.com/6791940/178541266-9e6d471f-42c0-482a-8838-70e69bd6398c.png)

### Describe the problem in detail

* At first nothing seems to happen when clicking the button
* After some time, a new RStudio window opens ~**but in background** so easily missed (previously new window was opening in foreground)~ - EDIT: don't know why, but it opens in the foreground now during live test with @ronblum 
* This new RStudio window does not have the project open - it opens in "no project" mode no matter if the state of the original IDE window 

### Describe the behavior you expected

I expect the project to open in a new Rstudio shown in foreground

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/9100265/diagnostics-report.txt)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-07-12 14:44
@cderv I'm not experiencing the same behavior—the project opens in a new window, on top of the previous window. Does this happen with all projects, or is it only a subset?

I do see the lag in opening the new window. I'll file an issue related to that.

**Comment by cderv** [comment] 2022-07-12 14:46
yes it seems to be with all project. I can screenshare with you live if you want to see and advice on some test to do.

**Comment by ronblum** [comment] 2022-07-12 14:57
Sounds good! I'll reach out to you shortly.

**Comment by ronblum** [comment] 2022-07-12 16:05
@timtmok—we looked at this in a number of ways together. But when we're going through the same steps, @cderv runs into the issue, while it works for me. Do you have any suggestions of what else to try out?

**Comment by timtmok** [comment] 2022-07-12 20:08
@ronblum I'll have to double-check what the code is doing but I recently (~2 weeks ago) implemented the window layering event. I hope that it's being called so that it brings the new window into the foreground.

**Comment by cderv** [comment] 2022-07-12 21:00
> I hope that it's being called so that it brings the new window into the foreground.

@timtmok for this part it seems to work the foreground. I don't know what it did not in the first place. 

The most impactful issue is that no project is open while either

* New session should open a new window with the same project
* Open Project in a new windows should open the selected project in a new window

If there is anything I can activate to see more log information about what is trying to be open, I'll be happy to run it for you, as @ronblum can't reproduce on his side.

**Comment by timtmok** [comment] 2022-07-12 21:50
If you could set `RS_LOG_LEVEL` to `debug` and attach the rdesktop.log after the issue occurs, that might help me determine the cause.

I'll try reproducing again on a different Windows machine since I'm using arm64 Windows most of the time.

**Comment by cderv** [comment] 2022-07-12 22:28
Here is the log file 
[rdesktop.2022-07-13.log](https://github.com/rstudio/rstudio/files/9097251/rdesktop.2022-07-13.log)

**Comment by jgutman** [comment] 2022-08-17 19:18
I wonder if this is related to #11730 -- what I saw there was a new session being opened, but with no active project. Seems like that is a dupe?

**Comment by timtmok** [comment] 2022-08-17 21:02
@jgutman it might be the same issue. If you turn on debug logging and check the logs, we might be able to confirm. Check for `RS_INITIAL_PROJECT` in the logs.

@cderv I think the issue here is the `RS_INITIAL_PROJECT` isn't set as I can see from the logs. I haven't been able to reproduce (2022.10.0.97). There might be a problem initializing the new session but I haven't discovered the cause.

**Comment by cderv** [comment] 2022-08-19 12:37
Hi @timtmok , 

I tested with latest daily 2022-11.120 and I can't reproduce anymore. So it was either fixed, or my system was in some state where the variable was not set. 

Feel free to consider this to close then.

**Comment by kevinushey** [comment] 2022-08-19 20:09
FWIW, I'm seeing this issue as well so I don't think it's resolved yet.

RStudio 2022.11.0-daily+116 "Elsbeth Geranium" Daily (3eaa7d9eed65a954275dcc46766a5448b41b55bc, 2022-08-18) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+116 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36

**Comment by jgutman** [comment] 2022-10-11 15:13
@kevinushey I'm having some trouble reproducing this now on Mac or Windows as of 2022.12.0.257

@kevinushey or @cderv can you still reproduce?

**Comment by jonvanausdeln** [comment] 2022-10-11 17:38
I also cannot reproduce the issue on Windows 11, MacOS 12.4, nor Ubuntu 22.04
All running 2022.11.0-daily+244
If no one can reproduce now, I will close this out.

**Comment by kevinushey** [comment] 2022-10-11 21:34
I'm no longer able to reproduce in the latest dailies.

**Comment by jonvanausdeln** [comment] 2022-10-12 21:16
Since no one can reproduce, I am going to close this out.

**Closed by jonvanausdeln** 2022-10-12 21:16 UTC
Labels: bug, projects
