### ISSUE TITLE
launching rstudio with 'sudo rstudio' can cause future rstudio launches to fail

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#6270] opened 2020-02-20 18:00 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.5033, v1.3.851
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.2

### Steps to reproduce the problem

Execute the following to launch RStudio:

```
sudo rm ~/.rstudio-desktop
sudo rstudio
```

RStudio will successfully launch. Try changing a preference (e.g. change the editor theme), save those preferences, and close RStudio.

Then, launch RStudio again with:

```
rstudio
```

### Describe the problem in detail

RStudio launch fails, with:

```
$ rstudio
"Uncaught TypeError: Cannot read property 'notifyRCrashed' of undefined"
```

printed in the console, and the generic "R failed to start" page shown.

### Describe the behavior you expected

Either:

1. RStudio should be able to recover when the default preference location is not readable / writable;
2. RStudio should more clearly indicate that the error was caused by an inability to read / write files within the `~/.rstudio-desktop` folder.

Note that one can recover from this state either by removing the `~/.rstudio-desktop` folder, or by fixing permissions.

See also: https://github.com/rstudio/rstudio/issues/4500

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-02-20 18:02
Another frustrating component of this bug: because `~/.rstudio-desktop` is not writable, there is nothing actionable in the diagnostics report as RStudio is unable to read / write the diagnostics log file on start.

**Comment by mikebessuille** [comment] 2020-07-16 18:06
Duplicate of #4505

**Closed** 2020-07-16 18:05 UTC
Labels: bug, session internals

**Comment by R-Hannibal** [comment] 2020-08-18 21:58
Marking this issue as verified and adding duplicate label.
