### ISSUE TITLE
Terminal whacky with RTools 4.0 on the PATH

### ISSUE THREAD

**Issue by AshesITR** [rstudio/rstudio#6939] opened 2020-05-22 06:20 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.957
    OS Version      : Windows 10
    R Version       : 4.0.0

### Steps to reproduce the problem

* Install RTools 4.0
* Put it on the PATH
* Open up a Terminal in RStudio

### Describe the problem in detail

An error message from `cut` appears: 

    /usr/bin/cut: you must specify a list of bytes, characters, or fields
    Try '/usr/bin/cut --help' for more information.

Interaction with the terminal produces weird behaviour:

    $ rm --help
    /usr/bin/rm: missing operand
    Try '/usr/bin/rm --help' for more information.

    $ where rm
    C:\rtools40\usr\bin\rm.exe
    C:\Program Files\Git\usr\bin\rm.exe

    $ where cut
    C:\rtools40\usr\bin\cut.exe
    C:\Program Files\Git\usr\bin\cut.exe

### Describe the behavior you expected

Unchanged behaviour compared to RTools 3.5 / R 3.6.3. 

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2020-05-22 15:34
This is a duplicate of #6828

**Closed by gtritchie** 2020-05-22 15:34 UTC
Labels: duplicate, terminal, windows
