### ISSUE TITLE
File cannot be saved when created through File > New File

### ISSUE THREAD

**Issue by timtmok** [rstudio/rstudio#11515] opened 2022-06-28 12:06 UTC
### Steps to reproduce:
* Create a file using File > New File (any type will do)
* Attempt to save the file (any name will do)

The file is not saved and does not show up in the Files pane. The editor shows the file name as `Untitled`. Attempting to create another file has the same result except that it may show the file in the Files pane. However, it is _not saved_ and refreshing the pane makes the file disappear.

So far, an issue on Windows. Mac saves the file successfully.

### Expected
The file should be saved.

Build: 2022.07.0+544 Electron
OS: Windows

**Comment by timtmok** [comment] 2022-06-29 18:02
I'm testing a fix locally for this. It seems that there is a bug with normalizing the save path. I also discovered another issue with the path normalization that assumes the user is saving the file to their home directory (or subdirectory of it). Going to run through some other tests to make sure this works correctly.

It's also only occurring in builds because local dev build behaves slightly differently with the environment variables.

**Comment by timtmok** [comment] 2022-06-30 12:50
Some things to test with the fix are:
* saving somewhere within the user's home directory
* saving on Linux or Mac since the altered code is shared with these platforms
* saving to a network location or outside of the home directory

If the path is not accessible (i.e. no permission), the save does result in a descriptive enough error message on Windows but not on Mac (says the path doesn't exist). On Windows, it does allow choosing a new path. On Mac, the dialog has closed and attempting to save again results in the same error message without the option to choose a new path (same thing occurs in a Qt build).

**Comment by dfalty** [comment] 2022-07-01 12:20
@andrie the fix would not be in 544. Looks like the fix is in [547](https://dailies.rstudio.com/version/2022.07.0+547.pro4/).

**Comment by ronblum** [comment] 2022-07-01 12:42
On MacOS 12.5, RStudio Desktop 2022.07.0+547
* The "Save" options work, saving outside of the home directory works
* The "Save All" options don't work (for new files)

**Closed** 2022-07-01 12:55 UTC
Labels: bug, electron, test

**Comment by anwhite003** [comment] 2022-07-02 09:07
Why does this appear to be a closed issue ??
I just downloaded RStudio 2022.07.0 Electron for latest build preview version on Windows 10 at work (on an HP Z2) and the GUI absolutely fails to save an RScript file, whether I select a new path or leave the standard directory I have for the RStudio Project.  If I quit & switch back to Non-Electron version of PRIOR RStudio Preview release, the R Script file is saved. This would APPEAR to be an Electron issue and AFAIK should NOT be closed. - Andy White (Friday 1 July 2022)

**Comment by gtritchie** [comment] 2022-07-02 16:14
I suspect the preview release hasn't been updated with the fix yet. Haven't confirmed as I'm on my phone at the moment.

You could try a daily build which should have the fix (again, I haven't confirmed). Pick the most recent from https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/windows/ and give it try.

**Comment by anwhite003** [comment] 2022-07-02 18:10
Mahalo Gary 
I will try that 
Thanks for your quick response!

With Aloha, Andy

**Comment by anwhite003** [comment] 2022-07-02 23:20
Double Mahalo Gary

RStudio Preview 2022.07.0 Build 545 Electron
Spotted Wakerobbin
for macOS
 now implements the file save fix.
That works fine now. 

With Aloha, Andy

**Comment by anwhite003** [comment] 2022-07-03 21:21
Aloha Gary

Once more RStudio Electron Issue for your consideration - an Extra Auto-Inserted Period in R Code & Console


While RStudio 2022.07.0 B545 Electron now saves RScripts just fine
I think I have noticed another “bug” in the Electron based text.code editing of an R Script in RStudio

Unlike the previous Qt based underpinnings
I think Electron has  a default setting which acts a LOT like an iPhone text editor 
which inserts a “.” when the user types more than once space rapidly in succession

Exemple:


Look at my snapshot example of R code I typed just now:
look at Line #8:  you see that after the “#” character, when I rapidly typed spaces
the editor in fact entered on its own volition a period “.”

This ALSO happens in the Console window as I just verified !

(I did not type that period, I simply hit the space bar rapidly 4 times.


Can you have this checked out?
Should I post it officially to GitHub RStudio Issues for Electron ?

Aloha
(and happy fourth)
Andy
