### ISSUE TITLE
'edit'/'undo' does not behave like keyboard shortcut for 'undo'  (MacOS)

### ISSUE THREAD

**Issue by FredMasc** [rstudio/rstudio#3511] opened 2018-09-20 08:47 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : MacOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem
To undo, one can use  CMD + z  or go to the menu 'Edit' and click on 'undo'

### Describe the problem in detail
Go to the menu 'Edit' and click on 'undo' open a box about 'saving changes' before closing the file.

### Describe the behavior you expected
Go to the menu 'Edit' and click on 'undo' should cancel the last action like  CMD + z  does.

**Comment by kevinushey** [comment] 2018-09-20 15:31
I'm not able to reproduce this -- can you provide any other information? Have you rebound any keys on your system (e.g. OS-level keyboard shortcuts or RStudio's own keyboard shortcuts)?

**Comment by kevinushey** [comment] 2018-10-23 14:30
Thanks; I can reproduce this now. This is also an issue in the current preview release of RStudio.

**Comment by kevinushey** [comment] 2018-10-23 19:31
Looks like this is already fixed in the v1.2 branch. (You can download the latest preview at [preview release](https://www.rstudio.com/products/rstudio/download/preview/))

**Closed** 2018-10-23 19:32 UTC
Labels: bug, reproducible
