### ISSUE TITLE
Unable to load workspace in Windows due to encoding translation failure

### ISSUE THREAD

**Issue by javbermejo** [rstudio/rstudio#8321] opened 2020-11-09 18:43 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.4.1010
    OS Version      :  Windows 10
    R Version       :  4.03

### Steps to reproduce the problem

When loading a project stored in a windows path which includes non UTF8 characters, workspace is not loaded. The full error in RStudio reads:

WARNING: Failed to restore workspace from 'C:/Users/javie/Desktop/HGUGM CARDIOLOGIA - InvestigaciÃ³n Imagen - InvestigaciÃ³n Imagen/Indices of AS/Stats Indices of AS/.RData'
Reason: unable to translate 'C:/Users/javie/Desktop/HGUGM CARDIOLOGIA - Investigaci<f3>n Imagen - Investigaci<f3>n Imagen/Indices of AS/Stats Indices of AS/.RData' to native encoding

### Describe the problem in detail
The Windows path is 'C:/Users/javie/Desktop/HGUGM CARDIOLOGIA - Investigación Imagen - Investigación Imagen/Indices of AS/Stats Indices of AS/.RData'

Tried different locales but error persists:
Sys.setlocale(locale = "Spanish")
[1] "LC_COLLATE=Spanish_Spain.1252;LC_CTYPE=Spanish_Spain.1252;LC_MONETARY=Spanish_Spain.1252;LC_NUMERIC=C;LC_TIME=Spanish_Spain.1252"
Warning message:
In list.files(cacheDir) :
  unable to translate 'C:/Users/javie/Desktop/HGUGM CARDIOLOGIA - Investigaci<f3>n Imagen - Investigaci<f3>n Imagen/Indices of AS/Stats Indices of AS/.Rproj.user/58CB7782/explorer-cache' to native encoding

### Describe the behavior you expected

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2020-11-10 00:45
Closed by https://github.com/rstudio/rstudio/pull/8322.

**Comment by valerie-rstudio** [comment] 2021-02-04 19:03
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1545
    OS Version      : Windows 10
    R Version       : 4.0.3

Verified that RStudio projects with non-ASCII characters in the pathname can be created/loaded. Tested with the reporter's pathname as well as other various non-ASCII characters.

### NOTES
- I was unable to repro the original issue on 1.4.1010, even using the reporter's provided project path.

**Comment by valerie-rstudio** [comment] 2021-02-05 22:03
### Reopen
    RStudio Edition : Desktop
    RStudio Version : 1.4.1548
    OS Version      : Windows 10
    R Version       : 4.0.3

### Steps to reproduce the problem
1. Create a new R project in a folder named with non-ASCII characters
2. Attempt to run any R code from either an R script or the Console
3. **Expected Results**: code runs without issue
4. **Actual Results**: warning message appears in console

### Notes
- The following warning message appears when attempting to run R code:
`Warning message:
In list.files(cacheDir) :
  unable to translate 'C:/Users/valeriemalcomb/Documents/HGUGM CARDIOLOGIA - InvestigaciÃ³n Imagen - InvestigaciÃ³n Imagen/<U+0B87><U+0BA8><U+0BCD><U+0BA4><U+0BBF><U+0BAF><U+0BBE>/.Rproj.user/BF5BCAE7/explorer-cache' to native encoding`
 - Pathname used for testing: `C:\Users\valeriemalcomb\Documents\HGUGM CARDIOLOGIA - InvestigaciÃ³n Imagen - InvestigaciÃ³n Imagen\இந்தியா`
 - Unsure as to why I was initially unable to reproduce this issue when verifying. Ran into this issue while verifying another bug.

**Comment by kevinushey** [comment] 2021-02-08 21:23
I spent some time looking at this further and ultimately I don't think we can expect RStudio to work for users who are working with paths not representable in the native system encoding. There are just too many internal R APIs that force conversion to the native encoding that making this work not possible.

That said, what confused me about the original issue is that:

```
> path <- enc2utf8("C:/Users/javie/Desktop/HGUGM CARDIOLOGIA - Investigación Imagen - Investigación Imagen/Indices of AS/Stats Indices of AS/.RData")
> 
> Sys.setlocale(locale = "English")
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> native <- enc2native(path)
> Encoding(native)
[1] "latin1"
> native
[1] "C:/Users/javie/Desktop/HGUGM CARDIOLOGIA - Investigación Imagen - Investigación Imagen/Indices of AS/Stats Indices of AS/.RData"
> 
> Sys.setlocale(locale = "Spanish")
[1] "LC_COLLATE=Spanish_Spain.1252;LC_CTYPE=Spanish_Spain.1252;LC_MONETARY=Spanish_Spain.1252;LC_NUMERIC=C;LC_TIME=Spanish_Spain.1252"
> native <- enc2native(path)
> Encoding(native)
[1] "latin1"
> native
[1] "C:/Users/javie/Desktop/HGUGM CARDIOLOGIA - Investigación Imagen - Investigación Imagen/Indices of AS/Stats Indices of AS/.RData"
```

... it should be possible to convert the supplied path to the native encoding, regardless.

**Comment by kevinushey** [comment] 2021-02-08 21:28
@valerie-rstudio: can you re-test using a path only containing latin1 characters, e.g. a project called "prøject"?

**Comment by valerie-rstudio** [comment] 2021-03-09 18:31
@kevinushey: 
It does look like it was an issue on RStudio 1.4.1010. With only the project/directory named Prøject, you get the following warning when attempting to run R code
 `Warning message:
In list.files(cacheDir) :
  unable to translate 'C:/Users/valeriemalcomb/Documents/Pr<f8>ject/.Rproj.user/BF5BCAE7/explorer-cache' to native encoding`.

On our latest daily, 1.4.1623, I'm no longer seeing that warning, but I don't think the encoding is being translated correctly. The project and directory are still named Prøject, but in the console I'm seeing `[Workspace loaded from ~/PrÃ¸ject/.RData]`

**Comment by kevinushey** [comment] 2021-03-15 20:34
> On our latest daily, 1.4.1623, I'm no longer seeing that warning, but I don't think the encoding is being translated correctly. The project and directory are still named Prøject, but in the console I'm seeing [Workspace loaded from ~/PrÃ¸ject/.RData]

That should be fixed in the latest dailies now as per https://github.com/rstudio/rstudio/pull/9068.

**Closed by kevinushey** 2021-03-15 20:34 UTC
Labels: bug, test
