### ISSUE TITLE
Outputs in console always move focus to the end

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8535] opened 2020-12-04 09:29 UTC
**Steps to reproduce:**
* Execute many statements so as to make the console scrollable.
* Execute something that would produce a lot of prints in the console (e.g. reading a large file through `readr`).
* Try to scroll up while there are statements or progress bars being printed.

**Expected behavior:** should allow scrolling. Focus should be set to the end if the currently visible section of the scroll includes the last line, like in terminal emulators such as konsole or windows' cmd.

**Actual behavior:** every time something new (a print statement or continuation of a progress bar) is sent to the console, focus moves to the end, losing the scrolling.

**Setup:** RStudio 1.4.1056, running on debian bullseye, KDE plasma 5.19.5, QT 5.15.1.

**Comment by jmcphers** [comment] 2020-12-04 17:56
Do you have console output limiting turned on? (Options -> Console -> Limit console display)

**Comment by kevinushey** [comment] 2020-12-04 18:08
Duplicate of https://github.com/rstudio/rstudio/issues/8504. You may also want to test + confirm with the latest [preview release](https://www.rstudio.com/products/rstudio/download/preview/) (1.4.1074).

Can you please add comments (+ a reproducible example if at all possible) in https://github.com/rstudio/rstudio/issues/8504?

**Closed by kevinushey** 2020-12-04 18:08 UTC
