### ISSUE TITLE
Cannot view typed text in text field when renaming a file in files pane

### ISSUE THREAD

**Issue by apreshill** [rstudio/rstudio#4497] opened 2019-03-22 20:07 UTC
### System details

    RStudio Edition : 
    RStudio Version : 1.2.1330
    OS Version      :  Mojave 10.14.13 <- typo Mojave 10.14.3
    R Version       : 

### Steps to reproduce the problem

1. Open a project in RStudio
1. In the file viewer pane, check the box to select a file and click "Rename"
1. Start typing the free text field that pops up

### Describe the problem in detail

When I try to rename a file in the RStudio files pane, I cannot see the text as I type in the free text field. See screenshot, where you can see the cursor is to the right (I was typing "index" but no text is visible):

<img width="1312" alt="Screen Shot 2019-03-22 at 1 01 48 PM" src="https://user-images.githubusercontent.com/12160301/54850011-24113b00-4ca3-11e9-98bf-b52ffbda50f7.png">

### Describe the behavior you expected

In previous versions I could always see the text as I typed in this field and I use this feature a lot so it is a new-ish issue.

**Comment by jmcphers** [comment] 2019-03-22 20:18
This was previously reported in https://github.com/rstudio/rstudio/issues/2983 but should have been resolved. :-/ I can't repro locally, but I'm not sure what version of MacOS you're on (10.14.13 doesn't exist). What does `sw_vers` return for you in the Terminal?

I'm on:

    ProductName:    Mac OS X
    ProductVersion: 10.14.4
    BuildVersion:   18E220a

Thanks for reporting!

**Comment by kevinushey** [comment] 2019-03-22 20:19
Could you also please copy a screenshot of the <kbd>Help -> About RStudio</kbd> dialog box? See e.g.

![Screen Shot 2019-03-22 at 1 19 48 PM](https://user-images.githubusercontent.com/1976582/54850739-2f656600-4ca5-11e9-9ccc-804e9347384c.png)

**Comment by kevinushey** [comment] 2019-03-22 20:33
It looks like this reproduces specifically if you have a dark MacOS theme active, but a light RStudio editor theme set.

**Comment by ronblum** [comment] 2019-03-22 20:33
Ah! I can reproduce with the dark theme on Mojave (10.14.4 beta). It's fine with the light theme. I believe this is a duplicate of the original, if I'm following it correctly.

**Comment by apreshill** [comment] 2019-03-22 21:08
Hi all,

Thanks for looking into it - sorry for the typo I'm on Mojave 10.14.3 and just installed the preview version of RStudio this morning based on the all staff email. I can confirm that I am using a "dark" theme: 

<img width="780" alt="Screen Shot 2019-03-22 at 2 07 12 PM" src="https://user-images.githubusercontent.com/12160301/54853017-ce8d5c00-4cab-11e9-92de-3ccfccb180d5.png">

If I switch to "light", I can see the text:

<img width="1312" alt="Screen Shot 2019-03-22 at 2 07 48 PM" src="https://user-images.githubusercontent.com/12160301/54853054-e9f86700-4cab-11e9-9da7-5ec49c12d930.png">

**Comment by coatless** [comment] 2019-03-22 21:42
Same issue 🙁 

```
RStudio Edition :  Desktop 
RStudio Version : 1.2.1327
OS Version      :  macOS Mojave 10.14.3
R Version       :  3.5.3 (2019-03-11)
```

If this helps, on start up or creating a new window the dark theme is initially applied and, then, removed.

![rstudio-startup-dark-theme](https://user-images.githubusercontent.com/833642/54854222-41083700-4cc0-11e9-8510-d5f8b799bd6a.gif)

![rstudio-pullout-window-dark-theme-issue](https://user-images.githubusercontent.com/833642/54854553-4dd95a80-4cc1-11e9-981b-99cdb714628e.gif)

Only when launching a new window, c.f. the `git` client,  does the dark theme not get overridden. 

![git-dark-theme-client-window](https://user-images.githubusercontent.com/833642/54854249-51b8ad00-4cc0-11e9-80c7-0abdb2221f34.png)

**Comment by kevinushey** [comment] 2019-04-01 18:12
Will be fixed in the v1.2 patch release with https://github.com/rstudio/rstudio/commit/6fa1ff001ba514825f5588c2ca5a51ded4675f83.

The fix involves backing out all attempts to change the titlebar color, as extra orchestration would be required to make sure this works with light vs. dark macOS themes, and we don't have time to do that safely for v1.2.

**Comment by ronblum** [comment] 2019-05-30 20:54
Verified in 1.2.1522 on MacOS 10.14.6. Checked four combinations (2 x 2) of MacOS theme and RStudio theme.

**Comment by coatless** [comment] 2019-05-31 17:04
@ronblum could this be reopened? I'm still getting the problem on 1.2.1522

**Comment by ronblum** [comment] 2019-05-31 18:34
@coatless OK, will do. Just to confirm: is the background of the input field white or black?
<img width="377" alt="white" src="https://user-images.githubusercontent.com/31009952/58726933-04884400-83b1-11e9-85e6-cfd4ea5c0796.png">
<img width="382" alt="black" src="https://user-images.githubusercontent.com/31009952/58726932-04884400-83b1-11e9-86d7-336a2fc31c9c.png">

@kevinushey We're seeing different results with 1.2.1522. For what it's worth, it works for me (MacOS 10.14.6 beta) and @rich-rstudio (MacOS 10.14), but not for @coatless (MacOS 10.14.3).

**Comment by coatless** [comment] 2019-05-31 18:37
@ronblum sorry. I wasn't on the latest preview build of Version 1.2.1522. This problem is fixed.

**Comment by ronblum** [comment] 2019-05-31 18:41
@coatless Ah—great, and thanks for the update!

**Closed by ronblum** 2019-05-31 18:41 UTC
Labels: bug, macos

**Comment by jcolomb** [comment] 2020-05-20 08:23
I seem to have the same problem, only for the rename field.
macOS 10.14.1 (18B75)
RStudio Version 1.2.1335 (fresh upgrade via brew cask).
(background white)

could making the text in blue (light or dark blue) be a way to get a workaround?
