### ISSUE TITLE
Corrupted inline LaTeX in visual editor

### ISSUE THREAD

**Issue by d-morrison** [rstudio/rstudio#12665] opened 2023-02-03 21:28 UTC
### System details

    RStudio Edition : RStudio Desktop 
    RStudio Version : 2022.12.0 Build 353
    OS Version      :  Windows 11
    R Version       :  4.2.2

### Steps to reproduce the problem

1. Open an RMarkdown editor in RStudio and enter some text with an inline LaTeX chunk; e.g.,

```
---
title: "test"
output: html_document
date: "2023-02-03"
---

i.e., $p(S \mid X)=p(X \mid S)p(S)/p(X)$, using a Markov-Chain Monte Carlo (MCMC) algorithm and assuming a uniform prior
```
2. Switch to Visual Editor mode.

3. Add another inline LaTeX chunk to that line; e.g., type "$x$" after "uniform prior".

The first LaTeX chunk ("$p(S \mid X)=p(X \mid S)p(S)/p(X)$") loses its visual formatting:

![image](https://user-images.githubusercontent.com/2474437/216713996-c79817a1-25c4-4fb6-b2b9-fc61273addd0.png)

On switching back to the "Source Editor" mode, you will find that the initial and final dollar signs have been escaped:

![image](https://user-images.githubusercontent.com/2474437/216714050-1e4ce935-4e1f-40ca-afdf-d45fc7e64356.png)

### Describe the problem in detail

When I add inline LaTeX while in the visual RMarkdown editor, previous inline LaTeX strings delimiters ($) get corrupted to ("\$"). See reprex above.

### Describe the behavior you expected

I expected the existing LaTeX chunks to stay as they were.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-02-07 20:58
@d-morrison Thank you for raising this! I can also reproduce this in RStudio Desktop 2022.07.2+576. We'll review this as we continue development of RStudio and the Visual Editor.

This appears to be because there's a character right after the `$` that closes the inline code, in this case a comma. So if we start with
```$\mid$,```
and then add
```$x$```
the same issue occurs.

**Comment by jjallaire** [comment] 2023-02-09 15:57
This should be fixed here: https://github.com/quarto-dev/quarto/commit/307b0d0d87014f359760db510bd86fe8358973fc

@ronblum The visual editor is now developed in its own repo (where that commit is from). RStudio daily builds should be picking up `main` from there whenever they are run (@timtmok can confirm for sure) so this should land in the next RStudio daily.

**Comment by ronblum** [comment] 2023-02-13 20:37
Verified in RStudio Desktop 2023.03.0-daily+316 on MacOS 13.2. Tested using both the original and later example.

**Closed by ronblum** 2023-02-13 20:37 UTC
Labels: bug, visual markdown
