### ISSUE TITLE
Support RStudio on Fedora 36

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11478] opened 2022-06-22 20:59 UTC
Support RStudio Desktop and RStudio Server on Fedora 36. We currently produce daily builds for it, but they're not fully supported yet (see #11140).

See also #11477 which addresses Red Hat 9, although they're currently the same builds.

**Comment by MariaSemple** [comment] 2023-01-23 17:38
We're not going to create a separate test environment for Fedora, if the tests for RHEL9 pass we will consider Fedora 36 supported.

**Comment by MariaSemple** [comment] 2023-01-23 17:38
Closing as duplicate of #11477

**Closed by MariaSemple** 2023-01-23 17:38 UTC
Labels: enhancement
