### ISSUE TITLE
Autocomplete previews for dataframe columns are unreadable in Dark mode 

### ISSUE THREAD

**Issue by DesiQuintans** [rstudio/rstudio#13097] opened 2023-05-05 20:37 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.05.0 Build 329 Pre-release
    OS Version      :  Windows 10
    R Version       :  4.2.2

### Steps to reproduce the problem

1. Change RStudio's theme to a dark one (for example, the built-in Dracula theme).
2. Type `iris$` into a new R script. 
3. Wait for the autocompletion window to suggest columns in `iris`, and to show the preview of those columns.
4. See that the preview of the column's contents is light grey text on white boxes and unreadable.

![image](https://user-images.githubusercontent.com/3200601/236563781-cbc7ccfb-9828-4758-9d76-9681f5b16707.png)

### Describe the problem in detail

RStudio's dataframe column autocompletion shows previews of what the column contains, but it is unreadable (see image above).

### Describe the behavior you expected

Text should be readable. Text should also be styleable in a custom theme.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-05-08 08:15
@DesiQuintans Thank you for raising this issue! We'll review it as we continue development of RStudio. BTW, Dracula is my favorite dark theme.

@jonvanausdeln Can you try this out? I tried reproducing this on MacOS 13.4, but it works correctly for me.

**Comment by jonvanausdeln** [comment] 2023-05-08 15:49
@ronblum , I tried on both latest Mountain Hydrangea and Cherry Blossom builds.  I was not able to reproduce on Windows 11.  The columns previewed correctly.

**Comment by sharon-wang** [comment] 2023-05-08 16:42
This reminds me of https://github.com/rstudio/rstudio/issues/12881

I think it has something to do with the data type, i.e. autocomplete previews of `int` or `dbl` (and maybe others) seem to have this issue, versus `numeric` or `factor` which might not have this issue.

**Comment by DesiQuintans** [comment] 2023-05-09 03:43
> This reminds me of #12881
> 
> I think it has something to do with the data type, i.e. autocomplete previews of `int` or `dbl` (and maybe others) seem to have this issue, versus `numeric` or `factor` which might not have this issue.

Interesting. Before attaching dplyr:

![image](https://user-images.githubusercontent.com/3200601/236988309-f854dc7c-910f-4c37-b82a-ee5ed288a24d.png)

After attaching dplyr:

![image](https://user-images.githubusercontent.com/3200601/236988385-5e34f555-89b4-4028-829a-dc19c82bd2a6.png)

But the data type doesn't seem to affect it for me:

![image](https://user-images.githubusercontent.com/3200601/236988528-14605c06-f525-40a0-8dee-5fcb2f5120d4.png)

**Comment by romainfrancois** [comment] 2023-05-12 07:52
These are styled with these rules: 

https://github.com/rstudio/rstudio/blob/afdee25b92abb127646fc345f5be6481ea777a0f/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.css#L45

```css
.helpGlimpseText ul li {
   display: inline-block;
   margin: 2px;  
   padding: 2px;
   border: 1px solid #cfd4d8;
   background-color: #ffffff;
   font-family: fixedWidthFont;
   font-size: 10px;
}

.helpGlimpseText ul li i{
   color: #cfd4d8;
}
```

There should probably be additional `.rstudio-themes-dark-menus` rules too

**Comment by samueelsen** [comment] 2023-11-12 18:42
How is this not fixed yet?

**Comment by kevinushey** [comment] 2023-12-08 21:22
We no longer use pillar for formatting of vector outputs in these previews, so the issue should be resolved in the latest daily builds.

**Closed** 2023-12-08 21:23 UTC
Labels: bug, autocompletion
