### ISSUE TITLE
Insert Chunk breaks document formatting in Visual mode but not Source mode

### ISSUE THREAD

**Issue by DarwinAwardWinner** [rstudio/rstudio#15452] opened 2024-11-21 19:15 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.09.1+394 (2024.09.1+394)
    OS Version      : Mac OS 13.7.1 (22H221)
    R Version       : 4.4.2 (2024-10-31)

### Steps to reproduce the problem

1. Create a new Quarto or RMarkdown document
2. Switch to Visual mode.
3. Create a code block with multiple lines of code
4. Place the cursor at the start of one of the middle lines of code.
5. Run Insert Chunk (Command+Option+I)

Example starting code chunk with multiple lines:

    ```{r}
    message("This is some code")
    message("This is some more code")
    message("This is even more code")
    ```

### Describe the behavior you expected

If the above sequence of actions is performed in Source mode instead of Visual mode (step 2), then the result is 2 separate source chunks, one containing all the code above the cursor and one containing all the code on the cursor's line and below. Both chunks are properly formatted. I would expect the exact same result in Visual mode.

Example correct result in Source mode:

    ```{r}
    message("This is some code")
    ```
    
    
    ```{r}
    message("This is some more code")
    message("This is even more code")
    ```

### Describe the problem in detail

When performing the above sequence of actions in Visual mode as described, instead of splitting the existing chunk into 2 smaller chunks, 3 chunks are created, and one of them is improperly formatted. One of the lines of code ends up on the opening line of the 3rd code chunk surrounded by curly braces.

Example incorrect result in Visual mode:

    ```{r}
    message("This is some code")
    
    ```
    
    ```{r}
    
    ```
    
    ```{message("This is some more code")}
    message("This is even more code")
    ```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by olivroy** [comment] 2024-11-22 14:04
This is a duplicate of #11063

**Comment by DarwinAwardWinner** [comment] 2024-11-22 14:11
Yes, looks like the same bug. I guess I didn't figure out the right search terms when I checked for duplicates.

**Comment by gtritchie** [comment] 2024-12-17 22:20
Closing as duplicate of https://github.com/rstudio/rstudio/issues/11063.

**Closed by gtritchie** 2024-12-17 22:20 UTC
Labels: bug, new
