### ISSUE TITLE
History pane doesn't stay minimized after using a reticulated python REPL

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#3084] opened 2018-06-27 13:08 UTC
Using the desktop dailies (current version for this issue 1.2.780), macOS 10.14.

I'm a "console on the right" person and have history pane minimized below the source pane since I never really use it. When processing R code it stays minimized.

When i start a python code file in a source pane tab and start executing lines the history pane _always_ unminimizes even when I re-minimize it.

Further, when going back to an R source pane tab in the same RStudio session, the first execution of a line of code causes a minimized history pane to unminimize, but it stays unminimized on subsequent R line executions.

I'll gladly clarify and/or post a screen cap when I get some time/if needed.

**Comment by ronblum** [comment] 2018-06-27 14:47
@hrbrmstr 
Thanks for reporting this. We'll check it out as we work on future development of RStudio.

Note:
1) Reproduced on MacOS 10.12.6 (Sierra) and confirmed that this doesn't occur with other file types, such as R Markdown and C++.
2) Not an issue on Windows 10.

**Comment by hrbrmstr** [comment] 2018-06-27 14:58
#ty

As an aside, def try to get on 10.13 if you can. Been seeing chatter abt some targeted campaigns for 10.12 systems and Apple will def lose focus on 10.12 (tho technically shld still get security stuff out for it but ya never know) once 10.14 is out later this year.

**Comment by ronblum** [comment] 2018-06-27 15:54
[Sorry—I didn't mean to close this. Reopened.]

Thanks @hrbrmstr. Pulling back the curtain a bit: I test on both, but a large part of the team is using 10.13, so I tend to focus on 10.12 to balance it out. This was a good example: you found the problem on 10.14, I checked it on 10.12 confirming it's not a 10.14 issue, and the developer will probably use 10.13 when researching it. And, of course, we rely on the community—I'm getting ready to include 10.14 in my mix, and in the meantime I'm very thankful for users like you who are ahead and already using it. So thank you!

**Comment by hrbrmstr** [comment] 2018-06-28 12:10
Phew (rly glad it's 10.12 just for testing)! I totally grok the need to take 10.12 in to account (and it's awesome y'all test across so many OS versions).

**Comment by ronblum** [comment] 2020-02-05 22:19
#5984 is a duplicate of this, but I'll close this one and merge the information.

**Closed** 2020-02-05 22:20 UTC
Labels: bug, macos
