### ISSUE TITLE
Prompt to restart R before reinstalling gets stuck

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8710] opened 2021-01-10 18:42 UTC
**Steps to reproduce:**
* Install the `Matrix` package.
* Load the package and create some objects from `Matrix` in the environment.
* Issue command `install.packages("Matrix")`.
* When the prompt asking to restart the R session before reinstalling the package pops-up, answer "Yes".

**Expected behavior:** should restart R and reinstall the package.

**Actual behavior:** restarts R and shows the prompt again. Continuing on clicking "Yes" leads to an infinite loop, without the package getting installed.

**Setup:** RStudio 1.4.1100, R 4.0.3.

**Comment by ronblum** [comment] 2021-01-25 18:24
I believe this is a duplicate of #2656.

**Closed by ronblum** 2021-01-25 18:24 UTC
Labels: bug, console
