### ISSUE TITLE
Incorrectly colored items in additional source panes for dark themes

### ISSUE THREAD

**Issue by salim-b** [rstudio/rstudio#8016] opened 2020-10-09 08:06 UTC
# System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.915
    OS Version      : Ubuntu 20.04 LTS
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Select one of the dark editor themes.

2. Add two or more additional source panes,
   - either by navigating to <kbd>Tools</kbd>→<kbd>Global Options…</kbd>→<kbd>Pane Layout</kbd>, clicking <kbd>Add Column</kbd> at least two times and <kbd>Apply</kbd>ing the changes, or
   - by choosing <kbd>View</kbd>→<kbd>Panes</kbd>→<kbd>Add Source Column</kbd> two or more times.

3. Stretch RStudio's window far enough apart so that the button to toggle the document outline (![Bildschirmfoto von 2020-10-09 09-50-25](https://user-images.githubusercontent.com/20040931/95557366-3e854380-0a04-11eb-847c-55f296bd6e96.png)) becomes visible _in each source pane_.

4. Now you should notice that the mentioned button in the primary as well as the _first_ additional source pane looks fine while the same button is **colored differently** (darker) in the _second_ additional source pane and subsequent ones.

   The button to toggle the newly added _Visual Markdown_ mode shows exactly the same problem.

### Describe the problem in detail

A screenshot might be clearer:

![Bildschirmfoto von 2020-10-09 10-00-05](https://user-images.githubusercontent.com/20040931/95558458-c9b30900-0a05-11eb-9f91-1b77d8dc21d7.png)

(The buttons encircled in green are fine while the ones in red are not.)

### Describe the behavior you expected

The buttons should look the same across all source panes.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment] 2020-10-09 13:54
Thanks @salim-b! I am able to reproduce in desktop mode and am looking into this.

**Comment by melissa-barca** [comment] 2020-10-09 21:20
I spent a fair amount of time looking into this with @adamconroy and determined the issue has something to do with how `rstudio-themes-invert` is cascading between tab panels but couldn't determine the cause. As it only happens in desktop it's possibly Qt related. This would be nice to have for 1.4 but not a must have.

**Comment by jmcphers** [comment] 2020-10-09 21:27
Yes, this is a QtWebEngine bug, and the bug is that sometimes (of course _sometimes_) the CSS inversion `filter` simply doesn't do anything. I hit it a couple of weeks ago, and wound up having to work around it by inverting the images myself. Annoying, but not hard. We could do something similar here:

https://github.com/rstudio/rstudio/pull/7848

**Comment by melissa-barca** [comment] 2020-10-09 21:33
Ah, thank you @jmcphers! I’ll take your approach.

**Comment by kevinushey** [comment] 2020-10-09 22:06
> Yes, this is a QtWebEngine bug, and the bug is that sometimes (of course sometimes) the CSS inversion filter simply doesn't do anything. 

It has been ~3~ 0 days since we last encountered a QtWebEngine bug. 😞 

I filed a somewhat similar bug a while back (https://bugreports.qt.io/browse/QTBUG-70684?jql=text%20~%20%22css%20filter%22), so there's a chance it'll be fixed in Qt 5.15.x.

**Comment by salim-b** [comment] 2020-10-10 11:57
> Yes, this is a QtWebEngine bug, and the bug is that sometimes (of course _sometimes_) the CSS inversion `filter` simply doesn't do anything. I hit it a couple of weeks ago, and wound up having to work around it **by inverting the images myself**. Annoying, but not hard. We could do something similar here:
> 
> #7848

I noticed that the close buttons of the tabs, search field etc. are hardcoded PNG images instead of styled font chars:

![Bildschirmfoto von 2020-10-10 13-48-57](https://user-images.githubusercontent.com/20040931/95654380-1b838e00-0aef-11eb-9759-a3c242a112a9.png)

These buttons are barely visible in dark themes (even worse when you try to create [your own](https://github.com/anthonynorth/rscodeio) blackish/greyish [dark theme](https://github.com/rileytwo/darkstudio)). Is this a known issue?

**Comment by melissa-barca** [comment] 2020-10-12 20:59
Unfortunately, it looks like these buttons are falling victim to the Qt bug as well and are missing the inversion filter we add. I'll include them in my fix for this issue as well.

**Comment by mikebessuille** [comment] 2020-10-13 18:04
Gary investigating moving to QT 5.15.1 so we will keep this in 1.4 for now in case it's magically fixed.

**Comment by melissa-barca** [comment] 2020-10-14 13:48
I tested out Gary's preview build for the qt fix and it does fix this issue as well 🥳
I'm closing out this ticket as the qt work is being tracked here in #8045

**Comment by gtritchie** [comment] 2020-10-14 16:19
Let's leave this open until the Qt update work is merged and it can be tested in an official build.

**Comment by kevinushey** [comment] 2022-03-02 23:08
Appears to be fixed in our latest Electron builds; I think this can be closed.

**Closed by kevinushey** 2022-03-02 23:08 UTC
Labels: bug, qtwebengine, backlog
