### ISSUE TITLE
Alt+- shortcut doesn't work in RMarkdown documents with RStudio 1.3

### ISSUE THREAD

**Issue by mojaveazure** [rstudio/rstudio#7169] opened 2020-06-18 19:35 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.959
    OS Version      :  Server: Ubuntu 16.04.6 LTS; Client: Windows 10 Home 1909 with Firefox 77.0.1
    R Version       : 4.0.1

### Steps to reproduce the problem
1. Open new RMarkdown document
1. In an R code chunk, press `Alt+-` (`Option+-`) to attempt to insert the `<-` assignment operator

### Describe the problem in detail

The latest version of RStudio ignores the `ALT+-` shortcut to insert the `<-` assignment operator in RMarkdown documents

### Describe the behavior you expected

I expected `Alt+-` to insert the `<-` assignment operator

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Note: updated to reflect proper RStudio shortcut of `Alt+-` instead of `Alt+0`; thanks Gary for pointing that out!

**Comment by gtritchie** [comment] 2020-06-18 20:12
The "insert assignment operator" command's default keyboard shortcut is <kbd>Alt+-</kbd>, not <kbd>Alt+0</kbd>. Is it possible you had previously customized this shortcut and that was reset when you upgraded to 1.3?

**Comment by mojaveazure** [comment] 2020-06-18 20:15
Hi Gary,

Sorry, I meant `Alt+-`, not `Alt+0`

`Alt+-` works in the console pane, but not in RMarkdown code chunks. I've just checked and it also does not work in R Scripts either.

**Comment by gtritchie** [comment] 2020-06-18 20:20
Ok, I have repro'd this in Firefox using latest 1.3 preview (1.3.1033), but it works in Chrome. I will try 1.2 with Firefox and see if it was working there.

**Comment by gtritchie** [comment] 2020-06-18 21:24
Yup, worked fine in 1.2 with FireFox on Windows. Marking as a regression in 1.3. Thanks for the report!

**Comment by kevinushey** [comment] 2020-06-18 22:03
Looks like this was previously handled here in v1.2:

https://github.com/rstudio/rstudio/blob/e4a1c219cbf6c10d9aec41461d80171ab3009bef/src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java#L436-L440

But that normalization is no longer happening; it looks like it was lost with a previous commit.

**Comment by gtritchie** [comment] 2020-06-18 23:09
Appears it happened in https://github.com/rstudio/rstudio/pull/3147

**Closed** 2020-06-19 19:52 UTC
Labels: bug, firefox, keyboard shortcuts, regression

**Comment by R-Hannibal** [comment] 2020-06-29 21:52
@mojaveazure, thanks so much for finding and reporting this issue. 

We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by mojaveazure** [comment] 2020-06-30 00:14
Hi Mario,

This issue is fixed under RStudio Server 1.3.1054

Thank you!

**Comment by finalspy** [comment] 2022-02-09 09:17
OK saw that this is linked to : 

- https://github.com/rstudio/rstudio/issues/2486
- https://github.com/rstudio/rstudio/issues/7543
