### ISSUE TITLE
Show all panes repeatedly results in gray empty window which has to be terminated as a system process

### ISSUE THREAD

**Issue by DaveParr** [rstudio/rstudio#7311] opened 2020-07-09 10:16 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.959
    OS Version      : Pop!_OS 20.04 LTS
    R Version       : 3.6.3

### Steps to reproduce the problem

* Open r studio
* Hide some panes - either by the menu system or shortcuts
* View all panes - either by the menu system or shortcuts

### Describe the problem in detail

It looks like this:

![Screenshot from 2020-07-09 13-40-32](https://user-images.githubusercontent.com/8363743/87041322-f890c780-c1e9-11ea-8c46-e97b85512827.png)

I end up with a window that is only background gray. I cannot use any of the panel shortcuts to make the UI reappear. I cannot close the window from the UI either. I have to open Systems Process and Kill it from the Process list.

This problem seems to be intermittant, but I can confirm it happens with and without key board shortcuts being used, with and without pop_os auto-tiling enabled, and when the RStudio window is both maximised and only occupying part of the screen. It's also relatively frequent. Multiple times per hour of use in many cases. I cannot trace to occuring only when a process is ongoing, or when a specific filetype or pane is in focus.

~The one thing I *think* is the main trigger is that it occurs (from memory) _only_ when the window is being returned to "normal' e.g. remove the focus from a subset of the panes to all the panes.~ It just occured when all 4 panes were open, and I dragged the horizontal bar to resize the partition.

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4896035/diagnostics-report.txt)

### Describe the behavior you expected

That when moving focus between panes, I don't crash the application.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment] 2020-07-09 16:00
Duplicate of #6379, try the preview build from https://rstudio.com/products/rstudio/download/preview/

**Closed by gtritchie** 2020-07-09 16:00 UTC
Labels: duplicate

**Comment by DaveParr** [comment] 2020-07-21 12:18
Having done a bit of work after installing the preview, it seems the issue is no longer present. Thanks :)
