### ISSUE TITLE
The compilation of RStudio server on AIX7.2 failed

### ISSUE THREAD

**Issue by bergen288** [rstudio/rstudio#7183] opened 2020-06-19 20:11 UTC
### System details

    RStudio Edition : Server 
    RStudio Version : rstudio-master.zip (downloaded 6/19/2020).
    OS Version      : AIX7.2
    R Version       : R3.6

### Steps to reproduce the problem
I am trying to build RStudio server on AIX7.2. First of all, my cmake version is 3.16.0 and I compiled boost 1.72.0 with the following statement to include all libraries.
```r
configure --prefix=/usr/local

bootstrap.sh --with-toolset=gcc  --with-libraries=all --with-python=`which python3`   --with-python-root=$PYTHON_ROOT  --prefix=/usr/local 
	
sudo ./b2 install
```
In rstudio-master/CMakeLists.txt file, I added the following statements after 14 comment lines.
```r
set(Boost_DEBUG 1)
set(BOOST_ROOT "/usr/local")
SET(Boost_USE_STATIC_LIBS ON)

SET(BOOST_INCLUDEDIR "/usr/local/include")
SET(Boost_INCLUDE_DIR "/usr/local/include")
SET(BOOST_LIBRARYDIR "/usr/local/lib")
SET(CMAKE_THREAD_LIBS_INIT "-lpthread")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread")

FIND_PACKAGE(Boost)
IF (Boost_FOUND)
    INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIR})
    ADD_DEFINITIONS( "-DHAS_BOOST" )
ENDIF()
```
### Describe the problem in detail
My cmake command is 
```r
cd build
cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release > cmake.log 2>&1
```

It has the following errors.  The log file and 2 output files are attached at the bottom.
```r
-- Found LibR: /opt/freeware/lib64/R  
-- Found R: /opt/freeware/lib64/R
CMake Error at src/cpp/session/CMakeLists.txt:23 (message):
  Dictionaries not found (re-run install-dependencies script to install)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/software/rstudio/rstudio-master/src/cpp/PQ_LIB
    linked by target "rstudio-core-tests" in directory /software/rstudio/rstudio-master/src/cpp/core
    linked by target "rstudio-core" in directory /software/rstudio/rstudio-master/src/cpp/core
SOCI_CORE_LIB
    linked by target "rstudio-core-tests" in directory /software/rstudio/rstudio-master/src/cpp/core
    linked by target "rstudio-core" in directory /software/rstudio/rstudio-master/src/cpp/core
SOCI_POSTGRESQL_LIB
    linked by target "rstudio-core-tests" in directory /software/rstudio/rstudio-master/src/cpp/core
    linked by target "rstudio-core" in directory /software/rstudio/rstudio-master/src/cpp/core
SOCI_SQLITE_LIB
    linked by target "rstudio-core-tests" in directory /software/rstudio/rstudio-master/src/cpp/core
    linked by target "rstudio-core" in directory /software/rstudio/rstudio-master/src/cpp/core
UTIL_LIBRARIES
    linked by target "rstudio-core-tests" in directory /software/rstudio/rstudio-master/src/cpp/core
    linked by target "rstudio-core" in directory /software/rstudio/rstudio-master/src/cpp/core
UUID_LIBRARIES
    linked by target "rstudio-core-tests" in directory /software/rstudio/rstudio-master/src/cpp/core
    linked by target "rstudio-core" in directory /software/rstudio/rstudio-master/src/cpp/core

-- Configuring incomplete, errors occurred!
See also "/software/rstudio/rstudio-master/build/CMakeFiles/CMakeOutput.log".
See also "/software/rstudio/rstudio-master/build/CMakeFiles/CMakeError.log".
```
### Describe the behavior you expected
Build RStudio Server on AIX7.2 successfully.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[cmake.log](https://github.com/rstudio/rstudio/files/4806534/cmake.log)
[CMakeCache.txt](https://github.com/rstudio/rstudio/files/4806535/CMakeCache.txt)
[CMakeError.log](https://github.com/rstudio/rstudio/files/4806537/CMakeError.log)

**Comment by gtritchie** [comment] 2020-06-22 17:23
As a first step, you would likely need to review the dependency installation scripts in dependencies/linux and create one for AIX.

Closing this as a duplicate of #4308 as we don't support building on AIX, better discussed in the RStudio community: https://community.rstudio.com

**Closed by gtritchie** 2020-06-22 17:23 UTC
Labels: developer, duplicate, otherdistro
