### ISSUE TITLE
RStudio hangs after opening a folder with many files in the "Files" tab

### ISSUE THREAD

**Issue by michalovadek** [rstudio/rstudio#13426] opened 2023-07-27 17:50 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-07) for windows
    OS Version      : Windows 10
    R Version       : 4.2.3

### Steps to reproduce the problem
In the "Files" tab navigate to a folder with (tens of) thousands of files.

### Describe the problem in detail
RStudio hangs after clicking (opening) a folder with many (tens of thousands of) files in the "Files" tab, as it tries to load the contents of the folder.

### Describe the behavior you expected
It would be preferable if an error message or truncated folder contents were displayed instead of RStudio trying to load all the files above a certain threshold (eg 1000).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2023-07-28 08:28
@michalovadek Thank you for raising the issue! I think this has been reported before, but I can't find an older issue, so we'll use this one. A few questions:
1. If you wait long enough does the list eventually show up? And if so, how long does it take in your case?
2. Do you see any difference in the lag time between 2023.06.1+524 and an earlier release?

**Comment by michalovadek** [comment] 2023-07-28 12:27
1. It does eventually show up. But a related issue is that if you reopen the project, RStudio will try to re-display the files pane as you left it (= another hang)
2. I cannot test this right now but I am fairly certain I have experienced this in the past. I doubt it's related to any recent updates

**Comment by ronblum** [comment] 2023-07-28 12:49
@michalovadek No need to recheck! I just wanted to make sure that this wasn't a new thing.

**Comment by michalovadek** [comment] 2023-07-28 13:37
sorry, I missed the second part of your first question. It took at least 10 minutes for the list to show. Then after clicking out of that folder there was another hang that would not in fact resolve, even after several restarts. I managed to break the cycle of hangs by clicking "Go To Working Directory" moments after a restart before RStudio went unresponsive from trying to reload the Files pane.

**Comment by GDoe5** [comment] 2024-02-06 15:41
This is still an issue. RStudio hangs on every open while loading the "Files" tab indefinitely, after previously navigating to a folder with too many files. It will not respond to opening files via File Explorer or to trying to create a new project. Unable to navigate to a different folder which does not make it hang. Does not respond to pressing close on windows UI or to q().

**Comment by ronblum** [comment] 2024-02-12 18:03
QA Note: Try to reproduce with thousands of files locally, then remote if it doesn't reproduce locally.

**Comment by ronblum** [comment] 2024-02-14 17:22
I tried this with 50,000 files in
- RStudio Desktop 2024.04.0-daily+440 on MacOS 14.3
- RStudio Server 2024.04.0-daily+397.pro21 on RHEL 9 via Chrome on MacOS 14.3

Server results
- The wheel spins for about 10 seconds.
- The wheel then freezes. The IDE is completely unresponsive.
- After another 20-30 seconds, a browser pop up appears about the page being unresponsive.

Desktop results
- The wheel spins for about 20 seconds.
- The wheel freezes and the IDE is completely unresponsive.
- After another minute, the files are displayed and the IDE is responsive.

**Comment by GDoe5** [comment] 2024-02-14 18:39
For me, it usually hangs for over 10 minutes before things will work as expected, e.g. loading files, closing the program, running code - the code will go to the console but not run until the Files pane has loaded. I can still type and navigate tabs.

**Comment by kevinushey** [comment] 2024-02-14 20:01
Thanks -- if I understand correctly, the issue here is not in listing all of the files, but the issue is instead attempting to display all of the files in the Files pane.

Here's a reproducible example:

```
n <- 5000  # adjust as needed
files <- sprintf("%05i.txt", 1:n)
file.create(files)
```

Then, open the Files pane, and refresh it. You should see a pause while the IDE attempts to render the Files pane, and that will increase as you increase the number of files above.

We should either:

1. See if we can use the virtualized data grid implementation for the Files pane display, or
2. Limit the number of files we display in the Files pane to a reasonable number (1000 max?)

**Comment by ronblum** [comment] 2024-06-21 18:39
Verified in RStudio Desktop 2024.07.0-daily+244 on Windows 11 and RStudio Server 2024.07.0-daily+240 on RHEL 8 via Edge on Windows 11. Upped the number to 50,000 files.

**Closed by ronblum** 2024-06-21 18:39 UTC
Labels: bug, files pane
