### ISSUE TITLE
Bug when Rstudio server 2022.02.1+461 in Ubuntu is opened in Safari 15.4 (MacOSX 12.3.1)

### ISSUE THREAD

**Issue by Marc-Girondot** [rstudio/rstudio#10926] opened 2022-04-07 10:01 UTC
### System details

    RStudio Edition : Server
    RStudio Version : 2022.02.1+461
    OS Version      : Ubuntu 20.04
    R Version       : 4.1.3

### Steps to reproduce the problem
When Rstudio server page is opened with safari 15.4 (last version) in MacOSX 12.3.1, the menus when clicked are hidden behind the tabs and only the first line can be seen.

### Describe the problem in detail
When a menu is clicked (from example File as in the image), only the first line is visible.

### Describe the behavior you expected
In previous versions of Safari, all the menu was visible. It is still visible with Chrome. So the problem comes from a bad interaction between last version of Safari and Rstudio server.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
<img width="839" alt="Capture d’écran 2022-04-07 à 11 56 36" src="https://user-images.githubusercontent.com/6521994/162174514-7f719a89-241b-4c23-aa9b-342fbecedd24.png">

**Comment by kevinushey** [comment] 2022-04-07 16:22
Thanks for the bug report -- this is a duplicate of https://github.com/rstudio/rstudio/issues/10821 and we plan to release a patched version of RStudio to work around this Safari bug.

**Closed** 2022-04-07 16:22 UTC
