### ISSUE TITLE
Switching visual mode on/off with third pane column leads to misaligned highlighting of chunks

### ISSUE THREAD

**Issue by cathblatter** [rstudio/rstudio#8088] opened 2020-10-16 12:39 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.869
    OS Version      :  macOS Catalina 10.15.6
    R Version       : 4.0.3 (2020-10-10)

### Steps to reproduce the problem

1. Open RStudio
2. Open new Rmarkdown file
3. Add third source column
4. Switch to visual mode
5. Modify one chunk (e.g. add more lines)
6. Switch back to code-mode

### Describe the problem in detail

The chunk modified in step 5) is not highlighted correctly, instead the highlighting still applies to 
the code lines from before modifying.

### Describe the behavior you expected

Adapted the highlighting of the chunk when third source column is active 

Thanks for all your great work! the option for additional columns is great!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

<img width="935" alt="Screenshot 2020-10-16 at 14 35 55" src="https://user-images.githubusercontent.com/24943957/96258893-0316e600-0fbd-11eb-986e-98cda9e18b3f.png">

**Comment by melissa-barca** [comment] 2020-10-16 14:31
Thanks for reporting this! I am able to reproduce and am adding to 1.4 since it affects new features.

**Comment by jmcphers** [comment] 2020-10-22 20:03
We're getting reports that this is still a problem in the latest dailies (1.4.959).

**Comment by mbojan** [comment] 2020-10-23 14:11
I can confirm this in 1.4.959 with an old-school single column editting of Rmd source:

![obraz](https://user-images.githubusercontent.com/636574/97014318-733be380-154a-11eb-9105-e4b05c8c4bb3.png)

**Comment by kevinushey** [comment] 2020-10-23 19:10
@mbojan: were you also using the new Visual Markdown editor mode, or did you experience this while only using the "regular" RStudio source editor mode?

**Comment by mbojan** [comment] 2020-10-24 00:07
@kevinushey I did not use the visual editor, just regular one.

**Comment by cathblatter** [comment] 2020-10-24 12:54
Version 1.4.970

I can confirm @mbojans issues and tested in dailies with both visual-mode and regular rmarkdown with both single and additional source column. 
However, the behaviour is different to my initial post as now the modified chunk's highlighting is aligned correctly, the misalignment affects all the following chunks. 

<img width="1552" alt="Bildschirmfoto 2020-10-24 um 14 48 43" src="https://user-images.githubusercontent.com/24943957/97082251-a6dd4300-1608-11eb-9625-e3a4aa6aa299.png">

**Comment by melissa-barca** [comment] 2020-10-26 21:13
This should be fixed with the next build cycle.

**Closed by melissa-barca** 2020-10-26 21:13 UTC
Labels: backlog, visual markdown editing, workbench

**Comment by mbojan** [comment] 2020-10-26 23:13
Awesome. Thanks!

**Comment by kfeinauer** [comment] 2020-12-01 16:21
Verified fixed 1.4.1069
