### ISSUE TITLE
R Studio 1.1.383 for Ubuntu 16.04 - Source Editor not working. Can't write/edit/view R Scripts or Datasets

### ISSUE THREAD

**Issue by baldsatan** [rstudio/rstudio#1877] opened 2017-12-21 09:17 UTC
Hi! I've used Ubuntu earlier and am returning after a hiatus (primarily to work on Hadoop). I installed R Studio and everything is working fine except the Source editor where one can create and edit R scripts and view Data. I've attached the screen shots and have also tried installing and uninstalling the software.

I used the following commands in the terminal to install R Studio. I have already installed the latest version of 

```
sudo apt-key adv –keyserver keyserver.ubuntu.com –recv-keys E084DAB9

sudo add-apt-repository 'deb https://ftp.ussg.iu.edu/CRAN/bin/linux/ubuntu xenial/'

sudo apt-get install r-base

sudo apt-get install r-base-dev

sudo apt-get install gdebi-core

get https://download1.rstudio.org/rstudio-1.1.383-amd64.deb

sudo gdebi rstudio-1.1.383-amd64.deb

rm rstudio-1.1.383-amd64.deb
```

Can anybody help me out here?

![1](https://user-images.githubusercontent.com/26858927/34248314-92f93b4e-e65b-11e7-8d2b-a0fc8df32df4.png)
![2](https://user-images.githubusercontent.com/26858927/34248315-934fd5ee-e65b-11e7-9b24-c9d692dc732c.png)
![3](https://user-images.githubusercontent.com/26858927/34248316-93a89a58-e65b-11e7-9cce-3cdeff73405d.png)
![4](https://user-images.githubusercontent.com/26858927/34248317-93da389c-e65b-11e7-9590-831eee9806b4.png)
![5](https://user-images.githubusercontent.com/26858927/34248319-9413a2d0-e65b-11e7-8d44-14a523cd6681.png)

**Comment by kevinushey** [comment] 2017-12-21 19:12
Can you share a diagnostics report? https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report. You may need to sanitize the report of any API keys you have stored as environment variables before posting it here.

You might also try resetting RStudio's state: https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State

**Comment by jmcphers** [comment] 2018-01-02 16:49
@baldsatan We're closing this since we can't reproduce the issue; feel free to reopen if you can help us do so.

**Closed by jmcphers** 2018-01-02 16:49 UTC
Labels: not reproducible
