### ISSUE TITLE
New R Markdown files open without chunk buttons (e.g. Run Current Chunk...)

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rstudio#7067] opened 2020-06-08 21:08 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1008 (Preview download as of 6/08/20)
    OS Version      :  10.14.6
    R Version       :  3.6.3

### Steps to reproduce the problem

Open a new R Markdown file by clicking **File > New File > R Markdown...** Click **Okay** in the wizard.

![rmarkdown-open](https://user-images.githubusercontent.com/85014/84080091-9f930100-a9a9-11ea-8406-d624c65ef4a7.gif)

### Describe the problem in detail

The R Markdown file that opens does not contain chunk buttons in the top left corner, which makes it difficult to run code chunks (or to teach a new user how to use R Markdown). Notice the absence of chunk buttons in the top right corner of the chunks in the document below. 

<img width="842" alt="Screen Shot 2020-06-08 at 4 54 31 PM" src="https://user-images.githubusercontent.com/85014/84080396-2051fd00-a9aa-11ea-8679-847851b8a72a.png">

### Describe the behavior you expected

I expect new R Markdown files to open with buttons available for every chunk _in the preview version of the IDE_, as in this screen shot taken with RStudio Version : 1.3.959 (the stable download as of 6/08/2020). I need access to both these buttons and features available in the preview.

<img width="842" alt="Screen Shot 2020-06-08 at 4 56 43 PM" src="https://user-images.githubusercontent.com/85014/84080591-673ff280-a9aa-11ea-9116-5c0ac0574ab4.png">

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2020-06-08 22:36
Can confirm; I just noticed this myself this morning.

**Comment by jmcphers** [comment] 2020-06-08 23:38
@melissa-barca Could you take a look? `git bisect` identifies this as the commit that introduced the issue: https://github.com/rstudio/rstudio/commit/bd83335362c7518a4eadf2a25b72497fc97ca31a

**Comment by melissa-barca** [comment] 2020-06-09 01:15
I cannot consistently reproduce this, @jmcphers  and @garrettgman did you run the highlightUi call sometime before you noticed the issue?

**Comment by garrettgman** [comment] 2020-06-09 02:09
@melissa-barca I did run `highlightUI` before the first time I noticed the missing buttons, but I then closed RStudio and reinstalled first the daily and then the preview versions of RStudio. For each of those, I reopened the project and immediately went to **File > New File > R Markdown...**  and noticed the same issue (without calling `highlightUI` in those sessions, unless it somehow stuck around in my workspace).

**Comment by melissa-barca** [comment] 2020-06-09 02:18
It does look like once the state exists it persists regardless of the version, when I checkout commits earlier than the one @jmcphers mentioned I still don't see the buttons. I think this is more likely related to the work I did with adding labels to the chunks.

**Comment by garrettgman** [comment] 2020-06-09 13:27
If it helps narrow things down, I've now noticed it happening in existing files when I open them (i.e. so it isn't just new files in the unsaved state).

**Comment by jmcphers** [comment] 2020-06-09 16:24
No, I didn't run `highlightUi`.

**Comment by melissa-barca** [comment] 2020-06-09 20:53
Closed in #7076.

**Comment by R-Hannibal** [comment] 2020-06-15 21:03
Verified Fixed on: Windows Desktop, RStudio 1.3.1023.

New R Markdown files are opening with chunk buttons displayed (and functional), clear difference from testing on an earlier 1.3 patch preview (1.3.1008 as reported by @garrettgman).

**Comment by trestletech** [comment] 2020-06-18 14:28
<img width="1211" alt="Screen Shot 2020-06-18 at 10 15 50 AM" src="https://user-images.githubusercontent.com/1593639/85032836-d0282700-b16f-11ea-8198-14126bd3f856.png">

We are still seeing this issue, unfortunately. It seems to work just fine when you create a new document but if you append text via `rstudioapi::insertText()` the new chunks don't get the appropriate play buttons.

**Comment by R-Hannibal** [comment] 2020-06-18 14:44
Re-opened ticket based on @trestletech's comment, looks like the issue is still occurring in the latest preview when text is appended via `rstudioapi::insertText()`.

**Comment by melissa-barca** [comment] 2020-06-18 16:23
@trestletech can you provide a code sample of how you used `rstudioapi::insertText()` to produce your example? Thanks!

**Comment by trestletech** [comment] 2020-06-18 16:26
`rstudioapi::insertText(rstudioapi::document_position(Inf, 0), "\n```{r}\n#I am a chunk\n```\n", id="E211F992")`

Where `E21...` is the ID obtained from the `getActiveDocumentContext()`.

**Comment by melissa-barca** [comment] 2020-06-18 17:35
I've done some research and it looks like the `Inf` value is confusing the IDE's code. If you pass a number into `rstudiapi::document_position` the buttons appear as expected.

**Comment by trestletech** [comment] 2020-06-18 17:38
Hm, I'm still seeing it if even if I specify a number.
![2020-06-18 12-37-45 2020-06-18 12_38_21](https://user-images.githubusercontent.com/1593639/85053751-8862c900-b18a-11ea-8fca-1fda7403ce2c.gif)

**Comment by melissa-barca** [comment] 2020-06-18 17:56
Hm, ok I'm now only seeing it sporadically as well. Things do consistently work as soon as you type something into the chunk, but still working on a fix. This code gets pretty deep into the IDE.

**Comment by trestletech** [comment] 2020-06-18 20:32
Thanks. I've personally been able to use that workaround but we're having I'm hearing of students getting tripped up when we say "now click the play button" and they don't always have one.

**Closed** 2020-06-23 16:18 UTC
Labels: bug, r markdown

**Comment by R-Hannibal** [comment] 2020-06-29 17:21
The baseline of this fix appears to have been successful (comparing between 1.3.1008 and 1.3.1054, the chunk commands were not appearing in an R Markdown in the old build, they ARE appearing on the latest preview 1.3.1054).

Holding off on adding the verified label until I can test some more edgecase functionality as outlined in @kevinushey 's [QA Notes](https://github.com/rstudio/rstudio/pull/7195#issuecomment-648269023).

**Comment by R-Hannibal** [comment] 2020-06-29 21:45
@kevinushey - I have some more testing to do here, but ran into the following issue while verifying (GIF below).

Not sure if this is a new issue or related to this ticket/necessitates a re-open. Let me know if you have a preference (the issue only appears to be occurring on Windows for me, couldn't repro on Mac desktop):

![ChunkSettingsWindowsWeird](https://user-images.githubusercontent.com/62304541/86059121-bd430b80-ba27-11ea-9841-5b17861a8c9b.gif)

**Comment by kevinushey** [comment] 2020-06-29 23:31
Very weird -- I've never seen that before. Are you able to confirm whether this is a new regression (only occurs in v1.4 or v1.3-preview) or does it occur in older builds of RStudio as well?

Also, does it reproduce consistently or only in some cases?

**Comment by R-Hannibal** [comment] 2020-06-30 04:47
OK, dug further and that 'issue' I outlined is some kind of extreme edge-case (I can repro consistently, but only on my Windows desktop under certain setting combinations, not my Windows laptop under those same combinations...it's weird).

Good news is it has nothing to do with your check-in or even Waterlily, apologies for the confusion.

**Comment by R-Hannibal** [comment] 2020-06-30 05:12
Verified Fixed on: RStudio Version - 1.3.1054, R Version - 4.0.2, Windows 10 - Desktop 

As previously noted, documents are now opening with chunk buttons successfully. Tested different methods of chunk creation, mutation, inline outputs of a couple different plots and html widgets, etc. with no issues.

**Comment by kevinushey** [comment] 2020-06-30 22:10
> OK, dug further and that 'issue' I outlined is some kind of extreme edge-case (I can repro consistently, but only on my Windows desktop under certain setting combinations, not my Windows laptop under those same combinations...it's weird).

For what it's worth, we've definitely seen a number of "weird" rendering issues on Windows machines, that are typically tied to a combination of:

1. What graphics card / display device is used by RStudio, and
2. Which graphics card drivers are installed (and are they up-to-date?)

Sometimes, switching to software rendering (as described in https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors) helps to alleviate these issues. It's definitely frustrating though and our main hope is that most of these issues will go away (or continue to go away) as we update Qt / Chromium.
