### ISSUE TITLE
consider using Cairo or ragg by default for graphics?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9286] opened 2021-04-29 17:48 UTC
R 4.1.0 comes with new features in the R graphics engine, as described in https://developer.r-project.org/Blog/public/2020/07/15/new-features-in-the-r-graphics-engine/. Most specifically:

> The new features have only been implemented on a subset of graphics devices so far: cairo_pdf(), cairo_ps(), x11(type="cairo"), png(type="cairo"), jpeg(type="cairo"), tiff(type="cairo"), svg(), and pdf(). Although there is no support yet for quartz() or windows(), almost all of the graphics devices above will work on all major platforms.

On macOS, we use Quartz by default; on Windows, we use the windows device. Since neither of these devices support these new graphics engine features, users would miss out if new R packages tried to make use of those features.

**Comment by mikebessuille** [comment] 2021-05-03 17:41
Duplicate of #8437

**Closed** 2021-05-03 17:41 UTC
Labels: enhancement
