### ISSUE TITLE
Rstudio freeze sometimes

### ISSUE THREAD

**Issue by Thinking2018** [rstudio/rstudio#5302] opened 2019-08-26 21:47 UTC
R 3.6.1
Rstudio 1.2.1335

System: Windows 10

Rstudio freeze and stuck when I open it for a while.

The icons and editor cannot be clicked and edited. I have to force to close it using task manager. And reopen it.

This problem always happen after I installed the version 1.2.1335. It doesn't happen previously.

I am trying to use the preview version of Rstudio, that is 1.2.1572, but still have such problems
Sometimes Rstudio doesn't give me any response. It just seems like freeze. The icon on the screen cannot be clicked, and the editor text widow cannot be clicked and edited

**Comment by Thinking2018** [comment] 2019-08-30 16:59
Dear 


Thank you for your attention. 


Recently, Rstudio seems to work properly. I guess it sometimes not stable. I cannot reproduce the problem currently as it not appear everytime.


I use Windows 10, the version is 10.0.18362 after updating yesterday.


Sincerely


L.




------------------ 原始邮件 ------------------
发件人: "Ron Blum"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 晚上11:04
收件人: "rstudio/rstudio"<rstudio@noreply.github.com>;
抄送: "彩虹后的阳光"<761134060@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [rstudio/rstudio] Rstudio freeze sometimes (#5302)




@Thinking2018 Thank you for raising the issue. I've not been able to reproduce it using the same combination. A few questions:
  
Have you noticed any pattern, such as running particular code, or an action such as waking up from sleep or after closing and opening a laptop?
 
What build version are you using? You can find this in the System Information app, which can be found by typing "System" in the search bar. For example, the machine I'm using is version 10.0.17763.
 
Can you provide a diagnostics report after restarting RStudio? Instructions for this are at https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
 Thanks!

**Comment by jmcphers** [comment] 2019-09-03 19:28
Thanks for the details! Since we can't reproduce and don't have further leads we will close this; feel free to open another issue if you find a set of steps that will cause the freeze again.

**Closed by jmcphers** 2019-09-03 19:28 UTC
Labels: repro needed
