### ISSUE TITLE
EPIC: Data Viewer

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#9025] opened 2021-02-25 16:26 UTC
```[tasklist]
### Tasks
- [ ] https://github.com/rstudio/rstudio/issues/12834
```

**Comment by rstudio-codetree** [comment] 2021-02-25 16:27
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [data viewer should gain keyboard focus when activated #2451](https://github.com/rstudio/rstudio/issues/2451)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/11796094) | 1.6-1.7 (later 2021) | gtritchie | backlog | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by sharon-wang** [comment] 2023-10-11 19:44
Another data viewer item: https://github.com/rstudio/rstudio/issues/12834

**Comment by sharon-wang** [comment] 2023-12-19 21:06
Closing this since it's a duplicate of https://github.com/rstudio/rstudio/issues/7600

**Closed by sharon-wang** 2023-12-19 21:06 UTC
Labels: data viewer, Epic
