### ISSUE TITLE
Blank screen on startup with Fedora 38

### ISSUE THREAD

**Issue by bshor** [rstudio/rstudio#13766] opened 2023-10-06 21:25 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0+463 (from the Fedora repos)
    OS Version      : Fedora 38 (Kernel 6.5.6)
    R Version       : 4.3.1

### Steps to reproduce the problem

I have the latest version of Rstudio installed from the [Fedora repos](https://packages.fedoraproject.org/pkgs/rstudio/rstudio-desktop/).

Starting from the GUI or terminal gives me the same issue.

Rstudio-server works without a problem. R on the command line works also.

**Note** I have updated this comment after Fedora repos updated Rstudio to 2023.09 from 2023.06. I get the exact same bug though: no display at all beyond the menu bar (and I have to kill the session from the command line).

### Describe the problem in detail

I see a blank screen on startup. Only the menubar is visible, but no options are selectable. No panes come up. Using the terminal has infinite lines of text output but no R window comes up.

I tried --no-sandbox but there's no change.

### Describe the behavior you expected

Application starts up and shows expected panes.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Diagnostic report is here: 
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/12871106/diagnostics-report.txt)

**Comment by bshor** [comment] 2023-10-11 16:07
Thanks for writing! First, the version in the repo (now) matches the version on the download page, so it's not going to be a matter of a newer version. A few days ago there was a mismatch, since the 09 version wasn't yet up, but now it is. And, as I mentioned, both 06 and 09 give the same problem.

But yes, the manual downloader works! (however, rstudio-server is not automatically installed, so I'll have to install it).

**Comment by Enchufa2** [comment] 2023-10-13 12:21
This issue happens with our (Fedora's) build. I cannot reproduce the issue in my machines, but it has something to do with the rendering (`GpuChannel: Failed to create SharedImageStub`). @bshor Can you copy the errors that you showed me here?

@ronblum I've recommended following [this troubleshooting guide](https://support.posit.co/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors). Any further advice would be welcome, because if the main window does not render, @bshor cannot reach the "OS Integration" options in the global options.

**Comment by bshor** [comment] 2023-10-13 14:50
Thank you @Enchufa2. The infinitely repeating error I get when I run the Fedora version of rstudio from the terminal is as follows:

```
[286469:286561:1013/094947.619309:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[286469:286561:1013/094947.619311:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[286469:286561:1013/094947.619380:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[286469:286561:1013/094947.619382:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
```

**Comment by Enchufa2** [comment] 2023-10-13 15:41
Can you please share your current settings at Tools > Global Options > General > Advanced > OS Integration?

**Comment by bshor** [comment] 2023-10-13 16:55
They are all standard.

![image](https://github.com/rstudio/rstudio/assets/468070/81c6a3b9-1c69-4be1-be2f-18d37f2e24ba)

BTW I do see the following error message related to Wayland in the terminal, but they don't seem to interfere with the operation of Rstudio. 

`qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
`

**Comment by Enchufa2** [comment] 2023-10-13 18:54
And if you switch the rendering engine to "auto", you get the blank screen, right? That's odd. You could try by setting `QT_QPA_PLATFORM=xcb`.

I'm using Wayland too, and I see that warning, but I have no issues.

**Comment by bshor** [comment] 2023-10-13 20:09
How do I do that setting? In the terminal?

**Comment by Enchufa2** [comment] 2023-10-13 20:30
In the terminal,

```bash
$ QT_QPA_PLATFORM=xcb rstudio
```

or 

```bash
$ export QT_QPA_PLATFORM=xcb
$ rstudio
```

**Comment by bshor** [comment] 2023-10-16 14:17
Unfortunately, that doesn't work. Still the blank screen if I leave rendering on "auto". I had to go back to software.

**Comment by Enchufa2** [comment] 2023-10-16 14:56
It must be some issue with QtWebEngine and your particular GPU then. :(

**Comment by bshor** [comment] 2023-10-16 16:28
Thank you for your help! I have an Nvidia 4070 card. Not too obscure :)

**Comment by bshor** [comment] 2023-10-30 14:36
I'm getting the same bug in X11 as well. After working for a while with @Enchufa2 help, back to blank screen using the repository version of Rstudio. And this is true across three machines running Fedora 38: desktop with 4070, desktop with 1050, AMD laptop with IGP.

**Comment by raimundojimenez** [comment] 2023-11-19 18:09
For the record, I suffer the exact same error, but for me it is not even working the manually downloaded version.

Using Fedora 38 with a NVIDIA Corporation GA106 [GeForce RTX 3060] graphic card...

`nov 19 19:02:59 f38 org.gnome.Software.desktop[74707]: [74707:74797:1119/190259.861246:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
nov 19 19:02:59 f38 org.gnome.Software.desktop[74707]: [74707:74797:1119/190259.861252:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
nov 19 19:02:59 f38 org.gnome.Software.desktop[74707]: [74707:74797:1119/190259.861261:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
nov 19 19:02:59 f38 org.gnome.Software.desktop[74707]: [74707:74797:1119/190259.862283:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
`

**Comment by bshor** [comment] 2023-11-22 23:24
Well, for me on Fedora 38 the newest packaged Rstudio is back to working -- both on a laptop with AMD graphics and a desktop with a 4070. Go figure.

**Comment by bshor** [comment] 2024-01-22 23:44
Fedora 39 still working on both AMD integrated graphics-laptop and discrete graphics-desktop.

**Comment by kevinushey** [comment] 2024-01-23 17:41
Glad to hear things are working on your end -- I'll close this for now but feel free to re-open if you still run into trouble.

**Closed by kevinushey** 2024-01-23 17:41 UTC
Labels: bug, startup

**Comment by carbonga** [comment] 2024-03-08 07:06
I have the same issue with Fedora 39, Wayland, Nvidia (Geforce 3070, proprietary driver), and RStudio 2023.12.1.

**Comment by bshor** [comment] 2024-03-08 14:49
Still running fine here ... Nobara 39, X11 though, Nvidia prop drivers + 4070, 2023.12.1

**Comment by carbonga** [comment] 2024-03-08 15:07
> Still running fine here ... Nobara 39, X11 though, Nvidia prop drivers + 4070, 2023.12.1

Indeed! Switching to X11 fixes the problem. If you take Wayland out of the equation, it works flawlessly. Would be nice to also work with the more modern framework, but not critical to me.

**Comment by bshor** [comment] 2024-03-26 04:09
Wayland works for me on Bazzite, an image-based (immutable) KDE version of Fedora 39 based on Kinoite. Installing was a little convoluted (dnf within a Fedora containter, then export with BoxBuddy) but everything works perfectly now.
