### ISSUE TITLE
RStudio IDE Layout Shortcuts Don't Work After I Click on Viewer

### ISSUE THREAD

**Issue by AdamSadowski** [rstudio/rstudio#5754] opened 2019-11-18 20:33 UTC
Hi,

I noticed that Cntrl-1, 2 etc. and Cntrl-Shift-1, 2, etc do not work after I click on the Viewer pane. I have to click outside of it to be able to use these shortcuts. I noticed this while using data tables specifically.

A minor inconvenience but shortcuts should work regardless of what pane I clicked on (the problem does not occur in the Packages pane e.g.).

Windows 10 and R version 3.6.1. RStudio version 1.2.5001.

**Comment by dfalty** [comment] 2019-11-21 14:37
Hi @AdamSadowski, I can't reproduce this on version 1.2.5019-6 on Mac. Can you please add the bug template to add the platform and RStudio version.

**Comment by AdamSadowski** [comment] 2019-11-21 15:20
It is Windows 10 and R version 3.6.1. RStudio version 1.2.5001.

I don't know the bug template you are referring to. Am new here. Thanks.

**Comment by ronblum** [comment] 2019-12-16 21:27
@AdamSadowski I believe this is a duplicate of #4342, so I am closing it here. 

By the way, the template @dfalty is referring is the one that shows up when clicking on "New Issue" , which takes you to https://github.com/rstudio/rstudio/issues/new/choose , and then clicking on the "Get Started" button next to "Bug Report". I'm guessing that you're using RStudio Desktop?

**Closed by ronblum** 2019-12-16 21:27 UTC
Labels: repro needed
