### ISSUE TITLE
Crtl+tab to open most recent Source tabs, like Firefox

### ISSUE THREAD

**Issue by SimonDedman** [rstudio/rstudio#7576] opened 2020-08-13 05:56 UTC
#7530 # System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1073
    OS Version      : xubuntu 20.04
    R Version       : 4.0.2

### Feature Request
Firefox [has a lovely feature](https://support.mozilla.org/en-US/kb/tab-preferences-and-settings) whereby ctrl+tab scrolls through tabs in recent order, rather than in left-to-right order. This allows quickpressing ctrl+tab once to switch back & forth between source tabs. Would it be possible to include this as an option in future releases? Thanks!

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jarauh** [comment] 2020-08-13 07:19
I believe that RStudio at one time had this behaviour (which, personaly, I hate).  I understand that this behaviour is nice if one only works with two tabs, but as soon as one works with more than two files it gets confusing.  I prefer to have the left-to-right order.  For two (neighbouring) tabs, one can still switch using ctrl+tab and ctrl+shift+tab.

That being said: Having an option would make a lot of sense, since I guess there are strong preferences for both kinds of behavious.

**Comment by smingerson** [comment] 2020-08-13 12:30
Not quite what you are looking for, but "Source Navigate Forward/Backward" are bound to Ctrl+F10/F9, respectively. They go forward/backward in recent order.

**Comment by SimonDedman** [comment] 2020-08-13 16:42
@jarauh I'd definitely be advocating for the option rather than a forced switch for everybody. In terms of working style, personally, even when working with multiple tabs I find I tend to be switching between one primary and one secondary, much more often than I'm switching equally around 3+, or cycling in order, especially given how datasheets spawn to the right of the currently open tab, breaking up the order.

@smingerson This sounds promising & my bindings are set that way but do nothing when pressed. In lieu of filing a bug request on this yet, please can someone check whether this works on a system other than (x)ubuntu 20.04? (and confirm what it does) My F keys are recognised by the system FWIW. Thanks!

**Comment by ronblum** [comment] 2020-08-13 18:35
@SimonDedman Thanks you for the suggestion! While we review it, if the keyboard shortcuts for navigating between source panes doesn't work, would you mind filing a bug report for it? 

And thank you all for the suggestions and feedback!

**Comment by SimonDedman** [comment] 2020-08-13 20:01
@ronblum yep can do, was just hoping someone could have a quick test to see if this feature is working on other systems, and what the expected behaviour is.

**Comment by smingerson** [comment] 2020-08-13 20:05
@SimonDedman I tested this morning before posting on windows 10 with the 1.4 daily from Monday and it worked as expected. I can test with 1.3 when I am back at a computer in a few days.

**Comment by SimonDedman** [comment] 2020-08-13 20:11
Cheers @smingerson ; and just to confirm, the behaviour is as I've described in the thread title / feature request - single tap of ctrl+F9 jumps from your current source tab to the last one you had in focus, regardless of tab order? If so this is a linux bug report (ctrl+f keys not recognised or that feature not working) rather than a feature request. Cheers!

**Comment by smingerson** [comment] 2020-08-13 20:18
Correct

**Comment by ronblum** [comment] 2020-08-13 21:09
@SimonDedman Ah, I'm sorry I misunderstood the original request. I thought you were specifically looking to switching back and forth between two tabs, but back and forth through the focus history.

I just checked a few Desktop and Server environments. It worked in most places, including Ubuntu 18 and Ubuntu 20. It succeeds on Ubuntu 20.04 Gnome, but fails on Plasma. Which desktop environment are you using, for comparison?

In any case, I'll switch this over to a bug.

**Comment by pat-s** [comment] 2020-08-27 14:32
Duplicate of #5804?

**Comment by SimonDedman** [comment] 2020-08-27 16:54
Sorry for the delay Ron, all, completely slipped through my hands. I'm on Xubuntu 20.04 so the XFCE DE. Let me know if there are any pertinent details of my system that would be informative & I'll dig em up.

Re ths issue, I'm not sure we're still understanding each other, but maybe we are. I'm talking about source pane script tabs, whereby the shortcut action would select/focus/bring onto the screen, the last source pane script tab that you were using. I'm not 100% sure what the difference would be between focus history in this sense, and tabs, but I can well imagine there is a technical difference and I'm just revealing my ignorance of RStudio element terms! I mean these fellas:

![image](https://user-images.githubusercontent.com/4599748/91471678-3fdf2000-e84b-11ea-8d0f-82ed35d8df1a.png)

@pat-s It is indeed. I'm surprised my searching didn't find this existing bug. But maybe a good thing, unusually, since it seems that thread petered out without the resolution you originally opened it for.

**Comment by ronblum** [comment] 2020-08-28 15:51
@SimonDedman Funny—I believe  my original understanding was correct, and then I got i wrong. :)  So I'm hopping on board the  "duplicate of #5804" bandwagon.

But—do you have the extension installed, which @pat-s is using? I don't have the extension on Chrome, so <kbd>Ctrl+Tab</kbd> and <kbd>Ctrl+Shift+Tab</kbd> switch between tabs round-robin.

**Closed by ronblum** 2020-08-28 15:51 UTC
Labels: bug, desktop integration, keyboard shortcuts, linux, source editor

**Comment by pat-s** [comment] 2020-08-28 16:10
I am not sure if this is meanwhile the default in FF (I don't think so otherwise the addon would not exist).

For reference, here is a link to the extension I am using. Maybe it makes things more clear: https://addons.mozilla.org/en-US/firefox/addon/most-recent-tab/.

**Comment by SimonDedman** [comment] 2020-08-28 17:52
Hi both,

In firefox you don't need an addon as they've boiled the option into the [settings](https://support.mozilla.org/en-US/kb/tab-preferences-and-settings) (same link as in first post, I've just realised).

**Comment by ronblum** [comment] 2020-08-28 18:10
@SimonDedman and @pat-s Thanks! I wasn't aware of the Firefox setting, and from the "About this extension" at the link above, It looks like the extension adds the ability to customize the keyboard shortcut. Firefox's setting is limited to controlling the behavior of <kbd>Ctrl-Tab</kbd>. In any case, thank you both!
