### ISSUE TITLE
Square and resized icon for macOS Big Sur

### ISSUE THREAD

**Issue by jackobailey** [rstudio/rstudio#8395] opened 2020-11-16 10:36 UTC
Most icons on macOS Big Sur use a square shape similar to those found on iOS and iPadOS. For the sake of consistency, it would be great if the RStudio team would also consider updating the app icon in future Mac builds to use a square shape too.

**Comment by ronblum** [comment] 2020-11-16 19:53
@jackobailey Thank you for the suggestion! Which icons do you mean though, as examples?

**Comment by jmcphers** [comment] 2020-11-17 00:35
I'm guessing this is in reference to the Dock icons. Most built-in macOS apps now use a Dock icon in the shape of a square with very round corners.

![image](https://user-images.githubusercontent.com/470418/99324706-b297e000-2829-11eb-8e21-bb1587cd1bce.png)

However on my own system I don't see any third-party apps which do this yet.

**Comment by jackobailey** [comment] 2020-11-17 09:06
Yes, the dock items. If you take a look at the App Store you'll see quite a few that now do. Two examples from my own dock include Twitter and iAWriter.

**Comment by danieltomasz** [comment] 2020-11-17 10:58
From apple page
```
In macOS 11, the design language for app icons promotes consistency with all platforms while retaining the lifelike rendering style typical of macOS icons. App icons combine a rounded-rectangle shape, a front-facing perspective, and a consistent drop shadow to provide a unified visual experience.
```

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/mail-photos-preferences-big-sur_2x.png)

```
Although the design language strongly encourages visual consistency, it doesn’t preclude judicious expressiveness. For example, the Preview, Xcode, and TextEdit icons continue to combine depictions of the physical objects that best convey the app’s core purpose, while incorporating the new shape, perspective, and shadow.
```

![](https://developer.apple.com/design/human-interface-guidelines/macos/images/preview-xcode-text-edit-big-sur_2x.png)


https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/

In case of Rstudio, Rstudio has rounded icon on all  platform, to retain consistence one solution is to rescale the icon and put white space  around it like in Apple own safari Browse
![image](https://user-images.githubusercontent.com/7980381/99381733-c3992d80-28cb-11eb-84c2-43a673c2873b.png)

In this moment most urgent would be to scale Rstudio icon 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/7980381/99381970-183ca880-28cc-11eb-967c-27b9be82e3ac.png">

**Comment by danieltomasz** [comment] 2020-11-17 10:59
In this moment most urgent would be to scale Rstudio icon 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/7980381/99382099-4b7f3780-28cc-11eb-8ac5-b351a60fc916.png">

The icon is too big in relation to other icons

**Comment by ronblum** [comment] 2020-11-17 18:07
Thank you both! I updated the subject line to also include resizing the icon.

**Comment by jackobailey** [comment] 2020-11-17 20:22
FWIW, I made my own version for the iPhone link I use to go to my RStudio server
![Uploading IMG_3E884A2A1DD6-1.jpeg…]()

**Comment by danieltomasz** [comment] 2020-11-17 21:07
> FWIW, I made my own version for the iPhone link I use to go to my RStudio server

I am unable to see the photo 
There are many attempts to bring user made icons, here you could find a simple attempt (smaller Rstudio logo in a squircle)
https://macosicons.com

**Comment by jackobailey** [comment] 2020-11-18 10:15
Apologies, I mustn't have given my browser time to upload it. Here it is.
![IMG_4739D248B6CD-1](https://user-images.githubusercontent.com/37049065/99517189-fd7b3a00-2986-11eb-986c-32a86e41951d.jpeg)

**Comment by danieltomasz** [comment] 2021-01-12 13:40
Any progress? Or dates when it could be implemented ? 

In this moment, sufficient (at least for me) would  be only resizing the shipped icon (without major design decision and changes) so the icon would fit to rest of native and non-native apps in the dock)
![image](https://user-images.githubusercontent.com/7980381/104321311-bec7b300-54e3-11eb-81c4-f40e5a6106c3.png)

**Comment by 9mm** [comment] 2021-01-12 19:01
I'm also wondering about this, it looks super bad. Funny the last reply was 5 hours ago when I just thought to ask this now 😆

**Comment by 9mm** [comment] 2021-01-12 19:02
If I make the version myself (identical logo, just the proper size), would it actually get merged? @ronblum

**Comment by 9mm** [comment] 2021-01-12 20:03
Ok I went ahead and made an icon.

In this zip:

- the ICNS file
- the original PSD file downloaded from apple design page (note that when you save this document it auto generates png assets in a sibling folder to the PSD)
- the 1024x1024 png I used to generate the ICNS file using the commands below

[rstudio-icon.zip](https://github.com/rstudio/rstudio/files/5804475/rstudio-icon.zip)

If you want to use this now w/o waiting for them to add it to the app (or they reject my icon and you want to use it), hit `command+i` on the R Studio icon. Drag the .icns file into the preview icon, and it will update.

Here's what it looks like:

![image](https://user-images.githubusercontent.com/1386207/104366380-24a94000-54ce-11eb-9018-30b3850ce690.png)

**Comment by 9mm** [comment] 2021-01-12 20:11
Also @jmcphers

**Comment by 9mm** [comment] 2021-02-01 23:30
@jmcphers @ronblum do you think you guys will add the icon I made (see last post)? I just installed R studio on my new mac and the current OSX icon looks so bad. Square icons are common place now with Big Sur having been out for quite some time now, R Studio is literally my only icon that's using old design standards. 

I already did all the work above though, you should be able to just drop it in.

**Comment by danieltomasz** [comment] 2021-02-01 23:46
I didnt have occasion to write it, but @9mm thanks for the icon! I am using it!
About Rstudio, I don't know if they use it, because they are also a corporate they may want to have a consistency between other platforms too, let's hope they will answer soon

**Comment by 9mm** [comment] 2021-02-01 23:49
Yes I figured, that's why I made it as plain as possible (I didnt change the design at all). I used same R logo vector, and their same branding colors with a very slight 1% fade (which many icons do).

Now it looks the part!

![image](https://user-images.githubusercontent.com/1386207/106532426-061edf00-64a5-11eb-9585-a878a2c1819f.png)

**Comment by jmcphers** [comment] 2021-02-02 17:23
> do you think you guys will add the icon I made (see last post)?

It's very nice, but not right now; the existing icon is a trademark so we need to be careful when modifying or replacing it.

**Comment by 9mm** [comment] 2021-02-02 18:41
Ok, I understand. FWIW i used the vector provided here: https://rstudio.com/about/logos/

And I used the SVG version.

But I totally understand. Keep up the great work!

**Comment by Youguang** [comment] 2021-04-01 09:46
I used [FIgma online tool](https://www.figma.com) + [icon template](https://www.figma.com/community/file/857303226040719059) + [icns/ico Generator](https://www.figma.com/community/plugin/742318143106037364/icns%2Fico-Generator) +  [svg file mentioned by @9mm](https://www.rstudio.com/about/logos/) created a self-using icon, and [shared here](https://github.com/rstudio/rstudio/files/6242610/Rstudio_icn.zip) if you like it.

<img width="263" alt="Screen Shot 2021-04-01 at 17 39 56" src="https://user-images.githubusercontent.com/7878120/113275395-55e91d80-9311-11eb-8d60-ede24f8cc2b9.png">

[Rstudio_icn.zip](https://github.com/rstudio/rstudio/files/6242610/Rstudio_icn.zip)

**Comment by pantajoe** [comment] 2021-06-03 14:40
@9mm Nice icon, you created there! Maybe you might want to upload the icon here? -> https://macosicons.com/.
 I'm sure others will appreciate this icon too. 😄

**Comment by 9mm** [comment] 2021-06-03 16:45
@pantajoe I just signed up and it merged my account with someone with an existing username............ seems very secure.

**Comment by pantajoe** [comment] 2021-06-03 20:18
@9mm Well, that's odd 😅 Maybe you can submit an issue to the repository https://github.com/elrumo/macOS_Big_Sur_icons_replacements . The site seems to still be in development regarding user profiles :D

**Comment by amirmasoudabdol** [comment] 2021-06-09 08:36
I didn't know that there is a long/active/open issue about this! But, I was so annoyed that I designed a set of icons for myself. You can find them [here](https://github.com/amirmasoudabdol/rstudio-icons). If anyone from RStudio team is interested, I am happy to work with them, or share the design file to make this a reality! 😄 

![](https://user-images.githubusercontent.com/1290841/121321428-610e8a00-c90e-11eb-8412-7131d4980659.png)

**Comment by benwhalley** [comment] 2021-11-16 11:18
Not sure if this is too late, but can I make a suggestion which might be easy to implement while looking at the icons?

I can't capture a screen grab to show, but on a Mac when switching between multiple sessions open (i.e. instances of RStudio) it's really hard to see which is which.

On my screen (MBP16) the text of the project name is super small, and all the icons are the same, so it's difficult to work out which project to switch to using Command-Tab.

If the text were larger or there were some other consistent way of discriminating between open sessions that would be really helpful.

Even better would be for separate sessions to be individual OS X Windows, rather than multiple instances of the application (this would be more in keeping with standard OSX UI guidelines I think).

Anyway - thanks for Rstudio - it's a great piece of software!

**Comment by mikebessuille** [comment] 2021-12-02 17:35
We need to consider trademark issues around the graphic.  Graham, can you please ask Greg Swinehart to create a mac graphic for us that meets the new mac standard?

**Comment by amirmasoudabdol** [comment] 2021-12-02 20:01
@mikebessuille, my drawings are under MIT license and I don't mind it being used by Rstudio team if you are wondering! 🙂

**Comment by mikebessuille** [comment] 2021-12-02 20:12
@amirmasoudabdol, much appreciated!  However, the problem isn't with using graphics created by the community, which we'd gladly accept. The problem (as I, as an engineer, understand it) is that our trademark includes the circle, not just the stylized R, so we are limited in how much we can modify that graphic.  We may have to have a rounded-square outer shape but still use a circle-R inner part.  It's up to RStudio legal and our graphics designer to figure out what we're allowed to do.

**Comment by 9mm** [comment] 2021-12-02 20:14
> @amirmasoudabdol, much appreciated! However, the problem isn't with using graphics created by the community, which we'd gladly accept. The problem (as I, as an engineer, understand it) is that our trademark includes the circle, not just the stylized R, so we are limited in how much we can modify that graphic. We may have to have a rounded-square outer shape but still use a circle-R inner part. It's up to RStudio legal and our graphics designer to figure out what we're allowed to do.

Yes, specifically the "blue ball" point below it seems:

```
The following guidelines must be followed for all use of the logo:

Use the positive version on light or white backgrounds. The full-color reverse logo may be used on dark color backgrounds, as well as dark areas within photographs.
­The logo is accompanied by the registered trademark symbol (®).
­­The Blue Ball may not be separated from the logotype.
­­A one color logo is only acceptable when media reproduction is limited. In these cases, the logo may be reversed to white on a background that provides suitable contrast. A dark logo is allowed when media reproduction is dark only.
To properly stage the logo, a minimum clearance between the logo and other elements must be maintained. The cap height of the R in the logo indicates the measurement of minimum clearance between the logo and other elements on all sides of the Logo.
The width of the logo must always be at least 70 pixels for on-screen or 1” (25mm) for print.
The logo may not be used in any manner that might imply that any non-RStudio materials, including but not limited to goods, services, websites, or publications are sponsored, endorsed, licensed by, or affiliated with RStudio.
The logo may not be displayed as a primary or prominent feature on any non-RStudio materials. Companies using the logo pursuant to these guidelines must also display in the primary and more prominent position, their own logo(s), business name, product names, or other branding.
The logo may not be imitated or used as a design feature in any manner.
The logo may not be used in a manner that would disparage RStudio or its products or services.
The attribution clause “RStudio is a trademark of RStudio, PBC” must accompany use of the logo.
Neither the logo nor the RStudio name may be used in any other company name, product name, service name, domain name, website title, publication title, or the like.
Non-RStudio materials should not mimic any RStudio advertising, product packaging, or website design.
The logo must be used as provided by RStudio with no changes, including but not limited to changes in the color, proportion, or design, or removal of any words or artwork. The logo may not be animated, morphed, or otherwise distorted in perspective or appearance.
The logo must appear only in a horizontal position.
The logo must stand alone and may not be combined with any other object, including but not limited to other logos, words, graphics, photos, slogans, numbers, design features, or symbols. The logo must never be used to represent the word “RStudio” in text, including in a headline, product-name logotype, or body copy.
The logo must not be incorporated or used in any manner as part of, or in close proximity to another company’s name, domain name, product or service name, logo, trade dress, design, slogan, or other trademarks. The logo must never appear with any other symbol or icon; contained within a box, circle, or other shape; or combined with any other name, logo, or icon to create a co-branded logo.
Words don’t just hold meaning; they communicate by their very form. We primarily use the Source Sans Pro font family: elegant and direct, stylish but not exclusive.
```

**Comment by danieltomasz** [comment] 2021-12-03 11:44
If there are trademark problem, it would be possible to  just resize R logo and leave everuything else as it is (puting it into white squere or even leaving only circle)?
Pre Big Sur logo feels out of scale in the comparison to the rest of new icons, slightly resizing might be enough to feel it as more native

**Comment by gregswinehart** [comment] 2021-12-16 19:47
@danieltomasz, I think that's spot on. I'll read the documentation for the icons and huddle with Roger Oberg, aka Captain Trademark, to get this figured out! Is there a date it needs to be done to ship with something?

**Comment by mikebessuille** [comment] 2021-12-16 22:10
@gregswinehart thanks!  We'll take the new icon whenever you have it.   Our next release is in Feb, feature complete by mid-January - but I would not say this is urgent for that.

**Comment by danieltomasz** [comment] 2021-12-19 20:25
> If this is a trademark problem, it would be possible to just resize R logo and leave everuything else as it is (puting it into white squere or even leaving only circle)?
> Pre Big Sur logo feels out of scale in the comparison to the rest of new icons, slightly resizing might be enough to feel it as more native

For example Spotify retained its circle, but it was resized, so it  fits much  better with other apps (for comparison Safari and Signal Icon)
![image](https://user-images.githubusercontent.com/7980381/146689688-d76e8b70-d060-415d-8fdf-997dfa0242d3.png)

**Comment by mikebessuille** [comment] 2021-12-20 14:24
@GCRev would you be able to resize the icon for now, before we get a new icon from Greg?

**Comment by GCRev** [comment] 2022-01-31 22:01
I'm un-assigning myself from this for now. As far as I know, Greg is handling this and shopping it around internally. There are some copyright minutia to be wary of here.

**Comment by mikebessuille** [comment] 2022-03-21 18:49
@jgutman would you mind following up with Greg Swinehart to see if there is anything underway?  I don't believe there is, at least not recently, and I believe Greg has switched roles but at least he can point you to whomever should own the new graphic now.

**Comment by gregswinehart** [comment] 2022-03-21 19:17
Hi @mikebessuille and @jgutman!  I sent this over to @AndrewMcClain in January, maybe it got lost in the shuffle? I followed Apple's specs for this, but in retrospect I should've packaged it up with an SVG, JPG, EPS, etc... I can do that if needed (I'm back from vacation on Thursday.)

I hope you all are well!  Let me know if I can help in any way-

Gre
![rstudio-icon-for-apple](https://user-images.githubusercontent.com/5993637/159347736-7e2e02d6-8d14-4b66-9ec0-659b090f2af2.png)
g

**Comment by jgutman** [comment] 2022-03-22 20:21
I think just the 1024 x 1024 png you provided is fine -- however I think we will need this on a transparent background.

**Comment by gtritchie** [comment] 2022-03-28 19:36
Confirmed with latest daily build.

**Closed by gtritchie** 2022-03-28 19:36 UTC
Labels: enhancement, macos, test

**Comment by elbamos** [comment] 2022-03-30 19:52
The new icon makes R look like a Microsoft product. Its more consistent with their branding than Apple's. Suggest you change it.
