### ISSUE TITLE
Cant't use arrow keys to navigate source after switching keyboard layout

### ISSUE THREAD

**Issue by lukastie** [rstudio/rstudio#6202] opened 2020-02-11 18:26 UTC
Hey!
I link to this [bug report](https://github.com/rstudio/rstudio/issues/4782) here as it is really similar to what I experience. However, I still experience the bug after updating R Studio. 

### System details
    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Windows 10 1909
    R Version       :  3.6.1

### Steps to reproduce the problem
- Enable two or more different keyboard layouts in Windows 10 settings
- Open a script in R Studio 
- Write something
- Hit Windows + space to switch between keyboard layout
- Try to use arrow keys to move cursor in R Studio source panel. The cursor does not move
- Hit alt + tab to open another window
- Hit alt + tab again to go back to R Studio
- Try to use arrow keys -> now the cursor moves again

### Describe the problem in detail
I swap between two different keyboard layouts constantly when using R Studio due to some special characters. Every time I have switched the layout, I need to open another program/window and get back to R Studio to be able to move the cursor with the arrow keys. 

In the console, after changing layout I can still use the up and down arrow buttons to go through recent inputs, however, left and right arrows will not work to move the cursor. Here I also have to open another window and get back first. 

### Describe the behavior you expected
- Writing in the R Studio source window
- Hitting windows + space to change keyboard layout
- Hitting arrow key -> cursor moves

Cheers and thanks for looking into this!
Lukas

- [ x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2020-02-20 16:35
@lukastie Thank you for raising the issue, and for providing a link to a similar issue! We'll review this a part of our issue reviews as we continue development of RStudio.

**Comment by mikebessuille** [comment] 2021-01-25 18:47
Cannot reproduce this in the latest 1.4 release.   Closing.  Please let us know if you are still experiencing this issue.

**Closed** 2021-01-25 18:47 UTC
Labels: bug, not reproducible
