### ISSUE TITLE
"State not recoverable" error when creating new Quarto doc (Electron)

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10871] opened 2022-03-30 19:54 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0-daily+247
    OS Version      : macOS 12.3
    R Version       : 4.1.3

### Steps to reproduce the problem

- Start RStudio Desktop (Electron)
- Enable Quarto preview in Global Options / R Markdown / Quarto, restart if necessary
- File / New File / Quarto Document...

### Describe the problem in detail

- after a delay, get error reading "State not recoverable"
- no document is created

![Screen Shot showing error dialog](https://user-images.githubusercontent.com/10569626/160919910-b56c396d-eee8-4591-b209-cc475e4b2387.png)

### Describe the behavior you expected

- new Quarto document; works in the Qt-based desktop build of same version

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by timtmok** [comment] 2022-04-01 14:50
Seems to only occur in a packaged build. The error:
`/Applications/RStudio Electron.app/Contents/Resources/app/bin/quarto/bin/quarto: line 77: cd: /Applications/RStudio Electron.app/Contents/Resources/app/bin/quarto/bin/../share: No such file or directory
/Applications/RStudio Electron.app/Contents/Resources/app/bin/quarto/bin/quarto: line 101: /Applications/RStudio: No such file or directory`

I also get the error in Qt. It's the wrong path to the Quarto executable.

**Comment by timtmok** [comment] 2022-04-01 18:18
I added some logging to debug and realized I was getting an error due to my rename of the app to include a space.

Here's the actual error:
`/Applications/RStudioElectron.app/Contents/Resources/app/bin/quarto/bin/quarto: line 77: cd: /Applications/RStudioElectron.app/Contents/Resources/app/bin/quarto/bin/../share: No such file or directory
[91mERROR: NotFound: No such file or directory (os error 2), readdir '/Users/tmok/source/test/formats/html/bootstrap/themes'[39m`

**Comment by timtmok** [comment] 2022-04-01 18:54
I took a look at the Quarto code and it sets `QUARTO_SHARE_PATH` to a few specific places. We're hitting the fallback since we don't package Electron with the share in the expected location. The fallback is still incorrect for the Electron package.

So the error is caused by Quarto looking for the share path and not finding it.

**Comment by timtmok** [comment] 2022-04-08 16:37
I checked the daily and it's still not fixed.

**Comment by ronblum** [comment] 2022-04-22 18:21
Verified that both Quarto documents and presentations can be created in
- RStudio Desktop 2022.06.0-daily+322 on MacOS 12.4
- RStudio Desktop 2022.06.0-daily+322 on Red Hat 8.4

**Comment by ArmelBrizuela** [comment] 2023-01-18 18:12
Hello.

I leave this comment in case someone else gets the same error. I'm working on a mac mini running macOS ventura 13.1 with an M1 chip. I have **R 4.2.2** and **RStudio 2022.12.0 Build 353** installed. Everything works fine, except that when I tried to create a .qmd file, I got the error window "State not recoverable". The issue was resolved by installing rosetta with `/usr/sbin/softwareupdate --install-rosetta --agree-to-license`.

**Comment by kevinushey** [comment] 2023-01-30 18:54
I wonder if this is because we only bundle an x86_64 build of pandoc? Do we need to consider bundling a universal build of pandoc?

**Comment by kevinushey** [comment] 2023-01-30 18:54
Re-opening to at least discuss whether we can / should bundle a universal build of pandoc:

```
kevin@MBP-P2MQ:/Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools
$ file pandoc
pandoc: Mach-O 64-bit executable x86_64
```

**Comment by gtritchie** [comment] 2023-01-30 20:13
FYI, some other non-universal components: #12572

**Comment by gtritchie** [comment] 2023-01-31 16:28
Also discussed in #12280

**Comment by mikebessuille** [comment] 2023-03-06 15:40
Tim will create a new ticket for the arm-specific aspect of this bug; closing this one.

**Closed by mikebessuille** 2023-03-06 15:40 UTC
Labels: bug, electron, quarto
