### ISSUE TITLE
Unable to publish static documents to Connect with the publish button

### ISSUE THREAD

**Issue by dbkegley** [rstudio/rstudio#9901] opened 2021-09-30 15:01 UTC
### System details

    RStudio Edition :  Desktop
    RStudio Version :  RStudio 2021.09.0 Build 351
    OS Version      :  MacOS Big Sur 11.6
    R Version       :  R version 4.0.5 (2021-03-31)

### Steps to reproduce the problem

1. Knit a static rmd document
2. From the preview window, click publish > RStudio Connect > Publish finished document only
3. Select a Connect server and click publish

### Describe the problem in detail

When attempting to publishing static documents (pre-rendered rmd, static html, etc.), RStudio fails to publish the document.

Publishing via the console is still working as expected: `rsconnect::deployDoc('index.html', ...)`

The diagnostic logs include a bunch of stack traces like the following:

```log
2021-09-30T14:52:59.417489Z [rsession-david] ERROR CLIENT EXCEPTION (rsession-david): (ReferenceError) : isQuarto is not defined;|||rstudio-0.js#-1::eval|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||org/rstudio/studio/client/rsconnect/RSConnect.java#821::deployFromSatellite|||org/rstudio/studio/client/rsconnect/RSConnect.java#875::fireRSConnectPublishEvent|||org/rstudio/studio/client/rsconnect/RSConnect.java#557::execute|||org/rstudio/studio/client/rsconnect/RSConnect.java#557::execute|||org/rstudio/core/client/widget/ModalDialog.java#90::execute|||org/rstudio/core/client/widget/Wizard.java#261::lambda$8|||org/rstudio/core/client/widget/Wizard.java#261::execute|||org/rstudio/core/client/widget/Wizard.java#261::execute|||org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java#512::execute|||org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java#1134::onResponseReceived|||org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java#1134::onResponseReceived|||org/rstudio/studio/client/server/remote/RemoteServer.java#3790::onResponseReceived|||rstudio-0.js#-1::eval|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||org/rstudio/studio/client/server/remote/RemoteServer.java#3690::performCallback|||org/rstudio/studio/client/server/remote/RemoteServer.java#3677::onResponseReceived|||org/rstudio/studio/client/server/remote/RemoteServer.java#3414::onResponseReceived|||org/rstudio/core/client/jsonrpc/RpcRequest.java#131::onResponseReceived|||com/google/gwt/http/client/Request.java#233::fireOnResponseReceived|||com/google/gwt/http/client/RequestBuilder.java#409::onReadyStateChange|||rstudio-0.js#-1::eval|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 11_6_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
```

### Describe the behavior you expected

I expect to be able to publish static documents to Connect using the publish button in the IDE

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment] 2021-09-30 20:00
May be a candidate for backport to Ghost Orchid if it reproduces consistently.

**Comment by ronblum** [comment] 2021-10-01 14:09
@dbkegley I'm unable to reproduce this. Is this an issue with the default Rmd created by RStudio? Or if not, could you provide a sample Rmd? Thanks!

**Comment by dbkegley** [comment] 2021-10-01 14:36
I have been able to reproduce this consistently from one of the provided templates in the IDE. `New document dropdown > R Markdown... > From Template > GitHub Document (Markdown)`

I believe @ChaitaC said that she was able to reproduce it as well on `2021.09.0 Build 351` but was not able to repro on `1.4.1717`

It's also worth noting that I have been testing quarto using pre-release builds. I saw the behavior initially on a daily build, then re-installed the latest stable release and re-tested before filing this issue

**Comment by ronblum** [comment] 2021-10-01 15:59
@dbkegley What happens if you uninstall Quarto?

**Comment by ronblum** [comment] 2021-10-01 17:42
[Followup from internal discussion]

1. FAILURE if published from a preview window
    - RStudio Desktop 2021.09.0+351 on MacOS 12 beta
    - RStudio Server 2021.09.0+351 on Ubuntu 20.04 via Safari on MacOS 12 beta
2. SUCCESS if published from the Viewer pane
    - RStudio Desktop 2021.09.0+351 on MacOS 12 beta
    - RStudio Server 2021.09.0+351 on Ubuntu 20.04 via Safari on MacOS 12 beta
3. SUCCESS in both cases in RStudio Desktop Juliet Rose
     - RStudio Desktop 1.4.1717 on MacOS 12 beta

**Comment by mikebessuille** [comment] 2021-10-04 17:07
This is a serious issue.  Doesn't necessarily warrant a patch on its own because there is a workaround, but we should patch in GO if a patch is otherwise needed.

**Comment by jmcphers** [comment] 2021-10-05 18:56
@cm421 This is a good place to start poking around, and feel free to bug me if you get stuck:

https://github.com/rstudio/rstudio/blob/490a91b3e98ffb0f62505b481abbe5f1ff9b44ef/src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java#L821-L842

**Comment by aja08379** [comment] 2021-10-06 10:08
@jmcphers have a customer seeing this issue inside RDP as well; will drop you a message with the Zendesk ref.

**Comment by scubastevew** [comment] 2021-10-07 18:24
A customer reported this issue in ticket 66803

**Comment by aja08379** [comment] 2021-10-08 15:06
Ticket 67184 also

**Comment by R-Hannibal** [comment] 2021-10-18 19:44
Verified Fixed on: RSW Version - 2021.09.1 Build 358.pro1, R Version - 4.1.0, rhel7 - Server 

Documents are now publishing successfully to Connect when published from a window (also tested publishing from the Viewer pane and console to verify those methods continue to function after the fix).

**Closed by R-Hannibal** 2021-10-18 19:44 UTC
Labels: bug, publishing, test

**Comment by R-Hannibal** [comment] 2021-10-19 14:30
Re-opening so this doesn't get closed before an automated test is written and adding the `autotest` label.

It looks like we already have a test in place for testing publishing to connect from the viewer pane [HERE](https://github.com/rstudio/rstudio-ide-automation/blob/master/rstudio_server_pro/tests/test_PublishToConnect.py), but as this ticket shows, we should probably test publishing from an external window as well (Settings button on the source pane > select Preview in Window).

**Comment by datakid** [comment] 2021-10-20 23:24
Ticket 67570 as well.
