### ISSUE TITLE
Square brackets automatically added around citations when switching to visual markdown

### ISSUE THREAD

**Issue by timbeechey** [rstudio/rstudio#7976] opened 2020-10-06 15:55 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.869 
    OS Version      : Windows 10
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Create a new RMarkdown document
2. Add a citation of the form `@nameyyyy`
3. Switch to visual markdown mode

### Describe the problem in detail

Square brackets are automatically added around citations of the form `@nameyyyy` to produce `[@nameyyyy]` when switching to visual markdown mode.

### Describe the behavior you expected

I expected a distinction to be maintained between bracketed and unbracketed citation forms to allow the use of both narrative and parenthesized citations, e.g. Name (yyyy) vs (Name, yyyy).

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by dragonstyle** [comment] 2020-10-07 00:33
Hi @timbeechey - thanks for opening this issue. 

We do standardize the citation format to the form `[@<citekey>]` in the visual editor. The square brackets are a part of the citation identifier, however, so they shouldn't affect or be present when the document is rendered (e.g. the rendering of the citation inline and in the bibliography should follow the form that is configured for the document via CSL). 

You can use the form `[-@citekey]` which will suppress the author (useful in the narrative case). Sample:

![Screen Shot 2020-10-06 at 8 32 41 PM](https://user-images.githubusercontent.com/261654/95274193-239fad00-0813-11eb-8866-556528b8718b.png)

Does this work for you?

**Comment by timbeechey** [comment] 2020-10-07 00:54
Hi @dragonstyle, thank you for your response. This does make the visual mode much less attractive for writing academic articles than it otherwise would be, in my opinion. If a citekey lacks brackets it seems to me that it can only be because the brackets were manually deleted by the user (since brackets are automatically present when a citation is first inserted). Adding brackets on switching to visual mode then only functions to undo a deliberate change made by the user. Is there another benefit to automatically adding the brackets?

The suggested solution of using the `[-@citekey]` form somewhat defeats the purpose of using a citation system since the user then needs to manually type author names and remember the specific rules of the particular style that should be taken care of by the CSL.

**Comment by earcanal** [comment] 2020-10-07 10:51
I agree with @timbeechey that this is a regression. The most common use cases for citations are rendering in text or parentheses, so it's going to be unpopular if the visual editor silently changes in-text citations such that they need manually repairing with `Foo [-@foo]`.

Incidentally, the way I ran into this was by inserting a citation in the visual editor and removing the square brackets. The editor escapes the citation, meaning that it's impossible to enter in-text citations (e.g. `@foo`).

Perhaps it's possible to trigger the citation manager on `@[a-zA-Z]` as well as `@\[`.

**Comment by earcanal** [comment] 2020-10-07 14:24
A related issue seems to be that including additional text within the citation e.g. `[@tsai_attentional_2016, Experiment 2]` is laggy, presumably because it's searching for a different key.

**Comment by dragonstyle** [comment] 2020-10-07 20:01
> A related issue seems to be that including additional text within the key e.g. `[@tsai_attentional_2016, Experiment 2]` is laggy, presumably because it's searching for a different key. When you click into these keys, you don't see the full citation (nice feature btw!). Again, probably because it's using everything in `[@]` as a search term.

Thanks - I will look into this!

**Comment by dragonstyle** [comment] 2020-10-07 20:12
> Hi @dragonstyle, thank you for your response. This does make the visual mode much less attractive for writing academic articles than it otherwise would be, in my opinion. If a citekey lacks brackets it seems to me that it can only be because the brackets were manually deleted by the user (since brackets are automatically present when a citation is first inserted). Adding brackets on switching to visual mode then only functions to undo a deliberate change made by the user. Is there another benefit to automatically adding the brackets?
> 
> The suggested solution of using the `[-@citekey]` form somewhat defeats the purpose of using a citation system since the user then needs to manually type author names and remember the specific rules of the particular style that should be taken care of by the CSL.

Ok, thanks for the clarification - I'm going to look into this a bit further...

**Comment by dragonstyle** [comment] 2020-10-07 21:10
You guys are definitely right- we're going to get these in-text citations working properly (supporting `@citekey` for in-text citation without mutating them to include the brackets).

**Comment by dragonstyle** [comment] 2020-10-28 17:42
This should be fixed now- we fully support both forms of citations and also give you the option to select in-text in the insert citation dialog. Documentation updated here!

https://rstudio.github.io/visual-markdown-editing/#/citations

**Closed by dragonstyle** 2020-10-28 17:42 UTC
Labels: bug, visual markdown editing

**Comment by timbeechey** [comment] 2020-10-29 14:16
Using build 1.4.984 I am still encountering some issues with square brackets being automatically inserted when switching to visual markdown mode and `@` being escaped.

In order to cite multiple sources by the same author I used `@smith1999 [-@smith2000]` which correctly produced Smith (1999, 2000). But when switching into visual mode this is transformed to `[@smith1999; -@smith2000]` which is rendered as (Smith 1999, 2000). If I delete the left square bracket in visual mode then `@` is escaped. It seems that `@` is escaped when any non whitespace character is deleted immediately to the left.

**Comment by jdutant** [comment] 2020-10-31 11:46
Related: if we try and insert several citations the "in-text" option disappears, even if all the citations have the same author.
