### ISSUE TITLE
Cannot open a file from the file explorer

### ISSUE THREAD

**Issue by ArmandoRl1** [rstudio/rstudio#4625] opened 2019-04-11 18:59 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1335
    OS Version      :  Windows 10 Version 1803
    R Version       : 3.5.2

### Steps to reproduce the problem
Open a .R, .Rmd or .Rproj file from the Windows File Explorer

### Describe the problem in detail
RStudio opens in a new window (even if it was open before) and once it loads, won't open any file in the editor, nor load any project.

### Describe the behavior you expected
RStudio should open the file that launched it.

**Comment by keyurbipinshah** [comment] 2019-04-11 19:08
Facing the same issue.

`R Studio Version: 1.2.1335`
`OS: Windows 10, version 1803`
`R Version: 3.5.3`
`RStudio Edition: Desktop`

RStudio crashes when trying to:
1. Trying to save a script using File > Save File option.
2. Trying to add new theme using the 'Add' button in the Global Options > Appearance tab.
3. Trying to open a script using File > Open File option.

This problem seems to pop up whenever Windows File Selection box appears.

**Comment by jmcphers** [comment] 2020-04-27 22:58
I can't reproduce this and there have been no reports in over a year, so closing.

**Closed by jmcphers** 2020-04-27 22:58 UTC
Labels: bug, windows
