### ISSUE TITLE
Console hyperlink makes part of the output disappear

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/rstudio#13869] opened 2023-10-31 15:00 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.1 Build 494
    OS Version      : macOS 13.5.2 (22G91)
    R Version       : 4.3.1

### Steps to reproduce the problem

```
#works with short names
cli::cli_inform("Unzipping {.file C:\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.zip}")
#doesn't with long names
cli::cli_inform("Unzipping {.file C:\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxx xxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxxxxxxxxxx xxxxxxxxxxxx xxxxxxxx.zip}")
#works with .val
cli::cli_inform("Unzipping {.val C:\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxx xxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxxxxxxxxxx xxxxxxxxxxxx xxxxxxxx.zip}")
```

### Describe the problem in detail

If there is a long hyperlink in the output, then part of the output (the "Unzipping" part in this case) disappears.

### Describe the behavior you expected

I expected the same output, as in a terminal, e.g.

```
❯ cli::cli_inform("Unzipping {.file C:\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxx xxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxxxxxxxxxx xxxxxxxxxxxx xxxxxxxx.zip}")
Unzipping
C:\xxxxxxxxxx\xxxxxxxxxx\xxxxxxxxxx\xxxxxxxxxx\xxxxxxxxxx\xxxxxxxxxx\xxxxx xxxxx\xxxxxxxxxx\xxx xxxxxx\xxxxx xxxxx\xxxxxxxxxx\xxxxxxxxxxx xxxxxxxxxxxx xxxxxxxx.zip
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment] 2023-10-31 16:26
It seems to be related to the console width; I can reproduce with smaller text if I use a smaller console width.

**Comment by kevinushey** [comment] 2023-10-31 16:28
I'm not sure if it's related, but I noticed that cli is also inserting "\a\033[34m" into the middle of the output. For example:

```
> long <- paste(rep.int("_", 128), collapse = "")
> message <- sprintf("Prefix: {.file %s}", long)
> formatted <- cli:::format_message(message)
> print(formatted)
[1] "\033[38;5;252mPrefix:\n\033]8;;file:///Users/kevin/rstudio/________________________________________________________________________________________________________________________________\a\033[34m________________________________________________________________________________________________________________________________\033[38;5;252m\033]8;;\a\033[39m"
```

But if I remove that, then no output is produced at all.

```
> formatted <- gsub("\a\033[34m", "", formatted, fixed = TRUE)
> cat(formatted)

```

**Comment by gaborcsardi** [comment] 2023-10-31 18:01
> but I noticed that cli is also inserting "\a\033[34m" into the middle of the output.

That's part of the ANSI sequence for links: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#the-escape-sequence

> But if I remove that, then no output is produced at all.

Because then you get an invalid ANSI sequence, so the output depends on how your parser handles that.

RStudio now also supports the regular `ST` terminator instead of the `\a`, but that fails the same way, so the issue is not the `\a` per se:
```r
Sys.setenv("R_CLI_HYPERLINK_MODE" = "posix")
cli::cli_inform("Unzipping {.file C:\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxx xxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxxxxxxxxxx xxxxxxxxxxxx xxxxxxxx.zip}")
```

**Comment by kevinushey** [comment] 2023-10-31 18:15
Ahh, gotcha -- thanks; that link is very useful. I'll dig in some more.

**Comment by gaborcsardi** [comment] 2023-11-02 16:34
This is possibly the same issue, cf. https://github.com/r-lib/cli/issues/627

```r
to_print <- "A long {.val value} with a {.href [link](https://github.com/)} with other stuff like {.help cli::inline-markup}"
options(cli.width = 35)
cli::cli_bullets(to_print)
```

**Comment by kevinushey** [comment] 2023-11-02 18:59
Looks like that should also be resolved via https://github.com/rstudio/rstudio/pull/13883; here's what I see:

<img width="285" alt="Screenshot 2023-11-02 at 11 59 30 AM" src="https://github.com/rstudio/rstudio/assets/1976582/5b8b9b09-26a6-4a26-be30-982509153140">

**Comment by jonvanausdeln** [comment] 2023-11-13 20:57
Verified with [2023.12.0-daily+278](https://dailies.rstudio.com/version/2023.12.0-daily+278)
Windows 11, MacOS 12.6

Long hyperlink (as per repro steps) appears correctly now.

**Closed by jonvanausdeln** 2023-11-13 20:57 UTC
Labels: bug, console
