### ISSUE TITLE
"Configure build tools" menu action does not open the correct tabs directly

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#9490] opened 2021-06-14 08:52 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.5.104
    OS Version      : Windows 10
    R Version       : 4.1.0

### Steps to reproduce the problem

* Open a project not configured with build tool
* Click "Build > Configure Build Tools..."

### Describe the problem in detail

This opens "Spelling" tab in option modal pane instead of Build tools 

![build-tools-options](https://user-images.githubusercontent.com/6791940/121865045-d1961c00-ccfd-11eb-94ee-7a9f81fc1d56.gif)

### Describe the behavior you expected

I think it should open Build Tools tab directly

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-06-14 13:36
@cderv I get the same result with RStudio Desktop 1.5.95 on MacOS 12 beta. This is a regression, as it works correctly—starting with Build Tools—in 1.4.1717 (Desktop on MacOS 12 and Windows 10).

**Comment by gtritchie** [comment] 2021-06-14 16:42
Same problem using the dropdown in build pane:

![screenshot of build pane with more dropdown expanded](https://user-images.githubusercontent.com/10569626/121928255-d1455300-ccf4-11eb-9207-3f426f60308e.png)

**Comment by gtritchie** [comment] 2021-06-14 17:02
Caused by: https://github.com/rstudio/rstudio/commit/40ef46a6cb2de01bc7729a5de730e4764b8c6b30

**Comment by ronblum** [comment] 2021-06-14 18:52
Added QA note: This also affects <kbd>Tools -> Version Control -> Project Setup</kbd>.

**Comment by astayleraz** [comment] 2021-06-22 16:17
Verified in version 1.5.109-2 the correct sections are opening from these drop-down options and added an automated test to check these 2 spots. Closing issue.

**Closed by astayleraz** 2021-06-22 16:17 UTC
Labels: bug, regression, test, user preferences
