### ISSUE TITLE
Inline math not rendering properly in new visual R markdown editing

### ISSUE THREAD

**Issue by skandgoel** [rstudio/rstudio#8839] opened 2021-01-28 18:47 UTC
### System details

    RStudio Edition: Desktop
    RStudio Version: 1.4.1103
    OS Version: MacOS High Sierra 10.13.2
    R Version: 4.0.2 

### Describe the problem
The inline math mode in the visual markdown editing feature is not working properly. It automatically escapes the `$...$` characters when they appear for a *second time* on a given line. 

### Steps to reproduce 
I am using the visual markdown editing feature of RStudio for writing a long-form scientific document. Open a new markdown file or R notebook. The inline math mode  `$...$` is rendered properly only the first time it is input on a given line. When I input it again on the same line, the `$` character is escaped and the math is not rendered properly. See below:

![RstudioBug](https://user-images.githubusercontent.com/73049859/106181897-24ff3780-616c-11eb-82fe-895b82b3ec7d.gif)

When I toggle back to the raw text mode, I can see that the second inline equation is entered as `\$x+y\$`.

Note that when I move to the next line by pressing the return key, it works fine again only for the first time.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-01-28 19:17
This is a duplicate of #8810, though I'm copying over the helpful animated GIF.

**Closed by ronblum** 2021-01-28 19:17 UTC
Labels: duplicate
