### ISSUE TITLE
Error saving to networked drives

### ISSUE THREAD

**Issue by jillymackay** [rstudio/rstudio#13052] opened 2023-04-26 10:52 UTC
I have a recurring error saving to networked drives. This has happened since updating to RStudio 2023.03.0+386  

**About the error:**

When saving an R Script (R), RMarkdown (.rmd), or Quarto (.qmd) file from R Studio, I receive an error:

> Error Saving File
> Error saving [path]: The network name cannot be found.

 
The issue does not occur with Version 1.2.5019 of RStudio which I also have access to. The issue does not occur in base R. 

The behaviour occurs:

- In a new, 'blank' R Studio project or existing projects
- When the PC is connected via  a hard ethernet line or through a remote VPN
- When the project is located on a local directory or a networked directory

 
![rstudio_error1](https://user-images.githubusercontent.com/31953319/234552495-42687d92-8145-400f-897f-3c7550270872.png)

**Session Info for new project with error**
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8 
[2] LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.3 tools_4.2.3 

**Request Log for new project with error**
1682506075230
1682505832387,-1894778784,"{""method"":""get_events"", ""params"":[70], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505833469,"{""result"":[{""id"":71,""type"":""console_write_prompt"",""data"":""> ""},{""id"":72,""type"":""console_write_input"",""data"":{""text"":""Sys.getenv()\n"",""console"":"""",""flags"":0}},{""id"":73,""type"":""history_entries_added"",""data"":{""index"":[0],""timestamp"":[0.0],""command"":[""Sys.getenv()""]}},{""id"":74,""type"":""busy"",""data"":{""value"":true}}],""ep"":""false""}"
1682505833033,1504185794,"{""method"":""get_args"", ""params"":[""Sys.getenv"",""package:base"",""""], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505833039,"{""result"":""(x = NULL, unset = \""\"", names = NA) "",""ep"":""false""}"
1682505833451,470853269,"{""method"":""console_input"", ""params"":[""Sys.getenv()"","""",0], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505833458,{"result":null}
1682505833475,165812120,"{""method"":""get_events"", ""params"":[74], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505833501,"{""result"":[{""id"":75,""type"":""console_output"",""data"":{""text"":""ALLUSERSPROFILE        C:\\ProgramData\nAPPDATA                C:\\Users\\jmackay4\\AppData\\Roaming\nCLICOLOR_FORCE         1\nCommonProgramFiles     C:\\Program Files\\Common Files\nCommonProgramFiles(x86)\n                       C:\\Program Files (x86)\\Common Files\nCommonProgramW6432     C:\\Program Files\\Common Files\nCOMPUTERNAME           MVM-EB-L21032\nComSpec                C:\\WINDOWS\\system32\\cmd.exe\nCURL_CA_BUNDLE         C:/Users/jmackay4/AppData/Local/Programs/R/R-4.2.3/etc/curl-ca-bundle.crt\nDISPLAY                :0\nDriverData             C:\\Windows\\System32\\Drivers\\DriverData\nFPS_BROWSER_APP_PROFILE_STRING\n                       Internet Explorer\nFPS_BROWSER_USER_PROFILE_STRING\n                       Default\nGFORTRAN_STDERR_UNIT   -1\nGFORTRAN_STDOUT_UNIT   -1\nGIT_ASKPASS            rpostback-askpass\nHOME                   C:/Users/jmackay4/Documents\nHOMEDRIVE              M:\nHOMEPATH               \\\nHOMESHARE              \\\\cmvm.datastore.ed.ac.uk\\cmvm\\eb\\users\\jmackay4\nLOCALAPPDATA           C:\\Users\\jmackay4\\AppData\\Local\nLOGONSERVER            \\\\KELSO\nMPLENGINE              tkAgg\nMSYS2_ENV_CONV_EXCL    R_ARCH\nNUMBER_OF_PROCESSORS   8\nOneDrive               C:\\Users\\jmackay4\\OneDrive - University of\n                       Edinburgh\nOneDriveCommercial     C:\\Users\\jmackay4\\OneDrive - University of\n                       Edinburgh\nORIGINAL_XDG_CURRENT_DESKTOP\n                       undefined\nOS                     Windows_NT\nPATH                   c:\\rtools42\\x86_64-w64-mingw32.static.posix\\bin;c:\\rtools42\\usr\\bin;C:\\rtools40\\usr\\bin;C:\\Users\\jmackay4\\AppData\\Local\\Programs\\R\\R-4.2.3\\bin\\x64;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program\n                       Files\\Git\\cmd;C:\\Program Files\\Microsoft SQL\n                       Server\\120\\Tools\\Binn\\;C:\\Program Files\n                       (x86)\\Windows\n                       Live\\Shared;C:\\Users\\jmackay4\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program\n                       Files\\RStudio\\resources\\app\\bin\\quarto\\bin;C:\\Program\n                       Files\\RStudio\\resources\\app\\bin\\postback\nPATHEXT                .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC\nPROCESSOR_ARCHITECTURE\n                       AMD64\nPROCESSOR_IDENTIFIER   Intel64 Family 6 Model 142 Stepping 12,\n                       GenuineIntel\nPROCESSOR_LEVEL        6\nPROCESSOR_REVISION     8e0c\nProgramData            C:\\ProgramData\nProgramFiles           C:\\Program Files\nProgramFiles(x86)      C:\\Program Files (x86)\nProgramW6432           C:\\Program Files\nPSModulePath           C:\\Program\n                       Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\nPUBLIC                 C:\\Users\\Public\nPYTHONIOENCODING       utf-8\nR_ARCH                 /x64\nR_CLI_HAS_HYPERLINK_IDE_HELP\n                       true\nR_CLI_HAS_HYPERLINK_IDE_RUN\n                       true\nR_CLI_HAS_HYPERLINK_IDE_VIGNETTE\n                       true\nR_COMPILED_BY          gcc 10.4.0\nR_DOC_DIR              C:/Users/jmackay4/AppData/Local/Programs/R/R-4.2.3/doc\nR_HOME                 C:/Users/jmackay4/AppData/Local/Programs/R/R-4.2.3\nR_INCLUDE_DIR          C:/Users/jmackay4/AppData/Local/Programs/R/R-4.2.3/include\nR_LIBS_SITE            C:/Users/jmackay4/AppData/Local/Programs/R/R-4.2.3/site-library\nR_LIBS_USER            C:\\Users\\jmackay4\\AppData\\Local/R/win-library/4.2\nR_RTOOLS42_PATH        c:/rtools42/x86_64-w64-mingw32.static.posix/bin;c:/rtools42/usr/bin\nR_RUNTIME              ucrt\nR_SHARE_DIR            C:/Users/jmackay4/AppData/Local/Programs/R/R-4.2.3/share\nR_USER                 C:/Users/jmackay4/Documents\nRMARKDOWN_MATHJAX_PATH\n                       C:/Program\n                       Files/RStudio/resources/app/resources/mathjax-27\nRS_LOCAL_PEER          \\\\.\\pipe\\43259-rsession\nRS_LOG_LEVEL           WARN\nRS_RPOSTBACK_PATH      C:/Program\n                       Files/RStudio/resources/app/bin/rpostback.exe\nRS_SHARED_SECRET       e90430e9-5b87-4dad-9cab-1126049e34f8\nRSTUDIO                1\nRSTUDIO_CLI_HYPERLINKS\n                       true\nRSTUDIO_CONSOLE_COLOR\n                       256\nRSTUDIO_CONSOLE_WIDTH\n                       77\nRSTUDIO_MSYS_SSH       C:/Program\n                       Files/RStudio/resources/app/bin/msys-ssh-1000-18\nRSTUDIO_PANDOC         C:/Program\n                       Files/RStudio/resources/app/bin/quarto/bin/tools\nRSTUDIO_PROGRAM_MODE   desktop\nRSTUDIO_SESSION_PID    3932\nRSTUDIO_SESSION_PORT   43259\nRSTUDIO_USER_IDENTITY\n                       jmackay4\nRSTUDIO_WINUTILS       C:/Program\n                       Files/RStudio/resources/app/bin/winutils\nRTOOLS40_HOME          C:\\rtools40\nSESSIONNAME            Console\nSSH_ASKPASS            rpostback-askpass\nSystemDrive            C:\nSystemRoot             C:\\WINDOWS\nTEMP                   C:\\Users\\jmackay4\\AppData\\Local\\Temp\nTERM                   xterm-256color\nTMP                    C:\\Users\\jmackay4\\AppData\\Local\\Temp\nUATDATA                C:\\WINDOWS\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77\nUSERDNSDOMAIN          ED.AC.UK\nUSERDOMAIN             ED\nUSERDOMAIN_ROAMINGPROFILE\n                       ED\nUSERNAME               jmackay4\nUSERPROFILE            C:\\Users\\jmackay4\nwindir                 C:\\WINDOWS\nZES_ENABLE_SYSMAN      1\n"",""console"":""""}},{""id"":76,""type"":""busy"",""data"":{""value"":false}},{""id"":77,""type"":""console_prompt"",""data"":{""prompt"":""> "",""history"":true,""default"":true,""language"":""R""}}],""ep"":""false""}"
1682505833518,-336090372,"{""method"":""get_events"", ""params"":[77], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505834067,"{""result"":[{""id"":78,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8654040,""provider"":2},""process"":{""kb"":125800,""provider"":2}}}],""ep"":""false""}"
1682505834070,-327816420,"{""method"":""get_events"", ""params"":[78], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505841483,"{""result"":[{""id"":79,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8650484,""provider"":2},""process"":{""kb"":125808,""provider"":2}}}],""ep"":""false""}"
1682505841491,1421625254,"{""method"":""get_events"", ""params"":[79], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505851565,"{""result"":[{""id"":80,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8865592,""provider"":2},""process"":{""kb"":125816,""provider"":2}}}],""ep"":""false""}"
1682505851572,537452593,"{""method"":""get_events"", ""params"":[80], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505861548,"{""result"":[{""id"":81,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8772896,""provider"":2},""process"":{""kb"":125824,""provider"":2}}}],""ep"":""false""}"
1682505861561,270036425,"{""method"":""get_events"", ""params"":[81], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505871571,"{""result"":[{""id"":82,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8797488,""provider"":2},""process"":{""kb"":125836,""provider"":2}}}],""ep"":""false""}"
1682505871584,1864994238,"{""method"":""get_events"", ""params"":[82], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505881639,"{""result"":[{""id"":83,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8689328,""provider"":2},""process"":{""kb"":125980,""provider"":2}}}],""ep"":""false""}"
1682505881655,1813902118,"{""method"":""get_events"", ""params"":[83], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505891627,"{""result"":[{""id"":84,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8699136,""provider"":2},""process"":{""kb"":125988,""provider"":2}}}],""ep"":""false""}"
1682505891646,1137720193,"{""method"":""get_events"", ""params"":[84], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505894994,"{""result"":[{""id"":85,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8715128,""provider"":2},""process"":{""kb"":125988,""provider"":2}}}],""ep"":""false""}"
1682505894305,-1153553367,"{""method"":""git_all_status"", ""params"":[], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505894429,"{""result"":{""status"":[{""status"":""??"",""path"":"".gitignore"",""raw_path"":""~/data/test/.gitignore"",""discardable"":false,""is_directory"":false,""size"":44.0},{""status"":""??"",""path"":""test.Rproj"",""raw_path"":""~/data/test/test.Rproj"",""discardable"":false,""is_directory"":false,""size"":218.0}],""branches"":{""branches"":[],""activeIndex"":null},""remote_branch_info"":null},""ep"":""false""}"
1682505894997,-1738510911,"{""method"":""get_events"", ""params"":[85], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505896514,"{""result"":[{""id"":86,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8720380,""provider"":2},""process"":{""kb"":137320,""provider"":2}}}],""ep"":""false""}"
1682505895709,-1031620413,"{""method"":""get_source_template"", ""params"":["""",""default.R""], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505895716,"{""result"":"""",""ep"":""false""}"
1682505895717,1091574071,"{""method"":""new_document"", ""params"":[""r_source"","""",{}], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505895730,"{""result"":{""id"":""157619E4"",""path"":null,""project_path"":null,""type"":""r_source"",""hash"":""0"",""contents"":"""",""dirty"":false,""created"":1682505895720.0,""source_on_save"":false,""relative_order"":2,""properties"":{},""folds"":"""",""lastKnownWriteTime"":2314885530818453536,""encoding"":"""",""collab_server"":"""",""source_window"":"""",""last_content_update"":1682505895720,""read_only"":false,""read_only_alternatives"":[],""extended_type"":"""",""notebook"":{}},""ep"":""false""}"
1682505895825,-802313817,"{""method"":""modify_document_properties"", ""params"":[""157619E4"",{""tempName"":""Untitled2""}], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505895886,"{""result"":null,""ep"":""false""}"
1682505895826,-1262492853,"{""method"":""discover_package_dependencies"", ""params"":[""157619E4"","".R""], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505895940,"{""result"":{""ready"":true,""packages"":[]},""ep"":""false""}"
1682505895865,-192349152,"{""method"":""modify_document_properties"", ""params"":[""157619E4"",{""source_window_id"":"""", ""Source"":""Source""}], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505895942,"{""result"":null,""ep"":""false""}"
1682505896521,-369171373,"{""method"":""get_events"", ""params"":[86], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505901733,"{""result"":[{""id"":87,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8950092,""provider"":2},""process"":{""kb"":137320,""provider"":2}}}],""ep"":""false""}"
1682505900592,810180954,"{""method"":""set_client_state"", ""params"":[{},{},{""source-pane"":{""activeTab"":1}}], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505900598,"{""result"":null,""ep"":""false""}"
1682505901743,422114945,"{""method"":""get_events"", ""params"":[87], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505911728,"{""result"":[{""id"":88,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8891484,""provider"":2},""process"":{""kb"":137320,""provider"":2}}}],""ep"":""false""}"
1682505911730,-1791875464,"{""method"":""get_events"", ""params"":[88], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505921744,"{""result"":[{""id"":89,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8889920,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682505921748,94426131,"{""method"":""get_events"", ""params"":[89], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505931771,"{""result"":[{""id"":90,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8778864,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682505931783,-951400529,"{""method"":""get_events"", ""params"":[90], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505941892,"{""result"":[{""id"":91,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8787548,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682505941895,-156245144,"{""method"":""get_events"", ""params"":[91], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505951883,"{""result"":[{""id"":92,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8775336,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682505951888,-1663670694,"{""method"":""get_events"", ""params"":[92], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505961956,"{""result"":[{""id"":93,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8777436,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682505961962,1245230400,"{""method"":""get_events"", ""params"":[93], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505971903,"{""result"":[{""id"":94,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8793804,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682505971916,1449076225,"{""method"":""get_events"", ""params"":[94], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505981967,"{""result"":[{""id"":95,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8757656,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682505981976,592311166,"{""method"":""get_events"", ""params"":[95], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682505992000,"{""result"":[{""id"":96,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8825660,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682505992015,-871573902,"{""method"":""get_events"", ""params"":[96], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506002058,"{""result"":[{""id"":97,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8794172,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682506002072,1702539284,"{""method"":""get_events"", ""params"":[97], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506012110,"{""result"":[{""id"":98,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8793376,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682506012122,1480017634,"{""method"":""get_events"", ""params"":[98], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506015671,"{""result"":[{""id"":99,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8802952,""provider"":2},""process"":{""kb"":137284,""provider"":2}}}],""ep"":""false""}"
1682506015041,2003275668,"{""method"":""git_all_status"", ""params"":[], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506015149,"{""result"":{""status"":[{""status"":""??"",""path"":"".gitignore"",""raw_path"":""~/data/test/.gitignore"",""discardable"":false,""is_directory"":false,""size"":44.0},{""status"":""??"",""path"":""test.Rproj"",""raw_path"":""~/data/test/test.Rproj"",""discardable"":false,""is_directory"":false,""size"":218.0}],""branches"":{""branches"":[],""activeIndex"":null},""remote_branch_info"":null},""ep"":""false""}"
1682506015674,-1311243203,"{""method"":""get_events"", ""params"":[99], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506018172,"{""result"":[{""id"":100,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8802580,""provider"":2},""process"":{""kb"":139508,""provider"":2}}}],""ep"":""false""}"
1682506017261,-1225184288,"{""method"":""get_completions"", ""params"":[""session"",[],[],[],"""","""",[],[],false,"""","""",""session"",true], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506017591,"{""result"":{""token"":[""session""],""results"":[""sessionInfo"",""sessioninfo::""],""packages"":[""package:utils"",""sessioninfo""],""quote"":[false,false],""type"":[6.0,21.0],""meta"":["""",""""],""fguess"":[""""],""excludeOtherCompletions"":false,""excludeOtherArgumentCompletions"":false,""overrideInsertParens"":false,""cacheable"":true,""helpHandler"":null,""language"":""R"",""context"":[0.0,13.0]},""ep"":""false""}"
1682506018187,-303759147,"{""method"":""get_events"", ""params"":[100], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506018923,"{""result"":[{""id"":101,""type"":""console_write_prompt"",""data"":""> ""},{""id"":102,""type"":""console_write_input"",""data"":{""text"":""sessionInfo()\n"",""console"":"""",""flags"":0}},{""id"":103,""type"":""history_entries_added"",""data"":{""index"":[1],""timestamp"":[0.0],""command"":[""sessionInfo()""]}},{""id"":104,""type"":""busy"",""data"":{""value"":true}}],""ep"":""false""}"
1682506018586,1312416042,"{""method"":""get_args"", ""params"":[""sessionInfo"",""package:utils"",""""], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506018623,"{""result"":""(package = NULL) "",""ep"":""false""}"
1682506018909,-313978979,"{""method"":""console_input"", ""params"":[""sessionInfo()"","""",0], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506018922,{"result":null}
1682506018932,-943799351,"{""method"":""get_events"", ""params"":[104], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506018961,"{""result"":[{""id"":105,""type"":""console_output"",""data"":{""text"":""R version 4.2.3 (2023-03-15 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 19044)\n\nMatrix products: default\n\nlocale:\n[1] LC_COLLATE=English_United Kingdom.utf8 \n[2] LC_CTYPE=English_United Kingdom.utf8   \n[3] LC_MONETARY=English_United Kingdom.utf8\n[4] LC_NUMERIC=C                           \n[5] LC_TIME=English_United Kingdom.utf8    \n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nloaded via a namespace (and not attached):\n[1] compiler_4.2.3 tools_4.2.3   \n"",""console"":""""}},{""id"":106,""type"":""busy"",""data"":{""value"":false}},{""id"":107,""type"":""console_prompt"",""data"":{""prompt"":""> "",""history"":true,""default"":true,""language"":""R""}}],""ep"":""false""}"
1682506018968,1858522504,"{""method"":""get_events"", ""params"":[107], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506019448,"{""result"":[{""id"":108,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8811412,""provider"":2},""process"":{""kb"":139648,""provider"":2}}}],""ep"":""false""}"
1682506019451,1797053060,"{""method"":""get_events"", ""params"":[108], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506022141,"{""result"":[{""id"":109,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8827600,""provider"":2},""process"":{""kb"":139648,""provider"":2}}}],""ep"":""false""}"
1682506022144,-691704666,"{""method"":""get_events"", ""params"":[109], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506032148,"{""result"":[{""id"":110,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8823492,""provider"":2},""process"":{""kb"":139648,""provider"":2}}}],""ep"":""false""}"
1682506032158,1942112924,"{""method"":""get_events"", ""params"":[110], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506042150,"{""result"":[{""id"":111,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8824720,""provider"":2},""process"":{""kb"":139648,""provider"":2}}}],""ep"":""false""}"
1682506042166,-77101124,"{""method"":""get_events"", ""params"":[111], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506052107,"{""result"":[{""id"":112,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8817024,""provider"":2},""process"":{""kb"":139648,""provider"":2}}}],""ep"":""false""}"
1682506052122,-413043745,"{""method"":""get_events"", ""params"":[112], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506062177,"{""result"":[{""id"":113,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8803204,""provider"":2},""process"":{""kb"":139648,""provider"":2}}}],""ep"":""false""}"
1682506062191,1708573683,"{""method"":""get_events"", ""params"":[113], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506065318,"{""result"":[{""id"":114,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8811320,""provider"":2},""process"":{""kb"":139648,""provider"":2}}}],""ep"":""false""}"
1682506064642,-757450336,"{""method"":""git_all_status"", ""params"":[], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506064741,"{""result"":{""status"":[{""status"":""??"",""path"":"".gitignore"",""raw_path"":""~/data/test/.gitignore"",""discardable"":false,""is_directory"":false,""size"":44.0},{""status"":""??"",""path"":""test.Rproj"",""raw_path"":""~/data/test/test.Rproj"",""discardable"":false,""is_directory"":false,""size"":218.0}],""branches"":{""branches"":[],""activeIndex"":null},""remote_branch_info"":null},""ep"":""false""}"
1682506065323,-865638410,"{""method"":""get_events"", ""params"":[114], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",1,1682506072189,"{""result"":[{""id"":115,""type"":""memory_usage_changed"",""data"":{""total"":{""kb"":16086376,""provider"":2},""used"":{""kb"":8818660,""provider"":2},""process"":{""kb"":139648,""provider"":2}}}],""ep"":""false""}"
1682506072204,2000500179,"{""method"":""get_events"", ""params"":[115], ""clientId"":""33e600bb-c1b1-46bf-b562-ab5cba070b0e"", ""clientVersion"":""""}",0
[environment.txt](https://github.com/rstudio/rstudio/files/11331875/environment.txt)

**Environment Data**
Attached

**Comment by econm5** [comment] 2023-04-26 15:12
Thank you for your excellent work. We have experienced this problem with similar behavior. We also see this happen on an intermittent basis with existing scripts that already exist in a UNC directory, and kept open and worked on with edits for about a half work day, then fail to save with the error shown above.

The problem seems to have been introduced with version 2022.12.0-353. (We are able to use 2022.07.2-576 without this issue.)

With the release of R 4.3.0, plotting is disabled under version 2022.07.2-576, so this issue will keep us from updating to the latest version of R.

**Comment by gtritchie** [comment] 2023-04-26 15:37
This is a duplicate of #12652. The issue has been fixed in the next release, currently under development. If you want to try a pre-release build to confirm if this indeed solves the problem for you: https://dailies.rstudio.com/rstudio/mountain-hydrangea/electron/windows/

**Closed by gtritchie** 2023-04-26 15:37 UTC

**Comment by jillymackay** [comment] 2023-04-27 08:34
There's no chance I'll be able to convince my IT system to install a daily build on my managed machine, I'm afraid - but hope a stable build is released soon :)
