### ISSUE TITLE
List not expandable in global environment when it contains an array with named dims

### ISSUE THREAD

**Issue by vlandau** [rstudio/rstudio#5032] opened 2019-06-28 16:26 UTC
### System details

    RStudio Edition : Server (running in rocker/tidyverse:3.6.0)
    RStudio Version : 1.2
    OS Version      : Debian GNU/Linux 9 (stretch)
    R Version       : 3.6.0

### Steps to reproduce the problem
Run the following code:
```R
a <- matrix(1:10, ncol = 2)
b <- array(1:64, dim = c(4, 4, 4))
dimnames(b)[[1]] = 1:4
dimnames(b)[[3]] = paste0(c("one", "two", "three", "four"))

listed <- list(a = a, b = b)
```
### Describe the problem in detail
When a list object contains an array with named dimensions, it can not be expanded in the global environment. See the image below. </br>
![image](https://user-images.githubusercontent.com/17304432/60356745-fff28380-998e-11e9-8888-78cae4c69092.png)

### Describe the behavior you expected
The list should be expandable in the global environment so that contents can be viewed.

**Comment by kevinushey** [comment] 2019-06-28 18:42
This should be fixed in the latest preview release (`1:4` creates an R ALTREP object in R 3.6.0, which isn't properly understood in the latest RStudio release)

**Comment by vlandau** [comment] 2019-06-28 18:44
Thanks @kevinushey! Will adjust the code from 1:4 in the meantime (until RStudio is updated in rocker/tidyverse).

**Comment by vlandau** [comment] 2019-06-28 20:01
Just for completeness, this also produces the same error
```R
a <- matrix(1:10, ncol = 2)
b <- array(1:64, dim = c(4, 4, 4))
dimnames(b)[[1]] = as.character(seq(1,4,1))
dimnames(b)[[3]] = paste0(c("one", "two", "three", "four"))

listed <- list(a = a, b = b)
``` 
Does seq(1, 4, 1) also create an R ALTREP?

**Comment by jmcphers** [comment] 2019-06-28 22:09
> Does seq(1, 4, 1) also create an R ALTREP?

It doesn't look like it. Recent versions of the IDE have a hidden `.rs.isAltrep` function that will tell you if an object is an R ALTREP. 

```r
> foo <- 1:4
> .rs.isAltrep(foo)
[1] TRUE
> bar <- seq(1, 4, 1)
> .rs.isAltrep(bar)
[1] FALSE
```

**Comment by jmcphers** [comment] 2019-06-28 22:21
For what it's worth, though, I can't reproduce this problem in the current preview release (1.2.1555). Can you?

![image](https://user-images.githubusercontent.com/470418/60374260-66d86280-99b8-11e9-8186-3c8a3a3772c8.png)

**Comment by vlandau** [comment] 2019-06-28 22:28
Sounds like it's all fixed up then. I just reopened the issue since I was able to produce the same problem with something other than `1:4`, so wanted to make sure the patch fixed that as well. I'm not running  the preview release since I'm using the rocker/tidyverse Docker container as a development environment. I'll go ahead and close the issue again. Thanks!

**Comment by kevinushey** [comment] 2019-07-23 21:04
Looks like the issue still manifests in some cases -- for example:

```
> df <- iris
> .rs.hasAltrep(df)
[1] TRUE
```

But the arrow is still not displayed:

![Screen Shot 2019-07-23 at 2 04 14 PM](https://user-images.githubusercontent.com/1976582/61747474-c83ee780-ad52-11e9-9767-ecdb137602b5.png)

**Comment by kevinushey** [comment] 2019-07-23 21:06
See also:

https://github.com/rstudio/rstudio/issues/4758, https://github.com/rstudio/rstudio/pull/4764

**Comment by jmcphers** [comment] 2019-07-23 21:26
@kevinushey Are you seeing that in 1.2 or 1.3? The change to make ALTREPs previewable is currently only in 1.3 (but based on feedback here and on the community forum I think we should backport to 1.2).

https://github.com/rstudio/rstudio/pull/4764

**Comment by kevinushey** [comment] 2019-07-23 21:31
Doh; you're right! For some reason I thought we had already backported this to v1.2.

**Comment by kevinushey** [comment] 2019-07-23 21:32
(and I would agree it's worth backporting as this has been surprising for a large number of users)

**Comment by jmcphers** [comment] 2019-07-23 22:05
Backported to 1.2-patch in https://github.com/rstudio/rstudio/commit/ea77107b365fa50d57345895785827a7af743051.

**Closed by jmcphers** 2019-07-23 22:05 UTC
