### ISSUE TITLE
Rstudio console is very slow printing large lists when Limit Visible Console Output is on

### ISSUE THREAD

**Issue by gorkang** [rstudio/rstudio#9376] opened 2021-05-19 17:25 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1712
    OS Version      : Ubuntu 20.04
    R Version       : 4.0.5

### Steps to reproduce the problem
```
library(dplyr)

create_vector <- function(N) {
  
  1:N %>% 
    purrr::map(~
                 {c(runif(N, min = 0, max = 100), 
                    runif(N, min = 0, max = 100))
                 })
}

VECTOR = create_vector(N = 500)
VECTOR
```
### Describe the problem in detail

When printing a large list in the console, Rstudio becomes unresponsive for a long time. Running the example above in a AMD Ryzen 2700x with 24GB of RAM takes the console >25 seconds to become responsive the first time is run, and >40 seconds the second run. Once I run the `VECTOR` line, there is no way to stop printing the list (the STOP icon is greyed out, and the escape key does not seem to do anything). After printing this kind of long lists, RStudio feels less responsive.

The same code in R in a GNOME Terminal (outside RStudio) takes ~2 seconds in the first and second runs.

### Describe the behavior you expected

The RStudio console being as fast/responsive as outside RStudio when printing large lists.

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2021-05-20 13:41
@gorkang Thank you for raising this! I can reproduce this in multiple environments. However, can you check what happens if you uncheck <kbd>Tools -> Global Options -> Console -> Limit visible console output</kbd>? For me, the output in the console is speedy then.

Reproduced with the example above, as well as with `print(nycflights13::flights, n = 2000)` in:
- RStudio Desktop 1.4.1106  and 1.4.1712 on MacOS 11.3
- RStudio Desktop 1.4.1106 on Ubuntu 20.04
- RStudio Server 1.4.1695 on Red Hat 8.3 via Chrome on MacOS 11.3

This works correctly:
- In RStudio Desktop 1.3.1093 on MacOS 11.3
- If "Limit visible console output" is unchecked

**Comment by kevinushey** [comment] 2021-05-20 17:54
I can confirm that re-running that initial code chunk multiple times causes the IDE to become much more sluggish. In particular, all future command executions (even just submitting an empty line) take a second or two to process. However, clearing the console (with Ctrl + L) does resolve it.

That same sluggishness does not occur with "Limit console output" disabled.

**Comment by CoryMcCartan** [comment] 2021-05-20 18:56
Can confirm this has worsened in 1.4.1711 and extends even to small data.frames.  E.g. if I run `mtcars` in a clean session there is a noticeable lag, increasing to at least a second if I repeat this 10-15 times.

**Comment by CoryMcCartan** [comment] 2021-05-20 20:46
@jmcphers it was 1.3.1093 (or at least whichever version of 1.3 was the public download version in early Feb 2021).
There, I just observed a slowdown in REPL speed when the total console length got very long, which could be fixed with a Ctrl-L.

When I upgraded to 1.4.1711 I also switched to a native arm (M1) build of R 4.1 rather than the intel/rosetta R 4.0.3

**Comment by jmcphers** [comment] 2021-05-20 21:54
Looks like this is a (the?) hot codepath:

https://github.com/rstudio/rstudio/blob/96d655e6788853ad5e2b7406cffc1d6e074fbc5a/src/gwt/src/org/rstudio/core/client/virtualscroller/virtualscroller.js#L278-L293

![image](https://user-images.githubusercontent.com/470418/119053571-19ce5280-b97b-11eb-967a-0c9709568afd.png)

The scroll computations were introduced here:

https://github.com/rstudio/rstudio/pull/8623/commits/3c8f5b44bc92e77d8e53e25ebff2e61938bc53ae

**Comment by PMassicotte** [comment] 2021-05-21 17:09
I have experimented the same issue with very laggy console. Unchecking the limits on printed line number fixed it.

**Comment by ronblum** [comment] 2021-05-24 20:25
Confirmed that "Limit visible console output" is unchecked/false by default in
- RStudio Desktop 1.4.1716 on MacOS 11.3
- RStudio Server 1.4.1716 on Red Hat 8.3 using Chrome on MacOS 11.3

using a brute force approach of clearing out all user preferences with <kbd>Help -> Diagnostics -> Clear User Prefs </kbd>.

**Comment by rich-rstudio** [comment] 2021-06-03 21:47
verified on Version 1.5.64

**Closed by rich-rstudio** 2021-06-03 21:47 UTC
Labels: bug, console, test
