### ISSUE TITLE
Strange popups on RStudio

### ISSUE THREAD

**Issue by njtierney** [rstudio/rstudio#3065] opened 2018-06-25 06:05 UTC
### System details

    RStudio Edition : Desktop 
    RStudio Version :  1.1.453
    OS Version      :  Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3
    R Version       :  R version 3.5.0 (2018-04-23)

### Steps to reproduce the problem

I have taken a screenshot, I can't exactly replicate the problem - @kevinushey suggested that submitting this screenshot with some info would be used

### Describe the problem in detail

When I am working on say an R package ([naniar](https://github.com/njtierney/naniar)), I get some floating boxes that look like linting errors, or help/autocomplete floating text boxes
![rstudio-strange-popups](https://user-images.githubusercontent.com/6488485/41832887-652795bc-7891-11e8-81db-72f61386b962.png)

### Describe the behavior you expected

I expect no strange floating boxes

**Comment by kevinushey** [comment] 2018-06-25 15:44
I've definitely seen these before (from what I've seen, this can be caused by RStudio erroneously popping up the signature tooltip for an editor in a different tab that is no longer in focus). Thanks for the bug report!

**Comment by kevinushey** [comment] 2018-06-25 18:32
I believe this may actually be a duplicate of https://github.com/rstudio/rstudio/issues/2400, and should be fixed (or at least mitigated) through https://github.com/rstudio/rstudio/commit/d11d93702cc70f2c93e7338e9c017cf1046d79c0. If you get a chance, can you test-drive the [preview release](https://www.rstudio.com/products/rstudio/download/preview/) and let us know if you're still encountering this issue?

**Comment by kevinushey** [comment] 2018-07-02 21:39
I'm going to mark this as resolved -- @njtierney please re-open if you bump into the issue again. Thanks for testing!

**Closed by kevinushey** 2018-07-02 21:39 UTC
Labels: bug

**Comment by njtierney** [comment] 2018-07-03 14:30
Heya, it looks to be all solved now, thanks! :)

Looking forward to upcoming RStudio releases!
