### ISSUE TITLE
dial back shiny 1.6.0 requirement

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10230] opened 2021-12-10 20:37 UTC
RStudio took a dependency on shiny 1.6.0, as part of https://github.com/rstudio/rstudio/pull/9847. This was done to accommodate the latest releases of the `rmarkdown` package, which requires `shiny (>= 1.6.0)`, although only as a suggested dependency (for documents with `runtime: shiny`).

Unfortunately, this can cause issues for IDE users who are running shiny applications, but not using R Markdown at all, as we do not separate version requirements for different IDE features based on the feature set. In other words, projects using older versions of shiny which are otherwise functional would be forced to update, which would be frustrating for users not prepared to update the versions of R packages used in their projects.

The simplest path forward here is likely (articulated by @jjallaire):

1. Relax the dependency on Shiny 1.6.0 in the IDE,
2. Enforce that version constraint at runtime only in R Markdown documents using Shiny features (e.g. for `runtime: shiny`).

IMHO we should take this for PT as this is almost surely going to effect a large number of users -- shiny 1.5.0 is only 1.5 years old, and is likely used by many users running older versions of R.

**Comment by jjallaire** [comment] 2021-12-10 20:49
Yes definitely. I think the carnage will be pretty bad (as evidenced already by some customers articulate complains) if we leave this alone. At a minimum we can just dial the Shiny version dependency back (the bit about dynamically asking for a higher version of shiny for `runtime: shiny` is only a nice to have -- if that's too complicated for PT that shouldn't keep us from taking the simple change to our baseline shiny version).

**Comment by jmcphers** [comment] 2021-12-10 20:52
Change https://github.com/rstudio/rstudio/pull/9847 included many package dependencies that were necessitated by the Shiny 1.6 change, several of which have also been tough for customers to update. I think the approach to fixing this should be to unwind https://github.com/rstudio/rstudio/pull/9847 altogether, and then reapply only the changes relevant to rmarkdown.

**Comment by mikebessuille** [comment] 2021-12-14 18:12
@jmcphers i'm tempted to beg you to take care of this mess for us...

**Comment by jmcphers** [comment] 2021-12-20 18:30
Instructions for fixing this:

1. Git revert all changes in https://github.com/rstudio/rstudio/pull/9847.
2. Bump rmarkdown dependency back to 2.10.
3. Update all rmarkdown package dependencies in `r-packages.json`, such that each package in rmarkdown 2.10's `Dependencies` list has an entry in `r-packages.json` with a sufficient version... *except* Shiny.
4. For extra credit, add a special case to look for an updated Shiny version when running Shiny R Markdown content.

**Comment by kevinushey** [comment] 2021-12-20 18:54
One other thing worth checking:

1. Do `shiny` and `rmarkdown` have any shared dependencies?
2. Could bumping the version of that dependency inadvertently force us to require a new version of `shiny`?

**Comment by kevinushey** [comment] 2022-01-10 18:56
For testing, we should confirm that users can use shiny 1.5.0 to run a Shiny application within the RStudio IDE.

I believe something like the following should be sufficient:

```
# in a clean session
remotes::install_version("shiny", "1.5.0")

# restart R, then try to run the 'default' shiny application
```

**Comment by kevinushey** [comment] 2022-01-10 18:58
Also: will this change need to be backported?

**Comment by jmcphers** [comment] 2022-01-10 19:02
I think we should backport it to Ghost Orchid since that's when the offending change was introduced.

**Comment by ronblum** [comment] 2022-01-10 21:42
Marking as `triage` to consider for backport.

**Comment by R-Hannibal** [comment] 2022-01-10 22:06
@jmcphers - how urgent is the need to backport this fix? 

Sadly from a timing perspective, we just got the 2021.09.2 patch out, so we'll have to do a new GO patch to backport this one.

**Comment by jmcphers** [comment] 2022-01-10 22:11
I think we should start a new patch for GO, and put this change in it, but no urgency to actually release. GO will be receiving patches into 2023, so there will almost certainly be a train it can ride on!

**Comment by mikebessuille** [comment] 2022-01-11 13:51
@romainfrancois when this is working in main, please backport it to the Ghost Orchid branch ("release-ghost-orchid")

**Comment by ronblum** [comment] 2022-01-12 21:11
Verified in Prairie Trillium using the default Shiny app. Also trying out Several public Shiny apps from https://shiny.rstudio.com/gallery, as well; I'll update when I'm done with that.

**Comment by ronblum** [comment] 2022-01-13 17:12
[Checked that nothing went awry with a few Shiny gallery apps https://shiny.rstudio.com/gallery/india-blood-banks.html and https://github.com/dreamRs/memory-hex, but these tests weren't relevant.]

Verified in
- RStudio Desktop 2022.02.0+366 on MacOS 12.1
- RStudio Server 2022.02.0+366 on Ubuntu 20.04.3 via Chrome on MacOS

Main tests were 
- With `shiny` 1.5.0 installed, creating a new Shiny app doesn't prompt for an update to a more recent version of `shiny`.
- With `shiny` removed, creating a new Shiny app prompts for installation to the latest version of `shiny` (1.7.1).
- With `shiny` 1.5.0 installed and `rmarkdown` removed, creating a new R Markdown file prompts for installation to the latest version of `rmarkdown` (2.11) but leaves `shiny` intact at 1.5.0.

However, when using `runtime: shiny` in an R Markdown document, there's no longer a prompt to update the latest version of `shiny`. Should we be prompting for this, as we did previously?

**Comment by ronblum** [comment] 2022-01-13 17:42
Confirmed (offline) that this is the expected behavior. Verified that the default file created with
<kbd>File -> New File -> R Markdown -> Shiny -> Shiny Document</kbd>
runs successfully on `shiny` 1.5.0.

**Closed** 2022-01-13 17:42 UTC
Labels: enhancement, shiny, r markdown, backport

**Comment by xavidp** [comment] 2022-02-09 08:58
Hi. sorry to jump in the thread at this time (I've just been aware of it), but I reckon I shall add some extra information.

We had some complex shiny app running on shiny 1.4.1, just a couple of years old or so, and we were attempting to use it in a few-months-old upgraded RStudio Server (2021.09.0 Build 351) in our development infrastructure in our organization, as I reported in a separate thread:
https://community.rstudio.com/t/update-of-rstudio-server-forces-shiny-update-even-if-renv-is-enabled-how-to-avoid/128542/4

I recently found out that I could upgrade the needed packages one by one to the minimum new version (from their own package history, one by one, shown in CRAN), and I found out that our critical issue (at least in our case) came not from upgrading shiny to the latest version 1.7.1., but from the related dependencies that were also upgraded to the latest possible version, when it seems that it was not needed to have them to the latest version (specially rlang, I guess). and this was the winning recipe in our case:

```
# while having renv enabled in the project
install.packages("devtools")
devtools::install_version("digest", version="0.6.25") # and answer NO to upgrade the other dependent packages offered to upgrade
devtools::install_version("rlang", version="0.4.10") # and answer NO to upgrade the other dependent packages offered to upgrade
devtools::install_version("fastmap", version="1.1.0") # and answer NO to upgrade the other dependent packages offered to upgrade
devtools::install_version("htmltools", version="0.5.2") # and answer NO to upgrade the other dependent packages offered to upgrade
devtools::install_version("shiny", version="1.7.0") # and answer NO to upgrade the other dependent packages offered to upgrade
```
This way, we were able to have our complex and oldish shiny app running pretty smoothly (just some warning of deprecated font awesome icons, but no errors).

Therefore, **I wonder if there would be some way to relax also the package dependencies from the new shiny package that RStudio Server seems to bring altogether** when the user clicks at "Yes" in the popup from RStudio indicating that you need to ugprade the "shiny" package in order to launch the shiny app from within RStudio Server UI.
