### ISSUE TITLE
Javascript exception from clicking spellcheck button

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#5496] opened 2019-10-02 16:27 UTC
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.3.479
    OS Version      : macOS 10.14.6, Windows-10
    R Version       : 3.6.0

### Steps to reproduce the problem
- File / New File / Text File
- Type "Hello world"
- Click on spell-check button in editor toolbar

### Describe the problem in detail
![2019-10-02_09-25-13](https://user-images.githubusercontent.com/10569626/66062617-99818200-e4f6-11e9-8ba9-38843742fa04.png)

### Describe the behavior you expected
- no error

**Comment by adamconroy** [comment] 2019-10-02 17:21
Dupe of https://github.com/rstudio/rstudio/issues/5348

**Comment by adamconroy** [comment] 2019-10-04 19:56
https://github.com/rstudio/rstudio/commit/3680e8c7f29fd836dd0439cc45c5c634ca07a240 Default text files don't return a scope. Might be worth considering if we want to actively spell check these documents as well, though likely much less value than Rmd/R files.

**Closed by adamconroy** 2019-10-04 19:56 UTC
