### ISSUE TITLE
RStudio IDE 2021.09.1 Build 372 for Mac OSX Monterey 12.1: Global Find with regular expressions does not work with `+` operator 

### ISSUE THREAD

**Issue by yogat3ch** [rstudio/rstudio#10499] opened 2022-02-03 18:53 UTC
[Original thread](https://community.rstudio.com/t/rstudio-ide-2021-09-1-build-372-for-mac-osx-monterey-12-1-global-find-with-regular-expressions-does-not-work-with-operator/127560)

### System details

    RStudio Edition : Ghost Orchid
    RStudio Version : 2021.09.1 Build 372
    OS Version      : Mac OSX Monterey 12.1
    R Version       : 4.1.2

### Steps to reproduce the problem
Screen recording in thread
### Describe the problem in detail
See thread
### Describe the behavior you expected
`+` operator matches one or more of preceding token

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MariaSemple** [comment] 2022-02-03 18:59
Thank you for reporting this issue. I believe it is a duplicate of #9344 and a fix should be available in a future release. You can download and try builds of that release here: https://dailies.rstudio.com/rstudio/spotted-wakerobin/. If that does not contain the fix, please update the issue again and I will re-open.

**Closed by MariaSemple** 2022-02-03 18:59 UTC

**Comment by yogat3ch** [comment] 2022-02-03 20:06
Yep, from the looks of [this comment](https://github.com/rstudio/rstudio/issues/9344#issuecomment-1021442738) it looks like y'all are on it already. Thank you!
