### ISSUE TITLE
autoComplete suggests non-exported functions; help fails

### ISSUE THREAD

**Issue by EmilBode** [rstudio/rstudio#2348] opened 2018-03-08 13:09 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.423 (also on 1.1.383)
    OS Version      : OSX 10.13.3
    R Version       : 3.4.3 (also 3.4.2)

### Steps to reproduce the problem
- load the 'rJava' library
- In either the console or Source pane, type 'dupli', and wait until the autocomplete box appears.
With 'duplicated      {rJava}' selected, press F1

### Describe the problem in detail
No help screen is produced, instead an error is generated:

Error in find.package(if (is.null(package)) loadedNamespaces() else package,  : 
  there is no package called ‘package:rJava’

Furthermore, the autocomplete suggestion box displays 'duplicated          {rJava}'

### Describe the behavior you expected
In the autocomplete box, it should display 'duplicated              {base}', and after pressing F1 I expect the man page to display

### Generalisation
It's interesting to note that the rJava package has a function 'duplicated', but it's not exported (and therefore doesn't mask base::duplicated, but also doesn't provide a man page).
I have a gut feeling that there may be the problem: RStudio detects there is a function duplicated outside base, but doesn't note it's not exported, and that the man page fails to load because the non-exported function can't be reached

**Comment by ronblum** [comment] 2018-03-08 17:09
[Note: reproduced on Fedora desktop and Ubuntu server.]

**Comment by kevinushey** [comment] 2018-03-08 23:02
Thanks for the bug report! This is a strange one -- it looks like `rJava` _does_ provide a function called `duplicated`, and exports it. This is what I see on macOS 10.13.3, R 3.4.3, rJava 0.9-9:

```
> rJava::duplicated
standardGeneric for "duplicated" defined from package "base"

function (x, incomparables = FALSE, ...) 
standardGeneric("duplicated")
<environment: 0x10f0d5c30>
Methods may be defined for arguments: x, incomparables
Use  showMethods("duplicated")  for currently available ones.
```

You can see this for other S4 generics that `rJava` requests definitions for, e.g. `unique`:

```
> rJava::unique
standardGeneric for "unique" defined from package "base"

function (x, incomparables = FALSE, ...) 
standardGeneric("unique")
<environment: 0x10270f6a0>
Methods may be defined for arguments: x, incomparables
Use  showMethods("unique")  for currently available ones.
```

Because `rJava` is attached, the definition it provides is found first:

```
> getAnywhere("duplicated")
2 differing objects matching 'duplicated' were found
in the following places
  package:rJava
  package:base
  namespace:base
  namespace:rJava
```

Note that the `base` definition is indeed 'masked', e.g.

```
> base::duplicated
function (x, incomparables = FALSE, ...) 
UseMethod("duplicated")
<bytecode: 0x102dbe6a8>
<environment: namespace:base>
```

However, even though the S4 generic is discovered from the `rJava` namespace, I think it might be more sensible for us to show the package from which it was defined ('base'), rather than the package from where it currently exists.

However, the fact that it fails to provide help is indeed an error!

**Comment by jmcphers** [comment] 2019-12-06 05:08
Should be fixed by https://github.com/rstudio/rstudio/commit/af336055dafdf58bca82264aaf8688d1f8d4c0f5.

**Closed by jmcphers** 2019-12-06 05:08 UTC
Labels: bug, reproducible
