### ISSUE TITLE
Polish keyboard won't work

### ISSUE THREAD

**Issue by tygrysuav** [rstudio/rstudio#7668] opened 2020-08-27 18:15 UTC
### System details

    RStudio Edition : 
    RStudio Version :  1.3.1073
    OS Version      :  Windows 10
    R Version       :  4.0.2

### Describe the problem in detail

There is a problem with the Polish keyboard in the latest version of RStudio when adding script comments.. Right Alt + letter does not work for most characters. 

### Describe the behavior you expected

For example: right Alt + L does nothing but should insert the appropriate character which is Ł.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by modeldev** [comment] 2020-08-27 23:38
Hi,

I confirm this problem. There are keyboard shortcuts conflicting with typing in Polish. Most of these shortcuts can be manually modified using "Tools"->"Modifiy Keyboard Shortcuts", but except shortcut: "Fold Selected": Alt+L

This one doesn't appear in "Modifiy Keyboard Shortcuts"  window and adding row:
  "foldSelected": "",
to the file "editor_bindings.json" has also no effect. I have no idea how to solve this (the only and very inconvinient way to input "ł" is to press Caps Lock and and Shift+left Alt+L)

Best, 
Piotr

**Comment by kadyb** [comment] 2020-09-02 16:32
This problem is also mentioned in #6973.

**Comment by mbojan** [comment] 2020-10-22 12:36
See also #6236. I just tested daily build RStudio Desktop 1.4.959 on Windows 10 and the problem seems gone. Interestingly, it does not happen on RStudio **Server** 1.3.1093.

(i need RStudio for teaching so I keep fingers crossed that the daily build will not be broken in some other essential aspect...) Thanks!

**Comment by kalimu** [comment] 2021-02-12 07:48
Hi all, any chance that the problem will be finally resolved? In the releases version 1.4 of RStudio Desktop the problem is still present. Basically, that means that users who want to use polish characters have to use version 1.2.5042.

**Comment by mbojan** [comment] 2021-02-12 10:01
@kalimu all seems OK in RStudio 1.4.1103 (under Ubuntu and Windows 10).

**Comment by kadyb** [comment] 2021-02-12 11:04
I can confirm that this is fixed on RStudio 1.4.1103 and Windows 8.1 too.

**Comment by kalimu** [comment] 2021-02-12 15:31
Ohh yes! Indeed it works with this version. I was misled by this issue still open. Many thanks guys for letting me know!

**Comment by mbojan** [comment] 2021-02-12 15:50
I think this can be closed.

**Comment by modeldev** [comment] 2021-02-14 16:44
I confirm, that the problem is no longer existing in 1.4.1103, Windows 10.

**Comment by mbojan** [comment] 2021-10-13 15:44
Indeed, already resolved, similarly to #6973 (which seems a duplicate). Can be closed.

**Closed** 2021-12-07 18:13 UTC
Labels: key bindings
