### ISSUE TITLE
Run all chunks above fails when non R chunks are present

### ISSUE THREAD

**Issue by thothal** [rstudio/rstudio#11995] opened 2022-09-21 08:52 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.0 Build 548
    OS Version      :  Win 10
    R Version       : 

### Steps to reproduce the problem

Consider the following Rmarkdown:

````
---
title: "Non R Chunks Prevent Run All"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{css css-chunk, echo = FALSE}
.sql {
  background-color: #cdd9ef;
}
```

```{r myconsts}
a <- 1
```

```{sql sql-chunk, connection = DBI::dbConnect(RSQLite::SQLite())}
SELECT 1
```

```{r r-chunk}
a + 1
```
````

Now press the `Run all Chunks above` button in the last r chunk:

![image](https://user-images.githubusercontent.com/30824940/191456950-071d57e0-b046-4aad-9431-b2347a6cff2a.png)

### Describe the problem in detail

The first non `R` chunk (i.e. the `CSS` chunk) will (naturally) fail with an error in the console, stopping all the other chunks to run. If I remove the `CSS` chunk, `Run all...` will trip over the  `SQL` chunk.

![image](https://user-images.githubusercontent.com/30824940/191458487-a0db34a5-a85a-4998-b290-2f649d0e82d0.png)

### Describe the behavior you expected

I think it is a natural workflow to run the R code in the console once in a while to some quick checks without the need to re-render the whole document. Any non `R` chunk prevents me from using the `Run all Chunks above` button, which is annoying as I have now to run all R chunks manually. I would expect that any non R chunk is excluded from `Run all Chunks above` by default, or at least a chunk option with which I could manually exclude certain chunks from being considered in the `Run all`. Another viable solution would be to be able to tell Rstudio to continue on error nevertheless. 

*N.B.* An `eval = FALSE` chunk option allows me to use the `Run all...` button, but then, well, the chunk is not evaluated when rendering. Clearly not what I want.

Interestingly enough, if I decide to output inline,, I can at least run the chunks.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment] 2022-09-21 20:03
@thothal Thank you for raising this! I believe this is the expected behavior, though: <kbd>Run All Chunks Above</kbd> should execute all chunks, not just R chunks. For example, this code includes both R and Python:

````
```{r myconsts}
print("First R chunk")
```

```{python}
print("Python chunk")
```

```{r r-chunk}
print("Second R chunk")
```
````

With the cursor in the third chunk, both the R and Python chunks above it run:
<img width="673" alt="runallabove" src="https://user-images.githubusercontent.com/31009952/191598790-6de62b93-f6bf-4001-a233-8b1eb721c358.png">

**Comment by cderv** [comment] 2022-09-22 08:41
@ronblum I believe the issue really is that the `css` chunk should not be run. It does not even have a run button 
![image](https://user-images.githubusercontent.com/6791940/191700539-ffebc46d-b0e0-4d8b-83f1-cf95ec175fc3.png)

So probably `Run all Chunk above ` should skip it. 🤔

**Comment by jgutman** [comment] 2022-11-17 17:20
It appears the CSS chunk does not run with Run All or Run All Chunks Above, so I believe that part of the issue has been resolved. The SQL issue still stands, and interferes with subsequent chunk execution, but the SQL issue is a duplicate of https://github.com/rstudio/rstudio/issues/6769 

This is in version 2022.12.0-preview+330. Closing this issue in preference to #6769, but please comment again if you believe the CSS issue persists -- on my end the CSS does not get executed/evaluated in console mode.

**Comment by DesiQuintans** [comment] 2022-12-07 08:15
I still get this issue with CSS chunks in RStudio 2022.07.2 Build 576 (newest available) on Windows 11 64-bit.

I can reproduce it by creating a new RMarkdown doc with the default template (New File > RMarkdown > Okay), inserting this CSS chunk above the setup chunk:

    ```{css, echo=FALSE}
    body {font-family: "Atkinson Hyperlegible" !important; font-size: 13pt !important; }
    pre {font-family: "Hack" !important; font-size: 12pt !important; }
    ```
    
And then using Run All Chunks Above from the `cars` R chunk.

    ## Error: unexpected '{' in "body {"

Knitting the Rmd to a HTML page works fine. It's just Run All Chunks Above that does not.

**Comment by cderv** [comment] 2022-12-07 14:28
@DesiQuintans it is probably best to open a new issue and link to a close one so that it is triaged correctly. 

@ronblum should we create a new issue from this or is it ok to reopen here if the issue is confirmed by you ?

**Comment by ronblum** [comment] 2022-12-07 15:27
Let's reopen this so that we have the history, and I'll add it to the RStudio IDE project. That said, I don't think I'm seeing the same problem; I tried in RStudio Desktop 2022.07.0+548 on both Windows 11 and MacOS 13. It looks like the `css` chunk might have run—even though it shouldn't have—since it's got a blank output? 

<img width="672" alt="css_run_all_above" src="https://user-images.githubusercontent.com/31009952/206220139-28f490f4-9278-4ba3-90dd-c35877ae02e9.png">

**Comment by DesiQuintans** [comment] 2022-12-07 23:53
>It looks like the css chunk might have run—even though it shouldn't have—since it's got a blank output?

I forgot to mention that, like the OP in this thread, I also have "Chunk Output In Console" turned on. The error `Error: unexpected '{' in "body {"` shows up in my console, whereas for you it seems to have invisibly done something wrong instead?

**Comment by ronblum** [comment] 2022-12-08 13:17
@DesiQuintans Thank you! I switched to console output and can reproduce what you're seeing perfectly.

**Comment by mikebessuille** [comment] 2022-12-12 15:38
@jgutman do you plan to address this with notebook mode changes you're looking at?

**Comment by jgutman** [comment] 2022-12-12 15:43
I did close it for that reason, but Ron reopened it because he had reproduced the issue, which I hadn't, so I was going to re-check it

**Comment by ronblum** [comment] 2024-02-26 15:54
Another example, from @gegznaV in issue #14324:
````
```{r}
```

```{css}
/* Some CSS comment */
```

```{r}
1 + 2
```

```{r}

```
````

**Comment by ronblum** [comment] 2024-02-29 19:11
Possible solution: in console mode, only execute R chunks

**Comment by victorfeagins** [comment] 2024-04-19 00:08
Any updates on this? For me this is only an issue when output goes to the console instead of inline.

**Comment by kevinushey** [comment] 2024-04-20 17:25
We're planning to investigate this for the next release.

**Comment by gadenbuie** [comment] 2024-05-17 19:43
Another example, using a custom knitr engine as reported in https://github.com/gadenbuie/epoxy/issues/126

````
---
output: html_document
---

```{setup}
library(epoxy)
```

```{epoxy}
The average speed of the cars was **{mean(cars$speed)} mph.**
```
````

The above document knits correctly, but clicking Run All returns Error: `unexpected symbol in "The average"`

**Comment by ronblum** [comment] 2024-09-16 18:32
Verified in RStudio Desktop 2024.09.0+372 on Windows 11 using multiple examples from above.

**Closed by ronblum** 2024-09-16 18:32 UTC
Labels: bug, reproducible, notebook mode
