### ISSUE TITLE
cannot install udunits in rstudio despite possible from the regular R console

### ISSUE THREAD

**Issue by lduvaux** [rstudio/rstudio#5836] opened 2019-12-05 14:53 UTC
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5019.r1893-1
    OS Version      : manjaro 18.1.3
    R Version       : 3.6.1-1 (2019-07-05)

### Steps to reproduce the problem
all system details being equal:
1. install udunits2 in the R console (terminal) (manjaro OS) --> it works
```
[ludo@garuda ~]$ R

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> remove.packages("udunits2")
Removing package from ‘/home/ludo/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
> install.packages("udunits2")
Installing package into ‘/home/ludo/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://ftp.igh.cnrs.fr/pub/CRAN/src/contrib/udunits2_0.13.tar.gz'
Content type 'application/octet-stream' length 67182 bytes (65 KB)
==================================================
downloaded 65 KB

* installing *source* package ‘udunits2’ ...
** package ‘udunits2’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking udunits2.h usability... yes
checking udunits2.h presence... yes
checking for udunits2.h... yes
checking for ut_read_xml in -ludunits2... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
gcc -I"/usr/include/R/" -DNDEBUG   -D_FORTIFY_SOURCE=2  -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -c udunits2_R.c -o udunits2_R.o
gcc -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o udunits2.so udunits2_R.o -ludunits2 -lexpat -lexpat -ludunits2 -L/usr/lib64/R/lib -lR
installing to /home/ludo/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-udunits2/00new/udunits2/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (udunits2)

The downloaded source packages are in
	‘/tmp/RtmpksFn3T/downloaded_packages’
> 
```

2. try to install udunits2 in rstudio --> that does not work:
```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> library(udunits2)
Error: package or namespace load failed for ‘udunits2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/ludo/R/x86_64-pc-linux-gnu-library/3.6/udunits2/libs/udunits2.so':
  libudunits2.so.0: cannot open shared object file: No such file or directory
> install.packages("udunits2")
Installing package into ‘/home/ludo/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/udunits2_0.13.tar.gz'
Content type 'application/x-gzip' length 67182 bytes (65 KB)
==================================================
downloaded 65 KB

* installing *source* package ‘udunits2’ ...
** package ‘udunits2’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking udunits2.h usability... yes
checking udunits2.h presence... yes
checking for udunits2.h... yes
checking for ut_read_xml in -ludunits2... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
gcc -I"/usr/include/R/" -DNDEBUG   -D_FORTIFY_SOURCE=2  -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -c udunits2_R.c -o udunits2_R.o
gcc -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o udunits2.so udunits2_R.o -ludunits2 -lexpat -lexpat -ludunits2 -L/usr/lib64/R/lib -lR
installing to /home/ludo/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-udunits2/00new/udunits2/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘udunits2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/ludo/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-udunits2/00new/udunits2/libs/udunits2.so':
  libudunits2.so.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/ludo/R/x86_64-pc-linux-gnu-library/3.6/udunits2’
Warning in install.packages :
  installation of package ‘udunits2’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp2gFHIh/downloaded_packages’
> 
```

### Describe the problem in detail
see above sections for symptoms.
I installed the udunits lib from sources and it is properly found by R when using the R console.
Rstudio does not seems to find it as shown by the following message:
```
 unable to load shared object '/home/ludo/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-udunits2/00new/udunits2/libs/udunits2.so':
  libudunits2.so.0: cannot open shared object file: No such file or directory
```
For all programs/libs involved I have only a single  installation (R, rstudio, udunits2) all performed by the OS tools (no conda or other package manager not designed specifically for the OS).
* R was installed using pacman (pacman -S r)
* rstudio using yaourt 
* the udunits lib from the sources
 

### Describe the behavior you expected
I expect rstudio to be able to install udunits as do the regular R.

### Other information
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.7.so
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1   
> 
```

**Comment by kevinushey** [comment] 2019-12-05 17:03
I'm guessing this is caused by a difference in some environment variables (`LD_LIBRARY_PATH`?) between your terminal R and RStudio R sessions.

Where is the `libudunits2.so.0` library actually located on your machine?

**Comment by lduvaux** [comment] 2019-12-06 09:20
The `libudunits2.so.0` lib is located in `/usr/local/lib/`. I have no idea if this the standard location for this lib (was the folder suggested by the `udunits2` manual). Actually for some reasons (address not found by curl apparently), I was not able to install `udunits2` using my regular package manager.

Concerning my `$LD_LIBRARY_PATH`, here the list:
```
[ludo@garuda ~]$ echo $LD_LIBRARY_PATH 
:/usr/lib/:/usr/local/lib:/usr/local/include
```
I did not know that RStudio would use another `$LD_LIBRARY_PATH` than the one of my global env. Where should/could I modify that? Many thanks in advance.

**Comment by kevinushey** [comment] 2019-12-06 17:44
What is the output of `Sys.getenv("LD_LIBRARY_PATH")` in your RStudio R session?

**Comment by lduvaux** [comment] 2019-12-06 17:50
```
> Sys.getenv("LD_LIBRARY_PATH")
[1] "/usr/lib64/R/lib::/lib:/usr/lib/jvm/java-7-openjdk/jre/lib/amd64/server"
```
Indeed, the folders `/usr/lib/:/usr/local/lib:/usr/local/include` are not in there. Should I create some symlinks or can I add the folders of my global "LD_LIBRARY_PATH" to the RStudio "LD_LIBRARY_PATH"? If the later, how can I do that?
Many thanks for your help in any case.

**Comment by kevinushey** [comment] 2019-12-06 17:52
It should be sufficient to set `LD_LIBRARY_PATH` in e.g. a startup `.Renviron` file (see `?Startup` for more details). E.g. you could set in a file at `~/.Renviron`:

```
LD_LIBRARY_PATH = :/usr/lib/:/usr/local/lib:/usr/local/include
```
```

**Comment by lduvaux** [comment] 2019-12-09 10:12
Setting the `~/.Renviron` fixed the installation problem, however when I try to load the `udunits2` library, I still have an error message concerning the `libudunits2.so.0`
```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> install.packages("udunits2")
Installing package into ‘/home/ludo/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/udunits2_0.13.tar.gz'
Content type 'application/x-gzip' length 67182 bytes (65 KB)
==================================================
downloaded 65 KB

* installing *source* package ‘udunits2’ ...
** package ‘udunits2’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking udunits2.h usability... yes
checking udunits2.h presence... yes
checking for udunits2.h... yes
checking for ut_read_xml in -ludunits2... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
gcc -I"/usr/include/R/" -DNDEBUG   -D_FORTIFY_SOURCE=2  -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -c udunits2_R.c -o udunits2_R.o
gcc -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o udunits2.so udunits2_R.o -ludunits2 -lexpat -lexpat -ludunits2 -L/usr/lib64/R/lib -lR
installing to /home/ludo/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-udunits2/00new/udunits2/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (udunits2)

The downloaded source packages are in
	‘/tmp/Rtmp1iqGlg/downloaded_packages’
> library(udunits2)
Error: package or namespace load failed for ‘udunits2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/ludo/R/x86_64-pc-linux-gnu-library/3.6/udunits2/libs/udunits2.so':
  libudunits2.so.0: cannot open shared object file: No such file or directory
> Sys.getenv("LD_LIBRARY_PATH")
[1] ":/usr/lib/:/usr/local/lib:/usr/local/include:/usr/lib64/R/lib:/lib:/usr/lib/jvm/java-7-openjdk/jre/lib/amd64/server"
```
Yet, the `libudunits2.so.0` file is realy in the rstudio `LD_LIBRARY_PATH`:
```
[ludo@garuda ~]$ locate libudunits2.so.0
/usr/local/lib/libudunits2.so.0
/usr/local/lib/libudunits2.so.0.1.0
[ludo@garuda ~]$ 
```
Any idea what's going on?

**Comment by jmcphers** [comment] 2019-12-13 18:32
Sorry, we're not totally sure what's going on here, but it doesn't look like a bug in RStudio, so we're closing this issue. This is a problem you'll need to sort out by comparing the environments inside and outside RStudio (LD_LIBRARY_PATH is only one variable in play here...) to see what's causing the discrepancy. 

The next thing you might try is using `ldd` to check library resolution, and `objdump` to see if there's a version expectation mismatch. If you need further help, please try our community forum:

https://community.rstudio.com/c/rstudio-ide

**Closed by jmcphers** 2019-12-13 18:32 UTC
Labels: bug, r packages, triage
