### ISSUE TITLE
Blinking dot(s) near cursor

### ISSUE THREAD

**Issue by FluffierThanThou** [rstudio/rstudio#4822] opened 2019-05-22 07:37 UTC
### System details
    RStudio Edition : Desktop
    RStudio Version :  1.2.1335 Build 1379 (f1ac3452)
    OS Version      :  Win10
    R Version       :  3.5.2

### Steps to reproduce the problem
Using a dark theme, have an active cursor in either the editor or console (or presumably, anywhere else).

### Describe the problem in detail
There are one or more white dots on the line above the cursor, whenever the cursor is active. 
![rstudio blinking dot](https://user-images.githubusercontent.com/18528306/58155732-ca15fd00-7c74-11e9-9121-4c450d9cef6e.gif)

### Describe the behavior you expected
No blinking dots.

**Comment by pascaloettli** [comment] 2019-05-22 08:06
It is a known issue with Windows 7 (see #4390 and #4732), but not with Windows 10, AFAIK

**Comment by FluffierThanThou** [comment] 2019-05-22 08:55
Oh, I did search for open issues - I'm not sure how I didn't find those. 

Anyway, I'm encountering the issue on Win10;
![image](https://user-images.githubusercontent.com/18528306/58160492-def78e00-7c7e-11e9-91e4-0034529f8628.png)

The system has Intel® HD Graphics 4600. As of writing this, I've noticed that the installed driver is 3 years old, so I'm currently (trying to) install a newer driver to see if that resolves the problem.

The problem does disappear when I force the use of software rendering, but I was rather pleased with the (perceived) performance boost of using GPU rendering.

**Comment by FluffierThanThou** [comment] 2019-05-22 09:46
Updating to the most recent driver DELL and Intel let me install seems to have had no effect, the problem still persists (using hardware rendering).

Card & driver details;

```
Display Devices
---------------
          Card name: Intel(R) HD Graphics 4600
       Manufacturer: Intel Corporation
          Chip type: Intel(R) HD Graphics Family
           DAC type: Internal
        Device Type: Full Device
         Device Key: Enum\PCI\VEN_8086&DEV_0412&SUBSYS_05A41028&REV_06
      Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
Device Problem Code: No Problem
Driver Problem Code: Unknown
     Display Memory: 2160 MB
   Dedicated Memory: 112 MB
      Shared Memory: 2048 MB
       Current Mode: 3440 x 1440 (32 bit) (59Hz)
       Monitor Name: Generic PnP Monitor
      Monitor Model: DELL U3415W
         Monitor Id: DELA0A7
        Native Mode: 3440 x 1440(p) (59.973Hz)
        Output Type: Displayport External
        Driver Name: igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll
Driver File Version: 20.19.0015.5063 (English)
     Driver Version: 20.19.15.5063
        DDI Version: 12
     Feature Levels: 11_1,11_0,10_1,10_0,9_3,9_2,9_1
       Driver Model: WDDM 2.0
Graphics Preemption: Primitive
 Compute Preemption: Thread group
           Miracast: Not Supported by WiFi driver
Hybrid Graphics GPU: Integrated
     Power P-states: Not Supported
  Driver Attributes: Final Retail
   Driver Date/Size: 29-10-2018 02:00:00, 39863040 bytes
```

**Comment by kevinushey** [comment] 2019-05-22 16:14
You may need to fall back to software rendering -- see https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors for more details.

**Comment by ronblum** [comment] 2019-05-24 18:35
Duplicate of #4390—thank you for updating it!

**Closed by ronblum** 2019-05-24 18:35 UTC
