### ISSUE TITLE
A pane window won't keep minimised when working with Python. 

### ISSUE THREAD

**Issue by Fred-Wu** [rstudio/rstudio#5984] opened 2020-01-09 09:18 UTC
I am currently using RStudio 1.2.5036 on a Linux machine. 

I setup my Pane Layout with History alone in the lower left, so that I can minimise it when working with R, and it is kept minimised just fine. 

However, when working with Python, everytime I run some codes, that window will be triggered and un-minimised automatically. 

Is this something that can be fixed?

**Comment by ronblum** [comment] 2020-01-09 14:54
@Fred-Wu Thank you for filing the issue. Is it limited to Python, or also R code? Also, what version of R and Linux are you using?

**Comment by Fred-Wu** [comment] 2020-01-09 22:57
> @Fred-Wu Thank you for filing the issue. Is it limited to Python, or also R code? Also, what version of R and Linux are you using?

I am working with R 3.6.2 on Ubuntu 18.04. 
It is limited to Python. Working with R is fine.
However, I can confirm that windows version of RStudio has no such an issue.

**Comment by ronblum** [comment] 2020-02-05 22:19
I am also able to reproduce this in
- RStudio Desktop 1.3.776 on MacOS 10.15.3
- RStudio Server 1.3.776 on Ubuntu 18.04.3 via MacOS 10.15.3 and Windows 10

but it works fine on
- RStudio Desktop 1.3.776 on Windows 10

Also, I see this in some other panes, like Environment.

This is a duplicate of #3084, but I'll close that one since this is already tagged.

--------

From @hrbrmstr in #3084:

> Using the desktop dailies (current version for this issue 1.2.780), macOS 10.14.
> 
> I'm a "console on the right" person and have history pane minimized below the source pane since I never really use it. When processing R code it stays minimized.
> 
> When i start a python code file in a source pane tab and start executing lines the history pane always unminimizes even when I re-minimize it.
> 
> Further, when going back to an R source pane tab in the same RStudio session, the first execution of a line of code causes a minimized history pane to unminimize, but it stays unminimized on subsequent R line executions.
> 
> I'll gladly clarify and/or post a screen cap when I get some time/if needed.

**Comment by tjtnew** [comment] 2020-02-21 11:46
Using a similar pane setup as that in #3084 (i.e. history below source and minimized) but not using python and I get the same unminimizing behaviour if I load a help file from console (e.g. `?ls`).  Other commands to not seem to have an effect.

**Comment by hrbrmstr** [comment] 2020-02-21 15:20
Still happens to me (as does the source pane losing focus on pkg builds, just needed to say that out loud since i've been making more than a few internal pkg of late) but it's gone on long enough that Pane Misbehaviour Stockholm Syndrome has set in and it doesn't cause a "DOH!" reaction anymore. :-)

**Comment by Fred-Wu** [comment] 2020-08-20 03:42
After trying the latest daily build, it seems that the issue is related to bottom left quadrant. As in the 1.4 daily built, all tabsets can be removed from that quadrant. However, even bottom left quadrant has no tabset to display, it still pops up after running python codes.

**Comment by kevinushey** [comment] 2020-08-20 18:40
This is caused by `reticulate` calling `utils::loadhistory()` on each REPL invocation, which causes RStudio to raise and show the History pane in response.

**Comment by gtritchie** [comment] 2020-08-20 21:24
Also note: #5515

**Comment by kevinushey** [comment] 2020-08-26 21:46
I believe this is resolved in the development version of `reticulate`. You can install it via:

```
remotes::install_github("rstudio/reticulate")
```

We'll release a new version of `reticulate` to CRAN within the next couple months with this fix.

**Comment by melissa-barca** [comment] 2020-11-10 23:19
Hey @kevinushey it looks like this still has the same issue as #7621 where the History Pane steals focus with the first python line run and `quit`.

**Closed** 2020-11-13 14:46 UTC
Labels: bug, python

**Comment by melissa-barca** [comment] 2020-11-13 18:21
Verified in 1.4.1028
